/********************************************************************************
** Form generated from reading UI file 'a2.ui'
**
** Created: Tue 10. Dec 18:43:55 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_A2_H
#define UI_A2_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_A2
{
public:
    QLabel *leVoltBU;
    WLabel *leFrec;
    QLabel *leVCET;
    QLabel *leVat_BU;
    WLabel *leAmp_B;
    QLabel *leMV_BT;
    WLabel *leVolt_BC;
    QLabel *leVA_AT;
    QLabel *leVat_BT;
    QLabel *leMV_BU;
    QLabel *leVat_AU;
    QLabel *leMV_TotalU;
    QLabel *leVA_BT;
    QLabel *leVat_CU;
    WLabel *leVA_A;
    QLabel *leVA_TotalesT;
    QLabel *leACET;
    QLabel *leVolt_BCT;
    QLabel *leAmp_CT;
    QLabel *leMV_AU;
    WLabel *leMV_Total;
    QLabel *leMV_CT;
    QLabel *leVolt_ABT;
    WLabel *leMWH;
    QLabel *leFrecBU;
    WLabel *leFP;
    QLabel *leVolt_ABU;
    QLabel *leACEU;
    QLabel *lbCerrado1;
    WLabel *leFrecB;
    QLabel *lb52uT;
    WLabel *leMV_B;
    WLabel *leMV_C;
    WLabel *leVoltB;
    WLabel *leVCE;
    WLabel *leMV_A;
    QLabel *leAmp_BU;
    WLabel *leVolt_AC;
    WLabel *leVA_Totales;
    QLabel *leVolt_ACT;
    QLabel *lb52GT;
    QLabel *leFrecU;
    QLabel *leVA_CU;
    WLabel *leVA_B;
    WLabel *leVat_Total;
    QLabel *leVat_TotalU;
    WLabel *leAmp_C;
    QLabel *leAmp_AT;
    QLabel *leVat_AT;
    WLabel *leVA_C;
    QLabel *leAVRT;
    QLabel *leMVHT;
    QLabel *leVA_AU;
    WLabel *leACE;
    WLabel *leAVR;
    WLabel *leVat_B;
    QLabel *lbCerrado2;
    WLabel *leVolt_AB;
    QLabel *leVolt_ACU;
    WLabel *leAmp_A;
    QLabel *leAmp_CU;
    QLabel *leMV_TotalT;
    QLabel *leVat_TotalT;
    QLabel *leMWHT;
    QLabel *leAmp_BT;
    QLabel *leMWHU;
    QLabel *leVoltBT;
    QLabel *leVA_TotalesU;
    WLabel *leVat_A;
    QLabel *leVat_CT;
    QLabel *leFPT;
    QLabel *leFPU;
    QLabel *lb521T;
    WLabel *leVat_C;
    QLabel *leVCEU;
    QLabel *leMV_CU;
    QLabel *leFrecT;
    WLabel *leMVH;
    QLabel *lb522T;
    QLabel *leMVHU;
    QLabel *leVolt_BCU;
    QLabel *leFrecBT;
    QLabel *lb51GT;
    QLabel *leAmp_AU;
    QLabel *leVA_CT;
    QLabel *leVA_BU;
    QLabel *leMV_AT;
    QLabel *lbBack;
    QLabel *lbUnit3;
    QPushButton *btnIMPPant;
    WLabel *etiqueta;

    void setupUi(QWidget *A2)
    {
        if (A2->objectName().isEmpty())
            A2->setObjectName(QString::fromUtf8("A2"));
        A2->resize(1024, 662);
        A2->setMinimumSize(QSize(1024, 662));
        A2->setMaximumSize(QSize(1024, 662));
        leVoltBU = new QLabel(A2);
        leVoltBU->setObjectName(QString::fromUtf8("leVoltBU"));
        leVoltBU->setGeometry(QRect(288, 50, 50, 21));
        leVoltBU->setMinimumSize(QSize(50, 21));
        leVoltBU->setMaximumSize(QSize(50, 21));
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        leVoltBU->setFont(font);
        leVoltBU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVoltBU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leFrec = new WLabel(A2);
        leFrec->setObjectName(QString::fromUtf8("leFrec"));
        leFrec->setGeometry(QRect(870, 488, 65, 23));
        leFrec->setMinimumSize(QSize(65, 23));
        leFrec->setMaximumSize(QSize(65, 23));
        leFrec->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        QFont font1;
        font1.setPointSize(9);
        leFrec->setFont(font1);
        leVCET = new QLabel(A2);
        leVCET->setObjectName(QString::fromUtf8("leVCET"));
        leVCET->setGeometry(QRect(17, 159, 190, 21));
        leVCET->setFont(font);
        leVCET->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVCET->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVat_BU = new QLabel(A2);
        leVat_BU->setObjectName(QString::fromUtf8("leVat_BU"));
        leVat_BU->setGeometry(QRect(290, 303, 50, 21));
        leVat_BU->setMinimumSize(QSize(50, 21));
        leVat_BU->setMaximumSize(QSize(50, 21));
        leVat_BU->setFont(font);
        leVat_BU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVat_BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leAmp_B = new WLabel(A2);
        leAmp_B->setObjectName(QString::fromUtf8("leAmp_B"));
        leAmp_B->setGeometry(QRect(870, 238, 65, 23));
        leAmp_B->setMinimumSize(QSize(65, 23));
        leAmp_B->setMaximumSize(QSize(65, 23));
        leAmp_B->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leAmp_B->setFont(font1);
        leMV_BT = new QLabel(A2);
        leMV_BT->setObjectName(QString::fromUtf8("leMV_BT"));
        leMV_BT->setGeometry(QRect(17, 421, 191, 21));
        leMV_BT->setMinimumSize(QSize(191, 21));
        leMV_BT->setMaximumSize(QSize(191, 21));
        leMV_BT->setFont(font);
        leMV_BT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMV_BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVolt_BC = new WLabel(A2);
        leVolt_BC->setObjectName(QString::fromUtf8("leVolt_BC"));
        leVolt_BC->setGeometry(QRect(217, 520, 65, 23));
        leVolt_BC->setMinimumSize(QSize(65, 23));
        leVolt_BC->setMaximumSize(QSize(65, 23));
        leVolt_BC->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVolt_BC->setFont(font1);
        leVA_AT = new QLabel(A2);
        leVA_AT->setObjectName(QString::fromUtf8("leVA_AT"));
        leVA_AT->setGeometry(QRect(668, 349, 191, 21));
        leVA_AT->setMinimumSize(QSize(191, 21));
        leVA_AT->setMaximumSize(QSize(191, 21));
        leVA_AT->setFont(font);
        leVA_AT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVA_AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVat_BT = new QLabel(A2);
        leVat_BT->setObjectName(QString::fromUtf8("leVat_BT"));
        leVat_BT->setGeometry(QRect(17, 303, 191, 21));
        leVat_BT->setMinimumSize(QSize(191, 21));
        leVat_BT->setMaximumSize(QSize(191, 21));
        leVat_BT->setFont(font);
        leVat_BT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVat_BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMV_BU = new QLabel(A2);
        leMV_BU->setObjectName(QString::fromUtf8("leMV_BU"));
        leMV_BU->setGeometry(QRect(290, 421, 50, 21));
        leMV_BU->setMinimumSize(QSize(50, 21));
        leMV_BU->setMaximumSize(QSize(50, 21));
        leMV_BU->setFont(font);
        leMV_BU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMV_BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVat_AU = new QLabel(A2);
        leVat_AU->setObjectName(QString::fromUtf8("leVat_AU"));
        leVat_AU->setGeometry(QRect(290, 272, 50, 21));
        leVat_AU->setMinimumSize(QSize(50, 21));
        leVat_AU->setMaximumSize(QSize(50, 21));
        leVat_AU->setFont(font);
        leVat_AU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVat_AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leMV_TotalU = new QLabel(A2);
        leMV_TotalU->setObjectName(QString::fromUtf8("leMV_TotalU"));
        leMV_TotalU->setGeometry(QRect(290, 359, 50, 21));
        leMV_TotalU->setMinimumSize(QSize(50, 21));
        leMV_TotalU->setMaximumSize(QSize(50, 21));
        leMV_TotalU->setFont(font);
        leMV_TotalU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMV_TotalU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVA_BT = new QLabel(A2);
        leVA_BT->setObjectName(QString::fromUtf8("leVA_BT"));
        leVA_BT->setGeometry(QRect(668, 380, 191, 21));
        leVA_BT->setMinimumSize(QSize(191, 21));
        leVA_BT->setMaximumSize(QSize(191, 21));
        leVA_BT->setFont(font);
        leVA_BT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVA_BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVat_CU = new QLabel(A2);
        leVat_CU->setObjectName(QString::fromUtf8("leVat_CU"));
        leVat_CU->setGeometry(QRect(290, 334, 50, 21));
        leVat_CU->setMinimumSize(QSize(50, 21));
        leVat_CU->setMaximumSize(QSize(50, 21));
        leVat_CU->setFont(font);
        leVat_CU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVat_CU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVA_A = new WLabel(A2);
        leVA_A->setObjectName(QString::fromUtf8("leVA_A"));
        leVA_A->setGeometry(QRect(870, 348, 65, 23));
        leVA_A->setMinimumSize(QSize(65, 23));
        leVA_A->setMaximumSize(QSize(65, 23));
        leVA_A->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVA_A->setFont(font1);
        leVA_TotalesT = new QLabel(A2);
        leVA_TotalesT->setObjectName(QString::fromUtf8("leVA_TotalesT"));
        leVA_TotalesT->setGeometry(QRect(668, 318, 191, 21));
        leVA_TotalesT->setMinimumSize(QSize(191, 21));
        leVA_TotalesT->setMaximumSize(QSize(191, 21));
        leVA_TotalesT->setFont(font);
        leVA_TotalesT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVA_TotalesT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leACET = new QLabel(A2);
        leACET->setObjectName(QString::fromUtf8("leACET"));
        leACET->setGeometry(QRect(17, 190, 190, 21));
        leACET->setFont(font);
        leACET->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leACET->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVolt_BCT = new QLabel(A2);
        leVolt_BCT->setObjectName(QString::fromUtf8("leVolt_BCT"));
        leVolt_BCT->setGeometry(QRect(17, 521, 191, 21));
        leVolt_BCT->setMinimumSize(QSize(191, 21));
        leVolt_BCT->setMaximumSize(QSize(191, 21));
        leVolt_BCT->setFont(font);
        leVolt_BCT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVolt_BCT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leAmp_CT = new QLabel(A2);
        leAmp_CT->setObjectName(QString::fromUtf8("leAmp_CT"));
        leAmp_CT->setGeometry(QRect(668, 270, 191, 21));
        leAmp_CT->setMinimumSize(QSize(191, 21));
        leAmp_CT->setMaximumSize(QSize(191, 21));
        leAmp_CT->setFont(font);
        leAmp_CT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leAmp_CT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMV_AU = new QLabel(A2);
        leMV_AU->setObjectName(QString::fromUtf8("leMV_AU"));
        leMV_AU->setGeometry(QRect(290, 390, 50, 21));
        leMV_AU->setMinimumSize(QSize(50, 21));
        leMV_AU->setMaximumSize(QSize(50, 21));
        leMV_AU->setFont(font);
        leMV_AU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMV_AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leMV_Total = new WLabel(A2);
        leMV_Total->setObjectName(QString::fromUtf8("leMV_Total"));
        leMV_Total->setGeometry(QRect(217, 358, 65, 23));
        leMV_Total->setMinimumSize(QSize(65, 23));
        leMV_Total->setMaximumSize(QSize(65, 23));
        leMV_Total->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leMV_Total->setFont(font1);
        leMV_CT = new QLabel(A2);
        leMV_CT->setObjectName(QString::fromUtf8("leMV_CT"));
        leMV_CT->setGeometry(QRect(17, 452, 191, 21));
        leMV_CT->setMinimumSize(QSize(191, 21));
        leMV_CT->setMaximumSize(QSize(191, 21));
        leMV_CT->setFont(font);
        leMV_CT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMV_CT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVolt_ABT = new QLabel(A2);
        leVolt_ABT->setObjectName(QString::fromUtf8("leVolt_ABT"));
        leVolt_ABT->setGeometry(QRect(17, 490, 191, 21));
        leVolt_ABT->setMinimumSize(QSize(191, 21));
        leVolt_ABT->setMaximumSize(QSize(191, 21));
        leVolt_ABT->setFont(font);
        leVolt_ABT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVolt_ABT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMWH = new WLabel(A2);
        leMWH->setObjectName(QString::fromUtf8("leMWH"));
        leMWH->setGeometry(QRect(829, 559, 105, 23));
        leMWH->setMinimumSize(QSize(105, 23));
        leMWH->setMaximumSize(QSize(105, 23));
        leMWH->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leMWH->setFont(font1);
        leFrecBU = new QLabel(A2);
        leFrecBU->setObjectName(QString::fromUtf8("leFrecBU"));
        leFrecBU->setGeometry(QRect(288, 80, 50, 21));
        leFrecBU->setMinimumSize(QSize(50, 21));
        leFrecBU->setMaximumSize(QSize(50, 21));
        leFrecBU->setFont(font);
        leFrecBU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leFrecBU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leFP = new WLabel(A2);
        leFP->setObjectName(QString::fromUtf8("leFP"));
        leFP->setGeometry(QRect(870, 457, 65, 23));
        leFP->setMinimumSize(QSize(65, 23));
        leFP->setMaximumSize(QSize(65, 23));
        leFP->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leFP->setFont(font1);
        leVolt_ABU = new QLabel(A2);
        leVolt_ABU->setObjectName(QString::fromUtf8("leVolt_ABU"));
        leVolt_ABU->setGeometry(QRect(290, 490, 50, 21));
        leVolt_ABU->setMinimumSize(QSize(50, 21));
        leVolt_ABU->setMaximumSize(QSize(50, 21));
        leVolt_ABU->setFont(font);
        leVolt_ABU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVolt_ABU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leACEU = new QLabel(A2);
        leACEU->setObjectName(QString::fromUtf8("leACEU"));
        leACEU->setGeometry(QRect(290, 190, 50, 21));
        leACEU->setMinimumSize(QSize(50, 21));
        leACEU->setMaximumSize(QSize(50, 21));
        leACEU->setFont(font);
        leACEU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leACEU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbCerrado1 = new QLabel(A2);
        lbCerrado1->setObjectName(QString::fromUtf8("lbCerrado1"));
        lbCerrado1->setGeometry(QRect(475, 154, 91, 21));
        lbCerrado1->setMinimumSize(QSize(91, 21));
        lbCerrado1->setMaximumSize(QSize(91, 21));
        QPalette palette;
        QBrush brush(QColor(170, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QBrush brush1(QColor(120, 120, 120, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        lbCerrado1->setPalette(palette);
        lbCerrado1->setFont(font);
        lbCerrado1->setStyleSheet(QString::fromUtf8("background-color: none;"));
        lbCerrado1->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/Extras/A2_abierto.png")));
        lbCerrado1->setScaledContents(true);
        lbCerrado1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leFrecB = new WLabel(A2);
        leFrecB->setObjectName(QString::fromUtf8("leFrecB"));
        leFrecB->setGeometry(QRect(217, 79, 65, 23));
        leFrecB->setMinimumSize(QSize(65, 23));
        leFrecB->setMaximumSize(QSize(65, 23));
        leFrecB->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leFrecB->setFont(font1);
        lb52uT = new QLabel(A2);
        lb52uT->setObjectName(QString::fromUtf8("lb52uT"));
        lb52uT->setGeometry(QRect(360, 160, 101, 31));
        lb52uT->setMinimumSize(QSize(101, 31));
        lb52uT->setMaximumSize(QSize(101, 31));
        lb52uT->setFont(font);
        lb52uT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        lb52uT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMV_B = new WLabel(A2);
        leMV_B->setObjectName(QString::fromUtf8("leMV_B"));
        leMV_B->setGeometry(QRect(217, 420, 65, 23));
        leMV_B->setMinimumSize(QSize(65, 23));
        leMV_B->setMaximumSize(QSize(65, 23));
        leMV_B->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leMV_B->setFont(font1);
        leMV_C = new WLabel(A2);
        leMV_C->setObjectName(QString::fromUtf8("leMV_C"));
        leMV_C->setGeometry(QRect(217, 451, 65, 23));
        leMV_C->setMinimumSize(QSize(65, 23));
        leMV_C->setMaximumSize(QSize(65, 23));
        leMV_C->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leMV_C->setFont(font1);
        leVoltB = new WLabel(A2);
        leVoltB->setObjectName(QString::fromUtf8("leVoltB"));
        leVoltB->setGeometry(QRect(217, 49, 65, 23));
        leVoltB->setMinimumSize(QSize(65, 23));
        leVoltB->setMaximumSize(QSize(65, 23));
        leVoltB->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVoltB->setTipo(-1);
        leVoltB->setValue(-1);
        leVoltB->setFont(font1);
        leVoltB->setProperty("indice", QVariant(-1));
        leVCE = new WLabel(A2);
        leVCE->setObjectName(QString::fromUtf8("leVCE"));
        leVCE->setGeometry(QRect(217, 158, 65, 23));
        leVCE->setMinimumSize(QSize(65, 23));
        leVCE->setMaximumSize(QSize(65, 23));
        leVCE->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVCE->setFont(font1);
        leMV_A = new WLabel(A2);
        leMV_A->setObjectName(QString::fromUtf8("leMV_A"));
        leMV_A->setGeometry(QRect(217, 389, 65, 23));
        leMV_A->setMinimumSize(QSize(65, 23));
        leMV_A->setMaximumSize(QSize(65, 23));
        leMV_A->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leMV_A->setFont(font1);
        leAmp_BU = new QLabel(A2);
        leAmp_BU->setObjectName(QString::fromUtf8("leAmp_BU"));
        leAmp_BU->setGeometry(QRect(940, 239, 50, 21));
        leAmp_BU->setMinimumSize(QSize(50, 21));
        leAmp_BU->setMaximumSize(QSize(50, 21));
        leAmp_BU->setFont(font);
        leAmp_BU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leAmp_BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVolt_AC = new WLabel(A2);
        leVolt_AC->setObjectName(QString::fromUtf8("leVolt_AC"));
        leVolt_AC->setGeometry(QRect(217, 551, 65, 23));
        leVolt_AC->setMinimumSize(QSize(65, 23));
        leVolt_AC->setMaximumSize(QSize(65, 23));
        leVolt_AC->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVolt_AC->setFont(font1);
        leVA_Totales = new WLabel(A2);
        leVA_Totales->setObjectName(QString::fromUtf8("leVA_Totales"));
        leVA_Totales->setGeometry(QRect(870, 317, 65, 23));
        leVA_Totales->setMinimumSize(QSize(65, 23));
        leVA_Totales->setMaximumSize(QSize(65, 23));
        leVA_Totales->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVA_Totales->setFont(font1);
        leVolt_ACT = new QLabel(A2);
        leVolt_ACT->setObjectName(QString::fromUtf8("leVolt_ACT"));
        leVolt_ACT->setGeometry(QRect(17, 552, 191, 21));
        leVolt_ACT->setMinimumSize(QSize(191, 21));
        leVolt_ACT->setMaximumSize(QSize(191, 21));
        leVolt_ACT->setFont(font);
        leVolt_ACT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVolt_ACT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb52GT = new QLabel(A2);
        lb52GT->setObjectName(QString::fromUtf8("lb52GT"));
        lb52GT->setGeometry(QRect(360, 320, 101, 31));
        lb52GT->setMinimumSize(QSize(101, 31));
        lb52GT->setMaximumSize(QSize(101, 31));
        lb52GT->setFont(font);
        lb52GT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        lb52GT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leFrecU = new QLabel(A2);
        leFrecU->setObjectName(QString::fromUtf8("leFrecU"));
        leFrecU->setGeometry(QRect(940, 489, 50, 21));
        leFrecU->setMinimumSize(QSize(50, 21));
        leFrecU->setMaximumSize(QSize(50, 21));
        leFrecU->setFont(font);
        leFrecU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leFrecU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVA_CU = new QLabel(A2);
        leVA_CU->setObjectName(QString::fromUtf8("leVA_CU"));
        leVA_CU->setGeometry(QRect(940, 411, 50, 21));
        leVA_CU->setMinimumSize(QSize(50, 21));
        leVA_CU->setMaximumSize(QSize(50, 21));
        leVA_CU->setFont(font);
        leVA_CU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVA_CU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVA_B = new WLabel(A2);
        leVA_B->setObjectName(QString::fromUtf8("leVA_B"));
        leVA_B->setGeometry(QRect(870, 379, 65, 23));
        leVA_B->setMinimumSize(QSize(65, 23));
        leVA_B->setMaximumSize(QSize(65, 23));
        leVA_B->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVA_B->setFont(font1);
        leVat_Total = new WLabel(A2);
        leVat_Total->setObjectName(QString::fromUtf8("leVat_Total"));
        leVat_Total->setGeometry(QRect(217, 239, 65, 23));
        leVat_Total->setMinimumSize(QSize(65, 23));
        leVat_Total->setMaximumSize(QSize(65, 23));
        leVat_Total->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVat_Total->setFont(font1);
        leVat_TotalU = new QLabel(A2);
        leVat_TotalU->setObjectName(QString::fromUtf8("leVat_TotalU"));
        leVat_TotalU->setGeometry(QRect(290, 241, 50, 21));
        leVat_TotalU->setMinimumSize(QSize(50, 21));
        leVat_TotalU->setMaximumSize(QSize(50, 21));
        leVat_TotalU->setFont(font);
        leVat_TotalU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVat_TotalU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leAmp_C = new WLabel(A2);
        leAmp_C->setObjectName(QString::fromUtf8("leAmp_C"));
        leAmp_C->setGeometry(QRect(870, 269, 65, 23));
        leAmp_C->setMinimumSize(QSize(65, 23));
        leAmp_C->setMaximumSize(QSize(65, 23));
        leAmp_C->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leAmp_C->setFont(font1);
        leAmp_AT = new QLabel(A2);
        leAmp_AT->setObjectName(QString::fromUtf8("leAmp_AT"));
        leAmp_AT->setGeometry(QRect(668, 208, 191, 21));
        leAmp_AT->setMinimumSize(QSize(191, 21));
        leAmp_AT->setMaximumSize(QSize(191, 21));
        leAmp_AT->setFont(font);
        leAmp_AT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leAmp_AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVat_AT = new QLabel(A2);
        leVat_AT->setObjectName(QString::fromUtf8("leVat_AT"));
        leVat_AT->setGeometry(QRect(17, 272, 191, 21));
        leVat_AT->setMinimumSize(QSize(191, 21));
        leVat_AT->setMaximumSize(QSize(191, 21));
        leVat_AT->setFont(font);
        leVat_AT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVat_AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVA_C = new WLabel(A2);
        leVA_C->setObjectName(QString::fromUtf8("leVA_C"));
        leVA_C->setGeometry(QRect(870, 410, 65, 23));
        leVA_C->setMinimumSize(QSize(65, 23));
        leVA_C->setMaximumSize(QSize(65, 23));
        leVA_C->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVA_C->setFont(font1);
        leAVRT = new QLabel(A2);
        leAVRT->setObjectName(QString::fromUtf8("leAVRT"));
        leAVRT->setGeometry(QRect(460, 590, 191, 21));
        leAVRT->setMinimumSize(QSize(191, 21));
        leAVRT->setMaximumSize(QSize(191, 21));
        leAVRT->setFont(font);
        leAVRT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leAVRT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMVHT = new QLabel(A2);
        leMVHT->setObjectName(QString::fromUtf8("leMVHT"));
        leMVHT->setGeometry(QRect(752, 525, 71, 21));
        leMVHT->setFont(font);
        leMVHT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMVHT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVA_AU = new QLabel(A2);
        leVA_AU->setObjectName(QString::fromUtf8("leVA_AU"));
        leVA_AU->setGeometry(QRect(940, 349, 50, 21));
        leVA_AU->setMinimumSize(QSize(50, 21));
        leVA_AU->setMaximumSize(QSize(50, 21));
        leVA_AU->setFont(font);
        leVA_AU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVA_AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leACE = new WLabel(A2);
        leACE->setObjectName(QString::fromUtf8("leACE"));
        leACE->setGeometry(QRect(217, 189, 65, 23));
        leACE->setMinimumSize(QSize(65, 23));
        leACE->setMaximumSize(QSize(65, 23));
        leACE->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leACE->setFont(font1);
        leAVR = new WLabel(A2);
        leAVR->setObjectName(QString::fromUtf8("leAVR"));
        leAVR->setGeometry(QRect(656, 591, 105, 23));
        leAVR->setMinimumSize(QSize(105, 23));
        leAVR->setMaximumSize(QSize(105, 23));
        leAVR->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leAVR->setFont(font1);
        leAVR->setProperty("isUpdateable", QVariant(false));
        leVat_B = new WLabel(A2);
        leVat_B->setObjectName(QString::fromUtf8("leVat_B"));
        leVat_B->setGeometry(QRect(217, 301, 65, 23));
        leVat_B->setMinimumSize(QSize(65, 23));
        leVat_B->setMaximumSize(QSize(65, 23));
        leVat_B->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVat_B->setFont(font1);
        lbCerrado2 = new QLabel(A2);
        lbCerrado2->setObjectName(QString::fromUtf8("lbCerrado2"));
        lbCerrado2->setGeometry(QRect(475, 273, 91, 21));
        lbCerrado2->setMinimumSize(QSize(91, 21));
        lbCerrado2->setMaximumSize(QSize(91, 21));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        lbCerrado2->setPalette(palette1);
        lbCerrado2->setFont(font);
        lbCerrado2->setStyleSheet(QString::fromUtf8("background-color: none;"));
        lbCerrado2->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/Extras/A2_cerrado.png")));
        lbCerrado2->setScaledContents(true);
        lbCerrado2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVolt_AB = new WLabel(A2);
        leVolt_AB->setObjectName(QString::fromUtf8("leVolt_AB"));
        leVolt_AB->setGeometry(QRect(217, 489, 65, 23));
        leVolt_AB->setMinimumSize(QSize(65, 23));
        leVolt_AB->setMaximumSize(QSize(65, 23));
        leVolt_AB->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVolt_AB->setFont(font1);
        leVolt_ACU = new QLabel(A2);
        leVolt_ACU->setObjectName(QString::fromUtf8("leVolt_ACU"));
        leVolt_ACU->setGeometry(QRect(290, 552, 50, 21));
        leVolt_ACU->setMinimumSize(QSize(50, 21));
        leVolt_ACU->setMaximumSize(QSize(50, 21));
        leVolt_ACU->setFont(font);
        leVolt_ACU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVolt_ACU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leAmp_A = new WLabel(A2);
        leAmp_A->setObjectName(QString::fromUtf8("leAmp_A"));
        leAmp_A->setGeometry(QRect(870, 207, 65, 23));
        leAmp_A->setMinimumSize(QSize(65, 23));
        leAmp_A->setMaximumSize(QSize(65, 23));
        leAmp_A->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leAmp_A->setFont(font1);
        leAmp_CU = new QLabel(A2);
        leAmp_CU->setObjectName(QString::fromUtf8("leAmp_CU"));
        leAmp_CU->setGeometry(QRect(940, 270, 50, 21));
        leAmp_CU->setMinimumSize(QSize(50, 21));
        leAmp_CU->setMaximumSize(QSize(50, 21));
        leAmp_CU->setFont(font);
        leAmp_CU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leAmp_CU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leMV_TotalT = new QLabel(A2);
        leMV_TotalT->setObjectName(QString::fromUtf8("leMV_TotalT"));
        leMV_TotalT->setGeometry(QRect(17, 359, 191, 21));
        leMV_TotalT->setMinimumSize(QSize(191, 21));
        leMV_TotalT->setMaximumSize(QSize(191, 21));
        leMV_TotalT->setFont(font);
        leMV_TotalT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMV_TotalT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVat_TotalT = new QLabel(A2);
        leVat_TotalT->setObjectName(QString::fromUtf8("leVat_TotalT"));
        leVat_TotalT->setGeometry(QRect(17, 241, 191, 21));
        leVat_TotalT->setMinimumSize(QSize(191, 21));
        leVat_TotalT->setMaximumSize(QSize(191, 21));
        leVat_TotalT->setFont(font);
        leVat_TotalT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVat_TotalT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMWHT = new QLabel(A2);
        leMWHT->setObjectName(QString::fromUtf8("leMWHT"));
        leMWHT->setGeometry(QRect(632, 560, 191, 21));
        leMWHT->setMinimumSize(QSize(191, 21));
        leMWHT->setMaximumSize(QSize(191, 21));
        leMWHT->setFont(font);
        leMWHT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMWHT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leAmp_BT = new QLabel(A2);
        leAmp_BT->setObjectName(QString::fromUtf8("leAmp_BT"));
        leAmp_BT->setGeometry(QRect(668, 239, 191, 21));
        leAmp_BT->setMinimumSize(QSize(191, 21));
        leAmp_BT->setMaximumSize(QSize(191, 21));
        leAmp_BT->setFont(font);
        leAmp_BT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leAmp_BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMWHU = new QLabel(A2);
        leMWHU->setObjectName(QString::fromUtf8("leMWHU"));
        leMWHU->setGeometry(QRect(940, 560, 91, 21));
        leMWHU->setMinimumSize(QSize(91, 21));
        leMWHU->setMaximumSize(QSize(91, 21));
        leMWHU->setFont(font);
        leMWHU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMWHU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVoltBT = new QLabel(A2);
        leVoltBT->setObjectName(QString::fromUtf8("leVoltBT"));
        leVoltBT->setGeometry(QRect(20, 50, 191, 21));
        leVoltBT->setMinimumSize(QSize(191, 21));
        leVoltBT->setMaximumSize(QSize(191, 21));
        leVoltBT->setFont(font);
        leVoltBT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVoltBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVA_TotalesU = new QLabel(A2);
        leVA_TotalesU->setObjectName(QString::fromUtf8("leVA_TotalesU"));
        leVA_TotalesU->setGeometry(QRect(940, 318, 50, 21));
        leVA_TotalesU->setMinimumSize(QSize(50, 21));
        leVA_TotalesU->setMaximumSize(QSize(50, 21));
        leVA_TotalesU->setFont(font);
        leVA_TotalesU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVA_TotalesU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVat_A = new WLabel(A2);
        leVat_A->setObjectName(QString::fromUtf8("leVat_A"));
        leVat_A->setGeometry(QRect(217, 270, 65, 23));
        leVat_A->setMinimumSize(QSize(65, 23));
        leVat_A->setMaximumSize(QSize(65, 23));
        leVat_A->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVat_A->setFont(font1);
        leVat_CT = new QLabel(A2);
        leVat_CT->setObjectName(QString::fromUtf8("leVat_CT"));
        leVat_CT->setGeometry(QRect(17, 334, 191, 21));
        leVat_CT->setMinimumSize(QSize(191, 21));
        leVat_CT->setMaximumSize(QSize(191, 21));
        leVat_CT->setFont(font);
        leVat_CT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVat_CT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leFPT = new QLabel(A2);
        leFPT->setObjectName(QString::fromUtf8("leFPT"));
        leFPT->setGeometry(QRect(668, 458, 191, 21));
        leFPT->setMinimumSize(QSize(191, 21));
        leFPT->setMaximumSize(QSize(191, 21));
        leFPT->setFont(font);
        leFPT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leFPT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leFPU = new QLabel(A2);
        leFPU->setObjectName(QString::fromUtf8("leFPU"));
        leFPU->setGeometry(QRect(940, 458, 50, 21));
        leFPU->setMinimumSize(QSize(50, 21));
        leFPU->setMaximumSize(QSize(50, 21));
        leFPU->setFont(font);
        leFPU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leFPU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb521T = new QLabel(A2);
        lb521T->setObjectName(QString::fromUtf8("lb521T"));
        lb521T->setGeometry(QRect(360, 180, 101, 31));
        lb521T->setMinimumSize(QSize(101, 31));
        lb521T->setMaximumSize(QSize(101, 31));
        lb521T->setFont(font);
        lb521T->setStyleSheet(QString::fromUtf8("background-color: none;"));
        lb521T->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVat_C = new WLabel(A2);
        leVat_C->setObjectName(QString::fromUtf8("leVat_C"));
        leVat_C->setGeometry(QRect(217, 332, 65, 23));
        leVat_C->setMinimumSize(QSize(65, 23));
        leVat_C->setMaximumSize(QSize(65, 23));
        leVat_C->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leVat_C->setFont(font1);
        leVCEU = new QLabel(A2);
        leVCEU->setObjectName(QString::fromUtf8("leVCEU"));
        leVCEU->setGeometry(QRect(290, 159, 50, 21));
        leVCEU->setMinimumSize(QSize(50, 21));
        leVCEU->setMaximumSize(QSize(50, 21));
        leVCEU->setFont(font);
        leVCEU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVCEU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leMV_CU = new QLabel(A2);
        leMV_CU->setObjectName(QString::fromUtf8("leMV_CU"));
        leMV_CU->setGeometry(QRect(290, 452, 50, 21));
        leMV_CU->setMinimumSize(QSize(50, 21));
        leMV_CU->setMaximumSize(QSize(50, 21));
        leMV_CU->setFont(font);
        leMV_CU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMV_CU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leFrecT = new QLabel(A2);
        leFrecT->setObjectName(QString::fromUtf8("leFrecT"));
        leFrecT->setGeometry(QRect(668, 489, 191, 21));
        leFrecT->setMinimumSize(QSize(191, 21));
        leFrecT->setMaximumSize(QSize(191, 21));
        leFrecT->setFont(font);
        leFrecT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leFrecT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMVH = new WLabel(A2);
        leMVH->setObjectName(QString::fromUtf8("leMVH"));
        leMVH->setGeometry(QRect(829, 524, 105, 23));
        leMVH->setMinimumSize(QSize(105, 23));
        leMVH->setMaximumSize(QSize(105, 23));
        leMVH->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        leMVH->setFont(font1);
        lb522T = new QLabel(A2);
        lb522T->setObjectName(QString::fromUtf8("lb522T"));
        lb522T->setGeometry(QRect(360, 200, 101, 31));
        lb522T->setMinimumSize(QSize(101, 31));
        lb522T->setMaximumSize(QSize(101, 31));
        lb522T->setFont(font);
        lb522T->setStyleSheet(QString::fromUtf8("background-color: none;"));
        lb522T->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leMVHU = new QLabel(A2);
        leMVHU->setObjectName(QString::fromUtf8("leMVHU"));
        leMVHU->setGeometry(QRect(940, 525, 78, 21));
        leMVHU->setFont(font);
        leMVHU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMVHU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVolt_BCU = new QLabel(A2);
        leVolt_BCU->setObjectName(QString::fromUtf8("leVolt_BCU"));
        leVolt_BCU->setGeometry(QRect(290, 521, 50, 21));
        leVolt_BCU->setMinimumSize(QSize(50, 21));
        leVolt_BCU->setMaximumSize(QSize(50, 21));
        leVolt_BCU->setFont(font);
        leVolt_BCU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVolt_BCU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leFrecBT = new QLabel(A2);
        leFrecBT->setObjectName(QString::fromUtf8("leFrecBT"));
        leFrecBT->setGeometry(QRect(20, 80, 191, 21));
        leFrecBT->setMinimumSize(QSize(191, 21));
        leFrecBT->setMaximumSize(QSize(191, 21));
        leFrecBT->setFont(font);
        leFrecBT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leFrecBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb51GT = new QLabel(A2);
        lb51GT->setObjectName(QString::fromUtf8("lb51GT"));
        lb51GT->setGeometry(QRect(360, 340, 101, 31));
        lb51GT->setMinimumSize(QSize(101, 31));
        lb51GT->setMaximumSize(QSize(101, 31));
        lb51GT->setFont(font);
        lb51GT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        lb51GT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leAmp_AU = new QLabel(A2);
        leAmp_AU->setObjectName(QString::fromUtf8("leAmp_AU"));
        leAmp_AU->setGeometry(QRect(940, 208, 50, 21));
        leAmp_AU->setMinimumSize(QSize(50, 21));
        leAmp_AU->setMaximumSize(QSize(50, 21));
        leAmp_AU->setFont(font);
        leAmp_AU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leAmp_AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leVA_CT = new QLabel(A2);
        leVA_CT->setObjectName(QString::fromUtf8("leVA_CT"));
        leVA_CT->setGeometry(QRect(668, 411, 191, 21));
        leVA_CT->setMinimumSize(QSize(191, 21));
        leVA_CT->setMaximumSize(QSize(191, 21));
        leVA_CT->setFont(font);
        leVA_CT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVA_CT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        leVA_BU = new QLabel(A2);
        leVA_BU->setObjectName(QString::fromUtf8("leVA_BU"));
        leVA_BU->setGeometry(QRect(940, 380, 50, 21));
        leVA_BU->setMinimumSize(QSize(50, 21));
        leVA_BU->setMaximumSize(QSize(50, 21));
        leVA_BU->setFont(font);
        leVA_BU->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leVA_BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        leMV_AT = new QLabel(A2);
        leMV_AT->setObjectName(QString::fromUtf8("leMV_AT"));
        leMV_AT->setGeometry(QRect(17, 390, 191, 21));
        leMV_AT->setMinimumSize(QSize(191, 21));
        leMV_AT->setMaximumSize(QSize(191, 21));
        leMV_AT->setFont(font);
        leMV_AT->setStyleSheet(QString::fromUtf8("background-color: none;"));
        leMV_AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbBack = new QLabel(A2);
        lbBack->setObjectName(QString::fromUtf8("lbBack"));
        lbBack->setGeometry(QRect(0, 0, 1024, 662));
        lbBack->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/A2.png")));
        lbBack->setScaledContents(true);
        lbUnit3 = new QLabel(A2);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(833, 647, 190, 15));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        lbUnit3->setFont(font2);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        btnIMPPant = new QPushButton(A2);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(10, 632, 134, 23));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(true);
        font3.setWeight(75);
        btnIMPPant->setFont(font3);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        etiqueta = new WLabel(A2);
        etiqueta->setObjectName(QString::fromUtf8("etiqueta"));
        etiqueta->setGeometry(QRect(410, 50, 321, 16));
        lbBack->raise();
        leVoltBU->raise();
        leFrec->raise();
        leVCET->raise();
        leVat_BU->raise();
        leAmp_B->raise();
        leMV_BT->raise();
        leVolt_BC->raise();
        leVA_AT->raise();
        leVat_BT->raise();
        leMV_BU->raise();
        leVat_AU->raise();
        leMV_TotalU->raise();
        leVA_BT->raise();
        leVat_CU->raise();
        leVA_A->raise();
        leVA_TotalesT->raise();
        leACET->raise();
        leVolt_BCT->raise();
        leAmp_CT->raise();
        leMV_AU->raise();
        leMV_Total->raise();
        leMV_CT->raise();
        leVolt_ABT->raise();
        leMWH->raise();
        leFrecBU->raise();
        leFP->raise();
        leVolt_ABU->raise();
        leACEU->raise();
        lbCerrado1->raise();
        leFrecB->raise();
        lb52uT->raise();
        leMV_B->raise();
        leMV_C->raise();
        leVoltB->raise();
        leVCE->raise();
        leMV_A->raise();
        leAmp_BU->raise();
        leVolt_AC->raise();
        leVA_Totales->raise();
        leVolt_ACT->raise();
        lb52GT->raise();
        leFrecU->raise();
        leVA_CU->raise();
        leVA_B->raise();
        leVat_Total->raise();
        leVat_TotalU->raise();
        leAmp_C->raise();
        leAmp_AT->raise();
        leVat_AT->raise();
        leVA_C->raise();
        leAVRT->raise();
        leMVHT->raise();
        leVA_AU->raise();
        leACE->raise();
        leAVR->raise();
        leVat_B->raise();
        lbCerrado2->raise();
        leVolt_AB->raise();
        leVolt_ACU->raise();
        leAmp_A->raise();
        leAmp_CU->raise();
        leMV_TotalT->raise();
        leVat_TotalT->raise();
        leMWHT->raise();
        leAmp_BT->raise();
        leMWHU->raise();
        leVoltBT->raise();
        leVA_TotalesU->raise();
        leVat_A->raise();
        leVat_CT->raise();
        leFPT->raise();
        leFPU->raise();
        lb521T->raise();
        leVat_C->raise();
        leVCEU->raise();
        leMV_CU->raise();
        leFrecT->raise();
        leMVH->raise();
        lb522T->raise();
        leMVHU->raise();
        leVolt_BCU->raise();
        leFrecBT->raise();
        lb51GT->raise();
        leAmp_AU->raise();
        leVA_CT->raise();
        leVA_BU->raise();
        leMV_AT->raise();
        lbUnit3->raise();
        btnIMPPant->raise();
        etiqueta->raise();

        retranslateUi(A2);

        QMetaObject::connectSlotsByName(A2);
    } // setupUi

    void retranslateUi(QWidget *A2)
    {
        A2->setWindowTitle(QApplication::translate("A2", "Form", 0, QApplication::UnicodeUTF8));
        leVoltBU->setText(QApplication::translate("A2", "KVAC", 0, QApplication::UnicodeUTF8));
        leFrec->setId(QApplication::translate("A2", "p_Fix32_THISNODE_FREQ_F_CV", 0, QApplication::UnicodeUTF8));
        leFrec->setText(QString());
        leVCET->setText(QApplication::translate("A2", "VOLTAJE CAMPO EXCITADOR", 0, QApplication::UnicodeUTF8));
        leVat_BU->setText(QApplication::translate("A2", "MW", 0, QApplication::UnicodeUTF8));
        leAmp_B->setId(QApplication::translate("A2", "p_Fix32_THISNODE_BUS_VLTS2_F_CV", 0, QApplication::UnicodeUTF8));
        leAmp_B->setText(QString());
        leMV_BT->setText(QApplication::translate("A2", "MVARS B", 0, QApplication::UnicodeUTF8));
        leVolt_BC->setId(QApplication::translate("A2", "p_Fix32_THISNODE_VOLT_BC_F_CV", 0, QApplication::UnicodeUTF8));
        leVolt_BC->setText(QString());
        leVA_AT->setText(QApplication::translate("A2", "VOLTIOS AMPS FASE A", 0, QApplication::UnicodeUTF8));
        leVat_BT->setText(QApplication::translate("A2", "VATIOS FASE B", 0, QApplication::UnicodeUTF8));
        leMV_BU->setText(QApplication::translate("A2", "MVAR", 0, QApplication::UnicodeUTF8));
        leVat_AU->setText(QApplication::translate("A2", "MW", 0, QApplication::UnicodeUTF8));
        leMV_TotalU->setText(QApplication::translate("A2", "MVAR", 0, QApplication::UnicodeUTF8));
        leVA_BT->setText(QApplication::translate("A2", "VOLTIOS AMPS FASE B", 0, QApplication::UnicodeUTF8));
        leVat_CU->setText(QApplication::translate("A2", "MW", 0, QApplication::UnicodeUTF8));
        leVA_A->setId(QApplication::translate("A2", "p_Fix32_THISNODE_AMPS_A_F_CV", 0, QApplication::UnicodeUTF8));
        leVA_A->setText(QString());
        leVA_TotalesT->setText(QApplication::translate("A2", "VOLTIOS AMPS TOTAL", 0, QApplication::UnicodeUTF8));
        leACET->setText(QApplication::translate("A2", "AMP DEL CAMPO EXCITADOR", 0, QApplication::UnicodeUTF8));
        leVolt_BCT->setText(QApplication::translate("A2", "VOLTAJE FASES B-C", 0, QApplication::UnicodeUTF8));
        leAmp_CT->setText(QApplication::translate("A2", "AMPS FASE C", 0, QApplication::UnicodeUTF8));
        leMV_AU->setText(QApplication::translate("A2", "MVAR", 0, QApplication::UnicodeUTF8));
        leMV_Total->setId(QApplication::translate("A2", "p_Fix32_THISNODE_MVAR_F_CV", 0, QApplication::UnicodeUTF8));
        leMV_Total->setText(QString());
        leMV_CT->setText(QApplication::translate("A2", "MVARS C", 0, QApplication::UnicodeUTF8));
        leVolt_ABT->setText(QApplication::translate("A2", "VOLTAJE FASES A-B", 0, QApplication::UnicodeUTF8));
        leMWH->setId(QApplication::translate("A2", "p_Fix32_THISNODE_MWHRSHI_F_CV", 0, QApplication::UnicodeUTF8));
        leMWH->setText(QString());
        leFrecBU->setText(QApplication::translate("A2", "HZ", 0, QApplication::UnicodeUTF8));
        leFP->setId(QApplication::translate("A2", "p_Fix32_THISNODE_PF_F_CV", 0, QApplication::UnicodeUTF8));
        leFP->setText(QString());
        leVolt_ABU->setText(QApplication::translate("A2", "KV", 0, QApplication::UnicodeUTF8));
        leACEU->setText(QApplication::translate("A2", "ADC", 0, QApplication::UnicodeUTF8));
        lbCerrado1->setText(QString());
        leFrecB->setId(QApplication::translate("A2", "p_Fix32_THISNODE_BFX_F_CV ", 0, QApplication::UnicodeUTF8));
        leFrecB->setText(QString());
        lb52uT->setText(QApplication::translate("A2", "52U", 0, QApplication::UnicodeUTF8));
        leMV_B->setId(QApplication::translate("A2", "p_Fix32_THISNODE_VARS_B_F_CV", 0, QApplication::UnicodeUTF8));
        leMV_B->setText(QString());
        leMV_C->setId(QApplication::translate("A2", "p_Fix32_THISNODE_VARS_C_F_CV", 0, QApplication::UnicodeUTF8));
        leMV_C->setText(QString());
        leVoltB->setId(QApplication::translate("A2", "p_Fix32_THISNODE_BVX_F_CV", 0, QApplication::UnicodeUTF8));
        leVoltB->setText(QString());
        leVCE->setId(QApplication::translate("A2", "p_Fix32_THISNODE_EXCIT_VLTS_F_CV", 0, QApplication::UnicodeUTF8));
        leVCE->setText(QString());
        leMV_A->setId(QApplication::translate("A2", "p_Fix32_THISNODE_VARS_A_F_CV", 0, QApplication::UnicodeUTF8));
        leMV_A->setText(QString());
        leAmp_BU->setText(QApplication::translate("A2", "AMPS", 0, QApplication::UnicodeUTF8));
        leVolt_AC->setId(QApplication::translate("A2", "p_Fix32_THISNODE_VOLT_AC_F_CV", 0, QApplication::UnicodeUTF8));
        leVolt_AC->setText(QString());
        leVA_Totales->setId(QApplication::translate("A2", "p_Fix32_THISNODE_BUS_FREQ2_F_CV", 0, QApplication::UnicodeUTF8));
        leVA_Totales->setText(QString());
        leVolt_ACT->setText(QApplication::translate("A2", "VOLTAJE FASES A-C", 0, QApplication::UnicodeUTF8));
        lb52GT->setText(QApplication::translate("A2", "52G", 0, QApplication::UnicodeUTF8));
        leFrecU->setText(QApplication::translate("A2", "HZ", 0, QApplication::UnicodeUTF8));
        leVA_CU->setText(QApplication::translate("A2", "MVA", 0, QApplication::UnicodeUTF8));
        leVA_B->setId(QApplication::translate("A2", "p_Fix32_THISNODE_AMPS_B_F_CV", 0, QApplication::UnicodeUTF8));
        leVA_B->setText(QString());
        leVat_Total->setId(QApplication::translate("A2", "p_Fix32_THISNODE_MW_INPUT_F_CV", 0, QApplication::UnicodeUTF8));
        leVat_Total->setText(QString());
        leVat_TotalU->setText(QApplication::translate("A2", "MW", 0, QApplication::UnicodeUTF8));
        leAmp_C->setId(QApplication::translate("A2", "p_Fix32_THISNODE_BUS_FREQ1_F_CV", 0, QApplication::UnicodeUTF8));
        leAmp_C->setText(QString());
        leAmp_AT->setText(QApplication::translate("A2", "AMPS FASE A", 0, QApplication::UnicodeUTF8));
        leVat_AT->setText(QApplication::translate("A2", "VATIOS FASE A", 0, QApplication::UnicodeUTF8));
        leVA_C->setId(QApplication::translate("A2", "p_Fix32_THISNODE_AMPS_C_F_CV", 0, QApplication::UnicodeUTF8));
        leVA_C->setText(QString());
        leAVRT->setText(QApplication::translate("A2", "MODO AVR:", 0, QApplication::UnicodeUTF8));
        leMVHT->setText(QApplication::translate("A2", "MVAR-HRS", 0, QApplication::UnicodeUTF8));
        leVA_AU->setText(QApplication::translate("A2", "MVA", 0, QApplication::UnicodeUTF8));
        leACE->setId(QApplication::translate("A2", "p_Fix32_THISNODE_EXCIT_AMPS_F_CV", 0, QApplication::UnicodeUTF8));
        leACE->setText(QString());
        leAVR->setId(QApplication::translate("A2", "p_Fix32_THISNODE_AVRINAUTO_F_CV", 0, QApplication::UnicodeUTF8));
        leAVR->setText(QString());
        leVat_B->setId(QApplication::translate("A2", "p_Fix32_THISNODE_WATTS_B_F_CV", 0, QApplication::UnicodeUTF8));
        leVat_B->setText(QString());
        lbCerrado2->setText(QString());
        leVolt_AB->setId(QApplication::translate("A2", "p_Fix32_THISNODE_VOLT_AB_F_CV", 0, QApplication::UnicodeUTF8));
        leVolt_AB->setText(QString());
        leVolt_ACU->setText(QApplication::translate("A2", "KV", 0, QApplication::UnicodeUTF8));
        leAmp_A->setId(QApplication::translate("A2", "p_Fix32_THISNODE_BUS_VLTS1_F_CV", 0, QApplication::UnicodeUTF8));
        leAmp_A->setText(QString());
        leAmp_CU->setText(QApplication::translate("A2", "AMPS", 0, QApplication::UnicodeUTF8));
        leMV_TotalT->setText(QApplication::translate("A2", "TOTAL DE VAR", 0, QApplication::UnicodeUTF8));
        leVat_TotalT->setText(QApplication::translate("A2", "VATIOS TOTALES", 0, QApplication::UnicodeUTF8));
        leMWHT->setText(QApplication::translate("A2", "MW-HRS", 0, QApplication::UnicodeUTF8));
        leAmp_BT->setText(QApplication::translate("A2", "AMPS FASE B", 0, QApplication::UnicodeUTF8));
        leMWHU->setText(QApplication::translate("A2", "MW-HRS", 0, QApplication::UnicodeUTF8));
        leVoltBT->setText(QApplication::translate("A2", "VOLTAJE DE BUS", 0, QApplication::UnicodeUTF8));
        leVA_TotalesU->setText(QApplication::translate("A2", "MVA", 0, QApplication::UnicodeUTF8));
        leVat_A->setId(QApplication::translate("A2", "p_Fix32_THISNODE_WATTS_A_F_CV", 0, QApplication::UnicodeUTF8));
        leVat_A->setText(QString());
        leVat_CT->setText(QApplication::translate("A2", "VATIOS FASE C", 0, QApplication::UnicodeUTF8));
        leFPT->setText(QApplication::translate("A2", "FACTOR DE POTENCIA", 0, QApplication::UnicodeUTF8));
        leFPU->setText(QApplication::translate("A2", "PF", 0, QApplication::UnicodeUTF8));
        lb521T->setText(QApplication::translate("A2", "52-1 T21A/", 0, QApplication::UnicodeUTF8));
        leVat_C->setId(QApplication::translate("A2", "p_Fix32_THISNODE_WATTS_C_F_CV", 0, QApplication::UnicodeUTF8));
        leVat_C->setText(QString());
        leVCEU->setText(QApplication::translate("A2", "VDC", 0, QApplication::UnicodeUTF8));
        leMV_CU->setText(QApplication::translate("A2", "MVAR", 0, QApplication::UnicodeUTF8));
        leFrecT->setText(QApplication::translate("A2", "FRECUENCIA", 0, QApplication::UnicodeUTF8));
        leMVH->setId(QApplication::translate("A2", "p_Fix32_THISNODE_VARHRSHI_F_CV", 0, QApplication::UnicodeUTF8));
        leMVH->setText(QString());
        lb522T->setText(QApplication::translate("A2", "52-2 T21A/", 0, QApplication::UnicodeUTF8));
        leMVHU->setText(QApplication::translate("A2", "MVAR-HRS", 0, QApplication::UnicodeUTF8));
        leVolt_BCU->setText(QApplication::translate("A2", "KV", 0, QApplication::UnicodeUTF8));
        leFrecBT->setText(QApplication::translate("A2", "FRECUENCIA DE BUS", 0, QApplication::UnicodeUTF8));
        lb51GT->setText(QApplication::translate("A2", "51G1", 0, QApplication::UnicodeUTF8));
        leAmp_AU->setText(QApplication::translate("A2", "AMPS", 0, QApplication::UnicodeUTF8));
        leVA_CT->setText(QApplication::translate("A2", "VOLTIOS AMPS FASE C", 0, QApplication::UnicodeUTF8));
        leVA_BU->setText(QApplication::translate("A2", "MVA", 0, QApplication::UnicodeUTF8));
        leMV_AT->setText(QApplication::translate("A2", "MVARS A", 0, QApplication::UnicodeUTF8));
        lbBack->setText(QString());
        lbUnit3->setText(QApplication::translate("A2", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("A2", "IMP PANT", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class A2: public Ui_A2 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_A2_H
