/********************************************************************************
** Form generated from reading UI file 'a5.ui'
**
** Created: Thu 19. Dec 14:36:09 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_A5_H
#define UI_A5_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "awmultiobject.h"

QT_BEGIN_NAMESPACE

class Ui_A5
{
public:
    QLabel *lbIMGFondo;
    QFrame *frame_7;
    QLabel *lbTexto_2;
    QFrame *frTitulo_9;
    QLabel *lbTexto_1;
    AWMultiObject *aLet_1;
    QLabel *lbTexto_3;
    AWMultiObject *aLet_2;
    AWMultiObject *aLet_3;
    QLabel *lbTexto_4;
    QLabel *lbTexto_5;
    AWMultiObject *aLet_4;
    QLabel *lbTexto_6;
    AWMultiObject *aLet_5;
    AWMultiObject *aLet_6;
    QLabel *lbTexto_7;
    AWMultiObject *aLet_7;
    QLabel *lbTexto_8;
    AWMultiObject *aLet_8;
    QLabel *lbTexto_9;
    AWMultiObject *aLet_9;
    QLabel *lbTexto_10;
    QLabel *lbTexto_11;
    AWMultiObject *aLet_10;
    AWMultiObject *aLet_11;
    QLabel *lbTexto_12;
    AWMultiObject *aLet_12;
    QLabel *lbTexto_13;
    AWMultiObject *aLet_13;
    QLabel *lbTexto_14;
    AWMultiObject *aLet_14;
    QLabel *lbTexto_15;
    AWMultiObject *aLet_15;
    QLabel *lbTexto_16;
    QFrame *frTitulo_10;
    QLabel *lbTexto_17;
    AWMultiObject *aLet_16;
    QLabel *lbTexto_18;
    AWMultiObject *aLet_17;
    QLabel *lbTexto_19;
    AWMultiObject *aLet_18;
    QLabel *lbTexto_20;
    QLabel *lbTexto_21;
    AWMultiObject *aLet_19;
    AWMultiObject *aLet_20;
    QLabel *lbTexto_22;
    QLabel *lbTexto_23;
    AWMultiObject *aLet_21;
    AWMultiObject *aLet_22;
    QLabel *lbTexto_24;
    QLabel *lbTexto_25;
    AWMultiObject *aLet_23;
    QLabel *lbTexto_26;
    AWMultiObject *aLet_24;
    QLabel *lbTextoT;
    QLabel *lbUnit3;
    QPushButton *btnIMPPant;
    QFrame *frame_8;
    QLabel *lbTexto_51;
    QFrame *frTitulo_13;
    QLabel *lbTexto_52;
    AWMultiObject *aLet_47;
    QLabel *lbTexto_53;
    AWMultiObject *aLet_48;
    AWMultiObject *aLet_49;
    QLabel *lbTexto_54;
    QLabel *lbTexto_55;
    AWMultiObject *aLet_50;
    QLabel *lbTexto_56;
    AWMultiObject *aLet_51;
    AWMultiObject *aLet_52;
    QLabel *lbTexto_57;
    AWMultiObject *aLet_53;
    QLabel *lbTexto_58;
    AWMultiObject *aLet_54;
    QLabel *lbTexto_59;
    AWMultiObject *aLet_55;
    QLabel *lbTexto_60;
    QLabel *lbTexto_61;
    AWMultiObject *aLet_56;
    AWMultiObject *aLet_57;
    QLabel *lbTexto_62;
    AWMultiObject *aLet_58;
    QLabel *lbTexto_63;
    AWMultiObject *aLet_59;
    QLabel *lbTexto_64;
    AWMultiObject *aLet_60;
    QLabel *lbTexto_65;
    AWMultiObject *aLet_61;
    QLabel *lbTexto_66;
    AWMultiObject *aLet_62;
    QLabel *lbTexto_68;
    AWMultiObject *aLet_63;
    QLabel *lbTexto_69;
    AWMultiObject *aLet_64;
    QLabel *lbTexto_70;
    QLabel *lbTexto_71;
    AWMultiObject *aLet_65;
    QFrame *frTitulo_20;
    QLabel *lbTexto_67;
    QFrame *frTitulo_21;
    QLabel *lbTexto_77;
    QFrame *frTitulo_22;
    QLabel *lbTexto_79;

    void setupUi(QWidget *A5)
    {
        if (A5->objectName().isEmpty())
            A5->setObjectName(QString::fromUtf8("A5"));
        A5->resize(1024, 662);
        A5->setMinimumSize(QSize(1024, 662));
        A5->setMaximumSize(QSize(1024, 662));
        A5->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbIMGFondo = new QLabel(A5);
        lbIMGFondo->setObjectName(QString::fromUtf8("lbIMGFondo"));
        lbIMGFondo->setGeometry(QRect(0, 0, 1024, 662));
        lbIMGFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/BackGround.png")));
        lbIMGFondo->setScaledContents(true);
        frame_7 = new QFrame(A5);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(170, 80, 345, 541));
        frame_7->setStyleSheet(QString::fromUtf8("background-color: none;"));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Plain);
        frame_7->setMidLineWidth(0);
        lbTexto_2 = new QLabel(frame_7);
        lbTexto_2->setObjectName(QString::fromUtf8("lbTexto_2"));
        lbTexto_2->setGeometry(QRect(48, 30, 281, 21));
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        lbTexto_2->setFont(font);
        lbTexto_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frTitulo_9 = new QFrame(frame_7);
        frTitulo_9->setObjectName(QString::fromUtf8("frTitulo_9"));
        frTitulo_9->setGeometry(QRect(1, 2, 339, 22));
        frTitulo_9->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_9->setFrameShape(QFrame::WinPanel);
        frTitulo_9->setFrameShadow(QFrame::Raised);
        frTitulo_9->setLineWidth(2);
        frTitulo_9->setMidLineWidth(0);
        lbTexto_1 = new QLabel(frTitulo_9);
        lbTexto_1->setObjectName(QString::fromUtf8("lbTexto_1"));
        lbTexto_1->setGeometry(QRect(18, 0, 311, 21));
        QFont font1;
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        lbTexto_1->setFont(font1);
        lbTexto_1->setStyleSheet(QString::fromUtf8("background-color: rgba(185, 138, 255, 0);"));
        lbTexto_1->setAlignment(Qt::AlignCenter);
        aLet_1 = new AWMultiObject(frame_7);
        aLet_1->setObjectName(QString::fromUtf8("aLet_1"));
        aLet_1->setGeometry(QRect(18, 29, 26, 26));
        aLet_1->setElementType(AWMultiObject::CIRLED);
        aLet_1->setOnColor(AWMultiObject::Grey);
        aLet_1->setOffColor(AWMultiObject::Green);
        lbTexto_3 = new QLabel(frame_7);
        lbTexto_3->setObjectName(QString::fromUtf8("lbTexto_3"));
        lbTexto_3->setGeometry(QRect(48, 50, 281, 21));
        lbTexto_3->setFont(font);
        lbTexto_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_2 = new AWMultiObject(frame_7);
        aLet_2->setObjectName(QString::fromUtf8("aLet_2"));
        aLet_2->setGeometry(QRect(18, 50, 26, 26));
        aLet_2->setElementType(AWMultiObject::CIRLED);
        aLet_2->setOnColor(AWMultiObject::Grey);
        aLet_2->setOffColor(AWMultiObject::Green);
        aLet_3 = new AWMultiObject(frame_7);
        aLet_3->setObjectName(QString::fromUtf8("aLet_3"));
        aLet_3->setGeometry(QRect(18, 70, 26, 26));
        aLet_3->setElementType(AWMultiObject::CIRLED);
        aLet_3->setOnColor(AWMultiObject::Grey);
        aLet_3->setOffColor(AWMultiObject::Green);
        lbTexto_4 = new QLabel(frame_7);
        lbTexto_4->setObjectName(QString::fromUtf8("lbTexto_4"));
        lbTexto_4->setGeometry(QRect(48, 69, 281, 21));
        lbTexto_4->setFont(font);
        lbTexto_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_5 = new QLabel(frame_7);
        lbTexto_5->setObjectName(QString::fromUtf8("lbTexto_5"));
        lbTexto_5->setGeometry(QRect(48, 89, 281, 21));
        lbTexto_5->setFont(font);
        lbTexto_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_4 = new AWMultiObject(frame_7);
        aLet_4->setObjectName(QString::fromUtf8("aLet_4"));
        aLet_4->setGeometry(QRect(18, 88, 26, 26));
        aLet_4->setElementType(AWMultiObject::CIRLED);
        aLet_4->setOnColor(AWMultiObject::Grey);
        aLet_4->setOffColor(AWMultiObject::Green);
        lbTexto_6 = new QLabel(frame_7);
        lbTexto_6->setObjectName(QString::fromUtf8("lbTexto_6"));
        lbTexto_6->setGeometry(QRect(48, 108, 281, 21));
        lbTexto_6->setFont(font);
        lbTexto_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_5 = new AWMultiObject(frame_7);
        aLet_5->setObjectName(QString::fromUtf8("aLet_5"));
        aLet_5->setGeometry(QRect(18, 107, 26, 26));
        aLet_5->setElementType(AWMultiObject::CIRLED);
        aLet_5->setOnColor(AWMultiObject::Grey);
        aLet_5->setOffColor(AWMultiObject::Green);
        aLet_6 = new AWMultiObject(frame_7);
        aLet_6->setObjectName(QString::fromUtf8("aLet_6"));
        aLet_6->setGeometry(QRect(18, 126, 26, 26));
        aLet_6->setElementType(AWMultiObject::CIRLED);
        aLet_6->setOnColor(AWMultiObject::Grey);
        aLet_6->setOffColor(AWMultiObject::Green);
        lbTexto_7 = new QLabel(frame_7);
        lbTexto_7->setObjectName(QString::fromUtf8("lbTexto_7"));
        lbTexto_7->setGeometry(QRect(48, 127, 281, 21));
        lbTexto_7->setFont(font);
        lbTexto_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_7 = new AWMultiObject(frame_7);
        aLet_7->setObjectName(QString::fromUtf8("aLet_7"));
        aLet_7->setGeometry(QRect(18, 145, 26, 26));
        aLet_7->setElementType(AWMultiObject::CIRLED);
        aLet_7->setOnColor(AWMultiObject::Grey);
        aLet_7->setOffColor(AWMultiObject::Green);
        lbTexto_8 = new QLabel(frame_7);
        lbTexto_8->setObjectName(QString::fromUtf8("lbTexto_8"));
        lbTexto_8->setGeometry(QRect(48, 146, 281, 21));
        lbTexto_8->setFont(font);
        lbTexto_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_8 = new AWMultiObject(frame_7);
        aLet_8->setObjectName(QString::fromUtf8("aLet_8"));
        aLet_8->setGeometry(QRect(18, 165, 26, 26));
        aLet_8->setElementType(AWMultiObject::CIRLED);
        aLet_8->setOnColor(AWMultiObject::Grey);
        aLet_8->setOffColor(AWMultiObject::Green);
        lbTexto_9 = new QLabel(frame_7);
        lbTexto_9->setObjectName(QString::fromUtf8("lbTexto_9"));
        lbTexto_9->setGeometry(QRect(50, 165, 281, 21));
        lbTexto_9->setFont(font);
        lbTexto_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_9 = new AWMultiObject(frame_7);
        aLet_9->setObjectName(QString::fromUtf8("aLet_9"));
        aLet_9->setGeometry(QRect(18, 185, 26, 26));
        aLet_9->setElementType(AWMultiObject::CIRLED);
        aLet_9->setOnColor(AWMultiObject::Grey);
        aLet_9->setOffColor(AWMultiObject::Green);
        lbTexto_10 = new QLabel(frame_7);
        lbTexto_10->setObjectName(QString::fromUtf8("lbTexto_10"));
        lbTexto_10->setGeometry(QRect(50, 185, 281, 21));
        lbTexto_10->setFont(font);
        lbTexto_10->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_11 = new QLabel(frame_7);
        lbTexto_11->setObjectName(QString::fromUtf8("lbTexto_11"));
        lbTexto_11->setGeometry(QRect(50, 203, 281, 21));
        lbTexto_11->setFont(font);
        lbTexto_11->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_10 = new AWMultiObject(frame_7);
        aLet_10->setObjectName(QString::fromUtf8("aLet_10"));
        aLet_10->setGeometry(QRect(18, 203, 26, 26));
        aLet_10->setElementType(AWMultiObject::CIRLED);
        aLet_10->setOnColor(AWMultiObject::Grey);
        aLet_10->setOffColor(AWMultiObject::Green);
        aLet_11 = new AWMultiObject(frame_7);
        aLet_11->setObjectName(QString::fromUtf8("aLet_11"));
        aLet_11->setGeometry(QRect(18, 223, 26, 26));
        aLet_11->setElementType(AWMultiObject::CIRLED);
        aLet_11->setOnColor(AWMultiObject::Grey);
        aLet_11->setOffColor(AWMultiObject::Green);
        lbTexto_12 = new QLabel(frame_7);
        lbTexto_12->setObjectName(QString::fromUtf8("lbTexto_12"));
        lbTexto_12->setGeometry(QRect(50, 224, 281, 21));
        lbTexto_12->setFont(font);
        lbTexto_12->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_12 = new AWMultiObject(frame_7);
        aLet_12->setObjectName(QString::fromUtf8("aLet_12"));
        aLet_12->setGeometry(QRect(18, 240, 26, 26));
        aLet_12->setElementType(AWMultiObject::CIRLED);
        aLet_12->setOnColor(AWMultiObject::Grey);
        aLet_12->setOffColor(AWMultiObject::Green);
        lbTexto_13 = new QLabel(frame_7);
        lbTexto_13->setObjectName(QString::fromUtf8("lbTexto_13"));
        lbTexto_13->setGeometry(QRect(50, 242, 281, 21));
        lbTexto_13->setFont(font);
        lbTexto_13->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_13 = new AWMultiObject(frame_7);
        aLet_13->setObjectName(QString::fromUtf8("aLet_13"));
        aLet_13->setGeometry(QRect(18, 260, 26, 26));
        aLet_13->setElementType(AWMultiObject::CIRLED);
        aLet_13->setOnColor(AWMultiObject::Grey);
        aLet_13->setOffColor(AWMultiObject::Green);
        lbTexto_14 = new QLabel(frame_7);
        lbTexto_14->setObjectName(QString::fromUtf8("lbTexto_14"));
        lbTexto_14->setGeometry(QRect(50, 262, 281, 21));
        lbTexto_14->setFont(font);
        lbTexto_14->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_14 = new AWMultiObject(frame_7);
        aLet_14->setObjectName(QString::fromUtf8("aLet_14"));
        aLet_14->setGeometry(QRect(18, 280, 26, 26));
        aLet_14->setElementType(AWMultiObject::CIRLED);
        aLet_14->setOnColor(AWMultiObject::Grey);
        aLet_14->setOffColor(AWMultiObject::Green);
        lbTexto_15 = new QLabel(frame_7);
        lbTexto_15->setObjectName(QString::fromUtf8("lbTexto_15"));
        lbTexto_15->setGeometry(QRect(50, 282, 281, 21));
        lbTexto_15->setFont(font);
        lbTexto_15->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_15 = new AWMultiObject(frame_7);
        aLet_15->setObjectName(QString::fromUtf8("aLet_15"));
        aLet_15->setGeometry(QRect(18, 300, 26, 26));
        aLet_15->setElementType(AWMultiObject::CIRLED);
        aLet_15->setOnColor(AWMultiObject::Grey);
        aLet_15->setOffColor(AWMultiObject::Green);
        lbTexto_16 = new QLabel(frame_7);
        lbTexto_16->setObjectName(QString::fromUtf8("lbTexto_16"));
        lbTexto_16->setGeometry(QRect(50, 300, 281, 21));
        lbTexto_16->setFont(font);
        lbTexto_16->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frTitulo_10 = new QFrame(frame_7);
        frTitulo_10->setObjectName(QString::fromUtf8("frTitulo_10"));
        frTitulo_10->setGeometry(QRect(1, 355, 339, 22));
        frTitulo_10->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_10->setFrameShape(QFrame::WinPanel);
        frTitulo_10->setFrameShadow(QFrame::Raised);
        frTitulo_10->setLineWidth(2);
        frTitulo_10->setMidLineWidth(0);
        lbTexto_17 = new QLabel(frTitulo_10);
        lbTexto_17->setObjectName(QString::fromUtf8("lbTexto_17"));
        lbTexto_17->setGeometry(QRect(18, 0, 311, 21));
        lbTexto_17->setFont(font1);
        lbTexto_17->setStyleSheet(QString::fromUtf8("background-color: rgba(185, 138, 255, 0);"));
        lbTexto_17->setAlignment(Qt::AlignCenter);
        aLet_16 = new AWMultiObject(frame_7);
        aLet_16->setObjectName(QString::fromUtf8("aLet_16"));
        aLet_16->setGeometry(QRect(18, 378, 26, 26));
        aLet_16->setElementType(AWMultiObject::CIRLED);
        aLet_16->setOnColor(AWMultiObject::Grey);
        aLet_16->setOffColor(AWMultiObject::Green);
        lbTexto_18 = new QLabel(frame_7);
        lbTexto_18->setObjectName(QString::fromUtf8("lbTexto_18"));
        lbTexto_18->setGeometry(QRect(50, 380, 281, 21));
        lbTexto_18->setFont(font);
        lbTexto_18->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_17 = new AWMultiObject(frame_7);
        aLet_17->setObjectName(QString::fromUtf8("aLet_17"));
        aLet_17->setGeometry(QRect(18, 398, 26, 26));
        aLet_17->setElementType(AWMultiObject::CIRLED);
        aLet_17->setOnColor(AWMultiObject::Grey);
        aLet_17->setOffColor(AWMultiObject::Green);
        lbTexto_19 = new QLabel(frame_7);
        lbTexto_19->setObjectName(QString::fromUtf8("lbTexto_19"));
        lbTexto_19->setGeometry(QRect(50, 398, 281, 21));
        lbTexto_19->setFont(font);
        lbTexto_19->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_18 = new AWMultiObject(frame_7);
        aLet_18->setObjectName(QString::fromUtf8("aLet_18"));
        aLet_18->setGeometry(QRect(18, 418, 26, 26));
        aLet_18->setElementType(AWMultiObject::CIRLED);
        aLet_18->setOnColor(AWMultiObject::Grey);
        aLet_18->setOffColor(AWMultiObject::Green);
        lbTexto_20 = new QLabel(frame_7);
        lbTexto_20->setObjectName(QString::fromUtf8("lbTexto_20"));
        lbTexto_20->setGeometry(QRect(50, 418, 281, 21));
        lbTexto_20->setFont(font);
        lbTexto_20->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_21 = new QLabel(frame_7);
        lbTexto_21->setObjectName(QString::fromUtf8("lbTexto_21"));
        lbTexto_21->setGeometry(QRect(50, 437, 281, 21));
        lbTexto_21->setFont(font);
        lbTexto_21->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_19 = new AWMultiObject(frame_7);
        aLet_19->setObjectName(QString::fromUtf8("aLet_19"));
        aLet_19->setGeometry(QRect(18, 437, 26, 26));
        aLet_19->setElementType(AWMultiObject::CIRLED);
        aLet_19->setOnColor(AWMultiObject::Grey);
        aLet_19->setOffColor(AWMultiObject::Green);
        aLet_20 = new AWMultiObject(frame_7);
        aLet_20->setObjectName(QString::fromUtf8("aLet_20"));
        aLet_20->setGeometry(QRect(18, 456, 26, 26));
        aLet_20->setElementType(AWMultiObject::CIRLED);
        aLet_20->setOnColor(AWMultiObject::Grey);
        aLet_20->setOffColor(AWMultiObject::Green);
        lbTexto_22 = new QLabel(frame_7);
        lbTexto_22->setObjectName(QString::fromUtf8("lbTexto_22"));
        lbTexto_22->setGeometry(QRect(50, 457, 281, 21));
        lbTexto_22->setFont(font);
        lbTexto_22->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_23 = new QLabel(frame_7);
        lbTexto_23->setObjectName(QString::fromUtf8("lbTexto_23"));
        lbTexto_23->setGeometry(QRect(50, 476, 281, 21));
        lbTexto_23->setFont(font);
        lbTexto_23->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_21 = new AWMultiObject(frame_7);
        aLet_21->setObjectName(QString::fromUtf8("aLet_21"));
        aLet_21->setGeometry(QRect(18, 475, 26, 26));
        aLet_21->setElementType(AWMultiObject::CIRLED);
        aLet_21->setOnColor(AWMultiObject::Grey);
        aLet_21->setOffColor(AWMultiObject::Green);
        aLet_22 = new AWMultiObject(frame_7);
        aLet_22->setObjectName(QString::fromUtf8("aLet_22"));
        aLet_22->setGeometry(QRect(18, 495, 26, 26));
        aLet_22->setElementType(AWMultiObject::CIRLED);
        aLet_22->setOnColor(AWMultiObject::Grey);
        aLet_22->setOffColor(AWMultiObject::Green);
        lbTexto_24 = new QLabel(frame_7);
        lbTexto_24->setObjectName(QString::fromUtf8("lbTexto_24"));
        lbTexto_24->setGeometry(QRect(50, 494, 281, 21));
        lbTexto_24->setFont(font);
        lbTexto_24->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_25 = new QLabel(frame_7);
        lbTexto_25->setObjectName(QString::fromUtf8("lbTexto_25"));
        lbTexto_25->setGeometry(QRect(50, 513, 281, 21));
        lbTexto_25->setFont(font);
        lbTexto_25->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_23 = new AWMultiObject(frame_7);
        aLet_23->setObjectName(QString::fromUtf8("aLet_23"));
        aLet_23->setGeometry(QRect(18, 513, 26, 26));
        aLet_23->setElementType(AWMultiObject::CIRLED);
        aLet_23->setOnColor(AWMultiObject::Grey);
        aLet_23->setOffColor(AWMultiObject::Green);
        lbTexto_26 = new QLabel(frame_7);
        lbTexto_26->setObjectName(QString::fromUtf8("lbTexto_26"));
        lbTexto_26->setGeometry(QRect(50, 320, 281, 21));
        lbTexto_26->setFont(font);
        lbTexto_26->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_24 = new AWMultiObject(frame_7);
        aLet_24->setObjectName(QString::fromUtf8("aLet_24"));
        aLet_24->setGeometry(QRect(18, 320, 26, 26));
        aLet_24->setElementType(AWMultiObject::CIRLED);
        aLet_24->setOnColor(AWMultiObject::Grey);
        aLet_24->setOffColor(AWMultiObject::Green);
        lbTextoT = new QLabel(A5);
        lbTextoT->setObjectName(QString::fromUtf8("lbTextoT"));
        lbTextoT->setGeometry(QRect(371, 50, 281, 21));
        QPalette palette;
        QBrush brush(QColor(0, 0, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 0, 0));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        QBrush brush2(QColor(120, 120, 120, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        lbTextoT->setPalette(palette);
        QFont font2;
        font2.setPointSize(11);
        font2.setBold(true);
        font2.setWeight(75);
        lbTextoT->setFont(font2);
        lbTextoT->setStyleSheet(QString::fromUtf8("background-color: rgba(0, 0, 0, 0);"));
        lbUnit3 = new QLabel(A5);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(835, 647, 190, 15));
        QFont font3;
        font3.setBold(true);
        font3.setWeight(75);
        lbUnit3->setFont(font3);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        btnIMPPant = new QPushButton(A5);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(8, 638, 134, 21));
        QFont font4;
        font4.setPointSize(8);
        font4.setBold(true);
        font4.setWeight(75);
        btnIMPPant->setFont(font4);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        frame_8 = new QFrame(A5);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(513, 80, 345, 541));
        frame_8->setStyleSheet(QString::fromUtf8("background-color: none;"));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Plain);
        frame_8->setMidLineWidth(0);
        lbTexto_51 = new QLabel(frame_8);
        lbTexto_51->setObjectName(QString::fromUtf8("lbTexto_51"));
        lbTexto_51->setGeometry(QRect(48, 30, 281, 21));
        lbTexto_51->setFont(font);
        lbTexto_51->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frTitulo_13 = new QFrame(frame_8);
        frTitulo_13->setObjectName(QString::fromUtf8("frTitulo_13"));
        frTitulo_13->setGeometry(QRect(1, 2, 339, 22));
        frTitulo_13->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_13->setFrameShape(QFrame::WinPanel);
        frTitulo_13->setFrameShadow(QFrame::Raised);
        frTitulo_13->setLineWidth(2);
        frTitulo_13->setMidLineWidth(0);
        lbTexto_52 = new QLabel(frTitulo_13);
        lbTexto_52->setObjectName(QString::fromUtf8("lbTexto_52"));
        lbTexto_52->setGeometry(QRect(18, 0, 311, 21));
        lbTexto_52->setFont(font1);
        lbTexto_52->setStyleSheet(QString::fromUtf8("background-color: rgba(185, 138, 255, 0);"));
        lbTexto_52->setAlignment(Qt::AlignCenter);
        aLet_47 = new AWMultiObject(frame_8);
        aLet_47->setObjectName(QString::fromUtf8("aLet_47"));
        aLet_47->setGeometry(QRect(18, 29, 26, 26));
        aLet_47->setElementType(AWMultiObject::CIRLED);
        aLet_47->setOnColor(AWMultiObject::Grey);
        aLet_47->setOffColor(AWMultiObject::Green);
        lbTexto_53 = new QLabel(frame_8);
        lbTexto_53->setObjectName(QString::fromUtf8("lbTexto_53"));
        lbTexto_53->setGeometry(QRect(48, 50, 281, 21));
        lbTexto_53->setFont(font);
        lbTexto_53->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_48 = new AWMultiObject(frame_8);
        aLet_48->setObjectName(QString::fromUtf8("aLet_48"));
        aLet_48->setGeometry(QRect(18, 50, 26, 26));
        aLet_48->setElementType(AWMultiObject::CIRLED);
        aLet_48->setOnColor(AWMultiObject::Grey);
        aLet_48->setOffColor(AWMultiObject::Green);
        aLet_49 = new AWMultiObject(frame_8);
        aLet_49->setObjectName(QString::fromUtf8("aLet_49"));
        aLet_49->setGeometry(QRect(18, 70, 26, 26));
        aLet_49->setElementType(AWMultiObject::CIRLED);
        aLet_49->setOnColor(AWMultiObject::Grey);
        aLet_49->setOffColor(AWMultiObject::Green);
        lbTexto_54 = new QLabel(frame_8);
        lbTexto_54->setObjectName(QString::fromUtf8("lbTexto_54"));
        lbTexto_54->setGeometry(QRect(48, 69, 281, 21));
        lbTexto_54->setFont(font);
        lbTexto_54->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_55 = new QLabel(frame_8);
        lbTexto_55->setObjectName(QString::fromUtf8("lbTexto_55"));
        lbTexto_55->setGeometry(QRect(48, 89, 281, 21));
        lbTexto_55->setFont(font);
        lbTexto_55->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_50 = new AWMultiObject(frame_8);
        aLet_50->setObjectName(QString::fromUtf8("aLet_50"));
        aLet_50->setGeometry(QRect(18, 88, 26, 26));
        aLet_50->setElementType(AWMultiObject::CIRLED);
        aLet_50->setOnColor(AWMultiObject::Grey);
        aLet_50->setOffColor(AWMultiObject::Green);
        lbTexto_56 = new QLabel(frame_8);
        lbTexto_56->setObjectName(QString::fromUtf8("lbTexto_56"));
        lbTexto_56->setGeometry(QRect(48, 108, 281, 21));
        lbTexto_56->setFont(font);
        lbTexto_56->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_51 = new AWMultiObject(frame_8);
        aLet_51->setObjectName(QString::fromUtf8("aLet_51"));
        aLet_51->setGeometry(QRect(18, 107, 26, 26));
        aLet_51->setElementType(AWMultiObject::CIRLED);
        aLet_51->setOnColor(AWMultiObject::Grey);
        aLet_51->setOffColor(AWMultiObject::Green);
        aLet_52 = new AWMultiObject(frame_8);
        aLet_52->setObjectName(QString::fromUtf8("aLet_52"));
        aLet_52->setGeometry(QRect(18, 162, 26, 26));
        aLet_52->setElementType(AWMultiObject::CIRLED);
        aLet_52->setOnColor(AWMultiObject::Grey);
        aLet_52->setOffColor(AWMultiObject::Green);
        lbTexto_57 = new QLabel(frame_8);
        lbTexto_57->setObjectName(QString::fromUtf8("lbTexto_57"));
        lbTexto_57->setGeometry(QRect(48, 164, 281, 21));
        lbTexto_57->setFont(font);
        lbTexto_57->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_53 = new AWMultiObject(frame_8);
        aLet_53->setObjectName(QString::fromUtf8("aLet_53"));
        aLet_53->setGeometry(QRect(18, 180, 26, 26));
        aLet_53->setElementType(AWMultiObject::CIRLED);
        aLet_53->setOnColor(AWMultiObject::Grey);
        aLet_53->setOffColor(AWMultiObject::Green);
        lbTexto_58 = new QLabel(frame_8);
        lbTexto_58->setObjectName(QString::fromUtf8("lbTexto_58"));
        lbTexto_58->setGeometry(QRect(48, 183, 281, 21));
        lbTexto_58->setFont(font);
        lbTexto_58->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_54 = new AWMultiObject(frame_8);
        aLet_54->setObjectName(QString::fromUtf8("aLet_54"));
        aLet_54->setGeometry(QRect(18, 198, 26, 26));
        aLet_54->setElementType(AWMultiObject::CIRLED);
        aLet_54->setOnColor(AWMultiObject::Grey);
        aLet_54->setOffColor(AWMultiObject::Green);
        lbTexto_59 = new QLabel(frame_8);
        lbTexto_59->setObjectName(QString::fromUtf8("lbTexto_59"));
        lbTexto_59->setGeometry(QRect(50, 201, 281, 21));
        lbTexto_59->setFont(font);
        lbTexto_59->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_55 = new AWMultiObject(frame_8);
        aLet_55->setObjectName(QString::fromUtf8("aLet_55"));
        aLet_55->setGeometry(QRect(18, 262, 26, 26));
        aLet_55->setElementType(AWMultiObject::CIRLED);
        aLet_55->setOnColor(AWMultiObject::Grey);
        aLet_55->setOffColor(AWMultiObject::Green);
        lbTexto_60 = new QLabel(frame_8);
        lbTexto_60->setObjectName(QString::fromUtf8("lbTexto_60"));
        lbTexto_60->setGeometry(QRect(50, 263, 281, 21));
        lbTexto_60->setFont(font);
        lbTexto_60->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_61 = new QLabel(frame_8);
        lbTexto_61->setObjectName(QString::fromUtf8("lbTexto_61"));
        lbTexto_61->setGeometry(QRect(50, 282, 281, 21));
        lbTexto_61->setFont(font);
        lbTexto_61->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_56 = new AWMultiObject(frame_8);
        aLet_56->setObjectName(QString::fromUtf8("aLet_56"));
        aLet_56->setGeometry(QRect(18, 280, 26, 26));
        aLet_56->setElementType(AWMultiObject::CIRLED);
        aLet_56->setOnColor(AWMultiObject::Grey);
        aLet_56->setOffColor(AWMultiObject::Green);
        aLet_57 = new AWMultiObject(frame_8);
        aLet_57->setObjectName(QString::fromUtf8("aLet_57"));
        aLet_57->setGeometry(QRect(18, 298, 26, 26));
        aLet_57->setElementType(AWMultiObject::CIRLED);
        aLet_57->setOnColor(AWMultiObject::Grey);
        aLet_57->setOffColor(AWMultiObject::Green);
        lbTexto_62 = new QLabel(frame_8);
        lbTexto_62->setObjectName(QString::fromUtf8("lbTexto_62"));
        lbTexto_62->setGeometry(QRect(50, 300, 281, 21));
        lbTexto_62->setFont(font);
        lbTexto_62->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_58 = new AWMultiObject(frame_8);
        aLet_58->setObjectName(QString::fromUtf8("aLet_58"));
        aLet_58->setGeometry(QRect(18, 316, 26, 26));
        aLet_58->setElementType(AWMultiObject::CIRLED);
        aLet_58->setOnColor(AWMultiObject::Grey);
        aLet_58->setOffColor(AWMultiObject::Green);
        lbTexto_63 = new QLabel(frame_8);
        lbTexto_63->setObjectName(QString::fromUtf8("lbTexto_63"));
        lbTexto_63->setGeometry(QRect(50, 318, 281, 21));
        lbTexto_63->setFont(font);
        lbTexto_63->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_59 = new AWMultiObject(frame_8);
        aLet_59->setObjectName(QString::fromUtf8("aLet_59"));
        aLet_59->setGeometry(QRect(18, 380, 26, 26));
        aLet_59->setElementType(AWMultiObject::CIRLED);
        aLet_59->setOnColor(AWMultiObject::Grey);
        aLet_59->setOffColor(AWMultiObject::Green);
        lbTexto_64 = new QLabel(frame_8);
        lbTexto_64->setObjectName(QString::fromUtf8("lbTexto_64"));
        lbTexto_64->setGeometry(QRect(50, 380, 281, 21));
        lbTexto_64->setFont(font);
        lbTexto_64->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_60 = new AWMultiObject(frame_8);
        aLet_60->setObjectName(QString::fromUtf8("aLet_60"));
        aLet_60->setGeometry(QRect(18, 400, 26, 26));
        aLet_60->setElementType(AWMultiObject::CIRLED);
        aLet_60->setOnColor(AWMultiObject::Grey);
        aLet_60->setOffColor(AWMultiObject::Green);
        lbTexto_65 = new QLabel(frame_8);
        lbTexto_65->setObjectName(QString::fromUtf8("lbTexto_65"));
        lbTexto_65->setGeometry(QRect(50, 400, 281, 21));
        lbTexto_65->setFont(font);
        lbTexto_65->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_61 = new AWMultiObject(frame_8);
        aLet_61->setObjectName(QString::fromUtf8("aLet_61"));
        aLet_61->setGeometry(QRect(18, 420, 26, 26));
        aLet_61->setElementType(AWMultiObject::CIRLED);
        aLet_61->setOnColor(AWMultiObject::Grey);
        aLet_61->setOffColor(AWMultiObject::Green);
        lbTexto_66 = new QLabel(frame_8);
        lbTexto_66->setObjectName(QString::fromUtf8("lbTexto_66"));
        lbTexto_66->setGeometry(QRect(50, 420, 281, 21));
        lbTexto_66->setFont(font);
        lbTexto_66->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_62 = new AWMultiObject(frame_8);
        aLet_62->setObjectName(QString::fromUtf8("aLet_62"));
        aLet_62->setGeometry(QRect(18, 438, 26, 26));
        aLet_62->setElementType(AWMultiObject::CIRLED);
        aLet_62->setOnColor(AWMultiObject::Grey);
        aLet_62->setOffColor(AWMultiObject::Green);
        lbTexto_68 = new QLabel(frame_8);
        lbTexto_68->setObjectName(QString::fromUtf8("lbTexto_68"));
        lbTexto_68->setGeometry(QRect(50, 440, 281, 21));
        lbTexto_68->setFont(font);
        lbTexto_68->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_63 = new AWMultiObject(frame_8);
        aLet_63->setObjectName(QString::fromUtf8("aLet_63"));
        aLet_63->setGeometry(QRect(18, 456, 26, 26));
        aLet_63->setElementType(AWMultiObject::CIRLED);
        aLet_63->setOnColor(AWMultiObject::Grey);
        aLet_63->setOffColor(AWMultiObject::Green);
        lbTexto_69 = new QLabel(frame_8);
        lbTexto_69->setObjectName(QString::fromUtf8("lbTexto_69"));
        lbTexto_69->setGeometry(QRect(50, 458, 281, 21));
        lbTexto_69->setFont(font);
        lbTexto_69->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_64 = new AWMultiObject(frame_8);
        aLet_64->setObjectName(QString::fromUtf8("aLet_64"));
        aLet_64->setGeometry(QRect(18, 475, 26, 26));
        aLet_64->setElementType(AWMultiObject::CIRLED);
        aLet_64->setOnColor(AWMultiObject::Grey);
        aLet_64->setOffColor(AWMultiObject::Green);
        lbTexto_70 = new QLabel(frame_8);
        lbTexto_70->setObjectName(QString::fromUtf8("lbTexto_70"));
        lbTexto_70->setGeometry(QRect(50, 476, 281, 21));
        lbTexto_70->setFont(font);
        lbTexto_70->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_71 = new QLabel(frame_8);
        lbTexto_71->setObjectName(QString::fromUtf8("lbTexto_71"));
        lbTexto_71->setGeometry(QRect(50, 495, 281, 21));
        lbTexto_71->setFont(font);
        lbTexto_71->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_65 = new AWMultiObject(frame_8);
        aLet_65->setObjectName(QString::fromUtf8("aLet_65"));
        aLet_65->setGeometry(QRect(18, 495, 26, 26));
        aLet_65->setElementType(AWMultiObject::CIRLED);
        aLet_65->setOnColor(AWMultiObject::Grey);
        aLet_65->setOffColor(AWMultiObject::Green);
        frTitulo_20 = new QFrame(frame_8);
        frTitulo_20->setObjectName(QString::fromUtf8("frTitulo_20"));
        frTitulo_20->setGeometry(QRect(1, 140, 339, 22));
        frTitulo_20->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_20->setFrameShape(QFrame::WinPanel);
        frTitulo_20->setFrameShadow(QFrame::Raised);
        frTitulo_20->setLineWidth(2);
        frTitulo_20->setMidLineWidth(0);
        lbTexto_67 = new QLabel(frTitulo_20);
        lbTexto_67->setObjectName(QString::fromUtf8("lbTexto_67"));
        lbTexto_67->setGeometry(QRect(10, 0, 311, 21));
        lbTexto_67->setFont(font1);
        lbTexto_67->setStyleSheet(QString::fromUtf8("background-color: rgba(185, 138, 255, 0);"));
        lbTexto_67->setAlignment(Qt::AlignCenter);
        frTitulo_21 = new QFrame(frame_8);
        frTitulo_21->setObjectName(QString::fromUtf8("frTitulo_21"));
        frTitulo_21->setGeometry(QRect(1, 243, 339, 22));
        frTitulo_21->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_21->setFrameShape(QFrame::WinPanel);
        frTitulo_21->setFrameShadow(QFrame::Raised);
        frTitulo_21->setLineWidth(2);
        frTitulo_21->setMidLineWidth(0);
        lbTexto_77 = new QLabel(frTitulo_21);
        lbTexto_77->setObjectName(QString::fromUtf8("lbTexto_77"));
        lbTexto_77->setGeometry(QRect(20, 0, 311, 21));
        lbTexto_77->setFont(font1);
        lbTexto_77->setStyleSheet(QString::fromUtf8("background-color: rgba(185, 138, 255, 0);"));
        lbTexto_77->setAlignment(Qt::AlignCenter);
        frTitulo_22 = new QFrame(frame_8);
        frTitulo_22->setObjectName(QString::fromUtf8("frTitulo_22"));
        frTitulo_22->setGeometry(QRect(1, 353, 339, 22));
        frTitulo_22->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_22->setFrameShape(QFrame::WinPanel);
        frTitulo_22->setFrameShadow(QFrame::Raised);
        frTitulo_22->setLineWidth(2);
        frTitulo_22->setMidLineWidth(0);
        lbTexto_79 = new QLabel(frTitulo_22);
        lbTexto_79->setObjectName(QString::fromUtf8("lbTexto_79"));
        lbTexto_79->setGeometry(QRect(20, 0, 311, 21));
        lbTexto_79->setFont(font1);
        lbTexto_79->setStyleSheet(QString::fromUtf8("background-color: rgba(185, 138, 255, 0);"));
        lbTexto_79->setAlignment(Qt::AlignCenter);

        retranslateUi(A5);

        QMetaObject::connectSlotsByName(A5);
    } // setupUi

    void retranslateUi(QWidget *A5)
    {
        A5->setWindowTitle(QApplication::translate("A5", "Form", 0, QApplication::UnicodeUTF8));
        lbIMGFondo->setText(QString());
        lbTexto_2->setText(QApplication::translate("A5", "SIN APAGADOS", 0, QApplication::UnicodeUTF8));
        lbTexto_1->setText(QApplication::translate("A5", "UNIDAD", 0, QApplication::UnicodeUTF8));
        aLet_1->setId(QApplication::translate("A5", "p_Fix32_THISNODE_NO_SHTDNS", 0, QApplication::UnicodeUTF8));
        lbTexto_3->setText(QApplication::translate("A5", "BLOQUEO CUATRO HORAS NO ACTIVO", 0, QApplication::UnicodeUTF8));
        aLet_2->setId(QApplication::translate("A5", "p_Fix32_THISNODE_LOK_4HROFF", 0, QApplication::UnicodeUTF8));
        aLet_3->setId(QApplication::translate("A5", "p_Fix32_THISNODE_CAL_MODE", 0, QApplication::UnicodeUTF8));
        lbTexto_4->setText(QApplication::translate("A5", "NO ES MODO DE CALIBRACI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_5->setText(QApplication::translate("A5", "TEMP ACEITE LUB TURBINA OK", 0, QApplication::UnicodeUTF8));
        aLet_4->setId(QApplication::translate("A5", "p_Fix32_THISNODE_TLUB_OK", 0, QApplication::UnicodeUTF8));
        lbTexto_6->setText(QApplication::translate("A5", "NIVEL TANQUE TURBINA OK", 0, QApplication::UnicodeUTF8));
        aLet_5->setId(QApplication::translate("A5", "p_Fix32_THISNODE_TLO_TNKLVL", 0, QApplication::UnicodeUTF8));
        aLet_6->setId(QApplication::translate("A5", "p_Fix32_THISNODE_HYD_ST_OK", 0, QApplication::UnicodeUTF8));
        lbTexto_7->setText(QApplication::translate("A5", "ARRANCADOR - HID OK", 0, QApplication::UnicodeUTF8));
        aLet_7->setId(QApplication::translate("A5", "p_Fix32_THISNODE_GLUBTNKTMP", 0, QApplication::UnicodeUTF8));
        lbTexto_8->setText(QApplication::translate("A5", "TEMP ACEITE LUB GEN OK ", 0, QApplication::UnicodeUTF8));
        aLet_8->setId(QApplication::translate("A5", "p_Fix32_THISNODE_BO_MANUAL", 0, QApplication::UnicodeUTF8));
        lbTexto_9->setText(QApplication::translate("A5", "CONTROL MANUAL DO DESHABILITADO", 0, QApplication::UnicodeUTF8));
        aLet_9->setId(QApplication::translate("A5", "p_Fix32_THISNODE_STATOR_PRM", 0, QApplication::UnicodeUTF8));
        lbTexto_10->setText(QApplication::translate("A5", "TEMP ESTATOR OK", 0, QApplication::UnicodeUTF8));
        lbTexto_11->setText(QApplication::translate("A5", "PRES DESEMPA\303\221ADOR GEN/GB OK", 0, QApplication::UnicodeUTF8));
        aLet_10->setId(QApplication::translate("A5", "p_Fix32_THISNODE_PSH6089_OK", 0, QApplication::UnicodeUTF8));
        aLet_11->setId(QApplication::translate("A5", "p_Fix32_THISNODE_FANS_OK", 0, QApplication::UnicodeUTF8));
        lbTexto_12->setText(QApplication::translate("A5", "TODO LOS VENT OK P/FUNC", 0, QApplication::UnicodeUTF8));
        aLet_12->setId(QApplication::translate("A5", "p_Fix32_THISNODE_WW_NOTACTIVE", 0, QApplication::UnicodeUTF8));
        lbTexto_13->setText(QApplication::translate("A5", "LAVADO AGUA FUERA DE L\303\215NEA NO ACTIVO", 0, QApplication::UnicodeUTF8));
        aLet_13->setId(QApplication::translate("A5", "p_Fix32_THISNODE_CUST_STRTPERM", 0, QApplication::UnicodeUTF8));
        lbTexto_14->setText(QApplication::translate("A5", "PERMISOS ARRANQUE CLIENTE", 0, QApplication::UnicodeUTF8));
        aLet_14->setId(QApplication::translate("A5", "p_Fix32_THISNODE_GLUBTNKLVL", 0, QApplication::UnicodeUTF8));
        lbTexto_15->setText(QApplication::translate("A5", "CANAL 2 N4N52", 0, QApplication::UnicodeUTF8));
        aLet_15->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OFF_RUN", 0, QApplication::UnicodeUTF8));
        lbTexto_16->setText(QApplication::translate("A5", "APAGADO/FUNCIONANDO", 0, QApplication::UnicodeUTF8));
        lbTexto_17->setText(QApplication::translate("A5", "OK P/ARRANQUE DESDE N\303\232CLEO", 0, QApplication::UnicodeUTF8));
        aLet_16->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START01", 0, QApplication::UnicodeUTF8));
        lbTexto_18->setText(QApplication::translate("A5", "4 T48 SENSORES NO FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_17->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START02", 0, QApplication::UnicodeUTF8));
        lbTexto_19->setText(QApplication::translate("A5", "3 T48 SENSORES ADYACENTES NO FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_18->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START03", 0, QApplication::UnicodeUTF8));
        lbTexto_20->setText(QApplication::translate("A5", "RETROALIMENTACIONES TBV NO FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_21->setText(QApplication::translate("A5", "ERROR GRAVE DE POSICI\303\223N TBV NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_19->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START04", 0, QApplication::UnicodeUTF8));
        aLet_20->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START05", 0, QApplication::UnicodeUTF8));
        lbTexto_22->setText(QApplication::translate("A5", "MOTOR TORQUE TBV NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        lbTexto_23->setText(QApplication::translate("A5", "CAMBIO NULO TBV NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_21->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START06", 0, QApplication::UnicodeUTF8));
        aLet_22->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START07", 0, QApplication::UnicodeUTF8));
        lbTexto_24->setText(QApplication::translate("A5", "RETROALIMENTACIONES CDP NO FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_25->setText(QApplication::translate("A5", "ERROR GRAVE DE POSICI\303\223N CDP NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_23->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START08", 0, QApplication::UnicodeUTF8));
        lbTexto_26->setText(QApplication::translate("A5", "LIBRE", 0, QApplication::UnicodeUTF8));
        aLet_24->setId(QApplication::translate("A5", "p_Fix32_THISNODE_GLUBTMP_OK", 0, QApplication::UnicodeUTF8));
        lbTextoT->setText(QApplication::translate("A5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#05fa05;\">UNIDAD LISTO PARA ARRANCAR</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("A5", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("A5", "IMP PANT", 0, QApplication::UnicodeUTF8));
        lbTexto_51->setText(QApplication::translate("A5", "IMPULS COMB OK", 0, QApplication::UnicodeUTF8));
        lbTexto_52->setText(QApplication::translate("A5", "SISTEMA DE COMBUSTIBLE", 0, QApplication::UnicodeUTF8));
        aLet_47->setId(QApplication::translate("A5", "p_Fix32_THISNODE_FUELDVR_OK", 0, QApplication::UnicodeUTF8));
        lbTexto_53->setText(QApplication::translate("A5", "V\303\201LV COMB EN ALTO MIN", 0, QApplication::UnicodeUTF8));
        aLet_48->setId(QApplication::translate("A5", "p_Fix32_THISNODE_VMIN_STOP", 0, QApplication::UnicodeUTF8));
        aLet_49->setId(QApplication::translate("A5", "p_Fix32_THISNODE_FUELPRSOK", 0, QApplication::UnicodeUTF8));
        lbTexto_54->setText(QApplication::translate("A5", "PRESI\303\223N DE COMB GAS OK", 0, QApplication::UnicodeUTF8));
        lbTexto_55->setText(QApplication::translate("A5", "SIST DE COMB LISTO", 0, QApplication::UnicodeUTF8));
        aLet_50->setId(QApplication::translate("A5", "p_Fix32_THISNODE_FUELSYSOK", 0, QApplication::UnicodeUTF8));
        lbTexto_56->setText(QApplication::translate("A5", "VALVS SUMINISTRO CERRADO VENTEO ABIERTO", 0, QApplication::UnicodeUTF8));
        aLet_51->setId(QApplication::translate("A5", "p_Fix32_THISNODE_SOV_CLSD", 0, QApplication::UnicodeUTF8));
        aLet_52->setId(QApplication::translate("A5", "p_Fix32_THISNODE_MNET_OK", 0, QApplication::UnicodeUTF8));
        lbTexto_57->setText(QApplication::translate("A5", "HARDWARE MICRONET OK", 0, QApplication::UnicodeUTF8));
        aLet_53->setId(QApplication::translate("A5", "p_Fix32_THISNODE_LH_OK", 0, QApplication::UnicodeUTF8));
        lbTexto_58->setText(QApplication::translate("A5", "HARDWARE LINKNET OK", 0, QApplication::UnicodeUTF8));
        aLet_54->setId(QApplication::translate("A5", "p_Fix32_THISNODE_VIB_SYS_OK", 0, QApplication::UnicodeUTF8));
        lbTexto_59->setText(QApplication::translate("A5", "SISTEMA DE VIBRACIONES OK", 0, QApplication::UnicodeUTF8));
        aLet_55->setId(QApplication::translate("A5", "p_Fix32_THISNODE_XN25MINPOS", 0, QApplication::UnicodeUTF8));
        lbTexto_60->setText(QApplication::translate("A5", "REF EN MIN N25", 0, QApplication::UnicodeUTF8));
        lbTexto_61->setText(QApplication::translate("A5", "NDS EN POSICI\303\223N D/SINC", 0, QApplication::UnicodeUTF8));
        aLet_56->setId(QApplication::translate("A5", "p_Fix32_THISNODE_NPTSYNCPOS", 0, QApplication::UnicodeUTF8));
        aLet_57->setId(QApplication::translate("A5", "p_Fix32_THISNODE_T48_LT400", 0, QApplication::UnicodeUTF8));
        lbTexto_62->setText(QApplication::translate("A5", "T48 MENOS DE 400", 0, QApplication::UnicodeUTF8));
        aLet_58->setId(QApplication::translate("A5", "p_Fix32_THISNODE_N25LT300", 0, QApplication::UnicodeUTF8));
        lbTexto_63->setText(QApplication::translate("A5", "MENOS DE 300 RPM N25", 0, QApplication::UnicodeUTF8));
        aLet_59->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START09", 0, QApplication::UnicodeUTF8));
        lbTexto_64->setText(QApplication::translate("A5", "MOTOR TORQUE CDP NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_60->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START10", 0, QApplication::UnicodeUTF8));
        lbTexto_65->setText(QApplication::translate("A5", "CAMBIO NULO CDP NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_61->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START11", 0, QApplication::UnicodeUTF8));
        lbTexto_66->setText(QApplication::translate("A5", "RETROALIMENTACIONES ST8 NO FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_62->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START12", 0, QApplication::UnicodeUTF8));
        lbTexto_68->setText(QApplication::translate("A5", "ERROR GRAVE DE POSICI\303\223N ST8 NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_63->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START13", 0, QApplication::UnicodeUTF8));
        lbTexto_69->setText(QApplication::translate("A5", "MOTOR TORQUE ST8 NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_64->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START14", 0, QApplication::UnicodeUTF8));
        lbTexto_70->setText(QApplication::translate("A5", "CAMBIO NULO ST8 NO FALL\303\223", 0, QApplication::UnicodeUTF8));
        lbTexto_71->setText(QApplication::translate("A5", "RETROAL VBV NO HAY GRAN DIFERENCIA", 0, QApplication::UnicodeUTF8));
        aLet_65->setId(QApplication::translate("A5", "p_Fix32_THISNODE_OK2START15", 0, QApplication::UnicodeUTF8));
        lbTexto_67->setText(QApplication::translate("A5", "EQUIPO DEL SISTEMA DE CONTROL OK", 0, QApplication::UnicodeUTF8));
        lbTexto_77->setText(QApplication::translate("A5", "TURBINA", 0, QApplication::UnicodeUTF8));
        lbTexto_79->setText(QApplication::translate("A5", "OK P/ARRANQUE DESDE N\303\232CLEO", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class A5: public Ui_A5 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_A5_H
