/********************************************************************************
** Form generated from reading UI file 'analog16_3.ui'
**
** Created: Tue 17. Dec 13:46:50 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ANALOG16_3_H
#define UI_ANALOG16_3_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_Analog16_3
{
public:
    WLabel *lbNum_6;
    WLabel *lbNumDes_10;
    WLabel *lbNumDes_5;
    WLabel *lbUni_12;
    WLabel *lbUni_7;
    WLabel *lbNum_5;
    WLabel *lbTit_3;
    QFrame *frame;
    WLabel *label_2;
    QFrame *frame_2;
    WLabel *lbIP;
    WLabel *lbUni_8;
    WLabel *lbTit_2;
    WLabel *lbNumDes_9;
    WLabel *lbNumDes_7;
    WLabel *lbTit_11;
    WLabel *lbNum_3;
    WLabel *lbTit_1;
    WLabel *lbNum_9;
    WLabel *lbTit_9;
    WLabel *lbUni_1;
    WLabel *lbUni_11;
    WLabel *lbTit_8;
    WLabel *lbTit_7;
    WLabel *lbNumDes_3;
    WLabel *lbNumDes_1;
    WLabel *lbNum_1;
    WLabel *lbUni_3;
    WLabel *lbNum_2;
    WLabel *lbTit_5;
    WLabel *lbUni_2;
    WLabel *lbNum_11;
    WLabel *lbNum_12;
    WLabel *lbNum_7;
    WLabel *lbNumDes_12;
    WLabel *lbNum_4;
    WLabel *lbNumDes_2;
    WLabel *lbTit_12;
    WLabel *lbNumDes_11;
    WLabel *lbUni_4;
    WLabel *lbNum_8;
    WLabel *lbUni_5;
    WLabel *lbUni_10;
    WLabel *lbNum_10;
    WLabel *lbNumDes_8;
    WLabel *lbUni_6;
    QPushButton *btCerrar;
    WLabel *lbNumDes_4;
    WLabel *lbTit_6;
    WLabel *lbUni_9;
    WLabel *lbTit_10;
    WLabel *lbTit_4;
    WLabel *lbNumDes_6;
    WLabel *lbNum_13;
    WLabel *lbNumDes_13;
    WLabel *lbTit_13;
    WLabel *lbNum_14;
    WLabel *lbUni_13;
    WLabel *lbTit_14;
    WLabel *lbNumDes_14;
    WLabel *lbUni_14;
    WLabel *lbTit_15;
    QLabel *lbFondo;

    void setupUi(QWidget *Analog16_3)
    {
        if (Analog16_3->objectName().isEmpty())
            Analog16_3->setObjectName(QString::fromUtf8("Analog16_3"));
        Analog16_3->resize(485, 425);
        Analog16_3->setMinimumSize(QSize(485, 425));
        Analog16_3->setMaximumSize(QSize(485, 425));
        Analog16_3->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbNum_6 = new WLabel(Analog16_3);
        lbNum_6->setObjectName(QString::fromUtf8("lbNum_6"));
        lbNum_6->setGeometry(QRect(12, 160, 21, 16));
        lbNum_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        QFont font;
        font.setFamily(QString::fromUtf8("Verdana"));
        font.setBold(true);
        font.setWeight(75);
        lbNum_6->setFont(font);
        lbNum_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_10 = new WLabel(Analog16_3);
        lbNumDes_10->setObjectName(QString::fromUtf8("lbNumDes_10"));
        lbNumDes_10->setGeometry(QRect(388, 240, 41, 16));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setPointSize(7);
        font1.setBold(false);
        font1.setWeight(50);
        lbNumDes_10->setFont(font1);
        lbNumDes_10->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumDes_5 = new WLabel(Analog16_3);
        lbNumDes_5->setObjectName(QString::fromUtf8("lbNumDes_5"));
        lbNumDes_5->setGeometry(QRect(388, 140, 41, 16));
        lbNumDes_5->setFont(font1);
        lbNumDes_5->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbUni_12 = new WLabel(Analog16_3);
        lbUni_12->setObjectName(QString::fromUtf8("lbUni_12"));
        lbUni_12->setGeometry(QRect(437, 280, 43, 16));
        lbUni_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_12->setFont(font1);
        lbUni_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_7 = new WLabel(Analog16_3);
        lbUni_7->setObjectName(QString::fromUtf8("lbUni_7"));
        lbUni_7->setGeometry(QRect(437, 180, 43, 16));
        lbUni_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_7->setFont(font1);
        lbUni_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_5 = new WLabel(Analog16_3);
        lbNum_5->setObjectName(QString::fromUtf8("lbNum_5"));
        lbNum_5->setGeometry(QRect(12, 140, 21, 16));
        lbNum_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_5->setFont(font);
        lbNum_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_3 = new WLabel(Analog16_3);
        lbTit_3->setObjectName(QString::fromUtf8("lbTit_3"));
        lbTit_3->setGeometry(QRect(40, 100, 340, 16));
        lbTit_3->setFont(font1);
        lbTit_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame = new QFrame(Analog16_3);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 17, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        label_2 = new WLabel(frame);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(62, 4, 400, 22));
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        label_2->setFont(font2);
        label_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame_2 = new QFrame(Analog16_3);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(2, 0, 485, 16));
        frame_2->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frame_2->setFrameShape(QFrame::Panel);
        frame_2->setFrameShadow(QFrame::Raised);
        frame_2->setLineWidth(0);
        lbIP = new WLabel(frame_2);
        lbIP->setObjectName(QString::fromUtf8("lbIP"));
        lbIP->setGeometry(QRect(3, 0, 103, 16));
        lbIP->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 110, 195);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(74, 110, 195);"));
        QFont font3;
        font3.setPointSize(9);
        lbIP->setFont(font3);
        lbIP->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_8 = new WLabel(Analog16_3);
        lbUni_8->setObjectName(QString::fromUtf8("lbUni_8"));
        lbUni_8->setGeometry(QRect(437, 200, 43, 16));
        lbUni_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_8->setFont(font1);
        lbUni_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_2 = new WLabel(Analog16_3);
        lbTit_2->setObjectName(QString::fromUtf8("lbTit_2"));
        lbTit_2->setGeometry(QRect(40, 80, 340, 16));
        lbTit_2->setFont(font1);
        lbTit_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_9 = new WLabel(Analog16_3);
        lbNumDes_9->setObjectName(QString::fromUtf8("lbNumDes_9"));
        lbNumDes_9->setGeometry(QRect(388, 220, 41, 16));
        lbNumDes_9->setFont(font1);
        lbNumDes_9->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumDes_7 = new WLabel(Analog16_3);
        lbNumDes_7->setObjectName(QString::fromUtf8("lbNumDes_7"));
        lbNumDes_7->setGeometry(QRect(388, 180, 41, 16));
        lbNumDes_7->setFont(font1);
        lbNumDes_7->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbTit_11 = new WLabel(Analog16_3);
        lbTit_11->setObjectName(QString::fromUtf8("lbTit_11"));
        lbTit_11->setGeometry(QRect(40, 260, 340, 16));
        lbTit_11->setFont(font1);
        lbTit_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_3 = new WLabel(Analog16_3);
        lbNum_3->setObjectName(QString::fromUtf8("lbNum_3"));
        lbNum_3->setGeometry(QRect(12, 100, 21, 16));
        lbNum_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_3->setFont(font);
        lbNum_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_1 = new WLabel(Analog16_3);
        lbTit_1->setObjectName(QString::fromUtf8("lbTit_1"));
        lbTit_1->setGeometry(QRect(40, 60, 340, 16));
        lbTit_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTit_1->setFont(font1);
        lbTit_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_9 = new WLabel(Analog16_3);
        lbNum_9->setObjectName(QString::fromUtf8("lbNum_9"));
        lbNum_9->setGeometry(QRect(12, 220, 21, 16));
        lbNum_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_9->setFont(font);
        lbNum_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_9 = new WLabel(Analog16_3);
        lbTit_9->setObjectName(QString::fromUtf8("lbTit_9"));
        lbTit_9->setGeometry(QRect(40, 220, 340, 16));
        lbTit_9->setFont(font1);
        lbTit_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_1 = new WLabel(Analog16_3);
        lbUni_1->setObjectName(QString::fromUtf8("lbUni_1"));
        lbUni_1->setGeometry(QRect(437, 60, 43, 16));
        lbUni_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_1->setFont(font1);
        lbUni_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_11 = new WLabel(Analog16_3);
        lbUni_11->setObjectName(QString::fromUtf8("lbUni_11"));
        lbUni_11->setGeometry(QRect(437, 260, 43, 16));
        lbUni_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_11->setFont(font1);
        lbUni_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_8 = new WLabel(Analog16_3);
        lbTit_8->setObjectName(QString::fromUtf8("lbTit_8"));
        lbTit_8->setGeometry(QRect(40, 200, 340, 16));
        lbTit_8->setFont(font1);
        lbTit_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_7 = new WLabel(Analog16_3);
        lbTit_7->setObjectName(QString::fromUtf8("lbTit_7"));
        lbTit_7->setGeometry(QRect(40, 180, 340, 16));
        lbTit_7->setFont(font1);
        lbTit_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_3 = new WLabel(Analog16_3);
        lbNumDes_3->setObjectName(QString::fromUtf8("lbNumDes_3"));
        lbNumDes_3->setGeometry(QRect(388, 100, 41, 16));
        lbNumDes_3->setFont(font1);
        lbNumDes_3->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumDes_1 = new WLabel(Analog16_3);
        lbNumDes_1->setObjectName(QString::fromUtf8("lbNumDes_1"));
        lbNumDes_1->setGeometry(QRect(388, 60, 41, 16));
        lbNumDes_1->setFont(font1);
        lbNumDes_1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_1 = new WLabel(Analog16_3);
        lbNum_1->setObjectName(QString::fromUtf8("lbNum_1"));
        lbNum_1->setGeometry(QRect(12, 60, 21, 16));
        lbNum_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_1->setFont(font);
        lbNum_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_3 = new WLabel(Analog16_3);
        lbUni_3->setObjectName(QString::fromUtf8("lbUni_3"));
        lbUni_3->setGeometry(QRect(437, 100, 43, 16));
        lbUni_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_3->setFont(font1);
        lbUni_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_2 = new WLabel(Analog16_3);
        lbNum_2->setObjectName(QString::fromUtf8("lbNum_2"));
        lbNum_2->setGeometry(QRect(12, 80, 21, 16));
        lbNum_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_2->setFont(font);
        lbNum_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_5 = new WLabel(Analog16_3);
        lbTit_5->setObjectName(QString::fromUtf8("lbTit_5"));
        lbTit_5->setGeometry(QRect(40, 140, 340, 16));
        lbTit_5->setFont(font1);
        lbTit_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_2 = new WLabel(Analog16_3);
        lbUni_2->setObjectName(QString::fromUtf8("lbUni_2"));
        lbUni_2->setGeometry(QRect(437, 80, 43, 16));
        lbUni_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_2->setFont(font1);
        lbUni_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_11 = new WLabel(Analog16_3);
        lbNum_11->setObjectName(QString::fromUtf8("lbNum_11"));
        lbNum_11->setGeometry(QRect(12, 260, 21, 16));
        lbNum_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_11->setFont(font);
        lbNum_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_12 = new WLabel(Analog16_3);
        lbNum_12->setObjectName(QString::fromUtf8("lbNum_12"));
        lbNum_12->setGeometry(QRect(12, 280, 21, 16));
        lbNum_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_12->setFont(font);
        lbNum_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_7 = new WLabel(Analog16_3);
        lbNum_7->setObjectName(QString::fromUtf8("lbNum_7"));
        lbNum_7->setGeometry(QRect(12, 180, 21, 16));
        lbNum_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_7->setFont(font);
        lbNum_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_12 = new WLabel(Analog16_3);
        lbNumDes_12->setObjectName(QString::fromUtf8("lbNumDes_12"));
        lbNumDes_12->setGeometry(QRect(388, 280, 41, 16));
        lbNumDes_12->setFont(font1);
        lbNumDes_12->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_4 = new WLabel(Analog16_3);
        lbNum_4->setObjectName(QString::fromUtf8("lbNum_4"));
        lbNum_4->setGeometry(QRect(12, 120, 21, 16));
        lbNum_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_4->setFont(font);
        lbNum_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_2 = new WLabel(Analog16_3);
        lbNumDes_2->setObjectName(QString::fromUtf8("lbNumDes_2"));
        lbNumDes_2->setGeometry(QRect(388, 80, 41, 16));
        lbNumDes_2->setFont(font1);
        lbNumDes_2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbTit_12 = new WLabel(Analog16_3);
        lbTit_12->setObjectName(QString::fromUtf8("lbTit_12"));
        lbTit_12->setGeometry(QRect(40, 280, 340, 16));
        lbTit_12->setFont(font1);
        lbTit_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_11 = new WLabel(Analog16_3);
        lbNumDes_11->setObjectName(QString::fromUtf8("lbNumDes_11"));
        lbNumDes_11->setGeometry(QRect(388, 260, 41, 16));
        lbNumDes_11->setFont(font1);
        lbNumDes_11->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbUni_4 = new WLabel(Analog16_3);
        lbUni_4->setObjectName(QString::fromUtf8("lbUni_4"));
        lbUni_4->setGeometry(QRect(437, 120, 43, 16));
        lbUni_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_4->setFont(font1);
        lbUni_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_8 = new WLabel(Analog16_3);
        lbNum_8->setObjectName(QString::fromUtf8("lbNum_8"));
        lbNum_8->setGeometry(QRect(12, 200, 21, 16));
        lbNum_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_8->setFont(font);
        lbNum_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_5 = new WLabel(Analog16_3);
        lbUni_5->setObjectName(QString::fromUtf8("lbUni_5"));
        lbUni_5->setGeometry(QRect(437, 140, 43, 16));
        lbUni_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_5->setFont(font1);
        lbUni_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_10 = new WLabel(Analog16_3);
        lbUni_10->setObjectName(QString::fromUtf8("lbUni_10"));
        lbUni_10->setGeometry(QRect(437, 240, 43, 16));
        lbUni_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_10->setFont(font1);
        lbUni_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_10 = new WLabel(Analog16_3);
        lbNum_10->setObjectName(QString::fromUtf8("lbNum_10"));
        lbNum_10->setGeometry(QRect(12, 240, 21, 16));
        lbNum_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_10->setFont(font);
        lbNum_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_8 = new WLabel(Analog16_3);
        lbNumDes_8->setObjectName(QString::fromUtf8("lbNumDes_8"));
        lbNumDes_8->setGeometry(QRect(388, 200, 41, 16));
        lbNumDes_8->setFont(font1);
        lbNumDes_8->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbUni_6 = new WLabel(Analog16_3);
        lbUni_6->setObjectName(QString::fromUtf8("lbUni_6"));
        lbUni_6->setGeometry(QRect(437, 160, 43, 16));
        lbUni_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_6->setFont(font1);
        lbUni_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        btCerrar = new QPushButton(Analog16_3);
        btCerrar->setObjectName(QString::fromUtf8("btCerrar"));
        btCerrar->setGeometry(QRect(124, 385, 100, 32));
        btCerrar->setFont(font2);
        btCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbNumDes_4 = new WLabel(Analog16_3);
        lbNumDes_4->setObjectName(QString::fromUtf8("lbNumDes_4"));
        lbNumDes_4->setGeometry(QRect(388, 120, 41, 16));
        lbNumDes_4->setFont(font1);
        lbNumDes_4->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbTit_6 = new WLabel(Analog16_3);
        lbTit_6->setObjectName(QString::fromUtf8("lbTit_6"));
        lbTit_6->setGeometry(QRect(40, 160, 340, 16));
        lbTit_6->setFont(font1);
        lbTit_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_9 = new WLabel(Analog16_3);
        lbUni_9->setObjectName(QString::fromUtf8("lbUni_9"));
        lbUni_9->setGeometry(QRect(437, 220, 43, 16));
        lbUni_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_9->setFont(font1);
        lbUni_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_10 = new WLabel(Analog16_3);
        lbTit_10->setObjectName(QString::fromUtf8("lbTit_10"));
        lbTit_10->setGeometry(QRect(40, 240, 340, 16));
        lbTit_10->setFont(font1);
        lbTit_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_4 = new WLabel(Analog16_3);
        lbTit_4->setObjectName(QString::fromUtf8("lbTit_4"));
        lbTit_4->setGeometry(QRect(40, 120, 340, 16));
        lbTit_4->setFont(font1);
        lbTit_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_6 = new WLabel(Analog16_3);
        lbNumDes_6->setObjectName(QString::fromUtf8("lbNumDes_6"));
        lbNumDes_6->setGeometry(QRect(388, 160, 41, 16));
        lbNumDes_6->setFont(font1);
        lbNumDes_6->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_13 = new WLabel(Analog16_3);
        lbNum_13->setObjectName(QString::fromUtf8("lbNum_13"));
        lbNum_13->setGeometry(QRect(12, 320, 21, 16));
        lbNum_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_13->setFont(font);
        lbNum_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_13 = new WLabel(Analog16_3);
        lbNumDes_13->setObjectName(QString::fromUtf8("lbNumDes_13"));
        lbNumDes_13->setGeometry(QRect(388, 320, 41, 16));
        lbNumDes_13->setFont(font1);
        lbNumDes_13->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbTit_13 = new WLabel(Analog16_3);
        lbTit_13->setObjectName(QString::fromUtf8("lbTit_13"));
        lbTit_13->setGeometry(QRect(40, 320, 340, 16));
        lbTit_13->setFont(font1);
        lbTit_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_14 = new WLabel(Analog16_3);
        lbNum_14->setObjectName(QString::fromUtf8("lbNum_14"));
        lbNum_14->setGeometry(QRect(12, 300, 21, 16));
        lbNum_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_14->setFont(font);
        lbNum_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_13 = new WLabel(Analog16_3);
        lbUni_13->setObjectName(QString::fromUtf8("lbUni_13"));
        lbUni_13->setGeometry(QRect(437, 300, 43, 16));
        lbUni_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_13->setFont(font1);
        lbUni_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_14 = new WLabel(Analog16_3);
        lbTit_14->setObjectName(QString::fromUtf8("lbTit_14"));
        lbTit_14->setGeometry(QRect(38, 100, 340, 16));
        lbTit_14->setFont(font1);
        lbTit_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_14 = new WLabel(Analog16_3);
        lbNumDes_14->setObjectName(QString::fromUtf8("lbNumDes_14"));
        lbNumDes_14->setGeometry(QRect(388, 300, 41, 16));
        lbNumDes_14->setFont(font1);
        lbNumDes_14->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbUni_14 = new WLabel(Analog16_3);
        lbUni_14->setObjectName(QString::fromUtf8("lbUni_14"));
        lbUni_14->setGeometry(QRect(437, 320, 43, 16));
        lbUni_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbUni_14->setFont(font1);
        lbUni_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_15 = new WLabel(Analog16_3);
        lbTit_15->setObjectName(QString::fromUtf8("lbTit_15"));
        lbTit_15->setGeometry(QRect(40, 300, 340, 16));
        lbTit_15->setFont(font1);
        lbTit_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbFondo = new QLabel(Analog16_3);
        lbFondo->setObjectName(QString::fromUtf8("lbFondo"));
        lbFondo->setGeometry(QRect(0, 0, 485, 425));
        lbFondo->setMaximumSize(QSize(485, 425));
        lbFondo->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbFondo->setFrameShape(QFrame::Box);
        lbFondo->setFrameShadow(QFrame::Sunken);
        lbFondo->raise();
        lbNum_6->raise();
        lbNumDes_10->raise();
        lbNumDes_5->raise();
        lbUni_12->raise();
        lbUni_7->raise();
        lbNum_5->raise();
        lbTit_3->raise();
        frame->raise();
        frame_2->raise();
        lbUni_8->raise();
        lbTit_2->raise();
        lbNumDes_9->raise();
        lbNumDes_7->raise();
        lbTit_11->raise();
        lbNum_3->raise();
        lbTit_1->raise();
        lbNum_9->raise();
        lbTit_9->raise();
        lbUni_1->raise();
        lbUni_11->raise();
        lbTit_8->raise();
        lbTit_7->raise();
        lbNumDes_3->raise();
        lbNumDes_1->raise();
        lbNum_1->raise();
        lbUni_3->raise();
        lbNum_2->raise();
        lbTit_5->raise();
        lbUni_2->raise();
        lbNum_11->raise();
        lbNum_12->raise();
        lbNum_7->raise();
        lbNumDes_12->raise();
        lbNum_4->raise();
        lbNumDes_2->raise();
        lbTit_12->raise();
        lbNumDes_11->raise();
        lbUni_4->raise();
        lbNum_8->raise();
        lbUni_5->raise();
        lbUni_10->raise();
        lbNum_10->raise();
        lbNumDes_8->raise();
        lbUni_6->raise();
        btCerrar->raise();
        lbNumDes_4->raise();
        lbTit_6->raise();
        lbUni_9->raise();
        lbTit_10->raise();
        lbTit_4->raise();
        lbNumDes_6->raise();
        lbNum_13->raise();
        lbNumDes_13->raise();
        lbTit_13->raise();
        lbNum_14->raise();
        lbUni_13->raise();
        lbTit_14->raise();
        lbNumDes_14->raise();
        lbUni_14->raise();
        lbTit_15->raise();

        retranslateUi(Analog16_3);

        QMetaObject::connectSlotsByName(Analog16_3);
    } // setupUi

    void retranslateUi(QWidget *Analog16_3)
    {
        Analog16_3->setWindowTitle(QApplication::translate("Analog16_3", "Analog16_3", 0, QApplication::UnicodeUTF8));
        lbNum_6->setText(QApplication::translate("Analog16_3", "6", 0, QApplication::UnicodeUTF8));
        lbNumDes_10->setText(QString());
        lbNumDes_5->setText(QString());
        lbUni_12->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbUni_7->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbNum_5->setText(QString());
        lbTit_3->setText(QApplication::translate("Analog16_3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Analog16_3", "SLOT-  A206  -RT SIO", 0, QApplication::UnicodeUTF8));
        lbIP->setText(QApplication::translate("Analog16_3", "ANALOG016.grf", 0, QApplication::UnicodeUTF8));
        lbUni_8->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbTit_2->setText(QApplication::translate("Analog16_3", "RETROAL PILOTO FCV62108 SELECCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbNumDes_9->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbNumDes_7->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbTit_11->setText(QApplication::translate("Analog16_3", "DEMANDA EXTERNA", 0, QApplication::UnicodeUTF8));
        lbNum_3->setText(QApplication::translate("Analog16_3", "3", 0, QApplication::UnicodeUTF8));
        lbTit_1->setText(QApplication::translate("Analog16_3", "DEMANDA PILOTO", 0, QApplication::UnicodeUTF8));
        lbNum_9->setText(QApplication::translate("Analog16_3", "9", 0, QApplication::UnicodeUTF8));
        lbTit_9->setText(QApplication::translate("Analog16_3", "RETROAL INTERNO FCV62107B ", 0, QApplication::UnicodeUTF8));
        lbUni_1->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbUni_11->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbTit_8->setText(QApplication::translate("Analog16_3", "RETROAL INTERN0 FCV62107A ", 0, QApplication::UnicodeUTF8));
        lbTit_7->setText(QApplication::translate("Analog16_3", "RETROAL INTERNO FCV62107 SELECCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbNumDes_3->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbNumDes_1->setText(QApplication::translate("Analog16_3", "45.60", 0, QApplication::UnicodeUTF8));
        lbNum_1->setText(QApplication::translate("Analog16_3", "1", 0, QApplication::UnicodeUTF8));
        lbUni_3->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbNum_2->setText(QApplication::translate("Analog16_3", "2", 0, QApplication::UnicodeUTF8));
        lbTit_5->setText(QString());
        lbUni_2->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbNum_11->setText(QApplication::translate("Analog16_3", "11", 0, QApplication::UnicodeUTF8));
        lbNum_12->setText(QApplication::translate("Analog16_3", "12", 0, QApplication::UnicodeUTF8));
        lbNum_7->setText(QApplication::translate("Analog16_3", "7", 0, QApplication::UnicodeUTF8));
        lbNumDes_12->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbNum_4->setText(QApplication::translate("Analog16_3", "4", 0, QApplication::UnicodeUTF8));
        lbNumDes_2->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbTit_12->setText(QApplication::translate("Analog16_3", "RETROAL EXTERNO FCV62109 SELECCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbNumDes_11->setText(QApplication::translate("Analog16_3", "44.10", 0, QApplication::UnicodeUTF8));
        lbUni_4->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbNum_8->setText(QApplication::translate("Analog16_3", "8", 0, QApplication::UnicodeUTF8));
        lbUni_5->setText(QString());
        lbUni_10->setText(QString());
        lbNum_10->setText(QString());
        lbNumDes_8->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbUni_6->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        btCerrar->setText(QApplication::translate("Analog16_3", "CERRAR", 0, QApplication::UnicodeUTF8));
        lbNumDes_4->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbTit_6->setText(QApplication::translate("Analog16_3", "DEMANDA INTERNA", 0, QApplication::UnicodeUTF8));
        lbUni_9->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbTit_10->setText(QString());
        lbTit_4->setText(QApplication::translate("Analog16_3", "RETROALIMENTACI\303\223N PILOTO FCV62108B", 0, QApplication::UnicodeUTF8));
        lbNumDes_6->setText(QApplication::translate("Analog16_3", "29.70", 0, QApplication::UnicodeUTF8));
        lbNum_13->setText(QApplication::translate("Analog16_3", "14", 0, QApplication::UnicodeUTF8));
        lbNumDes_13->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbTit_13->setText(QApplication::translate("Analog16_3", "RETROAL EXTERNO FCV62109B ", 0, QApplication::UnicodeUTF8));
        lbNum_14->setText(QApplication::translate("Analog16_3", "13", 0, QApplication::UnicodeUTF8));
        lbUni_13->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbTit_14->setText(QApplication::translate("Analog16_3", "RETROALIMENTACI\303\223N PILOTO FCV62108A ", 0, QApplication::UnicodeUTF8));
        lbNumDes_14->setText(QApplication::translate("Analog16_3", "0.00", 0, QApplication::UnicodeUTF8));
        lbUni_14->setText(QApplication::translate("Analog16_3", "% ", 0, QApplication::UnicodeUTF8));
        lbTit_15->setText(QApplication::translate("Analog16_3", "RETROAL EXTERNO FCV62109A ", 0, QApplication::UnicodeUTF8));
        lbFondo->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Analog16_3: public Ui_Analog16_3 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ANALOG16_3_H
