/********************************************************************************
** Form generated from reading UI file 'analog24.ui'
**
** Created: Sat 7. Dec 00:54:30 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ANALOG24_H
#define UI_ANALOG24_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_Analog24
{
public:
    QFrame *panel1;
    WLabel *lbAIT_5;
    WLabel *lbAI_20;
    WLabel *lbAIT_10;
    WLabel *lbAIT_1;
    WLabel *lbNumAI_21;
    WLabel *lbNumAI_10;
    WLabel *lbAI_2;
    WLabel *lbAIU_21;
    WLabel *lbAI_7;
    WLabel *lbNumAI_3;
    WLabel *lbAI_21;
    WLabel *lbAIU_5;
    WLabel *lbNumAI_2;
    WLabel *lbAIT_21;
    WLabel *lbAI_10;
    WLabel *lbAIU_3;
    WLabel *lbNumAI_22;
    WLabel *lbNumAI_11;
    WLabel *lbAI_1;
    WLabel *lbAIU_22;
    WLabel *lbAIU_10;
    WLabel *lbAIU_2;
    WLabel *lbAIT_22;
    WLabel *lbAIU_11;
    WLabel *lbAIT_2;
    WLabel *lbAI_22;
    WLabel *lbAI_12;
    QLabel *lbFondo;
    WLabel *lbNumAI_23;
    WLabel *lbNumAI_12;
    WLabel *lbAIU_23;
    WLabel *lbAI_9;
    WLabel *lbNumAI_1;
    WLabel *lbAI_23;
    WLabel *lbAI_11;
    QFrame *frame_2;
    WLabel *lbSloAl;
    WLabel *lbAIT_23;
    WLabel *lbAIU_12;
    WLabel *lbAIU_1;
    WLabel *lbAIU_24;
    WLabel *lbNumAI_13;
    WLabel *lbNumAI_24;
    WLabel *lbAIT_12;
    WLabel *lbAIT_24;
    QFrame *frBarraT;
    WLabel *lbAna24T;
    WLabel *lbAIT_13;
    WLabel *lbAI_24;
    WLabel *lbAIT_14;
    WLabel *lbAIT_15;
    WLabel *lbNumAI_14;
    WLabel *lbAIT_11;
    WLabel *lbAIU_13;
    WLabel *lbAI_15;
    WLabel *lbAI_13;
    WLabel *lbAIU_15;
    WLabel *lbAI_14;
    WLabel *lbNumAI_15;
    WLabel *lbNumAI_7;
    WLabel *lbAIT_16;
    WLabel *lbAIU_8;
    WLabel *lbAI_16;
    WLabel *lbAIU_4;
    WLabel *lbAIU_16;
    WLabel *lbNumAI_4;
    WLabel *lbNumAI_17;
    WLabel *lbAIT_3;
    WLabel *lbAIU_17;
    WLabel *lbAI_5;
    WLabel *lbAI_17;
    WLabel *lbAI_6;
    WLabel *lbAIT_17;
    WLabel *lbNumAI_18;
    WLabel *lbAI_4;
    WLabel *lbAI_18;
    WLabel *lbNumAI_5;
    WLabel *lbAIU_18;
    WLabel *lbAIT_4;
    WLabel *lbAIT_18;
    WLabel *lbAI_3;
    WLabel *lbNumAI_19;
    WLabel *lbNumAI_8;
    WLabel *lbNumAI_16;
    WLabel *lbAIT_19;
    WLabel *lbAIT_7;
    WLabel *lbAIU_7;
    WLabel *lbAIU_19;
    WLabel *lbAIU_9;
    WLabel *lbNumAI_6;
    WLabel *lbAI_19;
    WLabel *lbAIT_8;
    WLabel *lbAIT_6;
    WLabel *lbNumAI_20;
    WLabel *lbAI_8;
    WLabel *lbAIU_14;
    WLabel *lbAIU_20;
    WLabel *lbNumAI_9;
    WLabel *lbAIU_6;
    WLabel *lbAIT_20;
    WLabel *lbAIT_9;
    QFrame *panel2;
    WLabel *lbAIT_25;
    WLabel *lbAIT_27;
    WLabel *lbAI_26;
    WLabel *lbAI_27;
    WLabel *lbNumAI_27;
    WLabel *lbAIU_26;
    WLabel *lbNumAI_28;
    WLabel *lbAIU_27;
    WLabel *lbAI_30;
    WLabel *lbAIU_30;
    WLabel *lbAIT_30;
    QLabel *lbFondo_2;
    WLabel *lbNumAI_33;
    QFrame *frame_3;
    WLabel *lbSloAl_2;
    WLabel *lbAIU_34;
    QFrame *frBarraT_2;
    WLabel *lbAna24T_2;
    WLabel *lbNumAI_38;
    WLabel *lbAIU_38;
    WLabel *lbAIU_39;
    WLabel *lbNumAI_39;
    WLabel *lbAIT_39;
    WLabel *lbAI_41;
    WLabel *lbAI_43;
    WLabel *lbAI_44;
    WLabel *lbNumAI_42;
    WLabel *lbAIT_41;
    WLabel *lbAI_46;
    WLabel *lbNumAI_44;
    WLabel *lbAIT_44;
    WLabel *lbAIU_43;
    WLabel *lbNumAI_46;
    WLabel *lbAIT_45;
    WLabel *lbAIT_46;
    WLabel *lbAI_48;
    WLabel *lbAIU_48;
    QFrame *frame;
    QPushButton *btnProx;
    QPushButton *btnCerrar;

    void setupUi(QWidget *Analog24)
    {
        if (Analog24->objectName().isEmpty())
            Analog24->setObjectName(QString::fromUtf8("Analog24"));
        Analog24->resize(485, 590);
        Analog24->setMinimumSize(QSize(485, 590));
        Analog24->setMaximumSize(QSize(485, 590));
        Analog24->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        panel1 = new QFrame(Analog24);
        panel1->setObjectName(QString::fromUtf8("panel1"));
        panel1->setGeometry(QRect(0, 0, 485, 530));
        panel1->setFrameShape(QFrame::StyledPanel);
        panel1->setFrameShadow(QFrame::Raised);
        lbAIT_5 = new WLabel(panel1);
        lbAIT_5->setObjectName(QString::fromUtf8("lbAIT_5"));
        lbAIT_5->setGeometry(QRect(35, 135, 340, 16));
        QFont font;
        font.setFamily(QString::fromUtf8("Verdana"));
        font.setBold(true);
        font.setWeight(75);
        lbAIT_5->setFont(font);
        lbAIT_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_20 = new WLabel(panel1);
        lbAI_20->setObjectName(QString::fromUtf8("lbAI_20"));
        lbAI_20->setGeometry(QRect(366, 435, 61, 20));
        lbAI_20->setFont(font);
        lbAI_20->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_10 = new WLabel(panel1);
        lbAIT_10->setObjectName(QString::fromUtf8("lbAIT_10"));
        lbAIT_10->setGeometry(QRect(35, 237, 340, 16));
        lbAIT_10->setFont(font);
        lbAIT_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_1 = new WLabel(panel1);
        lbAIT_1->setObjectName(QString::fromUtf8("lbAIT_1"));
        lbAIT_1->setGeometry(QRect(33, 55, 340, 16));
        lbAIT_1->setFont(font);
        lbAIT_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_21 = new WLabel(panel1);
        lbNumAI_21->setObjectName(QString::fromUtf8("lbNumAI_21"));
        lbNumAI_21->setGeometry(QRect(10, 455, 21, 16));
        lbNumAI_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_21->setFont(font);
        lbNumAI_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_10 = new WLabel(panel1);
        lbNumAI_10->setObjectName(QString::fromUtf8("lbNumAI_10"));
        lbNumAI_10->setGeometry(QRect(10, 237, 21, 16));
        lbNumAI_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_10->setFont(font);
        lbNumAI_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_2 = new WLabel(panel1);
        lbAI_2->setObjectName(QString::fromUtf8("lbAI_2"));
        lbAI_2->setGeometry(QRect(366, 75, 59, 20));
        lbAI_2->setFont(font);
        lbAI_2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_21 = new WLabel(panel1);
        lbAIU_21->setObjectName(QString::fromUtf8("lbAIU_21"));
        lbAIU_21->setGeometry(QRect(435, 455, 51, 20));
        lbAIU_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_21->setFont(font);
        lbAIU_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_7 = new WLabel(panel1);
        lbAI_7->setObjectName(QString::fromUtf8("lbAI_7"));
        lbAI_7->setGeometry(QRect(366, 175, 61, 20));
        lbAI_7->setFont(font);
        lbAI_7->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_3 = new WLabel(panel1);
        lbNumAI_3->setObjectName(QString::fromUtf8("lbNumAI_3"));
        lbNumAI_3->setGeometry(QRect(10, 95, 21, 16));
        lbNumAI_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_3->setFont(font);
        lbNumAI_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_21 = new WLabel(panel1);
        lbAI_21->setObjectName(QString::fromUtf8("lbAI_21"));
        lbAI_21->setGeometry(QRect(366, 455, 61, 20));
        lbAI_21->setFont(font);
        lbAI_21->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_5 = new WLabel(panel1);
        lbAIU_5->setObjectName(QString::fromUtf8("lbAIU_5"));
        lbAIU_5->setGeometry(QRect(436, 135, 31, 20));
        lbAIU_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_5->setFont(font);
        lbAIU_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_2 = new WLabel(panel1);
        lbNumAI_2->setObjectName(QString::fromUtf8("lbNumAI_2"));
        lbNumAI_2->setGeometry(QRect(8, 75, 21, 16));
        lbNumAI_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_2->setFont(font);
        lbNumAI_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_21 = new WLabel(panel1);
        lbAIT_21->setObjectName(QString::fromUtf8("lbAIT_21"));
        lbAIT_21->setGeometry(QRect(35, 455, 311, 16));
        lbAIT_21->setFont(font);
        lbAIT_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_10 = new WLabel(panel1);
        lbAI_10->setObjectName(QString::fromUtf8("lbAI_10"));
        lbAI_10->setGeometry(QRect(366, 237, 61, 20));
        lbAI_10->setFont(font);
        lbAI_10->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_3 = new WLabel(panel1);
        lbAIU_3->setObjectName(QString::fromUtf8("lbAIU_3"));
        lbAIU_3->setGeometry(QRect(436, 95, 31, 20));
        lbAIU_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_3->setFont(font);
        lbAIU_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_22 = new WLabel(panel1);
        lbNumAI_22->setObjectName(QString::fromUtf8("lbNumAI_22"));
        lbNumAI_22->setGeometry(QRect(10, 475, 21, 16));
        lbNumAI_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_22->setFont(font);
        lbNumAI_22->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_11 = new WLabel(panel1);
        lbNumAI_11->setObjectName(QString::fromUtf8("lbNumAI_11"));
        lbNumAI_11->setGeometry(QRect(10, 255, 21, 16));
        lbNumAI_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_11->setFont(font);
        lbNumAI_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_1 = new WLabel(panel1);
        lbAI_1->setObjectName(QString::fromUtf8("lbAI_1"));
        lbAI_1->setGeometry(QRect(366, 55, 59, 20));
        lbAI_1->setFont(font);
        lbAI_1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_22 = new WLabel(panel1);
        lbAIU_22->setObjectName(QString::fromUtf8("lbAIU_22"));
        lbAIU_22->setGeometry(QRect(435, 475, 51, 20));
        lbAIU_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_22->setFont(font);
        lbAIU_22->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_10 = new WLabel(panel1);
        lbAIU_10->setObjectName(QString::fromUtf8("lbAIU_10"));
        lbAIU_10->setGeometry(QRect(436, 237, 31, 20));
        lbAIU_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_10->setFont(font);
        lbAIU_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_2 = new WLabel(panel1);
        lbAIU_2->setObjectName(QString::fromUtf8("lbAIU_2"));
        lbAIU_2->setGeometry(QRect(436, 75, 31, 20));
        lbAIU_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_2->setFont(font);
        lbAIU_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_22 = new WLabel(panel1);
        lbAIT_22->setObjectName(QString::fromUtf8("lbAIT_22"));
        lbAIT_22->setGeometry(QRect(35, 475, 311, 16));
        lbAIT_22->setFont(font);
        lbAIT_22->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_11 = new WLabel(panel1);
        lbAIU_11->setObjectName(QString::fromUtf8("lbAIU_11"));
        lbAIU_11->setGeometry(QRect(436, 255, 31, 20));
        lbAIU_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_11->setFont(font);
        lbAIU_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_2 = new WLabel(panel1);
        lbAIT_2->setObjectName(QString::fromUtf8("lbAIT_2"));
        lbAIT_2->setGeometry(QRect(33, 75, 340, 16));
        lbAIT_2->setFont(font);
        lbAIT_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_22 = new WLabel(panel1);
        lbAI_22->setObjectName(QString::fromUtf8("lbAI_22"));
        lbAI_22->setGeometry(QRect(366, 475, 61, 20));
        lbAI_22->setFont(font);
        lbAI_22->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_12 = new WLabel(panel1);
        lbAI_12->setObjectName(QString::fromUtf8("lbAI_12"));
        lbAI_12->setGeometry(QRect(366, 275, 61, 20));
        lbAI_12->setFont(font);
        lbAI_12->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbFondo = new QLabel(panel1);
        lbFondo->setObjectName(QString::fromUtf8("lbFondo"));
        lbFondo->setGeometry(QRect(0, 0, 485, 590));
        lbFondo->setMinimumSize(QSize(485, 590));
        lbFondo->setMaximumSize(QSize(485, 590));
        lbFondo->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbNumAI_23 = new WLabel(panel1);
        lbNumAI_23->setObjectName(QString::fromUtf8("lbNumAI_23"));
        lbNumAI_23->setGeometry(QRect(10, 495, 21, 16));
        lbNumAI_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_23->setFont(font);
        lbNumAI_23->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_12 = new WLabel(panel1);
        lbNumAI_12->setObjectName(QString::fromUtf8("lbNumAI_12"));
        lbNumAI_12->setGeometry(QRect(10, 275, 21, 16));
        lbNumAI_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_12->setFont(font);
        lbNumAI_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_23 = new WLabel(panel1);
        lbAIU_23->setObjectName(QString::fromUtf8("lbAIU_23"));
        lbAIU_23->setGeometry(QRect(435, 495, 51, 20));
        lbAIU_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_23->setFont(font);
        lbAIU_23->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_9 = new WLabel(panel1);
        lbAI_9->setObjectName(QString::fromUtf8("lbAI_9"));
        lbAI_9->setGeometry(QRect(366, 215, 61, 20));
        lbAI_9->setFont(font);
        lbAI_9->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_1 = new WLabel(panel1);
        lbNumAI_1->setObjectName(QString::fromUtf8("lbNumAI_1"));
        lbNumAI_1->setGeometry(QRect(8, 55, 21, 16));
        lbNumAI_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_1->setFont(font);
        lbNumAI_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_23 = new WLabel(panel1);
        lbAI_23->setObjectName(QString::fromUtf8("lbAI_23"));
        lbAI_23->setGeometry(QRect(366, 495, 61, 20));
        lbAI_23->setFont(font);
        lbAI_23->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_11 = new WLabel(panel1);
        lbAI_11->setObjectName(QString::fromUtf8("lbAI_11"));
        lbAI_11->setGeometry(QRect(366, 255, 61, 20));
        lbAI_11->setFont(font);
        lbAI_11->setProperty("Alineacion", QVariant(WLabel::Derecha));
        frame_2 = new QFrame(panel1);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(1, 20, 485, 30));
        frame_2->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Sunken);
        frame_2->setLineWidth(2);
        lbSloAl = new WLabel(frame_2);
        lbSloAl->setObjectName(QString::fromUtf8("lbSloAl"));
        lbSloAl->setGeometry(QRect(56, 6, 400, 15));
        lbSloAl->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        lbSloAl->setFont(font1);
        lbSloAl->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_23 = new WLabel(panel1);
        lbAIT_23->setObjectName(QString::fromUtf8("lbAIT_23"));
        lbAIT_23->setGeometry(QRect(35, 495, 311, 16));
        lbAIT_23->setFont(font);
        lbAIT_23->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_12 = new WLabel(panel1);
        lbAIU_12->setObjectName(QString::fromUtf8("lbAIU_12"));
        lbAIU_12->setGeometry(QRect(436, 275, 31, 20));
        lbAIU_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_12->setFont(font);
        lbAIU_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_1 = new WLabel(panel1);
        lbAIU_1->setObjectName(QString::fromUtf8("lbAIU_1"));
        lbAIU_1->setGeometry(QRect(436, 55, 31, 20));
        lbAIU_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_1->setFont(font);
        lbAIU_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_24 = new WLabel(panel1);
        lbAIU_24->setObjectName(QString::fromUtf8("lbAIU_24"));
        lbAIU_24->setGeometry(QRect(435, 515, 51, 20));
        lbAIU_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_24->setFont(font);
        lbAIU_24->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_13 = new WLabel(panel1);
        lbNumAI_13->setObjectName(QString::fromUtf8("lbNumAI_13"));
        lbNumAI_13->setGeometry(QRect(10, 295, 21, 16));
        lbNumAI_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_13->setFont(font);
        lbNumAI_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_24 = new WLabel(panel1);
        lbNumAI_24->setObjectName(QString::fromUtf8("lbNumAI_24"));
        lbNumAI_24->setGeometry(QRect(10, 515, 21, 16));
        lbNumAI_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_24->setFont(font);
        lbNumAI_24->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_12 = new WLabel(panel1);
        lbAIT_12->setObjectName(QString::fromUtf8("lbAIT_12"));
        lbAIT_12->setGeometry(QRect(35, 275, 340, 16));
        lbAIT_12->setFont(font);
        lbAIT_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_24 = new WLabel(panel1);
        lbAIT_24->setObjectName(QString::fromUtf8("lbAIT_24"));
        lbAIT_24->setGeometry(QRect(35, 515, 311, 16));
        lbAIT_24->setFont(font);
        lbAIT_24->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frBarraT = new QFrame(panel1);
        frBarraT->setObjectName(QString::fromUtf8("frBarraT"));
        frBarraT->setGeometry(QRect(1, 0, 485, 15));
        frBarraT->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frBarraT->setFrameShape(QFrame::Panel);
        frBarraT->setFrameShadow(QFrame::Raised);
        frBarraT->setLineWidth(0);
        lbAna24T = new WLabel(frBarraT);
        lbAna24T->setObjectName(QString::fromUtf8("lbAna24T"));
        lbAna24T->setGeometry(QRect(3, 0, 81, 12));
        lbAna24T->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        QFont font2;
        font2.setPointSize(5);
        font2.setBold(true);
        font2.setWeight(75);
        lbAna24T->setFont(font2);
        lbAna24T->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_13 = new WLabel(panel1);
        lbAIT_13->setObjectName(QString::fromUtf8("lbAIT_13"));
        lbAIT_13->setGeometry(QRect(35, 295, 340, 16));
        lbAIT_13->setFont(font);
        lbAIT_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_24 = new WLabel(panel1);
        lbAI_24->setObjectName(QString::fromUtf8("lbAI_24"));
        lbAI_24->setGeometry(QRect(366, 515, 61, 20));
        lbAI_24->setFont(font);
        lbAI_24->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_14 = new WLabel(panel1);
        lbAIT_14->setObjectName(QString::fromUtf8("lbAIT_14"));
        lbAIT_14->setGeometry(QRect(35, 315, 340, 16));
        lbAIT_14->setFont(font);
        lbAIT_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_15 = new WLabel(panel1);
        lbAIT_15->setObjectName(QString::fromUtf8("lbAIT_15"));
        lbAIT_15->setGeometry(QRect(35, 335, 340, 16));
        lbAIT_15->setFont(font);
        lbAIT_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_14 = new WLabel(panel1);
        lbNumAI_14->setObjectName(QString::fromUtf8("lbNumAI_14"));
        lbNumAI_14->setGeometry(QRect(10, 315, 21, 16));
        lbNumAI_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_14->setFont(font);
        lbNumAI_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_11 = new WLabel(panel1);
        lbAIT_11->setObjectName(QString::fromUtf8("lbAIT_11"));
        lbAIT_11->setGeometry(QRect(35, 255, 340, 16));
        lbAIT_11->setFont(font);
        lbAIT_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_13 = new WLabel(panel1);
        lbAIU_13->setObjectName(QString::fromUtf8("lbAIU_13"));
        lbAIU_13->setGeometry(QRect(436, 295, 31, 20));
        lbAIU_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_13->setFont(font);
        lbAIU_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_15 = new WLabel(panel1);
        lbAI_15->setObjectName(QString::fromUtf8("lbAI_15"));
        lbAI_15->setGeometry(QRect(366, 335, 61, 20));
        lbAI_15->setFont(font);
        lbAI_15->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_13 = new WLabel(panel1);
        lbAI_13->setObjectName(QString::fromUtf8("lbAI_13"));
        lbAI_13->setGeometry(QRect(366, 295, 61, 20));
        lbAI_13->setFont(font);
        lbAI_13->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_15 = new WLabel(panel1);
        lbAIU_15->setObjectName(QString::fromUtf8("lbAIU_15"));
        lbAIU_15->setGeometry(QRect(436, 335, 31, 20));
        lbAIU_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_15->setFont(font);
        lbAIU_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_14 = new WLabel(panel1);
        lbAI_14->setObjectName(QString::fromUtf8("lbAI_14"));
        lbAI_14->setGeometry(QRect(366, 315, 61, 20));
        lbAI_14->setFont(font);
        lbAI_14->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_15 = new WLabel(panel1);
        lbNumAI_15->setObjectName(QString::fromUtf8("lbNumAI_15"));
        lbNumAI_15->setGeometry(QRect(10, 335, 21, 16));
        lbNumAI_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_15->setFont(font);
        lbNumAI_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_7 = new WLabel(panel1);
        lbNumAI_7->setObjectName(QString::fromUtf8("lbNumAI_7"));
        lbNumAI_7->setGeometry(QRect(10, 175, 21, 16));
        lbNumAI_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_7->setFont(font);
        lbNumAI_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_16 = new WLabel(panel1);
        lbAIT_16->setObjectName(QString::fromUtf8("lbAIT_16"));
        lbAIT_16->setGeometry(QRect(35, 355, 340, 16));
        lbAIT_16->setFont(font);
        lbAIT_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_8 = new WLabel(panel1);
        lbAIU_8->setObjectName(QString::fromUtf8("lbAIU_8"));
        lbAIU_8->setGeometry(QRect(436, 195, 31, 20));
        lbAIU_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_8->setFont(font);
        lbAIU_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_16 = new WLabel(panel1);
        lbAI_16->setObjectName(QString::fromUtf8("lbAI_16"));
        lbAI_16->setGeometry(QRect(366, 355, 61, 20));
        lbAI_16->setFont(font);
        lbAI_16->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_4 = new WLabel(panel1);
        lbAIU_4->setObjectName(QString::fromUtf8("lbAIU_4"));
        lbAIU_4->setGeometry(QRect(436, 115, 31, 20));
        lbAIU_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_4->setFont(font);
        lbAIU_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_16 = new WLabel(panel1);
        lbAIU_16->setObjectName(QString::fromUtf8("lbAIU_16"));
        lbAIU_16->setGeometry(QRect(436, 355, 31, 20));
        lbAIU_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_16->setFont(font);
        lbAIU_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_4 = new WLabel(panel1);
        lbNumAI_4->setObjectName(QString::fromUtf8("lbNumAI_4"));
        lbNumAI_4->setGeometry(QRect(10, 115, 21, 16));
        lbNumAI_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_4->setFont(font);
        lbNumAI_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_17 = new WLabel(panel1);
        lbNumAI_17->setObjectName(QString::fromUtf8("lbNumAI_17"));
        lbNumAI_17->setGeometry(QRect(10, 375, 21, 16));
        lbNumAI_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_17->setFont(font);
        lbNumAI_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_3 = new WLabel(panel1);
        lbAIT_3->setObjectName(QString::fromUtf8("lbAIT_3"));
        lbAIT_3->setGeometry(QRect(35, 95, 340, 16));
        lbAIT_3->setFont(font);
        lbAIT_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_17 = new WLabel(panel1);
        lbAIU_17->setObjectName(QString::fromUtf8("lbAIU_17"));
        lbAIU_17->setGeometry(QRect(436, 375, 31, 20));
        lbAIU_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_17->setFont(font);
        lbAIU_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_5 = new WLabel(panel1);
        lbAI_5->setObjectName(QString::fromUtf8("lbAI_5"));
        lbAI_5->setGeometry(QRect(366, 135, 59, 20));
        lbAI_5->setFont(font);
        lbAI_5->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_17 = new WLabel(panel1);
        lbAI_17->setObjectName(QString::fromUtf8("lbAI_17"));
        lbAI_17->setGeometry(QRect(366, 375, 61, 20));
        lbAI_17->setFont(font);
        lbAI_17->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_6 = new WLabel(panel1);
        lbAI_6->setObjectName(QString::fromUtf8("lbAI_6"));
        lbAI_6->setGeometry(QRect(366, 155, 59, 20));
        lbAI_6->setFont(font);
        lbAI_6->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_17 = new WLabel(panel1);
        lbAIT_17->setObjectName(QString::fromUtf8("lbAIT_17"));
        lbAIT_17->setGeometry(QRect(35, 375, 340, 16));
        lbAIT_17->setFont(font);
        lbAIT_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_18 = new WLabel(panel1);
        lbNumAI_18->setObjectName(QString::fromUtf8("lbNumAI_18"));
        lbNumAI_18->setGeometry(QRect(10, 395, 21, 16));
        lbNumAI_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_18->setFont(font);
        lbNumAI_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_4 = new WLabel(panel1);
        lbAI_4->setObjectName(QString::fromUtf8("lbAI_4"));
        lbAI_4->setGeometry(QRect(366, 115, 59, 20));
        lbAI_4->setFont(font);
        lbAI_4->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_18 = new WLabel(panel1);
        lbAI_18->setObjectName(QString::fromUtf8("lbAI_18"));
        lbAI_18->setGeometry(QRect(366, 395, 61, 20));
        lbAI_18->setFont(font);
        lbAI_18->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_5 = new WLabel(panel1);
        lbNumAI_5->setObjectName(QString::fromUtf8("lbNumAI_5"));
        lbNumAI_5->setGeometry(QRect(10, 135, 21, 16));
        lbNumAI_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_5->setFont(font);
        lbNumAI_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_18 = new WLabel(panel1);
        lbAIU_18->setObjectName(QString::fromUtf8("lbAIU_18"));
        lbAIU_18->setGeometry(QRect(436, 395, 31, 20));
        lbAIU_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_18->setFont(font);
        lbAIU_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_4 = new WLabel(panel1);
        lbAIT_4->setObjectName(QString::fromUtf8("lbAIT_4"));
        lbAIT_4->setGeometry(QRect(35, 115, 340, 16));
        lbAIT_4->setFont(font);
        lbAIT_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_18 = new WLabel(panel1);
        lbAIT_18->setObjectName(QString::fromUtf8("lbAIT_18"));
        lbAIT_18->setGeometry(QRect(35, 395, 340, 16));
        lbAIT_18->setFont(font);
        lbAIT_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_3 = new WLabel(panel1);
        lbAI_3->setObjectName(QString::fromUtf8("lbAI_3"));
        lbAI_3->setGeometry(QRect(366, 95, 59, 20));
        lbAI_3->setFont(font);
        lbAI_3->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_19 = new WLabel(panel1);
        lbNumAI_19->setObjectName(QString::fromUtf8("lbNumAI_19"));
        lbNumAI_19->setGeometry(QRect(10, 415, 21, 16));
        lbNumAI_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_19->setFont(font);
        lbNumAI_19->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_8 = new WLabel(panel1);
        lbNumAI_8->setObjectName(QString::fromUtf8("lbNumAI_8"));
        lbNumAI_8->setGeometry(QRect(10, 195, 21, 16));
        lbNumAI_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_8->setFont(font);
        lbNumAI_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_16 = new WLabel(panel1);
        lbNumAI_16->setObjectName(QString::fromUtf8("lbNumAI_16"));
        lbNumAI_16->setGeometry(QRect(10, 355, 21, 16));
        lbNumAI_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_16->setFont(font);
        lbNumAI_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_19 = new WLabel(panel1);
        lbAIT_19->setObjectName(QString::fromUtf8("lbAIT_19"));
        lbAIT_19->setGeometry(QRect(35, 415, 340, 16));
        lbAIT_19->setFont(font);
        lbAIT_19->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_7 = new WLabel(panel1);
        lbAIT_7->setObjectName(QString::fromUtf8("lbAIT_7"));
        lbAIT_7->setGeometry(QRect(35, 175, 340, 16));
        lbAIT_7->setFont(font);
        lbAIT_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_7 = new WLabel(panel1);
        lbAIU_7->setObjectName(QString::fromUtf8("lbAIU_7"));
        lbAIU_7->setGeometry(QRect(436, 175, 31, 20));
        lbAIU_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_7->setFont(font);
        lbAIU_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_19 = new WLabel(panel1);
        lbAIU_19->setObjectName(QString::fromUtf8("lbAIU_19"));
        lbAIU_19->setGeometry(QRect(436, 415, 31, 20));
        lbAIU_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_19->setFont(font);
        lbAIU_19->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_9 = new WLabel(panel1);
        lbAIU_9->setObjectName(QString::fromUtf8("lbAIU_9"));
        lbAIU_9->setGeometry(QRect(436, 215, 31, 20));
        lbAIU_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_9->setFont(font);
        lbAIU_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_6 = new WLabel(panel1);
        lbNumAI_6->setObjectName(QString::fromUtf8("lbNumAI_6"));
        lbNumAI_6->setGeometry(QRect(10, 155, 21, 16));
        lbNumAI_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_6->setFont(font);
        lbNumAI_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_19 = new WLabel(panel1);
        lbAI_19->setObjectName(QString::fromUtf8("lbAI_19"));
        lbAI_19->setGeometry(QRect(366, 415, 61, 20));
        lbAI_19->setFont(font);
        lbAI_19->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_8 = new WLabel(panel1);
        lbAIT_8->setObjectName(QString::fromUtf8("lbAIT_8"));
        lbAIT_8->setGeometry(QRect(35, 195, 340, 16));
        lbAIT_8->setFont(font);
        lbAIT_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_6 = new WLabel(panel1);
        lbAIT_6->setObjectName(QString::fromUtf8("lbAIT_6"));
        lbAIT_6->setGeometry(QRect(33, 155, 340, 16));
        lbAIT_6->setFont(font);
        lbAIT_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_20 = new WLabel(panel1);
        lbNumAI_20->setObjectName(QString::fromUtf8("lbNumAI_20"));
        lbNumAI_20->setGeometry(QRect(10, 435, 21, 16));
        lbNumAI_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_20->setFont(font);
        lbNumAI_20->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_8 = new WLabel(panel1);
        lbAI_8->setObjectName(QString::fromUtf8("lbAI_8"));
        lbAI_8->setGeometry(QRect(366, 195, 61, 20));
        lbAI_8->setFont(font);
        lbAI_8->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_14 = new WLabel(panel1);
        lbAIU_14->setObjectName(QString::fromUtf8("lbAIU_14"));
        lbAIU_14->setGeometry(QRect(436, 315, 31, 20));
        lbAIU_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_14->setFont(font);
        lbAIU_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_20 = new WLabel(panel1);
        lbAIU_20->setObjectName(QString::fromUtf8("lbAIU_20"));
        lbAIU_20->setGeometry(QRect(435, 435, 51, 20));
        lbAIU_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_20->setFont(font);
        lbAIU_20->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_9 = new WLabel(panel1);
        lbNumAI_9->setObjectName(QString::fromUtf8("lbNumAI_9"));
        lbNumAI_9->setGeometry(QRect(10, 215, 21, 16));
        lbNumAI_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_9->setFont(font);
        lbNumAI_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_6 = new WLabel(panel1);
        lbAIU_6->setObjectName(QString::fromUtf8("lbAIU_6"));
        lbAIU_6->setGeometry(QRect(436, 155, 31, 20));
        lbAIU_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_6->setFont(font);
        lbAIU_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_20 = new WLabel(panel1);
        lbAIT_20->setObjectName(QString::fromUtf8("lbAIT_20"));
        lbAIT_20->setGeometry(QRect(35, 435, 311, 16));
        lbAIT_20->setFont(font);
        lbAIT_20->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_9 = new WLabel(panel1);
        lbAIT_9->setObjectName(QString::fromUtf8("lbAIT_9"));
        lbAIT_9->setGeometry(QRect(35, 215, 340, 16));
        lbAIT_9->setFont(font);
        lbAIT_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbFondo->raise();
        lbAIT_5->raise();
        lbAI_20->raise();
        lbAIT_10->raise();
        lbAIT_1->raise();
        lbNumAI_21->raise();
        lbNumAI_10->raise();
        lbAI_2->raise();
        lbAIU_21->raise();
        lbAI_7->raise();
        lbNumAI_3->raise();
        lbAI_21->raise();
        lbAIU_5->raise();
        lbNumAI_2->raise();
        lbAIT_21->raise();
        lbAI_10->raise();
        lbAIU_3->raise();
        lbNumAI_22->raise();
        lbNumAI_11->raise();
        lbAI_1->raise();
        lbAIU_22->raise();
        lbAIU_10->raise();
        lbAIU_2->raise();
        lbAIT_22->raise();
        lbAIU_11->raise();
        lbAIT_2->raise();
        lbAI_22->raise();
        lbAI_12->raise();
        lbNumAI_23->raise();
        lbNumAI_12->raise();
        lbAIU_23->raise();
        lbAI_9->raise();
        lbNumAI_1->raise();
        lbAI_23->raise();
        lbAI_11->raise();
        lbAIT_23->raise();
        lbAIU_12->raise();
        lbAIU_1->raise();
        lbAIU_24->raise();
        lbNumAI_13->raise();
        lbNumAI_24->raise();
        lbAIT_12->raise();
        lbAIT_24->raise();
        frBarraT->raise();
        lbAIT_13->raise();
        lbAI_24->raise();
        lbAIT_14->raise();
        lbAIT_15->raise();
        lbNumAI_14->raise();
        lbAIT_11->raise();
        lbAIU_13->raise();
        lbAI_15->raise();
        lbAI_13->raise();
        lbAIU_15->raise();
        lbAI_14->raise();
        lbNumAI_15->raise();
        lbNumAI_7->raise();
        lbAIT_16->raise();
        lbAIU_8->raise();
        lbAI_16->raise();
        lbAIU_4->raise();
        lbAIU_16->raise();
        lbNumAI_4->raise();
        lbNumAI_17->raise();
        lbAIT_3->raise();
        lbAIU_17->raise();
        lbAI_5->raise();
        lbAI_17->raise();
        lbAI_6->raise();
        lbAIT_17->raise();
        lbNumAI_18->raise();
        lbAI_4->raise();
        lbAI_18->raise();
        lbNumAI_5->raise();
        lbAIU_18->raise();
        lbAIT_4->raise();
        lbAIT_18->raise();
        lbAI_3->raise();
        lbNumAI_19->raise();
        lbNumAI_8->raise();
        lbNumAI_16->raise();
        lbAIT_19->raise();
        lbAIT_7->raise();
        lbAIU_7->raise();
        lbAIU_19->raise();
        lbAIU_9->raise();
        lbNumAI_6->raise();
        lbAI_19->raise();
        lbAIT_8->raise();
        lbAIT_6->raise();
        lbNumAI_20->raise();
        lbAI_8->raise();
        lbAIU_14->raise();
        lbAIU_20->raise();
        lbNumAI_9->raise();
        lbAIU_6->raise();
        lbAIT_20->raise();
        lbAIT_9->raise();
        frame_2->raise();
        panel2 = new QFrame(Analog24);
        panel2->setObjectName(QString::fromUtf8("panel2"));
        panel2->setGeometry(QRect(0, 0, 485, 530));
        panel2->setFrameShape(QFrame::StyledPanel);
        panel2->setFrameShadow(QFrame::Raised);
        lbAIT_25 = new WLabel(panel2);
        lbAIT_25->setObjectName(QString::fromUtf8("lbAIT_25"));
        lbAIT_25->setGeometry(QRect(35, 135, 340, 16));
        lbAIT_25->setFont(font);
        lbAIT_25->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_27 = new WLabel(panel2);
        lbAIT_27->setObjectName(QString::fromUtf8("lbAIT_27"));
        lbAIT_27->setGeometry(QRect(33, 55, 340, 16));
        lbAIT_27->setFont(font);
        lbAIT_27->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_26 = new WLabel(panel2);
        lbAI_26->setObjectName(QString::fromUtf8("lbAI_26"));
        lbAI_26->setGeometry(QRect(366, 75, 59, 20));
        lbAI_26->setFont(font);
        lbAI_26->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_27 = new WLabel(panel2);
        lbAI_27->setObjectName(QString::fromUtf8("lbAI_27"));
        lbAI_27->setGeometry(QRect(366, 175, 61, 20));
        lbAI_27->setFont(font);
        lbAI_27->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_27 = new WLabel(panel2);
        lbNumAI_27->setObjectName(QString::fromUtf8("lbNumAI_27"));
        lbNumAI_27->setGeometry(QRect(10, 95, 21, 16));
        lbNumAI_27->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_27->setFont(font);
        lbNumAI_27->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_26 = new WLabel(panel2);
        lbAIU_26->setObjectName(QString::fromUtf8("lbAIU_26"));
        lbAIU_26->setGeometry(QRect(436, 135, 31, 20));
        lbAIU_26->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_26->setFont(font);
        lbAIU_26->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_28 = new WLabel(panel2);
        lbNumAI_28->setObjectName(QString::fromUtf8("lbNumAI_28"));
        lbNumAI_28->setGeometry(QRect(8, 75, 21, 16));
        lbNumAI_28->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_28->setFont(font);
        lbNumAI_28->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_27 = new WLabel(panel2);
        lbAIU_27->setObjectName(QString::fromUtf8("lbAIU_27"));
        lbAIU_27->setGeometry(QRect(436, 95, 31, 20));
        lbAIU_27->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_27->setFont(font);
        lbAIU_27->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_30 = new WLabel(panel2);
        lbAI_30->setObjectName(QString::fromUtf8("lbAI_30"));
        lbAI_30->setGeometry(QRect(366, 55, 59, 20));
        lbAI_30->setFont(font);
        lbAI_30->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_30 = new WLabel(panel2);
        lbAIU_30->setObjectName(QString::fromUtf8("lbAIU_30"));
        lbAIU_30->setGeometry(QRect(436, 75, 31, 20));
        lbAIU_30->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_30->setFont(font);
        lbAIU_30->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_30 = new WLabel(panel2);
        lbAIT_30->setObjectName(QString::fromUtf8("lbAIT_30"));
        lbAIT_30->setGeometry(QRect(33, 75, 340, 16));
        lbAIT_30->setFont(font);
        lbAIT_30->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbFondo_2 = new QLabel(panel2);
        lbFondo_2->setObjectName(QString::fromUtf8("lbFondo_2"));
        lbFondo_2->setGeometry(QRect(0, 0, 485, 590));
        lbFondo_2->setMinimumSize(QSize(485, 590));
        lbFondo_2->setMaximumSize(QSize(485, 590));
        lbFondo_2->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbNumAI_33 = new WLabel(panel2);
        lbNumAI_33->setObjectName(QString::fromUtf8("lbNumAI_33"));
        lbNumAI_33->setGeometry(QRect(8, 55, 21, 16));
        lbNumAI_33->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_33->setFont(font);
        lbNumAI_33->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame_3 = new QFrame(panel2);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(1, 20, 485, 30));
        frame_3->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame_3->setFrameShape(QFrame::Box);
        frame_3->setFrameShadow(QFrame::Sunken);
        frame_3->setLineWidth(2);
        lbSloAl_2 = new WLabel(frame_3);
        lbSloAl_2->setObjectName(QString::fromUtf8("lbSloAl_2"));
        lbSloAl_2->setGeometry(QRect(56, 6, 400, 15));
        lbSloAl_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        lbSloAl_2->setFont(font1);
        lbSloAl_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_34 = new WLabel(panel2);
        lbAIU_34->setObjectName(QString::fromUtf8("lbAIU_34"));
        lbAIU_34->setGeometry(QRect(436, 55, 31, 20));
        lbAIU_34->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_34->setFont(font);
        lbAIU_34->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frBarraT_2 = new QFrame(panel2);
        frBarraT_2->setObjectName(QString::fromUtf8("frBarraT_2"));
        frBarraT_2->setGeometry(QRect(1, 0, 485, 15));
        frBarraT_2->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frBarraT_2->setFrameShape(QFrame::Panel);
        frBarraT_2->setFrameShadow(QFrame::Raised);
        frBarraT_2->setLineWidth(0);
        lbAna24T_2 = new WLabel(frBarraT_2);
        lbAna24T_2->setObjectName(QString::fromUtf8("lbAna24T_2"));
        lbAna24T_2->setGeometry(QRect(3, 0, 81, 12));
        lbAna24T_2->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        lbAna24T_2->setFont(font2);
        lbAna24T_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_38 = new WLabel(panel2);
        lbNumAI_38->setObjectName(QString::fromUtf8("lbNumAI_38"));
        lbNumAI_38->setGeometry(QRect(10, 175, 21, 16));
        lbNumAI_38->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_38->setFont(font);
        lbNumAI_38->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_38 = new WLabel(panel2);
        lbAIU_38->setObjectName(QString::fromUtf8("lbAIU_38"));
        lbAIU_38->setGeometry(QRect(436, 195, 31, 20));
        lbAIU_38->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_38->setFont(font);
        lbAIU_38->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_39 = new WLabel(panel2);
        lbAIU_39->setObjectName(QString::fromUtf8("lbAIU_39"));
        lbAIU_39->setGeometry(QRect(436, 115, 31, 20));
        lbAIU_39->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_39->setFont(font);
        lbAIU_39->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_39 = new WLabel(panel2);
        lbNumAI_39->setObjectName(QString::fromUtf8("lbNumAI_39"));
        lbNumAI_39->setGeometry(QRect(10, 115, 21, 16));
        lbNumAI_39->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_39->setFont(font);
        lbNumAI_39->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_39 = new WLabel(panel2);
        lbAIT_39->setObjectName(QString::fromUtf8("lbAIT_39"));
        lbAIT_39->setGeometry(QRect(35, 95, 340, 16));
        lbAIT_39->setFont(font);
        lbAIT_39->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_41 = new WLabel(panel2);
        lbAI_41->setObjectName(QString::fromUtf8("lbAI_41"));
        lbAI_41->setGeometry(QRect(366, 135, 59, 20));
        lbAI_41->setFont(font);
        lbAI_41->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_43 = new WLabel(panel2);
        lbAI_43->setObjectName(QString::fromUtf8("lbAI_43"));
        lbAI_43->setGeometry(QRect(366, 155, 59, 20));
        lbAI_43->setFont(font);
        lbAI_43->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_44 = new WLabel(panel2);
        lbAI_44->setObjectName(QString::fromUtf8("lbAI_44"));
        lbAI_44->setGeometry(QRect(366, 115, 59, 20));
        lbAI_44->setFont(font);
        lbAI_44->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_42 = new WLabel(panel2);
        lbNumAI_42->setObjectName(QString::fromUtf8("lbNumAI_42"));
        lbNumAI_42->setGeometry(QRect(10, 135, 21, 16));
        lbNumAI_42->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_42->setFont(font);
        lbNumAI_42->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_41 = new WLabel(panel2);
        lbAIT_41->setObjectName(QString::fromUtf8("lbAIT_41"));
        lbAIT_41->setGeometry(QRect(35, 115, 340, 16));
        lbAIT_41->setFont(font);
        lbAIT_41->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_46 = new WLabel(panel2);
        lbAI_46->setObjectName(QString::fromUtf8("lbAI_46"));
        lbAI_46->setGeometry(QRect(366, 95, 59, 20));
        lbAI_46->setFont(font);
        lbAI_46->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_44 = new WLabel(panel2);
        lbNumAI_44->setObjectName(QString::fromUtf8("lbNumAI_44"));
        lbNumAI_44->setGeometry(QRect(10, 195, 21, 16));
        lbNumAI_44->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_44->setFont(font);
        lbNumAI_44->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_44 = new WLabel(panel2);
        lbAIT_44->setObjectName(QString::fromUtf8("lbAIT_44"));
        lbAIT_44->setGeometry(QRect(35, 175, 340, 16));
        lbAIT_44->setFont(font);
        lbAIT_44->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_43 = new WLabel(panel2);
        lbAIU_43->setObjectName(QString::fromUtf8("lbAIU_43"));
        lbAIU_43->setGeometry(QRect(436, 175, 31, 20));
        lbAIU_43->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_43->setFont(font);
        lbAIU_43->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_46 = new WLabel(panel2);
        lbNumAI_46->setObjectName(QString::fromUtf8("lbNumAI_46"));
        lbNumAI_46->setGeometry(QRect(10, 155, 21, 16));
        lbNumAI_46->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_46->setFont(font);
        lbNumAI_46->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_45 = new WLabel(panel2);
        lbAIT_45->setObjectName(QString::fromUtf8("lbAIT_45"));
        lbAIT_45->setGeometry(QRect(35, 195, 340, 16));
        lbAIT_45->setFont(font);
        lbAIT_45->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_46 = new WLabel(panel2);
        lbAIT_46->setObjectName(QString::fromUtf8("lbAIT_46"));
        lbAIT_46->setGeometry(QRect(33, 155, 340, 16));
        lbAIT_46->setFont(font);
        lbAIT_46->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_48 = new WLabel(panel2);
        lbAI_48->setObjectName(QString::fromUtf8("lbAI_48"));
        lbAI_48->setGeometry(QRect(366, 195, 61, 20));
        lbAI_48->setFont(font);
        lbAI_48->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_48 = new WLabel(panel2);
        lbAIU_48->setObjectName(QString::fromUtf8("lbAIU_48"));
        lbAIU_48->setGeometry(QRect(436, 155, 31, 20));
        lbAIU_48->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_48->setFont(font);
        lbAIU_48->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbFondo_2->raise();
        lbAIT_25->raise();
        lbAIT_27->raise();
        lbAI_26->raise();
        lbAI_27->raise();
        lbNumAI_27->raise();
        lbAIU_26->raise();
        lbNumAI_28->raise();
        lbAIU_27->raise();
        lbAI_30->raise();
        lbAIU_30->raise();
        lbAIT_30->raise();
        lbNumAI_33->raise();
        frame_3->raise();
        lbAIU_34->raise();
        frBarraT_2->raise();
        lbNumAI_38->raise();
        lbAIU_38->raise();
        lbAIU_39->raise();
        lbNumAI_39->raise();
        lbAIT_39->raise();
        lbAI_41->raise();
        lbAI_43->raise();
        lbAI_44->raise();
        lbNumAI_42->raise();
        lbAIT_41->raise();
        lbAI_46->raise();
        lbNumAI_44->raise();
        lbAIT_44->raise();
        lbAIU_43->raise();
        lbNumAI_46->raise();
        lbAIT_45->raise();
        lbAIT_46->raise();
        lbAI_48->raise();
        lbAIU_48->raise();
        frame = new QFrame(Analog24);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 529, 486, 62));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        btnProx = new QPushButton(frame);
        btnProx->setObjectName(QString::fromUtf8("btnProx"));
        btnProx->setGeometry(QRect(290, 10, 101, 41));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        btnProx->setFont(font3);
        btnProx->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnCerrar = new QPushButton(frame);
        btnCerrar->setObjectName(QString::fromUtf8("btnCerrar"));
        btnCerrar->setGeometry(QRect(140, 10, 101, 41));
        btnCerrar->setFont(font3);
        btnCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        frame->raise();
        panel2->raise();
        panel1->raise();

        retranslateUi(Analog24);

        QMetaObject::connectSlotsByName(Analog24);
    } // setupUi

    void retranslateUi(QWidget *Analog24)
    {
        Analog24->setWindowTitle(QApplication::translate("Analog24", "Analog24", 0, QApplication::UnicodeUTF8));
        lbAIT_5->setText(QApplication::translate("Analog24", "T3A1 HPC TEMP DE DESCARGA", 0, QApplication::UnicodeUTF8));
        lbAI_20->setText(QApplication::translate("Analog24", "21370.00", 0, QApplication::UnicodeUTF8));
        lbAIT_10->setText(QApplication::translate("Analog24", "SENSOR A TEMPERATURA DE GAS COMB (TGSA)", 0, QApplication::UnicodeUTF8));
        lbAIT_1->setText(QApplication::translate("Analog24", "TEMP DE ENTRADA DE GAS LPT T48A", 0, QApplication::UnicodeUTF8));
        lbNumAI_21->setText(QApplication::translate("Analog24", "21", 0, QApplication::UnicodeUTF8));
        lbNumAI_10->setText(QApplication::translate("Analog24", "10", 0, QApplication::UnicodeUTF8));
        lbAI_2->setText(QApplication::translate("Analog24", "1531.00", 0, QApplication::UnicodeUTF8));
        lbAIU_21->setText(QApplication::translate("Analog24", "%", 0, QApplication::UnicodeUTF8));
        lbAI_7->setText(QApplication::translate("Analog24", "49.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_3->setText(QApplication::translate("Analog24", "3", 0, QApplication::UnicodeUTF8));
        lbAI_21->setText(QApplication::translate("Analog24", "45.00", 0, QApplication::UnicodeUTF8));
        lbAIU_5->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_2->setText(QApplication::translate("Analog24", "2", 0, QApplication::UnicodeUTF8));
        lbAIT_21->setText(QApplication::translate("Analog24", "VALV DE MDCION DE GAS COMB - RETRO DE Pl", 0, QApplication::UnicodeUTF8));
        lbAI_10->setText(QApplication::translate("Analog24", "78.00", 0, QApplication::UnicodeUTF8));
        lbAIU_3->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_22->setText(QApplication::translate("Analog24", "22", 0, QApplication::UnicodeUTF8));
        lbNumAI_11->setText(QApplication::translate("Analog24", "11", 0, QApplication::UnicodeUTF8));
        lbAI_1->setText(QApplication::translate("Analog24", "1576.00", 0, QApplication::UnicodeUTF8));
        lbAIU_22->setText(QApplication::translate("Analog24", "%", 0, QApplication::UnicodeUTF8));
        lbAIU_10->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_2->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_22->setText(QApplication::translate("Analog24", "VALV DE MDCION DE GAS COMB - RETRO INTER", 0, QApplication::UnicodeUTF8));
        lbAIU_11->setText(QString());
        lbAIT_2->setText(QApplication::translate("Analog24", "TEMP DE ENTRADA DE GAS LPT T48C (ABAJO)", 0, QApplication::UnicodeUTF8));
        lbAI_22->setText(QApplication::translate("Analog24", "29.10", 0, QApplication::UnicodeUTF8));
        lbAI_12->setText(QApplication::translate("Analog24", "10.00", 0, QApplication::UnicodeUTF8));
        lbFondo->setText(QString());
        lbNumAI_23->setText(QApplication::translate("Analog24", "23", 0, QApplication::UnicodeUTF8));
        lbNumAI_12->setText(QApplication::translate("Analog24", "12", 0, QApplication::UnicodeUTF8));
        lbAIU_23->setText(QApplication::translate("Analog24", "%", 0, QApplication::UnicodeUTF8));
        lbAI_9->setText(QApplication::translate("Analog24", "10.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_1->setText(QApplication::translate("Analog24", "1", 0, QApplication::UnicodeUTF8));
        lbAI_23->setText(QApplication::translate("Analog24", "43.20", 0, QApplication::UnicodeUTF8));
        lbAI_11->setText(QApplication::translate("Analog24", "10.00", 0, QApplication::UnicodeUTF8));
        lbSloAl->setText(QApplication::translate("Analog24", "SLOT-  A106  - Al", 0, QApplication::UnicodeUTF8));
        lbAIT_23->setText(QApplication::translate("Analog24", "VALV DE MDCION DE GAS COMB - RETRO EXTRN", 0, QApplication::UnicodeUTF8));
        lbAIU_12->setText(QString());
        lbAIU_1->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_24->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbNumAI_13->setText(QApplication::translate("Analog24", "13", 0, QApplication::UnicodeUTF8));
        lbNumAI_24->setText(QApplication::translate("Analog24", "24", 0, QApplication::UnicodeUTF8));
        lbAIT_12->setText(QApplication::translate("Analog24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIT_24->setText(QApplication::translate("Analog24", "PS3A PRES ST DE DESCARGA HPC", 0, QApplication::UnicodeUTF8));
        lbAna24T->setText(QApplication::translate("Analog24", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">ANALOG24.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbAIT_13->setText(QApplication::translate("Analog24", "PRES EST\303\201TICA DE ENTRADA P0", 0, QApplication::UnicodeUTF8));
        lbAI_24->setText(QApplication::translate("Analog24", "326.20", 0, QApplication::UnicodeUTF8));
        lbAIT_14->setText(QApplication::translate("Analog24", "P25A HPC PRES TOTAL ENTRADA \"A\"", 0, QApplication::UnicodeUTF8));
        lbAIT_15->setText(QApplication::translate("Analog24", "PRESI\303\223N DIN\303\201MICA AC\303\232STICA (PX36A)", 0, QApplication::UnicodeUTF8));
        lbNumAI_14->setText(QApplication::translate("Analog24", "14", 0, QApplication::UnicodeUTF8));
        lbAIT_11->setText(QApplication::translate("Analog24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIU_13->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbAI_15->setText(QApplication::translate("Analog24", "2.24", 0, QApplication::UnicodeUTF8));
        lbAI_13->setText(QApplication::translate("Analog24", "11.00", 0, QApplication::UnicodeUTF8));
        lbAIU_15->setText(QApplication::translate("Analog24", "PSID", 0, QApplication::UnicodeUTF8));
        lbAI_14->setText(QApplication::translate("Analog24", "27.60", 0, QApplication::UnicodeUTF8));
        lbNumAI_15->setText(QApplication::translate("Analog24", "15", 0, QApplication::UnicodeUTF8));
        lbNumAI_7->setText(QApplication::translate("Analog24", "7", 0, QApplication::UnicodeUTF8));
        lbAIT_16->setText(QApplication::translate("Analog24", "P48 PRES TOTAL ENTRADA TBP", 0, QApplication::UnicodeUTF8));
        lbAIU_8->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_16->setText(QApplication::translate("Analog24", "78.60", 0, QApplication::UnicodeUTF8));
        lbAIU_4->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_16->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbNumAI_4->setText(QApplication::translate("Analog24", "4", 0, QApplication::UnicodeUTF8));
        lbNumAI_17->setText(QApplication::translate("Analog24", "17", 0, QApplication::UnicodeUTF8));
        lbAIT_3->setText(QApplication::translate("Analog24", "TEMP DE ENTRADA DE GAS LPT T48E (ABAJO)", 0, QApplication::UnicodeUTF8));
        lbAIU_17->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbAI_5->setText(QApplication::translate("Analog24", "981.00", 0, QApplication::UnicodeUTF8));
        lbAI_17->setText(QApplication::translate("Analog24", "64.60", 0, QApplication::UnicodeUTF8));
        lbAI_6->setText(QApplication::translate("Analog24", "980.00", 0, QApplication::UnicodeUTF8));
        lbAIT_17->setText(QApplication::translate("Analog24", "PRES DE BALANCE DE IMPULSO PTBA", 0, QApplication::UnicodeUTF8));
        lbNumAI_18->setText(QApplication::translate("Analog24", "18", 0, QApplication::UnicodeUTF8));
        lbAI_4->setText(QApplication::translate("Analog24", "1565.00", 0, QApplication::UnicodeUTF8));
        lbAI_18->setText(QApplication::translate("Analog24", "0.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_5->setText(QApplication::translate("Analog24", "5", 0, QApplication::UnicodeUTF8));
        lbAIU_18->setText(QApplication::translate("Analog24", "MA", 0, QApplication::UnicodeUTF8));
        lbAIT_4->setText(QApplication::translate("Analog24", "TEMP DE ENTRADA DE GAS LPT T48G (ARRIBA)", 0, QApplication::UnicodeUTF8));
        lbAIT_18->setText(QApplication::translate("Analog24", "DETECTOR UV N\302\272 1 DE LLAMA DE TURBINA", 0, QApplication::UnicodeUTF8));
        lbAI_3->setText(QApplication::translate("Analog24", "1580.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_19->setText(QApplication::translate("Analog24", "19", 0, QApplication::UnicodeUTF8));
        lbNumAI_8->setText(QApplication::translate("Analog24", "8", 0, QApplication::UnicodeUTF8));
        lbNumAI_16->setText(QApplication::translate("Analog24", "16", 0, QApplication::UnicodeUTF8));
        lbAIT_19->setText(QApplication::translate("Analog24", "SE\303\221AL DE MW DE GEN MW", 0, QApplication::UnicodeUTF8));
        lbAIT_7->setText(QApplication::translate("Analog24", "T2A LPC TEMP ADMIS DE AIRE", 0, QApplication::UnicodeUTF8));
        lbAIU_7->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_19->setText(QApplication::translate("Analog24", "MW", 0, QApplication::UnicodeUTF8));
        lbAIU_9->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_6->setText(QApplication::translate("Analog24", "6", 0, QApplication::UnicodeUTF8));
        lbAI_19->setText(QApplication::translate("Analog24", "32.52", 0, QApplication::UnicodeUTF8));
        lbAIT_8->setText(QApplication::translate("Analog24", "TEMP ADMIS AIRE COMPRESOR HP T25A", 0, QApplication::UnicodeUTF8));
        lbAIT_6->setText(QApplication::translate("Analog24", "T3B1 HPC TEMP DE DESCARGA", 0, QApplication::UnicodeUTF8));
        lbNumAI_20->setText(QApplication::translate("Analog24", "20", 0, QApplication::UnicodeUTF8));
        lbAI_8->setText(QApplication::translate("Analog24", "216.00", 0, QApplication::UnicodeUTF8));
        lbAIU_14->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbAIU_20->setText(QApplication::translate("Analog24", "BTU/LB", 0, QApplication::UnicodeUTF8));
        lbNumAI_9->setText(QApplication::translate("Analog24", "9", 0, QApplication::UnicodeUTF8));
        lbAIU_6->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_20->setText(QApplication::translate("Analog24", "VALOR CALOR\303\215FICO (VCB)", 0, QApplication::UnicodeUTF8));
        lbAIT_9->setText(QApplication::translate("Analog24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIT_25->setText(QApplication::translate("Analog24", "VALV DE MDICION DE GAS COMB - DEMAN DE PILOT\n"
"", 0, QApplication::UnicodeUTF8));
        lbAIT_27->setText(QApplication::translate("Analog24", "REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbAI_26->setText(QApplication::translate("Analog24", "1531.00", 0, QApplication::UnicodeUTF8));
        lbAI_27->setText(QApplication::translate("Analog24", "49.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_27->setText(QApplication::translate("Analog24", "3", 0, QApplication::UnicodeUTF8));
        lbAIU_26->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_28->setText(QApplication::translate("Analog24", "2", 0, QApplication::UnicodeUTF8));
        lbAIU_27->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_30->setText(QApplication::translate("Analog24", "1576.00", 0, QApplication::UnicodeUTF8));
        lbAIU_30->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_30->setText(QApplication::translate("Analog24", "REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbFondo_2->setText(QString());
        lbNumAI_33->setText(QApplication::translate("Analog24", "1", 0, QApplication::UnicodeUTF8));
        lbSloAl_2->setText(QApplication::translate("Analog24", "SLOT-  A106  - A0", 0, QApplication::UnicodeUTF8));
        lbAIU_34->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAna24T_2->setText(QApplication::translate("Analog24", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">ANALOG24.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbNumAI_38->setText(QApplication::translate("Analog24", "7", 0, QApplication::UnicodeUTF8));
        lbAIU_38->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_39->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_39->setText(QApplication::translate("Analog24", "4", 0, QApplication::UnicodeUTF8));
        lbAIT_39->setText(QApplication::translate("Analog24", "VOLTAJE CAMPO EXITADOR \n"
"", 0, QApplication::UnicodeUTF8));
        lbAI_41->setText(QApplication::translate("Analog24", "981.00", 0, QApplication::UnicodeUTF8));
        lbAI_43->setText(QApplication::translate("Analog24", "980.00", 0, QApplication::UnicodeUTF8));
        lbAI_44->setText(QApplication::translate("Analog24", "1565.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_42->setText(QApplication::translate("Analog24", "5", 0, QApplication::UnicodeUTF8));
        lbAIT_41->setText(QApplication::translate("Analog24", "AMPS DE CAMPO EXITADOR \n"
"", 0, QApplication::UnicodeUTF8));
        lbAI_46->setText(QApplication::translate("Analog24", "1580.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_44->setText(QApplication::translate("Analog24", "8", 0, QApplication::UnicodeUTF8));
        lbAIT_44->setText(QApplication::translate("Analog24", "VALV DE MDICION DE GAS COMB - DEMAN EXTERN\n"
"", 0, QApplication::UnicodeUTF8));
        lbAIU_43->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_46->setText(QApplication::translate("Analog24", "6", 0, QApplication::UnicodeUTF8));
        lbAIT_45->setText(QApplication::translate("Analog24", "VALV DE CONTROL DE ARRANCADOR  HIDR\303\201ULICO\n"
"", 0, QApplication::UnicodeUTF8));
        lbAIT_46->setText(QApplication::translate("Analog24", "VALV DE MDICION DE GAS COMB - DEMAN INTERN\n"
"", 0, QApplication::UnicodeUTF8));
        lbAI_48->setText(QApplication::translate("Analog24", "216.00", 0, QApplication::UnicodeUTF8));
        lbAIU_48->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        btnProx->setText(QApplication::translate("Analog24", "PR\303\223X >", 0, QApplication::UnicodeUTF8));
        btnCerrar->setText(QApplication::translate("Analog24", "CERRAR", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Analog24: public Ui_Analog24 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ANALOG24_H
