/********************************************************************************
** Form generated from reading UI file 'analog24_s2.ui'
**
** Created: Mon 16. Dec 20:20:25 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ANALOG24_S2_H
#define UI_ANALOG24_S2_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_Analog24_S2
{
public:
    QFrame *panel1;
    WLabel *lbAIU_19;
    WLabel *lbAI_14;
    WLabel *lbAI_2;
    WLabel *lbAI_13;
    WLabel *lbAI_8;
    WLabel *lbAI_12;
    WLabel *lbAIU_13;
    WLabel *lbAIT_15;
    QLabel *lbFondo;
    WLabel *lbAIT_5;
    WLabel *lbAIT_18;
    WLabel *lbAI_3;
    WLabel *lbAI_22;
    WLabel *lbAIT_11;
    WLabel *lbNumAI_13;
    WLabel *lbAIT_20;
    WLabel *lbAIU_3;
    WLabel *lbAI_15;
    WLabel *lbAIT_14;
    WLabel *lbAI_7;
    WLabel *lbAIT_8;
    WLabel *lbAIT_7;
    WLabel *lbAIU_4;
    WLabel *lbNumAI_3;
    WLabel *lbAI_1;
    WLabel *lbAIT_1;
    WLabel *lbAIT_12;
    WLabel *lbNumAI_6;
    WLabel *lbAI_6;
    WLabel *lbAI_5;
    WLabel *lbAIT_2;
    WLabel *lbNumAI_16;
    WLabel *lbAIU_7;
    WLabel *lbAIT_22;
    WLabel *lbNumAI_20;
    WLabel *lbAIU_1;
    WLabel *lbAI_24;
    WLabel *lbAIT_24;
    WLabel *lbNumAI_8;
    WLabel *lbAIU_11;
    WLabel *lbNumAI_22;
    WLabel *lbNumAI_18;
    WLabel *lbNumAI_15;
    WLabel *lbAI_19;
    WLabel *lbNumAI_10;
    WLabel *lbAIU_24;
    WLabel *lbNumAI_5;
    WLabel *lbAIT_17;
    WLabel *lbAIU_16;
    WLabel *lbAI_4;
    WLabel *lbNumAI_7;
    WLabel *lbAI_16;
    WLabel *lbAIU_10;
    WLabel *lbAIT_9;
    WLabel *lbAIT_21;
    WLabel *lbAIU_18;
    WLabel *lbAIT_6;
    WLabel *lbAI_10;
    WLabel *lbNumAI_12;
    WLabel *lbAI_17;
    WLabel *lbAIT_4;
    WLabel *lbAI_21;
    WLabel *lbAIT_16;
    QFrame *frBarraT;
    WLabel *lbAna24_S2T;
    WLabel *lbNumAI_14;
    WLabel *lbAIU_20;
    WLabel *lbAI_9;
    WLabel *lbAIT_23;
    WLabel *lbAIU_5;
    QFrame *frame_2;
    WLabel *lbAIU_21;
    WLabel *lbSloAl;
    WLabel *lbAIU_8;
    WLabel *lbAIU_17;
    WLabel *lbAI_18;
    WLabel *lbAIU_22;
    WLabel *lbAIT_10;
    WLabel *lbAI_23;
    WLabel *lbNumAI_17;
    WLabel *lbAIU_9;
    WLabel *lbNumAI_21;
    WLabel *lbAIT_19;
    WLabel *lbAIU_14;
    WLabel *lbNumAI_4;
    WLabel *lbAIU_23;
    WLabel *lbAI_11;
    WLabel *lbAIU_15;
    WLabel *lbAIT_13;
    WLabel *lbNumAI_11;
    WLabel *lbAIU_12;
    WLabel *lbNumAI_23;
    WLabel *lbNumAI_2;
    WLabel *lbNumAI_1;
    WLabel *lbNumAI_24;
    WLabel *lbAIU_6;
    WLabel *lbNumAI_9;
    WLabel *lbAIT_3;
    WLabel *lbNumAI_19;
    WLabel *lbAIU_2;
    WLabel *lbAI_20;
    QFrame *panel2;
    WLabel *lbAI_26;
    WLabel *lbAI_28;
    QLabel *lbFondo_2;
    WLabel *lbAIT_26;
    WLabel *lbAI_30;
    WLabel *lbAIU_27;
    WLabel *lbAI_33;
    WLabel *lbAIT_31;
    WLabel *lbAIT_32;
    WLabel *lbAIU_28;
    WLabel *lbNumAI_26;
    WLabel *lbAI_34;
    WLabel *lbAIT_33;
    WLabel *lbNumAI_27;
    WLabel *lbAI_35;
    WLabel *lbAI_36;
    WLabel *lbAIT_35;
    WLabel *lbAIU_29;
    WLabel *lbAIU_30;
    WLabel *lbNumAI_30;
    WLabel *lbNumAI_35;
    WLabel *lbAI_39;
    WLabel *lbNumAI_36;
    WLabel *lbAIT_41;
    WLabel *lbAIT_42;
    QFrame *frBarraT_2;
    WLabel *lbAna24_S2T_2;
    WLabel *lbAIU_37;
    QFrame *frame_4;
    WLabel *lbSloAl_2;
    WLabel *lbAIU_39;
    WLabel *lbNumAI_41;
    WLabel *lbNumAI_44;
    WLabel *lbNumAI_45;
    WLabel *lbAIU_47;
    WLabel *lbAIT_48;
    WLabel *lbAIU_48;
    QFrame *frame;
    QPushButton *btnProx;
    QPushButton *btnCerrar;

    void setupUi(QWidget *Analog24_S2)
    {
        if (Analog24_S2->objectName().isEmpty())
            Analog24_S2->setObjectName(QString::fromUtf8("Analog24_S2"));
        Analog24_S2->resize(485, 590);
        Analog24_S2->setMinimumSize(QSize(485, 590));
        Analog24_S2->setMaximumSize(QSize(485, 590));
        Analog24_S2->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        panel1 = new QFrame(Analog24_S2);
        panel1->setObjectName(QString::fromUtf8("panel1"));
        panel1->setGeometry(QRect(0, 0, 485, 530));
        panel1->setFrameShape(QFrame::StyledPanel);
        panel1->setFrameShadow(QFrame::Raised);
        lbAIU_19 = new WLabel(panel1);
        lbAIU_19->setObjectName(QString::fromUtf8("lbAIU_19"));
        lbAIU_19->setGeometry(QRect(442, 415, 31, 20));
        lbAIU_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        QFont font;
        font.setFamily(QString::fromUtf8("Verdana"));
        font.setBold(true);
        font.setWeight(75);
        lbAIU_19->setFont(font);
        lbAIU_19->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_14 = new WLabel(panel1);
        lbAI_14->setObjectName(QString::fromUtf8("lbAI_14"));
        lbAI_14->setGeometry(QRect(366, 315, 66, 20));
        lbAI_14->setLayoutDirection(Qt::RightToLeft);
        lbAI_14->setFont(font);
        lbAI_14->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_2 = new WLabel(panel1);
        lbAI_2->setObjectName(QString::fromUtf8("lbAI_2"));
        lbAI_2->setGeometry(QRect(366, 75, 66, 20));
        lbAI_2->setLayoutDirection(Qt::RightToLeft);
        lbAI_2->setFont(font);
        lbAI_2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_13 = new WLabel(panel1);
        lbAI_13->setObjectName(QString::fromUtf8("lbAI_13"));
        lbAI_13->setGeometry(QRect(366, 295, 66, 20));
        lbAI_13->setLayoutDirection(Qt::RightToLeft);
        lbAI_13->setFont(font);
        lbAI_13->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_8 = new WLabel(panel1);
        lbAI_8->setObjectName(QString::fromUtf8("lbAI_8"));
        lbAI_8->setGeometry(QRect(366, 195, 66, 20));
        lbAI_8->setLayoutDirection(Qt::RightToLeft);
        lbAI_8->setFont(font);
        lbAI_8->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_12 = new WLabel(panel1);
        lbAI_12->setObjectName(QString::fromUtf8("lbAI_12"));
        lbAI_12->setGeometry(QRect(366, 275, 66, 20));
        lbAI_12->setLayoutDirection(Qt::RightToLeft);
        lbAI_12->setFont(font);
        lbAI_12->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_13 = new WLabel(panel1);
        lbAIU_13->setObjectName(QString::fromUtf8("lbAIU_13"));
        lbAIU_13->setGeometry(QRect(442, 295, 31, 20));
        lbAIU_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_13->setFont(font);
        lbAIU_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_15 = new WLabel(panel1);
        lbAIT_15->setObjectName(QString::fromUtf8("lbAIT_15"));
        lbAIT_15->setGeometry(QRect(35, 335, 340, 16));
        lbAIT_15->setFont(font);
        lbAIT_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbFondo = new QLabel(panel1);
        lbFondo->setObjectName(QString::fromUtf8("lbFondo"));
        lbFondo->setGeometry(QRect(0, 0, 485, 590));
        lbFondo->setMinimumSize(QSize(485, 590));
        lbFondo->setMaximumSize(QSize(485, 590));
        lbFondo->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbFondo->setFrameShape(QFrame::Box);
        lbFondo->setFrameShadow(QFrame::Sunken);
        lbAIT_5 = new WLabel(panel1);
        lbAIT_5->setObjectName(QString::fromUtf8("lbAIT_5"));
        lbAIT_5->setGeometry(QRect(35, 135, 340, 16));
        lbAIT_5->setFont(font);
        lbAIT_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_18 = new WLabel(panel1);
        lbAIT_18->setObjectName(QString::fromUtf8("lbAIT_18"));
        lbAIT_18->setGeometry(QRect(35, 395, 340, 16));
        lbAIT_18->setFont(font);
        lbAIT_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_3 = new WLabel(panel1);
        lbAI_3->setObjectName(QString::fromUtf8("lbAI_3"));
        lbAI_3->setGeometry(QRect(366, 95, 66, 20));
        lbAI_3->setLayoutDirection(Qt::RightToLeft);
        lbAI_3->setFont(font);
        lbAI_3->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_22 = new WLabel(panel1);
        lbAI_22->setObjectName(QString::fromUtf8("lbAI_22"));
        lbAI_22->setGeometry(QRect(366, 475, 66, 20));
        lbAI_22->setLayoutDirection(Qt::RightToLeft);
        lbAI_22->setFont(font);
        lbAI_22->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_11 = new WLabel(panel1);
        lbAIT_11->setObjectName(QString::fromUtf8("lbAIT_11"));
        lbAIT_11->setGeometry(QRect(35, 255, 340, 16));
        lbAIT_11->setFont(font);
        lbAIT_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_13 = new WLabel(panel1);
        lbNumAI_13->setObjectName(QString::fromUtf8("lbNumAI_13"));
        lbNumAI_13->setGeometry(QRect(10, 295, 21, 16));
        lbNumAI_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_13->setFont(font);
        lbNumAI_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_20 = new WLabel(panel1);
        lbAIT_20->setObjectName(QString::fromUtf8("lbAIT_20"));
        lbAIT_20->setGeometry(QRect(35, 435, 311, 16));
        lbAIT_20->setFont(font);
        lbAIT_20->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_3 = new WLabel(panel1);
        lbAIU_3->setObjectName(QString::fromUtf8("lbAIU_3"));
        lbAIU_3->setGeometry(QRect(442, 95, 31, 20));
        lbAIU_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_3->setFont(font);
        lbAIU_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_15 = new WLabel(panel1);
        lbAI_15->setObjectName(QString::fromUtf8("lbAI_15"));
        lbAI_15->setGeometry(QRect(366, 335, 66, 20));
        lbAI_15->setLayoutDirection(Qt::RightToLeft);
        lbAI_15->setFont(font);
        lbAI_15->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_14 = new WLabel(panel1);
        lbAIT_14->setObjectName(QString::fromUtf8("lbAIT_14"));
        lbAIT_14->setGeometry(QRect(35, 315, 340, 16));
        lbAIT_14->setFont(font);
        lbAIT_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_7 = new WLabel(panel1);
        lbAI_7->setObjectName(QString::fromUtf8("lbAI_7"));
        lbAI_7->setGeometry(QRect(366, 175, 66, 20));
        lbAI_7->setLayoutDirection(Qt::RightToLeft);
        lbAI_7->setFont(font);
        lbAI_7->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_8 = new WLabel(panel1);
        lbAIT_8->setObjectName(QString::fromUtf8("lbAIT_8"));
        lbAIT_8->setGeometry(QRect(35, 195, 340, 16));
        lbAIT_8->setFont(font);
        lbAIT_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_7 = new WLabel(panel1);
        lbAIT_7->setObjectName(QString::fromUtf8("lbAIT_7"));
        lbAIT_7->setGeometry(QRect(35, 175, 340, 16));
        lbAIT_7->setFont(font);
        lbAIT_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_4 = new WLabel(panel1);
        lbAIU_4->setObjectName(QString::fromUtf8("lbAIU_4"));
        lbAIU_4->setGeometry(QRect(442, 115, 31, 20));
        lbAIU_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_4->setFont(font);
        lbAIU_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_3 = new WLabel(panel1);
        lbNumAI_3->setObjectName(QString::fromUtf8("lbNumAI_3"));
        lbNumAI_3->setGeometry(QRect(10, 95, 21, 16));
        lbNumAI_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_3->setFont(font);
        lbNumAI_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_1 = new WLabel(panel1);
        lbAI_1->setObjectName(QString::fromUtf8("lbAI_1"));
        lbAI_1->setGeometry(QRect(366, 55, 66, 20));
        lbAI_1->setLayoutDirection(Qt::RightToLeft);
        lbAI_1->setFont(font);
        lbAI_1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_1 = new WLabel(panel1);
        lbAIT_1->setObjectName(QString::fromUtf8("lbAIT_1"));
        lbAIT_1->setGeometry(QRect(33, 55, 340, 16));
        lbAIT_1->setFont(font);
        lbAIT_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_12 = new WLabel(panel1);
        lbAIT_12->setObjectName(QString::fromUtf8("lbAIT_12"));
        lbAIT_12->setGeometry(QRect(35, 275, 340, 16));
        lbAIT_12->setFont(font);
        lbAIT_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_6 = new WLabel(panel1);
        lbNumAI_6->setObjectName(QString::fromUtf8("lbNumAI_6"));
        lbNumAI_6->setGeometry(QRect(10, 155, 21, 16));
        lbNumAI_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_6->setFont(font);
        lbNumAI_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_6 = new WLabel(panel1);
        lbAI_6->setObjectName(QString::fromUtf8("lbAI_6"));
        lbAI_6->setGeometry(QRect(366, 155, 66, 20));
        lbAI_6->setLayoutDirection(Qt::RightToLeft);
        lbAI_6->setFont(font);
        lbAI_6->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_5 = new WLabel(panel1);
        lbAI_5->setObjectName(QString::fromUtf8("lbAI_5"));
        lbAI_5->setGeometry(QRect(366, 135, 66, 20));
        lbAI_5->setLayoutDirection(Qt::RightToLeft);
        lbAI_5->setFont(font);
        lbAI_5->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_2 = new WLabel(panel1);
        lbAIT_2->setObjectName(QString::fromUtf8("lbAIT_2"));
        lbAIT_2->setGeometry(QRect(33, 75, 340, 16));
        lbAIT_2->setFont(font);
        lbAIT_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_16 = new WLabel(panel1);
        lbNumAI_16->setObjectName(QString::fromUtf8("lbNumAI_16"));
        lbNumAI_16->setGeometry(QRect(10, 355, 21, 16));
        lbNumAI_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_16->setFont(font);
        lbNumAI_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_7 = new WLabel(panel1);
        lbAIU_7->setObjectName(QString::fromUtf8("lbAIU_7"));
        lbAIU_7->setGeometry(QRect(442, 175, 31, 20));
        lbAIU_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_7->setFont(font);
        lbAIU_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_22 = new WLabel(panel1);
        lbAIT_22->setObjectName(QString::fromUtf8("lbAIT_22"));
        lbAIT_22->setGeometry(QRect(35, 475, 311, 16));
        lbAIT_22->setFont(font);
        lbAIT_22->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_20 = new WLabel(panel1);
        lbNumAI_20->setObjectName(QString::fromUtf8("lbNumAI_20"));
        lbNumAI_20->setGeometry(QRect(10, 435, 21, 16));
        lbNumAI_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_20->setFont(font);
        lbNumAI_20->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_1 = new WLabel(panel1);
        lbAIU_1->setObjectName(QString::fromUtf8("lbAIU_1"));
        lbAIU_1->setGeometry(QRect(440, 55, 31, 20));
        lbAIU_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_1->setFont(font);
        lbAIU_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_24 = new WLabel(panel1);
        lbAI_24->setObjectName(QString::fromUtf8("lbAI_24"));
        lbAI_24->setGeometry(QRect(366, 515, 66, 20));
        lbAI_24->setLayoutDirection(Qt::RightToLeft);
        lbAI_24->setFont(font);
        lbAI_24->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_24 = new WLabel(panel1);
        lbAIT_24->setObjectName(QString::fromUtf8("lbAIT_24"));
        lbAIT_24->setGeometry(QRect(35, 515, 311, 16));
        lbAIT_24->setFont(font);
        lbAIT_24->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_8 = new WLabel(panel1);
        lbNumAI_8->setObjectName(QString::fromUtf8("lbNumAI_8"));
        lbNumAI_8->setGeometry(QRect(10, 195, 21, 16));
        lbNumAI_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_8->setFont(font);
        lbNumAI_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_11 = new WLabel(panel1);
        lbAIU_11->setObjectName(QString::fromUtf8("lbAIU_11"));
        lbAIU_11->setGeometry(QRect(442, 255, 31, 20));
        lbAIU_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_11->setFont(font);
        lbAIU_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_22 = new WLabel(panel1);
        lbNumAI_22->setObjectName(QString::fromUtf8("lbNumAI_22"));
        lbNumAI_22->setGeometry(QRect(10, 475, 21, 16));
        lbNumAI_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_22->setFont(font);
        lbNumAI_22->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_18 = new WLabel(panel1);
        lbNumAI_18->setObjectName(QString::fromUtf8("lbNumAI_18"));
        lbNumAI_18->setGeometry(QRect(10, 395, 21, 16));
        lbNumAI_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_18->setFont(font);
        lbNumAI_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_15 = new WLabel(panel1);
        lbNumAI_15->setObjectName(QString::fromUtf8("lbNumAI_15"));
        lbNumAI_15->setGeometry(QRect(10, 335, 21, 16));
        lbNumAI_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_15->setFont(font);
        lbNumAI_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_19 = new WLabel(panel1);
        lbAI_19->setObjectName(QString::fromUtf8("lbAI_19"));
        lbAI_19->setGeometry(QRect(366, 415, 66, 20));
        lbAI_19->setLayoutDirection(Qt::RightToLeft);
        lbAI_19->setFont(font);
        lbAI_19->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_10 = new WLabel(panel1);
        lbNumAI_10->setObjectName(QString::fromUtf8("lbNumAI_10"));
        lbNumAI_10->setGeometry(QRect(10, 235, 21, 16));
        lbNumAI_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_10->setFont(font);
        lbNumAI_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_24 = new WLabel(panel1);
        lbAIU_24->setObjectName(QString::fromUtf8("lbAIU_24"));
        lbAIU_24->setGeometry(QRect(442, 515, 31, 20));
        lbAIU_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_24->setFont(font);
        lbAIU_24->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_5 = new WLabel(panel1);
        lbNumAI_5->setObjectName(QString::fromUtf8("lbNumAI_5"));
        lbNumAI_5->setGeometry(QRect(10, 135, 21, 16));
        lbNumAI_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_5->setFont(font);
        lbNumAI_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_17 = new WLabel(panel1);
        lbAIT_17->setObjectName(QString::fromUtf8("lbAIT_17"));
        lbAIT_17->setGeometry(QRect(35, 375, 340, 16));
        lbAIT_17->setFont(font);
        lbAIT_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_16 = new WLabel(panel1);
        lbAIU_16->setObjectName(QString::fromUtf8("lbAIU_16"));
        lbAIU_16->setGeometry(QRect(442, 355, 31, 20));
        lbAIU_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_16->setFont(font);
        lbAIU_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_4 = new WLabel(panel1);
        lbAI_4->setObjectName(QString::fromUtf8("lbAI_4"));
        lbAI_4->setGeometry(QRect(366, 115, 66, 20));
        lbAI_4->setLayoutDirection(Qt::RightToLeft);
        lbAI_4->setFont(font);
        lbAI_4->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_7 = new WLabel(panel1);
        lbNumAI_7->setObjectName(QString::fromUtf8("lbNumAI_7"));
        lbNumAI_7->setGeometry(QRect(10, 175, 21, 16));
        lbNumAI_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_7->setFont(font);
        lbNumAI_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_16 = new WLabel(panel1);
        lbAI_16->setObjectName(QString::fromUtf8("lbAI_16"));
        lbAI_16->setGeometry(QRect(366, 355, 66, 20));
        lbAI_16->setLayoutDirection(Qt::RightToLeft);
        lbAI_16->setFont(font);
        lbAI_16->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_10 = new WLabel(panel1);
        lbAIU_10->setObjectName(QString::fromUtf8("lbAIU_10"));
        lbAIU_10->setGeometry(QRect(442, 235, 31, 20));
        lbAIU_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_10->setFont(font);
        lbAIU_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_9 = new WLabel(panel1);
        lbAIT_9->setObjectName(QString::fromUtf8("lbAIT_9"));
        lbAIT_9->setGeometry(QRect(35, 215, 340, 16));
        lbAIT_9->setFont(font);
        lbAIT_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_21 = new WLabel(panel1);
        lbAIT_21->setObjectName(QString::fromUtf8("lbAIT_21"));
        lbAIT_21->setGeometry(QRect(35, 455, 311, 16));
        lbAIT_21->setFont(font);
        lbAIT_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_18 = new WLabel(panel1);
        lbAIU_18->setObjectName(QString::fromUtf8("lbAIU_18"));
        lbAIU_18->setGeometry(QRect(442, 395, 31, 20));
        lbAIU_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_18->setFont(font);
        lbAIU_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_6 = new WLabel(panel1);
        lbAIT_6->setObjectName(QString::fromUtf8("lbAIT_6"));
        lbAIT_6->setGeometry(QRect(33, 155, 340, 16));
        lbAIT_6->setFont(font);
        lbAIT_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_10 = new WLabel(panel1);
        lbAI_10->setObjectName(QString::fromUtf8("lbAI_10"));
        lbAI_10->setGeometry(QRect(366, 235, 66, 20));
        lbAI_10->setLayoutDirection(Qt::RightToLeft);
        lbAI_10->setFont(font);
        lbAI_10->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_12 = new WLabel(panel1);
        lbNumAI_12->setObjectName(QString::fromUtf8("lbNumAI_12"));
        lbNumAI_12->setGeometry(QRect(10, 275, 21, 16));
        lbNumAI_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_12->setFont(font);
        lbNumAI_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_17 = new WLabel(panel1);
        lbAI_17->setObjectName(QString::fromUtf8("lbAI_17"));
        lbAI_17->setGeometry(QRect(366, 375, 66, 20));
        lbAI_17->setLayoutDirection(Qt::RightToLeft);
        lbAI_17->setFont(font);
        lbAI_17->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_4 = new WLabel(panel1);
        lbAIT_4->setObjectName(QString::fromUtf8("lbAIT_4"));
        lbAIT_4->setGeometry(QRect(35, 115, 340, 16));
        lbAIT_4->setFont(font);
        lbAIT_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_21 = new WLabel(panel1);
        lbAI_21->setObjectName(QString::fromUtf8("lbAI_21"));
        lbAI_21->setGeometry(QRect(366, 455, 66, 20));
        lbAI_21->setLayoutDirection(Qt::RightToLeft);
        lbAI_21->setFont(font);
        lbAI_21->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_16 = new WLabel(panel1);
        lbAIT_16->setObjectName(QString::fromUtf8("lbAIT_16"));
        lbAIT_16->setGeometry(QRect(35, 355, 340, 16));
        lbAIT_16->setFont(font);
        lbAIT_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frBarraT = new QFrame(panel1);
        frBarraT->setObjectName(QString::fromUtf8("frBarraT"));
        frBarraT->setGeometry(QRect(0, 0, 485, 15));
        frBarraT->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frBarraT->setFrameShape(QFrame::Panel);
        frBarraT->setFrameShadow(QFrame::Raised);
        frBarraT->setLineWidth(0);
        lbAna24_S2T = new WLabel(frBarraT);
        lbAna24_S2T->setObjectName(QString::fromUtf8("lbAna24_S2T"));
        lbAna24_S2T->setGeometry(QRect(3, 0, 111, 16));
        lbAna24_S2T->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        QFont font1;
        font1.setPointSize(5);
        font1.setBold(true);
        font1.setWeight(75);
        lbAna24_S2T->setFont(font1);
        lbAna24_S2T->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_14 = new WLabel(panel1);
        lbNumAI_14->setObjectName(QString::fromUtf8("lbNumAI_14"));
        lbNumAI_14->setGeometry(QRect(10, 315, 21, 16));
        lbNumAI_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_14->setFont(font);
        lbNumAI_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_20 = new WLabel(panel1);
        lbAIU_20->setObjectName(QString::fromUtf8("lbAIU_20"));
        lbAIU_20->setGeometry(QRect(435, 435, 41, 20));
        lbAIU_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_20->setFont(font);
        lbAIU_20->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_9 = new WLabel(panel1);
        lbAI_9->setObjectName(QString::fromUtf8("lbAI_9"));
        lbAI_9->setGeometry(QRect(366, 215, 66, 20));
        lbAI_9->setLayoutDirection(Qt::RightToLeft);
        lbAI_9->setFont(font);
        lbAI_9->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_23 = new WLabel(panel1);
        lbAIT_23->setObjectName(QString::fromUtf8("lbAIT_23"));
        lbAIT_23->setGeometry(QRect(35, 495, 311, 16));
        lbAIT_23->setFont(font);
        lbAIT_23->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_5 = new WLabel(panel1);
        lbAIU_5->setObjectName(QString::fromUtf8("lbAIU_5"));
        lbAIU_5->setGeometry(QRect(442, 135, 31, 20));
        lbAIU_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_5->setFont(font);
        lbAIU_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame_2 = new QFrame(panel1);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(0, 20, 485, 30));
        frame_2->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Sunken);
        frame_2->setLineWidth(2);
        lbAIU_21 = new WLabel(panel1);
        lbAIU_21->setObjectName(QString::fromUtf8("lbAIU_21"));
        lbAIU_21->setGeometry(QRect(442, 455, 31, 20));
        lbAIU_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_21->setFont(font);
        lbAIU_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbSloAl = new WLabel(panel1);
        lbSloAl->setObjectName(QString::fromUtf8("lbSloAl"));
        lbSloAl->setGeometry(QRect(67, 23, 400, 22));
        lbSloAl->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setPointSize(11);
        font2.setBold(true);
        font2.setWeight(75);
        lbSloAl->setFont(font2);
        lbAIU_8 = new WLabel(panel1);
        lbAIU_8->setObjectName(QString::fromUtf8("lbAIU_8"));
        lbAIU_8->setGeometry(QRect(442, 195, 31, 20));
        lbAIU_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_8->setFont(font);
        lbAIU_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_17 = new WLabel(panel1);
        lbAIU_17->setObjectName(QString::fromUtf8("lbAIU_17"));
        lbAIU_17->setGeometry(QRect(442, 375, 31, 20));
        lbAIU_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_17->setFont(font);
        lbAIU_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_18 = new WLabel(panel1);
        lbAI_18->setObjectName(QString::fromUtf8("lbAI_18"));
        lbAI_18->setGeometry(QRect(366, 395, 66, 20));
        lbAI_18->setLayoutDirection(Qt::RightToLeft);
        lbAI_18->setFont(font);
        lbAI_18->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_22 = new WLabel(panel1);
        lbAIU_22->setObjectName(QString::fromUtf8("lbAIU_22"));
        lbAIU_22->setGeometry(QRect(445, 475, 31, 20));
        lbAIU_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_22->setFont(font);
        lbAIU_22->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_10 = new WLabel(panel1);
        lbAIT_10->setObjectName(QString::fromUtf8("lbAIT_10"));
        lbAIT_10->setGeometry(QRect(35, 235, 340, 16));
        lbAIT_10->setFont(font);
        lbAIT_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_23 = new WLabel(panel1);
        lbAI_23->setObjectName(QString::fromUtf8("lbAI_23"));
        lbAI_23->setGeometry(QRect(366, 495, 66, 20));
        lbAI_23->setLayoutDirection(Qt::RightToLeft);
        lbAI_23->setFont(font);
        lbAI_23->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_17 = new WLabel(panel1);
        lbNumAI_17->setObjectName(QString::fromUtf8("lbNumAI_17"));
        lbNumAI_17->setGeometry(QRect(10, 375, 21, 16));
        lbNumAI_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_17->setFont(font);
        lbNumAI_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_9 = new WLabel(panel1);
        lbAIU_9->setObjectName(QString::fromUtf8("lbAIU_9"));
        lbAIU_9->setGeometry(QRect(442, 215, 31, 20));
        lbAIU_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_9->setFont(font);
        lbAIU_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_21 = new WLabel(panel1);
        lbNumAI_21->setObjectName(QString::fromUtf8("lbNumAI_21"));
        lbNumAI_21->setGeometry(QRect(10, 455, 21, 16));
        lbNumAI_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_21->setFont(font);
        lbNumAI_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_19 = new WLabel(panel1);
        lbAIT_19->setObjectName(QString::fromUtf8("lbAIT_19"));
        lbAIT_19->setGeometry(QRect(35, 415, 340, 16));
        lbAIT_19->setFont(font);
        lbAIT_19->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_14 = new WLabel(panel1);
        lbAIU_14->setObjectName(QString::fromUtf8("lbAIU_14"));
        lbAIU_14->setGeometry(QRect(442, 315, 31, 20));
        lbAIU_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_14->setFont(font);
        lbAIU_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_4 = new WLabel(panel1);
        lbNumAI_4->setObjectName(QString::fromUtf8("lbNumAI_4"));
        lbNumAI_4->setGeometry(QRect(10, 115, 21, 16));
        lbNumAI_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_4->setFont(font);
        lbNumAI_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_23 = new WLabel(panel1);
        lbAIU_23->setObjectName(QString::fromUtf8("lbAIU_23"));
        lbAIU_23->setGeometry(QRect(445, 495, 31, 20));
        lbAIU_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_23->setFont(font);
        lbAIU_23->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_11 = new WLabel(panel1);
        lbAI_11->setObjectName(QString::fromUtf8("lbAI_11"));
        lbAI_11->setGeometry(QRect(366, 255, 66, 20));
        lbAI_11->setLayoutDirection(Qt::RightToLeft);
        lbAI_11->setFont(font);
        lbAI_11->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_15 = new WLabel(panel1);
        lbAIU_15->setObjectName(QString::fromUtf8("lbAIU_15"));
        lbAIU_15->setGeometry(QRect(442, 335, 31, 20));
        lbAIU_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_15->setFont(font);
        lbAIU_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_13 = new WLabel(panel1);
        lbAIT_13->setObjectName(QString::fromUtf8("lbAIT_13"));
        lbAIT_13->setGeometry(QRect(35, 295, 340, 16));
        lbAIT_13->setFont(font);
        lbAIT_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_11 = new WLabel(panel1);
        lbNumAI_11->setObjectName(QString::fromUtf8("lbNumAI_11"));
        lbNumAI_11->setGeometry(QRect(10, 255, 21, 16));
        lbNumAI_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_11->setFont(font);
        lbNumAI_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_12 = new WLabel(panel1);
        lbAIU_12->setObjectName(QString::fromUtf8("lbAIU_12"));
        lbAIU_12->setGeometry(QRect(442, 275, 31, 20));
        lbAIU_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_12->setFont(font);
        lbAIU_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_23 = new WLabel(panel1);
        lbNumAI_23->setObjectName(QString::fromUtf8("lbNumAI_23"));
        lbNumAI_23->setGeometry(QRect(10, 495, 21, 16));
        lbNumAI_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_23->setFont(font);
        lbNumAI_23->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_2 = new WLabel(panel1);
        lbNumAI_2->setObjectName(QString::fromUtf8("lbNumAI_2"));
        lbNumAI_2->setGeometry(QRect(10, 75, 21, 16));
        lbNumAI_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_2->setFont(font);
        lbNumAI_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_1 = new WLabel(panel1);
        lbNumAI_1->setObjectName(QString::fromUtf8("lbNumAI_1"));
        lbNumAI_1->setGeometry(QRect(10, 55, 21, 16));
        lbNumAI_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_1->setFont(font);
        lbNumAI_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_24 = new WLabel(panel1);
        lbNumAI_24->setObjectName(QString::fromUtf8("lbNumAI_24"));
        lbNumAI_24->setGeometry(QRect(10, 515, 21, 16));
        lbNumAI_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_24->setFont(font);
        lbNumAI_24->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_6 = new WLabel(panel1);
        lbAIU_6->setObjectName(QString::fromUtf8("lbAIU_6"));
        lbAIU_6->setGeometry(QRect(440, 155, 31, 20));
        lbAIU_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_6->setFont(font);
        lbAIU_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_9 = new WLabel(panel1);
        lbNumAI_9->setObjectName(QString::fromUtf8("lbNumAI_9"));
        lbNumAI_9->setGeometry(QRect(10, 215, 21, 16));
        lbNumAI_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_9->setFont(font);
        lbNumAI_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_3 = new WLabel(panel1);
        lbAIT_3->setObjectName(QString::fromUtf8("lbAIT_3"));
        lbAIT_3->setGeometry(QRect(35, 95, 340, 16));
        lbAIT_3->setFont(font);
        lbAIT_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_19 = new WLabel(panel1);
        lbNumAI_19->setObjectName(QString::fromUtf8("lbNumAI_19"));
        lbNumAI_19->setGeometry(QRect(10, 415, 21, 16));
        lbNumAI_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_19->setFont(font);
        lbNumAI_19->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_2 = new WLabel(panel1);
        lbAIU_2->setObjectName(QString::fromUtf8("lbAIU_2"));
        lbAIU_2->setGeometry(QRect(440, 75, 31, 20));
        lbAIU_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_2->setFont(font);
        lbAIU_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_20 = new WLabel(panel1);
        lbAI_20->setObjectName(QString::fromUtf8("lbAI_20"));
        lbAI_20->setGeometry(QRect(366, 435, 66, 20));
        lbAI_20->setLayoutDirection(Qt::RightToLeft);
        lbAI_20->setFont(font);
        lbAI_20->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbFondo->raise();
        lbAIU_19->raise();
        lbAI_14->raise();
        lbAI_2->raise();
        lbAI_13->raise();
        lbAI_8->raise();
        lbAI_12->raise();
        lbAIU_13->raise();
        lbAIT_15->raise();
        lbAIT_5->raise();
        lbAIT_18->raise();
        lbAI_3->raise();
        lbAI_22->raise();
        lbAIT_11->raise();
        lbNumAI_13->raise();
        lbAIT_20->raise();
        lbAIU_3->raise();
        lbAI_15->raise();
        lbAIT_14->raise();
        lbAI_7->raise();
        lbAIT_8->raise();
        lbAIT_7->raise();
        lbAIU_4->raise();
        lbNumAI_3->raise();
        lbAI_1->raise();
        lbAIT_1->raise();
        lbAIT_12->raise();
        lbNumAI_6->raise();
        lbAI_6->raise();
        lbAI_5->raise();
        lbAIT_2->raise();
        lbNumAI_16->raise();
        lbAIU_7->raise();
        lbAIT_22->raise();
        lbNumAI_20->raise();
        lbAIU_1->raise();
        lbAI_24->raise();
        lbAIT_24->raise();
        lbNumAI_8->raise();
        lbAIU_11->raise();
        lbNumAI_22->raise();
        lbNumAI_18->raise();
        lbNumAI_15->raise();
        lbAI_19->raise();
        lbNumAI_10->raise();
        lbAIU_24->raise();
        lbNumAI_5->raise();
        lbAIT_17->raise();
        lbAIU_16->raise();
        lbAI_4->raise();
        lbNumAI_7->raise();
        lbAI_16->raise();
        lbAIU_10->raise();
        lbAIT_9->raise();
        lbAIT_21->raise();
        lbAIU_18->raise();
        lbAIT_6->raise();
        lbAI_10->raise();
        lbNumAI_12->raise();
        lbAI_17->raise();
        lbAIT_4->raise();
        lbAI_21->raise();
        lbAIT_16->raise();
        frBarraT->raise();
        lbNumAI_14->raise();
        lbAIU_20->raise();
        lbAI_9->raise();
        lbAIT_23->raise();
        lbAIU_5->raise();
        frame_2->raise();
        lbAIU_21->raise();
        lbSloAl->raise();
        lbAIU_8->raise();
        lbAIU_17->raise();
        lbAI_18->raise();
        lbAIU_22->raise();
        lbAIT_10->raise();
        lbAI_23->raise();
        lbNumAI_17->raise();
        lbAIU_9->raise();
        lbNumAI_21->raise();
        lbAIT_19->raise();
        lbAIU_14->raise();
        lbNumAI_4->raise();
        lbAIU_23->raise();
        lbAI_11->raise();
        lbAIU_15->raise();
        lbAIT_13->raise();
        lbNumAI_11->raise();
        lbAIU_12->raise();
        lbNumAI_23->raise();
        lbNumAI_2->raise();
        lbNumAI_1->raise();
        lbNumAI_24->raise();
        lbAIU_6->raise();
        lbNumAI_9->raise();
        lbAIT_3->raise();
        lbNumAI_19->raise();
        lbAIU_2->raise();
        lbAI_20->raise();
        panel2 = new QFrame(Analog24_S2);
        panel2->setObjectName(QString::fromUtf8("panel2"));
        panel2->setGeometry(QRect(0, 0, 485, 534));
        panel2->setFrameShape(QFrame::StyledPanel);
        panel2->setFrameShadow(QFrame::Raised);
        lbAI_26 = new WLabel(panel2);
        lbAI_26->setObjectName(QString::fromUtf8("lbAI_26"));
        lbAI_26->setGeometry(QRect(366, 75, 66, 20));
        lbAI_26->setLayoutDirection(Qt::RightToLeft);
        lbAI_26->setFont(font);
        lbAI_26->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_28 = new WLabel(panel2);
        lbAI_28->setObjectName(QString::fromUtf8("lbAI_28"));
        lbAI_28->setGeometry(QRect(366, 195, 66, 20));
        lbAI_28->setLayoutDirection(Qt::RightToLeft);
        lbAI_28->setFont(font);
        lbAI_28->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbFondo_2 = new QLabel(panel2);
        lbFondo_2->setObjectName(QString::fromUtf8("lbFondo_2"));
        lbFondo_2->setGeometry(QRect(0, 0, 485, 590));
        lbFondo_2->setMinimumSize(QSize(485, 590));
        lbFondo_2->setMaximumSize(QSize(485, 590));
        lbFondo_2->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbAIT_26 = new WLabel(panel2);
        lbAIT_26->setObjectName(QString::fromUtf8("lbAIT_26"));
        lbAIT_26->setGeometry(QRect(35, 135, 340, 16));
        lbAIT_26->setFont(font);
        lbAIT_26->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_30 = new WLabel(panel2);
        lbAI_30->setObjectName(QString::fromUtf8("lbAI_30"));
        lbAI_30->setGeometry(QRect(366, 95, 66, 20));
        lbAI_30->setLayoutDirection(Qt::RightToLeft);
        lbAI_30->setFont(font);
        lbAI_30->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIU_27 = new WLabel(panel2);
        lbAIU_27->setObjectName(QString::fromUtf8("lbAIU_27"));
        lbAIU_27->setGeometry(QRect(442, 95, 31, 20));
        lbAIU_27->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_27->setFont(font);
        lbAIU_27->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_33 = new WLabel(panel2);
        lbAI_33->setObjectName(QString::fromUtf8("lbAI_33"));
        lbAI_33->setGeometry(QRect(366, 175, 66, 20));
        lbAI_33->setLayoutDirection(Qt::RightToLeft);
        lbAI_33->setFont(font);
        lbAI_33->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_31 = new WLabel(panel2);
        lbAIT_31->setObjectName(QString::fromUtf8("lbAIT_31"));
        lbAIT_31->setGeometry(QRect(35, 195, 340, 16));
        lbAIT_31->setFont(font);
        lbAIT_31->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_32 = new WLabel(panel2);
        lbAIT_32->setObjectName(QString::fromUtf8("lbAIT_32"));
        lbAIT_32->setGeometry(QRect(35, 175, 340, 16));
        lbAIT_32->setFont(font);
        lbAIT_32->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_28 = new WLabel(panel2);
        lbAIU_28->setObjectName(QString::fromUtf8("lbAIU_28"));
        lbAIU_28->setGeometry(QRect(442, 115, 31, 20));
        lbAIU_28->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_28->setFont(font);
        lbAIU_28->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_26 = new WLabel(panel2);
        lbNumAI_26->setObjectName(QString::fromUtf8("lbNumAI_26"));
        lbNumAI_26->setGeometry(QRect(10, 95, 21, 16));
        lbNumAI_26->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_26->setFont(font);
        lbNumAI_26->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_34 = new WLabel(panel2);
        lbAI_34->setObjectName(QString::fromUtf8("lbAI_34"));
        lbAI_34->setGeometry(QRect(366, 55, 66, 20));
        lbAI_34->setLayoutDirection(Qt::RightToLeft);
        lbAI_34->setFont(font);
        lbAI_34->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_33 = new WLabel(panel2);
        lbAIT_33->setObjectName(QString::fromUtf8("lbAIT_33"));
        lbAIT_33->setGeometry(QRect(33, 55, 340, 16));
        lbAIT_33->setFont(font);
        lbAIT_33->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_27 = new WLabel(panel2);
        lbNumAI_27->setObjectName(QString::fromUtf8("lbNumAI_27"));
        lbNumAI_27->setGeometry(QRect(10, 155, 21, 16));
        lbNumAI_27->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_27->setFont(font);
        lbNumAI_27->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_35 = new WLabel(panel2);
        lbAI_35->setObjectName(QString::fromUtf8("lbAI_35"));
        lbAI_35->setGeometry(QRect(366, 155, 66, 20));
        lbAI_35->setLayoutDirection(Qt::RightToLeft);
        lbAI_35->setFont(font);
        lbAI_35->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAI_36 = new WLabel(panel2);
        lbAI_36->setObjectName(QString::fromUtf8("lbAI_36"));
        lbAI_36->setGeometry(QRect(366, 135, 66, 20));
        lbAI_36->setLayoutDirection(Qt::RightToLeft);
        lbAI_36->setFont(font);
        lbAI_36->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbAIT_35 = new WLabel(panel2);
        lbAIT_35->setObjectName(QString::fromUtf8("lbAIT_35"));
        lbAIT_35->setGeometry(QRect(33, 75, 340, 16));
        lbAIT_35->setFont(font);
        lbAIT_35->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_29 = new WLabel(panel2);
        lbAIU_29->setObjectName(QString::fromUtf8("lbAIU_29"));
        lbAIU_29->setGeometry(QRect(442, 175, 31, 20));
        lbAIU_29->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_29->setFont(font);
        lbAIU_29->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_30 = new WLabel(panel2);
        lbAIU_30->setObjectName(QString::fromUtf8("lbAIU_30"));
        lbAIU_30->setGeometry(QRect(440, 55, 31, 20));
        lbAIU_30->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_30->setFont(font);
        lbAIU_30->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_30 = new WLabel(panel2);
        lbNumAI_30->setObjectName(QString::fromUtf8("lbNumAI_30"));
        lbNumAI_30->setGeometry(QRect(10, 195, 21, 16));
        lbNumAI_30->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_30->setFont(font);
        lbNumAI_30->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_35 = new WLabel(panel2);
        lbNumAI_35->setObjectName(QString::fromUtf8("lbNumAI_35"));
        lbNumAI_35->setGeometry(QRect(10, 135, 21, 16));
        lbNumAI_35->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_35->setFont(font);
        lbNumAI_35->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAI_39 = new WLabel(panel2);
        lbAI_39->setObjectName(QString::fromUtf8("lbAI_39"));
        lbAI_39->setGeometry(QRect(366, 115, 66, 20));
        lbAI_39->setLayoutDirection(Qt::RightToLeft);
        lbAI_39->setFont(font);
        lbAI_39->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumAI_36 = new WLabel(panel2);
        lbNumAI_36->setObjectName(QString::fromUtf8("lbNumAI_36"));
        lbNumAI_36->setGeometry(QRect(10, 175, 21, 16));
        lbNumAI_36->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_36->setFont(font);
        lbNumAI_36->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_41 = new WLabel(panel2);
        lbAIT_41->setObjectName(QString::fromUtf8("lbAIT_41"));
        lbAIT_41->setGeometry(QRect(33, 155, 340, 16));
        lbAIT_41->setFont(font);
        lbAIT_41->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_42 = new WLabel(panel2);
        lbAIT_42->setObjectName(QString::fromUtf8("lbAIT_42"));
        lbAIT_42->setGeometry(QRect(35, 115, 340, 16));
        lbAIT_42->setFont(font);
        lbAIT_42->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frBarraT_2 = new QFrame(panel2);
        frBarraT_2->setObjectName(QString::fromUtf8("frBarraT_2"));
        frBarraT_2->setGeometry(QRect(0, 0, 485, 15));
        frBarraT_2->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frBarraT_2->setFrameShape(QFrame::Panel);
        frBarraT_2->setFrameShadow(QFrame::Raised);
        frBarraT_2->setLineWidth(0);
        lbAna24_S2T_2 = new WLabel(frBarraT_2);
        lbAna24_S2T_2->setObjectName(QString::fromUtf8("lbAna24_S2T_2"));
        lbAna24_S2T_2->setGeometry(QRect(3, 0, 111, 16));
        lbAna24_S2T_2->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        lbAna24_S2T_2->setFont(font1);
        lbAna24_S2T_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_37 = new WLabel(panel2);
        lbAIU_37->setObjectName(QString::fromUtf8("lbAIU_37"));
        lbAIU_37->setGeometry(QRect(442, 135, 31, 20));
        lbAIU_37->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_37->setFont(font);
        lbAIU_37->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame_4 = new QFrame(panel2);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(0, 20, 485, 30));
        frame_4->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame_4->setFrameShape(QFrame::Box);
        frame_4->setFrameShadow(QFrame::Sunken);
        frame_4->setLineWidth(2);
        lbSloAl_2 = new WLabel(panel2);
        lbSloAl_2->setObjectName(QString::fromUtf8("lbSloAl_2"));
        lbSloAl_2->setGeometry(QRect(67, 23, 400, 22));
        lbSloAl_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        lbSloAl_2->setFont(font2);
        lbAIU_39 = new WLabel(panel2);
        lbAIU_39->setObjectName(QString::fromUtf8("lbAIU_39"));
        lbAIU_39->setGeometry(QRect(442, 195, 31, 20));
        lbAIU_39->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_39->setFont(font);
        lbAIU_39->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_41 = new WLabel(panel2);
        lbNumAI_41->setObjectName(QString::fromUtf8("lbNumAI_41"));
        lbNumAI_41->setGeometry(QRect(10, 115, 21, 16));
        lbNumAI_41->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_41->setFont(font);
        lbNumAI_41->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_44 = new WLabel(panel2);
        lbNumAI_44->setObjectName(QString::fromUtf8("lbNumAI_44"));
        lbNumAI_44->setGeometry(QRect(10, 75, 21, 16));
        lbNumAI_44->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_44->setFont(font);
        lbNumAI_44->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumAI_45 = new WLabel(panel2);
        lbNumAI_45->setObjectName(QString::fromUtf8("lbNumAI_45"));
        lbNumAI_45->setGeometry(QRect(10, 55, 21, 16));
        lbNumAI_45->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_45->setFont(font);
        lbNumAI_45->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_47 = new WLabel(panel2);
        lbAIU_47->setObjectName(QString::fromUtf8("lbAIU_47"));
        lbAIU_47->setGeometry(QRect(440, 155, 31, 20));
        lbAIU_47->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_47->setFont(font);
        lbAIU_47->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIT_48 = new WLabel(panel2);
        lbAIT_48->setObjectName(QString::fromUtf8("lbAIT_48"));
        lbAIT_48->setGeometry(QRect(35, 95, 340, 16));
        lbAIT_48->setFont(font);
        lbAIT_48->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbAIU_48 = new WLabel(panel2);
        lbAIU_48->setObjectName(QString::fromUtf8("lbAIU_48"));
        lbAIU_48->setGeometry(QRect(440, 75, 31, 20));
        lbAIU_48->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_48->setFont(font);
        lbAIU_48->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbFondo_2->raise();
        lbAI_26->raise();
        lbAI_28->raise();
        lbAIT_26->raise();
        lbAI_30->raise();
        lbAIU_27->raise();
        lbAI_33->raise();
        lbAIT_31->raise();
        lbAIT_32->raise();
        lbAIU_28->raise();
        lbNumAI_26->raise();
        lbAI_34->raise();
        lbAIT_33->raise();
        lbNumAI_27->raise();
        lbAI_35->raise();
        lbAI_36->raise();
        lbAIT_35->raise();
        lbAIU_29->raise();
        lbAIU_30->raise();
        lbNumAI_30->raise();
        lbNumAI_35->raise();
        lbAI_39->raise();
        lbNumAI_36->raise();
        lbAIT_41->raise();
        lbAIT_42->raise();
        frBarraT_2->raise();
        lbAIU_37->raise();
        frame_4->raise();
        lbSloAl_2->raise();
        lbAIU_39->raise();
        lbNumAI_41->raise();
        lbNumAI_44->raise();
        lbNumAI_45->raise();
        lbAIU_47->raise();
        lbAIT_48->raise();
        lbAIU_48->raise();
        frame = new QFrame(Analog24_S2);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 530, 486, 62));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        btnProx = new QPushButton(frame);
        btnProx->setObjectName(QString::fromUtf8("btnProx"));
        btnProx->setGeometry(QRect(290, 10, 101, 41));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        btnProx->setFont(font3);
        btnProx->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnCerrar = new QPushButton(frame);
        btnCerrar->setObjectName(QString::fromUtf8("btnCerrar"));
        btnCerrar->setGeometry(QRect(140, 10, 101, 41));
        btnCerrar->setFont(font3);
        btnCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        frame->raise();
        panel2->raise();
        panel1->raise();

        retranslateUi(Analog24_S2);

        QMetaObject::connectSlotsByName(Analog24_S2);
    } // setupUi

    void retranslateUi(QWidget *Analog24_S2)
    {
        Analog24_S2->setWindowTitle(QApplication::translate("Analog24_S2", "Analog24_S2", 0, QApplication::UnicodeUTF8));
        lbAIU_19->setText(QApplication::translate("Analog24_S2", "%", 0, QApplication::UnicodeUTF8));
        lbAI_14->setText(QApplication::translate("Analog24_S2", "27.50", 0, QApplication::UnicodeUTF8));
        lbAI_2->setText(QApplication::translate("Analog24_S2", "1599.00", 0, QApplication::UnicodeUTF8));
        lbAI_13->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAI_8->setText(QApplication::translate("Analog24_S2", "216.00", 0, QApplication::UnicodeUTF8));
        lbAI_12->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIU_13->setText(QString());
        lbAIT_15->setText(QApplication::translate("Analog24_S2", "PRESI\303\223N DIN\303\201MICA AC\303\232STICA (PX36B)", 0, QApplication::UnicodeUTF8));
        lbFondo->setText(QString());
        lbAIT_5->setText(QApplication::translate("Analog24_S2", "T3A2 HPC TEMP DE DESCARGA", 0, QApplication::UnicodeUTF8));
        lbAIT_18->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAI_3->setText(QApplication::translate("Analog24_S2", "1615.00", 0, QApplication::UnicodeUTF8));
        lbAI_22->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIT_11->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_13->setText(QApplication::translate("Analog24_S2", "13", 0, QApplication::UnicodeUTF8));
        lbAIT_20->setText(QApplication::translate("Analog24_S2", "GRAV ESPECIFICA DE GAS COMB", 0, QApplication::UnicodeUTF8));
        lbAIU_3->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_15->setText(QApplication::translate("Analog24_S2", "2.16", 0, QApplication::UnicodeUTF8));
        lbAIT_14->setText(QApplication::translate("Analog24_S2", "P25B HPC PRES TOTAL ENTRADA \"B\"", 0, QApplication::UnicodeUTF8));
        lbAI_7->setText(QApplication::translate("Analog24_S2", "49.00", 0, QApplication::UnicodeUTF8));
        lbAIT_8->setText(QApplication::translate("Analog24_S2", "TEMP ADMIS AIRE COMPRESOR HP T25B", 0, QApplication::UnicodeUTF8));
        lbAIT_7->setText(QApplication::translate("Analog24_S2", "T2B LPC TEMP ADMIS DE AIRE", 0, QApplication::UnicodeUTF8));
        lbAIU_4->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_3->setText(QApplication::translate("Analog24_S2", "3", 0, QApplication::UnicodeUTF8));
        lbAI_1->setText(QApplication::translate("Analog24_S2", "1561.00", 0, QApplication::UnicodeUTF8));
        lbAIT_1->setText(QApplication::translate("Analog24_S2", "TEMP DE ENTRADA DE GAS LPT T48B (ARRIBA)", 0, QApplication::UnicodeUTF8));
        lbAIT_12->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_6->setText(QApplication::translate("Analog24_S2", "6", 0, QApplication::UnicodeUTF8));
        lbAI_6->setText(QApplication::translate("Analog24_S2", "981.00", 0, QApplication::UnicodeUTF8));
        lbAI_5->setText(QApplication::translate("Analog24_S2", "982.00", 0, QApplication::UnicodeUTF8));
        lbAIT_2->setText(QApplication::translate("Analog24_S2", "TEMP DE ENTRADA DE GAS LPT T48D (ABAJO)", 0, QApplication::UnicodeUTF8));
        lbNumAI_16->setText(QApplication::translate("Analog24_S2", "16", 0, QApplication::UnicodeUTF8));
        lbAIU_7->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_22->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_20->setText(QApplication::translate("Analog24_S2", "20", 0, QApplication::UnicodeUTF8));
        lbAIU_1->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_24->setText(QApplication::translate("Analog24_S2", "325.40", 0, QApplication::UnicodeUTF8));
        lbAIT_24->setText(QApplication::translate("Analog24_S2", "PS3B PRES ST DE DESCARGA HPC", 0, QApplication::UnicodeUTF8));
        lbNumAI_8->setText(QApplication::translate("Analog24_S2", "8", 0, QApplication::UnicodeUTF8));
        lbAIU_11->setText(QString());
        lbNumAI_22->setText(QApplication::translate("Analog24_S2", "22", 0, QApplication::UnicodeUTF8));
        lbNumAI_18->setText(QApplication::translate("Analog24_S2", "18", 0, QApplication::UnicodeUTF8));
        lbNumAI_15->setText(QApplication::translate("Analog24_S2", "15", 0, QApplication::UnicodeUTF8));
        lbAI_19->setText(QApplication::translate("Analog24_S2", "0.10", 0, QApplication::UnicodeUTF8));
        lbNumAI_10->setText(QApplication::translate("Analog24_S2", "10", 0, QApplication::UnicodeUTF8));
        lbAIU_24->setText(QApplication::translate("Analog24_S2", "PSIA", 0, QApplication::UnicodeUTF8));
        lbNumAI_5->setText(QApplication::translate("Analog24_S2", "5", 0, QApplication::UnicodeUTF8));
        lbAIT_17->setText(QApplication::translate("Analog24_S2", "PRES DE BALANCE DE IMPULSO PTBB", 0, QApplication::UnicodeUTF8));
        lbAIU_16->setText(QString());
        lbAI_4->setText(QApplication::translate("Analog24_S2", "1601.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_7->setText(QApplication::translate("Analog24_S2", "7", 0, QApplication::UnicodeUTF8));
        lbAI_16->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIU_10->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_9->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIT_21->setText(QApplication::translate("Analog24_S2", "NIVEL TANQUE DE LUB DE CAJA DE ENGRAN DE", 0, QApplication::UnicodeUTF8));
        lbAIU_18->setText(QApplication::translate("Analog24_S2", "MA", 0, QApplication::UnicodeUTF8));
        lbAIT_6->setText(QApplication::translate("Analog24_S2", "T3B2 HPC TEMP DE DESCARGA", 0, QApplication::UnicodeUTF8));
        lbAI_10->setText(QApplication::translate("Analog24_S2", "78.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_12->setText(QApplication::translate("Analog24_S2", "12", 0, QApplication::UnicodeUTF8));
        lbAI_17->setText(QApplication::translate("Analog24_S2", "64.80", 0, QApplication::UnicodeUTF8));
        lbAIT_4->setText(QApplication::translate("Analog24_S2", "TEMP DE ENTRADA DE GAS LPT T48H (ARRIBA)", 0, QApplication::UnicodeUTF8));
        lbAI_21->setText(QApplication::translate("Analog24_S2", "0.90", 0, QApplication::UnicodeUTF8));
        lbAIT_16->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAna24_S2T->setText(QApplication::translate("Analog24_S2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">ANALOG24_S2.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbNumAI_14->setText(QApplication::translate("Analog24_S2", "14", 0, QApplication::UnicodeUTF8));
        lbAIU_20->setText(QString());
        lbAI_9->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIT_23->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIU_5->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_21->setText(QApplication::translate("Analog24_S2", "PPM", 0, QApplication::UnicodeUTF8));
        lbSloAl->setText(QApplication::translate("Analog24_S2", "SLOT-  A107  - Al", 0, QApplication::UnicodeUTF8));
        lbAIU_8->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_17->setText(QApplication::translate("Analog24_S2", "PSIA", 0, QApplication::UnicodeUTF8));
        lbAI_18->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIU_22->setText(QString());
        lbAIT_10->setText(QApplication::translate("Analog24_S2", "SENSOR B TEMPERATURA DE GAS COMB", 0, QApplication::UnicodeUTF8));
        lbAI_23->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_17->setText(QApplication::translate("Analog24_S2", "17", 0, QApplication::UnicodeUTF8));
        lbAIU_9->setText(QString());
        lbNumAI_21->setText(QApplication::translate("Analog24_S2", "21", 0, QApplication::UnicodeUTF8));
        lbAIT_19->setText(QApplication::translate("Analog24_S2", "HUMEDAD DE GAS COMBUSTIBLE", 0, QApplication::UnicodeUTF8));
        lbAIU_14->setText(QApplication::translate("Analog24_S2", "PSIA", 0, QApplication::UnicodeUTF8));
        lbNumAI_4->setText(QApplication::translate("Analog24_S2", "4", 0, QApplication::UnicodeUTF8));
        lbAIU_23->setText(QString());
        lbAI_11->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIU_15->setText(QApplication::translate("Analog24_S2", "PSID", 0, QApplication::UnicodeUTF8));
        lbAIT_13->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_11->setText(QApplication::translate("Analog24_S2", "11", 0, QApplication::UnicodeUTF8));
        lbAIU_12->setText(QString());
        lbNumAI_23->setText(QApplication::translate("Analog24_S2", "23", 0, QApplication::UnicodeUTF8));
        lbNumAI_2->setText(QApplication::translate("Analog24_S2", "2", 0, QApplication::UnicodeUTF8));
        lbNumAI_1->setText(QApplication::translate("Analog24_S2", "1", 0, QApplication::UnicodeUTF8));
        lbNumAI_24->setText(QApplication::translate("Analog24_S2", "24", 0, QApplication::UnicodeUTF8));
        lbAIU_6->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_9->setText(QApplication::translate("Analog24_S2", "9", 0, QApplication::UnicodeUTF8));
        lbAIT_3->setText(QApplication::translate("Analog24_S2", "TEMP DE ENTRADA DE GAS LPT T48F (ABAJO)", 0, QApplication::UnicodeUTF8));
        lbNumAI_19->setText(QApplication::translate("Analog24_S2", "19", 0, QApplication::UnicodeUTF8));
        lbAIU_2->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_20->setText(QApplication::translate("Analog24_S2", "0.58", 0, QApplication::UnicodeUTF8));
        lbAI_26->setText(QApplication::translate("Analog24_S2", "1599.00", 0, QApplication::UnicodeUTF8));
        lbAI_28->setText(QApplication::translate("Analog24_S2", "216.00", 0, QApplication::UnicodeUTF8));
        lbFondo_2->setText(QString());
        lbAIT_26->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAI_30->setText(QApplication::translate("Analog24_S2", "1615.00", 0, QApplication::UnicodeUTF8));
        lbAIU_27->setText(QString());
        lbAI_33->setText(QApplication::translate("Analog24_S2", "49.00", 0, QApplication::UnicodeUTF8));
        lbAIT_31->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIT_32->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIU_28->setText(QString());
        lbNumAI_26->setText(QApplication::translate("Analog24_S2", "3", 0, QApplication::UnicodeUTF8));
        lbAI_34->setText(QApplication::translate("Analog24_S2", "1561.00", 0, QApplication::UnicodeUTF8));
        lbAIT_33->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_27->setText(QApplication::translate("Analog24_S2", "6", 0, QApplication::UnicodeUTF8));
        lbAI_35->setText(QApplication::translate("Analog24_S2", "981.00", 0, QApplication::UnicodeUTF8));
        lbAI_36->setText(QApplication::translate("Analog24_S2", "982.00", 0, QApplication::UnicodeUTF8));
        lbAIT_35->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIU_29->setText(QString());
        lbAIU_30->setText(QString());
        lbNumAI_30->setText(QApplication::translate("Analog24_S2", "8", 0, QApplication::UnicodeUTF8));
        lbNumAI_35->setText(QApplication::translate("Analog24_S2", "5", 0, QApplication::UnicodeUTF8));
        lbAI_39->setText(QApplication::translate("Analog24_S2", "1601.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_36->setText(QApplication::translate("Analog24_S2", "7", 0, QApplication::UnicodeUTF8));
        lbAIT_41->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIT_42->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAna24_S2T_2->setText(QApplication::translate("Analog24_S2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">ANALOG24_S2.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbAIU_37->setText(QString());
        lbSloAl_2->setText(QApplication::translate("Analog24_S2", "SLOT-  A107  - A0", 0, QApplication::UnicodeUTF8));
        lbAIU_39->setText(QString());
        lbNumAI_41->setText(QApplication::translate("Analog24_S2", "4", 0, QApplication::UnicodeUTF8));
        lbNumAI_44->setText(QApplication::translate("Analog24_S2", "2", 0, QApplication::UnicodeUTF8));
        lbNumAI_45->setText(QApplication::translate("Analog24_S2", "1", 0, QApplication::UnicodeUTF8));
        lbAIU_47->setText(QString());
        lbAIT_48->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIU_48->setText(QString());
        btnProx->setText(QApplication::translate("Analog24_S2", "PR\303\223X >", 0, QApplication::UnicodeUTF8));
        btnCerrar->setText(QApplication::translate("Analog24_S2", "CERRAR", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Analog24_S2: public Ui_Analog24_S2 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ANALOG24_S2_H
