/********************************************************************************
** Form generated from reading UI file 'd1.ui'
**
** Created: Tue 17. Dec 02:39:54 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_D1_H
#define UI_D1_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCommandLinkButton>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "awmultiobject.h"

QT_BEGIN_NAMESPACE

class Ui_D1
{
public:
    QLabel *lbIMGFondo;
    QLabel *lbInd_1;
    QLabel *lbInd_2;
    QLabel *lbInd_3;
    QLabel *lbInd_4;
    QLabel *lbInd_5;
    QLabel *lbInd_6;
    QLabel *lbInd_7;
    QLabel *lbInd_8;
    QLabel *lbInd_9;
    QLabel *lbInd_10;
    QLabel *lbInd_11;
    QLabel *lbInd_12;
    QLabel *lbInd_13;
    QLabel *lbInd_14;
    QLabel *lbInd_15;
    QLabel *lbInd_16;
    QLabel *lbInd_17;
    QLabel *lbInd_18;
    QLabel *lbInd_19;
    QLabel *lbInd_20;
    QLabel *lbInd_21;
    QLabel *lbInd_22;
    QLabel *lbInd_23;
    QLabel *lbInd_24;
    QLabel *lbInd_25;
    QLabel *lbInd_26;
    QLabel *lbInd_27;
    QLabel *lbInd_28;
    QLabel *lbInd_29;
    QLabel *lbInd_30;
    QLabel *lbInd_31;
    QLabel *lbInd_32;
    AWMultiObject *WCuadrado_1;
    AWMultiObject *WCuadrado_2;
    AWMultiObject *WCuadrado_3;
    AWMultiObject *WCuadrado_4;
    AWMultiObject *WCuadrado_5;
    AWMultiObject *WCuadrado_7;
    AWMultiObject *WCuadrado_8;
    AWMultiObject *WCuadrado_9;
    AWMultiObject *WCuadrado_10;
    AWMultiObject *WCuadrado_11;
    AWMultiObject *WCuadrado_12;
    AWMultiObject *WCuadrado_13;
    AWMultiObject *WCuadrado_14;
    AWMultiObject *WCuadrado_15;
    AWMultiObject *WCuadrado_16;
    AWMultiObject *WCuadrado_17;
    AWMultiObject *WCuadrado_18;
    QPushButton *btnRed_1;
    QPushButton *btnRed_2;
    QPushButton *btnRed_3;
    QPushButton *btnImprimir;
    QLabel *lbUnit3;
    QCommandLinkButton *btind1;
    QCommandLinkButton *btind2;
    QCommandLinkButton *btind4;
    QCommandLinkButton *btind3;
    QCommandLinkButton *btind8;
    QCommandLinkButton *btind5;
    QCommandLinkButton *btind7;
    QCommandLinkButton *btind6;
    QCommandLinkButton *btnind12;
    QCommandLinkButton *btnind9;
    QCommandLinkButton *btind11;
    QCommandLinkButton *btnind10;
    QCommandLinkButton *btnind23;
    QCommandLinkButton *btnind14;
    QCommandLinkButton *btnind13;
    QCommandLinkButton *btnind17;
    QCommandLinkButton *btnind22;
    QCommandLinkButton *btnind18_2;
    QCommandLinkButton *btnind19;
    QCommandLinkButton *btnind20;
    QCommandLinkButton *btnind15;
    QCommandLinkButton *btnind16;
    QCommandLinkButton *btnind18;
    QCommandLinkButton *btnind21;

    void setupUi(QWidget *D1)
    {
        if (D1->objectName().isEmpty())
            D1->setObjectName(QString::fromUtf8("D1"));
        D1->resize(1024, 662);
        D1->setStyleSheet(QString::fromUtf8(""));
        lbIMGFondo = new QLabel(D1);
        lbIMGFondo->setObjectName(QString::fromUtf8("lbIMGFondo"));
        lbIMGFondo->setGeometry(QRect(0, 0, 1024, 664));
        lbIMGFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/D1.png")));
        lbIMGFondo->setScaledContents(true);
        lbInd_1 = new QLabel(D1);
        lbInd_1->setObjectName(QString::fromUtf8("lbInd_1"));
        lbInd_1->setGeometry(QRect(90, 63, 21, 21));
        QFont font;
        font.setFamily(QString::fromUtf8("Verdana"));
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        lbInd_1->setFont(font);
        lbInd_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_2 = new QLabel(D1);
        lbInd_2->setObjectName(QString::fromUtf8("lbInd_2"));
        lbInd_2->setGeometry(QRect(193, 62, 21, 21));
        lbInd_2->setFont(font);
        lbInd_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_3 = new QLabel(D1);
        lbInd_3->setObjectName(QString::fromUtf8("lbInd_3"));
        lbInd_3->setGeometry(QRect(227, 62, 16, 21));
        lbInd_3->setFont(font);
        lbInd_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_4 = new QLabel(D1);
        lbInd_4->setObjectName(QString::fromUtf8("lbInd_4"));
        lbInd_4->setGeometry(QRect(260, 62, 21, 21));
        lbInd_4->setFont(font);
        lbInd_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_5 = new QLabel(D1);
        lbInd_5->setObjectName(QString::fromUtf8("lbInd_5"));
        lbInd_5->setGeometry(QRect(295, 62, 21, 21));
        lbInd_5->setFont(font);
        lbInd_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_6 = new QLabel(D1);
        lbInd_6->setObjectName(QString::fromUtf8("lbInd_6"));
        lbInd_6->setGeometry(QRect(330, 62, 21, 21));
        lbInd_6->setFont(font);
        lbInd_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_7 = new QLabel(D1);
        lbInd_7->setObjectName(QString::fromUtf8("lbInd_7"));
        lbInd_7->setGeometry(QRect(363, 62, 21, 21));
        lbInd_7->setFont(font);
        lbInd_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_8 = new QLabel(D1);
        lbInd_8->setObjectName(QString::fromUtf8("lbInd_8"));
        lbInd_8->setGeometry(QRect(395, 62, 21, 21));
        lbInd_8->setFont(font);
        lbInd_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_9 = new QLabel(D1);
        lbInd_9->setObjectName(QString::fromUtf8("lbInd_9"));
        lbInd_9->setGeometry(QRect(430, 62, 21, 21));
        lbInd_9->setFont(font);
        lbInd_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_10 = new QLabel(D1);
        lbInd_10->setObjectName(QString::fromUtf8("lbInd_10"));
        lbInd_10->setGeometry(QRect(460, 62, 21, 21));
        lbInd_10->setFont(font);
        lbInd_10->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_11 = new QLabel(D1);
        lbInd_11->setObjectName(QString::fromUtf8("lbInd_11"));
        lbInd_11->setGeometry(QRect(86, 317, 31, 21));
        lbInd_11->setFont(font);
        lbInd_11->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_12 = new QLabel(D1);
        lbInd_12->setObjectName(QString::fromUtf8("lbInd_12"));
        lbInd_12->setGeometry(QRect(186, 317, 31, 21));
        lbInd_12->setFont(font);
        lbInd_12->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_13 = new QLabel(D1);
        lbInd_13->setObjectName(QString::fromUtf8("lbInd_13"));
        lbInd_13->setGeometry(QRect(222, 317, 31, 21));
        lbInd_13->setFont(font);
        lbInd_13->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_14 = new QLabel(D1);
        lbInd_14->setObjectName(QString::fromUtf8("lbInd_14"));
        lbInd_14->setGeometry(QRect(260, 317, 31, 21));
        lbInd_14->setFont(font);
        lbInd_14->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_14->setAlignment(Qt::AlignCenter);
        lbInd_15 = new QLabel(D1);
        lbInd_15->setObjectName(QString::fromUtf8("lbInd_15"));
        lbInd_15->setGeometry(QRect(290, 317, 31, 21));
        lbInd_15->setFont(font);
        lbInd_15->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_15->setAlignment(Qt::AlignCenter);
        lbInd_16 = new QLabel(D1);
        lbInd_16->setObjectName(QString::fromUtf8("lbInd_16"));
        lbInd_16->setGeometry(QRect(325, 317, 31, 21));
        lbInd_16->setFont(font);
        lbInd_16->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_16->setAlignment(Qt::AlignCenter);
        lbInd_17 = new QLabel(D1);
        lbInd_17->setObjectName(QString::fromUtf8("lbInd_17"));
        lbInd_17->setGeometry(QRect(355, 317, 31, 21));
        lbInd_17->setFont(font);
        lbInd_17->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_17->setAlignment(Qt::AlignCenter);
        lbInd_18 = new QLabel(D1);
        lbInd_18->setObjectName(QString::fromUtf8("lbInd_18"));
        lbInd_18->setGeometry(QRect(390, 317, 31, 21));
        lbInd_18->setFont(font);
        lbInd_18->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_18->setAlignment(Qt::AlignCenter);
        lbInd_19 = new QLabel(D1);
        lbInd_19->setObjectName(QString::fromUtf8("lbInd_19"));
        lbInd_19->setGeometry(QRect(425, 317, 31, 21));
        lbInd_19->setFont(font);
        lbInd_19->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_19->setAlignment(Qt::AlignCenter);
        lbInd_20 = new QLabel(D1);
        lbInd_20->setObjectName(QString::fromUtf8("lbInd_20"));
        lbInd_20->setGeometry(QRect(460, 317, 31, 21));
        lbInd_20->setFont(font);
        lbInd_20->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_20->setAlignment(Qt::AlignCenter);
        lbInd_21 = new QLabel(D1);
        lbInd_21->setObjectName(QString::fromUtf8("lbInd_21"));
        lbInd_21->setGeometry(QRect(93, 370, 31, 21));
        lbInd_21->setFont(font);
        lbInd_21->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_22 = new QLabel(D1);
        lbInd_22->setObjectName(QString::fromUtf8("lbInd_22"));
        lbInd_22->setGeometry(QRect(126, 370, 31, 21));
        lbInd_22->setFont(font);
        lbInd_22->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_23 = new QLabel(D1);
        lbInd_23->setObjectName(QString::fromUtf8("lbInd_23"));
        lbInd_23->setGeometry(QRect(194, 370, 31, 21));
        lbInd_23->setFont(font);
        lbInd_23->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_24 = new QLabel(D1);
        lbInd_24->setObjectName(QString::fromUtf8("lbInd_24"));
        lbInd_24->setGeometry(QRect(228, 370, 31, 20));
        lbInd_24->setFont(font);
        lbInd_24->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_25 = new QLabel(D1);
        lbInd_25->setObjectName(QString::fromUtf8("lbInd_25"));
        lbInd_25->setGeometry(QRect(263, 370, 31, 20));
        lbInd_25->setFont(font);
        lbInd_25->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_26 = new QLabel(D1);
        lbInd_26->setObjectName(QString::fromUtf8("lbInd_26"));
        lbInd_26->setGeometry(QRect(466, 368, 31, 20));
        lbInd_26->setFont(font);
        lbInd_26->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_27 = new QLabel(D1);
        lbInd_27->setObjectName(QString::fromUtf8("lbInd_27"));
        lbInd_27->setGeometry(QRect(84, 622, 31, 20));
        lbInd_27->setFont(font);
        lbInd_27->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_27->setAlignment(Qt::AlignCenter);
        lbInd_28 = new QLabel(D1);
        lbInd_28->setObjectName(QString::fromUtf8("lbInd_28"));
        lbInd_28->setGeometry(QRect(118, 622, 31, 20));
        lbInd_28->setFont(font);
        lbInd_28->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_28->setAlignment(Qt::AlignCenter);
        lbInd_29 = new QLabel(D1);
        lbInd_29->setObjectName(QString::fromUtf8("lbInd_29"));
        lbInd_29->setGeometry(QRect(185, 622, 31, 20));
        lbInd_29->setFont(font);
        lbInd_29->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_29->setAlignment(Qt::AlignCenter);
        lbInd_30 = new QLabel(D1);
        lbInd_30->setObjectName(QString::fromUtf8("lbInd_30"));
        lbInd_30->setGeometry(QRect(220, 622, 31, 20));
        lbInd_30->setFont(font);
        lbInd_30->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_30->setAlignment(Qt::AlignCenter);
        lbInd_31 = new QLabel(D1);
        lbInd_31->setObjectName(QString::fromUtf8("lbInd_31"));
        lbInd_31->setGeometry(QRect(252, 622, 31, 20));
        lbInd_31->setFont(font);
        lbInd_31->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_31->setAlignment(Qt::AlignCenter);
        lbInd_32 = new QLabel(D1);
        lbInd_32->setObjectName(QString::fromUtf8("lbInd_32"));
        lbInd_32->setGeometry(QRect(465, 622, 31, 20));
        lbInd_32->setFont(font);
        lbInd_32->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        WCuadrado_1 = new AWMultiObject(D1);
        WCuadrado_1->setObjectName(QString::fromUtf8("WCuadrado_1"));
        WCuadrado_1->setGeometry(QRect(92, 490, 25, 25));
        WCuadrado_1->setElementType(AWMultiObject::SQUARE);
        WCuadrado_1->setOnColor(AWMultiObject::Grey);
        WCuadrado_1->setOffColor(AWMultiObject::Green);
        WCuadrado_2 = new AWMultiObject(D1);
        WCuadrado_2->setObjectName(QString::fromUtf8("WCuadrado_2"));
        WCuadrado_2->setGeometry(QRect(190, 490, 25, 25));
        WCuadrado_2->setElementType(AWMultiObject::SQUARE);
        WCuadrado_2->setOnColor(AWMultiObject::Grey);
        WCuadrado_2->setOffColor(AWMultiObject::Green);
        WCuadrado_3 = new AWMultiObject(D1);
        WCuadrado_3->setObjectName(QString::fromUtf8("WCuadrado_3"));
        WCuadrado_3->setGeometry(QRect(225, 490, 25, 25));
        WCuadrado_3->setElementType(AWMultiObject::SQUARE);
        WCuadrado_3->setOnColor(AWMultiObject::Grey);
        WCuadrado_3->setOffColor(AWMultiObject::Green);
        WCuadrado_4 = new AWMultiObject(D1);
        WCuadrado_4->setObjectName(QString::fromUtf8("WCuadrado_4"));
        WCuadrado_4->setGeometry(QRect(260, 490, 25, 25));
        WCuadrado_4->setElementType(AWMultiObject::SQUARE);
        WCuadrado_4->setOnColor(AWMultiObject::Grey);
        WCuadrado_4->setOffColor(AWMultiObject::Green);
        WCuadrado_5 = new AWMultiObject(D1);
        WCuadrado_5->setObjectName(QString::fromUtf8("WCuadrado_5"));
        WCuadrado_5->setGeometry(QRect(190, 193, 25, 25));
        WCuadrado_5->setElementType(AWMultiObject::SQUARE);
        WCuadrado_5->setOnColor(AWMultiObject::Grey);
        WCuadrado_5->setOffColor(AWMultiObject::Green);
        WCuadrado_7 = new AWMultiObject(D1);
        WCuadrado_7->setObjectName(QString::fromUtf8("WCuadrado_7"));
        WCuadrado_7->setGeometry(QRect(225, 193, 25, 25));
        WCuadrado_7->setElementType(AWMultiObject::SQUARE);
        WCuadrado_7->setOnColor(AWMultiObject::Grey);
        WCuadrado_7->setOffColor(AWMultiObject::Green);
        WCuadrado_8 = new AWMultiObject(D1);
        WCuadrado_8->setObjectName(QString::fromUtf8("WCuadrado_8"));
        WCuadrado_8->setGeometry(QRect(259, 193, 25, 25));
        WCuadrado_8->setElementType(AWMultiObject::SQUARE);
        WCuadrado_8->setOnColor(AWMultiObject::Grey);
        WCuadrado_8->setOffColor(AWMultiObject::Green);
        WCuadrado_9 = new AWMultiObject(D1);
        WCuadrado_9->setObjectName(QString::fromUtf8("WCuadrado_9"));
        WCuadrado_9->setGeometry(QRect(294, 193, 25, 25));
        WCuadrado_9->setElementType(AWMultiObject::SQUARE);
        WCuadrado_9->setOnColor(AWMultiObject::Grey);
        WCuadrado_9->setOffColor(AWMultiObject::Green);
        WCuadrado_10 = new AWMultiObject(D1);
        WCuadrado_10->setObjectName(QString::fromUtf8("WCuadrado_10"));
        WCuadrado_10->setGeometry(QRect(327, 193, 25, 25));
        WCuadrado_10->setElementType(AWMultiObject::SQUARE);
        WCuadrado_10->setOnColor(AWMultiObject::Grey);
        WCuadrado_10->setOffColor(AWMultiObject::Green);
        WCuadrado_11 = new AWMultiObject(D1);
        WCuadrado_11->setObjectName(QString::fromUtf8("WCuadrado_11"));
        WCuadrado_11->setGeometry(QRect(363, 193, 25, 25));
        WCuadrado_11->setElementType(AWMultiObject::SQUARE);
        WCuadrado_11->setOnColor(AWMultiObject::Grey);
        WCuadrado_11->setOffColor(AWMultiObject::Green);
        WCuadrado_12 = new AWMultiObject(D1);
        WCuadrado_12->setObjectName(QString::fromUtf8("WCuadrado_12"));
        WCuadrado_12->setGeometry(QRect(397, 193, 25, 25));
        WCuadrado_12->setElementType(AWMultiObject::SQUARE);
        WCuadrado_12->setOnColor(AWMultiObject::Grey);
        WCuadrado_12->setOffColor(AWMultiObject::Green);
        WCuadrado_13 = new AWMultiObject(D1);
        WCuadrado_13->setObjectName(QString::fromUtf8("WCuadrado_13"));
        WCuadrado_13->setGeometry(QRect(464, 193, 25, 25));
        WCuadrado_13->setElementType(AWMultiObject::SQUARE);
        WCuadrado_13->setOnColor(AWMultiObject::Grey);
        WCuadrado_13->setOffColor(AWMultiObject::Green);
        WCuadrado_14 = new AWMultiObject(D1);
        WCuadrado_14->setObjectName(QString::fromUtf8("WCuadrado_14"));
        WCuadrado_14->setGeometry(QRect(460, 400, 25, 25));
        WCuadrado_14->setElementType(AWMultiObject::SQUARE);
        WCuadrado_14->setOnColor(AWMultiObject::Grey);
        WCuadrado_14->setOffColor(AWMultiObject::Blue);
        WCuadrado_15 = new AWMultiObject(D1);
        WCuadrado_15->setObjectName(QString::fromUtf8("WCuadrado_15"));
        WCuadrado_15->setGeometry(QRect(460, 421, 25, 25));
        WCuadrado_15->setElementType(AWMultiObject::SQUARE);
        WCuadrado_15->setOnColor(AWMultiObject::Grey);
        WCuadrado_15->setOffColor(AWMultiObject::Blue);
        WCuadrado_16 = new AWMultiObject(D1);
        WCuadrado_16->setObjectName(QString::fromUtf8("WCuadrado_16"));
        WCuadrado_16->setGeometry(QRect(460, 444, 25, 25));
        WCuadrado_16->setElementType(AWMultiObject::SQUARE);
        WCuadrado_16->setOnColor(AWMultiObject::Grey);
        WCuadrado_16->setOffColor(AWMultiObject::Blue);
        WCuadrado_17 = new AWMultiObject(D1);
        WCuadrado_17->setObjectName(QString::fromUtf8("WCuadrado_17"));
        WCuadrado_17->setGeometry(QRect(460, 470, 25, 25));
        WCuadrado_17->setElementType(AWMultiObject::SQUARE);
        WCuadrado_17->setOnColor(AWMultiObject::Grey);
        WCuadrado_17->setOffColor(AWMultiObject::Blue);
        WCuadrado_18 = new AWMultiObject(D1);
        WCuadrado_18->setObjectName(QString::fromUtf8("WCuadrado_18"));
        WCuadrado_18->setGeometry(QRect(460, 496, 25, 25));
        WCuadrado_18->setElementType(AWMultiObject::SQUARE);
        WCuadrado_18->setOnColor(AWMultiObject::Grey);
        WCuadrado_18->setOffColor(AWMultiObject::Green);
        btnRed_1 = new QPushButton(D1);
        btnRed_1->setObjectName(QString::fromUtf8("btnRed_1"));
        btnRed_1->setGeometry(QRect(625, 480, 190, 31));
        QFont font1;
        font1.setPointSize(12);
        font1.setBold(true);
        font1.setWeight(75);
        btnRed_1->setFont(font1);
        btnRed_1->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnRed_2 = new QPushButton(D1);
        btnRed_2->setObjectName(QString::fromUtf8("btnRed_2"));
        btnRed_2->setGeometry(QRect(625, 517, 190, 31));
        btnRed_2->setFont(font1);
        btnRed_2->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnRed_3 = new QPushButton(D1);
        btnRed_3->setObjectName(QString::fromUtf8("btnRed_3"));
        btnRed_3->setGeometry(QRect(625, 554, 190, 31));
        btnRed_3->setFont(font1);
        btnRed_3->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnImprimir = new QPushButton(D1);
        btnImprimir->setObjectName(QString::fromUtf8("btnImprimir"));
        btnImprimir->setGeometry(QRect(780, 620, 143, 21));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        btnImprimir->setFont(font2);
        btnImprimir->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbUnit3 = new QLabel(D1);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(837, 647, 190, 15));
        lbUnit3->setFont(font2);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        btind1 = new QCommandLinkButton(D1);
        btind1->setObjectName(QString::fromUtf8("btind1"));
        btind1->setGeometry(QRect(84, 50, 36, 301));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Resources/PNG/Extras/transparente.svg"), QSize(), QIcon::Normal, QIcon::Off);
        btind1->setIcon(icon);
        btind2 = new QCommandLinkButton(D1);
        btind2->setObjectName(QString::fromUtf8("btind2"));
        btind2->setGeometry(QRect(118, 50, 36, 301));
        btind2->setIcon(icon);
        btind4 = new QCommandLinkButton(D1);
        btind4->setObjectName(QString::fromUtf8("btind4"));
        btind4->setGeometry(QRect(186, 50, 36, 301));
        btind4->setIcon(icon);
        btind3 = new QCommandLinkButton(D1);
        btind3->setObjectName(QString::fromUtf8("btind3"));
        btind3->setGeometry(QRect(153, 50, 36, 301));
        btind3->setIcon(icon);
        btind8 = new QCommandLinkButton(D1);
        btind8->setObjectName(QString::fromUtf8("btind8"));
        btind8->setGeometry(QRect(322, 50, 36, 301));
        btind8->setIcon(icon);
        btind5 = new QCommandLinkButton(D1);
        btind5->setObjectName(QString::fromUtf8("btind5"));
        btind5->setGeometry(QRect(219, 50, 36, 301));
        btind5->setIcon(icon);
        btind7 = new QCommandLinkButton(D1);
        btind7->setObjectName(QString::fromUtf8("btind7"));
        btind7->setGeometry(QRect(288, 50, 36, 301));
        btind7->setIcon(icon);
        btind6 = new QCommandLinkButton(D1);
        btind6->setObjectName(QString::fromUtf8("btind6"));
        btind6->setGeometry(QRect(254, 50, 36, 301));
        btind6->setIcon(icon);
        btnind12 = new QCommandLinkButton(D1);
        btnind12->setObjectName(QString::fromUtf8("btnind12"));
        btnind12->setGeometry(QRect(461, 50, 36, 301));
        btnind12->setIcon(icon);
        btnind9 = new QCommandLinkButton(D1);
        btnind9->setObjectName(QString::fromUtf8("btnind9"));
        btnind9->setGeometry(QRect(356, 50, 36, 301));
        btnind9->setIcon(icon);
        btind11 = new QCommandLinkButton(D1);
        btind11->setObjectName(QString::fromUtf8("btind11"));
        btind11->setGeometry(QRect(426, 50, 36, 301));
        btind11->setIcon(icon);
        btnind10 = new QCommandLinkButton(D1);
        btnind10->setObjectName(QString::fromUtf8("btnind10"));
        btnind10->setGeometry(QRect(390, 50, 36, 301));
        btnind10->setIcon(icon);
        btnind23 = new QCommandLinkButton(D1);
        btnind23->setObjectName(QString::fromUtf8("btnind23"));
        btnind23->setGeometry(QRect(461, 357, 36, 301));
        btnind23->setIcon(icon);
        btnind14 = new QCommandLinkButton(D1);
        btnind14->setObjectName(QString::fromUtf8("btnind14"));
        btnind14->setGeometry(QRect(118, 357, 36, 301));
        btnind14->setIcon(icon);
        btnind13 = new QCommandLinkButton(D1);
        btnind13->setObjectName(QString::fromUtf8("btnind13"));
        btnind13->setGeometry(QRect(84, 357, 36, 301));
        btnind13->setIcon(icon);
        btnind17 = new QCommandLinkButton(D1);
        btnind17->setObjectName(QString::fromUtf8("btnind17"));
        btnind17->setGeometry(QRect(220, 357, 36, 301));
        btnind17->setIcon(icon);
        btnind22 = new QCommandLinkButton(D1);
        btnind22->setObjectName(QString::fromUtf8("btnind22"));
        btnind22->setGeometry(QRect(426, 357, 36, 301));
        btnind22->setIcon(icon);
        btnind18_2 = new QCommandLinkButton(D1);
        btnind18_2->setObjectName(QString::fromUtf8("btnind18_2"));
        btnind18_2->setGeometry(QRect(288, 357, 36, 301));
        btnind18_2->setIcon(icon);
        btnind19 = new QCommandLinkButton(D1);
        btnind19->setObjectName(QString::fromUtf8("btnind19"));
        btnind19->setGeometry(QRect(322, 357, 36, 301));
        btnind19->setIcon(icon);
        btnind20 = new QCommandLinkButton(D1);
        btnind20->setObjectName(QString::fromUtf8("btnind20"));
        btnind20->setGeometry(QRect(356, 357, 36, 301));
        btnind20->setIcon(icon);
        btnind15 = new QCommandLinkButton(D1);
        btnind15->setObjectName(QString::fromUtf8("btnind15"));
        btnind15->setGeometry(QRect(153, 357, 36, 301));
        btnind15->setIcon(icon);
        btnind16 = new QCommandLinkButton(D1);
        btnind16->setObjectName(QString::fromUtf8("btnind16"));
        btnind16->setGeometry(QRect(186, 357, 36, 301));
        btnind16->setIcon(icon);
        btnind18 = new QCommandLinkButton(D1);
        btnind18->setObjectName(QString::fromUtf8("btnind18"));
        btnind18->setGeometry(QRect(254, 357, 36, 301));
        btnind18->setIcon(icon);
        btnind21 = new QCommandLinkButton(D1);
        btnind21->setObjectName(QString::fromUtf8("btnind21"));
        btnind21->setGeometry(QRect(390, 357, 36, 301));
        btnind21->setIcon(icon);
        lbIMGFondo->raise();
        lbInd_1->raise();
        lbInd_2->raise();
        lbInd_3->raise();
        lbInd_4->raise();
        lbInd_5->raise();
        lbInd_6->raise();
        lbInd_7->raise();
        lbInd_8->raise();
        lbInd_9->raise();
        lbInd_10->raise();
        lbInd_11->raise();
        lbInd_12->raise();
        lbInd_13->raise();
        lbInd_14->raise();
        lbInd_15->raise();
        lbInd_16->raise();
        lbInd_17->raise();
        lbInd_18->raise();
        lbInd_19->raise();
        lbInd_20->raise();
        lbInd_21->raise();
        lbInd_22->raise();
        lbInd_23->raise();
        lbInd_24->raise();
        lbInd_25->raise();
        lbInd_26->raise();
        lbInd_27->raise();
        lbInd_28->raise();
        lbInd_29->raise();
        lbInd_30->raise();
        lbInd_31->raise();
        lbInd_32->raise();
        WCuadrado_1->raise();
        WCuadrado_2->raise();
        WCuadrado_3->raise();
        WCuadrado_4->raise();
        WCuadrado_5->raise();
        WCuadrado_7->raise();
        WCuadrado_8->raise();
        WCuadrado_9->raise();
        WCuadrado_10->raise();
        WCuadrado_11->raise();
        WCuadrado_12->raise();
        WCuadrado_13->raise();
        WCuadrado_14->raise();
        WCuadrado_15->raise();
        WCuadrado_16->raise();
        WCuadrado_17->raise();
        WCuadrado_18->raise();
        btnRed_1->raise();
        btnRed_2->raise();
        btnRed_3->raise();
        btnImprimir->raise();
        lbUnit3->raise();
        btnind9->raise();
        btnind20->raise();
        btnind18_2->raise();
        btnind13->raise();
        btnind23->raise();
        btind6->raise();
        btind8->raise();
        btnind16->raise();
        btnind15->raise();
        btnind10->raise();
        btnind21->raise();
        btnind19->raise();
        btind1->raise();
        btind4->raise();
        btnind18->raise();
        btnind14->raise();
        btind2->raise();
        btind11->raise();
        btind7->raise();
        btind3->raise();
        btnind22->raise();
        btnind12->raise();
        btnind17->raise();
        btind5->raise();

        retranslateUi(D1);

        QMetaObject::connectSlotsByName(D1);
    } // setupUi

    void retranslateUi(QWidget *D1)
    {
        D1->setWindowTitle(QApplication::translate("D1", "D1", 0, QApplication::UnicodeUTF8));
        lbIMGFondo->setText(QString());
        lbInd_1->setText(QApplication::translate("D1", "01", 0, QApplication::UnicodeUTF8));
        lbInd_2->setText(QApplication::translate("D1", "04", 0, QApplication::UnicodeUTF8));
        lbInd_3->setText(QApplication::translate("D1", "05", 0, QApplication::UnicodeUTF8));
        lbInd_4->setText(QApplication::translate("D1", "06", 0, QApplication::UnicodeUTF8));
        lbInd_5->setText(QApplication::translate("D1", "07", 0, QApplication::UnicodeUTF8));
        lbInd_6->setText(QApplication::translate("D1", "08", 0, QApplication::UnicodeUTF8));
        lbInd_7->setText(QApplication::translate("D1", "09", 0, QApplication::UnicodeUTF8));
        lbInd_8->setText(QApplication::translate("D1", "10", 0, QApplication::UnicodeUTF8));
        lbInd_9->setText(QApplication::translate("D1", "11", 0, QApplication::UnicodeUTF8));
        lbInd_10->setText(QApplication::translate("D1", "12", 0, QApplication::UnicodeUTF8));
        lbInd_11->setText(QApplication::translate("D1", "CPU", 0, QApplication::UnicodeUTF8));
        lbInd_12->setText(QApplication::translate("D1", "MPU", 0, QApplication::UnicodeUTF8));
        lbInd_13->setText(QApplication::translate("D1", "SIO", 0, QApplication::UnicodeUTF8));
        lbInd_14->setText(QApplication::translate("D1", "Al", 0, QApplication::UnicodeUTF8));
        lbInd_15->setText(QApplication::translate("D1", "Al", 0, QApplication::UnicodeUTF8));
        lbInd_16->setText(QApplication::translate("D1", "DO", 0, QApplication::UnicodeUTF8));
        lbInd_17->setText(QApplication::translate("D1", "ACT", 0, QApplication::UnicodeUTF8));
        lbInd_18->setText(QApplication::translate("D1", "ACT", 0, QApplication::UnicodeUTF8));
        lbInd_19->setText(QApplication::translate("D1", "EXP", 0, QApplication::UnicodeUTF8));
        lbInd_20->setText(QApplication::translate("D1", "Dl", 0, QApplication::UnicodeUTF8));
        lbInd_21->setText(QApplication::translate("D1", "01", 0, QApplication::UnicodeUTF8));
        lbInd_22->setText(QApplication::translate("D1", "02", 0, QApplication::UnicodeUTF8));
        lbInd_23->setText(QApplication::translate("D1", "04", 0, QApplication::UnicodeUTF8));
        lbInd_24->setText(QApplication::translate("D1", "05", 0, QApplication::UnicodeUTF8));
        lbInd_25->setText(QApplication::translate("D1", "06", 0, QApplication::UnicodeUTF8));
        lbInd_26->setText(QApplication::translate("D1", "12", 0, QApplication::UnicodeUTF8));
        lbInd_27->setText(QApplication::translate("D1", "EXP", 0, QApplication::UnicodeUTF8));
        lbInd_28->setText(QApplication::translate("D1", "Dl", 0, QApplication::UnicodeUTF8));
        lbInd_29->setText(QApplication::translate("D1", "Al", 0, QApplication::UnicodeUTF8));
        lbInd_30->setText(QApplication::translate("D1", "Al", 0, QApplication::UnicodeUTF8));
        lbInd_31->setText(QApplication::translate("D1", "DVR", 0, QApplication::UnicodeUTF8));
        lbInd_32->setText(QApplication::translate("D1", "LN", 0, QApplication::UnicodeUTF8));
        WCuadrado_1->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN033_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_2->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN031_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_3->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN031_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_4->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN034_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_5->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN030_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_7->setId(QString());
        WCuadrado_8->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN031_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_9->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN032_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_10->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN033_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_11->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN034_F_CV ", 0, QApplication::UnicodeUTF8));
        WCuadrado_12->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN035_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_13->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN036_F_CV", 0, QApplication::UnicodeUTF8));
        WCuadrado_18->setId(QApplication::translate("D1", "p_Fix32_THISNODE_SDNGEN039_F_CV", 0, QApplication::UnicodeUTF8));
        btnRed_1->setText(QApplication::translate("D1", "RED DE C\303\223MPUTO 1", 0, QApplication::UnicodeUTF8));
        btnRed_2->setText(QApplication::translate("D1", "RED DE C\303\223MPUTO 2", 0, QApplication::UnicodeUTF8));
        btnRed_3->setText(QApplication::translate("D1", "RED DE C\303\223MPUTO 3", 0, QApplication::UnicodeUTF8));
        btnImprimir->setText(QApplication::translate("D1", "IMP PANT", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("D1", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btind1->setText(QString());
        btind2->setText(QString());
        btind4->setText(QString());
        btind3->setText(QString());
        btind8->setText(QString());
        btind5->setText(QString());
        btind7->setText(QString());
        btind6->setText(QString());
        btnind12->setText(QString());
        btnind9->setText(QString());
        btind11->setText(QString());
        btnind10->setText(QString());
        btnind23->setText(QString());
        btnind14->setText(QString());
        btnind13->setText(QString());
        btnind17->setText(QString());
        btnind22->setText(QString());
        btnind18_2->setText(QString());
        btnind19->setText(QString());
        btnind20->setText(QString());
        btnind15->setText(QString());
        btnind16->setText(QString());
        btnind18->setText(QString());
        btnind21->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class D1: public Ui_D1 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_D1_H
