/********************************************************************************
** Form generated from reading UI file 'f2.ui'
**
** Created: Fri 13. Dec 19:34:24 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_F2_H
#define UI_F2_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "awmultiobject.h"

QT_BEGIN_NAMESPACE

class Ui_F2
{
public:
    QLabel *lbIMGFondo;
    QFrame *fr_1;
    QFrame *frTitulo_1;
    QLabel *lbTitulo_1;
    QFrame *frTitulo_2;
    QLabel *lbTitulo_2;
    QLabel *lbTexto_1;
    AWMultiObject *aLet_1;
    QLabel *lbTexto_2;
    AWMultiObject *aLet_2;
    QLabel *lbTexto_3;
    AWMultiObject *aLet_3;
    QLabel *lbTexto_4;
    AWMultiObject *aLet_4;
    AWMultiObject *aLet_5;
    QLabel *lbTexto_5;
    AWMultiObject *aLet_6;
    QLabel *lbTexto_6;
    QLabel *lbTexto_7;
    AWMultiObject *aLet_7;
    AWMultiObject *aLet_8;
    QLabel *lbTexto_8;
    AWMultiObject *aLet_9;
    QLabel *lbTexto_9;
    QLabel *lbTexto_10;
    AWMultiObject *aLet_10;
    QLabel *lbTexto_11;
    AWMultiObject *aLet_11;
    AWMultiObject *aLet_12;
    QLabel *lbTexto_12;
    QLabel *lbTexto_13;
    AWMultiObject *aLet_13;
    AWMultiObject *aLet_14;
    QLabel *lbTexto_14;
    QLabel *lbTexto_15;
    AWMultiObject *aLet_15;
    AWMultiObject *aLet_16;
    QLabel *lbTexto_16;
    AWMultiObject *aLet_17;
    QLabel *lbTexto_17;
    AWMultiObject *aLet_18;
    QLabel *lbTexto_18;
    AWMultiObject *aLet_19;
    QLabel *lbTexto_19;
    QFrame *fr_2;
    QFrame *frTitulo_5;
    QLabel *lbTitulo_5;
    QLabel *lbTexto_39;
    AWMultiObject *aLet_39;
    QLabel *lbTexto_40;
    AWMultiObject *aLet_40;
    QLabel *lbTexto_41;
    AWMultiObject *aLet_41;
    QLabel *lbTexto_42;
    AWMultiObject *aLet_42;
    AWMultiObject *aLet_43;
    QLabel *lbTexto_43;
    AWMultiObject *aLet_44;
    QLabel *lbTexto_44;
    QLabel *lbTexto_45;
    AWMultiObject *aLet_45;
    AWMultiObject *aLet_46;
    QLabel *lbTexto_46;
    AWMultiObject *aLet_47;
    QLabel *lbTexto_47;
    QLabel *lbTexto_48;
    AWMultiObject *aLet_48;
    QLabel *lbTexto_49;
    AWMultiObject *aLet_49;
    AWMultiObject *aLet_50;
    QLabel *lbTexto_50;
    QLabel *lbTexto_51;
    AWMultiObject *aLet_51;
    AWMultiObject *aLet_52;
    QLabel *lbTexto_52;
    QLabel *lbTexto_53;
    AWMultiObject *aLet_53;
    AWMultiObject *aLet_54;
    QLabel *lbTexto_54;
    AWMultiObject *aLet_55;
    QLabel *lbTexto_55;
    AWMultiObject *aLet_56;
    QLabel *lbTexto_56;
    AWMultiObject *aLet_57;
    QLabel *lbTexto_57;
    QFrame *fr_3;
    QFrame *frTitulo_8;
    QLabel *lbTitulo_8;
    QLabel *lbTexto_96;
    AWMultiObject *aLet_96;
    QLabel *lbTexto_97;
    AWMultiObject *aLet_97;
    QLabel *lbTexto_98;
    AWMultiObject *aLet_98;
    QLabel *lbTexto_99;
    AWMultiObject *aLet_99;
    AWMultiObject *aLet_100;
    QLabel *lbTexto_100;
    AWMultiObject *aLet_101;
    QLabel *lbTexto_101;
    QLabel *lbTexto_102;
    AWMultiObject *aLet_102;
    AWMultiObject *aLet_103;
    QLabel *lbTexto_103;
    AWMultiObject *aLet_104;
    QLabel *lbTexto_104;
    QLabel *lbTexto_105;
    AWMultiObject *aLet_105;
    QLabel *lbTexto_106;
    AWMultiObject *aLet_106;
    AWMultiObject *aLet_107;
    QLabel *lbTexto_107;
    QLabel *lbTexto_108;
    AWMultiObject *aLet_108;
    AWMultiObject *aLet_109;
    QLabel *lbTexto_109;
    QLabel *lbTexto_110;
    AWMultiObject *aLet_110;
    AWMultiObject *aLet_111;
    QLabel *lbTexto_111;
    AWMultiObject *aLet_112;
    QLabel *lbTexto_112;
    AWMultiObject *aLet_113;
    QLabel *lbTexto_113;
    AWMultiObject *aLet_114;
    QLabel *lbTexto_114;
    QLabel *lbTexto_115;
    AWMultiObject *aLet_115;
    AWMultiObject *aLet_116;
    QLabel *lbTexto_116;
    QLabel *lbTexto_117;
    AWMultiObject *aLet_117;
    QLabel *lbTexto_118;
    AWMultiObject *aLet_118;
    QLabel *lbTexto_119;
    AWMultiObject *aLet_119;
    AWMultiObject *aLet_120;
    QLabel *lbTexto_120;
    QLabel *lbUnit3;
    QPushButton *btnIMPPant;
    QLabel *lbApagado;
    QFrame *frTitulo_9;
    QFrame *frAux;
    QFrame *frAux_2;
    QLabel *lbAux_1;
    QLabel *lbAux_2;
    QLabel *lbValNUM;
    QLabel *lbValDES;
    QPushButton *btnEng_2;
    QPushButton *btnIMPPant_2;
    QLabel *lbUnit3_2;

    void setupUi(QWidget *F2)
    {
        if (F2->objectName().isEmpty())
            F2->setObjectName(QString::fromUtf8("F2"));
        F2->resize(1024, 662);
        F2->setMinimumSize(QSize(1024, 662));
        F2->setMaximumSize(QSize(1024, 662));
        F2->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbIMGFondo = new QLabel(F2);
        lbIMGFondo->setObjectName(QString::fromUtf8("lbIMGFondo"));
        lbIMGFondo->setGeometry(QRect(0, 0, 1024, 662));
        lbIMGFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/BackGround.png")));
        lbIMGFondo->setScaledContents(true);
        fr_1 = new QFrame(F2);
        fr_1->setObjectName(QString::fromUtf8("fr_1"));
        fr_1->setGeometry(QRect(3, 53, 341, 528));
        fr_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_1->setFrameShape(QFrame::StyledPanel);
        fr_1->setFrameShadow(QFrame::Plain);
        fr_1->setLineWidth(1);
        fr_1->setMidLineWidth(0);
        frTitulo_1 = new QFrame(fr_1);
        frTitulo_1->setObjectName(QString::fromUtf8("frTitulo_1"));
        frTitulo_1->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_1->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_1->setFrameShape(QFrame::WinPanel);
        frTitulo_1->setFrameShadow(QFrame::Raised);
        frTitulo_1->setLineWidth(2);
        frTitulo_1->setMidLineWidth(0);
        lbTitulo_1 = new QLabel(fr_1);
        lbTitulo_1->setObjectName(QString::fromUtf8("lbTitulo_1"));
        lbTitulo_1->setGeometry(QRect(88, 5, 181, 16));
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        lbTitulo_1->setFont(font);
        lbTitulo_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frTitulo_2 = new QFrame(fr_1);
        frTitulo_2->setObjectName(QString::fromUtf8("frTitulo_2"));
        frTitulo_2->setGeometry(QRect(3, 395, 333, 26));
        frTitulo_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_2->setFrameShape(QFrame::WinPanel);
        frTitulo_2->setFrameShadow(QFrame::Raised);
        frTitulo_2->setLineWidth(2);
        frTitulo_2->setMidLineWidth(0);
        lbTitulo_2 = new QLabel(fr_1);
        lbTitulo_2->setObjectName(QString::fromUtf8("lbTitulo_2"));
        lbTitulo_2->setGeometry(QRect(88, 398, 181, 16));
        lbTitulo_2->setFont(font);
        lbTitulo_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_1 = new QLabel(fr_1);
        lbTexto_1->setObjectName(QString::fromUtf8("lbTexto_1"));
        lbTexto_1->setGeometry(QRect(42, 36, 281, 16));
        QFont font1;
        font1.setPointSize(8);
        font1.setBold(true);
        font1.setWeight(75);
        lbTexto_1->setFont(font1);
        lbTexto_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_1 = new AWMultiObject(fr_1);
        aLet_1->setObjectName(QString::fromUtf8("aLet_1"));
        aLet_1->setGeometry(QRect(13, 29, 25, 31));
        aLet_1->setElementType(AWMultiObject::CIRLED);
        aLet_1->setOnColor(AWMultiObject::Grey);
        aLet_1->setOffColor(AWMultiObject::Grey);
        lbTexto_2 = new QLabel(fr_1);
        lbTexto_2->setObjectName(QString::fromUtf8("lbTexto_2"));
        lbTexto_2->setGeometry(QRect(42, 55, 281, 16));
        lbTexto_2->setFont(font1);
        lbTexto_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_2 = new AWMultiObject(fr_1);
        aLet_2->setObjectName(QString::fromUtf8("aLet_2"));
        aLet_2->setGeometry(QRect(13, 48, 25, 31));
        aLet_2->setElementType(AWMultiObject::CIRLED);
        aLet_2->setOnColor(AWMultiObject::Grey);
        aLet_2->setOffColor(AWMultiObject::Grey);
        lbTexto_3 = new QLabel(fr_1);
        lbTexto_3->setObjectName(QString::fromUtf8("lbTexto_3"));
        lbTexto_3->setGeometry(QRect(42, 74, 281, 16));
        lbTexto_3->setFont(font1);
        lbTexto_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_3 = new AWMultiObject(fr_1);
        aLet_3->setObjectName(QString::fromUtf8("aLet_3"));
        aLet_3->setGeometry(QRect(13, 68, 25, 31));
        aLet_3->setElementType(AWMultiObject::CIRLED);
        aLet_3->setOnColor(AWMultiObject::Grey);
        aLet_3->setOffColor(AWMultiObject::Grey);
        lbTexto_4 = new QLabel(fr_1);
        lbTexto_4->setObjectName(QString::fromUtf8("lbTexto_4"));
        lbTexto_4->setGeometry(QRect(42, 94, 281, 16));
        lbTexto_4->setFont(font1);
        lbTexto_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_4 = new AWMultiObject(fr_1);
        aLet_4->setObjectName(QString::fromUtf8("aLet_4"));
        aLet_4->setGeometry(QRect(13, 86, 25, 31));
        aLet_4->setElementType(AWMultiObject::CIRLED);
        aLet_4->setOnColor(AWMultiObject::Grey);
        aLet_4->setOffColor(AWMultiObject::Grey);
        aLet_5 = new AWMultiObject(fr_1);
        aLet_5->setObjectName(QString::fromUtf8("aLet_5"));
        aLet_5->setGeometry(QRect(13, 145, 25, 31));
        aLet_5->setElementType(AWMultiObject::CIRLED);
        aLet_5->setOnColor(AWMultiObject::Grey);
        aLet_5->setOffColor(AWMultiObject::Grey);
        lbTexto_5 = new QLabel(fr_1);
        lbTexto_5->setObjectName(QString::fromUtf8("lbTexto_5"));
        lbTexto_5->setGeometry(QRect(42, 152, 281, 16));
        lbTexto_5->setFont(font1);
        lbTexto_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_6 = new AWMultiObject(fr_1);
        aLet_6->setObjectName(QString::fromUtf8("aLet_6"));
        aLet_6->setGeometry(QRect(13, 165, 25, 31));
        aLet_6->setElementType(AWMultiObject::CIRLED);
        aLet_6->setOnColor(AWMultiObject::Grey);
        aLet_6->setOffColor(AWMultiObject::Grey);
        lbTexto_6 = new QLabel(fr_1);
        lbTexto_6->setObjectName(QString::fromUtf8("lbTexto_6"));
        lbTexto_6->setGeometry(QRect(42, 171, 281, 16));
        lbTexto_6->setFont(font1);
        lbTexto_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_7 = new QLabel(fr_1);
        lbTexto_7->setObjectName(QString::fromUtf8("lbTexto_7"));
        lbTexto_7->setGeometry(QRect(42, 190, 281, 16));
        lbTexto_7->setFont(font1);
        lbTexto_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_7 = new AWMultiObject(fr_1);
        aLet_7->setObjectName(QString::fromUtf8("aLet_7"));
        aLet_7->setGeometry(QRect(13, 184, 25, 31));
        aLet_7->setElementType(AWMultiObject::CIRLED);
        aLet_7->setOnColor(AWMultiObject::Grey);
        aLet_7->setOffColor(AWMultiObject::Grey);
        aLet_8 = new AWMultiObject(fr_1);
        aLet_8->setObjectName(QString::fromUtf8("aLet_8"));
        aLet_8->setGeometry(QRect(13, 204, 25, 31));
        aLet_8->setElementType(AWMultiObject::CIRLED);
        aLet_8->setOnColor(AWMultiObject::Grey);
        aLet_8->setOffColor(AWMultiObject::Grey);
        lbTexto_8 = new QLabel(fr_1);
        lbTexto_8->setObjectName(QString::fromUtf8("lbTexto_8"));
        lbTexto_8->setGeometry(QRect(42, 210, 281, 16));
        lbTexto_8->setFont(font1);
        lbTexto_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_9 = new AWMultiObject(fr_1);
        aLet_9->setObjectName(QString::fromUtf8("aLet_9"));
        aLet_9->setGeometry(QRect(13, 222, 25, 31));
        aLet_9->setElementType(AWMultiObject::CIRLED);
        aLet_9->setOnColor(AWMultiObject::Grey);
        aLet_9->setOffColor(AWMultiObject::Grey);
        lbTexto_9 = new QLabel(fr_1);
        lbTexto_9->setObjectName(QString::fromUtf8("lbTexto_9"));
        lbTexto_9->setGeometry(QRect(42, 230, 281, 16));
        lbTexto_9->setFont(font1);
        lbTexto_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_10 = new QLabel(fr_1);
        lbTexto_10->setObjectName(QString::fromUtf8("lbTexto_10"));
        lbTexto_10->setGeometry(QRect(42, 249, 281, 16));
        lbTexto_10->setFont(font1);
        lbTexto_10->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_10 = new AWMultiObject(fr_1);
        aLet_10->setObjectName(QString::fromUtf8("aLet_10"));
        aLet_10->setGeometry(QRect(13, 242, 25, 31));
        aLet_10->setElementType(AWMultiObject::CIRLED);
        aLet_10->setOnColor(AWMultiObject::Grey);
        aLet_10->setOffColor(AWMultiObject::Grey);
        lbTexto_11 = new QLabel(fr_1);
        lbTexto_11->setObjectName(QString::fromUtf8("lbTexto_11"));
        lbTexto_11->setGeometry(QRect(42, 268, 281, 16));
        lbTexto_11->setFont(font1);
        lbTexto_11->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_11 = new AWMultiObject(fr_1);
        aLet_11->setObjectName(QString::fromUtf8("aLet_11"));
        aLet_11->setGeometry(QRect(13, 260, 25, 31));
        aLet_11->setElementType(AWMultiObject::CIRLED);
        aLet_11->setOnColor(AWMultiObject::Grey);
        aLet_11->setOffColor(AWMultiObject::Grey);
        aLet_12 = new AWMultiObject(fr_1);
        aLet_12->setObjectName(QString::fromUtf8("aLet_12"));
        aLet_12->setGeometry(QRect(13, 280, 25, 31));
        aLet_12->setElementType(AWMultiObject::CIRLED);
        aLet_12->setOnColor(AWMultiObject::Grey);
        aLet_12->setOffColor(AWMultiObject::Grey);
        lbTexto_12 = new QLabel(fr_1);
        lbTexto_12->setObjectName(QString::fromUtf8("lbTexto_12"));
        lbTexto_12->setGeometry(QRect(42, 286, 281, 16));
        lbTexto_12->setFont(font1);
        lbTexto_12->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_13 = new QLabel(fr_1);
        lbTexto_13->setObjectName(QString::fromUtf8("lbTexto_13"));
        lbTexto_13->setGeometry(QRect(42, 306, 281, 16));
        lbTexto_13->setFont(font1);
        lbTexto_13->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_13 = new AWMultiObject(fr_1);
        aLet_13->setObjectName(QString::fromUtf8("aLet_13"));
        aLet_13->setGeometry(QRect(13, 300, 25, 31));
        aLet_13->setElementType(AWMultiObject::CIRLED);
        aLet_13->setOnColor(AWMultiObject::Grey);
        aLet_13->setOffColor(AWMultiObject::Grey);
        aLet_14 = new AWMultiObject(fr_1);
        aLet_14->setObjectName(QString::fromUtf8("aLet_14"));
        aLet_14->setGeometry(QRect(13, 320, 25, 31));
        aLet_14->setElementType(AWMultiObject::CIRLED);
        aLet_14->setOnColor(AWMultiObject::Grey);
        aLet_14->setOffColor(AWMultiObject::Grey);
        lbTexto_14 = new QLabel(fr_1);
        lbTexto_14->setObjectName(QString::fromUtf8("lbTexto_14"));
        lbTexto_14->setGeometry(QRect(42, 326, 281, 16));
        lbTexto_14->setFont(font1);
        lbTexto_14->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_15 = new QLabel(fr_1);
        lbTexto_15->setObjectName(QString::fromUtf8("lbTexto_15"));
        lbTexto_15->setGeometry(QRect(42, 422, 281, 16));
        lbTexto_15->setFont(font1);
        lbTexto_15->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_15 = new AWMultiObject(fr_1);
        aLet_15->setObjectName(QString::fromUtf8("aLet_15"));
        aLet_15->setGeometry(QRect(13, 415, 25, 31));
        aLet_15->setElementType(AWMultiObject::CIRLED);
        aLet_15->setOnColor(AWMultiObject::Grey);
        aLet_15->setOffColor(AWMultiObject::Grey);
        aLet_16 = new AWMultiObject(fr_1);
        aLet_16->setObjectName(QString::fromUtf8("aLet_16"));
        aLet_16->setGeometry(QRect(13, 435, 25, 31));
        aLet_16->setElementType(AWMultiObject::CIRLED);
        aLet_16->setOnColor(AWMultiObject::Grey);
        aLet_16->setOffColor(AWMultiObject::Grey);
        lbTexto_16 = new QLabel(fr_1);
        lbTexto_16->setObjectName(QString::fromUtf8("lbTexto_16"));
        lbTexto_16->setGeometry(QRect(42, 442, 281, 16));
        lbTexto_16->setFont(font1);
        lbTexto_16->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_17 = new AWMultiObject(fr_1);
        aLet_17->setObjectName(QString::fromUtf8("aLet_17"));
        aLet_17->setGeometry(QRect(13, 453, 25, 31));
        aLet_17->setElementType(AWMultiObject::CIRLED);
        aLet_17->setOnColor(AWMultiObject::Grey);
        aLet_17->setOffColor(AWMultiObject::Grey);
        lbTexto_17 = new QLabel(fr_1);
        lbTexto_17->setObjectName(QString::fromUtf8("lbTexto_17"));
        lbTexto_17->setGeometry(QRect(42, 461, 281, 16));
        lbTexto_17->setFont(font1);
        lbTexto_17->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_18 = new AWMultiObject(fr_1);
        aLet_18->setObjectName(QString::fromUtf8("aLet_18"));
        aLet_18->setGeometry(QRect(13, 473, 25, 31));
        aLet_18->setElementType(AWMultiObject::CIRLED);
        aLet_18->setOnColor(AWMultiObject::Grey);
        aLet_18->setOffColor(AWMultiObject::Grey);
        lbTexto_18 = new QLabel(fr_1);
        lbTexto_18->setObjectName(QString::fromUtf8("lbTexto_18"));
        lbTexto_18->setGeometry(QRect(42, 480, 281, 16));
        lbTexto_18->setFont(font1);
        lbTexto_18->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_19 = new AWMultiObject(fr_1);
        aLet_19->setObjectName(QString::fromUtf8("aLet_19"));
        aLet_19->setGeometry(QRect(13, 493, 25, 31));
        aLet_19->setElementType(AWMultiObject::CIRLED);
        aLet_19->setOnColor(AWMultiObject::Grey);
        aLet_19->setOffColor(AWMultiObject::Grey);
        lbTexto_19 = new QLabel(fr_1);
        lbTexto_19->setObjectName(QString::fromUtf8("lbTexto_19"));
        lbTexto_19->setGeometry(QRect(42, 500, 281, 16));
        lbTexto_19->setFont(font1);
        lbTexto_19->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_2 = new QFrame(F2);
        fr_2->setObjectName(QString::fromUtf8("fr_2"));
        fr_2->setGeometry(QRect(344, 53, 341, 528));
        fr_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_2->setFrameShape(QFrame::StyledPanel);
        fr_2->setFrameShadow(QFrame::Plain);
        fr_2->setLineWidth(1);
        fr_2->setMidLineWidth(0);
        frTitulo_5 = new QFrame(fr_2);
        frTitulo_5->setObjectName(QString::fromUtf8("frTitulo_5"));
        frTitulo_5->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_5->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_5->setFrameShape(QFrame::WinPanel);
        frTitulo_5->setFrameShadow(QFrame::Raised);
        frTitulo_5->setLineWidth(2);
        frTitulo_5->setMidLineWidth(0);
        lbTitulo_5 = new QLabel(fr_2);
        lbTitulo_5->setObjectName(QString::fromUtf8("lbTitulo_5"));
        lbTitulo_5->setGeometry(QRect(88, 5, 181, 16));
        lbTitulo_5->setFont(font);
        lbTitulo_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_39 = new QLabel(fr_2);
        lbTexto_39->setObjectName(QString::fromUtf8("lbTexto_39"));
        lbTexto_39->setGeometry(QRect(42, 36, 281, 16));
        lbTexto_39->setFont(font1);
        lbTexto_39->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_39 = new AWMultiObject(fr_2);
        aLet_39->setObjectName(QString::fromUtf8("aLet_39"));
        aLet_39->setGeometry(QRect(13, 29, 25, 31));
        aLet_39->setElementType(AWMultiObject::CIRLED);
        aLet_39->setOnColor(AWMultiObject::Grey);
        aLet_39->setOffColor(AWMultiObject::Grey);
        lbTexto_40 = new QLabel(fr_2);
        lbTexto_40->setObjectName(QString::fromUtf8("lbTexto_40"));
        lbTexto_40->setGeometry(QRect(42, 55, 281, 16));
        lbTexto_40->setFont(font1);
        lbTexto_40->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_40 = new AWMultiObject(fr_2);
        aLet_40->setObjectName(QString::fromUtf8("aLet_40"));
        aLet_40->setGeometry(QRect(13, 48, 25, 31));
        aLet_40->setElementType(AWMultiObject::CIRLED);
        aLet_40->setOnColor(AWMultiObject::Grey);
        aLet_40->setOffColor(AWMultiObject::Grey);
        lbTexto_41 = new QLabel(fr_2);
        lbTexto_41->setObjectName(QString::fromUtf8("lbTexto_41"));
        lbTexto_41->setGeometry(QRect(42, 74, 281, 16));
        lbTexto_41->setFont(font1);
        lbTexto_41->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_41 = new AWMultiObject(fr_2);
        aLet_41->setObjectName(QString::fromUtf8("aLet_41"));
        aLet_41->setGeometry(QRect(13, 68, 25, 31));
        aLet_41->setElementType(AWMultiObject::CIRLED);
        aLet_41->setOnColor(AWMultiObject::Grey);
        aLet_41->setOffColor(AWMultiObject::Grey);
        lbTexto_42 = new QLabel(fr_2);
        lbTexto_42->setObjectName(QString::fromUtf8("lbTexto_42"));
        lbTexto_42->setGeometry(QRect(42, 94, 281, 16));
        lbTexto_42->setFont(font1);
        lbTexto_42->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_42 = new AWMultiObject(fr_2);
        aLet_42->setObjectName(QString::fromUtf8("aLet_42"));
        aLet_42->setGeometry(QRect(13, 86, 25, 31));
        aLet_42->setElementType(AWMultiObject::CIRLED);
        aLet_42->setOnColor(AWMultiObject::Grey);
        aLet_42->setOffColor(AWMultiObject::Grey);
        aLet_43 = new AWMultiObject(fr_2);
        aLet_43->setObjectName(QString::fromUtf8("aLet_43"));
        aLet_43->setGeometry(QRect(13, 106, 25, 31));
        aLet_43->setElementType(AWMultiObject::CIRLED);
        aLet_43->setOnColor(AWMultiObject::Grey);
        aLet_43->setOffColor(AWMultiObject::Grey);
        lbTexto_43 = new QLabel(fr_2);
        lbTexto_43->setObjectName(QString::fromUtf8("lbTexto_43"));
        lbTexto_43->setGeometry(QRect(42, 113, 281, 16));
        lbTexto_43->setFont(font1);
        lbTexto_43->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_44 = new AWMultiObject(fr_2);
        aLet_44->setObjectName(QString::fromUtf8("aLet_44"));
        aLet_44->setGeometry(QRect(13, 126, 25, 31));
        aLet_44->setElementType(AWMultiObject::CIRLED);
        aLet_44->setOnColor(AWMultiObject::Grey);
        aLet_44->setOffColor(AWMultiObject::Grey);
        lbTexto_44 = new QLabel(fr_2);
        lbTexto_44->setObjectName(QString::fromUtf8("lbTexto_44"));
        lbTexto_44->setGeometry(QRect(42, 133, 281, 16));
        lbTexto_44->setFont(font1);
        lbTexto_44->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_45 = new QLabel(fr_2);
        lbTexto_45->setObjectName(QString::fromUtf8("lbTexto_45"));
        lbTexto_45->setGeometry(QRect(42, 152, 281, 16));
        lbTexto_45->setFont(font1);
        lbTexto_45->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_45 = new AWMultiObject(fr_2);
        aLet_45->setObjectName(QString::fromUtf8("aLet_45"));
        aLet_45->setGeometry(QRect(13, 145, 25, 31));
        aLet_45->setElementType(AWMultiObject::CIRLED);
        aLet_45->setOnColor(AWMultiObject::Grey);
        aLet_45->setOffColor(AWMultiObject::Grey);
        aLet_46 = new AWMultiObject(fr_2);
        aLet_46->setObjectName(QString::fromUtf8("aLet_46"));
        aLet_46->setGeometry(QRect(13, 165, 25, 31));
        aLet_46->setElementType(AWMultiObject::CIRLED);
        aLet_46->setOnColor(AWMultiObject::Grey);
        aLet_46->setOffColor(AWMultiObject::Grey);
        lbTexto_46 = new QLabel(fr_2);
        lbTexto_46->setObjectName(QString::fromUtf8("lbTexto_46"));
        lbTexto_46->setGeometry(QRect(42, 171, 281, 16));
        lbTexto_46->setFont(font1);
        lbTexto_46->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_47 = new AWMultiObject(fr_2);
        aLet_47->setObjectName(QString::fromUtf8("aLet_47"));
        aLet_47->setGeometry(QRect(13, 183, 25, 31));
        aLet_47->setElementType(AWMultiObject::CIRLED);
        aLet_47->setOnColor(AWMultiObject::Grey);
        aLet_47->setOffColor(AWMultiObject::Grey);
        lbTexto_47 = new QLabel(fr_2);
        lbTexto_47->setObjectName(QString::fromUtf8("lbTexto_47"));
        lbTexto_47->setGeometry(QRect(42, 190, 281, 16));
        lbTexto_47->setFont(font1);
        lbTexto_47->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_48 = new QLabel(fr_2);
        lbTexto_48->setObjectName(QString::fromUtf8("lbTexto_48"));
        lbTexto_48->setGeometry(QRect(42, 210, 281, 16));
        lbTexto_48->setFont(font1);
        lbTexto_48->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_48 = new AWMultiObject(fr_2);
        aLet_48->setObjectName(QString::fromUtf8("aLet_48"));
        aLet_48->setGeometry(QRect(13, 205, 25, 31));
        aLet_48->setElementType(AWMultiObject::CIRLED);
        aLet_48->setOnColor(AWMultiObject::Grey);
        aLet_48->setOffColor(AWMultiObject::Grey);
        lbTexto_49 = new QLabel(fr_2);
        lbTexto_49->setObjectName(QString::fromUtf8("lbTexto_49"));
        lbTexto_49->setGeometry(QRect(42, 230, 281, 16));
        lbTexto_49->setFont(font1);
        lbTexto_49->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_49 = new AWMultiObject(fr_2);
        aLet_49->setObjectName(QString::fromUtf8("aLet_49"));
        aLet_49->setGeometry(QRect(13, 223, 25, 31));
        aLet_49->setElementType(AWMultiObject::CIRLED);
        aLet_49->setOnColor(AWMultiObject::Grey);
        aLet_49->setOffColor(AWMultiObject::Grey);
        aLet_50 = new AWMultiObject(fr_2);
        aLet_50->setObjectName(QString::fromUtf8("aLet_50"));
        aLet_50->setGeometry(QRect(13, 241, 25, 31));
        aLet_50->setElementType(AWMultiObject::CIRLED);
        aLet_50->setOnColor(AWMultiObject::Grey);
        aLet_50->setOffColor(AWMultiObject::Grey);
        lbTexto_50 = new QLabel(fr_2);
        lbTexto_50->setObjectName(QString::fromUtf8("lbTexto_50"));
        lbTexto_50->setGeometry(QRect(42, 250, 281, 16));
        lbTexto_50->setFont(font1);
        lbTexto_50->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_51 = new QLabel(fr_2);
        lbTexto_51->setObjectName(QString::fromUtf8("lbTexto_51"));
        lbTexto_51->setGeometry(QRect(42, 268, 281, 16));
        lbTexto_51->setFont(font1);
        lbTexto_51->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_51 = new AWMultiObject(fr_2);
        aLet_51->setObjectName(QString::fromUtf8("aLet_51"));
        aLet_51->setGeometry(QRect(13, 260, 25, 31));
        aLet_51->setElementType(AWMultiObject::CIRLED);
        aLet_51->setOnColor(AWMultiObject::Grey);
        aLet_51->setOffColor(AWMultiObject::Grey);
        aLet_52 = new AWMultiObject(fr_2);
        aLet_52->setObjectName(QString::fromUtf8("aLet_52"));
        aLet_52->setGeometry(QRect(13, 280, 25, 31));
        aLet_52->setElementType(AWMultiObject::CIRLED);
        aLet_52->setOnColor(AWMultiObject::Grey);
        aLet_52->setOffColor(AWMultiObject::Grey);
        lbTexto_52 = new QLabel(fr_2);
        lbTexto_52->setObjectName(QString::fromUtf8("lbTexto_52"));
        lbTexto_52->setGeometry(QRect(42, 286, 281, 16));
        lbTexto_52->setFont(font1);
        lbTexto_52->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_53 = new QLabel(fr_2);
        lbTexto_53->setObjectName(QString::fromUtf8("lbTexto_53"));
        lbTexto_53->setGeometry(QRect(42, 306, 281, 16));
        lbTexto_53->setFont(font1);
        lbTexto_53->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_53 = new AWMultiObject(fr_2);
        aLet_53->setObjectName(QString::fromUtf8("aLet_53"));
        aLet_53->setGeometry(QRect(13, 300, 25, 31));
        aLet_53->setElementType(AWMultiObject::CIRLED);
        aLet_53->setOnColor(AWMultiObject::Grey);
        aLet_53->setOffColor(AWMultiObject::Grey);
        aLet_54 = new AWMultiObject(fr_2);
        aLet_54->setObjectName(QString::fromUtf8("aLet_54"));
        aLet_54->setGeometry(QRect(13, 320, 25, 31));
        aLet_54->setElementType(AWMultiObject::CIRLED);
        aLet_54->setOnColor(AWMultiObject::Grey);
        aLet_54->setOffColor(AWMultiObject::Grey);
        lbTexto_54 = new QLabel(fr_2);
        lbTexto_54->setObjectName(QString::fromUtf8("lbTexto_54"));
        lbTexto_54->setGeometry(QRect(42, 325, 281, 16));
        lbTexto_54->setFont(font1);
        lbTexto_54->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_55 = new AWMultiObject(fr_2);
        aLet_55->setObjectName(QString::fromUtf8("aLet_55"));
        aLet_55->setGeometry(QRect(13, 338, 25, 31));
        aLet_55->setElementType(AWMultiObject::CIRLED);
        aLet_55->setOnColor(AWMultiObject::Grey);
        aLet_55->setOffColor(AWMultiObject::Grey);
        lbTexto_55 = new QLabel(fr_2);
        lbTexto_55->setObjectName(QString::fromUtf8("lbTexto_55"));
        lbTexto_55->setGeometry(QRect(42, 345, 281, 16));
        lbTexto_55->setFont(font1);
        lbTexto_55->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_56 = new AWMultiObject(fr_2);
        aLet_56->setObjectName(QString::fromUtf8("aLet_56"));
        aLet_56->setGeometry(QRect(13, 356, 25, 31));
        aLet_56->setElementType(AWMultiObject::CIRLED);
        aLet_56->setOnColor(AWMultiObject::Grey);
        aLet_56->setOffColor(AWMultiObject::Grey);
        lbTexto_56 = new QLabel(fr_2);
        lbTexto_56->setObjectName(QString::fromUtf8("lbTexto_56"));
        lbTexto_56->setGeometry(QRect(42, 365, 281, 16));
        lbTexto_56->setFont(font1);
        lbTexto_56->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_57 = new AWMultiObject(fr_2);
        aLet_57->setObjectName(QString::fromUtf8("aLet_57"));
        aLet_57->setGeometry(QRect(13, 378, 25, 31));
        aLet_57->setElementType(AWMultiObject::CIRLED);
        aLet_57->setOnColor(AWMultiObject::Grey);
        aLet_57->setOffColor(AWMultiObject::Grey);
        lbTexto_57 = new QLabel(fr_2);
        lbTexto_57->setObjectName(QString::fromUtf8("lbTexto_57"));
        lbTexto_57->setGeometry(QRect(42, 383, 281, 16));
        lbTexto_57->setFont(font1);
        lbTexto_57->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_3 = new QFrame(F2);
        fr_3->setObjectName(QString::fromUtf8("fr_3"));
        fr_3->setGeometry(QRect(685, 53, 337, 528));
        fr_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_3->setFrameShape(QFrame::StyledPanel);
        fr_3->setFrameShadow(QFrame::Plain);
        fr_3->setLineWidth(1);
        fr_3->setMidLineWidth(0);
        frTitulo_8 = new QFrame(fr_3);
        frTitulo_8->setObjectName(QString::fromUtf8("frTitulo_8"));
        frTitulo_8->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_8->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_8->setFrameShape(QFrame::WinPanel);
        frTitulo_8->setFrameShadow(QFrame::Raised);
        frTitulo_8->setLineWidth(2);
        frTitulo_8->setMidLineWidth(0);
        lbTitulo_8 = new QLabel(fr_3);
        lbTitulo_8->setObjectName(QString::fromUtf8("lbTitulo_8"));
        lbTitulo_8->setGeometry(QRect(88, 5, 181, 16));
        lbTitulo_8->setFont(font);
        lbTitulo_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_96 = new QLabel(fr_3);
        lbTexto_96->setObjectName(QString::fromUtf8("lbTexto_96"));
        lbTexto_96->setGeometry(QRect(42, 36, 281, 16));
        lbTexto_96->setFont(font1);
        lbTexto_96->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_96 = new AWMultiObject(fr_3);
        aLet_96->setObjectName(QString::fromUtf8("aLet_96"));
        aLet_96->setGeometry(QRect(13, 29, 25, 31));
        aLet_96->setElementType(AWMultiObject::CIRLED);
        aLet_96->setOnColor(AWMultiObject::Grey);
        aLet_96->setOffColor(AWMultiObject::Grey);
        lbTexto_97 = new QLabel(fr_3);
        lbTexto_97->setObjectName(QString::fromUtf8("lbTexto_97"));
        lbTexto_97->setGeometry(QRect(42, 55, 281, 16));
        lbTexto_97->setFont(font1);
        lbTexto_97->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_97 = new AWMultiObject(fr_3);
        aLet_97->setObjectName(QString::fromUtf8("aLet_97"));
        aLet_97->setGeometry(QRect(13, 48, 25, 31));
        aLet_97->setElementType(AWMultiObject::CIRLED);
        aLet_97->setOnColor(AWMultiObject::Grey);
        aLet_97->setOffColor(AWMultiObject::Grey);
        lbTexto_98 = new QLabel(fr_3);
        lbTexto_98->setObjectName(QString::fromUtf8("lbTexto_98"));
        lbTexto_98->setGeometry(QRect(42, 74, 281, 16));
        lbTexto_98->setFont(font1);
        lbTexto_98->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_98 = new AWMultiObject(fr_3);
        aLet_98->setObjectName(QString::fromUtf8("aLet_98"));
        aLet_98->setGeometry(QRect(13, 68, 25, 31));
        aLet_98->setElementType(AWMultiObject::CIRLED);
        aLet_98->setOnColor(AWMultiObject::Grey);
        aLet_98->setOffColor(AWMultiObject::Grey);
        lbTexto_99 = new QLabel(fr_3);
        lbTexto_99->setObjectName(QString::fromUtf8("lbTexto_99"));
        lbTexto_99->setGeometry(QRect(42, 94, 281, 16));
        lbTexto_99->setFont(font1);
        lbTexto_99->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_99 = new AWMultiObject(fr_3);
        aLet_99->setObjectName(QString::fromUtf8("aLet_99"));
        aLet_99->setGeometry(QRect(13, 86, 25, 31));
        aLet_99->setElementType(AWMultiObject::CIRLED);
        aLet_99->setOnColor(AWMultiObject::Grey);
        aLet_99->setOffColor(AWMultiObject::Grey);
        aLet_100 = new AWMultiObject(fr_3);
        aLet_100->setObjectName(QString::fromUtf8("aLet_100"));
        aLet_100->setGeometry(QRect(13, 106, 25, 31));
        aLet_100->setElementType(AWMultiObject::CIRLED);
        aLet_100->setOnColor(AWMultiObject::Grey);
        aLet_100->setOffColor(AWMultiObject::Grey);
        lbTexto_100 = new QLabel(fr_3);
        lbTexto_100->setObjectName(QString::fromUtf8("lbTexto_100"));
        lbTexto_100->setGeometry(QRect(42, 113, 281, 16));
        lbTexto_100->setFont(font1);
        lbTexto_100->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_101 = new AWMultiObject(fr_3);
        aLet_101->setObjectName(QString::fromUtf8("aLet_101"));
        aLet_101->setGeometry(QRect(13, 126, 25, 31));
        aLet_101->setElementType(AWMultiObject::CIRLED);
        aLet_101->setOnColor(AWMultiObject::Grey);
        aLet_101->setOffColor(AWMultiObject::Grey);
        lbTexto_101 = new QLabel(fr_3);
        lbTexto_101->setObjectName(QString::fromUtf8("lbTexto_101"));
        lbTexto_101->setGeometry(QRect(42, 133, 281, 16));
        lbTexto_101->setFont(font1);
        lbTexto_101->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_102 = new QLabel(fr_3);
        lbTexto_102->setObjectName(QString::fromUtf8("lbTexto_102"));
        lbTexto_102->setGeometry(QRect(42, 152, 281, 16));
        lbTexto_102->setFont(font1);
        lbTexto_102->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_102 = new AWMultiObject(fr_3);
        aLet_102->setObjectName(QString::fromUtf8("aLet_102"));
        aLet_102->setGeometry(QRect(13, 145, 25, 31));
        aLet_102->setElementType(AWMultiObject::CIRLED);
        aLet_102->setOnColor(AWMultiObject::Grey);
        aLet_102->setOffColor(AWMultiObject::Grey);
        aLet_103 = new AWMultiObject(fr_3);
        aLet_103->setObjectName(QString::fromUtf8("aLet_103"));
        aLet_103->setGeometry(QRect(13, 165, 25, 31));
        aLet_103->setElementType(AWMultiObject::CIRLED);
        aLet_103->setOnColor(AWMultiObject::Grey);
        aLet_103->setOffColor(AWMultiObject::Grey);
        lbTexto_103 = new QLabel(fr_3);
        lbTexto_103->setObjectName(QString::fromUtf8("lbTexto_103"));
        lbTexto_103->setGeometry(QRect(42, 171, 281, 16));
        lbTexto_103->setFont(font1);
        lbTexto_103->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_104 = new AWMultiObject(fr_3);
        aLet_104->setObjectName(QString::fromUtf8("aLet_104"));
        aLet_104->setGeometry(QRect(13, 183, 25, 31));
        aLet_104->setElementType(AWMultiObject::CIRLED);
        aLet_104->setOnColor(AWMultiObject::Grey);
        aLet_104->setOffColor(AWMultiObject::Grey);
        lbTexto_104 = new QLabel(fr_3);
        lbTexto_104->setObjectName(QString::fromUtf8("lbTexto_104"));
        lbTexto_104->setGeometry(QRect(42, 190, 281, 16));
        lbTexto_104->setFont(font1);
        lbTexto_104->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_105 = new QLabel(fr_3);
        lbTexto_105->setObjectName(QString::fromUtf8("lbTexto_105"));
        lbTexto_105->setGeometry(QRect(42, 210, 281, 16));
        lbTexto_105->setFont(font1);
        lbTexto_105->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_105 = new AWMultiObject(fr_3);
        aLet_105->setObjectName(QString::fromUtf8("aLet_105"));
        aLet_105->setGeometry(QRect(13, 205, 25, 31));
        aLet_105->setElementType(AWMultiObject::CIRLED);
        aLet_105->setOnColor(AWMultiObject::Grey);
        aLet_105->setOffColor(AWMultiObject::Grey);
        lbTexto_106 = new QLabel(fr_3);
        lbTexto_106->setObjectName(QString::fromUtf8("lbTexto_106"));
        lbTexto_106->setGeometry(QRect(42, 230, 281, 16));
        lbTexto_106->setFont(font1);
        lbTexto_106->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_106 = new AWMultiObject(fr_3);
        aLet_106->setObjectName(QString::fromUtf8("aLet_106"));
        aLet_106->setGeometry(QRect(13, 223, 25, 31));
        aLet_106->setElementType(AWMultiObject::CIRLED);
        aLet_106->setOnColor(AWMultiObject::Grey);
        aLet_106->setOffColor(AWMultiObject::Grey);
        aLet_107 = new AWMultiObject(fr_3);
        aLet_107->setObjectName(QString::fromUtf8("aLet_107"));
        aLet_107->setGeometry(QRect(13, 241, 25, 31));
        aLet_107->setElementType(AWMultiObject::CIRLED);
        aLet_107->setOnColor(AWMultiObject::Grey);
        aLet_107->setOffColor(AWMultiObject::Grey);
        lbTexto_107 = new QLabel(fr_3);
        lbTexto_107->setObjectName(QString::fromUtf8("lbTexto_107"));
        lbTexto_107->setGeometry(QRect(42, 250, 281, 16));
        lbTexto_107->setFont(font1);
        lbTexto_107->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_108 = new QLabel(fr_3);
        lbTexto_108->setObjectName(QString::fromUtf8("lbTexto_108"));
        lbTexto_108->setGeometry(QRect(42, 268, 281, 16));
        lbTexto_108->setFont(font1);
        lbTexto_108->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_108 = new AWMultiObject(fr_3);
        aLet_108->setObjectName(QString::fromUtf8("aLet_108"));
        aLet_108->setGeometry(QRect(13, 260, 25, 31));
        aLet_108->setElementType(AWMultiObject::CIRLED);
        aLet_108->setOnColor(AWMultiObject::Grey);
        aLet_108->setOffColor(AWMultiObject::Grey);
        aLet_109 = new AWMultiObject(fr_3);
        aLet_109->setObjectName(QString::fromUtf8("aLet_109"));
        aLet_109->setGeometry(QRect(13, 280, 25, 31));
        aLet_109->setElementType(AWMultiObject::CIRLED);
        aLet_109->setOnColor(AWMultiObject::Grey);
        aLet_109->setOffColor(AWMultiObject::Grey);
        lbTexto_109 = new QLabel(fr_3);
        lbTexto_109->setObjectName(QString::fromUtf8("lbTexto_109"));
        lbTexto_109->setGeometry(QRect(42, 286, 281, 16));
        lbTexto_109->setFont(font1);
        lbTexto_109->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_110 = new QLabel(fr_3);
        lbTexto_110->setObjectName(QString::fromUtf8("lbTexto_110"));
        lbTexto_110->setGeometry(QRect(42, 306, 281, 16));
        lbTexto_110->setFont(font1);
        lbTexto_110->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_110 = new AWMultiObject(fr_3);
        aLet_110->setObjectName(QString::fromUtf8("aLet_110"));
        aLet_110->setGeometry(QRect(13, 300, 25, 31));
        aLet_110->setElementType(AWMultiObject::CIRLED);
        aLet_110->setOnColor(AWMultiObject::Grey);
        aLet_110->setOffColor(AWMultiObject::Grey);
        aLet_111 = new AWMultiObject(fr_3);
        aLet_111->setObjectName(QString::fromUtf8("aLet_111"));
        aLet_111->setGeometry(QRect(13, 320, 25, 31));
        aLet_111->setElementType(AWMultiObject::CIRLED);
        aLet_111->setOnColor(AWMultiObject::Grey);
        aLet_111->setOffColor(AWMultiObject::Grey);
        lbTexto_111 = new QLabel(fr_3);
        lbTexto_111->setObjectName(QString::fromUtf8("lbTexto_111"));
        lbTexto_111->setGeometry(QRect(42, 325, 281, 16));
        lbTexto_111->setFont(font1);
        lbTexto_111->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_112 = new AWMultiObject(fr_3);
        aLet_112->setObjectName(QString::fromUtf8("aLet_112"));
        aLet_112->setGeometry(QRect(13, 338, 25, 31));
        aLet_112->setElementType(AWMultiObject::CIRLED);
        aLet_112->setOnColor(AWMultiObject::Grey);
        aLet_112->setOffColor(AWMultiObject::Grey);
        lbTexto_112 = new QLabel(fr_3);
        lbTexto_112->setObjectName(QString::fromUtf8("lbTexto_112"));
        lbTexto_112->setGeometry(QRect(42, 345, 281, 16));
        lbTexto_112->setFont(font1);
        lbTexto_112->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_113 = new AWMultiObject(fr_3);
        aLet_113->setObjectName(QString::fromUtf8("aLet_113"));
        aLet_113->setGeometry(QRect(13, 356, 25, 31));
        aLet_113->setElementType(AWMultiObject::CIRLED);
        aLet_113->setOnColor(AWMultiObject::Grey);
        aLet_113->setOffColor(AWMultiObject::Grey);
        lbTexto_113 = new QLabel(fr_3);
        lbTexto_113->setObjectName(QString::fromUtf8("lbTexto_113"));
        lbTexto_113->setGeometry(QRect(42, 365, 281, 16));
        lbTexto_113->setFont(font1);
        lbTexto_113->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_114 = new AWMultiObject(fr_3);
        aLet_114->setObjectName(QString::fromUtf8("aLet_114"));
        aLet_114->setGeometry(QRect(13, 378, 25, 31));
        aLet_114->setElementType(AWMultiObject::CIRLED);
        aLet_114->setOnColor(AWMultiObject::Grey);
        aLet_114->setOffColor(AWMultiObject::Grey);
        lbTexto_114 = new QLabel(fr_3);
        lbTexto_114->setObjectName(QString::fromUtf8("lbTexto_114"));
        lbTexto_114->setGeometry(QRect(42, 383, 281, 16));
        lbTexto_114->setFont(font1);
        lbTexto_114->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_115 = new QLabel(fr_3);
        lbTexto_115->setObjectName(QString::fromUtf8("lbTexto_115"));
        lbTexto_115->setGeometry(QRect(42, 403, 281, 16));
        lbTexto_115->setFont(font1);
        lbTexto_115->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_115 = new AWMultiObject(fr_3);
        aLet_115->setObjectName(QString::fromUtf8("aLet_115"));
        aLet_115->setGeometry(QRect(13, 395, 25, 31));
        aLet_115->setElementType(AWMultiObject::CIRLED);
        aLet_115->setOnColor(AWMultiObject::Grey);
        aLet_115->setOffColor(AWMultiObject::Grey);
        aLet_116 = new AWMultiObject(fr_3);
        aLet_116->setObjectName(QString::fromUtf8("aLet_116"));
        aLet_116->setGeometry(QRect(13, 416, 25, 31));
        aLet_116->setElementType(AWMultiObject::CIRLED);
        aLet_116->setOnColor(AWMultiObject::Grey);
        aLet_116->setOffColor(AWMultiObject::Grey);
        lbTexto_116 = new QLabel(fr_3);
        lbTexto_116->setObjectName(QString::fromUtf8("lbTexto_116"));
        lbTexto_116->setGeometry(QRect(42, 423, 281, 16));
        lbTexto_116->setFont(font1);
        lbTexto_116->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_117 = new QLabel(fr_3);
        lbTexto_117->setObjectName(QString::fromUtf8("lbTexto_117"));
        lbTexto_117->setGeometry(QRect(42, 442, 281, 16));
        lbTexto_117->setFont(font1);
        lbTexto_117->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_117 = new AWMultiObject(fr_3);
        aLet_117->setObjectName(QString::fromUtf8("aLet_117"));
        aLet_117->setGeometry(QRect(13, 435, 25, 31));
        aLet_117->setElementType(AWMultiObject::CIRLED);
        aLet_117->setOnColor(AWMultiObject::Grey);
        aLet_117->setOffColor(AWMultiObject::Grey);
        lbTexto_118 = new QLabel(fr_3);
        lbTexto_118->setObjectName(QString::fromUtf8("lbTexto_118"));
        lbTexto_118->setGeometry(QRect(42, 460, 281, 16));
        lbTexto_118->setFont(font1);
        lbTexto_118->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_118 = new AWMultiObject(fr_3);
        aLet_118->setObjectName(QString::fromUtf8("aLet_118"));
        aLet_118->setGeometry(QRect(13, 455, 25, 31));
        aLet_118->setElementType(AWMultiObject::CIRLED);
        aLet_118->setOnColor(AWMultiObject::Grey);
        aLet_118->setOffColor(AWMultiObject::Grey);
        lbTexto_119 = new QLabel(fr_3);
        lbTexto_119->setObjectName(QString::fromUtf8("lbTexto_119"));
        lbTexto_119->setGeometry(QRect(42, 480, 281, 16));
        lbTexto_119->setFont(font1);
        lbTexto_119->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_119 = new AWMultiObject(fr_3);
        aLet_119->setObjectName(QString::fromUtf8("aLet_119"));
        aLet_119->setGeometry(QRect(13, 473, 25, 31));
        aLet_119->setElementType(AWMultiObject::CIRLED);
        aLet_119->setOnColor(AWMultiObject::Grey);
        aLet_119->setOffColor(AWMultiObject::Grey);
        aLet_120 = new AWMultiObject(fr_3);
        aLet_120->setObjectName(QString::fromUtf8("aLet_120"));
        aLet_120->setGeometry(QRect(13, 493, 25, 31));
        aLet_120->setElementType(AWMultiObject::CIRLED);
        aLet_120->setOnColor(AWMultiObject::Grey);
        aLet_120->setOffColor(AWMultiObject::Grey);
        lbTexto_120 = new QLabel(fr_3);
        lbTexto_120->setObjectName(QString::fromUtf8("lbTexto_120"));
        lbTexto_120->setGeometry(QRect(42, 500, 281, 16));
        lbTexto_120->setFont(font1);
        lbTexto_120->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbUnit3 = new QLabel(F2);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(835, 647, 190, 15));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        lbUnit3->setFont(font2);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        btnIMPPant = new QPushButton(F2);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(4, 640, 134, 21));
        btnIMPPant->setFont(font1);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbApagado = new QLabel(F2);
        lbApagado->setObjectName(QString::fromUtf8("lbApagado"));
        lbApagado->setGeometry(QRect(140, 585, 111, 71));
        lbApagado->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frTitulo_9 = new QFrame(F2);
        frTitulo_9->setObjectName(QString::fromUtf8("frTitulo_9"));
        frTitulo_9->setGeometry(QRect(310, 590, 561, 54));
        frTitulo_9->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_9->setFrameShape(QFrame::WinPanel);
        frTitulo_9->setFrameShadow(QFrame::Raised);
        frTitulo_9->setLineWidth(2);
        frTitulo_9->setMidLineWidth(0);
        frAux = new QFrame(F2);
        frAux->setObjectName(QString::fromUtf8("frAux"));
        frAux->setGeometry(QRect(318, 615, 63, 24));
        frAux->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux->setFrameShape(QFrame::WinPanel);
        frAux->setFrameShadow(QFrame::Sunken);
        frAux_2 = new QFrame(F2);
        frAux_2->setObjectName(QString::fromUtf8("frAux_2"));
        frAux_2->setGeometry(QRect(390, 615, 466, 24));
        frAux_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux_2->setFrameShape(QFrame::WinPanel);
        frAux_2->setFrameShadow(QFrame::Sunken);
        lbAux_1 = new QLabel(F2);
        lbAux_1->setObjectName(QString::fromUtf8("lbAux_1"));
        lbAux_1->setGeometry(QRect(334, 597, 46, 16));
        QFont font3;
        font3.setPointSize(12);
        font3.setBold(true);
        font3.setWeight(75);
        lbAux_1->setFont(font3);
        lbAux_1->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbAux_2 = new QLabel(F2);
        lbAux_2->setObjectName(QString::fromUtf8("lbAux_2"));
        lbAux_2->setGeometry(QRect(421, 597, 101, 16));
        lbAux_2->setFont(font3);
        lbAux_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbValNUM = new QLabel(F2);
        lbValNUM->setObjectName(QString::fromUtf8("lbValNUM"));
        lbValNUM->setGeometry(QRect(340, 620, 35, 16));
        QFont font4;
        font4.setPointSize(11);
        font4.setBold(true);
        font4.setWeight(75);
        lbValNUM->setFont(font4);
        lbValNUM->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbValDES = new QLabel(F2);
        lbValDES->setObjectName(QString::fromUtf8("lbValDES"));
        lbValDES->setGeometry(QRect(400, 620, 151, 16));
        lbValDES->setFont(font4);
        lbValDES->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        btnEng_2 = new QPushButton(F2);
        btnEng_2->setObjectName(QString::fromUtf8("btnEng_2"));
        btnEng_2->setGeometry(QRect(1014, 661, 113, 21));
        btnEng_2->setFont(font1);
        btnIMPPant_2 = new QPushButton(F2);
        btnIMPPant_2->setObjectName(QString::fromUtf8("btnIMPPant_2"));
        btnIMPPant_2->setGeometry(QRect(110, 675, 134, 21));
        btnIMPPant_2->setFont(font1);
        lbUnit3_2 = new QLabel(F2);
        lbUnit3_2->setObjectName(QString::fromUtf8("lbUnit3_2"));
        lbUnit3_2->setGeometry(QRect(941, 682, 190, 15));
        lbUnit3_2->setFont(font2);
        lbUnit3_2->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        lbIMGFondo->raise();
        frTitulo_9->raise();
        frAux_2->raise();
        frAux->raise();
        fr_1->raise();
        fr_2->raise();
        fr_3->raise();
        lbUnit3->raise();
        btnIMPPant->raise();
        lbApagado->raise();
        lbAux_1->raise();
        lbAux_2->raise();
        lbValNUM->raise();
        lbValDES->raise();
        btnEng_2->raise();
        btnIMPPant_2->raise();
        lbUnit3_2->raise();

        retranslateUi(F2);

        QMetaObject::connectSlotsByName(F2);
    } // setupUi

    void retranslateUi(QWidget *F2)
    {
        F2->setWindowTitle(QApplication::translate("F2", "Form", 0, QApplication::UnicodeUTF8));
        lbIMGFondo->setText(QString());
        lbTitulo_1->setText(QApplication::translate("F2", "DETENCIONES NORMALES", 0, QApplication::UnicodeUTF8));
        lbTitulo_2->setText(QApplication::translate("F2", "DESACEL A MIN (N\303\232CLEO)", 0, QApplication::UnicodeUTF8));
        lbTexto_1->setText(QApplication::translate("F2", "SEC:FILTRO SUMIN ACE LUB TURB ALT P/D", 0, QApplication::UnicodeUTF8));
        aLet_1->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLO001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_2->setText(QApplication::translate("F2", "SEC:FILTRO ACE RECUP TURB ALT ALT P/D", 0, QApplication::UnicodeUTF8));
        aLet_2->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLO002_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_3->setText(QApplication::translate("F2", "SEC:FILTRO ENTR AIR ALT ALT P/D", 0, QApplication::UnicodeUTF8));
        aLet_3->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLO003_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_4->setText(QApplication::translate("F2", "SEC:DM A CDLO", 0, QApplication::UnicodeUTF8));
        aLet_4->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLO004_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_5->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLO007_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_5->setText(QApplication::translate("F2", "SEC:REFACCI\303\223N CDLO", 0, QApplication::UnicodeUTF8));
        aLet_6->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLO008_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_6->setText(QApplication::translate("F2", "SEC:REFACCI\303\223N CDLO", 0, QApplication::UnicodeUTF8));
        lbTexto_7->setText(QApplication::translate("F2", "SEC:REFACCI\303\223N CDLO", 0, QApplication::UnicodeUTF8));
        aLet_7->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLO009_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_8->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLOGEN001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_8->setText(QApplication::translate("F2", "SEC:IGPS (DGP) FALLA", 0, QApplication::UnicodeUTF8));
        aLet_9->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLOGEN002_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_9->setText(QApplication::translate("F2", "SEC:ALTO NORMAL DE GCP", 0, QApplication::UnicodeUTF8));
        lbTexto_10->setText(QApplication::translate("F2", "SEC: TEMP SUMINISTRO ACEITE GEN", 0, QApplication::UnicodeUTF8));
        aLet_10->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLOGEN003_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_11->setText(QApplication::translate("F2", "SEC: GEN NIV TNQ CIER GRD ACE LUB", 0, QApplication::UnicodeUTF8));
        aLet_11->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLOGEN004_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_12->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLOGEN005_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_12->setText(QApplication::translate("F2", "SEC: LS6041 SENSOR FALL\303\223", 0, QApplication::UnicodeUTF8));
        lbTexto_13->setText(QApplication::translate("F2", "SEC: LS6042 SENSOR FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_13->setId(QApplication::translate("F2", "p_Fix32_THISNODE_CDLOGEN006_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_14->setId(QApplication::translate("F2", "p_Fix32_THISNODE_NSM001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_14->setText(QApplication::translate("F2", "SEC:ALTO NORMAL INICIADO POR OPERADOR", 0, QApplication::UnicodeUTF8));
        lbTexto_15->setText(QApplication::translate("F2", "N\303\232CLEO:L\303\223GICA SEGUNDO ANILLO", 0, QApplication::UnicodeUTF8));
        aLet_15->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE001_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_16->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE002_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_16->setText(QApplication::translate("F2", "N\303\232CLEO:T2 A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_17->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE003_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_17->setText(QApplication::translate("F2", "N\303\232CLEO:T25 A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_18->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE004_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_18->setText(QApplication::translate("F2", "N\303\232CLEO:T48 ABC SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_19->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE005_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_19->setText(QApplication::translate("F2", "N\303\232CLEO:T48 BCD SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        lbTitulo_5->setText(QApplication::translate("F2", "DESACEL A MIN (N\303\232CLEO)", 0, QApplication::UnicodeUTF8));
        lbTexto_39->setText(QApplication::translate("F2", "N\303\232CLEO:T48 CDE SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_39->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE006_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_40->setText(QApplication::translate("F2", "N\303\232CLEO:T48 DEF SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_40->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE007_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_41->setText(QApplication::translate("F2", "N\303\232CLEO:T48 EFG SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_41->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE008_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_42->setText(QApplication::translate("F2", "N\303\232CLEO:T48 FGH SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_42->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE009_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_43->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE010_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_43->setText(QApplication::translate("F2", "N\303\232CLEO:T48 GHA SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_44->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE011_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_44->setText(QApplication::translate("F2", "N\303\232CLEO:T48 HAB SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_45->setText(QApplication::translate("F2", "N\303\232CLEO:T48 4 SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_45->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE012_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_46->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE013_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_46->setText(QApplication::translate("F2", "N\303\232CLEO:P25 A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_47->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE014_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_47->setText(QApplication::translate("F2", "N\303\232CLEO:P48 SENSOR FALL\303\223", 0, QApplication::UnicodeUTF8));
        lbTexto_48->setText(QApplication::translate("F2", "N\303\232CLEO:PTB A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_48->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE015_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_49->setText(QApplication::translate("F2", "N\303\232CLEO:PTB A&B SENSORES ALTA DIF", 0, QApplication::UnicodeUTF8));
        aLet_49->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE016_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_50->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE017_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_50->setText(QApplication::translate("F2", "N\303\232CLEO:PTB DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        lbTexto_51->setText(QApplication::translate("F2", "N\303\232CLEO:PTB DEMANDA VS PROG ERR", 0, QApplication::UnicodeUTF8));
        aLet_51->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE018_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_52->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE019_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_52->setText(QApplication::translate("F2", "N\303\232CLEO:TGBA A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_53->setText(QApplication::translate("F2", "N\303\232CLEO:TGBB A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_53->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE020_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_54->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE021_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_54->setText(QApplication::translate("F2", "N\303\232CLEO:TGBC A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_55->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE022_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_55->setText(QApplication::translate("F2", "N\303\232CLEO:TGBD A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_56->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE023_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_56->setText(QApplication::translate("F2", "N\303\232CLEO:TGBE A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_57->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE024_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_57->setText(QApplication::translate("F2", "N\303\232CLEO:TGBA SOBRE TEMP", 0, QApplication::UnicodeUTF8));
        lbTitulo_8->setText(QApplication::translate("F2", "DESACEL A MIN (N\303\232CLEO)", 0, QApplication::UnicodeUTF8));
        lbTexto_96->setText(QApplication::translate("F2", "N\303\232CLEO:TLUP A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_96->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE031_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_97->setText(QApplication::translate("F2", "N\303\232CLEO:IGV CAMBIO CORRIENTE NULO", 0, QApplication::UnicodeUTF8));
        aLet_97->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE032_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_98->setText(QApplication::translate("F2", "N\303\232CLEO:VSV CAMBIO CORRIENTE NULO", 0, QApplication::UnicodeUTF8));
        aLet_98->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE033_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_99->setText(QApplication::translate("F2", "N\303\232CLEO:TBV A&B RETROALS FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_99->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE034_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_100->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE035_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_100->setText(QApplication::translate("F2", "N\303\232CLEO:TBV DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        aLet_101->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE036_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_101->setText(QApplication::translate("F2", "N\303\232CLEO:TBV IMPULSOR/CT MEDIDOR FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_102->setText(QApplication::translate("F2", "N\303\232CLEO:TBV CAMBIO CORRIENTE NULO", 0, QApplication::UnicodeUTF8));
        aLet_102->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE037_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_103->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE038_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_103->setText(QApplication::translate("F2", "N\303\232CLEO:VBV A&B RETROALMS ALTA DIF", 0, QApplication::UnicodeUTF8));
        aLet_104->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE039_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_104->setText(QApplication::translate("F2", "N\303\232CLEO:VBV A&B RETROALS FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_105->setText(QApplication::translate("F2", "N\303\232CLEO:VBV DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        aLet_105->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE040_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_106->setText(QApplication::translate("F2", "N\303\232CLEO:TBV IMPULSOR/CT MEDIDOR FALLA", 0, QApplication::UnicodeUTF8));
        aLet_106->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE041_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_107->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE042_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_107->setText(QApplication::translate("F2", "N\303\232CLEO:VBV CAMBIO CORRIENTE NULO", 0, QApplication::UnicodeUTF8));
        lbTexto_108->setText(QApplication::translate("F2", "N\303\232CLEO:CDP CAMBIO CORRIENTE NULO", 0, QApplication::UnicodeUTF8));
        aLet_108->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE043_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_109->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE044_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_109->setText(QApplication::translate("F2", "N\303\232CLEO:ST8 CAMBIO CORRIENTE NULO", 0, QApplication::UnicodeUTF8));
        lbTexto_110->setText(QApplication::translate("F2", "N\303\232CLEO:ALTA TEMP GAS", 0, QApplication::UnicodeUTF8));
        aLet_110->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE045_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_111->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE046_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_111->setText(QApplication::translate("F2", "N\303\232CLEO:TEMP PILOT ALTA MODO AB", 0, QApplication::UnicodeUTF8));
        aLet_112->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE047_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_112->setText(QApplication::translate("F2", "N\303\232CLEO:TEMP PILOT ALTA MODO ABC", 0, QApplication::UnicodeUTF8));
        aLet_113->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE048_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_113->setText(QApplication::translate("F2", "N\303\232CLEO:T48 DESACEL DIFERENCL ALTA", 0, QApplication::UnicodeUTF8));
        aLet_114->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE049_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_114->setText(QApplication::translate("F2", "N\303\232CLEO:DM_N\303\232CLEO REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_115->setText(QApplication::translate("F2", "N\303\232CLEO:DM_N\303\232CLEO REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_115->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_CORE050_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_116->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_FMS001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_116->setText(QApplication::translate("F2", "N\303\232CLEO:PRES SUMIN GAS BAJA", 0, QApplication::UnicodeUTF8));
        lbTexto_117->setText(QApplication::translate("F2", "N\303\232CLEO:DM_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_117->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_FMS002_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_118->setText(QApplication::translate("F2", "N\303\232CLEO:DM_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_118->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_FMS003_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_119->setText(QApplication::translate("F2", "N\303\232CLEO:DM_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_119->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_FMS004_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_120->setId(QApplication::translate("F2", "p_Fix32_THISNODE_DM_FMS005_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_120->setText(QApplication::translate("F2", "N\303\232CLEO:DM_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("F2", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("F2", "IMP PANT", 0, QApplication::UnicodeUTF8));
        lbApagado->setText(QApplication::translate("F2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">PRIMER</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">APAGADO</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbAux_1->setText(QApplication::translate("F2", "N\302\272", 0, QApplication::UnicodeUTF8));
        lbAux_2->setText(QApplication::translate("F2", "Descripci\303\263n", 0, QApplication::UnicodeUTF8));
        lbValNUM->setText(QApplication::translate("F2", "0", 0, QApplication::UnicodeUTF8));
        lbValDES->setText(QApplication::translate("F2", "SIN APAGADOS", 0, QApplication::UnicodeUTF8));
        btnEng_2->setText(QApplication::translate("F2", "ENGLISH", 0, QApplication::UnicodeUTF8));
        btnIMPPant_2->setText(QApplication::translate("F2", "IMP PANT", 0, QApplication::UnicodeUTF8));
        lbUnit3_2->setText(QApplication::translate("F2", "    UNIT3", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class F2: public Ui_F2 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_F2_H
