/********************************************************************************
** Form generated from reading UI file 'f3.ui'
**
** Created: Mon 9. Dec 18:08:33 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_F3_H
#define UI_F3_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "awmultiobject.h"

QT_BEGIN_NAMESPACE

class Ui_F3
{
public:
    QLabel *lbIMGFondo;
    QFrame *fr_1;
    QFrame *frTitulo_1;
    QLabel *lbTitulo_1;
    QLabel *lbTexto_1;
    AWMultiObject *aLet_1;
    QLabel *lbTexto_2;
    AWMultiObject *aLet_2;
    QLabel *lbTexto_3;
    AWMultiObject *aLet_3;
    QLabel *lbTexto_4;
    AWMultiObject *aLet_4;
    AWMultiObject *aLet_5;
    QLabel *lbTexto_5;
    AWMultiObject *aLet_6;
    QLabel *lbTexto_6;
    QLabel *lbTexto_7;
    AWMultiObject *aLet_7;
    AWMultiObject *aLet_8;
    QLabel *lbTexto_8;
    AWMultiObject *aLet_9;
    QLabel *lbTexto_9;
    QLabel *lbTexto_10;
    AWMultiObject *aLet_10;
    QLabel *lbTexto_11;
    AWMultiObject *aLet_11;
    AWMultiObject *aLet_12;
    QLabel *lbTexto_12;
    QLabel *lbTexto_13;
    AWMultiObject *aLet_13;
    AWMultiObject *aLet_14;
    QLabel *lbTexto_14;
    QLabel *lbTexto_15;
    AWMultiObject *aLet_15;
    AWMultiObject *aLet_16;
    QLabel *lbTexto_16;
    AWMultiObject *aLet_17;
    QLabel *lbTexto_17;
    AWMultiObject *aLet_18;
    QLabel *lbTexto_18;
    AWMultiObject *aLet_19;
    QLabel *lbTexto_19;
    QLabel *lbTexto_20;
    AWMultiObject *aLet_20;
    QFrame *fr_2;
    QFrame *frTitulo_2;
    QLabel *lbTitulo_2;
    QLabel *lbTexto_21;
    AWMultiObject *aLet_21;
    QLabel *lbTexto_22;
    AWMultiObject *aLet_22;
    QLabel *lbTexto_23;
    AWMultiObject *aLet_23;
    QLabel *lbTexto_24;
    AWMultiObject *aLet_24;
    AWMultiObject *aLet_25;
    QLabel *lbTexto_25;
    AWMultiObject *aLet_26;
    QLabel *lbTexto_26;
    QLabel *lbTexto_27;
    AWMultiObject *aLet_27;
    AWMultiObject *aLet_28;
    QLabel *lbTexto_28;
    AWMultiObject *aLet_29;
    QLabel *lbTexto_29;
    QLabel *lbTexto_30;
    AWMultiObject *aLet_30;
    QLabel *lbTexto_31;
    AWMultiObject *aLet_31;
    AWMultiObject *aLet_32;
    QLabel *lbTexto_32;
    QLabel *lbTexto_33;
    AWMultiObject *aLet_33;
    AWMultiObject *aLet_34;
    QLabel *lbTexto_34;
    QLabel *lbTexto_35;
    AWMultiObject *aLet_35;
    AWMultiObject *aLet_36;
    QLabel *lbTexto_36;
    QFrame *fr_3;
    QFrame *frTitulo_3;
    QLabel *lbTitulo_3;
    QLabel *lbTexto_37;
    AWMultiObject *aLet_37;
    QLabel *lbTexto_38;
    QLabel *lbTexto_39;
    AWMultiObject *aLet_39;
    QLabel *lbTexto_40;
    AWMultiObject *aLet_40;
    AWMultiObject *aLet_41;
    QFrame *frAux;
    QFrame *frTitulo_9;
    QLabel *lbValDES;
    QLabel *lbValNUM;
    QLabel *lbAux_2;
    QPushButton *btnIMPPant;
    QFrame *frAux_2;
    QLabel *lbUnit3;
    QLabel *lbApagado;
    QLabel *lbAux_1;

    void setupUi(QWidget *F3)
    {
        if (F3->objectName().isEmpty())
            F3->setObjectName(QString::fromUtf8("F3"));
        F3->resize(1024, 662);
        F3->setMinimumSize(QSize(1024, 662));
        F3->setMaximumSize(QSize(1024, 662));
        F3->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbIMGFondo = new QLabel(F3);
        lbIMGFondo->setObjectName(QString::fromUtf8("lbIMGFondo"));
        lbIMGFondo->setGeometry(QRect(0, 0, 1024, 662));
        lbIMGFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/BackGround.png")));
        lbIMGFondo->setScaledContents(true);
        fr_1 = new QFrame(F3);
        fr_1->setObjectName(QString::fromUtf8("fr_1"));
        fr_1->setGeometry(QRect(4, 54, 341, 528));
        fr_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_1->setFrameShape(QFrame::StyledPanel);
        fr_1->setFrameShadow(QFrame::Plain);
        fr_1->setLineWidth(1);
        fr_1->setMidLineWidth(0);
        frTitulo_1 = new QFrame(fr_1);
        frTitulo_1->setObjectName(QString::fromUtf8("frTitulo_1"));
        frTitulo_1->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_1->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_1->setFrameShape(QFrame::WinPanel);
        frTitulo_1->setFrameShadow(QFrame::Raised);
        frTitulo_1->setLineWidth(2);
        frTitulo_1->setMidLineWidth(0);
        lbTitulo_1 = new QLabel(fr_1);
        lbTitulo_1->setObjectName(QString::fromUtf8("lbTitulo_1"));
        lbTitulo_1->setGeometry(QRect(88, 5, 181, 16));
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        lbTitulo_1->setFont(font);
        lbTitulo_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_1 = new QLabel(fr_1);
        lbTexto_1->setObjectName(QString::fromUtf8("lbTexto_1"));
        lbTexto_1->setGeometry(QRect(42, 36, 281, 16));
        QFont font1;
        font1.setPointSize(8);
        font1.setBold(true);
        font1.setWeight(75);
        lbTexto_1->setFont(font1);
        lbTexto_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_1 = new AWMultiObject(fr_1);
        aLet_1->setObjectName(QString::fromUtf8("aLet_1"));
        aLet_1->setGeometry(QRect(13, 29, 25, 31));
        aLet_1->setElementType(AWMultiObject::CIRLED);
        aLet_1->setOnColor(AWMultiObject::Grey);
        aLet_1->setOffColor(AWMultiObject::Grey);
        lbTexto_2 = new QLabel(fr_1);
        lbTexto_2->setObjectName(QString::fromUtf8("lbTexto_2"));
        lbTexto_2->setGeometry(QRect(42, 55, 281, 16));
        lbTexto_2->setFont(font1);
        lbTexto_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_2 = new AWMultiObject(fr_1);
        aLet_2->setObjectName(QString::fromUtf8("aLet_2"));
        aLet_2->setGeometry(QRect(13, 48, 25, 31));
        aLet_2->setElementType(AWMultiObject::CIRLED);
        aLet_2->setOnColor(AWMultiObject::Grey);
        aLet_2->setOffColor(AWMultiObject::Grey);
        lbTexto_3 = new QLabel(fr_1);
        lbTexto_3->setObjectName(QString::fromUtf8("lbTexto_3"));
        lbTexto_3->setGeometry(QRect(42, 74, 281, 16));
        lbTexto_3->setFont(font1);
        lbTexto_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_3 = new AWMultiObject(fr_1);
        aLet_3->setObjectName(QString::fromUtf8("aLet_3"));
        aLet_3->setGeometry(QRect(13, 68, 25, 31));
        aLet_3->setElementType(AWMultiObject::CIRLED);
        aLet_3->setOnColor(AWMultiObject::Grey);
        aLet_3->setOffColor(AWMultiObject::Grey);
        lbTexto_4 = new QLabel(fr_1);
        lbTexto_4->setObjectName(QString::fromUtf8("lbTexto_4"));
        lbTexto_4->setGeometry(QRect(42, 94, 281, 16));
        lbTexto_4->setFont(font1);
        lbTexto_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_4 = new AWMultiObject(fr_1);
        aLet_4->setObjectName(QString::fromUtf8("aLet_4"));
        aLet_4->setGeometry(QRect(13, 86, 25, 31));
        aLet_4->setElementType(AWMultiObject::CIRLED);
        aLet_4->setOnColor(AWMultiObject::Grey);
        aLet_4->setOffColor(AWMultiObject::Grey);
        aLet_5 = new AWMultiObject(fr_1);
        aLet_5->setObjectName(QString::fromUtf8("aLet_5"));
        aLet_5->setGeometry(QRect(13, 105, 25, 31));
        aLet_5->setElementType(AWMultiObject::CIRLED);
        aLet_5->setOnColor(AWMultiObject::Grey);
        aLet_5->setOffColor(AWMultiObject::Grey);
        lbTexto_5 = new QLabel(fr_1);
        lbTexto_5->setObjectName(QString::fromUtf8("lbTexto_5"));
        lbTexto_5->setGeometry(QRect(42, 113, 281, 16));
        lbTexto_5->setFont(font1);
        lbTexto_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_6 = new AWMultiObject(fr_1);
        aLet_6->setObjectName(QString::fromUtf8("aLet_6"));
        aLet_6->setGeometry(QRect(13, 143, 25, 31));
        aLet_6->setElementType(AWMultiObject::CIRLED);
        aLet_6->setOnColor(AWMultiObject::Grey);
        aLet_6->setOffColor(AWMultiObject::Grey);
        lbTexto_6 = new QLabel(fr_1);
        lbTexto_6->setObjectName(QString::fromUtf8("lbTexto_6"));
        lbTexto_6->setGeometry(QRect(42, 151, 281, 16));
        lbTexto_6->setFont(font1);
        lbTexto_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_7 = new QLabel(fr_1);
        lbTexto_7->setObjectName(QString::fromUtf8("lbTexto_7"));
        lbTexto_7->setGeometry(QRect(42, 170, 281, 16));
        lbTexto_7->setFont(font1);
        lbTexto_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_7 = new AWMultiObject(fr_1);
        aLet_7->setObjectName(QString::fromUtf8("aLet_7"));
        aLet_7->setGeometry(QRect(13, 163, 25, 31));
        aLet_7->setElementType(AWMultiObject::CIRLED);
        aLet_7->setOnColor(AWMultiObject::Grey);
        aLet_7->setOffColor(AWMultiObject::Grey);
        aLet_8 = new AWMultiObject(fr_1);
        aLet_8->setObjectName(QString::fromUtf8("aLet_8"));
        aLet_8->setGeometry(QRect(13, 183, 25, 31));
        aLet_8->setElementType(AWMultiObject::CIRLED);
        aLet_8->setOnColor(AWMultiObject::Grey);
        aLet_8->setOffColor(AWMultiObject::Grey);
        lbTexto_8 = new QLabel(fr_1);
        lbTexto_8->setObjectName(QString::fromUtf8("lbTexto_8"));
        lbTexto_8->setGeometry(QRect(42, 189, 281, 16));
        lbTexto_8->setFont(font1);
        lbTexto_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_9 = new AWMultiObject(fr_1);
        aLet_9->setObjectName(QString::fromUtf8("aLet_9"));
        aLet_9->setGeometry(QRect(13, 203, 25, 31));
        aLet_9->setElementType(AWMultiObject::CIRLED);
        aLet_9->setOnColor(AWMultiObject::Grey);
        aLet_9->setOffColor(AWMultiObject::Grey);
        lbTexto_9 = new QLabel(fr_1);
        lbTexto_9->setObjectName(QString::fromUtf8("lbTexto_9"));
        lbTexto_9->setGeometry(QRect(42, 210, 281, 16));
        lbTexto_9->setFont(font1);
        lbTexto_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_10 = new QLabel(fr_1);
        lbTexto_10->setObjectName(QString::fromUtf8("lbTexto_10"));
        lbTexto_10->setGeometry(QRect(42, 229, 281, 16));
        lbTexto_10->setFont(font1);
        lbTexto_10->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_10 = new AWMultiObject(fr_1);
        aLet_10->setObjectName(QString::fromUtf8("aLet_10"));
        aLet_10->setGeometry(QRect(13, 220, 25, 31));
        aLet_10->setElementType(AWMultiObject::CIRLED);
        aLet_10->setOnColor(AWMultiObject::Grey);
        aLet_10->setOffColor(AWMultiObject::Grey);
        lbTexto_11 = new QLabel(fr_1);
        lbTexto_11->setObjectName(QString::fromUtf8("lbTexto_11"));
        lbTexto_11->setGeometry(QRect(42, 248, 281, 16));
        lbTexto_11->setFont(font1);
        lbTexto_11->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_11 = new AWMultiObject(fr_1);
        aLet_11->setObjectName(QString::fromUtf8("aLet_11"));
        aLet_11->setGeometry(QRect(13, 240, 25, 31));
        aLet_11->setElementType(AWMultiObject::CIRLED);
        aLet_11->setOnColor(AWMultiObject::Grey);
        aLet_11->setOffColor(AWMultiObject::Grey);
        aLet_12 = new AWMultiObject(fr_1);
        aLet_12->setObjectName(QString::fromUtf8("aLet_12"));
        aLet_12->setGeometry(QRect(13, 260, 25, 31));
        aLet_12->setElementType(AWMultiObject::CIRLED);
        aLet_12->setOnColor(AWMultiObject::Grey);
        aLet_12->setOffColor(AWMultiObject::Grey);
        lbTexto_12 = new QLabel(fr_1);
        lbTexto_12->setObjectName(QString::fromUtf8("lbTexto_12"));
        lbTexto_12->setGeometry(QRect(42, 268, 281, 16));
        lbTexto_12->setFont(font1);
        lbTexto_12->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_13 = new QLabel(fr_1);
        lbTexto_13->setObjectName(QString::fromUtf8("lbTexto_13"));
        lbTexto_13->setGeometry(QRect(42, 285, 281, 16));
        lbTexto_13->setFont(font1);
        lbTexto_13->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_13 = new AWMultiObject(fr_1);
        aLet_13->setObjectName(QString::fromUtf8("aLet_13"));
        aLet_13->setGeometry(QRect(13, 280, 25, 31));
        aLet_13->setElementType(AWMultiObject::CIRLED);
        aLet_13->setOnColor(AWMultiObject::Grey);
        aLet_13->setOffColor(AWMultiObject::Grey);
        aLet_14 = new AWMultiObject(fr_1);
        aLet_14->setObjectName(QString::fromUtf8("aLet_14"));
        aLet_14->setGeometry(QRect(13, 300, 25, 31));
        aLet_14->setElementType(AWMultiObject::CIRLED);
        aLet_14->setOnColor(AWMultiObject::Grey);
        aLet_14->setOffColor(AWMultiObject::Grey);
        lbTexto_14 = new QLabel(fr_1);
        lbTexto_14->setObjectName(QString::fromUtf8("lbTexto_14"));
        lbTexto_14->setGeometry(QRect(42, 305, 281, 16));
        lbTexto_14->setFont(font1);
        lbTexto_14->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_15 = new QLabel(fr_1);
        lbTexto_15->setObjectName(QString::fromUtf8("lbTexto_15"));
        lbTexto_15->setGeometry(QRect(42, 325, 281, 16));
        lbTexto_15->setFont(font1);
        lbTexto_15->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_15 = new AWMultiObject(fr_1);
        aLet_15->setObjectName(QString::fromUtf8("aLet_15"));
        aLet_15->setGeometry(QRect(13, 318, 25, 31));
        aLet_15->setElementType(AWMultiObject::CIRLED);
        aLet_15->setOnColor(AWMultiObject::Grey);
        aLet_15->setOffColor(AWMultiObject::Grey);
        aLet_16 = new AWMultiObject(fr_1);
        aLet_16->setObjectName(QString::fromUtf8("aLet_16"));
        aLet_16->setGeometry(QRect(13, 337, 25, 31));
        aLet_16->setElementType(AWMultiObject::CIRLED);
        aLet_16->setOnColor(AWMultiObject::Grey);
        aLet_16->setOffColor(AWMultiObject::Grey);
        lbTexto_16 = new QLabel(fr_1);
        lbTexto_16->setObjectName(QString::fromUtf8("lbTexto_16"));
        lbTexto_16->setGeometry(QRect(42, 344, 281, 16));
        lbTexto_16->setFont(font1);
        lbTexto_16->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_17 = new AWMultiObject(fr_1);
        aLet_17->setObjectName(QString::fromUtf8("aLet_17"));
        aLet_17->setGeometry(QRect(13, 375, 25, 31));
        aLet_17->setElementType(AWMultiObject::CIRLED);
        aLet_17->setOnColor(AWMultiObject::Grey);
        aLet_17->setOffColor(AWMultiObject::Grey);
        lbTexto_17 = new QLabel(fr_1);
        lbTexto_17->setObjectName(QString::fromUtf8("lbTexto_17"));
        lbTexto_17->setGeometry(QRect(42, 382, 281, 16));
        lbTexto_17->setFont(font1);
        lbTexto_17->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_18 = new AWMultiObject(fr_1);
        aLet_18->setObjectName(QString::fromUtf8("aLet_18"));
        aLet_18->setGeometry(QRect(13, 395, 25, 31));
        aLet_18->setElementType(AWMultiObject::CIRLED);
        aLet_18->setOnColor(AWMultiObject::Grey);
        aLet_18->setOffColor(AWMultiObject::Grey);
        lbTexto_18 = new QLabel(fr_1);
        lbTexto_18->setObjectName(QString::fromUtf8("lbTexto_18"));
        lbTexto_18->setGeometry(QRect(42, 402, 281, 16));
        lbTexto_18->setFont(font1);
        lbTexto_18->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_19 = new AWMultiObject(fr_1);
        aLet_19->setObjectName(QString::fromUtf8("aLet_19"));
        aLet_19->setGeometry(QRect(13, 415, 25, 31));
        aLet_19->setElementType(AWMultiObject::CIRLED);
        aLet_19->setOnColor(AWMultiObject::Grey);
        aLet_19->setOffColor(AWMultiObject::Grey);
        lbTexto_19 = new QLabel(fr_1);
        lbTexto_19->setObjectName(QString::fromUtf8("lbTexto_19"));
        lbTexto_19->setGeometry(QRect(42, 420, 281, 16));
        lbTexto_19->setFont(font1);
        lbTexto_19->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_20 = new QLabel(fr_1);
        lbTexto_20->setObjectName(QString::fromUtf8("lbTexto_20"));
        lbTexto_20->setGeometry(QRect(42, 440, 281, 16));
        lbTexto_20->setFont(font1);
        lbTexto_20->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_20 = new AWMultiObject(fr_1);
        aLet_20->setObjectName(QString::fromUtf8("aLet_20"));
        aLet_20->setGeometry(QRect(13, 435, 25, 31));
        aLet_20->setElementType(AWMultiObject::CIRLED);
        aLet_20->setOnColor(AWMultiObject::Grey);
        aLet_20->setOffColor(AWMultiObject::Grey);
        fr_2 = new QFrame(F3);
        fr_2->setObjectName(QString::fromUtf8("fr_2"));
        fr_2->setGeometry(QRect(345, 54, 341, 528));
        fr_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_2->setFrameShape(QFrame::StyledPanel);
        fr_2->setFrameShadow(QFrame::Plain);
        fr_2->setLineWidth(1);
        fr_2->setMidLineWidth(0);
        frTitulo_2 = new QFrame(fr_2);
        frTitulo_2->setObjectName(QString::fromUtf8("frTitulo_2"));
        frTitulo_2->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_2->setFrameShape(QFrame::WinPanel);
        frTitulo_2->setFrameShadow(QFrame::Raised);
        frTitulo_2->setLineWidth(2);
        frTitulo_2->setMidLineWidth(0);
        lbTitulo_2 = new QLabel(fr_2);
        lbTitulo_2->setObjectName(QString::fromUtf8("lbTitulo_2"));
        lbTitulo_2->setGeometry(QRect(42, 5, 281, 20));
        lbTitulo_2->setFont(font);
        lbTitulo_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_21 = new QLabel(fr_2);
        lbTexto_21->setObjectName(QString::fromUtf8("lbTexto_21"));
        lbTexto_21->setGeometry(QRect(42, 36, 281, 16));
        lbTexto_21->setFont(font1);
        lbTexto_21->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_21 = new AWMultiObject(fr_2);
        aLet_21->setObjectName(QString::fromUtf8("aLet_21"));
        aLet_21->setGeometry(QRect(13, 29, 25, 31));
        aLet_21->setElementType(AWMultiObject::CIRLED);
        aLet_21->setOnColor(AWMultiObject::Grey);
        aLet_21->setOffColor(AWMultiObject::Grey);
        lbTexto_22 = new QLabel(fr_2);
        lbTexto_22->setObjectName(QString::fromUtf8("lbTexto_22"));
        lbTexto_22->setGeometry(QRect(42, 55, 281, 16));
        lbTexto_22->setFont(font1);
        lbTexto_22->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_22 = new AWMultiObject(fr_2);
        aLet_22->setObjectName(QString::fromUtf8("aLet_22"));
        aLet_22->setGeometry(QRect(13, 48, 25, 31));
        aLet_22->setElementType(AWMultiObject::CIRLED);
        aLet_22->setOnColor(AWMultiObject::Grey);
        aLet_22->setOffColor(AWMultiObject::Grey);
        lbTexto_23 = new QLabel(fr_2);
        lbTexto_23->setObjectName(QString::fromUtf8("lbTexto_23"));
        lbTexto_23->setGeometry(QRect(42, 74, 281, 16));
        lbTexto_23->setFont(font1);
        lbTexto_23->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_23 = new AWMultiObject(fr_2);
        aLet_23->setObjectName(QString::fromUtf8("aLet_23"));
        aLet_23->setGeometry(QRect(13, 68, 25, 31));
        aLet_23->setElementType(AWMultiObject::CIRLED);
        aLet_23->setOnColor(AWMultiObject::Grey);
        aLet_23->setOffColor(AWMultiObject::Grey);
        lbTexto_24 = new QLabel(fr_2);
        lbTexto_24->setObjectName(QString::fromUtf8("lbTexto_24"));
        lbTexto_24->setGeometry(QRect(42, 94, 281, 16));
        lbTexto_24->setFont(font1);
        lbTexto_24->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_24 = new AWMultiObject(fr_2);
        aLet_24->setObjectName(QString::fromUtf8("aLet_24"));
        aLet_24->setGeometry(QRect(13, 86, 25, 31));
        aLet_24->setElementType(AWMultiObject::CIRLED);
        aLet_24->setOnColor(AWMultiObject::Grey);
        aLet_24->setOffColor(AWMultiObject::Grey);
        aLet_25 = new AWMultiObject(fr_2);
        aLet_25->setObjectName(QString::fromUtf8("aLet_25"));
        aLet_25->setGeometry(QRect(13, 105, 25, 31));
        aLet_25->setElementType(AWMultiObject::CIRLED);
        aLet_25->setOnColor(AWMultiObject::Grey);
        aLet_25->setOffColor(AWMultiObject::Grey);
        lbTexto_25 = new QLabel(fr_2);
        lbTexto_25->setObjectName(QString::fromUtf8("lbTexto_25"));
        lbTexto_25->setGeometry(QRect(42, 113, 281, 16));
        lbTexto_25->setFont(font1);
        lbTexto_25->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_26 = new AWMultiObject(fr_2);
        aLet_26->setObjectName(QString::fromUtf8("aLet_26"));
        aLet_26->setGeometry(QRect(13, 125, 25, 31));
        aLet_26->setElementType(AWMultiObject::CIRLED);
        aLet_26->setOnColor(AWMultiObject::Grey);
        aLet_26->setOffColor(AWMultiObject::Grey);
        lbTexto_26 = new QLabel(fr_2);
        lbTexto_26->setObjectName(QString::fromUtf8("lbTexto_26"));
        lbTexto_26->setGeometry(QRect(42, 130, 281, 16));
        lbTexto_26->setFont(font1);
        lbTexto_26->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_27 = new QLabel(fr_2);
        lbTexto_27->setObjectName(QString::fromUtf8("lbTexto_27"));
        lbTexto_27->setGeometry(QRect(42, 150, 281, 16));
        lbTexto_27->setFont(font1);
        lbTexto_27->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_27 = new AWMultiObject(fr_2);
        aLet_27->setObjectName(QString::fromUtf8("aLet_27"));
        aLet_27->setGeometry(QRect(13, 143, 25, 31));
        aLet_27->setElementType(AWMultiObject::CIRLED);
        aLet_27->setOnColor(AWMultiObject::Grey);
        aLet_27->setOffColor(AWMultiObject::Grey);
        aLet_28 = new AWMultiObject(fr_2);
        aLet_28->setObjectName(QString::fromUtf8("aLet_28"));
        aLet_28->setGeometry(QRect(13, 163, 25, 31));
        aLet_28->setElementType(AWMultiObject::CIRLED);
        aLet_28->setOnColor(AWMultiObject::Grey);
        aLet_28->setOffColor(AWMultiObject::Grey);
        lbTexto_28 = new QLabel(fr_2);
        lbTexto_28->setObjectName(QString::fromUtf8("lbTexto_28"));
        lbTexto_28->setGeometry(QRect(42, 169, 281, 16));
        lbTexto_28->setFont(font1);
        lbTexto_28->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_29 = new AWMultiObject(fr_2);
        aLet_29->setObjectName(QString::fromUtf8("aLet_29"));
        aLet_29->setGeometry(QRect(13, 183, 25, 31));
        aLet_29->setElementType(AWMultiObject::CIRLED);
        aLet_29->setOnColor(AWMultiObject::Grey);
        aLet_29->setOffColor(AWMultiObject::Grey);
        lbTexto_29 = new QLabel(fr_2);
        lbTexto_29->setObjectName(QString::fromUtf8("lbTexto_29"));
        lbTexto_29->setGeometry(QRect(42, 190, 281, 16));
        lbTexto_29->setFont(font1);
        lbTexto_29->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_30 = new QLabel(fr_2);
        lbTexto_30->setObjectName(QString::fromUtf8("lbTexto_30"));
        lbTexto_30->setGeometry(QRect(42, 209, 281, 16));
        lbTexto_30->setFont(font1);
        lbTexto_30->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_30 = new AWMultiObject(fr_2);
        aLet_30->setObjectName(QString::fromUtf8("aLet_30"));
        aLet_30->setGeometry(QRect(13, 200, 25, 31));
        aLet_30->setElementType(AWMultiObject::CIRLED);
        aLet_30->setOnColor(AWMultiObject::Grey);
        aLet_30->setOffColor(AWMultiObject::Grey);
        lbTexto_31 = new QLabel(fr_2);
        lbTexto_31->setObjectName(QString::fromUtf8("lbTexto_31"));
        lbTexto_31->setGeometry(QRect(42, 228, 281, 16));
        lbTexto_31->setFont(font1);
        lbTexto_31->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_31 = new AWMultiObject(fr_2);
        aLet_31->setObjectName(QString::fromUtf8("aLet_31"));
        aLet_31->setGeometry(QRect(13, 220, 25, 31));
        aLet_31->setElementType(AWMultiObject::CIRLED);
        aLet_31->setOnColor(AWMultiObject::Grey);
        aLet_31->setOffColor(AWMultiObject::Grey);
        aLet_32 = new AWMultiObject(fr_2);
        aLet_32->setObjectName(QString::fromUtf8("aLet_32"));
        aLet_32->setGeometry(QRect(13, 240, 25, 31));
        aLet_32->setElementType(AWMultiObject::CIRLED);
        aLet_32->setOnColor(AWMultiObject::Grey);
        aLet_32->setOffColor(AWMultiObject::Grey);
        lbTexto_32 = new QLabel(fr_2);
        lbTexto_32->setObjectName(QString::fromUtf8("lbTexto_32"));
        lbTexto_32->setGeometry(QRect(42, 248, 281, 16));
        lbTexto_32->setFont(font1);
        lbTexto_32->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_33 = new QLabel(fr_2);
        lbTexto_33->setObjectName(QString::fromUtf8("lbTexto_33"));
        lbTexto_33->setGeometry(QRect(42, 265, 281, 16));
        lbTexto_33->setFont(font1);
        lbTexto_33->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_33 = new AWMultiObject(fr_2);
        aLet_33->setObjectName(QString::fromUtf8("aLet_33"));
        aLet_33->setGeometry(QRect(13, 260, 25, 31));
        aLet_33->setElementType(AWMultiObject::CIRLED);
        aLet_33->setOnColor(AWMultiObject::Grey);
        aLet_33->setOffColor(AWMultiObject::Grey);
        aLet_34 = new AWMultiObject(fr_2);
        aLet_34->setObjectName(QString::fromUtf8("aLet_34"));
        aLet_34->setGeometry(QRect(13, 280, 25, 31));
        aLet_34->setElementType(AWMultiObject::CIRLED);
        aLet_34->setOnColor(AWMultiObject::Grey);
        aLet_34->setOffColor(AWMultiObject::Grey);
        lbTexto_34 = new QLabel(fr_2);
        lbTexto_34->setObjectName(QString::fromUtf8("lbTexto_34"));
        lbTexto_34->setGeometry(QRect(42, 285, 281, 16));
        lbTexto_34->setFont(font1);
        lbTexto_34->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_35 = new QLabel(fr_2);
        lbTexto_35->setObjectName(QString::fromUtf8("lbTexto_35"));
        lbTexto_35->setGeometry(QRect(42, 305, 281, 16));
        lbTexto_35->setFont(font1);
        lbTexto_35->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_35 = new AWMultiObject(fr_2);
        aLet_35->setObjectName(QString::fromUtf8("aLet_35"));
        aLet_35->setGeometry(QRect(13, 298, 25, 31));
        aLet_35->setElementType(AWMultiObject::CIRLED);
        aLet_35->setOnColor(AWMultiObject::Grey);
        aLet_35->setOffColor(AWMultiObject::Grey);
        aLet_36 = new AWMultiObject(fr_2);
        aLet_36->setObjectName(QString::fromUtf8("aLet_36"));
        aLet_36->setGeometry(QRect(13, 317, 25, 31));
        aLet_36->setElementType(AWMultiObject::CIRLED);
        aLet_36->setOnColor(AWMultiObject::Grey);
        aLet_36->setOffColor(AWMultiObject::Grey);
        lbTexto_36 = new QLabel(fr_2);
        lbTexto_36->setObjectName(QString::fromUtf8("lbTexto_36"));
        lbTexto_36->setGeometry(QRect(42, 324, 281, 16));
        lbTexto_36->setFont(font1);
        lbTexto_36->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_3 = new QFrame(F3);
        fr_3->setObjectName(QString::fromUtf8("fr_3"));
        fr_3->setGeometry(QRect(686, 53, 341, 528));
        fr_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_3->setFrameShape(QFrame::StyledPanel);
        fr_3->setFrameShadow(QFrame::Plain);
        fr_3->setLineWidth(1);
        fr_3->setMidLineWidth(0);
        frTitulo_3 = new QFrame(fr_3);
        frTitulo_3->setObjectName(QString::fromUtf8("frTitulo_3"));
        frTitulo_3->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_3->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_3->setFrameShape(QFrame::WinPanel);
        frTitulo_3->setFrameShadow(QFrame::Raised);
        frTitulo_3->setLineWidth(2);
        frTitulo_3->setMidLineWidth(0);
        lbTitulo_3 = new QLabel(fr_3);
        lbTitulo_3->setObjectName(QString::fromUtf8("lbTitulo_3"));
        lbTitulo_3->setGeometry(QRect(32, 5, 291, 20));
        lbTitulo_3->setFont(font);
        lbTitulo_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_37 = new QLabel(fr_3);
        lbTexto_37->setObjectName(QString::fromUtf8("lbTexto_37"));
        lbTexto_37->setGeometry(QRect(42, 35, 281, 16));
        lbTexto_37->setFont(font1);
        lbTexto_37->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_37 = new AWMultiObject(fr_3);
        aLet_37->setObjectName(QString::fromUtf8("aLet_37"));
        aLet_37->setGeometry(QRect(13, 29, 25, 31));
        aLet_37->setElementType(AWMultiObject::CIRLED);
        aLet_37->setOnColor(AWMultiObject::Grey);
        aLet_37->setOffColor(AWMultiObject::Grey);
        lbTexto_38 = new QLabel(fr_3);
        lbTexto_38->setObjectName(QString::fromUtf8("lbTexto_38"));
        lbTexto_38->setGeometry(QRect(42, 74, 281, 16));
        lbTexto_38->setFont(font1);
        lbTexto_38->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_39 = new QLabel(fr_3);
        lbTexto_39->setObjectName(QString::fromUtf8("lbTexto_39"));
        lbTexto_39->setGeometry(QRect(42, 94, 281, 16));
        lbTexto_39->setFont(font1);
        lbTexto_39->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_39 = new AWMultiObject(fr_3);
        aLet_39->setObjectName(QString::fromUtf8("aLet_39"));
        aLet_39->setGeometry(QRect(13, 68, 25, 31));
        aLet_39->setElementType(AWMultiObject::CIRLED);
        aLet_39->setOnColor(AWMultiObject::Grey);
        aLet_39->setOffColor(AWMultiObject::Grey);
        lbTexto_40 = new QLabel(fr_3);
        lbTexto_40->setObjectName(QString::fromUtf8("lbTexto_40"));
        lbTexto_40->setGeometry(QRect(42, 113, 281, 16));
        lbTexto_40->setFont(font1);
        lbTexto_40->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_40 = new AWMultiObject(fr_3);
        aLet_40->setObjectName(QString::fromUtf8("aLet_40"));
        aLet_40->setGeometry(QRect(13, 86, 25, 31));
        aLet_40->setElementType(AWMultiObject::CIRLED);
        aLet_40->setOnColor(AWMultiObject::Grey);
        aLet_40->setOffColor(AWMultiObject::Grey);
        aLet_41 = new AWMultiObject(fr_3);
        aLet_41->setObjectName(QString::fromUtf8("aLet_41"));
        aLet_41->setGeometry(QRect(13, 105, 25, 31));
        aLet_41->setElementType(AWMultiObject::CIRLED);
        aLet_41->setOnColor(AWMultiObject::Grey);
        aLet_41->setOffColor(AWMultiObject::Grey);
        frAux = new QFrame(F3);
        frAux->setObjectName(QString::fromUtf8("frAux"));
        frAux->setGeometry(QRect(324, 615, 63, 24));
        frAux->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux->setFrameShape(QFrame::WinPanel);
        frAux->setFrameShadow(QFrame::Sunken);
        frTitulo_9 = new QFrame(F3);
        frTitulo_9->setObjectName(QString::fromUtf8("frTitulo_9"));
        frTitulo_9->setGeometry(QRect(310, 590, 561, 54));
        frTitulo_9->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_9->setFrameShape(QFrame::WinPanel);
        frTitulo_9->setFrameShadow(QFrame::Raised);
        frTitulo_9->setLineWidth(2);
        frTitulo_9->setMidLineWidth(0);
        lbValDES = new QLabel(F3);
        lbValDES->setObjectName(QString::fromUtf8("lbValDES"));
        lbValDES->setGeometry(QRect(406, 620, 151, 16));
        QFont font2;
        font2.setPointSize(11);
        font2.setBold(true);
        font2.setWeight(75);
        lbValDES->setFont(font2);
        lbValDES->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbValNUM = new QLabel(F3);
        lbValNUM->setObjectName(QString::fromUtf8("lbValNUM"));
        lbValNUM->setGeometry(QRect(346, 620, 35, 16));
        lbValNUM->setFont(font2);
        lbValNUM->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbAux_2 = new QLabel(F3);
        lbAux_2->setObjectName(QString::fromUtf8("lbAux_2"));
        lbAux_2->setGeometry(QRect(427, 597, 101, 16));
        QFont font3;
        font3.setPointSize(12);
        font3.setBold(true);
        font3.setWeight(75);
        lbAux_2->setFont(font3);
        lbAux_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        btnIMPPant = new QPushButton(F3);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(9, 638, 134, 21));
        btnIMPPant->setFont(font1);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        frAux_2 = new QFrame(F3);
        frAux_2->setObjectName(QString::fromUtf8("frAux_2"));
        frAux_2->setGeometry(QRect(396, 615, 466, 24));
        frAux_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux_2->setFrameShape(QFrame::WinPanel);
        frAux_2->setFrameShadow(QFrame::Sunken);
        lbUnit3 = new QLabel(F3);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(840, 648, 190, 15));
        QFont font4;
        font4.setBold(true);
        font4.setWeight(75);
        lbUnit3->setFont(font4);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        lbApagado = new QLabel(F3);
        lbApagado->setObjectName(QString::fromUtf8("lbApagado"));
        lbApagado->setGeometry(QRect(143, 585, 111, 71));
        lbApagado->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbAux_1 = new QLabel(F3);
        lbAux_1->setObjectName(QString::fromUtf8("lbAux_1"));
        lbAux_1->setGeometry(QRect(340, 597, 46, 16));
        lbAux_1->setFont(font3);
        lbAux_1->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbIMGFondo->raise();
        fr_1->raise();
        fr_2->raise();
        fr_3->raise();
        frTitulo_9->raise();
        lbAux_2->raise();
        btnIMPPant->raise();
        frAux_2->raise();
        lbUnit3->raise();
        lbApagado->raise();
        lbAux_1->raise();
        lbValDES->raise();
        frAux->raise();
        lbValNUM->raise();

        retranslateUi(F3);

        QMetaObject::connectSlotsByName(F3);
    } // setupUi

    void retranslateUi(QWidget *F3)
    {
        F3->setWindowTitle(QApplication::translate("F3", "Form", 0, QApplication::UnicodeUTF8));
        lbIMGFondo->setText(QString());
        lbTitulo_1->setText(QApplication::translate("F3", "DESACEL A MIN (2\302\272 ANILLO)", 0, QApplication::UnicodeUTF8));
        lbTexto_1->setText(QApplication::translate("F3", "SEC:N1N6 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_2->setText(QApplication::translate("F3", "SEC:N1N7 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_3->setText(QApplication::translate("F3", "SEC:N1N8 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_4->setText(QApplication::translate("F3", "SEC:N2N3 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_5->setText(QApplication::translate("F3", "SEC:N2N5 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_6->setText(QApplication::translate("F3", "SEC:PT6121 A&B FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_7->setText(QApplication::translate("F3", "SEC:TEMP DE ESTATOR DEL GEN FASE W(N\302\272)", 0, QApplication::UnicodeUTF8));
        lbTexto_8->setText(QApplication::translate("F3", "SEC:TEMP DE ESTATOR DEL GEN FASE V (N\302\272)", 0, QApplication::UnicodeUTF8));
        lbTexto_9->setText(QApplication::translate("F3", "SEC:TEMP DE ESTATOR DEL GEN FASE U (N\302\272)", 0, QApplication::UnicodeUTF8));
        lbTexto_10->setText(QApplication::translate("F3", "SEC: TEMP SALIDA AIRE DE GEN", 0, QApplication::UnicodeUTF8));
        lbTexto_11->setText(QApplication::translate("F3", "SEC: TEMP DE ESTATOR DEL GEN FASE W (N\302\272)", 0, QApplication::UnicodeUTF8));
        lbTexto_12->setText(QApplication::translate("F3", "SEC: TEMP AIRE DE ENTR CUARTO DE TURB (N\302\272)", 0, QApplication::UnicodeUTF8));
        lbTexto_13->setText(QApplication::translate("F3", "SEC: TEMP DE ESTATOR DEL GEN FASE V (N\302\272)", 0, QApplication::UnicodeUTF8));
        lbTexto_14->setText(QApplication::translate("F3", "SEC: TEMP AIRE CUARTO DE GENERADOR", 0, QApplication::UnicodeUTF8));
        lbTexto_15->setText(QApplication::translate("F3", "SEC:TEMP DE ESTATOR DEL GEN PASE U (N\302\272)", 0, QApplication::UnicodeUTF8));
        lbTexto_16->setText(QApplication::translate("F3", "SEC:TEMP SALIDA AIRE DE EXCITADOR DE GEN", 0, QApplication::UnicodeUTF8));
        lbTexto_17->setText(QApplication::translate("F3", "SEC:DM GEN REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_18->setText(QApplication::translate("F3", "SEC:DM GEN REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_19->setText(QApplication::translate("F3", "SEC:DM GEN REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_20->setText(QApplication::translate("F3", "SEC:VOLTAJE BATER\303\215A BAJO (24DC)", 0, QApplication::UnicodeUTF8));
        lbTitulo_2->setText(QApplication::translate("F3", "REDUCIR POR PASOS A RELENT\303\215 (N\303\232CLEO)", 0, QApplication::UnicodeUTF8));
        lbTexto_21->setText(QApplication::translate("F3", "N\303\232CLEO:L\303\223GICO SEGUNDO ANILLO", 0, QApplication::UnicodeUTF8));
        lbTexto_22->setText(QApplication::translate("F3", "N\303\232CLEO:ICV DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        lbTexto_23->setText(QApplication::translate("F3", "N\303\232CLEO:IGV A&B RETROALS FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_24->setText(QApplication::translate("F3", "N\303\232CLEO:IGV IMPULSOR/CT MEDIDOR FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_25->setText(QApplication::translate("F3", "N\303\232CLEO:VSV DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        lbTexto_26->setText(QApplication::translate("F3", "N\303\232CLEO:VSV A&B RETROALS FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_27->setText(QApplication::translate("F3", "N\303\232CLEO:VSV IMPULSOR/CT MEDIDOR FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_28->setText(QApplication::translate("F3", "N\303\232CLEO:CDP DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        lbTexto_29->setText(QApplication::translate("F3", "N\303\232CLEO:CDP A&B RETROALS FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_30->setText(QApplication::translate("F3", "N\303\232CLEO:CDP IMPULSOR/CT MEDIDOR FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_31->setText(QApplication::translate("F3", "N\303\232CLEO:ST8 DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        lbTexto_32->setText(QApplication::translate("F3", "N\303\232CLEO:ST8 A&B RETROALS FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_33->setText(QApplication::translate("F3", "N\303\232CLEO:ST8 IMPULSOR/CT MEDIDOR FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_34->setText(QApplication::translate("F3", "N\303\232CLEO:PX36 A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_35->setText(QApplication::translate("F3", "N\303\232CLEO:T48 SOBRE TEMP", 0, QApplication::UnicodeUTF8));
        lbTexto_36->setText(QApplication::translate("F3", "N\303\232CLEO:PRES ACEITE LUB BAJA", 0, QApplication::UnicodeUTF8));
        lbTitulo_3->setText(QApplication::translate("F3", "REDUCIR POR  PASOS A RELENT\303\215 (2\302\272 ANILLO)", 0, QApplication::UnicodeUTF8));
        lbTexto_37->setText(QApplication::translate("F3", "SEC:RESUMEN VIBRACI\303\223N Sl", 0, QApplication::UnicodeUTF8));
        lbTexto_38->setText(QApplication::translate("F3", "SEC:PRES LUB A TURB BAJ BAJ(XN25>7.8K)", 0, QApplication::UnicodeUTF8));
        lbTexto_39->setText(QApplication::translate("F3", "SEC:PRES LUB TURB B BAJ BAJ(XN25>7.8K)", 0, QApplication::UnicodeUTF8));
        lbTexto_40->setText(QApplication::translate("F3", "PRES SUMIN LUB DEL GEN A&B FALLARON", 0, QApplication::UnicodeUTF8));
        lbValDES->setText(QApplication::translate("F3", "SIN APAGADOS", 0, QApplication::UnicodeUTF8));
        lbValNUM->setText(QApplication::translate("F3", "0", 0, QApplication::UnicodeUTF8));
        lbAux_2->setText(QApplication::translate("F3", "Descripci\303\263n", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("F3", "IMP PANT", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("F3", "    UNIT3", 0, QApplication::UnicodeUTF8));
        lbApagado->setText(QApplication::translate("F3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">PRIMER</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">APAGADO</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbAux_1->setText(QApplication::translate("F3", "N\302\272", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class F3: public Ui_F3 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_F3_H
