/********************************************************************************
** Form generated from reading UI file 'f4.ui'
**
** Created: Thu 19. Dec 23:58:05 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_F4_H
#define UI_F4_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "awmultiobject.h"

QT_BEGIN_NAMESPACE

class Ui_F4
{
public:
    QLabel *lbIMGFondo;
    QLabel *lbUnit3;
    QLabel *lbValDES;
    QFrame *frAux_2;
    QLabel *lbAux_1;
    QLabel *lbApagado;
    QFrame *frTitulo_9;
    QFrame *frAux;
    QLabel *lbAux_2;
    QLabel *lbValNUM;
    QPushButton *btnIMPPant;
    QFrame *fr_1;
    QFrame *frTitulo_1;
    QLabel *lbTitulo_1;
    QLabel *lbTexto_1;
    AWMultiObject *aLet_1;
    QLabel *lbTexto_2;
    AWMultiObject *aLet_2;
    QLabel *lbTexto_3;
    AWMultiObject *aLet_3;
    QLabel *lbTexto_4;
    AWMultiObject *aLet_4;
    AWMultiObject *aLet_5;
    QLabel *lbTexto_5;
    AWMultiObject *aLet_6;
    QLabel *lbTexto_6;
    QLabel *lbTexto_7;
    AWMultiObject *aLet_7;
    AWMultiObject *aLet_8;
    QLabel *lbTexto_8;
    AWMultiObject *aLet_9;
    QLabel *lbTexto_9;
    QLabel *lbTexto_10;
    AWMultiObject *aLet_10;
    QLabel *lbTexto_11;
    AWMultiObject *aLet_11;
    AWMultiObject *aLet_12;
    QLabel *lbTexto_12;
    QLabel *lbTexto_13;
    AWMultiObject *aLet_13;
    AWMultiObject *aLet_14;
    QLabel *lbTexto_14;
    QLabel *lbTexto_15;
    AWMultiObject *aLet_15;
    AWMultiObject *aLet_16;
    QLabel *lbTexto_16;
    AWMultiObject *aLet_17;
    QLabel *lbTexto_17;
    AWMultiObject *aLet_18;
    QLabel *lbTexto_18;
    AWMultiObject *aLet_19;
    QLabel *lbTexto_19;
    QLabel *lbTexto_58;
    AWMultiObject *aLet_58;
    QLabel *lbTexto_59;
    AWMultiObject *aLet_59;
    AWMultiObject *aLet_60;
    QLabel *lbTexto_60;
    AWMultiObject *aLet_61;
    QLabel *lbTexto_61;
    QLabel *lbTexto_62;
    AWMultiObject *aLet_62;
    AWMultiObject *aLet_63;
    QLabel *lbTexto_63;
    QFrame *fr_2;
    QFrame *frTitulo_5;
    QLabel *lbTitulo_5;
    QFrame *frTitulo_6;
    QLabel *lbTitulo_6;
    QLabel *lbTexto_39;
    AWMultiObject *aLet_39;
    QLabel *lbTexto_40;
    AWMultiObject *aLet_40;
    QLabel *lbTexto_41;
    AWMultiObject *aLet_41;
    QLabel *lbTexto_42;
    AWMultiObject *aLet_42;
    AWMultiObject *aLet_43;
    QLabel *lbTexto_43;
    AWMultiObject *aLet_44;
    QLabel *lbTexto_44;
    QLabel *lbTexto_45;
    AWMultiObject *aLet_45;
    AWMultiObject *aLet_46;
    QLabel *lbTexto_46;
    AWMultiObject *aLet_47;
    QLabel *lbTexto_47;
    QLabel *lbTexto_48;
    AWMultiObject *aLet_48;
    QLabel *lbTexto_49;
    AWMultiObject *aLet_49;
    AWMultiObject *aLet_50;
    QLabel *lbTexto_50;
    QLabel *lbTexto_51;
    AWMultiObject *aLet_51;
    AWMultiObject *aLet_52;
    QLabel *lbTexto_52;
    QLabel *lbTexto_53;
    AWMultiObject *aLet_53;
    AWMultiObject *aLet_54;
    QLabel *lbTexto_54;
    AWMultiObject *aLet_55;
    QLabel *lbTexto_55;
    AWMultiObject *aLet_56;
    QLabel *lbTexto_56;
    AWMultiObject *aLet_57;
    QLabel *lbTexto_57;
    AWMultiObject *aLet_64;
    QLabel *lbTexto_64;
    QFrame *fr_3;
    QFrame *frTitulo_7;
    QLabel *lbTitulo_7;
    QFrame *frTitulo_8;
    QLabel *lbTitulo_8;
    QLabel *lbTexto_65;
    AWMultiObject *aLet_65;
    QLabel *lbTexto_66;
    AWMultiObject *aLet_66;
    QLabel *lbTexto_67;
    AWMultiObject *aLet_67;
    QLabel *lbTexto_68;
    AWMultiObject *aLet_68;
    AWMultiObject *aLet_69;
    QLabel *lbTexto_69;
    AWMultiObject *aLet_70;
    QLabel *lbTexto_70;
    QLabel *lbTexto_71;
    AWMultiObject *aLet_71;
    AWMultiObject *aLet_72;
    QLabel *lbTexto_72;
    AWMultiObject *aLet_73;
    QLabel *lbTexto_73;
    QLabel *lbTexto_74;
    AWMultiObject *aLet_74;
    QLabel *lbTexto_75;
    AWMultiObject *aLet_75;
    AWMultiObject *aLet_76;
    QLabel *lbTexto_76;
    QLabel *lbTexto_77;
    AWMultiObject *aLet_77;
    AWMultiObject *aLet_78;
    QLabel *lbTexto_78;
    QLabel *lbTexto_79;
    AWMultiObject *aLet_79;
    AWMultiObject *aLet_80;
    QLabel *lbTexto_80;
    AWMultiObject *aLet_81;
    QLabel *lbTexto_81;
    AWMultiObject *aLet_82;
    QLabel *lbTexto_82;
    AWMultiObject *aLet_83;
    QLabel *lbTexto_83;
    AWMultiObject *aLet_84;
    QLabel *lbTexto_84;
    QLabel *lbTexto_85;
    AWMultiObject *aLet_85;

    void setupUi(QWidget *F4)
    {
        if (F4->objectName().isEmpty())
            F4->setObjectName(QString::fromUtf8("F4"));
        F4->resize(1024, 662);
        F4->setMinimumSize(QSize(1024, 662));
        F4->setMaximumSize(QSize(1024, 662));
        F4->setStyleSheet(QString::fromUtf8("background-color: rgb(128,128, 128);"));
        lbIMGFondo = new QLabel(F4);
        lbIMGFondo->setObjectName(QString::fromUtf8("lbIMGFondo"));
        lbIMGFondo->setGeometry(QRect(0, 0, 1024, 662));
        lbIMGFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/BackGround.png")));
        lbIMGFondo->setScaledContents(true);
        lbUnit3 = new QLabel(F4);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(841, 650, 190, 15));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        lbUnit3->setFont(font);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        lbValDES = new QLabel(F4);
        lbValDES->setObjectName(QString::fromUtf8("lbValDES"));
        lbValDES->setGeometry(QRect(407, 622, 151, 16));
        QFont font1;
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        lbValDES->setFont(font1);
        lbValDES->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux_2 = new QFrame(F4);
        frAux_2->setObjectName(QString::fromUtf8("frAux_2"));
        frAux_2->setGeometry(QRect(397, 617, 466, 24));
        frAux_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux_2->setFrameShape(QFrame::WinPanel);
        frAux_2->setFrameShadow(QFrame::Sunken);
        lbAux_1 = new QLabel(F4);
        lbAux_1->setObjectName(QString::fromUtf8("lbAux_1"));
        lbAux_1->setGeometry(QRect(341, 599, 46, 16));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        lbAux_1->setFont(font2);
        lbAux_1->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbApagado = new QLabel(F4);
        lbApagado->setObjectName(QString::fromUtf8("lbApagado"));
        lbApagado->setGeometry(QRect(142, 585, 111, 71));
        lbApagado->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frTitulo_9 = new QFrame(F4);
        frTitulo_9->setObjectName(QString::fromUtf8("frTitulo_9"));
        frTitulo_9->setGeometry(QRect(311, 592, 561, 54));
        frTitulo_9->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_9->setFrameShape(QFrame::WinPanel);
        frTitulo_9->setFrameShadow(QFrame::Raised);
        frTitulo_9->setLineWidth(2);
        frTitulo_9->setMidLineWidth(0);
        frAux = new QFrame(F4);
        frAux->setObjectName(QString::fromUtf8("frAux"));
        frAux->setGeometry(QRect(325, 617, 63, 24));
        frAux->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux->setFrameShape(QFrame::WinPanel);
        frAux->setFrameShadow(QFrame::Sunken);
        lbAux_2 = new QLabel(F4);
        lbAux_2->setObjectName(QString::fromUtf8("lbAux_2"));
        lbAux_2->setGeometry(QRect(428, 599, 101, 16));
        lbAux_2->setFont(font2);
        lbAux_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbValNUM = new QLabel(F4);
        lbValNUM->setObjectName(QString::fromUtf8("lbValNUM"));
        lbValNUM->setGeometry(QRect(347, 622, 35, 16));
        lbValNUM->setFont(font1);
        lbValNUM->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        btnIMPPant = new QPushButton(F4);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(9, 640, 134, 21));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(true);
        font3.setWeight(75);
        btnIMPPant->setFont(font3);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        fr_1 = new QFrame(F4);
        fr_1->setObjectName(QString::fromUtf8("fr_1"));
        fr_1->setGeometry(QRect(3, 53, 341, 528));
        fr_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_1->setFrameShape(QFrame::StyledPanel);
        fr_1->setFrameShadow(QFrame::Plain);
        fr_1->setLineWidth(1);
        fr_1->setMidLineWidth(0);
        frTitulo_1 = new QFrame(fr_1);
        frTitulo_1->setObjectName(QString::fromUtf8("frTitulo_1"));
        frTitulo_1->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_1->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_1->setFrameShape(QFrame::WinPanel);
        frTitulo_1->setFrameShadow(QFrame::Raised);
        frTitulo_1->setLineWidth(2);
        frTitulo_1->setMidLineWidth(0);
        lbTitulo_1 = new QLabel(fr_1);
        lbTitulo_1->setObjectName(QString::fromUtf8("lbTitulo_1"));
        lbTitulo_1->setGeometry(QRect(38, 5, 261, 20));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        lbTitulo_1->setFont(font4);
        lbTitulo_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_1 = new QLabel(fr_1);
        lbTexto_1->setObjectName(QString::fromUtf8("lbTexto_1"));
        lbTexto_1->setGeometry(QRect(42, 36, 281, 16));
        lbTexto_1->setFont(font3);
        lbTexto_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_1 = new AWMultiObject(fr_1);
        aLet_1->setObjectName(QString::fromUtf8("aLet_1"));
        aLet_1->setGeometry(QRect(13, 29, 25, 31));
        aLet_1->setElementType(AWMultiObject::CIRLED);
        aLet_1->setOnColor(AWMultiObject::Grey);
        aLet_1->setOffColor(AWMultiObject::Grey);
        lbTexto_2 = new QLabel(fr_1);
        lbTexto_2->setObjectName(QString::fromUtf8("lbTexto_2"));
        lbTexto_2->setGeometry(QRect(42, 55, 281, 16));
        lbTexto_2->setFont(font3);
        lbTexto_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_2 = new AWMultiObject(fr_1);
        aLet_2->setObjectName(QString::fromUtf8("aLet_2"));
        aLet_2->setGeometry(QRect(13, 48, 25, 31));
        aLet_2->setElementType(AWMultiObject::CIRLED);
        aLet_2->setOnColor(AWMultiObject::Grey);
        aLet_2->setOffColor(AWMultiObject::Grey);
        lbTexto_3 = new QLabel(fr_1);
        lbTexto_3->setObjectName(QString::fromUtf8("lbTexto_3"));
        lbTexto_3->setGeometry(QRect(42, 74, 281, 16));
        lbTexto_3->setFont(font3);
        lbTexto_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_3 = new AWMultiObject(fr_1);
        aLet_3->setObjectName(QString::fromUtf8("aLet_3"));
        aLet_3->setGeometry(QRect(13, 68, 25, 31));
        aLet_3->setElementType(AWMultiObject::CIRLED);
        aLet_3->setOnColor(AWMultiObject::Grey);
        aLet_3->setOffColor(AWMultiObject::Grey);
        lbTexto_4 = new QLabel(fr_1);
        lbTexto_4->setObjectName(QString::fromUtf8("lbTexto_4"));
        lbTexto_4->setGeometry(QRect(42, 94, 281, 16));
        lbTexto_4->setFont(font3);
        lbTexto_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_4 = new AWMultiObject(fr_1);
        aLet_4->setObjectName(QString::fromUtf8("aLet_4"));
        aLet_4->setGeometry(QRect(13, 86, 25, 31));
        aLet_4->setElementType(AWMultiObject::CIRLED);
        aLet_4->setOnColor(AWMultiObject::Grey);
        aLet_4->setOffColor(AWMultiObject::Grey);
        aLet_5 = new AWMultiObject(fr_1);
        aLet_5->setObjectName(QString::fromUtf8("aLet_5"));
        aLet_5->setGeometry(QRect(13, 105, 25, 31));
        aLet_5->setElementType(AWMultiObject::CIRLED);
        aLet_5->setOnColor(AWMultiObject::Grey);
        aLet_5->setOffColor(AWMultiObject::Grey);
        lbTexto_5 = new QLabel(fr_1);
        lbTexto_5->setObjectName(QString::fromUtf8("lbTexto_5"));
        lbTexto_5->setGeometry(QRect(42, 112, 281, 16));
        lbTexto_5->setFont(font3);
        lbTexto_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_6 = new AWMultiObject(fr_1);
        aLet_6->setObjectName(QString::fromUtf8("aLet_6"));
        aLet_6->setGeometry(QRect(13, 125, 25, 31));
        aLet_6->setElementType(AWMultiObject::CIRLED);
        aLet_6->setOnColor(AWMultiObject::Grey);
        aLet_6->setOffColor(AWMultiObject::Grey);
        lbTexto_6 = new QLabel(fr_1);
        lbTexto_6->setObjectName(QString::fromUtf8("lbTexto_6"));
        lbTexto_6->setGeometry(QRect(42, 131, 281, 16));
        lbTexto_6->setFont(font3);
        lbTexto_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_7 = new QLabel(fr_1);
        lbTexto_7->setObjectName(QString::fromUtf8("lbTexto_7"));
        lbTexto_7->setGeometry(QRect(42, 150, 281, 16));
        lbTexto_7->setFont(font3);
        lbTexto_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_7 = new AWMultiObject(fr_1);
        aLet_7->setObjectName(QString::fromUtf8("aLet_7"));
        aLet_7->setGeometry(QRect(13, 144, 25, 31));
        aLet_7->setElementType(AWMultiObject::CIRLED);
        aLet_7->setOnColor(AWMultiObject::Grey);
        aLet_7->setOffColor(AWMultiObject::Grey);
        aLet_8 = new AWMultiObject(fr_1);
        aLet_8->setObjectName(QString::fromUtf8("aLet_8"));
        aLet_8->setGeometry(QRect(13, 164, 25, 31));
        aLet_8->setElementType(AWMultiObject::CIRLED);
        aLet_8->setOnColor(AWMultiObject::Grey);
        aLet_8->setOffColor(AWMultiObject::Grey);
        lbTexto_8 = new QLabel(fr_1);
        lbTexto_8->setObjectName(QString::fromUtf8("lbTexto_8"));
        lbTexto_8->setGeometry(QRect(42, 170, 281, 16));
        lbTexto_8->setFont(font3);
        lbTexto_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_9 = new AWMultiObject(fr_1);
        aLet_9->setObjectName(QString::fromUtf8("aLet_9"));
        aLet_9->setGeometry(QRect(13, 182, 25, 31));
        aLet_9->setElementType(AWMultiObject::CIRLED);
        aLet_9->setOnColor(AWMultiObject::Grey);
        aLet_9->setOffColor(AWMultiObject::Grey);
        lbTexto_9 = new QLabel(fr_1);
        lbTexto_9->setObjectName(QString::fromUtf8("lbTexto_9"));
        lbTexto_9->setGeometry(QRect(42, 190, 281, 16));
        lbTexto_9->setFont(font3);
        lbTexto_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_10 = new QLabel(fr_1);
        lbTexto_10->setObjectName(QString::fromUtf8("lbTexto_10"));
        lbTexto_10->setGeometry(QRect(42, 209, 281, 16));
        lbTexto_10->setFont(font3);
        lbTexto_10->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_10 = new AWMultiObject(fr_1);
        aLet_10->setObjectName(QString::fromUtf8("aLet_10"));
        aLet_10->setGeometry(QRect(13, 202, 25, 31));
        aLet_10->setElementType(AWMultiObject::CIRLED);
        aLet_10->setOnColor(AWMultiObject::Grey);
        aLet_10->setOffColor(AWMultiObject::Grey);
        lbTexto_11 = new QLabel(fr_1);
        lbTexto_11->setObjectName(QString::fromUtf8("lbTexto_11"));
        lbTexto_11->setGeometry(QRect(42, 228, 281, 16));
        lbTexto_11->setFont(font3);
        lbTexto_11->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_11 = new AWMultiObject(fr_1);
        aLet_11->setObjectName(QString::fromUtf8("aLet_11"));
        aLet_11->setGeometry(QRect(13, 220, 25, 31));
        aLet_11->setElementType(AWMultiObject::CIRLED);
        aLet_11->setOnColor(AWMultiObject::Grey);
        aLet_11->setOffColor(AWMultiObject::Grey);
        aLet_12 = new AWMultiObject(fr_1);
        aLet_12->setObjectName(QString::fromUtf8("aLet_12"));
        aLet_12->setGeometry(QRect(13, 240, 25, 31));
        aLet_12->setElementType(AWMultiObject::CIRLED);
        aLet_12->setOnColor(AWMultiObject::Grey);
        aLet_12->setOffColor(AWMultiObject::Grey);
        lbTexto_12 = new QLabel(fr_1);
        lbTexto_12->setObjectName(QString::fromUtf8("lbTexto_12"));
        lbTexto_12->setGeometry(QRect(42, 248, 281, 16));
        lbTexto_12->setFont(font3);
        lbTexto_12->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_13 = new QLabel(fr_1);
        lbTexto_13->setObjectName(QString::fromUtf8("lbTexto_13"));
        lbTexto_13->setGeometry(QRect(42, 266, 281, 16));
        lbTexto_13->setFont(font3);
        lbTexto_13->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_13 = new AWMultiObject(fr_1);
        aLet_13->setObjectName(QString::fromUtf8("aLet_13"));
        aLet_13->setGeometry(QRect(13, 260, 25, 31));
        aLet_13->setElementType(AWMultiObject::CIRLED);
        aLet_13->setOnColor(AWMultiObject::Grey);
        aLet_13->setOffColor(AWMultiObject::Grey);
        aLet_14 = new AWMultiObject(fr_1);
        aLet_14->setObjectName(QString::fromUtf8("aLet_14"));
        aLet_14->setGeometry(QRect(13, 280, 25, 31));
        aLet_14->setElementType(AWMultiObject::CIRLED);
        aLet_14->setOnColor(AWMultiObject::Grey);
        aLet_14->setOffColor(AWMultiObject::Grey);
        lbTexto_14 = new QLabel(fr_1);
        lbTexto_14->setObjectName(QString::fromUtf8("lbTexto_14"));
        lbTexto_14->setGeometry(QRect(42, 286, 281, 16));
        lbTexto_14->setFont(font3);
        lbTexto_14->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_15 = new QLabel(fr_1);
        lbTexto_15->setObjectName(QString::fromUtf8("lbTexto_15"));
        lbTexto_15->setGeometry(QRect(42, 305, 281, 16));
        lbTexto_15->setFont(font3);
        lbTexto_15->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_15 = new AWMultiObject(fr_1);
        aLet_15->setObjectName(QString::fromUtf8("aLet_15"));
        aLet_15->setGeometry(QRect(13, 300, 25, 31));
        aLet_15->setElementType(AWMultiObject::CIRLED);
        aLet_15->setOnColor(AWMultiObject::Grey);
        aLet_15->setOffColor(AWMultiObject::Grey);
        aLet_16 = new AWMultiObject(fr_1);
        aLet_16->setObjectName(QString::fromUtf8("aLet_16"));
        aLet_16->setGeometry(QRect(13, 320, 25, 31));
        aLet_16->setElementType(AWMultiObject::CIRLED);
        aLet_16->setOnColor(AWMultiObject::Grey);
        aLet_16->setOffColor(AWMultiObject::Grey);
        lbTexto_16 = new QLabel(fr_1);
        lbTexto_16->setObjectName(QString::fromUtf8("lbTexto_16"));
        lbTexto_16->setGeometry(QRect(42, 325, 281, 16));
        lbTexto_16->setFont(font3);
        lbTexto_16->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_17 = new AWMultiObject(fr_1);
        aLet_17->setObjectName(QString::fromUtf8("aLet_17"));
        aLet_17->setGeometry(QRect(13, 340, 25, 31));
        aLet_17->setElementType(AWMultiObject::CIRLED);
        aLet_17->setOnColor(AWMultiObject::Grey);
        aLet_17->setOffColor(AWMultiObject::Grey);
        lbTexto_17 = new QLabel(fr_1);
        lbTexto_17->setObjectName(QString::fromUtf8("lbTexto_17"));
        lbTexto_17->setGeometry(QRect(42, 345, 281, 16));
        lbTexto_17->setFont(font3);
        lbTexto_17->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_18 = new AWMultiObject(fr_1);
        aLet_18->setObjectName(QString::fromUtf8("aLet_18"));
        aLet_18->setGeometry(QRect(13, 358, 25, 31));
        aLet_18->setElementType(AWMultiObject::CIRLED);
        aLet_18->setOnColor(AWMultiObject::Grey);
        aLet_18->setOffColor(AWMultiObject::Grey);
        lbTexto_18 = new QLabel(fr_1);
        lbTexto_18->setObjectName(QString::fromUtf8("lbTexto_18"));
        lbTexto_18->setGeometry(QRect(42, 365, 281, 16));
        lbTexto_18->setFont(font3);
        lbTexto_18->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_19 = new AWMultiObject(fr_1);
        aLet_19->setObjectName(QString::fromUtf8("aLet_19"));
        aLet_19->setGeometry(QRect(13, 378, 25, 31));
        aLet_19->setElementType(AWMultiObject::CIRLED);
        aLet_19->setOnColor(AWMultiObject::Grey);
        aLet_19->setOffColor(AWMultiObject::Grey);
        lbTexto_19 = new QLabel(fr_1);
        lbTexto_19->setObjectName(QString::fromUtf8("lbTexto_19"));
        lbTexto_19->setGeometry(QRect(42, 385, 281, 16));
        lbTexto_19->setFont(font3);
        lbTexto_19->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_58 = new QLabel(fr_1);
        lbTexto_58->setObjectName(QString::fromUtf8("lbTexto_58"));
        lbTexto_58->setGeometry(QRect(42, 403, 281, 16));
        lbTexto_58->setFont(font3);
        lbTexto_58->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_58 = new AWMultiObject(fr_1);
        aLet_58->setObjectName(QString::fromUtf8("aLet_58"));
        aLet_58->setGeometry(QRect(13, 398, 25, 31));
        aLet_58->setElementType(AWMultiObject::CIRLED);
        aLet_58->setOnColor(AWMultiObject::Grey);
        aLet_58->setOffColor(AWMultiObject::Grey);
        lbTexto_59 = new QLabel(fr_1);
        lbTexto_59->setObjectName(QString::fromUtf8("lbTexto_59"));
        lbTexto_59->setGeometry(QRect(42, 424, 281, 16));
        lbTexto_59->setFont(font3);
        lbTexto_59->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_59 = new AWMultiObject(fr_1);
        aLet_59->setObjectName(QString::fromUtf8("aLet_59"));
        aLet_59->setGeometry(QRect(13, 416, 25, 31));
        aLet_59->setElementType(AWMultiObject::CIRLED);
        aLet_59->setOnColor(AWMultiObject::Grey);
        aLet_59->setOffColor(AWMultiObject::Grey);
        aLet_60 = new AWMultiObject(fr_1);
        aLet_60->setObjectName(QString::fromUtf8("aLet_60"));
        aLet_60->setGeometry(QRect(13, 435, 25, 31));
        aLet_60->setElementType(AWMultiObject::CIRLED);
        aLet_60->setOnColor(AWMultiObject::Grey);
        aLet_60->setOffColor(AWMultiObject::Grey);
        lbTexto_60 = new QLabel(fr_1);
        lbTexto_60->setObjectName(QString::fromUtf8("lbTexto_60"));
        lbTexto_60->setGeometry(QRect(39, 442, 281, 16));
        lbTexto_60->setFont(font3);
        lbTexto_60->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_61 = new AWMultiObject(fr_1);
        aLet_61->setObjectName(QString::fromUtf8("aLet_61"));
        aLet_61->setGeometry(QRect(13, 455, 25, 31));
        aLet_61->setElementType(AWMultiObject::CIRLED);
        aLet_61->setOnColor(AWMultiObject::Grey);
        aLet_61->setOffColor(AWMultiObject::Grey);
        lbTexto_61 = new QLabel(fr_1);
        lbTexto_61->setObjectName(QString::fromUtf8("lbTexto_61"));
        lbTexto_61->setGeometry(QRect(42, 462, 281, 16));
        lbTexto_61->setFont(font3);
        lbTexto_61->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_62 = new QLabel(fr_1);
        lbTexto_62->setObjectName(QString::fromUtf8("lbTexto_62"));
        lbTexto_62->setGeometry(QRect(42, 480, 281, 16));
        lbTexto_62->setFont(font3);
        lbTexto_62->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_62 = new AWMultiObject(fr_1);
        aLet_62->setObjectName(QString::fromUtf8("aLet_62"));
        aLet_62->setGeometry(QRect(13, 473, 25, 31));
        aLet_62->setElementType(AWMultiObject::CIRLED);
        aLet_62->setOnColor(AWMultiObject::Grey);
        aLet_62->setOffColor(AWMultiObject::Grey);
        aLet_63 = new AWMultiObject(fr_1);
        aLet_63->setObjectName(QString::fromUtf8("aLet_63"));
        aLet_63->setGeometry(QRect(13, 495, 25, 31));
        aLet_63->setElementType(AWMultiObject::CIRLED);
        aLet_63->setOnColor(AWMultiObject::Grey);
        aLet_63->setOffColor(AWMultiObject::Grey);
        lbTexto_63 = new QLabel(fr_1);
        lbTexto_63->setObjectName(QString::fromUtf8("lbTexto_63"));
        lbTexto_63->setGeometry(QRect(42, 500, 281, 16));
        lbTexto_63->setFont(font3);
        lbTexto_63->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_2 = new QFrame(F4);
        fr_2->setObjectName(QString::fromUtf8("fr_2"));
        fr_2->setGeometry(QRect(344, 53, 341, 528));
        fr_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_2->setFrameShape(QFrame::StyledPanel);
        fr_2->setFrameShadow(QFrame::Plain);
        fr_2->setLineWidth(1);
        fr_2->setMidLineWidth(0);
        frTitulo_5 = new QFrame(fr_2);
        frTitulo_5->setObjectName(QString::fromUtf8("frTitulo_5"));
        frTitulo_5->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_5->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_5->setFrameShape(QFrame::WinPanel);
        frTitulo_5->setFrameShadow(QFrame::Raised);
        frTitulo_5->setLineWidth(2);
        frTitulo_5->setMidLineWidth(0);
        lbTitulo_5 = new QLabel(fr_2);
        lbTitulo_5->setObjectName(QString::fromUtf8("lbTitulo_5"));
        lbTitulo_5->setGeometry(QRect(88, 5, 181, 16));
        lbTitulo_5->setFont(font4);
        lbTitulo_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frTitulo_6 = new QFrame(fr_2);
        frTitulo_6->setObjectName(QString::fromUtf8("frTitulo_6"));
        frTitulo_6->setGeometry(QRect(3, 335, 333, 26));
        frTitulo_6->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_6->setFrameShape(QFrame::WinPanel);
        frTitulo_6->setFrameShadow(QFrame::Raised);
        frTitulo_6->setLineWidth(2);
        frTitulo_6->setMidLineWidth(0);
        lbTitulo_6 = new QLabel(fr_2);
        lbTitulo_6->setObjectName(QString::fromUtf8("lbTitulo_6"));
        lbTitulo_6->setGeometry(QRect(48, 337, 261, 20));
        lbTitulo_6->setFont(font4);
        lbTitulo_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_39 = new QLabel(fr_2);
        lbTexto_39->setObjectName(QString::fromUtf8("lbTexto_39"));
        lbTexto_39->setGeometry(QRect(42, 36, 281, 16));
        lbTexto_39->setFont(font3);
        lbTexto_39->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_39 = new AWMultiObject(fr_2);
        aLet_39->setObjectName(QString::fromUtf8("aLet_39"));
        aLet_39->setGeometry(QRect(13, 29, 25, 31));
        aLet_39->setElementType(AWMultiObject::CIRLED);
        aLet_39->setOnColor(AWMultiObject::Grey);
        aLet_39->setOffColor(AWMultiObject::Grey);
        lbTexto_40 = new QLabel(fr_2);
        lbTexto_40->setObjectName(QString::fromUtf8("lbTexto_40"));
        lbTexto_40->setGeometry(QRect(42, 55, 281, 16));
        lbTexto_40->setFont(font3);
        lbTexto_40->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_40 = new AWMultiObject(fr_2);
        aLet_40->setObjectName(QString::fromUtf8("aLet_40"));
        aLet_40->setGeometry(QRect(13, 48, 25, 31));
        aLet_40->setElementType(AWMultiObject::CIRLED);
        aLet_40->setOnColor(AWMultiObject::Grey);
        aLet_40->setOffColor(AWMultiObject::Grey);
        lbTexto_41 = new QLabel(fr_2);
        lbTexto_41->setObjectName(QString::fromUtf8("lbTexto_41"));
        lbTexto_41->setGeometry(QRect(42, 74, 281, 16));
        lbTexto_41->setFont(font3);
        lbTexto_41->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_41 = new AWMultiObject(fr_2);
        aLet_41->setObjectName(QString::fromUtf8("aLet_41"));
        aLet_41->setGeometry(QRect(13, 68, 25, 31));
        aLet_41->setElementType(AWMultiObject::CIRLED);
        aLet_41->setOnColor(AWMultiObject::Grey);
        aLet_41->setOffColor(AWMultiObject::Grey);
        lbTexto_42 = new QLabel(fr_2);
        lbTexto_42->setObjectName(QString::fromUtf8("lbTexto_42"));
        lbTexto_42->setGeometry(QRect(42, 94, 281, 16));
        lbTexto_42->setFont(font3);
        lbTexto_42->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_42 = new AWMultiObject(fr_2);
        aLet_42->setObjectName(QString::fromUtf8("aLet_42"));
        aLet_42->setGeometry(QRect(13, 86, 25, 31));
        aLet_42->setElementType(AWMultiObject::CIRLED);
        aLet_42->setOnColor(AWMultiObject::Grey);
        aLet_42->setOffColor(AWMultiObject::Grey);
        aLet_43 = new AWMultiObject(fr_2);
        aLet_43->setObjectName(QString::fromUtf8("aLet_43"));
        aLet_43->setGeometry(QRect(13, 105, 25, 31));
        aLet_43->setElementType(AWMultiObject::CIRLED);
        aLet_43->setOnColor(AWMultiObject::Grey);
        aLet_43->setOffColor(AWMultiObject::Grey);
        lbTexto_43 = new QLabel(fr_2);
        lbTexto_43->setObjectName(QString::fromUtf8("lbTexto_43"));
        lbTexto_43->setGeometry(QRect(42, 112, 281, 16));
        lbTexto_43->setFont(font3);
        lbTexto_43->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_44 = new AWMultiObject(fr_2);
        aLet_44->setObjectName(QString::fromUtf8("aLet_44"));
        aLet_44->setGeometry(QRect(13, 126, 25, 31));
        aLet_44->setElementType(AWMultiObject::CIRLED);
        aLet_44->setOnColor(AWMultiObject::Grey);
        aLet_44->setOffColor(AWMultiObject::Grey);
        lbTexto_44 = new QLabel(fr_2);
        lbTexto_44->setObjectName(QString::fromUtf8("lbTexto_44"));
        lbTexto_44->setGeometry(QRect(42, 131, 281, 16));
        lbTexto_44->setFont(font3);
        lbTexto_44->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_45 = new QLabel(fr_2);
        lbTexto_45->setObjectName(QString::fromUtf8("lbTexto_45"));
        lbTexto_45->setGeometry(QRect(42, 151, 281, 16));
        lbTexto_45->setFont(font3);
        lbTexto_45->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_45 = new AWMultiObject(fr_2);
        aLet_45->setObjectName(QString::fromUtf8("aLet_45"));
        aLet_45->setGeometry(QRect(13, 144, 25, 31));
        aLet_45->setElementType(AWMultiObject::CIRLED);
        aLet_45->setOnColor(AWMultiObject::Grey);
        aLet_45->setOffColor(AWMultiObject::Grey);
        aLet_46 = new AWMultiObject(fr_2);
        aLet_46->setObjectName(QString::fromUtf8("aLet_46"));
        aLet_46->setGeometry(QRect(13, 164, 25, 31));
        aLet_46->setElementType(AWMultiObject::CIRLED);
        aLet_46->setOnColor(AWMultiObject::Grey);
        aLet_46->setOffColor(AWMultiObject::Grey);
        lbTexto_46 = new QLabel(fr_2);
        lbTexto_46->setObjectName(QString::fromUtf8("lbTexto_46"));
        lbTexto_46->setGeometry(QRect(42, 170, 281, 16));
        lbTexto_46->setFont(font3);
        lbTexto_46->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_47 = new AWMultiObject(fr_2);
        aLet_47->setObjectName(QString::fromUtf8("aLet_47"));
        aLet_47->setGeometry(QRect(13, 183, 25, 31));
        aLet_47->setElementType(AWMultiObject::CIRLED);
        aLet_47->setOnColor(AWMultiObject::Grey);
        aLet_47->setOffColor(AWMultiObject::Grey);
        lbTexto_47 = new QLabel(fr_2);
        lbTexto_47->setObjectName(QString::fromUtf8("lbTexto_47"));
        lbTexto_47->setGeometry(QRect(42, 190, 281, 16));
        lbTexto_47->setFont(font3);
        lbTexto_47->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_48 = new QLabel(fr_2);
        lbTexto_48->setObjectName(QString::fromUtf8("lbTexto_48"));
        lbTexto_48->setGeometry(QRect(42, 209, 281, 16));
        lbTexto_48->setFont(font3);
        lbTexto_48->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_48 = new AWMultiObject(fr_2);
        aLet_48->setObjectName(QString::fromUtf8("aLet_48"));
        aLet_48->setGeometry(QRect(13, 202, 25, 31));
        aLet_48->setElementType(AWMultiObject::CIRLED);
        aLet_48->setOnColor(AWMultiObject::Grey);
        aLet_48->setOffColor(AWMultiObject::Grey);
        lbTexto_49 = new QLabel(fr_2);
        lbTexto_49->setObjectName(QString::fromUtf8("lbTexto_49"));
        lbTexto_49->setGeometry(QRect(42, 228, 281, 16));
        lbTexto_49->setFont(font3);
        lbTexto_49->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_49 = new AWMultiObject(fr_2);
        aLet_49->setObjectName(QString::fromUtf8("aLet_49"));
        aLet_49->setGeometry(QRect(13, 220, 25, 31));
        aLet_49->setElementType(AWMultiObject::CIRLED);
        aLet_49->setOnColor(AWMultiObject::Grey);
        aLet_49->setOffColor(AWMultiObject::Grey);
        aLet_50 = new AWMultiObject(fr_2);
        aLet_50->setObjectName(QString::fromUtf8("aLet_50"));
        aLet_50->setGeometry(QRect(13, 240, 25, 31));
        aLet_50->setElementType(AWMultiObject::CIRLED);
        aLet_50->setOnColor(AWMultiObject::Grey);
        aLet_50->setOffColor(AWMultiObject::Grey);
        lbTexto_50 = new QLabel(fr_2);
        lbTexto_50->setObjectName(QString::fromUtf8("lbTexto_50"));
        lbTexto_50->setGeometry(QRect(42, 246, 281, 16));
        lbTexto_50->setFont(font3);
        lbTexto_50->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_51 = new QLabel(fr_2);
        lbTexto_51->setObjectName(QString::fromUtf8("lbTexto_51"));
        lbTexto_51->setGeometry(QRect(42, 268, 281, 16));
        lbTexto_51->setFont(font3);
        lbTexto_51->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_51 = new AWMultiObject(fr_2);
        aLet_51->setObjectName(QString::fromUtf8("aLet_51"));
        aLet_51->setGeometry(QRect(13, 260, 25, 31));
        aLet_51->setElementType(AWMultiObject::CIRLED);
        aLet_51->setOnColor(AWMultiObject::Grey);
        aLet_51->setOffColor(AWMultiObject::Grey);
        aLet_52 = new AWMultiObject(fr_2);
        aLet_52->setObjectName(QString::fromUtf8("aLet_52"));
        aLet_52->setGeometry(QRect(13, 280, 25, 31));
        aLet_52->setElementType(AWMultiObject::CIRLED);
        aLet_52->setOnColor(AWMultiObject::Grey);
        aLet_52->setOffColor(AWMultiObject::Grey);
        lbTexto_52 = new QLabel(fr_2);
        lbTexto_52->setObjectName(QString::fromUtf8("lbTexto_52"));
        lbTexto_52->setGeometry(QRect(42, 286, 281, 16));
        lbTexto_52->setFont(font3);
        lbTexto_52->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_53 = new QLabel(fr_2);
        lbTexto_53->setObjectName(QString::fromUtf8("lbTexto_53"));
        lbTexto_53->setGeometry(QRect(42, 306, 281, 16));
        lbTexto_53->setFont(font3);
        lbTexto_53->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_53 = new AWMultiObject(fr_2);
        aLet_53->setObjectName(QString::fromUtf8("aLet_53"));
        aLet_53->setGeometry(QRect(13, 300, 25, 31));
        aLet_53->setElementType(AWMultiObject::CIRLED);
        aLet_53->setOnColor(AWMultiObject::Grey);
        aLet_53->setOffColor(AWMultiObject::Grey);
        aLet_54 = new AWMultiObject(fr_2);
        aLet_54->setObjectName(QString::fromUtf8("aLet_54"));
        aLet_54->setGeometry(QRect(13, 360, 25, 31));
        aLet_54->setElementType(AWMultiObject::CIRLED);
        aLet_54->setOnColor(AWMultiObject::Grey);
        aLet_54->setOffColor(AWMultiObject::Grey);
        lbTexto_54 = new QLabel(fr_2);
        lbTexto_54->setObjectName(QString::fromUtf8("lbTexto_54"));
        lbTexto_54->setGeometry(QRect(42, 365, 281, 16));
        lbTexto_54->setFont(font3);
        lbTexto_54->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_55 = new AWMultiObject(fr_2);
        aLet_55->setObjectName(QString::fromUtf8("aLet_55"));
        aLet_55->setGeometry(QRect(13, 378, 25, 31));
        aLet_55->setElementType(AWMultiObject::CIRLED);
        aLet_55->setOnColor(AWMultiObject::Grey);
        aLet_55->setOffColor(AWMultiObject::Grey);
        lbTexto_55 = new QLabel(fr_2);
        lbTexto_55->setObjectName(QString::fromUtf8("lbTexto_55"));
        lbTexto_55->setGeometry(QRect(42, 385, 281, 16));
        lbTexto_55->setFont(font3);
        lbTexto_55->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_56 = new AWMultiObject(fr_2);
        aLet_56->setObjectName(QString::fromUtf8("aLet_56"));
        aLet_56->setGeometry(QRect(13, 398, 25, 31));
        aLet_56->setElementType(AWMultiObject::CIRLED);
        aLet_56->setOnColor(AWMultiObject::Grey);
        aLet_56->setOffColor(AWMultiObject::Grey);
        lbTexto_56 = new QLabel(fr_2);
        lbTexto_56->setObjectName(QString::fromUtf8("lbTexto_56"));
        lbTexto_56->setGeometry(QRect(42, 403, 281, 16));
        lbTexto_56->setFont(font3);
        lbTexto_56->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_57 = new AWMultiObject(fr_2);
        aLet_57->setObjectName(QString::fromUtf8("aLet_57"));
        aLet_57->setGeometry(QRect(13, 417, 25, 31));
        aLet_57->setElementType(AWMultiObject::CIRLED);
        aLet_57->setOnColor(AWMultiObject::Grey);
        aLet_57->setOffColor(AWMultiObject::Grey);
        lbTexto_57 = new QLabel(fr_2);
        lbTexto_57->setObjectName(QString::fromUtf8("lbTexto_57"));
        lbTexto_57->setGeometry(QRect(42, 422, 281, 16));
        lbTexto_57->setFont(font3);
        lbTexto_57->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_64 = new AWMultiObject(fr_2);
        aLet_64->setObjectName(QString::fromUtf8("aLet_64"));
        aLet_64->setGeometry(QRect(13, 435, 25, 31));
        aLet_64->setElementType(AWMultiObject::CIRLED);
        aLet_64->setOnColor(AWMultiObject::Grey);
        aLet_64->setOffColor(AWMultiObject::Grey);
        lbTexto_64 = new QLabel(fr_2);
        lbTexto_64->setObjectName(QString::fromUtf8("lbTexto_64"));
        lbTexto_64->setGeometry(QRect(42, 441, 281, 16));
        lbTexto_64->setFont(font3);
        lbTexto_64->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_3 = new QFrame(F4);
        fr_3->setObjectName(QString::fromUtf8("fr_3"));
        fr_3->setGeometry(QRect(685, 53, 341, 528));
        fr_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_3->setFrameShape(QFrame::StyledPanel);
        fr_3->setFrameShadow(QFrame::Plain);
        fr_3->setLineWidth(1);
        fr_3->setMidLineWidth(0);
        frTitulo_7 = new QFrame(fr_3);
        frTitulo_7->setObjectName(QString::fromUtf8("frTitulo_7"));
        frTitulo_7->setGeometry(QRect(3, 2, 333, 26));
        frTitulo_7->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_7->setFrameShape(QFrame::WinPanel);
        frTitulo_7->setFrameShadow(QFrame::Raised);
        frTitulo_7->setLineWidth(2);
        frTitulo_7->setMidLineWidth(0);
        lbTitulo_7 = new QLabel(fr_3);
        lbTitulo_7->setObjectName(QString::fromUtf8("lbTitulo_7"));
        lbTitulo_7->setGeometry(QRect(38, 2, 271, 20));
        lbTitulo_7->setFont(font4);
        lbTitulo_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frTitulo_8 = new QFrame(fr_3);
        frTitulo_8->setObjectName(QString::fromUtf8("frTitulo_8"));
        frTitulo_8->setGeometry(QRect(3, 318, 333, 26));
        frTitulo_8->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_8->setFrameShape(QFrame::WinPanel);
        frTitulo_8->setFrameShadow(QFrame::Raised);
        frTitulo_8->setLineWidth(2);
        frTitulo_8->setMidLineWidth(0);
        lbTitulo_8 = new QLabel(fr_3);
        lbTitulo_8->setObjectName(QString::fromUtf8("lbTitulo_8"));
        lbTitulo_8->setGeometry(QRect(18, 320, 311, 20));
        lbTitulo_8->setFont(font4);
        lbTitulo_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_65 = new QLabel(fr_3);
        lbTexto_65->setObjectName(QString::fromUtf8("lbTexto_65"));
        lbTexto_65->setGeometry(QRect(42, 31, 281, 16));
        lbTexto_65->setFont(font3);
        lbTexto_65->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_65 = new AWMultiObject(fr_3);
        aLet_65->setObjectName(QString::fromUtf8("aLet_65"));
        aLet_65->setGeometry(QRect(13, 25, 25, 31));
        aLet_65->setElementType(AWMultiObject::CIRLED);
        aLet_65->setOnColor(AWMultiObject::Grey);
        aLet_65->setOffColor(AWMultiObject::Grey);
        lbTexto_66 = new QLabel(fr_3);
        lbTexto_66->setObjectName(QString::fromUtf8("lbTexto_66"));
        lbTexto_66->setGeometry(QRect(42, 51, 281, 16));
        lbTexto_66->setFont(font3);
        lbTexto_66->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_66 = new AWMultiObject(fr_3);
        aLet_66->setObjectName(QString::fromUtf8("aLet_66"));
        aLet_66->setGeometry(QRect(13, 45, 25, 31));
        aLet_66->setElementType(AWMultiObject::CIRLED);
        aLet_66->setOnColor(AWMultiObject::Grey);
        aLet_66->setOffColor(AWMultiObject::Grey);
        lbTexto_67 = new QLabel(fr_3);
        lbTexto_67->setObjectName(QString::fromUtf8("lbTexto_67"));
        lbTexto_67->setGeometry(QRect(42, 70, 281, 16));
        lbTexto_67->setFont(font3);
        lbTexto_67->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_67 = new AWMultiObject(fr_3);
        aLet_67->setObjectName(QString::fromUtf8("aLet_67"));
        aLet_67->setGeometry(QRect(13, 64, 25, 31));
        aLet_67->setElementType(AWMultiObject::CIRLED);
        aLet_67->setOnColor(AWMultiObject::Grey);
        aLet_67->setOffColor(AWMultiObject::Grey);
        lbTexto_68 = new QLabel(fr_3);
        lbTexto_68->setObjectName(QString::fromUtf8("lbTexto_68"));
        lbTexto_68->setGeometry(QRect(42, 90, 281, 16));
        lbTexto_68->setFont(font3);
        lbTexto_68->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_68 = new AWMultiObject(fr_3);
        aLet_68->setObjectName(QString::fromUtf8("aLet_68"));
        aLet_68->setGeometry(QRect(13, 83, 25, 31));
        aLet_68->setElementType(AWMultiObject::CIRLED);
        aLet_68->setOnColor(AWMultiObject::Grey);
        aLet_68->setOffColor(AWMultiObject::Grey);
        aLet_69 = new AWMultiObject(fr_3);
        aLet_69->setObjectName(QString::fromUtf8("aLet_69"));
        aLet_69->setGeometry(QRect(13, 139, 25, 31));
        aLet_69->setElementType(AWMultiObject::CIRLED);
        aLet_69->setOnColor(AWMultiObject::Grey);
        aLet_69->setOffColor(AWMultiObject::Grey);
        lbTexto_69 = new QLabel(fr_3);
        lbTexto_69->setObjectName(QString::fromUtf8("lbTexto_69"));
        lbTexto_69->setGeometry(QRect(42, 128, 281, 16));
        lbTexto_69->setFont(font3);
        lbTexto_69->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_70 = new AWMultiObject(fr_3);
        aLet_70->setObjectName(QString::fromUtf8("aLet_70"));
        aLet_70->setGeometry(QRect(13, 160, 25, 31));
        aLet_70->setElementType(AWMultiObject::CIRLED);
        aLet_70->setOnColor(AWMultiObject::Grey);
        aLet_70->setOffColor(AWMultiObject::Grey);
        lbTexto_70 = new QLabel(fr_3);
        lbTexto_70->setObjectName(QString::fromUtf8("lbTexto_70"));
        lbTexto_70->setGeometry(QRect(42, 148, 281, 16));
        lbTexto_70->setFont(font3);
        lbTexto_70->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_71 = new QLabel(fr_3);
        lbTexto_71->setObjectName(QString::fromUtf8("lbTexto_71"));
        lbTexto_71->setGeometry(QRect(42, 168, 281, 16));
        lbTexto_71->setFont(font3);
        lbTexto_71->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_71 = new AWMultiObject(fr_3);
        aLet_71->setObjectName(QString::fromUtf8("aLet_71"));
        aLet_71->setGeometry(QRect(13, 121, 25, 31));
        aLet_71->setElementType(AWMultiObject::CIRLED);
        aLet_71->setOnColor(AWMultiObject::Grey);
        aLet_71->setOffColor(AWMultiObject::Grey);
        aLet_72 = new AWMultiObject(fr_3);
        aLet_72->setObjectName(QString::fromUtf8("aLet_72"));
        aLet_72->setGeometry(QRect(13, 198, 25, 31));
        aLet_72->setElementType(AWMultiObject::CIRLED);
        aLet_72->setOnColor(AWMultiObject::Grey);
        aLet_72->setOffColor(AWMultiObject::Grey);
        lbTexto_72 = new QLabel(fr_3);
        lbTexto_72->setObjectName(QString::fromUtf8("lbTexto_72"));
        lbTexto_72->setGeometry(QRect(42, 188, 281, 16));
        lbTexto_72->setFont(font3);
        lbTexto_72->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_73 = new AWMultiObject(fr_3);
        aLet_73->setObjectName(QString::fromUtf8("aLet_73"));
        aLet_73->setGeometry(QRect(13, 237, 25, 31));
        aLet_73->setElementType(AWMultiObject::CIRLED);
        aLet_73->setOnColor(AWMultiObject::Grey);
        aLet_73->setOffColor(AWMultiObject::Grey);
        lbTexto_73 = new QLabel(fr_3);
        lbTexto_73->setObjectName(QString::fromUtf8("lbTexto_73"));
        lbTexto_73->setGeometry(QRect(42, 205, 281, 16));
        lbTexto_73->setFont(font3);
        lbTexto_73->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_74 = new QLabel(fr_3);
        lbTexto_74->setObjectName(QString::fromUtf8("lbTexto_74"));
        lbTexto_74->setGeometry(QRect(42, 385, 281, 16));
        lbTexto_74->setFont(font3);
        lbTexto_74->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_74 = new AWMultiObject(fr_3);
        aLet_74->setObjectName(QString::fromUtf8("aLet_74"));
        aLet_74->setGeometry(QRect(13, 180, 25, 31));
        aLet_74->setElementType(AWMultiObject::CIRLED);
        aLet_74->setOnColor(AWMultiObject::Grey);
        aLet_74->setOffColor(AWMultiObject::Grey);
        lbTexto_75 = new QLabel(fr_3);
        lbTexto_75->setObjectName(QString::fromUtf8("lbTexto_75"));
        lbTexto_75->setGeometry(QRect(42, 244, 281, 16));
        lbTexto_75->setFont(font3);
        lbTexto_75->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_75 = new AWMultiObject(fr_3);
        aLet_75->setObjectName(QString::fromUtf8("aLet_75"));
        aLet_75->setGeometry(QRect(13, 256, 25, 31));
        aLet_75->setElementType(AWMultiObject::CIRLED);
        aLet_75->setOnColor(AWMultiObject::Grey);
        aLet_75->setOffColor(AWMultiObject::Grey);
        aLet_76 = new AWMultiObject(fr_3);
        aLet_76->setObjectName(QString::fromUtf8("aLet_76"));
        aLet_76->setGeometry(QRect(13, 339, 25, 31));
        aLet_76->setElementType(AWMultiObject::CIRLED);
        aLet_76->setOnColor(AWMultiObject::Grey);
        aLet_76->setOffColor(AWMultiObject::Grey);
        lbTexto_76 = new QLabel(fr_3);
        lbTexto_76->setObjectName(QString::fromUtf8("lbTexto_76"));
        lbTexto_76->setGeometry(QRect(42, 263, 281, 16));
        lbTexto_76->setFont(font3);
        lbTexto_76->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_77 = new QLabel(fr_3);
        lbTexto_77->setObjectName(QString::fromUtf8("lbTexto_77"));
        lbTexto_77->setGeometry(QRect(42, 345, 281, 16));
        lbTexto_77->setFont(font3);
        lbTexto_77->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_77 = new AWMultiObject(fr_3);
        aLet_77->setObjectName(QString::fromUtf8("aLet_77"));
        aLet_77->setGeometry(QRect(13, 358, 25, 31));
        aLet_77->setElementType(AWMultiObject::CIRLED);
        aLet_77->setOnColor(AWMultiObject::Grey);
        aLet_77->setOffColor(AWMultiObject::Grey);
        aLet_78 = new AWMultiObject(fr_3);
        aLet_78->setObjectName(QString::fromUtf8("aLet_78"));
        aLet_78->setGeometry(QRect(13, 378, 25, 31));
        aLet_78->setElementType(AWMultiObject::CIRLED);
        aLet_78->setOnColor(AWMultiObject::Grey);
        aLet_78->setOffColor(AWMultiObject::Grey);
        lbTexto_78 = new QLabel(fr_3);
        lbTexto_78->setObjectName(QString::fromUtf8("lbTexto_78"));
        lbTexto_78->setGeometry(QRect(42, 365, 281, 16));
        lbTexto_78->setFont(font3);
        lbTexto_78->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_79 = new QLabel(fr_3);
        lbTexto_79->setObjectName(QString::fromUtf8("lbTexto_79"));
        lbTexto_79->setGeometry(QRect(42, 403, 281, 16));
        lbTexto_79->setFont(font3);
        lbTexto_79->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_79 = new AWMultiObject(fr_3);
        aLet_79->setObjectName(QString::fromUtf8("aLet_79"));
        aLet_79->setGeometry(QRect(13, 396, 25, 31));
        aLet_79->setElementType(AWMultiObject::CIRLED);
        aLet_79->setOnColor(AWMultiObject::Grey);
        aLet_79->setOffColor(AWMultiObject::Grey);
        aLet_80 = new AWMultiObject(fr_3);
        aLet_80->setObjectName(QString::fromUtf8("aLet_80"));
        aLet_80->setGeometry(QRect(13, 455, 25, 31));
        aLet_80->setElementType(AWMultiObject::CIRLED);
        aLet_80->setOnColor(AWMultiObject::Grey);
        aLet_80->setOffColor(AWMultiObject::Grey);
        lbTexto_80 = new QLabel(fr_3);
        lbTexto_80->setObjectName(QString::fromUtf8("lbTexto_80"));
        lbTexto_80->setGeometry(QRect(42, 462, 281, 16));
        lbTexto_80->setFont(font3);
        lbTexto_80->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_81 = new AWMultiObject(fr_3);
        aLet_81->setObjectName(QString::fromUtf8("aLet_81"));
        aLet_81->setGeometry(QRect(13, 525, 25, 31));
        aLet_81->setElementType(AWMultiObject::CIRLED);
        aLet_81->setOnColor(AWMultiObject::Grey);
        aLet_81->setOffColor(AWMultiObject::Grey);
        lbTexto_81 = new QLabel(fr_3);
        lbTexto_81->setObjectName(QString::fromUtf8("lbTexto_81"));
        lbTexto_81->setGeometry(QRect(42, 532, 281, 16));
        lbTexto_81->setFont(font3);
        lbTexto_81->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_82 = new AWMultiObject(fr_3);
        aLet_82->setObjectName(QString::fromUtf8("aLet_82"));
        aLet_82->setGeometry(QRect(13, 545, 25, 31));
        aLet_82->setElementType(AWMultiObject::CIRLED);
        aLet_82->setOnColor(AWMultiObject::Grey);
        aLet_82->setOffColor(AWMultiObject::Grey);
        lbTexto_82 = new QLabel(fr_3);
        lbTexto_82->setObjectName(QString::fromUtf8("lbTexto_82"));
        lbTexto_82->setGeometry(QRect(42, 550, 281, 16));
        lbTexto_82->setFont(font3);
        lbTexto_82->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_83 = new AWMultiObject(fr_3);
        aLet_83->setObjectName(QString::fromUtf8("aLet_83"));
        aLet_83->setGeometry(QRect(13, 415, 25, 31));
        aLet_83->setElementType(AWMultiObject::CIRLED);
        aLet_83->setOnColor(AWMultiObject::Grey);
        aLet_83->setOffColor(AWMultiObject::Grey);
        lbTexto_83 = new QLabel(fr_3);
        lbTexto_83->setObjectName(QString::fromUtf8("lbTexto_83"));
        lbTexto_83->setGeometry(QRect(42, 423, 281, 16));
        lbTexto_83->setFont(font3);
        lbTexto_83->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_84 = new AWMultiObject(fr_3);
        aLet_84->setObjectName(QString::fromUtf8("aLet_84"));
        aLet_84->setGeometry(QRect(13, 435, 25, 31));
        aLet_84->setElementType(AWMultiObject::CIRLED);
        aLet_84->setOnColor(AWMultiObject::Grey);
        aLet_84->setOffColor(AWMultiObject::Grey);
        lbTexto_84 = new QLabel(fr_3);
        lbTexto_84->setObjectName(QString::fromUtf8("lbTexto_84"));
        lbTexto_84->setGeometry(QRect(42, 441, 281, 16));
        lbTexto_84->setFont(font3);
        lbTexto_84->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_85 = new QLabel(fr_3);
        lbTexto_85->setObjectName(QString::fromUtf8("lbTexto_85"));
        lbTexto_85->setGeometry(QRect(42, 480, 281, 16));
        lbTexto_85->setFont(font3);
        lbTexto_85->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_85 = new AWMultiObject(fr_3);
        aLet_85->setObjectName(QString::fromUtf8("aLet_85"));
        aLet_85->setGeometry(QRect(13, 475, 25, 31));
        aLet_85->setElementType(AWMultiObject::CIRLED);
        aLet_85->setOnColor(AWMultiObject::Grey);
        aLet_85->setOffColor(AWMultiObject::Grey);
        lbIMGFondo->raise();
        lbUnit3->raise();
        lbApagado->raise();
        frTitulo_9->raise();
        frAux->raise();
        lbAux_2->raise();
        lbValNUM->raise();
        btnIMPPant->raise();
        frAux_2->raise();
        lbValDES->raise();
        lbAux_1->raise();
        fr_1->raise();
        fr_2->raise();
        fr_3->raise();

        retranslateUi(F4);

        QMetaObject::connectSlotsByName(F4);
    } // setupUi

    void retranslateUi(QWidget *F4)
    {
        F4->setWindowTitle(QApplication::translate("F4", "Form", 0, QApplication::UnicodeUTF8));
        lbIMGFondo->setText(QString());
        lbUnit3->setText(QApplication::translate("F4", "    UNIT3", 0, QApplication::UnicodeUTF8));
        lbValDES->setText(QApplication::translate("F4", "SIN APAGADOS", 0, QApplication::UnicodeUTF8));
        lbAux_1->setText(QApplication::translate("F4", "N\302\272", 0, QApplication::UnicodeUTF8));
        lbApagado->setText(QApplication::translate("F4", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">PRIMER</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">APAGADO</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbAux_2->setText(QApplication::translate("F4", "Descripci\303\263n", 0, QApplication::UnicodeUTF8));
        lbValNUM->setText(QApplication::translate("F4", "0", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("F4", "IMP PANT", 0, QApplication::UnicodeUTF8));
        lbTitulo_1->setText(QApplication::translate("F4", "APAGADO DE EMERGENCIA (N\303\232CLEO)", 0, QApplication::UnicodeUTF8));
        lbTexto_1->setText(QApplication::translate("F4", "N\303\232CLEO:L\303\223GICA SEGUNDO ANILLO", 0, QApplication::UnicodeUTF8));
        aLet_1->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_2->setText(QApplication::translate("F4", "N\303\232CLEO:T3 A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_2->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE002_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_3->setText(QApplication::translate("F4", "N\303\232CLEO:N2/NSD A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_3->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE003_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_4->setText(QApplication::translate("F4", "N\303\232CLEO:PS3 A&B SENSORES ALTA DIF", 0, QApplication::UnicodeUTF8));
        aLet_4->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE004_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_5->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE005_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_5->setText(QApplication::translate("F4", "N\303\232CLEO:PS3 A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_6->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE006_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_6->setText(QApplication::translate("F4", "N\303\232CLEO:DETECTORES LLAMA A&B FALLARON", 0, QApplication::UnicodeUTF8));
        lbTexto_7->setText(QApplication::translate("F4", "N\303\232CLEO:APAGADO DE LLAMA", 0, QApplication::UnicodeUTF8));
        aLet_7->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE007_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_8->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE008_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_8->setText(QApplication::translate("F4", "N\303\232CLEO:SOBRE VEL ROTOR AP", 0, QApplication::UnicodeUTF8));
        aLet_9->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE009_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_9->setText(QApplication::translate("F4", "N\303\232CLEO:SOBRE VEL ROTOR BP", 0, QApplication::UnicodeUTF8));
        lbTexto_10->setText(QApplication::translate("F4", "N\303\232CLEO:T48 BAJA TEMP", 0, QApplication::UnicodeUTF8));
        aLet_10->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE010_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_11->setText(QApplication::translate("F4", "N\303\232CLEO:T48 SOBRE TEMP D/ARRANQUE", 0, QApplication::UnicodeUTF8));
        aLet_11->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE011_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_12->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE012_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_12->setText(QApplication::translate("F4", "N\303\232CLEO:REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_13->setText(QApplication::translate("F4", "N\303\232CLEO:T48 SOBRE TEMP MODO B", 0, QApplication::UnicodeUTF8));
        aLet_13->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_CORE013_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_14->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_14->setText(QApplication::translate("F4", "N\303\232CLEO:FMVP SOLUCIONADOR A/B ALTA DIF", 0, QApplication::UnicodeUTF8));
        lbTexto_15->setText(QApplication::translate("F4", "N\303\232CLEO:FMVP SOLUCIONADOR A/B FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_15->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS002_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_16->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS003_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_16->setText(QApplication::translate("F4", "N\303\232CLEO:FMVP DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        aLet_17->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS004_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_17->setText(QApplication::translate("F4", "N\303\232CLEO:FMVP IMPULSOR FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_18->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS005_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_18->setText(QApplication::translate("F4", "N\303\232CLEO:FMVl RESOLVEDOR A/B AL DIF", 0, QApplication::UnicodeUTF8));
        aLet_19->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS006_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_19->setText(QApplication::translate("F4", "N\303\232CLEO:FMVl SOLUCIONADOR A/B FALL\303\223", 0, QApplication::UnicodeUTF8));
        lbTexto_58->setText(QApplication::translate("F4", "N\303\232CLEO:FMVl DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        aLet_58->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS007_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_59->setText(QApplication::translate("F4", "N\303\232CLEO:FMVl IMPULSOR FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_59->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS008_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_60->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS009_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_60->setText(QApplication::translate("F4", "N\303\232CLEO:FMVO RESLVEDOR A/B AL DIF", 0, QApplication::UnicodeUTF8));
        aLet_61->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS010_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_61->setText(QApplication::translate("F4", "N\303\232CLEO:FMVO SOLUCIONADOR A/B FALL\303\223", 0, QApplication::UnicodeUTF8));
        lbTexto_62->setText(QApplication::translate("F4", "N\303\232CLEO:FMVO DEMANDA VS RETROAL ERR", 0, QApplication::UnicodeUTF8));
        aLet_62->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS011_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_63->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS012_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_63->setText(QApplication::translate("F4", "N\303\232CLEO:FMVO IMPULSOR FALL\303\223", 0, QApplication::UnicodeUTF8));
        lbTitulo_5->setText(QApplication::translate("F4", "DETENCIONES NORMALES", 0, QApplication::UnicodeUTF8));
        lbTitulo_6->setText(QApplication::translate("F4", "APAGADO DE EMERGENCIA (2\302\272 ANILLO)", 0, QApplication::UnicodeUTF8));
        lbTexto_39->setText(QApplication::translate("F4", "N\303\232CLEO:INR FMV S/N DESIGUAL", 0, QApplication::UnicodeUTF8));
        aLet_39->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS026_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_40->setText(QApplication::translate("F4", "N\303\232CLEO:OTR FMV S/N DESIGUAL", 0, QApplication::UnicodeUTF8));
        aLet_40->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS027_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_41->setText(QApplication::translate("F4", "N\303\232CLEO:GMVP IMPULSOR COM\303\232N FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_41->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS028_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_42->setText(QApplication::translate("F4", "N\303\232CLEO:GMVI IMPULSOR COM\303\232N FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_42->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS029_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_43->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS030_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_43->setText(QApplication::translate("F4", "N\303\232CLEO:GMVO IMPULSOR COM\303\232N FALL\303\223", 0, QApplication::UnicodeUTF8));
        aLet_44->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS031_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_44->setText(QApplication::translate("F4", "N\303\232CLEO:GP1 PRES PILOR SUMIN GAS ALTA", 0, QApplication::UnicodeUTF8));
        lbTexto_45->setText(QApplication::translate("F4", "N\303\232CLEO:GP1 PRES INTER SUMIN GAS ALTA", 0, QApplication::UnicodeUTF8));
        aLet_45->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS032_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_46->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS033_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_46->setText(QApplication::translate("F4", "N\303\232CLEO:GP1 PRES EXTERN SUMIN GAS ALTA", 0, QApplication::UnicodeUTF8));
        aLet_47->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS034_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_47->setText(QApplication::translate("F4", "N\303\232CLEO:SD_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_48->setText(QApplication::translate("F4", "N\303\232CLEO:SD_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_48->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS035_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_49->setText(QApplication::translate("F4", "N\303\232CLEO:SD_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_49->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS036_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_50->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS037_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_50->setText(QApplication::translate("F4", "N\303\232CLEO:SD_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_51->setText(QApplication::translate("F4", "N\303\232CLEO:SD_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_51->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS038_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_52->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS039_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_52->setText(QApplication::translate("F4", "N\303\232CLEO:SD_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_53->setText(QApplication::translate("F4", "N\303\232CLEO:SD_FMS REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_53->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_FMS040_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_54->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_54->setText(QApplication::translate("F4", "SEC:XNSD FALLO EN SEPARARSE", 0, QApplication::UnicodeUTF8));
        aLet_55->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR002_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_55->setText(QApplication::translate("F4", "SEC:XN25 FALL\303\223 EN HACER N\303\232CLEO", 0, QApplication::UnicodeUTF8));
        aLet_56->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR004_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_56->setText(QApplication::translate("F4", "SEC:FALL\303\223 EN ENCENDER", 0, QApplication::UnicodeUTF8));
        aLet_57->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR005_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_57->setText(QApplication::translate("F4", "SEC:XN25 FALLA DE ACC A 6050", 0, QApplication::UnicodeUTF8));
        aLet_64->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR006_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_64->setText(QApplication::translate("F4", "SEC:POS VALV DESAG\303\234E COMBUSTOR", 0, QApplication::UnicodeUTF8));
        lbTitulo_7->setText(QApplication::translate("F4", "APAGADO DE EMERGENCIA (2\302\272 ANILLO)", 0, QApplication::UnicodeUTF8));
        lbTitulo_8->setText(QApplication::translate("F4", "APAGADO DE EMERGENCIA SIN MOTOR (N\303\232CLEO)", 0, QApplication::UnicodeUTF8));
        lbTexto_65->setText(QApplication::translate("F4", "SEC:ACEITE LUB TURBINA BAJA", 0, QApplication::UnicodeUTF8));
        aLet_65->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR009_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_66->setText(QApplication::translate("F4", "SEC:XN25 FALLA DE ACC A 4600", 0, QApplication::UnicodeUTF8));
        aLet_66->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR010_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_67->setText(QApplication::translate("F4", "SEC:N1N33 FALLA NODO", 0, QApplication::UnicodeUTF8));
        aLet_67->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR012_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_68->setText(QApplication::translate("F4", "SEC:N1N34 FALLA NODO", 0, QApplication::UnicodeUTF8));
        aLet_68->setId(QApplication::translate("F4", "p_Fix32_THISNODE_ABRTST011_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_69->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR015_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_69->setText(QApplication::translate("F4", "SEC:PRES COMB GAS ALTA ALTA", 0, QApplication::UnicodeUTF8));
        aLet_70->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_GEN001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_70->setText(QApplication::translate("F4", "SEC:VALV BLOCK NO ABIERTO AL ARRANCAR", 0, QApplication::UnicodeUTF8));
        lbTexto_71->setText(QApplication::translate("F4", "SEC:INTERRUPTOR GENERADOR FALLA", 0, QApplication::UnicodeUTF8));
        aLet_71->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_MSTR014_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_72->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_GEN003_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_72->setText(QApplication::translate("F4", "SEC:GEN 86 ACTIVADO LOCAL", 0, QApplication::UnicodeUTF8));
        aLet_73->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_GEN005_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_73->setText(QApplication::translate("F4", "SEC:GEN 86 ACTIVADO (REMOTO)", 0, QApplication::UnicodeUTF8));
        lbTexto_74->setText(QApplication::translate("F4", "N\303\232CLEO:N2 SOBRE VELO BLOQUEO", 0, QApplication::UnicodeUTF8));
        aLet_74->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_GEN002_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_75->setText(QApplication::translate("F4", "SEC:N3N42 FALLA NODO", 0, QApplication::UnicodeUTF8));
        aLet_75->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SD_GEN006_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_76->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SDN_CORE001_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_76->setText(QApplication::translate("F4", "SEC:ESD DE GCP", 0, QApplication::UnicodeUTF8));
        lbTexto_77->setText(QApplication::translate("F4", "N\303\232CLEO:L\303\223GICO SEGUNDO ANILLO", 0, QApplication::UnicodeUTF8));
        aLet_77->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SDN_CORE002_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_78->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SDN_CORE003_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_78->setText(QApplication::translate("F4", "N\303\232CLEO:BP FLECHA FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_79->setText(QApplication::translate("F4", "N\303\232CLEO:N25 A&B SENSORES FALLARON", 0, QApplication::UnicodeUTF8));
        aLet_79->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SDN_CORE004_F_CV", 0, QApplication::UnicodeUTF8));
        aLet_80->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SDN_CORE007_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_80->setText(QApplication::translate("F4", "N\303\232CLEO:PS2 CALADA DETECTADA", 0, QApplication::UnicodeUTF8));
        lbTexto_81->setText(QApplication::translate("F4", "SEC:XN25 FALL\303\223 EN HACER N\303\232CLEO", 0, QApplication::UnicodeUTF8));
        lbTexto_82->setText(QApplication::translate("F4", "SEC:FALL\303\223 EN ENCENDER", 0, QApplication::UnicodeUTF8));
        aLet_83->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SDN_CORE005_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_83->setText(QApplication::translate("F4", "N\303\232CLEO:PRES ACEITe LUB BAJA", 0, QApplication::UnicodeUTF8));
        aLet_84->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SDN_CORE006_F_CV", 0, QApplication::UnicodeUTF8));
        lbTexto_84->setText(QApplication::translate("F4", "N\303\232CLEO:PLUB SENSOR FALL\303\223", 0, QApplication::UnicodeUTF8));
        lbTexto_85->setText(QApplication::translate("F4", "N\303\232CLEO:SDN_N\303\232CLEO REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        aLet_85->setId(QApplication::translate("F4", "p_Fix32_THISNODE_SDN_CORE008_F_CV", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class F4: public Ui_F4 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_F4_H
