/********************************************************************************
** Form generated from reading UI file 'inet_ai_6.ui'
**
** Created: Mon 16. Dec 20:20:26 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_INET_AI_6_H
#define UI_INET_AI_6_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_Inet_AI_6
{
public:
    QFrame *frame;
    WLabel *label_2;
    WLabel *lbNumDes_20;
    WLabel *lbUni_12;
    WLabel *lbTit_24;
    WLabel *lbUni_11;
    WLabel *lbNum_9;
    WLabel *lbNum_20;
    WLabel *lbNumDes_2;
    WLabel *lbNumDes_7;
    WLabel *lbNum_6;
    WLabel *lbTit_3;
    WLabel *lbNumDes_3;
    WLabel *lbTit_5;
    WLabel *lbNum_11;
    WLabel *lbNumDes_11;
    WLabel *lbTit_12;
    WLabel *lbUni_8;
    WLabel *lbNumDes_18;
    WLabel *lbTit_21;
    WLabel *lbUni_3;
    WLabel *lbTit_2;
    WLabel *lbUni_14;
    WLabel *lbUni_7;
    WLabel *lbTit_9;
    WLabel *lbNumDes_10;
    WLabel *lbNumDes_8;
    WLabel *lbNum_23;
    WLabel *lbTit_11;
    WLabel *lbNumDes_1;
    WLabel *lbNum_2;
    WLabel *lbNumDes_17;
    WLabel *lbNum_21;
    WLabel *lbUni_15;
    WLabel *lbNum_4;
    WLabel *lbNum_7;
    WLabel *lbNumDes_24;
    WLabel *lbNum_10;
    WLabel *lbTit_10;
    WLabel *lbNum_18;
    WLabel *lbUni_9;
    WLabel *lbTit_6;
    WLabel *lbTit_13;
    WLabel *lbNum_3;
    WLabel *lbUni_5;
    WLabel *lbNumDes_9;
    WLabel *lbNum_5;
    WLabel *lbTit_1;
    QPushButton *btCerrar;
    WLabel *lbUni_19;
    WLabel *lbUni_6;
    WLabel *lbUni_10;
    WLabel *lbTit_4;
    WLabel *lbUni_2;
    WLabel *lbNum_8;
    WLabel *lbUni_17;
    QFrame *frame_2;
    WLabel *lbIP;
    WLabel *lbUni_1;
    WLabel *lbNumDes_6;
    WLabel *lbNumDes_12;
    WLabel *lbNum_12;
    WLabel *lbNumDes_4;
    WLabel *lbTit_7;
    WLabel *lbTit_18;
    WLabel *lbNumDes_5;
    WLabel *lbUni_4;
    WLabel *lbNum_1;
    WLabel *lbTit_8;
    QLabel *lbFondo;

    void setupUi(QWidget *Inet_AI_6)
    {
        if (Inet_AI_6->objectName().isEmpty())
            Inet_AI_6->setObjectName(QString::fromUtf8("Inet_AI_6"));
        Inet_AI_6->resize(485, 430);
        Inet_AI_6->setMinimumSize(QSize(485, 430));
        Inet_AI_6->setMaximumSize(QSize(485, 430));
        QFont font;
        font.setFamily(QString::fromUtf8("Verdana"));
        Inet_AI_6->setFont(font);
        Inet_AI_6->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        frame = new QFrame(Inet_AI_6);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(2, 17, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        label_2 = new WLabel(frame);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(62, 4, 400, 22));
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setPointSize(9);
        font1.setBold(true);
        font1.setWeight(75);
        label_2->setFont(font1);
        label_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_20 = new WLabel(Inet_AI_6);
        lbNumDes_20->setObjectName(QString::fromUtf8("lbNumDes_20"));
        lbNumDes_20->setGeometry(QRect(366, 350, 50, 16));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setPointSize(8);
        font2.setBold(true);
        font2.setWeight(75);
        lbNumDes_20->setFont(font2);
        lbNumDes_20->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbUni_12 = new WLabel(Inet_AI_6);
        lbUni_12->setObjectName(QString::fromUtf8("lbUni_12"));
        lbUni_12->setGeometry(QRect(420, 270, 51, 16));
        lbUni_12->setStyleSheet(QString::fromUtf8(""));
        lbUni_12->setFont(font2);
        lbUni_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_24 = new WLabel(Inet_AI_6);
        lbTit_24->setObjectName(QString::fromUtf8("lbTit_24"));
        lbTit_24->setGeometry(QRect(30, 290, 340, 16));
        lbTit_24->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTit_24->setFont(font2);
        lbTit_24->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_11 = new WLabel(Inet_AI_6);
        lbUni_11->setObjectName(QString::fromUtf8("lbUni_11"));
        lbUni_11->setGeometry(QRect(420, 250, 51, 16));
        lbUni_11->setStyleSheet(QString::fromUtf8(""));
        lbUni_11->setFont(font2);
        lbUni_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_9 = new WLabel(Inet_AI_6);
        lbNum_9->setObjectName(QString::fromUtf8("lbNum_9"));
        lbNum_9->setGeometry(QRect(5, 210, 21, 16));
        lbNum_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setBold(true);
        font3.setWeight(75);
        lbNum_9->setFont(font3);
        lbNum_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_20 = new WLabel(Inet_AI_6);
        lbNum_20->setObjectName(QString::fromUtf8("lbNum_20"));
        lbNum_20->setGeometry(QRect(5, 290, 21, 16));
        lbNum_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_20->setFont(font3);
        lbNum_20->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_2 = new WLabel(Inet_AI_6);
        lbNumDes_2->setObjectName(QString::fromUtf8("lbNumDes_2"));
        lbNumDes_2->setGeometry(QRect(366, 74, 50, 16));
        lbNumDes_2->setFont(font2);
        lbNumDes_2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumDes_7 = new WLabel(Inet_AI_6);
        lbNumDes_7->setObjectName(QString::fromUtf8("lbNumDes_7"));
        lbNumDes_7->setGeometry(QRect(366, 173, 50, 16));
        lbNumDes_7->setFont(font2);
        lbNumDes_7->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_6 = new WLabel(Inet_AI_6);
        lbNum_6->setObjectName(QString::fromUtf8("lbNum_6"));
        lbNum_6->setGeometry(QRect(5, 154, 21, 16));
        lbNum_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_6->setFont(font3);
        lbNum_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_3 = new WLabel(Inet_AI_6);
        lbTit_3->setObjectName(QString::fromUtf8("lbTit_3"));
        lbTit_3->setGeometry(QRect(30, 94, 340, 16));
        lbTit_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTit_3->setFont(font2);
        lbTit_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_3 = new WLabel(Inet_AI_6);
        lbNumDes_3->setObjectName(QString::fromUtf8("lbNumDes_3"));
        lbNumDes_3->setGeometry(QRect(366, 94, 50, 16));
        lbNumDes_3->setFont(font2);
        lbNumDes_3->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbTit_5 = new WLabel(Inet_AI_6);
        lbTit_5->setObjectName(QString::fromUtf8("lbTit_5"));
        lbTit_5->setGeometry(QRect(30, 135, 340, 16));
        lbTit_5->setFont(font2);
        lbTit_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_11 = new WLabel(Inet_AI_6);
        lbNum_11->setObjectName(QString::fromUtf8("lbNum_11"));
        lbNum_11->setGeometry(QRect(5, 250, 21, 16));
        lbNum_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_11->setFont(font3);
        lbNum_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_11 = new WLabel(Inet_AI_6);
        lbNumDes_11->setObjectName(QString::fromUtf8("lbNumDes_11"));
        lbNumDes_11->setGeometry(QRect(366, 250, 50, 16));
        lbNumDes_11->setFont(font2);
        lbNumDes_11->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbTit_12 = new WLabel(Inet_AI_6);
        lbTit_12->setObjectName(QString::fromUtf8("lbTit_12"));
        lbTit_12->setGeometry(QRect(30, 270, 340, 16));
        lbTit_12->setFont(font2);
        lbTit_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_8 = new WLabel(Inet_AI_6);
        lbUni_8->setObjectName(QString::fromUtf8("lbUni_8"));
        lbUni_8->setGeometry(QRect(420, 190, 51, 16));
        lbUni_8->setStyleSheet(QString::fromUtf8(""));
        lbUni_8->setFont(font2);
        lbUni_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_18 = new WLabel(Inet_AI_6);
        lbNumDes_18->setObjectName(QString::fromUtf8("lbNumDes_18"));
        lbNumDes_18->setGeometry(QRect(366, 330, 50, 16));
        lbNumDes_18->setFont(font2);
        lbNumDes_18->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbTit_21 = new WLabel(Inet_AI_6);
        lbTit_21->setObjectName(QString::fromUtf8("lbTit_21"));
        lbTit_21->setGeometry(QRect(30, 350, 340, 16));
        lbTit_21->setFont(font2);
        lbTit_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_3 = new WLabel(Inet_AI_6);
        lbUni_3->setObjectName(QString::fromUtf8("lbUni_3"));
        lbUni_3->setGeometry(QRect(420, 94, 51, 16));
        lbUni_3->setStyleSheet(QString::fromUtf8(""));
        lbUni_3->setFont(font2);
        lbUni_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_2 = new WLabel(Inet_AI_6);
        lbTit_2->setObjectName(QString::fromUtf8("lbTit_2"));
        lbTit_2->setGeometry(QRect(30, 74, 340, 16));
        lbTit_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTit_2->setFont(font2);
        lbTit_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_14 = new WLabel(Inet_AI_6);
        lbUni_14->setObjectName(QString::fromUtf8("lbUni_14"));
        lbUni_14->setGeometry(QRect(420, 310, 51, 16));
        lbUni_14->setStyleSheet(QString::fromUtf8(""));
        lbUni_14->setFont(font2);
        lbUni_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_7 = new WLabel(Inet_AI_6);
        lbUni_7->setObjectName(QString::fromUtf8("lbUni_7"));
        lbUni_7->setGeometry(QRect(420, 173, 51, 16));
        lbUni_7->setStyleSheet(QString::fromUtf8(""));
        lbUni_7->setFont(font2);
        lbUni_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_9 = new WLabel(Inet_AI_6);
        lbTit_9->setObjectName(QString::fromUtf8("lbTit_9"));
        lbTit_9->setGeometry(QRect(30, 210, 340, 16));
        lbTit_9->setFont(font2);
        lbTit_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_10 = new WLabel(Inet_AI_6);
        lbNumDes_10->setObjectName(QString::fromUtf8("lbNumDes_10"));
        lbNumDes_10->setGeometry(QRect(366, 230, 50, 16));
        lbNumDes_10->setFont(font2);
        lbNumDes_10->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumDes_8 = new WLabel(Inet_AI_6);
        lbNumDes_8->setObjectName(QString::fromUtf8("lbNumDes_8"));
        lbNumDes_8->setGeometry(QRect(366, 190, 50, 16));
        lbNumDes_8->setFont(font2);
        lbNumDes_8->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_23 = new WLabel(Inet_AI_6);
        lbNum_23->setObjectName(QString::fromUtf8("lbNum_23"));
        lbNum_23->setGeometry(QRect(5, 330, 21, 16));
        lbNum_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_23->setFont(font3);
        lbNum_23->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_11 = new WLabel(Inet_AI_6);
        lbTit_11->setObjectName(QString::fromUtf8("lbTit_11"));
        lbTit_11->setGeometry(QRect(30, 250, 340, 16));
        lbTit_11->setFont(font2);
        lbTit_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_1 = new WLabel(Inet_AI_6);
        lbNumDes_1->setObjectName(QString::fromUtf8("lbNumDes_1"));
        lbNumDes_1->setGeometry(QRect(366, 55, 50, 16));
        lbNumDes_1->setFont(font2);
        lbNumDes_1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_2 = new WLabel(Inet_AI_6);
        lbNum_2->setObjectName(QString::fromUtf8("lbNum_2"));
        lbNum_2->setGeometry(QRect(5, 74, 21, 16));
        lbNum_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_2->setFont(font3);
        lbNum_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_17 = new WLabel(Inet_AI_6);
        lbNumDes_17->setObjectName(QString::fromUtf8("lbNumDes_17"));
        lbNumDes_17->setGeometry(QRect(366, 290, 50, 16));
        lbNumDes_17->setFont(font2);
        lbNumDes_17->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_21 = new WLabel(Inet_AI_6);
        lbNum_21->setObjectName(QString::fromUtf8("lbNum_21"));
        lbNum_21->setGeometry(QRect(5, 350, 21, 16));
        lbNum_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_21->setFont(font3);
        lbNum_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_15 = new WLabel(Inet_AI_6);
        lbUni_15->setObjectName(QString::fromUtf8("lbUni_15"));
        lbUni_15->setGeometry(QRect(420, 290, 51, 16));
        lbUni_15->setStyleSheet(QString::fromUtf8(""));
        lbUni_15->setFont(font2);
        lbUni_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_4 = new WLabel(Inet_AI_6);
        lbNum_4->setObjectName(QString::fromUtf8("lbNum_4"));
        lbNum_4->setGeometry(QRect(5, 113, 21, 16));
        lbNum_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_4->setFont(font3);
        lbNum_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_7 = new WLabel(Inet_AI_6);
        lbNum_7->setObjectName(QString::fromUtf8("lbNum_7"));
        lbNum_7->setGeometry(QRect(5, 173, 21, 16));
        lbNum_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_7->setFont(font3);
        lbNum_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_24 = new WLabel(Inet_AI_6);
        lbNumDes_24->setObjectName(QString::fromUtf8("lbNumDes_24"));
        lbNumDes_24->setGeometry(QRect(366, 310, 50, 16));
        lbNumDes_24->setFont(font2);
        lbNumDes_24->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_10 = new WLabel(Inet_AI_6);
        lbNum_10->setObjectName(QString::fromUtf8("lbNum_10"));
        lbNum_10->setGeometry(QRect(5, 230, 21, 16));
        lbNum_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_10->setFont(font3);
        lbNum_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_10 = new WLabel(Inet_AI_6);
        lbTit_10->setObjectName(QString::fromUtf8("lbTit_10"));
        lbTit_10->setGeometry(QRect(30, 230, 340, 16));
        lbTit_10->setFont(font2);
        lbTit_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_18 = new WLabel(Inet_AI_6);
        lbNum_18->setObjectName(QString::fromUtf8("lbNum_18"));
        lbNum_18->setGeometry(QRect(5, 310, 21, 16));
        lbNum_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_18->setFont(font3);
        lbNum_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_9 = new WLabel(Inet_AI_6);
        lbUni_9->setObjectName(QString::fromUtf8("lbUni_9"));
        lbUni_9->setGeometry(QRect(420, 210, 51, 16));
        lbUni_9->setStyleSheet(QString::fromUtf8(""));
        lbUni_9->setFont(font2);
        lbUni_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_6 = new WLabel(Inet_AI_6);
        lbTit_6->setObjectName(QString::fromUtf8("lbTit_6"));
        lbTit_6->setGeometry(QRect(30, 154, 340, 16));
        lbTit_6->setFont(font2);
        lbTit_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_13 = new WLabel(Inet_AI_6);
        lbTit_13->setObjectName(QString::fromUtf8("lbTit_13"));
        lbTit_13->setGeometry(QRect(30, 310, 340, 16));
        lbTit_13->setFont(font2);
        lbTit_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_3 = new WLabel(Inet_AI_6);
        lbNum_3->setObjectName(QString::fromUtf8("lbNum_3"));
        lbNum_3->setGeometry(QRect(5, 94, 21, 16));
        lbNum_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_3->setFont(font3);
        lbNum_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_5 = new WLabel(Inet_AI_6);
        lbUni_5->setObjectName(QString::fromUtf8("lbUni_5"));
        lbUni_5->setGeometry(QRect(420, 135, 51, 16));
        lbUni_5->setStyleSheet(QString::fromUtf8(""));
        lbUni_5->setFont(font2);
        lbUni_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_9 = new WLabel(Inet_AI_6);
        lbNumDes_9->setObjectName(QString::fromUtf8("lbNumDes_9"));
        lbNumDes_9->setGeometry(QRect(366, 210, 50, 16));
        lbNumDes_9->setFont(font2);
        lbNumDes_9->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_5 = new WLabel(Inet_AI_6);
        lbNum_5->setObjectName(QString::fromUtf8("lbNum_5"));
        lbNum_5->setGeometry(QRect(5, 135, 21, 16));
        lbNum_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_5->setFont(font3);
        lbNum_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_1 = new WLabel(Inet_AI_6);
        lbTit_1->setObjectName(QString::fromUtf8("lbTit_1"));
        lbTit_1->setGeometry(QRect(30, 55, 340, 16));
        lbTit_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTit_1->setFont(font2);
        lbTit_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        btCerrar = new QPushButton(Inet_AI_6);
        btCerrar->setObjectName(QString::fromUtf8("btCerrar"));
        btCerrar->setGeometry(QRect(136, 383, 101, 33));
        btCerrar->setFont(font1);
        btCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbUni_19 = new WLabel(Inet_AI_6);
        lbUni_19->setObjectName(QString::fromUtf8("lbUni_19"));
        lbUni_19->setGeometry(QRect(420, 350, 51, 16));
        lbUni_19->setStyleSheet(QString::fromUtf8(""));
        lbUni_19->setFont(font2);
        lbUni_19->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_6 = new WLabel(Inet_AI_6);
        lbUni_6->setObjectName(QString::fromUtf8("lbUni_6"));
        lbUni_6->setGeometry(QRect(420, 154, 51, 16));
        lbUni_6->setStyleSheet(QString::fromUtf8(""));
        lbUni_6->setFont(font2);
        lbUni_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_10 = new WLabel(Inet_AI_6);
        lbUni_10->setObjectName(QString::fromUtf8("lbUni_10"));
        lbUni_10->setGeometry(QRect(420, 230, 51, 16));
        lbUni_10->setStyleSheet(QString::fromUtf8(""));
        lbUni_10->setFont(font2);
        lbUni_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_4 = new WLabel(Inet_AI_6);
        lbTit_4->setObjectName(QString::fromUtf8("lbTit_4"));
        lbTit_4->setGeometry(QRect(30, 113, 340, 16));
        lbTit_4->setFont(font2);
        lbTit_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_2 = new WLabel(Inet_AI_6);
        lbUni_2->setObjectName(QString::fromUtf8("lbUni_2"));
        lbUni_2->setGeometry(QRect(420, 74, 51, 16));
        lbUni_2->setStyleSheet(QString::fromUtf8(""));
        lbUni_2->setFont(font2);
        lbUni_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_8 = new WLabel(Inet_AI_6);
        lbNum_8->setObjectName(QString::fromUtf8("lbNum_8"));
        lbNum_8->setGeometry(QRect(5, 190, 21, 16));
        lbNum_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_8->setFont(font3);
        lbNum_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_17 = new WLabel(Inet_AI_6);
        lbUni_17->setObjectName(QString::fromUtf8("lbUni_17"));
        lbUni_17->setGeometry(QRect(420, 330, 51, 16));
        lbUni_17->setStyleSheet(QString::fromUtf8(""));
        lbUni_17->setFont(font2);
        lbUni_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame_2 = new QFrame(Inet_AI_6);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(0, 0, 485, 16));
        frame_2->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frame_2->setFrameShape(QFrame::Panel);
        frame_2->setFrameShadow(QFrame::Raised);
        frame_2->setLineWidth(0);
        lbIP = new WLabel(frame_2);
        lbIP->setObjectName(QString::fromUtf8("lbIP"));
        lbIP->setGeometry(QRect(3, 0, 101, 16));
        lbIP->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 110, 195);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(74, 110, 195);"));
        QFont font4;
        font4.setPointSize(9);
        font4.setBold(true);
        font4.setWeight(75);
        lbIP->setFont(font4);
        lbIP->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbUni_1 = new WLabel(Inet_AI_6);
        lbUni_1->setObjectName(QString::fromUtf8("lbUni_1"));
        lbUni_1->setGeometry(QRect(420, 55, 50, 16));
        lbUni_1->setStyleSheet(QString::fromUtf8(""));
        lbUni_1->setFont(font2);
        lbUni_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_6 = new WLabel(Inet_AI_6);
        lbNumDes_6->setObjectName(QString::fromUtf8("lbNumDes_6"));
        lbNumDes_6->setGeometry(QRect(366, 154, 50, 16));
        lbNumDes_6->setFont(font2);
        lbNumDes_6->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumDes_12 = new WLabel(Inet_AI_6);
        lbNumDes_12->setObjectName(QString::fromUtf8("lbNumDes_12"));
        lbNumDes_12->setGeometry(QRect(366, 270, 50, 16));
        lbNumDes_12->setFont(font2);
        lbNumDes_12->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNum_12 = new WLabel(Inet_AI_6);
        lbNum_12->setObjectName(QString::fromUtf8("lbNum_12"));
        lbNum_12->setGeometry(QRect(5, 270, 21, 16));
        lbNum_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_12->setFont(font3);
        lbNum_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_4 = new WLabel(Inet_AI_6);
        lbNumDes_4->setObjectName(QString::fromUtf8("lbNumDes_4"));
        lbNumDes_4->setGeometry(QRect(366, 113, 50, 16));
        lbNumDes_4->setFont(font2);
        lbNumDes_4->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbTit_7 = new WLabel(Inet_AI_6);
        lbTit_7->setObjectName(QString::fromUtf8("lbTit_7"));
        lbTit_7->setGeometry(QRect(30, 173, 340, 16));
        lbTit_7->setFont(font2);
        lbTit_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_18 = new WLabel(Inet_AI_6);
        lbTit_18->setObjectName(QString::fromUtf8("lbTit_18"));
        lbTit_18->setGeometry(QRect(30, 330, 340, 16));
        lbTit_18->setFont(font2);
        lbTit_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumDes_5 = new WLabel(Inet_AI_6);
        lbNumDes_5->setObjectName(QString::fromUtf8("lbNumDes_5"));
        lbNumDes_5->setGeometry(QRect(366, 135, 50, 16));
        lbNumDes_5->setFont(font2);
        lbNumDes_5->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbUni_4 = new WLabel(Inet_AI_6);
        lbUni_4->setObjectName(QString::fromUtf8("lbUni_4"));
        lbUni_4->setGeometry(QRect(420, 113, 51, 16));
        lbUni_4->setStyleSheet(QString::fromUtf8(""));
        lbUni_4->setFont(font2);
        lbUni_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNum_1 = new WLabel(Inet_AI_6);
        lbNum_1->setObjectName(QString::fromUtf8("lbNum_1"));
        lbNum_1->setGeometry(QRect(5, 55, 21, 16));
        lbNum_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_1->setFont(font3);
        lbNum_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbTit_8 = new WLabel(Inet_AI_6);
        lbTit_8->setObjectName(QString::fromUtf8("lbTit_8"));
        lbTit_8->setGeometry(QRect(30, 190, 340, 16));
        lbTit_8->setFont(font2);
        lbTit_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbFondo = new QLabel(Inet_AI_6);
        lbFondo->setObjectName(QString::fromUtf8("lbFondo"));
        lbFondo->setGeometry(QRect(0, 0, 485, 431));
        lbFondo->setMinimumSize(QSize(485, 431));
        lbFondo->setMaximumSize(QSize(485, 431));
        lbFondo->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbFondo->setFrameShape(QFrame::Box);
        lbFondo->setFrameShadow(QFrame::Sunken);
        lbFondo->raise();
        frame->raise();
        lbNumDes_20->raise();
        lbUni_12->raise();
        lbTit_24->raise();
        lbUni_11->raise();
        lbNum_9->raise();
        lbNum_20->raise();
        lbNumDes_2->raise();
        lbNumDes_7->raise();
        lbNum_6->raise();
        lbTit_3->raise();
        lbNumDes_3->raise();
        lbTit_5->raise();
        lbNum_11->raise();
        lbNumDes_11->raise();
        lbTit_12->raise();
        lbUni_8->raise();
        lbNumDes_18->raise();
        lbTit_21->raise();
        lbUni_3->raise();
        lbTit_2->raise();
        lbUni_14->raise();
        lbUni_7->raise();
        lbTit_9->raise();
        lbNumDes_10->raise();
        lbNumDes_8->raise();
        lbNum_23->raise();
        lbTit_11->raise();
        lbNumDes_1->raise();
        lbNum_2->raise();
        lbNumDes_17->raise();
        lbNum_21->raise();
        lbUni_15->raise();
        lbNum_4->raise();
        lbNum_7->raise();
        lbNumDes_24->raise();
        lbNum_10->raise();
        lbTit_10->raise();
        lbNum_18->raise();
        lbUni_9->raise();
        lbTit_6->raise();
        lbTit_13->raise();
        lbNum_3->raise();
        lbUni_5->raise();
        lbNumDes_9->raise();
        lbNum_5->raise();
        lbTit_1->raise();
        btCerrar->raise();
        lbUni_19->raise();
        lbUni_6->raise();
        lbUni_10->raise();
        lbTit_4->raise();
        lbUni_2->raise();
        lbNum_8->raise();
        lbUni_17->raise();
        frame_2->raise();
        lbUni_1->raise();
        lbNumDes_6->raise();
        lbNumDes_12->raise();
        lbNum_12->raise();
        lbNumDes_4->raise();
        lbTit_7->raise();
        lbTit_18->raise();
        lbNumDes_5->raise();
        lbUni_4->raise();
        lbNum_1->raise();
        lbTit_8->raise();

        retranslateUi(Inet_AI_6);

        QMetaObject::connectSlotsByName(Inet_AI_6);
    } // setupUi

    void retranslateUi(QWidget *Inet_AI_6)
    {
        Inet_AI_6->setWindowTitle(QApplication::translate("Inet_AI_6", "Inet_AI_6", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Inet_AI_6", "NODE - N232 - N1", 0, QApplication::UnicodeUTF8));
        lbNumDes_20->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbUni_12->setText(QApplication::translate("Inet_AI_6", "NALM", 0, QApplication::UnicodeUTF8));
        lbTit_24->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbUni_11->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbNum_9->setText(QApplication::translate("Inet_AI_6", "9", 0, QApplication::UnicodeUTF8));
        lbNum_20->setText(QApplication::translate("Inet_AI_6", "13", 0, QApplication::UnicodeUTF8));
        lbNumDes_2->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNumDes_7->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNum_6->setText(QApplication::translate("Inet_AI_6", "6", 0, QApplication::UnicodeUTF8));
        lbTit_3->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDes_3->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbTit_5->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNum_11->setText(QApplication::translate("Inet_AI_6", "11", 0, QApplication::UnicodeUTF8));
        lbNumDes_11->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbTit_12->setText(QApplication::translate("Inet_AI_6", "FILTRO ACEITE LUB GEN P/D ALTA", 0, QApplication::UnicodeUTF8));
        lbUni_8->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_18->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbTit_21->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbUni_3->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbTit_2->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbUni_14->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbUni_7->setText(QApplication::translate("Inet_AI_6", "NALM", 0, QApplication::UnicodeUTF8));
        lbTit_9->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDes_10->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNumDes_8->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNum_23->setText(QApplication::translate("Inet_AI_6", "15", 0, QApplication::UnicodeUTF8));
        lbTit_11->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDes_1->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNum_2->setText(QApplication::translate("Inet_AI_6", "2", 0, QApplication::UnicodeUTF8));
        lbNumDes_17->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNum_21->setText(QApplication::translate("Inet_AI_6", "16", 0, QApplication::UnicodeUTF8));
        lbUni_15->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbNum_4->setText(QApplication::translate("Inet_AI_6", "4", 0, QApplication::UnicodeUTF8));
        lbNum_7->setText(QApplication::translate("Inet_AI_6", "7", 0, QApplication::UnicodeUTF8));
        lbNumDes_24->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNum_10->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbTit_10->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNum_18->setText(QApplication::translate("Inet_AI_6", "14", 0, QApplication::UnicodeUTF8));
        lbUni_9->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbTit_6->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbTit_13->setText(QApplication::translate("Inet_AI_6", "DIF PRES GEN A TURB", 0, QApplication::UnicodeUTF8));
        lbNum_3->setText(QApplication::translate("Inet_AI_6", "3", 0, QApplication::UnicodeUTF8));
        lbUni_5->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_9->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNum_5->setText(QApplication::translate("Inet_AI_6", "5", 0, QApplication::UnicodeUTF8));
        lbTit_1->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        btCerrar->setText(QApplication::translate("Inet_AI_6", "CERRAR", 0, QApplication::UnicodeUTF8));
        lbUni_19->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbUni_6->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbUni_10->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbTit_4->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbUni_2->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbNum_8->setText(QApplication::translate("Inet_AI_6", "8", 0, QApplication::UnicodeUTF8));
        lbUni_17->setText(QString());
        lbIP->setText(QApplication::translate("Inet_AI_6", "LNET_D1.grf", 0, QApplication::UnicodeUTF8));
        lbUni_1->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_6->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNumDes_12->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbNum_12->setText(QApplication::translate("Inet_AI_6", "12", 0, QApplication::UnicodeUTF8));
        lbNumDes_4->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbTit_7->setText(QApplication::translate("Inet_AI_6", "TEMP BAJ TANQUE ACEITE LUB GEN\\", 0, QApplication::UnicodeUTF8));
        lbTit_18->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDes_5->setText(QApplication::translate("Inet_AI_6", "00", 0, QApplication::UnicodeUTF8));
        lbUni_4->setText(QApplication::translate("Inet_AI_6", "10", 0, QApplication::UnicodeUTF8));
        lbNum_1->setText(QApplication::translate("Inet_AI_6", "1", 0, QApplication::UnicodeUTF8));
        lbTit_8->setText(QApplication::translate("Inet_AI_6", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbFondo->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Inet_AI_6: public Ui_Inet_AI_6 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_INET_AI_6_H
