/********************************************************************************
** Form generated from reading UI file 'lnet_dl2.ui'
**
** Created: Wed 11. Dec 20:17:14 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LNET_DL2_H
#define UI_LNET_DL2_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_LNET_Dl2
{
public:
    QFrame *frame_3;
    WLabel *lbLnetT_2;
    QFrame *frame_4;
    WLabel *lbLnetT_3;
    WLabel *lbLnetT;
    WLabel *lbNodRTD;
    QFrame *frame;
    WLabel *lbNodeT_1;
    WLabel *lbNode_1;
    WLabel *lbNodeU_1;
    QPushButton *btCerrar;
    WLabel *lbNumNode_1;
    WLabel *lbNumNode_2;
    WLabel *lbNodeT_2;
    WLabel *lbNodeU_2;
    WLabel *lbNode_2;
    WLabel *lbNodeU_3;
    WLabel *lbNodeT_3;
    WLabel *lbNode_3;
    WLabel *lbNumNode_3;
    WLabel *lbNumNode_4;
    WLabel *lbNodeT_4;
    WLabel *lbNodeU_4;
    WLabel *lbNode_4;
    WLabel *lbNumNode_5;
    WLabel *lbNode_5;
    WLabel *lbNodeU_5;
    WLabel *lbNodeT_5;
    WLabel *lbNumNode_6;
    WLabel *lbNode_6;
    WLabel *lbNodeT_6;
    WLabel *lbNodeU_6;
    WLabel *lbNodeT_7;
    WLabel *lbNode_7;
    WLabel *lbNumNode_7;
    WLabel *lbNodeU_7;
    WLabel *lbNumNode_8;
    WLabel *lbNodeT_8;
    WLabel *lbNode_8;
    WLabel *lbNodeU_8;
    WLabel *lbNumNode_9;
    WLabel *lbNodeU_9;
    WLabel *lbNodeT_9;
    WLabel *lbNode_9;
    WLabel *lbNumNode_10;
    WLabel *lbNodeU_10;
    WLabel *lbNode_10;
    WLabel *lbNodeT_10;
    WLabel *lbNumNode_11;
    WLabel *lbNodeT_11;
    WLabel *lbNode_11;
    WLabel *lbNodeU_11;
    WLabel *lbNumNode_12;
    WLabel *lbNodeT_12;
    WLabel *lbNodeU_12;
    WLabel *lbNode_12;
    WLabel *lbNumNode_13;
    WLabel *lbNode_13;
    WLabel *lbNodeU_13;
    WLabel *lbNodeT_13;
    WLabel *lbNodeU_14;
    WLabel *lbNode_14;
    WLabel *lbNumNode_14;
    WLabel *lbNodeT_14;
    WLabel *lbNumNode_15;
    WLabel *lbNodeU_15;
    WLabel *lbNode_15;
    WLabel *lbNodeT_15;
    WLabel *lbNumNode_16;
    WLabel *lbNodeT_16;
    WLabel *lbNode_16;
    WLabel *lbNodeU_16;
    QLabel *lbFondo;

    void setupUi(QWidget *LNET_Dl2)
    {
        if (LNET_Dl2->objectName().isEmpty())
            LNET_Dl2->setObjectName(QString::fromUtf8("LNET_Dl2"));
        LNET_Dl2->resize(485, 425);
        LNET_Dl2->setMinimumSize(QSize(485, 425));
        LNET_Dl2->setMaximumSize(QSize(485, 425));
        LNET_Dl2->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        frame_3 = new QFrame(LNET_Dl2);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(0, 0, 485, 12));
        frame_3->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frame_3->setFrameShape(QFrame::Panel);
        frame_3->setFrameShadow(QFrame::Raised);
        frame_3->setLineWidth(0);
        lbLnetT_2 = new WLabel(frame_3);
        lbLnetT_2->setObjectName(QString::fromUtf8("lbLnetT_2"));
        lbLnetT_2->setGeometry(QRect(0, 0, 81, 20));
        lbLnetT_2->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        QFont font;
        font.setPointSize(5);
        font.setBold(true);
        font.setWeight(75);
        lbLnetT_2->setFont(font);
        lbLnetT_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame_4 = new QFrame(frame_3);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(10, 10, 485, 11));
        frame_4->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frame_4->setFrameShape(QFrame::Panel);
        frame_4->setFrameShadow(QFrame::Raised);
        frame_4->setLineWidth(0);
        lbLnetT_3 = new WLabel(frame_4);
        lbLnetT_3->setObjectName(QString::fromUtf8("lbLnetT_3"));
        lbLnetT_3->setGeometry(QRect(0, 0, 81, 20));
        lbLnetT_3->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        lbLnetT_3->setFont(font);
        lbLnetT_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbLnetT = new WLabel(frame_3);
        lbLnetT->setObjectName(QString::fromUtf8("lbLnetT"));
        lbLnetT->setGeometry(QRect(3, 0, 81, 12));
        lbLnetT->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        lbLnetT->setFont(font);
        lbLnetT->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodRTD = new WLabel(LNET_Dl2);
        lbNodRTD->setObjectName(QString::fromUtf8("lbNodRTD"));
        lbNodRTD->setGeometry(QRect(63, 21, 400, 20));
        lbNodRTD->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        lbNodRTD->setFont(font1);
        lbNodRTD->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame = new QFrame(LNET_Dl2);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 15, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        lbNodeT_1 = new WLabel(LNET_Dl2);
        lbNodeT_1->setObjectName(QString::fromUtf8("lbNodeT_1"));
        lbNodeT_1->setGeometry(QRect(30, 50, 291, 16));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setBold(true);
        font2.setWeight(75);
        lbNodeT_1->setFont(font2);
        lbNodeT_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_1 = new WLabel(LNET_Dl2);
        lbNode_1->setObjectName(QString::fromUtf8("lbNode_1"));
        lbNode_1->setGeometry(QRect(346, 50, 51, 20));
        lbNode_1->setLayoutDirection(Qt::RightToLeft);
        lbNode_1->setFont(font2);
        lbNode_1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_1 = new WLabel(LNET_Dl2);
        lbNodeU_1->setObjectName(QString::fromUtf8("lbNodeU_1"));
        lbNodeU_1->setGeometry(QRect(415, 50, 61, 20));
        lbNodeU_1->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_1->setFont(font2);
        lbNodeU_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        btCerrar = new QPushButton(LNET_Dl2);
        btCerrar->setObjectName(QString::fromUtf8("btCerrar"));
        btCerrar->setGeometry(QRect(134, 374, 101, 31));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        btCerrar->setFont(font3);
        btCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbNumNode_1 = new WLabel(LNET_Dl2);
        lbNumNode_1->setObjectName(QString::fromUtf8("lbNumNode_1"));
        lbNumNode_1->setGeometry(QRect(10, 50, 21, 16));
        lbNumNode_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_1->setFont(font2);
        lbNumNode_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_2 = new WLabel(LNET_Dl2);
        lbNumNode_2->setObjectName(QString::fromUtf8("lbNumNode_2"));
        lbNumNode_2->setGeometry(QRect(10, 70, 21, 16));
        lbNumNode_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_2->setFont(font2);
        lbNumNode_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_2 = new WLabel(LNET_Dl2);
        lbNodeT_2->setObjectName(QString::fromUtf8("lbNodeT_2"));
        lbNodeT_2->setGeometry(QRect(30, 70, 291, 16));
        lbNodeT_2->setFont(font2);
        lbNodeT_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_2 = new WLabel(LNET_Dl2);
        lbNodeU_2->setObjectName(QString::fromUtf8("lbNodeU_2"));
        lbNodeU_2->setGeometry(QRect(415, 70, 61, 20));
        lbNodeU_2->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_2->setFont(font2);
        lbNodeU_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_2 = new WLabel(LNET_Dl2);
        lbNode_2->setObjectName(QString::fromUtf8("lbNode_2"));
        lbNode_2->setGeometry(QRect(346, 70, 51, 20));
        lbNode_2->setLayoutDirection(Qt::RightToLeft);
        lbNode_2->setFont(font2);
        lbNode_2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_3 = new WLabel(LNET_Dl2);
        lbNodeU_3->setObjectName(QString::fromUtf8("lbNodeU_3"));
        lbNodeU_3->setGeometry(QRect(415, 90, 61, 20));
        lbNodeU_3->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_3->setFont(font2);
        lbNodeU_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_3 = new WLabel(LNET_Dl2);
        lbNodeT_3->setObjectName(QString::fromUtf8("lbNodeT_3"));
        lbNodeT_3->setGeometry(QRect(30, 90, 291, 16));
        lbNodeT_3->setFont(font2);
        lbNodeT_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_3 = new WLabel(LNET_Dl2);
        lbNode_3->setObjectName(QString::fromUtf8("lbNode_3"));
        lbNode_3->setGeometry(QRect(346, 90, 51, 20));
        lbNode_3->setLayoutDirection(Qt::RightToLeft);
        lbNode_3->setFont(font2);
        lbNode_3->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_3 = new WLabel(LNET_Dl2);
        lbNumNode_3->setObjectName(QString::fromUtf8("lbNumNode_3"));
        lbNumNode_3->setGeometry(QRect(10, 90, 21, 16));
        lbNumNode_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_3->setFont(font2);
        lbNumNode_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_4 = new WLabel(LNET_Dl2);
        lbNumNode_4->setObjectName(QString::fromUtf8("lbNumNode_4"));
        lbNumNode_4->setGeometry(QRect(10, 110, 21, 16));
        lbNumNode_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_4->setFont(font2);
        lbNumNode_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_4 = new WLabel(LNET_Dl2);
        lbNodeT_4->setObjectName(QString::fromUtf8("lbNodeT_4"));
        lbNodeT_4->setGeometry(QRect(30, 110, 291, 16));
        lbNodeT_4->setFont(font2);
        lbNodeT_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_4 = new WLabel(LNET_Dl2);
        lbNodeU_4->setObjectName(QString::fromUtf8("lbNodeU_4"));
        lbNodeU_4->setGeometry(QRect(415, 110, 61, 20));
        lbNodeU_4->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_4->setFont(font2);
        lbNodeU_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_4 = new WLabel(LNET_Dl2);
        lbNode_4->setObjectName(QString::fromUtf8("lbNode_4"));
        lbNode_4->setGeometry(QRect(346, 110, 51, 20));
        lbNode_4->setLayoutDirection(Qt::RightToLeft);
        lbNode_4->setFont(font2);
        lbNode_4->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_5 = new WLabel(LNET_Dl2);
        lbNumNode_5->setObjectName(QString::fromUtf8("lbNumNode_5"));
        lbNumNode_5->setGeometry(QRect(10, 130, 21, 16));
        lbNumNode_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_5->setFont(font2);
        lbNumNode_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_5 = new WLabel(LNET_Dl2);
        lbNode_5->setObjectName(QString::fromUtf8("lbNode_5"));
        lbNode_5->setGeometry(QRect(346, 130, 51, 20));
        lbNode_5->setLayoutDirection(Qt::RightToLeft);
        lbNode_5->setFont(font2);
        lbNode_5->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_5 = new WLabel(LNET_Dl2);
        lbNodeU_5->setObjectName(QString::fromUtf8("lbNodeU_5"));
        lbNodeU_5->setGeometry(QRect(415, 130, 61, 20));
        lbNodeU_5->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_5->setFont(font2);
        lbNodeU_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_5 = new WLabel(LNET_Dl2);
        lbNodeT_5->setObjectName(QString::fromUtf8("lbNodeT_5"));
        lbNodeT_5->setGeometry(QRect(30, 130, 291, 16));
        lbNodeT_5->setFont(font2);
        lbNodeT_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_6 = new WLabel(LNET_Dl2);
        lbNumNode_6->setObjectName(QString::fromUtf8("lbNumNode_6"));
        lbNumNode_6->setGeometry(QRect(10, 148, 21, 16));
        lbNumNode_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_6->setFont(font2);
        lbNumNode_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_6 = new WLabel(LNET_Dl2);
        lbNode_6->setObjectName(QString::fromUtf8("lbNode_6"));
        lbNode_6->setGeometry(QRect(346, 148, 51, 20));
        lbNode_6->setLayoutDirection(Qt::RightToLeft);
        lbNode_6->setFont(font2);
        lbNode_6->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_6 = new WLabel(LNET_Dl2);
        lbNodeT_6->setObjectName(QString::fromUtf8("lbNodeT_6"));
        lbNodeT_6->setGeometry(QRect(30, 148, 291, 16));
        lbNodeT_6->setFont(font2);
        lbNodeT_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_6 = new WLabel(LNET_Dl2);
        lbNodeU_6->setObjectName(QString::fromUtf8("lbNodeU_6"));
        lbNodeU_6->setGeometry(QRect(415, 148, 61, 20));
        lbNodeU_6->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_6->setFont(font2);
        lbNodeU_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_7 = new WLabel(LNET_Dl2);
        lbNodeT_7->setObjectName(QString::fromUtf8("lbNodeT_7"));
        lbNodeT_7->setGeometry(QRect(30, 168, 291, 16));
        lbNodeT_7->setFont(font2);
        lbNodeT_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_7 = new WLabel(LNET_Dl2);
        lbNode_7->setObjectName(QString::fromUtf8("lbNode_7"));
        lbNode_7->setGeometry(QRect(346, 168, 51, 20));
        lbNode_7->setLayoutDirection(Qt::RightToLeft);
        lbNode_7->setFont(font2);
        lbNode_7->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_7 = new WLabel(LNET_Dl2);
        lbNumNode_7->setObjectName(QString::fromUtf8("lbNumNode_7"));
        lbNumNode_7->setGeometry(QRect(10, 168, 21, 16));
        lbNumNode_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_7->setFont(font2);
        lbNumNode_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_7 = new WLabel(LNET_Dl2);
        lbNodeU_7->setObjectName(QString::fromUtf8("lbNodeU_7"));
        lbNodeU_7->setGeometry(QRect(415, 168, 61, 20));
        lbNodeU_7->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_7->setFont(font2);
        lbNodeU_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_8 = new WLabel(LNET_Dl2);
        lbNumNode_8->setObjectName(QString::fromUtf8("lbNumNode_8"));
        lbNumNode_8->setGeometry(QRect(10, 186, 21, 16));
        lbNumNode_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_8->setFont(font2);
        lbNumNode_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_8 = new WLabel(LNET_Dl2);
        lbNodeT_8->setObjectName(QString::fromUtf8("lbNodeT_8"));
        lbNodeT_8->setGeometry(QRect(30, 186, 291, 16));
        lbNodeT_8->setFont(font2);
        lbNodeT_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_8 = new WLabel(LNET_Dl2);
        lbNode_8->setObjectName(QString::fromUtf8("lbNode_8"));
        lbNode_8->setGeometry(QRect(346, 186, 51, 20));
        lbNode_8->setLayoutDirection(Qt::RightToLeft);
        lbNode_8->setFont(font2);
        lbNode_8->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_8 = new WLabel(LNET_Dl2);
        lbNodeU_8->setObjectName(QString::fromUtf8("lbNodeU_8"));
        lbNodeU_8->setGeometry(QRect(415, 186, 61, 20));
        lbNodeU_8->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_8->setFont(font2);
        lbNodeU_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_9 = new WLabel(LNET_Dl2);
        lbNumNode_9->setObjectName(QString::fromUtf8("lbNumNode_9"));
        lbNumNode_9->setGeometry(QRect(10, 205, 21, 16));
        lbNumNode_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_9->setFont(font2);
        lbNumNode_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_9 = new WLabel(LNET_Dl2);
        lbNodeU_9->setObjectName(QString::fromUtf8("lbNodeU_9"));
        lbNodeU_9->setGeometry(QRect(415, 205, 61, 20));
        lbNodeU_9->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_9->setFont(font2);
        lbNodeU_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_9 = new WLabel(LNET_Dl2);
        lbNodeT_9->setObjectName(QString::fromUtf8("lbNodeT_9"));
        lbNodeT_9->setGeometry(QRect(30, 205, 291, 16));
        lbNodeT_9->setFont(font2);
        lbNodeT_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_9 = new WLabel(LNET_Dl2);
        lbNode_9->setObjectName(QString::fromUtf8("lbNode_9"));
        lbNode_9->setGeometry(QRect(346, 205, 51, 20));
        lbNode_9->setLayoutDirection(Qt::RightToLeft);
        lbNode_9->setFont(font2);
        lbNode_9->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_10 = new WLabel(LNET_Dl2);
        lbNumNode_10->setObjectName(QString::fromUtf8("lbNumNode_10"));
        lbNumNode_10->setGeometry(QRect(10, 225, 21, 16));
        lbNumNode_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_10->setFont(font2);
        lbNumNode_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_10 = new WLabel(LNET_Dl2);
        lbNodeU_10->setObjectName(QString::fromUtf8("lbNodeU_10"));
        lbNodeU_10->setGeometry(QRect(415, 225, 61, 20));
        lbNodeU_10->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_10->setFont(font2);
        lbNodeU_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_10 = new WLabel(LNET_Dl2);
        lbNode_10->setObjectName(QString::fromUtf8("lbNode_10"));
        lbNode_10->setGeometry(QRect(346, 225, 51, 20));
        lbNode_10->setLayoutDirection(Qt::RightToLeft);
        lbNode_10->setFont(font2);
        lbNode_10->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_10 = new WLabel(LNET_Dl2);
        lbNodeT_10->setObjectName(QString::fromUtf8("lbNodeT_10"));
        lbNodeT_10->setGeometry(QRect(30, 225, 311, 16));
        lbNodeT_10->setFont(font2);
        lbNodeT_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_11 = new WLabel(LNET_Dl2);
        lbNumNode_11->setObjectName(QString::fromUtf8("lbNumNode_11"));
        lbNumNode_11->setGeometry(QRect(10, 245, 21, 16));
        lbNumNode_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_11->setFont(font2);
        lbNumNode_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_11 = new WLabel(LNET_Dl2);
        lbNodeT_11->setObjectName(QString::fromUtf8("lbNodeT_11"));
        lbNodeT_11->setGeometry(QRect(30, 245, 311, 16));
        lbNodeT_11->setFont(font2);
        lbNodeT_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_11 = new WLabel(LNET_Dl2);
        lbNode_11->setObjectName(QString::fromUtf8("lbNode_11"));
        lbNode_11->setGeometry(QRect(346, 245, 51, 20));
        lbNode_11->setLayoutDirection(Qt::RightToLeft);
        lbNode_11->setFont(font2);
        lbNode_11->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_11 = new WLabel(LNET_Dl2);
        lbNodeU_11->setObjectName(QString::fromUtf8("lbNodeU_11"));
        lbNodeU_11->setGeometry(QRect(415, 245, 61, 20));
        lbNodeU_11->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_11->setFont(font2);
        lbNodeU_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_12 = new WLabel(LNET_Dl2);
        lbNumNode_12->setObjectName(QString::fromUtf8("lbNumNode_12"));
        lbNumNode_12->setGeometry(QRect(10, 262, 21, 16));
        lbNumNode_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_12->setFont(font2);
        lbNumNode_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_12 = new WLabel(LNET_Dl2);
        lbNodeT_12->setObjectName(QString::fromUtf8("lbNodeT_12"));
        lbNodeT_12->setGeometry(QRect(30, 262, 311, 16));
        lbNodeT_12->setFont(font2);
        lbNodeT_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_12 = new WLabel(LNET_Dl2);
        lbNodeU_12->setObjectName(QString::fromUtf8("lbNodeU_12"));
        lbNodeU_12->setGeometry(QRect(415, 262, 61, 20));
        lbNodeU_12->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_12->setFont(font2);
        lbNodeU_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_12 = new WLabel(LNET_Dl2);
        lbNode_12->setObjectName(QString::fromUtf8("lbNode_12"));
        lbNode_12->setGeometry(QRect(346, 262, 51, 20));
        lbNode_12->setLayoutDirection(Qt::RightToLeft);
        lbNode_12->setFont(font2);
        lbNode_12->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_13 = new WLabel(LNET_Dl2);
        lbNumNode_13->setObjectName(QString::fromUtf8("lbNumNode_13"));
        lbNumNode_13->setGeometry(QRect(10, 282, 21, 16));
        lbNumNode_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_13->setFont(font2);
        lbNumNode_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_13 = new WLabel(LNET_Dl2);
        lbNode_13->setObjectName(QString::fromUtf8("lbNode_13"));
        lbNode_13->setGeometry(QRect(346, 282, 51, 20));
        lbNode_13->setLayoutDirection(Qt::RightToLeft);
        lbNode_13->setFont(font2);
        lbNode_13->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_13 = new WLabel(LNET_Dl2);
        lbNodeU_13->setObjectName(QString::fromUtf8("lbNodeU_13"));
        lbNodeU_13->setGeometry(QRect(415, 282, 61, 20));
        lbNodeU_13->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_13->setFont(font2);
        lbNodeU_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_13 = new WLabel(LNET_Dl2);
        lbNodeT_13->setObjectName(QString::fromUtf8("lbNodeT_13"));
        lbNodeT_13->setGeometry(QRect(30, 282, 311, 16));
        lbNodeT_13->setFont(font2);
        lbNodeT_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_14 = new WLabel(LNET_Dl2);
        lbNodeU_14->setObjectName(QString::fromUtf8("lbNodeU_14"));
        lbNodeU_14->setGeometry(QRect(415, 301, 61, 20));
        lbNodeU_14->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_14->setFont(font2);
        lbNodeU_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_14 = new WLabel(LNET_Dl2);
        lbNode_14->setObjectName(QString::fromUtf8("lbNode_14"));
        lbNode_14->setGeometry(QRect(346, 301, 51, 20));
        lbNode_14->setLayoutDirection(Qt::RightToLeft);
        lbNode_14->setFont(font2);
        lbNode_14->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_14 = new WLabel(LNET_Dl2);
        lbNumNode_14->setObjectName(QString::fromUtf8("lbNumNode_14"));
        lbNumNode_14->setGeometry(QRect(10, 301, 21, 16));
        lbNumNode_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_14->setFont(font2);
        lbNumNode_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_14 = new WLabel(LNET_Dl2);
        lbNodeT_14->setObjectName(QString::fromUtf8("lbNodeT_14"));
        lbNodeT_14->setGeometry(QRect(30, 301, 311, 16));
        lbNodeT_14->setFont(font2);
        lbNodeT_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_15 = new WLabel(LNET_Dl2);
        lbNumNode_15->setObjectName(QString::fromUtf8("lbNumNode_15"));
        lbNumNode_15->setGeometry(QRect(10, 320, 21, 16));
        lbNumNode_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_15->setFont(font2);
        lbNumNode_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_15 = new WLabel(LNET_Dl2);
        lbNodeU_15->setObjectName(QString::fromUtf8("lbNodeU_15"));
        lbNodeU_15->setGeometry(QRect(415, 320, 61, 20));
        lbNodeU_15->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_15->setFont(font2);
        lbNodeU_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_15 = new WLabel(LNET_Dl2);
        lbNode_15->setObjectName(QString::fromUtf8("lbNode_15"));
        lbNode_15->setGeometry(QRect(346, 320, 51, 20));
        lbNode_15->setLayoutDirection(Qt::RightToLeft);
        lbNode_15->setFont(font2);
        lbNode_15->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_15 = new WLabel(LNET_Dl2);
        lbNodeT_15->setObjectName(QString::fromUtf8("lbNodeT_15"));
        lbNodeT_15->setGeometry(QRect(30, 320, 311, 16));
        lbNodeT_15->setFont(font2);
        lbNodeT_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_16 = new WLabel(LNET_Dl2);
        lbNumNode_16->setObjectName(QString::fromUtf8("lbNumNode_16"));
        lbNumNode_16->setGeometry(QRect(10, 340, 21, 16));
        lbNumNode_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_16->setFont(font2);
        lbNumNode_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_16 = new WLabel(LNET_Dl2);
        lbNodeT_16->setObjectName(QString::fromUtf8("lbNodeT_16"));
        lbNodeT_16->setGeometry(QRect(30, 340, 311, 16));
        lbNodeT_16->setFont(font2);
        lbNodeT_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_16 = new WLabel(LNET_Dl2);
        lbNode_16->setObjectName(QString::fromUtf8("lbNode_16"));
        lbNode_16->setGeometry(QRect(346, 340, 51, 20));
        lbNode_16->setLayoutDirection(Qt::RightToLeft);
        lbNode_16->setFont(font2);
        lbNode_16->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_16 = new WLabel(LNET_Dl2);
        lbNodeU_16->setObjectName(QString::fromUtf8("lbNodeU_16"));
        lbNodeU_16->setGeometry(QRect(415, 340, 61, 20));
        lbNodeU_16->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_16->setFont(font2);
        lbNodeU_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbFondo = new QLabel(LNET_Dl2);
        lbFondo->setObjectName(QString::fromUtf8("lbFondo"));
        lbFondo->setGeometry(QRect(0, 0, 485, 421));
        lbFondo->setMinimumSize(QSize(485, 421));
        lbFondo->setMaximumSize(QSize(485, 421));
        lbFondo->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbFondo->raise();
        frame->raise();
        frame_3->raise();
        lbNodRTD->raise();
        lbNodeT_1->raise();
        lbNode_1->raise();
        lbNodeU_1->raise();
        btCerrar->raise();
        lbNumNode_1->raise();
        lbNumNode_2->raise();
        lbNodeT_2->raise();
        lbNodeU_2->raise();
        lbNode_2->raise();
        lbNodeU_3->raise();
        lbNodeT_3->raise();
        lbNode_3->raise();
        lbNumNode_3->raise();
        lbNumNode_4->raise();
        lbNodeT_4->raise();
        lbNodeU_4->raise();
        lbNode_4->raise();
        lbNumNode_5->raise();
        lbNode_5->raise();
        lbNodeU_5->raise();
        lbNodeT_5->raise();
        lbNumNode_6->raise();
        lbNode_6->raise();
        lbNodeT_6->raise();
        lbNodeU_6->raise();
        lbNodeT_7->raise();
        lbNode_7->raise();
        lbNumNode_7->raise();
        lbNodeU_7->raise();
        lbNumNode_8->raise();
        lbNodeT_8->raise();
        lbNode_8->raise();
        lbNodeU_8->raise();
        lbNumNode_9->raise();
        lbNodeU_9->raise();
        lbNodeT_9->raise();
        lbNode_9->raise();
        lbNumNode_10->raise();
        lbNodeU_10->raise();
        lbNode_10->raise();
        lbNodeT_10->raise();
        lbNumNode_11->raise();
        lbNodeT_11->raise();
        lbNode_11->raise();
        lbNodeU_11->raise();
        lbNumNode_12->raise();
        lbNodeT_12->raise();
        lbNodeU_12->raise();
        lbNode_12->raise();
        lbNumNode_13->raise();
        lbNode_13->raise();
        lbNodeU_13->raise();
        lbNodeT_13->raise();
        lbNodeU_14->raise();
        lbNode_14->raise();
        lbNumNode_14->raise();
        lbNodeT_14->raise();
        lbNumNode_15->raise();
        lbNodeU_15->raise();
        lbNode_15->raise();
        lbNodeT_15->raise();
        lbNumNode_16->raise();
        lbNodeT_16->raise();
        lbNode_16->raise();
        lbNodeU_16->raise();

        retranslateUi(LNET_Dl2);

        QMetaObject::connectSlotsByName(LNET_Dl2);
    } // setupUi

    void retranslateUi(QWidget *LNET_Dl2)
    {
        LNET_Dl2->setWindowTitle(QApplication::translate("LNET_Dl2", "LNET_Dl2", 0, QApplication::UnicodeUTF8));
        lbLnetT_2->setText(QApplication::translate("LNET_Dl2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbLnetT_3->setText(QApplication::translate("LNET_Dl2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbLnetT->setText(QApplication::translate("LNET_Dl2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">LNET_DI.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbNodRTD->setText(QApplication::translate("LNET_Dl2", "NODE - N1N34 - Dl", 0, QApplication::UnicodeUTF8));
        lbNodeT_1->setText(QApplication::translate("LNET_Dl2", "TEMP BAJ TANQUE ACEITE LUB TRUB", 0, QApplication::UnicodeUTF8));
        lbNode_1->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_1->setText(QApplication::translate("LNET_Dl2", "NALM", 0, QApplication::UnicodeUTF8));
        btCerrar->setText(QApplication::translate("LNET_Dl2", "CERRAR", 0, QApplication::UnicodeUTF8));
        lbNumNode_1->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNumNode_2->setText(QApplication::translate("LNET_Dl2", "2", 0, QApplication::UnicodeUTF8));
        lbNodeT_2->setText(QApplication::translate("LNET_Dl2", "ESTACI\303\223N CONTROL LAVADO AGUA", 0, QApplication::UnicodeUTF8));
        lbNodeU_2->setText(QApplication::translate("LNET_Dl2", "NENBL", 0, QApplication::UnicodeUTF8));
        lbNode_2->setText(QApplication::translate("LNET_Dl2", "0", 0, QApplication::UnicodeUTF8));
        lbNodeU_3->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_3->setText(QApplication::translate("LNET_Dl2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_3->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_3->setText(QApplication::translate("LNET_Dl2", "3", 0, QApplication::UnicodeUTF8));
        lbNumNode_4->setText(QApplication::translate("LNET_Dl2", "4", 0, QApplication::UnicodeUTF8));
        lbNodeT_4->setText(QApplication::translate("LNET_Dl2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNodeU_4->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNode_4->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_5->setText(QApplication::translate("LNET_Dl2", "5", 0, QApplication::UnicodeUTF8));
        lbNode_5->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNodeU_5->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_5->setText(QApplication::translate("LNET_Dl2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumNode_6->setText(QApplication::translate("LNET_Dl2", "6", 0, QApplication::UnicodeUTF8));
        lbNode_6->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNodeT_6->setText(QApplication::translate("LNET_Dl2", "BAJ NIVEL TANQUE ACEITE LUB TURB", 0, QApplication::UnicodeUTF8));
        lbNodeU_6->setText(QApplication::translate("LNET_Dl2", "NALM", 0, QApplication::UnicodeUTF8));
        lbNodeT_7->setText(QApplication::translate("LNET_Dl2", "NIVEL TANQUE LAV AGUA", 0, QApplication::UnicodeUTF8));
        lbNode_7->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNumNode_7->setText(QApplication::translate("LNET_Dl2", "7", 0, QApplication::UnicodeUTF8));
        lbNodeU_7->setText(QApplication::translate("LNET_Dl2", "NALM", 0, QApplication::UnicodeUTF8));
        lbNumNode_8->setText(QApplication::translate("LNET_Dl2", "8", 0, QApplication::UnicodeUTF8));
        lbNodeT_8->setText(QApplication::translate("LNET_Dl2", "FILTRO RECUP ACEITE LUB TURB ALT P/D", 0, QApplication::UnicodeUTF8));
        lbNode_8->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_8->setText(QApplication::translate("LNET_Dl2", "NALM", 0, QApplication::UnicodeUTF8));
        lbNumNode_9->setText(QApplication::translate("LNET_Dl2", "9", 0, QApplication::UnicodeUTF8));
        lbNodeU_9->setText(QApplication::translate("LNET_Dl2", "NSDN", 0, QApplication::UnicodeUTF8));
        lbNodeT_9->setText(QApplication::translate("LNET_Dl2", "ARRANQUE PAT\303\215N RESERV ACEITE HID NIV", 0, QApplication::UnicodeUTF8));
        lbNode_9->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNumNode_10->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNodeU_10->setText(QApplication::translate("LNET_Dl2", "NALM", 0, QApplication::UnicodeUTF8));
        lbNode_10->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNodeT_10->setText(QApplication::translate("LNET_Dl2", "ARRANQUE PAT\303\215N RESERV ACEITE HID TEMP AL", 0, QApplication::UnicodeUTF8));
        lbNumNode_11->setText(QApplication::translate("LNET_Dl2", "11", 0, QApplication::UnicodeUTF8));
        lbNodeT_11->setText(QApplication::translate("LNET_Dl2", "ARRANQUE PAT\303\215N RESERV ACEITE HID TEMP BA", 0, QApplication::UnicodeUTF8));
        lbNode_11->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_11->setText(QApplication::translate("LNET_Dl2", "NALM", 0, QApplication::UnicodeUTF8));
        lbNumNode_12->setText(QApplication::translate("LNET_Dl2", "12", 0, QApplication::UnicodeUTF8));
        lbNodeT_12->setText(QApplication::translate("LNET_Dl2", "PAT\303\215N ARRANQUE PRES SUMIN HID BOMBA BAJ", 0, QApplication::UnicodeUTF8));
        lbNodeU_12->setText(QApplication::translate("LNET_Dl2", "SDN", 0, QApplication::UnicodeUTF8));
        lbNode_12->setText(QApplication::translate("LNET_Dl2", "0", 0, QApplication::UnicodeUTF8));
        lbNumNode_13->setText(QApplication::translate("LNET_Dl2", "13", 0, QApplication::UnicodeUTF8));
        lbNode_13->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_13->setText(QApplication::translate("LNET_Dl2", "NSDN", 0, QApplication::UnicodeUTF8));
        lbNodeT_13->setText(QApplication::translate("LNET_Dl2", "ARRANQUE PAT\303\215N BMBA HID VAC\303\215O P/D ALTA A", 0, QApplication::UnicodeUTF8));
        lbNodeU_14->setText(QApplication::translate("LNET_Dl2", "NALM", 0, QApplication::UnicodeUTF8));
        lbNode_14->setText(QApplication::translate("LNET_Dl2", "1", 0, QApplication::UnicodeUTF8));
        lbNumNode_14->setText(QApplication::translate("LNET_Dl2", "14", 0, QApplication::UnicodeUTF8));
        lbNodeT_14->setText(QApplication::translate("LNET_Dl2", "FILTRO RECUP ACEITE RECIC TURB ALT P/D", 0, QApplication::UnicodeUTF8));
        lbNumNode_15->setText(QApplication::translate("LNET_Dl2", "15", 0, QApplication::UnicodeUTF8));
        lbNodeU_15->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNode_15->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_15->setText(QApplication::translate("LNET_Dl2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumNode_16->setText(QApplication::translate("LNET_Dl2", "16", 0, QApplication::UnicodeUTF8));
        lbNodeT_16->setText(QApplication::translate("LNET_Dl2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_16->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbNodeU_16->setText(QApplication::translate("LNET_Dl2", "10", 0, QApplication::UnicodeUTF8));
        lbFondo->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class LNET_Dl2: public Ui_LNET_Dl2 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LNET_DL2_H
