/********************************************************************************
** Form generated from reading UI file 'lnet_di.ui'
**
** Created: Thu 19. Dec 16:09:58 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LNET_DI_H
#define UI_LNET_DI_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_LNET_DI
{
public:
    QFrame *frame_3;
    WLabel *lbLnetT_3;
    WLabel *lbLnetT;
    WLabel *lbNodRTD;
    QFrame *frame;
    WLabel *lbNumNode_1;
    WLabel *lbNodeT_1;
    WLabel *lbNode_1;
    WLabel *lbNodeU_1;
    WLabel *lbNumNode_2;
    WLabel *lbNodeT_2;
    WLabel *lbNode_2;
    WLabel *lbNodeU_2;
    WLabel *lbNumNode_3;
    WLabel *lbNodeU_3;
    WLabel *lbNode_3;
    WLabel *lbNodeT_3;
    WLabel *lbNumNode_4;
    WLabel *lbNodeU_4;
    WLabel *lbNodeT_4;
    WLabel *lbNode_4;
    WLabel *lbNumNode_5;
    WLabel *lbNode_5;
    WLabel *lbNodeT_5;
    WLabel *lbNodeU_5;
    WLabel *lbNumNode_6;
    WLabel *lbNodeT_6;
    WLabel *lbNodeU_6;
    WLabel *lbNode_6;
    WLabel *lbNumNode_7;
    WLabel *lbNodeU_7;
    WLabel *lbNodeT_7;
    WLabel *lbNode_7;
    WLabel *lbNumNode_8;
    WLabel *lbNodeU_8;
    WLabel *lbNode_8;
    WLabel *lbNodeT_8;
    WLabel *lbNumNode_9;
    WLabel *lbNode_9;
    WLabel *lbNodeT_9;
    WLabel *lbNodeU_9;
    WLabel *lbNumNode_10;
    WLabel *lbNodeU_10;
    WLabel *lbNodeT_10;
    WLabel *lbNode_10;
    WLabel *lbNumNode_11;
    WLabel *lbNode_11;
    WLabel *lbNodeT_11;
    WLabel *lbNodeU_11;
    WLabel *lbNumNode_12;
    WLabel *lbNodeT_12;
    WLabel *lbNode_12;
    WLabel *lbNodeU_12;
    WLabel *lbNodeU_13;
    WLabel *lbNodeT_13;
    WLabel *lbNumNode_13;
    WLabel *lbNode_13;
    WLabel *lbNodeU_14;
    WLabel *lbNodeT_14;
    WLabel *lbNumNode_14;
    WLabel *lbNode_14;
    WLabel *lbNumNode_15;
    WLabel *lbNodeU_15;
    WLabel *lbNodeT_15;
    WLabel *lbNode_15;
    WLabel *lbNumNode_16;
    WLabel *lbNodeU_16;
    WLabel *lbNode_16;
    WLabel *lbNodeT_16;
    QPushButton *btCerrar;
    QLabel *lbFondo;

    void setupUi(QWidget *LNET_DI)
    {
        if (LNET_DI->objectName().isEmpty())
            LNET_DI->setObjectName(QString::fromUtf8("LNET_DI"));
        LNET_DI->resize(485, 425);
        LNET_DI->setMinimumSize(QSize(485, 425));
        LNET_DI->setMaximumSize(QSize(485, 425));
        LNET_DI->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        frame_3 = new QFrame(LNET_DI);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(0, 0, 485, 13));
        frame_3->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frame_3->setFrameShape(QFrame::Panel);
        frame_3->setFrameShadow(QFrame::Raised);
        frame_3->setLineWidth(0);
        lbLnetT_3 = new WLabel(frame_3);
        lbLnetT_3->setObjectName(QString::fromUtf8("lbLnetT_3"));
        lbLnetT_3->setGeometry(QRect(0, 0, 81, 20));
        lbLnetT_3->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        QFont font;
        font.setPointSize(5);
        font.setBold(true);
        font.setWeight(75);
        lbLnetT_3->setFont(font);
        lbLnetT_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbLnetT = new WLabel(frame_3);
        lbLnetT->setObjectName(QString::fromUtf8("lbLnetT"));
        lbLnetT->setGeometry(QRect(3, 0, 81, 12));
        lbLnetT->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        lbLnetT->setFont(font);
        lbLnetT->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodRTD = new WLabel(LNET_DI);
        lbNodRTD->setObjectName(QString::fromUtf8("lbNodRTD"));
        lbNodRTD->setGeometry(QRect(68, 22, 400, 20));
        lbNodRTD->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        lbNodRTD->setFont(font1);
        lbNodRTD->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        frame = new QFrame(LNET_DI);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 17, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        lbNumNode_1 = new WLabel(LNET_DI);
        lbNumNode_1->setObjectName(QString::fromUtf8("lbNumNode_1"));
        lbNumNode_1->setGeometry(QRect(10, 52, 21, 16));
        lbNumNode_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setBold(true);
        font2.setWeight(75);
        lbNumNode_1->setFont(font2);
        lbNumNode_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_1 = new WLabel(LNET_DI);
        lbNodeT_1->setObjectName(QString::fromUtf8("lbNodeT_1"));
        lbNodeT_1->setGeometry(QRect(30, 52, 291, 16));
        lbNodeT_1->setFont(font2);
        lbNodeT_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_1 = new WLabel(LNET_DI);
        lbNode_1->setObjectName(QString::fromUtf8("lbNode_1"));
        lbNode_1->setGeometry(QRect(335, 52, 61, 20));
        lbNode_1->setLayoutDirection(Qt::RightToLeft);
        lbNode_1->setFont(font2);
        lbNode_1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_1 = new WLabel(LNET_DI);
        lbNodeU_1->setObjectName(QString::fromUtf8("lbNodeU_1"));
        lbNodeU_1->setGeometry(QRect(416, 52, 62, 20));
        lbNodeU_1->setStyleSheet(QString::fromUtf8(""));
        lbNodeU_1->setFont(font2);
        lbNodeU_1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_2 = new WLabel(LNET_DI);
        lbNumNode_2->setObjectName(QString::fromUtf8("lbNumNode_2"));
        lbNumNode_2->setGeometry(QRect(10, 72, 21, 16));
        lbNumNode_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_2->setFont(font2);
        lbNumNode_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_2 = new WLabel(LNET_DI);
        lbNodeT_2->setObjectName(QString::fromUtf8("lbNodeT_2"));
        lbNodeT_2->setGeometry(QRect(30, 72, 291, 16));
        lbNodeT_2->setFont(font2);
        lbNodeT_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_2 = new WLabel(LNET_DI);
        lbNode_2->setObjectName(QString::fromUtf8("lbNode_2"));
        lbNode_2->setGeometry(QRect(335, 72, 61, 20));
        lbNode_2->setLayoutDirection(Qt::RightToLeft);
        lbNode_2->setFont(font2);
        lbNode_2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_2 = new WLabel(LNET_DI);
        lbNodeU_2->setObjectName(QString::fromUtf8("lbNodeU_2"));
        lbNodeU_2->setGeometry(QRect(416, 72, 62, 20));
        lbNodeU_2->setStyleSheet(QString::fromUtf8(""));
        lbNodeU_2->setFont(font2);
        lbNodeU_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_3 = new WLabel(LNET_DI);
        lbNumNode_3->setObjectName(QString::fromUtf8("lbNumNode_3"));
        lbNumNode_3->setGeometry(QRect(10, 90, 21, 16));
        lbNumNode_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_3->setFont(font2);
        lbNumNode_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_3 = new WLabel(LNET_DI);
        lbNodeU_3->setObjectName(QString::fromUtf8("lbNodeU_3"));
        lbNodeU_3->setGeometry(QRect(416, 90, 62, 20));
        lbNodeU_3->setStyleSheet(QString::fromUtf8(""));
        lbNodeU_3->setFont(font2);
        lbNodeU_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_3 = new WLabel(LNET_DI);
        lbNode_3->setObjectName(QString::fromUtf8("lbNode_3"));
        lbNode_3->setGeometry(QRect(335, 90, 61, 20));
        lbNode_3->setLayoutDirection(Qt::RightToLeft);
        lbNode_3->setFont(font2);
        lbNode_3->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_3 = new WLabel(LNET_DI);
        lbNodeT_3->setObjectName(QString::fromUtf8("lbNodeT_3"));
        lbNodeT_3->setGeometry(QRect(30, 90, 291, 16));
        lbNodeT_3->setFont(font2);
        lbNodeT_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_4 = new WLabel(LNET_DI);
        lbNumNode_4->setObjectName(QString::fromUtf8("lbNumNode_4"));
        lbNumNode_4->setGeometry(QRect(10, 108, 21, 16));
        lbNumNode_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_4->setFont(font2);
        lbNumNode_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_4 = new WLabel(LNET_DI);
        lbNodeU_4->setObjectName(QString::fromUtf8("lbNodeU_4"));
        lbNodeU_4->setGeometry(QRect(416, 108, 62, 20));
        lbNodeU_4->setStyleSheet(QString::fromUtf8(""));
        lbNodeU_4->setFont(font2);
        lbNodeU_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_4 = new WLabel(LNET_DI);
        lbNodeT_4->setObjectName(QString::fromUtf8("lbNodeT_4"));
        lbNodeT_4->setGeometry(QRect(30, 108, 291, 16));
        lbNodeT_4->setFont(font2);
        lbNodeT_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_4 = new WLabel(LNET_DI);
        lbNode_4->setObjectName(QString::fromUtf8("lbNode_4"));
        lbNode_4->setGeometry(QRect(335, 108, 61, 20));
        lbNode_4->setLayoutDirection(Qt::RightToLeft);
        lbNode_4->setFont(font2);
        lbNode_4->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_5 = new WLabel(LNET_DI);
        lbNumNode_5->setObjectName(QString::fromUtf8("lbNumNode_5"));
        lbNumNode_5->setGeometry(QRect(10, 128, 21, 16));
        lbNumNode_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_5->setFont(font2);
        lbNumNode_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_5 = new WLabel(LNET_DI);
        lbNode_5->setObjectName(QString::fromUtf8("lbNode_5"));
        lbNode_5->setGeometry(QRect(335, 128, 61, 20));
        lbNode_5->setLayoutDirection(Qt::RightToLeft);
        lbNode_5->setFont(font2);
        lbNode_5->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_5 = new WLabel(LNET_DI);
        lbNodeT_5->setObjectName(QString::fromUtf8("lbNodeT_5"));
        lbNodeT_5->setGeometry(QRect(30, 128, 291, 16));
        lbNodeT_5->setFont(font2);
        lbNodeT_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_5 = new WLabel(LNET_DI);
        lbNodeU_5->setObjectName(QString::fromUtf8("lbNodeU_5"));
        lbNodeU_5->setGeometry(QRect(416, 128, 62, 20));
        lbNodeU_5->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_5->setFont(font2);
        lbNodeU_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_6 = new WLabel(LNET_DI);
        lbNumNode_6->setObjectName(QString::fromUtf8("lbNumNode_6"));
        lbNumNode_6->setGeometry(QRect(10, 148, 21, 16));
        lbNumNode_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_6->setFont(font2);
        lbNumNode_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_6 = new WLabel(LNET_DI);
        lbNodeT_6->setObjectName(QString::fromUtf8("lbNodeT_6"));
        lbNodeT_6->setGeometry(QRect(30, 148, 291, 16));
        lbNodeT_6->setFont(font2);
        lbNodeT_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_6 = new WLabel(LNET_DI);
        lbNodeU_6->setObjectName(QString::fromUtf8("lbNodeU_6"));
        lbNodeU_6->setGeometry(QRect(416, 148, 62, 20));
        lbNodeU_6->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_6->setFont(font2);
        lbNodeU_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_6 = new WLabel(LNET_DI);
        lbNode_6->setObjectName(QString::fromUtf8("lbNode_6"));
        lbNode_6->setGeometry(QRect(335, 148, 61, 20));
        lbNode_6->setLayoutDirection(Qt::RightToLeft);
        lbNode_6->setFont(font2);
        lbNode_6->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_7 = new WLabel(LNET_DI);
        lbNumNode_7->setObjectName(QString::fromUtf8("lbNumNode_7"));
        lbNumNode_7->setGeometry(QRect(10, 165, 21, 16));
        lbNumNode_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_7->setFont(font2);
        lbNumNode_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_7 = new WLabel(LNET_DI);
        lbNodeU_7->setObjectName(QString::fromUtf8("lbNodeU_7"));
        lbNodeU_7->setGeometry(QRect(416, 165, 62, 20));
        lbNodeU_7->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_7->setFont(font2);
        lbNodeU_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_7 = new WLabel(LNET_DI);
        lbNodeT_7->setObjectName(QString::fromUtf8("lbNodeT_7"));
        lbNodeT_7->setGeometry(QRect(30, 165, 291, 16));
        lbNodeT_7->setFont(font2);
        lbNodeT_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_7 = new WLabel(LNET_DI);
        lbNode_7->setObjectName(QString::fromUtf8("lbNode_7"));
        lbNode_7->setGeometry(QRect(335, 165, 61, 20));
        lbNode_7->setLayoutDirection(Qt::RightToLeft);
        lbNode_7->setFont(font2);
        lbNode_7->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_8 = new WLabel(LNET_DI);
        lbNumNode_8->setObjectName(QString::fromUtf8("lbNumNode_8"));
        lbNumNode_8->setGeometry(QRect(10, 185, 21, 16));
        lbNumNode_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_8->setFont(font2);
        lbNumNode_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_8 = new WLabel(LNET_DI);
        lbNodeU_8->setObjectName(QString::fromUtf8("lbNodeU_8"));
        lbNodeU_8->setGeometry(QRect(416, 185, 62, 20));
        lbNodeU_8->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_8->setFont(font2);
        lbNodeU_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_8 = new WLabel(LNET_DI);
        lbNode_8->setObjectName(QString::fromUtf8("lbNode_8"));
        lbNode_8->setGeometry(QRect(335, 185, 61, 20));
        lbNode_8->setLayoutDirection(Qt::RightToLeft);
        lbNode_8->setFont(font2);
        lbNode_8->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_8 = new WLabel(LNET_DI);
        lbNodeT_8->setObjectName(QString::fromUtf8("lbNodeT_8"));
        lbNodeT_8->setGeometry(QRect(30, 185, 291, 16));
        lbNodeT_8->setFont(font2);
        lbNodeT_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_9 = new WLabel(LNET_DI);
        lbNumNode_9->setObjectName(QString::fromUtf8("lbNumNode_9"));
        lbNumNode_9->setGeometry(QRect(10, 205, 21, 16));
        lbNumNode_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_9->setFont(font2);
        lbNumNode_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_9 = new WLabel(LNET_DI);
        lbNode_9->setObjectName(QString::fromUtf8("lbNode_9"));
        lbNode_9->setGeometry(QRect(335, 205, 61, 20));
        lbNode_9->setLayoutDirection(Qt::RightToLeft);
        lbNode_9->setFont(font2);
        lbNode_9->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_9 = new WLabel(LNET_DI);
        lbNodeT_9->setObjectName(QString::fromUtf8("lbNodeT_9"));
        lbNodeT_9->setGeometry(QRect(30, 205, 291, 16));
        lbNodeT_9->setFont(font2);
        lbNodeT_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_9 = new WLabel(LNET_DI);
        lbNodeU_9->setObjectName(QString::fromUtf8("lbNodeU_9"));
        lbNodeU_9->setGeometry(QRect(416, 205, 62, 20));
        lbNodeU_9->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_9->setFont(font2);
        lbNodeU_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_10 = new WLabel(LNET_DI);
        lbNumNode_10->setObjectName(QString::fromUtf8("lbNumNode_10"));
        lbNumNode_10->setGeometry(QRect(10, 225, 21, 16));
        lbNumNode_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_10->setFont(font2);
        lbNumNode_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_10 = new WLabel(LNET_DI);
        lbNodeU_10->setObjectName(QString::fromUtf8("lbNodeU_10"));
        lbNodeU_10->setGeometry(QRect(416, 225, 62, 20));
        lbNodeU_10->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_10->setFont(font2);
        lbNodeU_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_10 = new WLabel(LNET_DI);
        lbNodeT_10->setObjectName(QString::fromUtf8("lbNodeT_10"));
        lbNodeT_10->setGeometry(QRect(30, 225, 291, 16));
        lbNodeT_10->setFont(font2);
        lbNodeT_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_10 = new WLabel(LNET_DI);
        lbNode_10->setObjectName(QString::fromUtf8("lbNode_10"));
        lbNode_10->setGeometry(QRect(335, 225, 61, 20));
        lbNode_10->setLayoutDirection(Qt::RightToLeft);
        lbNode_10->setFont(font2);
        lbNode_10->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_11 = new WLabel(LNET_DI);
        lbNumNode_11->setObjectName(QString::fromUtf8("lbNumNode_11"));
        lbNumNode_11->setGeometry(QRect(10, 245, 21, 16));
        lbNumNode_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_11->setFont(font2);
        lbNumNode_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_11 = new WLabel(LNET_DI);
        lbNode_11->setObjectName(QString::fromUtf8("lbNode_11"));
        lbNode_11->setGeometry(QRect(335, 245, 61, 20));
        lbNode_11->setLayoutDirection(Qt::RightToLeft);
        lbNode_11->setFont(font2);
        lbNode_11->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_11 = new WLabel(LNET_DI);
        lbNodeT_11->setObjectName(QString::fromUtf8("lbNodeT_11"));
        lbNodeT_11->setGeometry(QRect(30, 245, 291, 16));
        lbNodeT_11->setFont(font2);
        lbNodeT_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_11 = new WLabel(LNET_DI);
        lbNodeU_11->setObjectName(QString::fromUtf8("lbNodeU_11"));
        lbNodeU_11->setGeometry(QRect(416, 245, 62, 20));
        lbNodeU_11->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_11->setFont(font2);
        lbNodeU_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_12 = new WLabel(LNET_DI);
        lbNumNode_12->setObjectName(QString::fromUtf8("lbNumNode_12"));
        lbNumNode_12->setGeometry(QRect(10, 262, 21, 16));
        lbNumNode_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_12->setFont(font2);
        lbNumNode_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_12 = new WLabel(LNET_DI);
        lbNodeT_12->setObjectName(QString::fromUtf8("lbNodeT_12"));
        lbNodeT_12->setGeometry(QRect(30, 262, 291, 16));
        lbNodeT_12->setFont(font2);
        lbNodeT_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_12 = new WLabel(LNET_DI);
        lbNode_12->setObjectName(QString::fromUtf8("lbNode_12"));
        lbNode_12->setGeometry(QRect(335, 262, 61, 20));
        lbNode_12->setLayoutDirection(Qt::RightToLeft);
        lbNode_12->setFont(font2);
        lbNode_12->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_12 = new WLabel(LNET_DI);
        lbNodeU_12->setObjectName(QString::fromUtf8("lbNodeU_12"));
        lbNodeU_12->setGeometry(QRect(416, 262, 62, 20));
        lbNodeU_12->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_12->setFont(font2);
        lbNodeU_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_13 = new WLabel(LNET_DI);
        lbNodeU_13->setObjectName(QString::fromUtf8("lbNodeU_13"));
        lbNodeU_13->setGeometry(QRect(416, 283, 62, 20));
        lbNodeU_13->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_13->setFont(font2);
        lbNodeU_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_13 = new WLabel(LNET_DI);
        lbNodeT_13->setObjectName(QString::fromUtf8("lbNodeT_13"));
        lbNodeT_13->setGeometry(QRect(31, 283, 291, 16));
        lbNodeT_13->setFont(font2);
        lbNodeT_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_13 = new WLabel(LNET_DI);
        lbNumNode_13->setObjectName(QString::fromUtf8("lbNumNode_13"));
        lbNumNode_13->setGeometry(QRect(10, 283, 21, 16));
        lbNumNode_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_13->setFont(font2);
        lbNumNode_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_13 = new WLabel(LNET_DI);
        lbNode_13->setObjectName(QString::fromUtf8("lbNode_13"));
        lbNode_13->setGeometry(QRect(335, 283, 61, 20));
        lbNode_13->setLayoutDirection(Qt::RightToLeft);
        lbNode_13->setFont(font2);
        lbNode_13->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeU_14 = new WLabel(LNET_DI);
        lbNodeU_14->setObjectName(QString::fromUtf8("lbNodeU_14"));
        lbNodeU_14->setGeometry(QRect(416, 300, 62, 20));
        lbNodeU_14->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_14->setFont(font2);
        lbNodeU_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_14 = new WLabel(LNET_DI);
        lbNodeT_14->setObjectName(QString::fromUtf8("lbNodeT_14"));
        lbNodeT_14->setGeometry(QRect(30, 300, 291, 16));
        lbNodeT_14->setFont(font2);
        lbNodeT_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNumNode_14 = new WLabel(LNET_DI);
        lbNumNode_14->setObjectName(QString::fromUtf8("lbNumNode_14"));
        lbNumNode_14->setGeometry(QRect(10, 300, 21, 16));
        lbNumNode_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_14->setFont(font2);
        lbNumNode_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_14 = new WLabel(LNET_DI);
        lbNode_14->setObjectName(QString::fromUtf8("lbNode_14"));
        lbNode_14->setGeometry(QRect(335, 300, 61, 20));
        lbNode_14->setLayoutDirection(Qt::RightToLeft);
        lbNode_14->setFont(font2);
        lbNode_14->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_15 = new WLabel(LNET_DI);
        lbNumNode_15->setObjectName(QString::fromUtf8("lbNumNode_15"));
        lbNumNode_15->setGeometry(QRect(10, 320, 21, 16));
        lbNumNode_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_15->setFont(font2);
        lbNumNode_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_15 = new WLabel(LNET_DI);
        lbNodeU_15->setObjectName(QString::fromUtf8("lbNodeU_15"));
        lbNodeU_15->setGeometry(QRect(416, 320, 62, 20));
        lbNodeU_15->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_15->setFont(font2);
        lbNodeU_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeT_15 = new WLabel(LNET_DI);
        lbNodeT_15->setObjectName(QString::fromUtf8("lbNodeT_15"));
        lbNodeT_15->setGeometry(QRect(30, 320, 291, 16));
        lbNodeT_15->setFont(font2);
        lbNodeT_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_15 = new WLabel(LNET_DI);
        lbNode_15->setObjectName(QString::fromUtf8("lbNode_15"));
        lbNode_15->setGeometry(QRect(335, 320, 61, 20));
        lbNode_15->setLayoutDirection(Qt::RightToLeft);
        lbNode_15->setFont(font2);
        lbNode_15->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNumNode_16 = new WLabel(LNET_DI);
        lbNumNode_16->setObjectName(QString::fromUtf8("lbNumNode_16"));
        lbNumNode_16->setGeometry(QRect(10, 340, 21, 16));
        lbNumNode_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_16->setFont(font2);
        lbNumNode_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNodeU_16 = new WLabel(LNET_DI);
        lbNodeU_16->setObjectName(QString::fromUtf8("lbNodeU_16"));
        lbNodeU_16->setGeometry(QRect(416, 340, 62, 20));
        lbNodeU_16->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_16->setFont(font2);
        lbNodeU_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lbNode_16 = new WLabel(LNET_DI);
        lbNode_16->setObjectName(QString::fromUtf8("lbNode_16"));
        lbNode_16->setGeometry(QRect(335, 340, 61, 20));
        lbNode_16->setLayoutDirection(Qt::RightToLeft);
        lbNode_16->setFont(font2);
        lbNode_16->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbNodeT_16 = new WLabel(LNET_DI);
        lbNodeT_16->setObjectName(QString::fromUtf8("lbNodeT_16"));
        lbNodeT_16->setGeometry(QRect(30, 340, 291, 16));
        lbNodeT_16->setFont(font2);
        lbNodeT_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        btCerrar = new QPushButton(LNET_DI);
        btCerrar->setObjectName(QString::fromUtf8("btCerrar"));
        btCerrar->setGeometry(QRect(134, 372, 101, 31));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        btCerrar->setFont(font3);
        btCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbFondo = new QLabel(LNET_DI);
        lbFondo->setObjectName(QString::fromUtf8("lbFondo"));
        lbFondo->setGeometry(QRect(0, 0, 485, 425));
        lbFondo->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbFondo->setFrameShape(QFrame::Box);
        lbFondo->setFrameShadow(QFrame::Sunken);
        lbFondo->raise();
        frame->raise();
        frame_3->raise();
        lbNodRTD->raise();
        lbNumNode_1->raise();
        lbNodeT_1->raise();
        lbNode_1->raise();
        lbNodeU_1->raise();
        lbNumNode_2->raise();
        lbNodeT_2->raise();
        lbNode_2->raise();
        lbNodeU_2->raise();
        lbNumNode_3->raise();
        lbNodeU_3->raise();
        lbNode_3->raise();
        lbNodeT_3->raise();
        lbNumNode_4->raise();
        lbNodeU_4->raise();
        lbNodeT_4->raise();
        lbNode_4->raise();
        lbNumNode_5->raise();
        lbNode_5->raise();
        lbNodeT_5->raise();
        lbNodeU_5->raise();
        lbNumNode_6->raise();
        lbNodeT_6->raise();
        lbNodeU_6->raise();
        lbNode_6->raise();
        lbNumNode_7->raise();
        lbNodeU_7->raise();
        lbNodeT_7->raise();
        lbNode_7->raise();
        lbNumNode_8->raise();
        lbNodeU_8->raise();
        lbNode_8->raise();
        lbNodeT_8->raise();
        lbNumNode_9->raise();
        lbNode_9->raise();
        lbNodeT_9->raise();
        lbNodeU_9->raise();
        lbNumNode_10->raise();
        lbNodeU_10->raise();
        lbNodeT_10->raise();
        lbNode_10->raise();
        lbNumNode_11->raise();
        lbNode_11->raise();
        lbNodeT_11->raise();
        lbNodeU_11->raise();
        lbNumNode_12->raise();
        lbNodeT_12->raise();
        lbNode_12->raise();
        lbNodeU_12->raise();
        lbNodeU_13->raise();
        lbNodeT_13->raise();
        lbNumNode_13->raise();
        lbNode_13->raise();
        lbNodeU_14->raise();
        lbNodeT_14->raise();
        lbNumNode_14->raise();
        lbNode_14->raise();
        lbNumNode_15->raise();
        lbNodeU_15->raise();
        lbNodeT_15->raise();
        lbNode_15->raise();
        lbNumNode_16->raise();
        lbNodeU_16->raise();
        lbNode_16->raise();
        lbNodeT_16->raise();
        btCerrar->raise();

        retranslateUi(LNET_DI);

        QMetaObject::connectSlotsByName(LNET_DI);
    } // setupUi

    void retranslateUi(QWidget *LNET_DI)
    {
        LNET_DI->setWindowTitle(QApplication::translate("LNET_DI", "LNET_DI", 0, QApplication::UnicodeUTF8));
        lbLnetT_3->setText(QApplication::translate("LNET_DI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbLnetT->setText(QApplication::translate("LNET_DI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">LNET_DI.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbNodRTD->setText(QApplication::translate("LNET_DI", "NODE - N1N31 - Dl", 0, QApplication::UnicodeUTF8));
        lbNumNode_1->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNodeT_1->setText(QApplication::translate("LNET_DI", "(NO SE UTILIZA)", 0, QApplication::UnicodeUTF8));
        lbNode_1->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_1->setText(QApplication::translate("LNET_DI", "NALM", 0, QApplication::UnicodeUTF8));
        lbNumNode_2->setText(QApplication::translate("LNET_DI", "2", 0, QApplication::UnicodeUTF8));
        lbNodeT_2->setText(QApplication::translate("LNET_DI", "(NO SE UTILIZA)", 0, QApplication::UnicodeUTF8));
        lbNode_2->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_2->setText(QApplication::translate("LNET_DI", "NSDN", 0, QApplication::UnicodeUTF8));
        lbNumNode_3->setText(QApplication::translate("LNET_DI", "3", 0, QApplication::UnicodeUTF8));
        lbNodeU_3->setText(QApplication::translate("LNET_DI", "NALM", 0, QApplication::UnicodeUTF8));
        lbNode_3->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNodeT_3->setText(QApplication::translate("LNET_DI", "FILTRO ENTRADA DE AIRE DE COMB DE P", 0, QApplication::UnicodeUTF8));
        lbNumNode_4->setText(QApplication::translate("LNET_DI", "4", 0, QApplication::UnicodeUTF8));
        lbNodeU_4->setText(QApplication::translate("LNET_DI", "NCDLO", 0, QApplication::UnicodeUTF8));
        lbNodeT_4->setText(QApplication::translate("LNET_DI", "FILTRO ENTRADA DE AIRE DE COMB DE P", 0, QApplication::UnicodeUTF8));
        lbNode_4->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNumNode_5->setText(QApplication::translate("LNET_DI", "5", 0, QApplication::UnicodeUTF8));
        lbNode_5->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_5->setText(QApplication::translate("LNET_DI", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNodeU_5->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_6->setText(QApplication::translate("LNET_DI", "6", 0, QApplication::UnicodeUTF8));
        lbNodeT_6->setText(QApplication::translate("LNET_DI", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNodeU_6->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNode_6->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_7->setText(QApplication::translate("LNET_DI", "7", 0, QApplication::UnicodeUTF8));
        lbNodeU_7->setText(QApplication::translate("LNET_DI", "NALM", 0, QApplication::UnicodeUTF8));
        lbNodeT_7->setText(QApplication::translate("LNET_DI", "BOMB DESC ACEITE RECIC TURB ALTA PRES", 0, QApplication::UnicodeUTF8));
        lbNode_7->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNumNode_8->setText(QApplication::translate("LNET_DI", "8", 0, QApplication::UnicodeUTF8));
        lbNodeU_8->setText(QApplication::translate("LNET_DI", "CLSD", 0, QApplication::UnicodeUTF8));
        lbNode_8->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNodeT_8->setText(QApplication::translate("LNET_DI", "POS VALV DESAG\303\234E COMBUSTOR", 0, QApplication::UnicodeUTF8));
        lbNumNode_9->setText(QApplication::translate("LNET_DI", "9", 0, QApplication::UnicodeUTF8));
        lbNode_9->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_9->setText(QApplication::translate("LNET_DI", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNodeU_9->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_10->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNodeU_10->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_10->setText(QApplication::translate("LNET_DI", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_10->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_11->setText(QApplication::translate("LNET_DI", "11", 0, QApplication::UnicodeUTF8));
        lbNode_11->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_11->setText(QApplication::translate("LNET_DI", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNodeU_11->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_12->setText(QApplication::translate("LNET_DI", "12", 0, QApplication::UnicodeUTF8));
        lbNodeT_12->setText(QApplication::translate("LNET_DI", "VENT FLUJO AIRE GEN BAJO (VENT A)", 0, QApplication::UnicodeUTF8));
        lbNode_12->setText(QApplication::translate("LNET_DI", "0", 0, QApplication::UnicodeUTF8));
        lbNodeU_12->setText(QApplication::translate("LNET_DI", "ALM", 0, QApplication::UnicodeUTF8));
        lbNodeU_13->setText(QApplication::translate("LNET_DI", "ALM", 0, QApplication::UnicodeUTF8));
        lbNodeT_13->setText(QApplication::translate("LNET_DI", "VENT FLUJO AIRE GEN BAJO (VENT B)", 0, QApplication::UnicodeUTF8));
        lbNumNode_13->setText(QApplication::translate("LNET_DI", "13", 0, QApplication::UnicodeUTF8));
        lbNode_13->setText(QApplication::translate("LNET_DI", "0", 0, QApplication::UnicodeUTF8));
        lbNodeU_14->setText(QApplication::translate("LNET_DI", "NALM", 0, QApplication::UnicodeUTF8));
        lbNodeT_14->setText(QApplication::translate("LNET_DI", "FILTRO ACEITE LUB TURB ALTA P/D", 0, QApplication::UnicodeUTF8));
        lbNumNode_14->setText(QApplication::translate("LNET_DI", "14", 0, QApplication::UnicodeUTF8));
        lbNode_14->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNumNode_15->setText(QApplication::translate("LNET_DI", "15", 0, QApplication::UnicodeUTF8));
        lbNodeU_15->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_15->setText(QApplication::translate("LNET_DI", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_15->setText(QApplication::translate("LNET_DI", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_16->setText(QApplication::translate("LNET_DI", "16", 0, QApplication::UnicodeUTF8));
        lbNodeU_16->setText(QApplication::translate("LNET_DI", "NALM", 0, QApplication::UnicodeUTF8));
        lbNode_16->setText(QApplication::translate("LNET_DI", "1", 0, QApplication::UnicodeUTF8));
        lbNodeT_16->setText(QApplication::translate("LNET_DI", "FILTRO SEPARADO AIRE/ACEITE ALTA P/D", 0, QApplication::UnicodeUTF8));
        btCerrar->setText(QApplication::translate("LNET_DI", "CERRAR", 0, QApplication::UnicodeUTF8));
        lbFondo->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class LNET_DI: public Ui_LNET_DI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LNET_DI_H
