/********************************************************************************
** Form generated from reading UI file 'menu.ui'
**
** Created: Tue 10. Dec 18:43:55 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MENU_H
#define UI_MENU_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "Componets/qlabelclick.h"

QT_BEGIN_NAMESPACE

class Ui_Menu
{
public:
    QFrame *frame;
    QLabel *label_17;
    QLabelClick *lb_A1_1;
    QLabelClick *lb_A2_1;
    QLabelClick *lb_A3_1;
    QLabelClick *lb_A4_1;
    QLabelClick *lb_A5_1;
    QLabelClick *lb_A6_1;
    QFrame *line_2;
    QFrame *line_7;
    QFrame *line_12;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *frame_3;
    QLabel *label_19;
    QLabelClick *lb_C1_1;
    QLabelClick *lb_C2_1;
    QLabelClick *lb_C3_1;
    QLabelClick *lb_C4_1;
    QLabelClick *lb_C5_1;
    QFrame *frame_4;
    QLabel *label_20;
    QLabelClick *lb_D1_1;
    QLabelClick *lb_D2_1;
    QLabelClick *lb_D3_1;
    QLabelClick *lb_D4_1;
    QLabelClick *lb_D5_1;
    QLabelClick *lb_D6_1;
    QLabelClick *lb_D7_1;
    QLabelClick *lb_D8_1;
    QLabelClick *lb_D9_1;
    QFrame *frame_6;
    QLabel *label_22;
    QLabelClick *lb_F1_1;
    QLabelClick *lb_F2_1;
    QLabelClick *lb_F3_1;
    QLabelClick *lb_F4_1;
    QLabelClick *lb_F5_1;
    QFrame *frame_5;
    QLabel *label_21;
    QLabelClick *lb_E1_1;
    QLabelClick *lb_E2_1;
    QLabelClick *lb_E3_1;
    QFrame *frame_2;
    QLabel *label_18;
    QLabelClick *lb_B8_1;
    QLabelClick *lb_B9_1;
    QLabelClick *lb_B1_1;
    QLabelClick *lb_B11_1;
    QLabelClick *lb_B2_1;
    QLabelClick *lb_B12_1;
    QLabel *lb_B13_1;
    QLabelClick *lb_B14_1;
    QLabelClick *lb_B10_1;
    QLabelClick *lb_B7_1;
    QLabelClick *lb_B5_1;
    QLabelClick *lb_B6_1;
    QLabelClick *lb_B3_1;
    QLabelClick *lb_B4_1;
    QLabel *BackGround;
    QPushButton *btnBOP;

    void setupUi(QWidget *Menu)
    {
        if (Menu->objectName().isEmpty())
            Menu->setObjectName(QString::fromUtf8("Menu"));
        Menu->resize(1024, 662);
        Menu->setMinimumSize(QSize(1024, 662));
        Menu->setMaximumSize(QSize(1024, 662));
        Menu->setAutoFillBackground(false);
        frame = new QFrame(Menu);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(420, 30, 321, 179));
        QFont font;
        font.setPointSize(7);
        frame->setFont(font);
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        label_17 = new QLabel(frame);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(30, 10, 131, 21));
        label_17->setMinimumSize(QSize(131, 21));
        QFont font1;
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setUnderline(true);
        font1.setWeight(75);
        label_17->setFont(font1);
        label_17->setAlignment(Qt::AlignCenter);
        lb_A1_1 = new QLabelClick(frame);
        lb_A1_1->setObjectName(QString::fromUtf8("lb_A1_1"));
        lb_A1_1->setGeometry(QRect(10, 37, 291, 17));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Agency FB"));
        font2.setPointSize(10);
        font2.setBold(true);
        font2.setUnderline(false);
        font2.setWeight(75);
        lb_A1_1->setFont(font2);
        lb_A1_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_A1_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_A2_1 = new QLabelClick(frame);
        lb_A2_1->setObjectName(QString::fromUtf8("lb_A2_1"));
        lb_A2_1->setGeometry(QRect(10, 58, 195, 17));
        lb_A2_1->setFont(font2);
        lb_A2_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_A2_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_A3_1 = new QLabelClick(frame);
        lb_A3_1->setObjectName(QString::fromUtf8("lb_A3_1"));
        lb_A3_1->setGeometry(QRect(10, 76, 195, 17));
        lb_A3_1->setFont(font2);
        lb_A3_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_A3_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_A4_1 = new QLabelClick(frame);
        lb_A4_1->setObjectName(QString::fromUtf8("lb_A4_1"));
        lb_A4_1->setGeometry(QRect(10, 96, 195, 17));
        lb_A4_1->setFont(font2);
        lb_A4_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_A4_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_A5_1 = new QLabelClick(frame);
        lb_A5_1->setObjectName(QString::fromUtf8("lb_A5_1"));
        lb_A5_1->setGeometry(QRect(10, 115, 195, 17));
        lb_A5_1->setFont(font2);
        lb_A5_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_A5_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_A6_1 = new QLabelClick(frame);
        lb_A6_1->setObjectName(QString::fromUtf8("lb_A6_1"));
        lb_A6_1->setGeometry(QRect(10, 135, 195, 17));
        lb_A6_1->setFont(font2);
        lb_A6_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_A6_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        line_2 = new QFrame(Menu);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(69, 251, 801, 20));
        line_2->setStyleSheet(QString::fromUtf8("background-color: none;"));
        line_2->setFrameShadow(QFrame::Plain);
        line_2->setLineWidth(2);
        line_2->setFrameShape(QFrame::HLine);
        line_7 = new QFrame(Menu);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(60, 260, 20, 33));
        line_7->setStyleSheet(QString::fromUtf8("background-color: none;"));
        line_7->setFrameShadow(QFrame::Plain);
        line_7->setLineWidth(2);
        line_7->setFrameShape(QFrame::VLine);
        line_12 = new QFrame(Menu);
        line_12->setObjectName(QString::fromUtf8("line_12"));
        line_12->setGeometry(QRect(502, 201, 20, 59));
        line_12->setStyleSheet(QString::fromUtf8("background-color: none;"));
        line_12->setFrameShadow(QFrame::Plain);
        line_12->setLineWidth(2);
        line_12->setFrameShape(QFrame::VLine);
        line_8 = new QFrame(Menu);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(240, 260, 20, 33));
        line_8->setStyleSheet(QString::fromUtf8("background-color: none;"));
        line_8->setFrameShadow(QFrame::Plain);
        line_8->setLineWidth(2);
        line_8->setFrameShape(QFrame::VLine);
        line_9 = new QFrame(Menu);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(470, 260, 20, 33));
        line_9->setStyleSheet(QString::fromUtf8("background-color: none;"));
        line_9->setFrameShadow(QFrame::Plain);
        line_9->setLineWidth(2);
        line_9->setFrameShape(QFrame::VLine);
        line_10 = new QFrame(Menu);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(675, 260, 20, 33));
        line_10->setStyleSheet(QString::fromUtf8("background-color: none;"));
        line_10->setFrameShadow(QFrame::Plain);
        line_10->setLineWidth(2);
        line_10->setFrameShape(QFrame::VLine);
        line_11 = new QFrame(Menu);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setGeometry(QRect(860, 260, 20, 33));
        line_11->setStyleSheet(QString::fromUtf8("background-color: none;"));
        line_11->setFrameShadow(QFrame::Plain);
        line_11->setLineWidth(2);
        line_11->setFrameShape(QFrame::VLine);
        frame_3 = new QFrame(Menu);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(196, 290, 167, 157));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        label_19 = new QLabel(frame_3);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(-20, 10, 131, 21));
        label_19->setMinimumSize(QSize(131, 21));
        label_19->setFont(font1);
        label_19->setAlignment(Qt::AlignCenter);
        lb_C1_1 = new QLabelClick(frame_3);
        lb_C1_1->setObjectName(QString::fromUtf8("lb_C1_1"));
        lb_C1_1->setGeometry(QRect(10, 40, 155, 17));
        lb_C1_1->setMinimumSize(QSize(20, 0));
        lb_C1_1->setFont(font2);
        lb_C1_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_C1_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_C2_1 = new QLabelClick(frame_3);
        lb_C2_1->setObjectName(QString::fromUtf8("lb_C2_1"));
        lb_C2_1->setGeometry(QRect(10, 60, 155, 17));
        lb_C2_1->setMinimumSize(QSize(20, 0));
        lb_C2_1->setFont(font2);
        lb_C2_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_C2_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_C3_1 = new QLabelClick(frame_3);
        lb_C3_1->setObjectName(QString::fromUtf8("lb_C3_1"));
        lb_C3_1->setGeometry(QRect(10, 80, 155, 17));
        lb_C3_1->setMinimumSize(QSize(20, 0));
        lb_C3_1->setFont(font2);
        lb_C3_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_C3_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_C4_1 = new QLabelClick(frame_3);
        lb_C4_1->setObjectName(QString::fromUtf8("lb_C4_1"));
        lb_C4_1->setGeometry(QRect(10, 98, 155, 17));
        lb_C4_1->setMinimumSize(QSize(20, 0));
        lb_C4_1->setFont(font2);
        lb_C4_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_C4_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_C5_1 = new QLabelClick(frame_3);
        lb_C5_1->setObjectName(QString::fromUtf8("lb_C5_1"));
        lb_C5_1->setGeometry(QRect(10, 118, 155, 17));
        lb_C5_1->setMinimumSize(QSize(20, 0));
        lb_C5_1->setFont(font2);
        lb_C5_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_C5_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_4 = new QFrame(Menu);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(396, 290, 219, 269));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        label_20 = new QLabel(frame_4);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 10, 131, 21));
        label_20->setMinimumSize(QSize(131, 21));
        label_20->setFont(font1);
        label_20->setAlignment(Qt::AlignCenter);
        lb_D1_1 = new QLabelClick(frame_4);
        lb_D1_1->setObjectName(QString::fromUtf8("lb_D1_1"));
        lb_D1_1->setGeometry(QRect(10, 39, 208, 17));
        lb_D1_1->setMinimumSize(QSize(20, 0));
        lb_D1_1->setFont(font2);
        lb_D1_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D1_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_D2_1 = new QLabelClick(frame_4);
        lb_D2_1->setObjectName(QString::fromUtf8("lb_D2_1"));
        lb_D2_1->setGeometry(QRect(10, 60, 208, 17));
        lb_D2_1->setMinimumSize(QSize(20, 0));
        lb_D2_1->setFont(font2);
        lb_D2_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D2_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_D3_1 = new QLabelClick(frame_4);
        lb_D3_1->setObjectName(QString::fromUtf8("lb_D3_1"));
        lb_D3_1->setGeometry(QRect(10, 80, 208, 17));
        lb_D3_1->setMinimumSize(QSize(20, 0));
        lb_D3_1->setFont(font2);
        lb_D3_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D3_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_D4_1 = new QLabelClick(frame_4);
        lb_D4_1->setObjectName(QString::fromUtf8("lb_D4_1"));
        lb_D4_1->setGeometry(QRect(10, 98, 208, 17));
        lb_D4_1->setMinimumSize(QSize(20, 0));
        lb_D4_1->setFont(font2);
        lb_D4_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D4_1->setLayoutDirection(Qt::RightToLeft);
        lb_D4_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_D5_1 = new QLabelClick(frame_4);
        lb_D5_1->setObjectName(QString::fromUtf8("lb_D5_1"));
        lb_D5_1->setGeometry(QRect(10, 118, 208, 17));
        lb_D5_1->setMinimumSize(QSize(20, 0));
        lb_D5_1->setFont(font2);
        lb_D5_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D5_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_D6_1 = new QLabelClick(frame_4);
        lb_D6_1->setObjectName(QString::fromUtf8("lb_D6_1"));
        lb_D6_1->setGeometry(QRect(10, 136, 208, 17));
        lb_D6_1->setMinimumSize(QSize(20, 0));
        lb_D6_1->setFont(font2);
        lb_D6_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D6_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_D7_1 = new QLabelClick(frame_4);
        lb_D7_1->setObjectName(QString::fromUtf8("lb_D7_1"));
        lb_D7_1->setGeometry(QRect(10, 155, 208, 17));
        lb_D7_1->setMinimumSize(QSize(20, 0));
        lb_D7_1->setFont(font2);
        lb_D7_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D7_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_D8_1 = new QLabelClick(frame_4);
        lb_D8_1->setObjectName(QString::fromUtf8("lb_D8_1"));
        lb_D8_1->setGeometry(QRect(10, 175, 208, 17));
        lb_D8_1->setMinimumSize(QSize(20, 0));
        lb_D8_1->setFont(font2);
        lb_D8_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D8_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_D9_1 = new QLabelClick(frame_4);
        lb_D9_1->setObjectName(QString::fromUtf8("lb_D9_1"));
        lb_D9_1->setGeometry(QRect(10, 195, 208, 17));
        lb_D9_1->setMinimumSize(QSize(20, 0));
        lb_D9_1->setFont(font2);
        lb_D9_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_D9_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_6 = new QFrame(Menu);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(804, 290, 192, 156));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        label_22 = new QLabel(frame_6);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(0, 10, 147, 21));
        label_22->setMinimumSize(QSize(140, 21));
        label_22->setFont(font1);
        label_22->setAlignment(Qt::AlignCenter);
        lb_F1_1 = new QLabelClick(frame_6);
        lb_F1_1->setObjectName(QString::fromUtf8("lb_F1_1"));
        lb_F1_1->setGeometry(QRect(10, 40, 180, 17));
        lb_F1_1->setMinimumSize(QSize(20, 0));
        lb_F1_1->setFont(font2);
        lb_F1_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_F1_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_F2_1 = new QLabelClick(frame_6);
        lb_F2_1->setObjectName(QString::fromUtf8("lb_F2_1"));
        lb_F2_1->setGeometry(QRect(10, 60, 180, 17));
        lb_F2_1->setMinimumSize(QSize(20, 0));
        lb_F2_1->setFont(font2);
        lb_F2_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_F2_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_F3_1 = new QLabelClick(frame_6);
        lb_F3_1->setObjectName(QString::fromUtf8("lb_F3_1"));
        lb_F3_1->setGeometry(QRect(10, 80, 180, 17));
        lb_F3_1->setMinimumSize(QSize(20, 0));
        lb_F3_1->setFont(font2);
        lb_F3_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_F3_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_F4_1 = new QLabelClick(frame_6);
        lb_F4_1->setObjectName(QString::fromUtf8("lb_F4_1"));
        lb_F4_1->setGeometry(QRect(10, 98, 180, 17));
        lb_F4_1->setMinimumSize(QSize(20, 0));
        lb_F4_1->setFont(font2);
        lb_F4_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_F4_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_F5_1 = new QLabelClick(frame_6);
        lb_F5_1->setObjectName(QString::fromUtf8("lb_F5_1"));
        lb_F5_1->setGeometry(QRect(10, 118, 180, 17));
        lb_F5_1->setMinimumSize(QSize(20, 0));
        lb_F5_1->setFont(font2);
        lb_F5_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_F5_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_5 = new QFrame(Menu);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(630, 290, 156, 110));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        label_21 = new QLabel(frame_5);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(-20, 10, 131, 21));
        label_21->setMinimumSize(QSize(131, 21));
        label_21->setFont(font1);
        label_21->setAlignment(Qt::AlignCenter);
        lb_E1_1 = new QLabelClick(frame_5);
        lb_E1_1->setObjectName(QString::fromUtf8("lb_E1_1"));
        lb_E1_1->setGeometry(QRect(10, 40, 143, 17));
        lb_E1_1->setMinimumSize(QSize(20, 0));
        lb_E1_1->setFont(font2);
        lb_E1_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_E1_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_E2_1 = new QLabelClick(frame_5);
        lb_E2_1->setObjectName(QString::fromUtf8("lb_E2_1"));
        lb_E2_1->setGeometry(QRect(10, 60, 143, 17));
        lb_E2_1->setMinimumSize(QSize(20, 0));
        lb_E2_1->setFont(font2);
        lb_E2_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_E2_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_E3_1 = new QLabelClick(frame_5);
        lb_E3_1->setObjectName(QString::fromUtf8("lb_E3_1"));
        lb_E3_1->setGeometry(QRect(10, 79, 143, 17));
        lb_E3_1->setMinimumSize(QSize(20, 0));
        lb_E3_1->setFont(font2);
        lb_E3_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_E3_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_2 = new QFrame(Menu);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(8, 290, 191, 320));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_18 = new QLabel(frame_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(0, 10, 131, 21));
        label_18->setMinimumSize(QSize(131, 21));
        label_18->setFont(font1);
        label_18->setAlignment(Qt::AlignCenter);
        lb_B8_1 = new QLabelClick(frame_2);
        lb_B8_1->setObjectName(QString::fromUtf8("lb_B8_1"));
        lb_B8_1->setGeometry(QRect(10, 175, 158, 17));
        lb_B8_1->setMinimumSize(QSize(20, 0));
        lb_B8_1->setFont(font2);
        lb_B8_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B8_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B9_1 = new QLabelClick(frame_2);
        lb_B9_1->setObjectName(QString::fromUtf8("lb_B9_1"));
        lb_B9_1->setGeometry(QRect(10, 195, 158, 17));
        lb_B9_1->setMinimumSize(QSize(20, 0));
        lb_B9_1->setFont(font2);
        lb_B9_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B9_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B1_1 = new QLabelClick(frame_2);
        lb_B1_1->setObjectName(QString::fromUtf8("lb_B1_1"));
        lb_B1_1->setGeometry(QRect(10, 40, 158, 17));
        lb_B1_1->setMinimumSize(QSize(20, 0));
        lb_B1_1->setFont(font2);
        lb_B1_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B1_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B11_1 = new QLabelClick(frame_2);
        lb_B11_1->setObjectName(QString::fromUtf8("lb_B11_1"));
        lb_B11_1->setGeometry(QRect(10, 235, 158, 17));
        lb_B11_1->setMinimumSize(QSize(20, 0));
        lb_B11_1->setFont(font2);
        lb_B11_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B11_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B2_1 = new QLabelClick(frame_2);
        lb_B2_1->setObjectName(QString::fromUtf8("lb_B2_1"));
        lb_B2_1->setGeometry(QRect(10, 61, 171, 17));
        lb_B2_1->setMinimumSize(QSize(20, 0));
        lb_B2_1->setFont(font2);
        lb_B2_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B2_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B12_1 = new QLabelClick(frame_2);
        lb_B12_1->setObjectName(QString::fromUtf8("lb_B12_1"));
        lb_B12_1->setGeometry(QRect(10, 253, 158, 17));
        lb_B12_1->setMinimumSize(QSize(20, 0));
        lb_B12_1->setFont(font2);
        lb_B12_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B12_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B13_1 = new QLabel(frame_2);
        lb_B13_1->setObjectName(QString::fromUtf8("lb_B13_1"));
        lb_B13_1->setGeometry(QRect(10, 273, 158, 17));
        lb_B13_1->setMinimumSize(QSize(20, 0));
        lb_B13_1->setFont(font2);
        lb_B13_1->setCursor(QCursor(Qt::ArrowCursor));
        lb_B13_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B14_1 = new QLabelClick(frame_2);
        lb_B14_1->setObjectName(QString::fromUtf8("lb_B14_1"));
        lb_B14_1->setGeometry(QRect(10, 293, 158, 17));
        lb_B14_1->setMinimumSize(QSize(20, 0));
        lb_B14_1->setFont(font2);
        lb_B14_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B14_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B10_1 = new QLabelClick(frame_2);
        lb_B10_1->setObjectName(QString::fromUtf8("lb_B10_1"));
        lb_B10_1->setGeometry(QRect(10, 215, 158, 17));
        lb_B10_1->setMinimumSize(QSize(20, 0));
        lb_B10_1->setFont(font2);
        lb_B10_1->setCursor(QCursor(Qt::ArrowCursor));
        lb_B10_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B7_1 = new QLabelClick(frame_2);
        lb_B7_1->setObjectName(QString::fromUtf8("lb_B7_1"));
        lb_B7_1->setGeometry(QRect(10, 155, 158, 17));
        lb_B7_1->setMinimumSize(QSize(20, 0));
        lb_B7_1->setFont(font2);
        lb_B7_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B7_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B5_1 = new QLabelClick(frame_2);
        lb_B5_1->setObjectName(QString::fromUtf8("lb_B5_1"));
        lb_B5_1->setGeometry(QRect(10, 118, 158, 17));
        lb_B5_1->setMinimumSize(QSize(20, 0));
        lb_B5_1->setFont(font2);
        lb_B5_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B5_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B6_1 = new QLabelClick(frame_2);
        lb_B6_1->setObjectName(QString::fromUtf8("lb_B6_1"));
        lb_B6_1->setGeometry(QRect(10, 135, 158, 17));
        lb_B6_1->setMinimumSize(QSize(20, 0));
        lb_B6_1->setFont(font2);
        lb_B6_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B6_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B3_1 = new QLabelClick(frame_2);
        lb_B3_1->setObjectName(QString::fromUtf8("lb_B3_1"));
        lb_B3_1->setGeometry(QRect(10, 80, 158, 17));
        lb_B3_1->setMinimumSize(QSize(20, 0));
        lb_B3_1->setFont(font2);
        lb_B3_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B3_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_B4_1 = new QLabelClick(frame_2);
        lb_B4_1->setObjectName(QString::fromUtf8("lb_B4_1"));
        lb_B4_1->setGeometry(QRect(10, 98, 158, 17));
        lb_B4_1->setMinimumSize(QSize(20, 0));
        lb_B4_1->setFont(font2);
        lb_B4_1->setCursor(QCursor(Qt::PointingHandCursor));
        lb_B4_1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        BackGround = new QLabel(Menu);
        BackGround->setObjectName(QString::fromUtf8("BackGround"));
        BackGround->setGeometry(QRect(0, 0, 1024, 663));
        BackGround->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/BackGround.png")));
        BackGround->setScaledContents(true);
        btnBOP = new QPushButton(Menu);
        btnBOP->setObjectName(QString::fromUtf8("btnBOP"));
        btnBOP->setGeometry(QRect(830, 610, 131, 21));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(true);
        font3.setWeight(75);
        btnBOP->setFont(font3);
        btnBOP->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        BackGround->raise();
        frame->raise();
        line_2->raise();
        line_7->raise();
        line_12->raise();
        line_8->raise();
        line_9->raise();
        line_10->raise();
        line_11->raise();
        frame_3->raise();
        frame_4->raise();
        frame_6->raise();
        frame_5->raise();
        frame_2->raise();
        btnBOP->raise();

        retranslateUi(Menu);

        QMetaObject::connectSlotsByName(Menu);
    } // setupUi

    void retranslateUi(QWidget *Menu)
    {
        Menu->setWindowTitle(QApplication::translate("Menu", "Form", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("Menu", "PRINCIPAL", 0, QApplication::UnicodeUTF8));
        lb_A1_1->setText(QApplication::translate("Menu", "A1     GENERALIDADES TURBINA PRINCIPAL", 0, QApplication::UnicodeUTF8));
        lb_A2_1->setText(QApplication::translate("Menu", "A2    GENERADOR", 0, QApplication::UnicodeUTF8));
        lb_A3_1->setText(QApplication::translate("Menu", "A3    SECUENCIA DE ARRANQUE", 0, QApplication::UnicodeUTF8));
        lb_A4_1->setText(QApplication::translate("Menu", "A4    SECUENCIA PARA PARO", 0, QApplication::UnicodeUTF8));
        lb_A5_1->setText(QApplication::translate("Menu", "A5    PERMISOS DE ARRANQUE", 0, QApplication::UnicodeUTF8));
        lb_A6_1->setText(QApplication::translate("Menu", "A6    PERMISOS DE ROTACI\303\223N", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("Menu", "MONITOR", 0, QApplication::UnicodeUTF8));
        lb_C1_1->setText(QApplication::translate("Menu", "C1   REGULADOR DE CONTROL", 0, QApplication::UnicodeUTF8));
        lb_C2_1->setText(QApplication::translate("Menu", "C2  TEMP. ENTRADAS PT", 0, QApplication::UnicodeUTF8));
        lb_C3_1->setText(QApplication::translate("Menu", "C3  TEMPS. BOBINADO ESTATOR", 0, QApplication::UnicodeUTF8));
        lb_C4_1->setText(QApplication::translate("Menu", "C4  VIBRACIONES", 0, QApplication::UnicodeUTF8));
        lb_C5_1->setText(QApplication::translate("Menu", "C5  DATOS DE OPERACI\303\223N", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("Menu", "UTILER\303\215A", 0, QApplication::UnicodeUTF8));
        lb_D1_1->setText(QApplication::translate("Menu", "D1   GENERALIDADES DE MICRONET", 0, QApplication::UnicodeUTF8));
        lb_D2_1->setText(QApplication::translate("Menu", "D2  GENERALIDADES DE LINKNET", 0, QApplication::UnicodeUTF8));
        lb_D3_1->setText(QApplication::translate("Menu", "D3  GENERALIDADES DE LINKNET", 0, QApplication::UnicodeUTF8));
        lb_D4_1->setText(QApplication::translate("Menu", "D4  GENERALIDADES DE ACONDICIONAMIENTO", 0, QApplication::UnicodeUTF8));
        lb_D5_1->setText(QApplication::translate("Menu", "D5  REPORTE DE DATOS DE LA TURBINA", 0, QApplication::UnicodeUTF8));
        lb_D6_1->setText(QApplication::translate("Menu", "D6  REPORTE DE DATOS DE LA TURBINA", 0, QApplication::UnicodeUTF8));
        lb_D7_1->setText(QApplication::translate("Menu", "D7  REPORTE DE DATOS DE GENERADOR", 0, QApplication::UnicodeUTF8));
        lb_D8_1->setText(QApplication::translate("Menu", "D8  MAPEO COMBUSTOR", 0, QApplication::UnicodeUTF8));
        lb_D9_1->setText(QApplication::translate("Menu", "D9  CALIBRACI\303\223N DEL IMPULSOR", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("Menu", "RESUMEN DE ALARMAS", 0, QApplication::UnicodeUTF8));
        lb_F1_1->setText(QApplication::translate("Menu", "F1   RESUMEN  DE ALARMAS", 0, QApplication::UnicodeUTF8));
        lb_F2_1->setText(QApplication::translate("Menu", "F2  DETENCION NORM/DESACEL. A MIN.", 0, QApplication::UnicodeUTF8));
        lb_F3_1->setText(QApplication::translate("Menu", "F3  DESACEL A MIN./PASO A RALENT\303\215.", 0, QApplication::UnicodeUTF8));
        lb_F4_1->setText(QApplication::translate("Menu", "F4  APAGADOS DE EMERGENCIA", 0, QApplication::UnicodeUTF8));
        lb_F5_1->setText(QApplication::translate("Menu", "F5  APAGADOS DE EMERGENCIA", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("Menu", "TENDENCIAS", 0, QApplication::UnicodeUTF8));
        lb_E1_1->setText(QApplication::translate("Menu", "E1   DATOS DE LA TURBINA", 0, QApplication::UnicodeUTF8));
        lb_E2_1->setText(QApplication::translate("Menu", "E2  DATOS DEL COMB. Y AGUA", 0, QApplication::UnicodeUTF8));
        lb_E3_1->setText(QApplication::translate("Menu", "E3  DATOS DEL ACEITE LUB.", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("Menu", "SISTEMAS", 0, QApplication::UnicodeUTF8));
        lb_B8_1->setText(QApplication::translate("Menu", "B8  V\303\201LVULAS DE ETAPAS", 0, QApplication::UnicodeUTF8));
        lb_B9_1->setText(QApplication::translate("Menu", "B9  CARCASA DE TURBINA", 0, QApplication::UnicodeUTF8));
        lb_B1_1->setText(QApplication::translate("Menu", "B1   ACEITE LUB. DE GEN. 1", 0, QApplication::UnicodeUTF8));
        lb_B11_1->setText(QApplication::translate("Menu", "B11  CARCASA DE GENERADOR", 0, QApplication::UnicodeUTF8));
        lb_B2_1->setText(QApplication::translate("Menu", "B2  ACEITE LUB. DE GEN. 2", 0, QApplication::UnicodeUTF8));
        lb_B12_1->setText(QApplication::translate("Menu", "B12  PROTECCI\303\223N CONTRA FUEGO", 0, QApplication::UnicodeUTF8));
        lb_B13_1->setText(QApplication::translate("Menu", "B13  --DISPONIBLE--", 0, QApplication::UnicodeUTF8));
        lb_B14_1->setText(QApplication::translate("Menu", "B14  LAVADO CON AGUA", 0, QApplication::UnicodeUTF8));
        lb_B10_1->setText(QApplication::translate("Menu", "B10  --DISPONIBLE--", 0, QApplication::UnicodeUTF8));
        lb_B7_1->setText(QApplication::translate("Menu", "B7 SISTEMA DE COMBUSTIBLE 2", 0, QApplication::UnicodeUTF8));
        lb_B5_1->setText(QApplication::translate("Menu", "B5  GENERALIDADES DE LA TURB.", 0, QApplication::UnicodeUTF8));
        lb_B6_1->setText(QApplication::translate("Menu", "B6  SISTEMA DE COMBUSTIBLE 1", 0, QApplication::UnicodeUTF8));
        lb_B3_1->setText(QApplication::translate("Menu", "B3  ACEITE LUB. DE TURBINA", 0, QApplication::UnicodeUTF8));
        lb_B4_1->setText(QApplication::translate("Menu", "B4  MOTOR HIDR. DE ARRANQUE", 0, QApplication::UnicodeUTF8));
        BackGround->setText(QString());
        btnBOP->setText(QApplication::translate("Menu", "BOP", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Menu: public Ui_Menu {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MENU_H
