/********************************************************************************
** Form generated from reading UI file 'sistema_electrico.ui'
**
** Created: Mon 2. Dec 19:01:08 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SISTEMA_ELECTRICO_H
#define UI_SISTEMA_ELECTRICO_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Sistema_Electrico
{
public:
    QLabel *label_5;
    QLabel *label_39;
    QCheckBox *checkBox_8;
    QTextEdit *txt27;
    QCheckBox *checkBox_5;
    QLabel *label_19;
    QLabel *label_36;
    QLabel *label_30;
    QCheckBox *checkBox_11;
    QTextEdit *txt18;
    QCheckBox *checkBox_3;
    QTextEdit *txt9;
    QLabel *label_14;
    QTextEdit *txt14;
    QTextEdit *txt35;
    QLabel *label_27;
    QTextEdit *txt6;
    QTextEdit *txt2;
    QTextEdit *txt31;
    QTextEdit *txt39;
    QLabel *label_21;
    QTextEdit *txt28;
    QLabel *label_16;
    QTextEdit *txt4;
    QTextEdit *txt3;
    QCheckBox *checkBox_14;
    QLabel *label_17;
    QCheckBox *checkBox_6;
    QLabel *label;
    QLabel *label_23;
    QTextEdit *txt22;
    QTextEdit *txt15;
    QLabel *label_7;
    QTextEdit *txt16;
    QTextEdit *txt7;
    QLabel *label_10;
    QCheckBox *checkBox_12;
    QTextEdit *txt10;
    QTextEdit *txt32;
    QLabel *label_38;
    QTextEdit *txt40;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox;
    QLabel *label_3;
    QLabel *label_35;
    QLabel *label_29;
    QTextEdit *txt25;
    QLabel *label_13;
    QLabel *label_26;
    QTextEdit *txt38;
    QLabel *label_6;
    QTextEdit *txt37;
    QCheckBox *checkBox_9;
    QTextEdit *txt23;
    QLabel *label_33;
    QTextEdit *txt36;
    QLabel *label_20;
    QTextEdit *txt8;
    QLabel *label_40;
    QTextEdit *txt20;
    QTextEdit *txt19;
    QTextEdit *txt12;
    QTextEdit *txt11;
    QPushButton *btn1;
    QTextEdit *txt33;
    QCheckBox *checkBox_7;
    QLabel *label_15;
    QTextEdit *txt30;
    QTextEdit *txt29;
    QLabel *label_22;
    QCheckBox *checkBox_2;
    QLabel *label_32;
    QLabel *label_4;
    QLabel *label_37;
    QTextEdit *txt17;
    QTextEdit *txt21;
    QTextEdit *txt13;
    QLabel *label_31;
    QTextEdit *txt34;
    QCheckBox *checkBox_10;
    QLabel *label_18;
    QLabel *label_2;
    QLabel *label_34;
    QLabel *label_24;
    QTextEdit *txt5;
    QLabel *label_28;
    QTextEdit *txt1;
    QLabel *label_8;
    QLabel *label_12;
    QLabel *label_25;
    QPushButton *btn2;
    QCheckBox *checkBox_13;

    void setupUi(QWidget *Sistema_Electrico)
    {
        if (Sistema_Electrico->objectName().isEmpty())
            Sistema_Electrico->setObjectName(QString::fromUtf8("Sistema_Electrico"));
        Sistema_Electrico->resize(1140, 779);
        label_5 = new QLabel(Sistema_Electrico);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(490, 40, 271, 21));
        label_39 = new QLabel(Sistema_Electrico);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(510, 600, 271, 21));
        checkBox_8 = new QCheckBox(Sistema_Electrico);
        checkBox_8->setObjectName(QString::fromUtf8("checkBox_8"));
        checkBox_8->setGeometry(QRect(880, 430, 271, 20));
        txt27 = new QTextEdit(Sistema_Electrico);
        txt27->setObjectName(QString::fromUtf8("txt27"));
        txt27->setGeometry(QRect(10, 190, 104, 21));
        txt27->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt27->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        checkBox_5 = new QCheckBox(Sistema_Electrico);
        checkBox_5->setObjectName(QString::fromUtf8("checkBox_5"));
        checkBox_5->setGeometry(QRect(880, 340, 271, 20));
        label_19 = new QLabel(Sistema_Electrico);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(490, 160, 231, 21));
        label_36 = new QLabel(Sistema_Electrico);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(120, 710, 201, 21));
        label_30 = new QLabel(Sistema_Electrico);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(490, 330, 251, 21));
        checkBox_11 = new QCheckBox(Sistema_Electrico);
        checkBox_11->setObjectName(QString::fromUtf8("checkBox_11"));
        checkBox_11->setGeometry(QRect(880, 520, 281, 20));
        txt18 = new QTextEdit(Sistema_Electrico);
        txt18->setObjectName(QString::fromUtf8("txt18"));
        txt18->setGeometry(QRect(10, 70, 104, 21));
        txt18->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt18->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        checkBox_3 = new QCheckBox(Sistema_Electrico);
        checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
        checkBox_3->setGeometry(QRect(880, 280, 271, 20));
        txt9 = new QTextEdit(Sistema_Electrico);
        txt9->setObjectName(QString::fromUtf8("txt9"));
        txt9->setGeometry(QRect(380, 190, 104, 21));
        txt9->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt9->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_14 = new QLabel(Sistema_Electrico);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(120, 270, 171, 21));
        txt14 = new QTextEdit(Sistema_Electrico);
        txt14->setObjectName(QString::fromUtf8("txt14"));
        txt14->setGeometry(QRect(10, 440, 104, 21));
        txt14->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt14->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt35 = new QTextEdit(Sistema_Electrico);
        txt35->setObjectName(QString::fromUtf8("txt35"));
        txt35->setGeometry(QRect(400, 570, 104, 21));
        txt35->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt35->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_27 = new QLabel(Sistema_Electrico);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(490, 500, 261, 21));
        txt6 = new QTextEdit(Sistema_Electrico);
        txt6->setObjectName(QString::fromUtf8("txt6"));
        txt6->setGeometry(QRect(10, 360, 104, 21));
        txt6->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt6->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt2 = new QTextEdit(Sistema_Electrico);
        txt2->setObjectName(QString::fromUtf8("txt2"));
        txt2->setGeometry(QRect(380, 10, 104, 21));
        txt2->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt2->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt31 = new QTextEdit(Sistema_Electrico);
        txt31->setObjectName(QString::fromUtf8("txt31"));
        txt31->setGeometry(QRect(380, 440, 104, 21));
        txt31->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt31->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt39 = new QTextEdit(Sistema_Electrico);
        txt39->setObjectName(QString::fromUtf8("txt39"));
        txt39->setGeometry(QRect(10, 740, 104, 21));
        txt39->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt39->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_21 = new QLabel(Sistema_Electrico);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(490, 220, 241, 21));
        txt28 = new QTextEdit(Sistema_Electrico);
        txt28->setObjectName(QString::fromUtf8("txt28"));
        txt28->setGeometry(QRect(10, 220, 104, 21));
        txt28->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt28->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_16 = new QLabel(Sistema_Electrico);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(120, 330, 171, 21));
        txt4 = new QTextEdit(Sistema_Electrico);
        txt4->setObjectName(QString::fromUtf8("txt4"));
        txt4->setGeometry(QRect(10, 300, 104, 21));
        txt4->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt4->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt3 = new QTextEdit(Sistema_Electrico);
        txt3->setObjectName(QString::fromUtf8("txt3"));
        txt3->setGeometry(QRect(10, 270, 104, 21));
        txt3->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt3->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        checkBox_14 = new QCheckBox(Sistema_Electrico);
        checkBox_14->setObjectName(QString::fromUtf8("checkBox_14"));
        checkBox_14->setGeometry(QRect(880, 610, 251, 20));
        label_17 = new QLabel(Sistema_Electrico);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(120, 360, 171, 21));
        checkBox_6 = new QCheckBox(Sistema_Electrico);
        checkBox_6->setObjectName(QString::fromUtf8("checkBox_6"));
        checkBox_6->setGeometry(QRect(880, 370, 271, 20));
        label = new QLabel(Sistema_Electrico);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(120, 40, 251, 21));
        label_23 = new QLabel(Sistema_Electrico);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(120, 470, 261, 21));
        txt22 = new QTextEdit(Sistema_Electrico);
        txt22->setObjectName(QString::fromUtf8("txt22"));
        txt22->setGeometry(QRect(380, 100, 104, 21));
        txt22->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt22->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt15 = new QTextEdit(Sistema_Electrico);
        txt15->setObjectName(QString::fromUtf8("txt15"));
        txt15->setGeometry(QRect(10, 470, 104, 21));
        txt15->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt15->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_7 = new QLabel(Sistema_Electrico);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(490, 100, 261, 21));
        txt16 = new QTextEdit(Sistema_Electrico);
        txt16->setObjectName(QString::fromUtf8("txt16"));
        txt16->setGeometry(QRect(10, 500, 104, 21));
        txt16->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt16->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt7 = new QTextEdit(Sistema_Electrico);
        txt7->setObjectName(QString::fromUtf8("txt7"));
        txt7->setGeometry(QRect(10, 390, 104, 21));
        txt7->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt7->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_10 = new QLabel(Sistema_Electrico);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(120, 160, 241, 21));
        checkBox_12 = new QCheckBox(Sistema_Electrico);
        checkBox_12->setObjectName(QString::fromUtf8("checkBox_12"));
        checkBox_12->setGeometry(QRect(880, 550, 281, 20));
        txt10 = new QTextEdit(Sistema_Electrico);
        txt10->setObjectName(QString::fromUtf8("txt10"));
        txt10->setGeometry(QRect(380, 220, 104, 21));
        txt10->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt10->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt32 = new QTextEdit(Sistema_Electrico);
        txt32->setObjectName(QString::fromUtf8("txt32"));
        txt32->setGeometry(QRect(380, 470, 104, 21));
        txt32->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt32->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_38 = new QLabel(Sistema_Electrico);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(510, 570, 271, 21));
        txt40 = new QTextEdit(Sistema_Electrico);
        txt40->setObjectName(QString::fromUtf8("txt40"));
        txt40->setGeometry(QRect(10, 680, 104, 21));
        txt40->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt40->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        checkBox_4 = new QCheckBox(Sistema_Electrico);
        checkBox_4->setObjectName(QString::fromUtf8("checkBox_4"));
        checkBox_4->setGeometry(QRect(880, 310, 281, 20));
        checkBox = new QCheckBox(Sistema_Electrico);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(880, 220, 231, 20));
        label_3 = new QLabel(Sistema_Electrico);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(490, 10, 81, 21));
        label_35 = new QLabel(Sistema_Electrico);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(120, 680, 151, 21));
        label_29 = new QLabel(Sistema_Electrico);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(490, 300, 251, 21));
        txt25 = new QTextEdit(Sistema_Electrico);
        txt25->setObjectName(QString::fromUtf8("txt25"));
        txt25->setGeometry(QRect(10, 160, 104, 21));
        txt25->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt25->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_13 = new QLabel(Sistema_Electrico);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(120, 220, 191, 21));
        label_26 = new QLabel(Sistema_Electrico);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(490, 470, 261, 21));
        txt38 = new QTextEdit(Sistema_Electrico);
        txt38->setObjectName(QString::fromUtf8("txt38"));
        txt38->setGeometry(QRect(10, 710, 104, 21));
        txt38->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt38->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_6 = new QLabel(Sistema_Electrico);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(490, 70, 261, 21));
        txt37 = new QTextEdit(Sistema_Electrico);
        txt37->setObjectName(QString::fromUtf8("txt37"));
        txt37->setGeometry(QRect(10, 650, 104, 21));
        txt37->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt37->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        checkBox_9 = new QCheckBox(Sistema_Electrico);
        checkBox_9->setObjectName(QString::fromUtf8("checkBox_9"));
        checkBox_9->setGeometry(QRect(880, 460, 281, 20));
        txt23 = new QTextEdit(Sistema_Electrico);
        txt23->setObjectName(QString::fromUtf8("txt23"));
        txt23->setGeometry(QRect(10, 10, 104, 21));
        txt23->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt23->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_33 = new QLabel(Sistema_Electrico);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(120, 600, 271, 21));
        txt36 = new QTextEdit(Sistema_Electrico);
        txt36->setObjectName(QString::fromUtf8("txt36"));
        txt36->setGeometry(QRect(400, 600, 104, 21));
        txt36->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt36->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_20 = new QLabel(Sistema_Electrico);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(490, 190, 241, 21));
        txt8 = new QTextEdit(Sistema_Electrico);
        txt8->setObjectName(QString::fromUtf8("txt8"));
        txt8->setGeometry(QRect(380, 160, 104, 21));
        txt8->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt8->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_40 = new QLabel(Sistema_Electrico);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(120, 740, 131, 21));
        txt20 = new QTextEdit(Sistema_Electrico);
        txt20->setObjectName(QString::fromUtf8("txt20"));
        txt20->setGeometry(QRect(380, 40, 104, 21));
        txt20->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt20->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt19 = new QTextEdit(Sistema_Electrico);
        txt19->setObjectName(QString::fromUtf8("txt19"));
        txt19->setGeometry(QRect(10, 100, 104, 21));
        txt19->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt19->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt12 = new QTextEdit(Sistema_Electrico);
        txt12->setObjectName(QString::fromUtf8("txt12"));
        txt12->setGeometry(QRect(380, 300, 104, 21));
        txt12->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt12->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt11 = new QTextEdit(Sistema_Electrico);
        txt11->setObjectName(QString::fromUtf8("txt11"));
        txt11->setGeometry(QRect(380, 270, 104, 21));
        txt11->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt11->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        btn1 = new QPushButton(Sistema_Electrico);
        btn1->setObjectName(QString::fromUtf8("btn1"));
        btn1->setGeometry(QRect(410, 670, 93, 28));
        txt33 = new QTextEdit(Sistema_Electrico);
        txt33->setObjectName(QString::fromUtf8("txt33"));
        txt33->setGeometry(QRect(380, 500, 104, 21));
        txt33->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt33->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        checkBox_7 = new QCheckBox(Sistema_Electrico);
        checkBox_7->setObjectName(QString::fromUtf8("checkBox_7"));
        checkBox_7->setGeometry(QRect(880, 400, 251, 20));
        label_15 = new QLabel(Sistema_Electrico);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(120, 300, 171, 21));
        txt30 = new QTextEdit(Sistema_Electrico);
        txt30->setObjectName(QString::fromUtf8("txt30"));
        txt30->setGeometry(QRect(10, 600, 104, 21));
        txt30->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt30->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt29 = new QTextEdit(Sistema_Electrico);
        txt29->setObjectName(QString::fromUtf8("txt29"));
        txt29->setGeometry(QRect(10, 570, 104, 21));
        txt29->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt29->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_22 = new QLabel(Sistema_Electrico);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(120, 440, 261, 21));
        checkBox_2 = new QCheckBox(Sistema_Electrico);
        checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));
        checkBox_2->setGeometry(QRect(880, 250, 231, 20));
        label_32 = new QLabel(Sistema_Electrico);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(120, 570, 271, 21));
        label_4 = new QLabel(Sistema_Electrico);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(120, 100, 251, 21));
        label_37 = new QLabel(Sistema_Electrico);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(510, 540, 271, 21));
        txt17 = new QTextEdit(Sistema_Electrico);
        txt17->setObjectName(QString::fromUtf8("txt17"));
        txt17->setGeometry(QRect(10, 540, 104, 21));
        txt17->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt17->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt21 = new QTextEdit(Sistema_Electrico);
        txt21->setObjectName(QString::fromUtf8("txt21"));
        txt21->setGeometry(QRect(380, 70, 104, 21));
        txt21->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt21->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt13 = new QTextEdit(Sistema_Electrico);
        txt13->setObjectName(QString::fromUtf8("txt13"));
        txt13->setGeometry(QRect(380, 330, 104, 21));
        txt13->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt13->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_31 = new QLabel(Sistema_Electrico);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(120, 540, 271, 21));
        txt34 = new QTextEdit(Sistema_Electrico);
        txt34->setObjectName(QString::fromUtf8("txt34"));
        txt34->setGeometry(QRect(400, 540, 104, 21));
        txt34->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt34->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        checkBox_10 = new QCheckBox(Sistema_Electrico);
        checkBox_10->setObjectName(QString::fromUtf8("checkBox_10"));
        checkBox_10->setGeometry(QRect(880, 490, 271, 20));
        label_18 = new QLabel(Sistema_Electrico);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(120, 390, 151, 21));
        label_2 = new QLabel(Sistema_Electrico);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(120, 70, 251, 21));
        label_34 = new QLabel(Sistema_Electrico);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(120, 650, 161, 21));
        label_24 = new QLabel(Sistema_Electrico);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(120, 500, 261, 21));
        txt5 = new QTextEdit(Sistema_Electrico);
        txt5->setObjectName(QString::fromUtf8("txt5"));
        txt5->setGeometry(QRect(10, 330, 104, 21));
        txt5->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt5->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_28 = new QLabel(Sistema_Electrico);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(490, 270, 251, 21));
        txt1 = new QTextEdit(Sistema_Electrico);
        txt1->setObjectName(QString::fromUtf8("txt1"));
        txt1->setGeometry(QRect(10, 40, 104, 21));
        txt1->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txt1->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_8 = new QLabel(Sistema_Electrico);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(120, 10, 221, 21));
        label_12 = new QLabel(Sistema_Electrico);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(120, 190, 191, 21));
        label_25 = new QLabel(Sistema_Electrico);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(490, 440, 261, 21));
        btn2 = new QPushButton(Sistema_Electrico);
        btn2->setObjectName(QString::fromUtf8("btn2"));
        btn2->setGeometry(QRect(410, 710, 93, 28));
        checkBox_13 = new QCheckBox(Sistema_Electrico);
        checkBox_13->setObjectName(QString::fromUtf8("checkBox_13"));
        checkBox_13->setGeometry(QRect(880, 580, 271, 20));

        retranslateUi(Sistema_Electrico);

        QMetaObject::connectSlotsByName(Sistema_Electrico);
    } // setupUi

    void retranslateUi(QWidget *Sistema_Electrico)
    {
        Sistema_Electrico->setWindowTitle(QApplication::translate("Sistema_Electrico", "Form", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase A del Generador de la Unidad", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase C del Transformador T00AuxG1", 0, QApplication::UnicodeUTF8));
        checkBox_8->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre del Interruptor 521T21A", 0, QApplication::UnicodeUTF8));
        checkBox_5->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre de la Cuchilla 92BT221C", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase A del Transformador T21A", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("Sistema_Electrico", "Potencia Tablero Compresor Aire", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase C del Transformador T21A", 0, QApplication::UnicodeUTF8));
        checkBox_11->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre del Interruptor 501AuxG1", 0, QApplication::UnicodeUTF8));
        checkBox_3->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre de la Cuchilla 92BT221A", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("Sistema_Electrico", "Posici\303\263n Cuchilla 92BT221A", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase C del Transformador T00AuxG1", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase C del Transformador T21A", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("Sistema_Electrico", "Posici\303\263n Cuchilla 92BT221C", 0, QApplication::UnicodeUTF8));
        checkBox_14->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre del Interruptor 51G1", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("Sistema_Electrico", "Posici\303\263n Cuchilla 92BCT21A", 0, QApplication::UnicodeUTF8));
        checkBox_6->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre de la Cuchilla 92BCT21A", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase A del Generador de la Unidad", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase B del Transformador T20AuxG1", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase C del Generador de la Unidad", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("Sistema_Electrico", "Potencia El\303\251ctrica del Generador Auxiliar", 0, QApplication::UnicodeUTF8));
        checkBox_12->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre del Interruptor 502AuxG1", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase B del Transformador T00AuxG1", 0, QApplication::UnicodeUTF8));
        checkBox_4->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre de la Cuchilla 92BAT21A", 0, QApplication::UnicodeUTF8));
        checkBox->setText(QApplication::translate("Sistema_Electrico", "Arranque y Paro Generador Unidad", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("Sistema_Electrico", "Tiempo", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("Sistema_Electrico", "Potencia Tablero Chiller", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase B del Transformador T21A", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("Sistema_Electrico", "Corriente del Generador Auxiliar", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase B del Transformador T00AuxG1", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase B del Generador de la Unidad", 0, QApplication::UnicodeUTF8));
        checkBox_9->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre del Interruptor 522T21A", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase C del Transformador T20AuxG1", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase B del Transformador T21A", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("Sistema_Electrico", "Potencia Tablero BCI", 0, QApplication::UnicodeUTF8));
        btn1->setText(QApplication::translate("Sistema_Electrico", "Start", 0, QApplication::UnicodeUTF8));
        checkBox_7->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre de la Cuchilla 90MC", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("Sistema_Electrico", "Posici\303\263n Cuchilla 92BAT21A", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase A del Transformador T20AuxG1", 0, QApplication::UnicodeUTF8));
        checkBox_2->setText(QApplication::translate("Sistema_Electrico", "Arranque y Paro Generador Auxiliar", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase B del Transformador T20AuxG1", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase C del Generador de la Unidad", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase A del Transformador T00AuxG1", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase A del Transformador T20AuxG1", 0, QApplication::UnicodeUTF8));
        checkBox_10->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre del Interruptor 52AuxG1", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("Sistema_Electrico", "Posici\303\263n Cuchilla 90MC", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase B del Generador de la Unidad", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("Sistema_Electrico", "Potencia Tablero CCM", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase C del Transformador T20AuxG1", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("Sistema_Electrico", "Corriente Fase A del Transformador T21A", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("Sistema_Electrico", "Potencia del Generador de la Unidad", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("Sistema_Electrico", "Voltaje del Generador Auxiliar", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("Sistema_Electrico", "Voltaje Fase A del Transformador T00AuxG1", 0, QApplication::UnicodeUTF8));
        btn2->setText(QApplication::translate("Sistema_Electrico", "Stop", 0, QApplication::UnicodeUTF8));
        checkBox_13->setText(QApplication::translate("Sistema_Electrico", "Apertura y Cierre del Interruptor 50ANG1", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Sistema_Electrico: public Ui_Sistema_Electrico {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SISTEMA_ELECTRICO_H
