/********************************************************************************
** Form generated from reading UI file 'sisgascomb.ui'
**
** Created: Tue 17. Dec 02:39:55 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SISGASCOMB_H
#define UI_SISGASCOMB_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCommandLinkButton>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "awmultiobject.h"
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_SisGasComb
{
public:
    QLabel *lbFondo;
    QFrame *frame;
    QLabel *lbPatinT;
    WLabel *lbts208cT;
    WLabel *lbts208AT;
    WLabel *lbts208bT;
    QLabel *lbAlarIncT;
    QLabel *lbComMarcAT;
    QLabel *lbComMarcBT;
    QLineEdit *lePatin_1;
    QLineEdit *lealarma_1;
    QCommandLinkButton *btnleAlarma_01;
    QCommandLinkButton *btnleAlarma_02;
    WLabel *lbts208AT_2;
    QLabel *lbSisGasT;
    QLabel *lbBotT;
    QLabel *lbPatinCompT;
    QLabel *lbsk079;
    QFrame *frame_2;
    QLabel *lbEnfComb;
    QLabel *lbSk080T;
    QFrame *frame_4;
    QLabel *lbGAS_CHROMO_1;
    QLabel *lbGAS_CHROMO_2;
    QLabel *lbGAS_CHROMO_3;
    QLabel *lbGAS_CHROMO_4;
    QLabel *lbGAS_CHROMO_8;
    QLabel *lbGAS_CHROMO_7;
    QLabel *lbGAS_CHROMO_6;
    QLabel *lbGAS_CHROMO_5;
    QLabel *lbGAS_CHROMO_11;
    QLabel *lbGAS_CHROMO_9;
    QLabel *lbGAS_CHROMO_10;
    QLabel *lbGAS_CHROMO_21;
    QLabel *lbGAS_CHROMO_14;
    QLabel *lbGAS_CHROMO_19;
    QLabel *lbGAS_CHROMO_13;
    QLabel *lbGAS_CHROMO_16;
    QLabel *lbGAS_CHROMO_12;
    QLabel *lbGAS_CHROMO_15;
    QLabel *lbGAS_CHROMO_17;
    QLabel *lbGAS_CHROMO_18;
    QLabel *lbGAS_CHROMO_20;
    QLabel *label_47;
    QLabel *lbMole_11;
    QLabel *lbMole_3;
    QLabel *lbMole_8;
    QLabel *lbMole_2;
    QLabel *lbMole_5;
    QLabel *lbMole_1;
    QLabel *lbMole_4;
    QLabel *lbMole_6;
    QLabel *lbMole_7;
    QLabel *lbMole_9;
    QLabel *lbMole_10;
    QLabel *lbGAS_CHROMOPor_11;
    QLabel *lbGAS_CHROMOPor_10;
    QLabel *lbGAS_CHROMOPor_3;
    QLabel *lbGAS_CHROMOPor_5;
    QLabel *lbGAS_CHROMOPor_9;
    QLabel *lbGAS_CHROMOPor_7;
    QLabel *lbGAS_CHROMOPor_1;
    QLabel *lbGAS_CHROMOPor_2;
    QLabel *lbGAS_CHROMOPor_6;
    QLabel *lbGAS_CHROMOPor_4;
    QLabel *lbGAS_CHROMOPor_8;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    WLabel *lbGAS_CHROMOVal_11;
    WLabel *lbGAS_CHROMOVal_3;
    WLabel *lbGAS_CHROMOVal_10;
    WLabel *lbGAS_CHROMOVal_5;
    WLabel *lbGAS_CHROMOVal_9;
    WLabel *lbGAS_CHROMOVal_7;
    WLabel *lbGAS_CHROMOVal_1;
    WLabel *lbGAS_CHROMOVal_2;
    WLabel *lbGAS_CHROMOVal_6;
    WLabel *lbGAS_CHROMOVal_4;
    WLabel *lbGAS_CHROMOVal_8;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *lbGAS_CHROMOPor_12;
    QLabel *label_95;
    QLabel *lbGAS_CHROMOPor_17;
    QLabel *lbGAS_CHROMOPor_13;
    QLabel *lbGAS_CHROMOPor_15;
    QLabel *label_99;
    QLabel *lbGAS_CHROMOPor_21;
    QLabel *label_101;
    QLabel *lbGAS_CHROMOPor_19;
    QLabel *label_103;
    QLabel *lbGAS_CHROMOPor_22;
    QLabel *lbGAS_CHROMOPor_14;
    QLabel *label_106;
    QLabel *lbGAS_CHROMOPor_16;
    QLabel *label_108;
    QLabel *lbGAS_CHROMOPor_20;
    QLabel *label_110;
    QLabel *label_111;
    QLabel *label_112;
    QLabel *lbGAS_CHROMOPor_18;
    WLabel *lbGAS_CHROMOVal_14;
    WLabel *lbGAS_CHROMOVal_15;
    WLabel *lbGAS_CHROMOVal_20;
    WLabel *lbGAS_CHROMOVal_17;
    WLabel *lbGAS_CHROMOVal_16;
    WLabel *lbGAS_CHROMOVal_13;
    WLabel *lbGAS_CHROMOVal_19;
    WLabel *lbGAS_CHROMOVal_12;
    WLabel *lbGAS_CHROMOVal_21;
    WLabel *lbGAS_CHROMOVal_18;
    QLabel *lbGAS_CHROMOU_21;
    QLabel *lbGAS_CHROMOU_15;
    QLabel *lbGAS_CHROMOU_13;
    QLabel *lbGAS_CHROMOU_14;
    QLabel *lbGAS_CHROMOU_16;
    QLabel *lbGAS_CHROMOU_17;
    QLabel *lbGAS_CHROMOU_12;
    QLabel *lbGAS_CHROMOU_20;
    QLabel *lbGAS_CHROMOU_19;
    QLabel *lbGAS_CHROMOU_18;
    QLabel *label_135;
    QLabel *label_136;
    QLabel *label_137;
    QLabel *label_138;
    QLabel *label_139;
    QLabel *label_140;
    QLabel *label_141;
    QLabel *label_142;
    QLabel *label_143;
    QLabel *label_144;
    QFrame *frame_3;
    QLabel *lbFilGasT;
    QLabel *lbsk082T;
    QLabel *lbVenT;
    QLabel *lbVenT_2;
    QLabel *lbResidT;
    QLabel *lbEntraT;
    QLabel *lbEntraT_2;
    QLabel *lbxy106bT;
    QLabel *lbXy106aT;
    QLabel *lbXy107b;
    QLabel *lbXy107aT;
    AWMultiObject *led_4;
    AWMultiObject *led_3;
    AWMultiObject *led_1;
    AWMultiObject *led_2;
    QPushButton *btImpr;
    QCommandLinkButton *btnleAlarma_1;
    QCommandLinkButton *btnleAlarma_03;
    QCommandLinkButton *btnleAlarma_4;
    QCommandLinkButton *btnleAlarma_04;
    QCommandLinkButton *btnDisparo;
    QCommandLinkButton *btnleAlarma_9;

    void setupUi(QWidget *SisGasComb)
    {
        if (SisGasComb->objectName().isEmpty())
            SisGasComb->setObjectName(QString::fromUtf8("SisGasComb"));
        SisGasComb->resize(1024, 662);
        SisGasComb->setMinimumSize(QSize(1024, 662));
        SisGasComb->setMaximumSize(QSize(1024, 662));
        lbFondo = new QLabel(SisGasComb);
        lbFondo->setObjectName(QString::fromUtf8("lbFondo"));
        lbFondo->setGeometry(QRect(0, 0, 1024, 662));
        lbFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/N3.png")));
        lbFondo->setScaledContents(true);
        frame = new QFrame(SisGasComb);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(8, 66, 301, 146));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        lbPatinT = new QLabel(frame);
        lbPatinT->setObjectName(QString::fromUtf8("lbPatinT"));
        lbPatinT->setGeometry(QRect(10, -1, 281, 20));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        lbPatinT->setFont(font);
        lbPatinT->setAlignment(Qt::AlignCenter);
        lbts208cT = new WLabel(frame);
        lbts208cT->setObjectName(QString::fromUtf8("lbts208cT"));
        lbts208cT->setGeometry(QRect(11, 103, 41, 16));
        lbts208AT = new WLabel(frame);
        lbts208AT->setObjectName(QString::fromUtf8("lbts208AT"));
        lbts208AT->setGeometry(QRect(11, 79, 46, 13));
        lbts208bT = new WLabel(frame);
        lbts208bT->setObjectName(QString::fromUtf8("lbts208bT"));
        lbts208bT->setGeometry(QRect(11, 91, 46, 13));
        lbAlarIncT = new QLabel(frame);
        lbAlarIncT->setObjectName(QString::fromUtf8("lbAlarIncT"));
        lbAlarIncT->setGeometry(QRect(67, 103, 231, 16));
        QFont font1;
        font1.setPointSize(7);
        lbAlarIncT->setFont(font1);
        lbAlarIncT->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        lbComMarcAT = new QLabel(frame);
        lbComMarcAT->setObjectName(QString::fromUtf8("lbComMarcAT"));
        lbComMarcAT->setGeometry(QRect(67, 79, 231, 16));
        lbComMarcAT->setFont(font1);
        lbComMarcAT->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        lbComMarcBT = new QLabel(frame);
        lbComMarcBT->setObjectName(QString::fromUtf8("lbComMarcBT"));
        lbComMarcBT->setGeometry(QRect(67, 91, 231, 16));
        lbComMarcBT->setFont(font1);
        lbComMarcBT->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        lePatin_1 = new QLineEdit(frame);
        lePatin_1->setObjectName(QString::fromUtf8("lePatin_1"));
        lePatin_1->setGeometry(QRect(94, 24, 113, 20));
        lePatin_1->setFont(font);
        lePatin_1->setStyleSheet(QString::fromUtf8("background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 0);"));
        lePatin_1->setAlignment(Qt::AlignCenter);
        lealarma_1 = new QLineEdit(frame);
        lealarma_1->setObjectName(QString::fromUtf8("lealarma_1"));
        lealarma_1->setGeometry(QRect(102, 125, 98, 17));
        lealarma_1->setFont(font);
        lealarma_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(192, 192, 192);"));
        lealarma_1->setAlignment(Qt::AlignCenter);
        btnleAlarma_01 = new QCommandLinkButton(frame);
        btnleAlarma_01->setObjectName(QString::fromUtf8("btnleAlarma_01"));
        btnleAlarma_01->setGeometry(QRect(95, 25, 110, 17));
        btnleAlarma_01->setStyleSheet(QString::fromUtf8(""));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Resources/PNG/Extras/transparente.svg"), QSize(), QIcon::Normal, QIcon::Off);
        btnleAlarma_01->setIcon(icon);
        btnleAlarma_02 = new QCommandLinkButton(frame);
        btnleAlarma_02->setObjectName(QString::fromUtf8("btnleAlarma_02"));
        btnleAlarma_02->setGeometry(QRect(100, 50, 110, 17));
        btnleAlarma_02->setStyleSheet(QString::fromUtf8(""));
        btnleAlarma_02->setIcon(icon);
        lbts208AT_2 = new WLabel(frame);
        lbts208AT_2->setObjectName(QString::fromUtf8("lbts208AT_2"));
        lbts208AT_2->setGeometry(QRect(120, 55, 46, 13));
        lbts208AT_2->raise();
        lbPatinT->raise();
        lbts208cT->raise();
        lbts208AT->raise();
        lbts208bT->raise();
        lbAlarIncT->raise();
        lbComMarcAT->raise();
        lbComMarcBT->raise();
        lePatin_1->raise();
        lealarma_1->raise();
        btnleAlarma_01->raise();
        btnleAlarma_02->raise();
        lbSisGasT = new QLabel(SisGasComb);
        lbSisGasT->setObjectName(QString::fromUtf8("lbSisGasT"));
        lbSisGasT->setGeometry(QRect(364, 3, 261, 21));
        QFont font2;
        font2.setPointSize(11);
        font2.setBold(true);
        font2.setWeight(75);
        lbSisGasT->setFont(font2);
        lbSisGasT->setAlignment(Qt::AlignCenter);
        lbBotT = new QLabel(SisGasComb);
        lbBotT->setObjectName(QString::fromUtf8("lbBotT"));
        lbBotT->setGeometry(QRect(775, 148, 161, 61));
        QFont font3;
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        lbBotT->setFont(font3);
        lbBotT->setAlignment(Qt::AlignCenter);
        lbPatinCompT = new QLabel(SisGasComb);
        lbPatinCompT->setObjectName(QString::fromUtf8("lbPatinCompT"));
        lbPatinCompT->setGeometry(QRect(339, 87, 161, 61));
        QFont font4;
        font4.setPointSize(8);
        font4.setBold(true);
        font4.setWeight(75);
        lbPatinCompT->setFont(font4);
        lbPatinCompT->setAlignment(Qt::AlignCenter);
        lbsk079 = new QLabel(SisGasComb);
        lbsk079->setObjectName(QString::fromUtf8("lbsk079"));
        lbsk079->setGeometry(QRect(390, 83, 51, 16));
        QFont font5;
        font5.setUnderline(true);
        lbsk079->setFont(font5);
        lbsk079->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(SisGasComb);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(350, 206, 132, 86));
        frame_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Sunken);
        lbEnfComb = new QLabel(frame_2);
        lbEnfComb->setObjectName(QString::fromUtf8("lbEnfComb"));
        lbEnfComb->setGeometry(QRect(10, 40, 111, 31));
        lbEnfComb->setFont(font4);
        lbEnfComb->setAlignment(Qt::AlignCenter);
        lbSk080T = new QLabel(frame_2);
        lbSk080T->setObjectName(QString::fromUtf8("lbSk080T"));
        lbSk080T->setGeometry(QRect(41, 6, 51, 16));
        lbSk080T->setFont(font5);
        lbSk080T->setAlignment(Qt::AlignCenter);
        frame_4 = new QFrame(SisGasComb);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(10, 440, 1011, 191));
        frame_4->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);\n"
"background-color: rgba(255, 255, 255, 0);"));
        frame_4->setFrameShape(QFrame::Box);
        frame_4->setFrameShadow(QFrame::Sunken);
        lbGAS_CHROMO_1 = new QLabel(frame_4);
        lbGAS_CHROMO_1->setObjectName(QString::fromUtf8("lbGAS_CHROMO_1"));
        lbGAS_CHROMO_1->setGeometry(QRect(22, 17, 116, 16));
        lbGAS_CHROMO_1->setFont(font3);
        lbGAS_CHROMO_2 = new QLabel(frame_4);
        lbGAS_CHROMO_2->setObjectName(QString::fromUtf8("lbGAS_CHROMO_2"));
        lbGAS_CHROMO_2->setGeometry(QRect(22, 32, 116, 16));
        lbGAS_CHROMO_2->setFont(font3);
        lbGAS_CHROMO_3 = new QLabel(frame_4);
        lbGAS_CHROMO_3->setObjectName(QString::fromUtf8("lbGAS_CHROMO_3"));
        lbGAS_CHROMO_3->setGeometry(QRect(22, 48, 116, 16));
        lbGAS_CHROMO_3->setFont(font3);
        lbGAS_CHROMO_4 = new QLabel(frame_4);
        lbGAS_CHROMO_4->setObjectName(QString::fromUtf8("lbGAS_CHROMO_4"));
        lbGAS_CHROMO_4->setGeometry(QRect(22, 62, 116, 16));
        lbGAS_CHROMO_4->setFont(font3);
        lbGAS_CHROMO_8 = new QLabel(frame_4);
        lbGAS_CHROMO_8->setObjectName(QString::fromUtf8("lbGAS_CHROMO_8"));
        lbGAS_CHROMO_8->setGeometry(QRect(22, 123, 116, 16));
        lbGAS_CHROMO_8->setFont(font3);
        lbGAS_CHROMO_7 = new QLabel(frame_4);
        lbGAS_CHROMO_7->setObjectName(QString::fromUtf8("lbGAS_CHROMO_7"));
        lbGAS_CHROMO_7->setGeometry(QRect(22, 107, 116, 16));
        lbGAS_CHROMO_7->setFont(font3);
        lbGAS_CHROMO_6 = new QLabel(frame_4);
        lbGAS_CHROMO_6->setObjectName(QString::fromUtf8("lbGAS_CHROMO_6"));
        lbGAS_CHROMO_6->setGeometry(QRect(22, 93, 116, 16));
        lbGAS_CHROMO_6->setFont(font3);
        lbGAS_CHROMO_5 = new QLabel(frame_4);
        lbGAS_CHROMO_5->setObjectName(QString::fromUtf8("lbGAS_CHROMO_5"));
        lbGAS_CHROMO_5->setGeometry(QRect(22, 78, 116, 16));
        lbGAS_CHROMO_5->setFont(font3);
        lbGAS_CHROMO_11 = new QLabel(frame_4);
        lbGAS_CHROMO_11->setObjectName(QString::fromUtf8("lbGAS_CHROMO_11"));
        lbGAS_CHROMO_11->setGeometry(QRect(22, 170, 116, 16));
        lbGAS_CHROMO_11->setFont(font3);
        lbGAS_CHROMO_9 = new QLabel(frame_4);
        lbGAS_CHROMO_9->setObjectName(QString::fromUtf8("lbGAS_CHROMO_9"));
        lbGAS_CHROMO_9->setGeometry(QRect(22, 139, 116, 16));
        lbGAS_CHROMO_9->setFont(font3);
        lbGAS_CHROMO_10 = new QLabel(frame_4);
        lbGAS_CHROMO_10->setObjectName(QString::fromUtf8("lbGAS_CHROMO_10"));
        lbGAS_CHROMO_10->setGeometry(QRect(22, 154, 116, 16));
        lbGAS_CHROMO_10->setFont(font3);
        lbGAS_CHROMO_21 = new QLabel(frame_4);
        lbGAS_CHROMO_21->setObjectName(QString::fromUtf8("lbGAS_CHROMO_21"));
        lbGAS_CHROMO_21->setGeometry(QRect(520, 154, 116, 16));
        lbGAS_CHROMO_21->setFont(font3);
        lbGAS_CHROMO_14 = new QLabel(frame_4);
        lbGAS_CHROMO_14->setObjectName(QString::fromUtf8("lbGAS_CHROMO_14"));
        lbGAS_CHROMO_14->setGeometry(QRect(520, 48, 116, 16));
        lbGAS_CHROMO_14->setFont(font3);
        lbGAS_CHROMO_19 = new QLabel(frame_4);
        lbGAS_CHROMO_19->setObjectName(QString::fromUtf8("lbGAS_CHROMO_19"));
        lbGAS_CHROMO_19->setGeometry(QRect(520, 123, 116, 16));
        lbGAS_CHROMO_19->setFont(font3);
        lbGAS_CHROMO_13 = new QLabel(frame_4);
        lbGAS_CHROMO_13->setObjectName(QString::fromUtf8("lbGAS_CHROMO_13"));
        lbGAS_CHROMO_13->setGeometry(QRect(520, 32, 116, 16));
        lbGAS_CHROMO_13->setFont(font3);
        lbGAS_CHROMO_16 = new QLabel(frame_4);
        lbGAS_CHROMO_16->setObjectName(QString::fromUtf8("lbGAS_CHROMO_16"));
        lbGAS_CHROMO_16->setGeometry(QRect(520, 78, 116, 16));
        lbGAS_CHROMO_16->setFont(font3);
        lbGAS_CHROMO_12 = new QLabel(frame_4);
        lbGAS_CHROMO_12->setObjectName(QString::fromUtf8("lbGAS_CHROMO_12"));
        lbGAS_CHROMO_12->setGeometry(QRect(520, 17, 116, 16));
        lbGAS_CHROMO_12->setFont(font3);
        lbGAS_CHROMO_15 = new QLabel(frame_4);
        lbGAS_CHROMO_15->setObjectName(QString::fromUtf8("lbGAS_CHROMO_15"));
        lbGAS_CHROMO_15->setGeometry(QRect(520, 62, 116, 16));
        lbGAS_CHROMO_15->setFont(font3);
        lbGAS_CHROMO_17 = new QLabel(frame_4);
        lbGAS_CHROMO_17->setObjectName(QString::fromUtf8("lbGAS_CHROMO_17"));
        lbGAS_CHROMO_17->setGeometry(QRect(520, 93, 116, 16));
        lbGAS_CHROMO_17->setFont(font3);
        lbGAS_CHROMO_18 = new QLabel(frame_4);
        lbGAS_CHROMO_18->setObjectName(QString::fromUtf8("lbGAS_CHROMO_18"));
        lbGAS_CHROMO_18->setGeometry(QRect(520, 107, 116, 16));
        lbGAS_CHROMO_18->setFont(font3);
        lbGAS_CHROMO_20 = new QLabel(frame_4);
        lbGAS_CHROMO_20->setObjectName(QString::fromUtf8("lbGAS_CHROMO_20"));
        lbGAS_CHROMO_20->setGeometry(QRect(520, 139, 116, 16));
        lbGAS_CHROMO_20->setFont(font3);
        label_47 = new QLabel(frame_4);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(3, 3, 1004, 16));
        label_47->setFont(font4);
        label_47->setAlignment(Qt::AlignCenter);
        lbMole_11 = new QLabel(frame_4);
        lbMole_11->setObjectName(QString::fromUtf8("lbMole_11"));
        lbMole_11->setGeometry(QRect(135, 170, 38, 16));
        lbMole_11->setFont(font3);
        lbMole_3 = new QLabel(frame_4);
        lbMole_3->setObjectName(QString::fromUtf8("lbMole_3"));
        lbMole_3->setGeometry(QRect(135, 48, 38, 16));
        lbMole_3->setFont(font3);
        lbMole_8 = new QLabel(frame_4);
        lbMole_8->setObjectName(QString::fromUtf8("lbMole_8"));
        lbMole_8->setGeometry(QRect(135, 123, 38, 16));
        lbMole_8->setFont(font3);
        lbMole_2 = new QLabel(frame_4);
        lbMole_2->setObjectName(QString::fromUtf8("lbMole_2"));
        lbMole_2->setGeometry(QRect(135, 32, 38, 16));
        lbMole_2->setFont(font3);
        lbMole_5 = new QLabel(frame_4);
        lbMole_5->setObjectName(QString::fromUtf8("lbMole_5"));
        lbMole_5->setGeometry(QRect(135, 78, 38, 16));
        lbMole_5->setFont(font3);
        lbMole_1 = new QLabel(frame_4);
        lbMole_1->setObjectName(QString::fromUtf8("lbMole_1"));
        lbMole_1->setGeometry(QRect(135, 17, 38, 16));
        lbMole_1->setFont(font3);
        lbMole_4 = new QLabel(frame_4);
        lbMole_4->setObjectName(QString::fromUtf8("lbMole_4"));
        lbMole_4->setGeometry(QRect(135, 62, 38, 16));
        lbMole_4->setFont(font3);
        lbMole_6 = new QLabel(frame_4);
        lbMole_6->setObjectName(QString::fromUtf8("lbMole_6"));
        lbMole_6->setGeometry(QRect(135, 93, 38, 16));
        lbMole_6->setFont(font3);
        lbMole_7 = new QLabel(frame_4);
        lbMole_7->setObjectName(QString::fromUtf8("lbMole_7"));
        lbMole_7->setGeometry(QRect(135, 107, 38, 16));
        lbMole_7->setFont(font3);
        lbMole_9 = new QLabel(frame_4);
        lbMole_9->setObjectName(QString::fromUtf8("lbMole_9"));
        lbMole_9->setGeometry(QRect(135, 139, 38, 16));
        lbMole_9->setFont(font3);
        lbMole_10 = new QLabel(frame_4);
        lbMole_10->setObjectName(QString::fromUtf8("lbMole_10"));
        lbMole_10->setGeometry(QRect(135, 154, 38, 16));
        lbMole_10->setFont(font3);
        lbGAS_CHROMOPor_11 = new QLabel(frame_4);
        lbGAS_CHROMOPor_11->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_11"));
        lbGAS_CHROMOPor_11->setGeometry(QRect(173, 170, 19, 16));
        lbGAS_CHROMOPor_11->setFont(font3);
        lbGAS_CHROMOPor_10 = new QLabel(frame_4);
        lbGAS_CHROMOPor_10->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_10"));
        lbGAS_CHROMOPor_10->setGeometry(QRect(173, 154, 19, 16));
        lbGAS_CHROMOPor_10->setFont(font3);
        lbGAS_CHROMOPor_3 = new QLabel(frame_4);
        lbGAS_CHROMOPor_3->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_3"));
        lbGAS_CHROMOPor_3->setGeometry(QRect(173, 48, 19, 16));
        lbGAS_CHROMOPor_3->setFont(font3);
        lbGAS_CHROMOPor_5 = new QLabel(frame_4);
        lbGAS_CHROMOPor_5->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_5"));
        lbGAS_CHROMOPor_5->setGeometry(QRect(173, 78, 19, 16));
        lbGAS_CHROMOPor_5->setFont(font3);
        lbGAS_CHROMOPor_9 = new QLabel(frame_4);
        lbGAS_CHROMOPor_9->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_9"));
        lbGAS_CHROMOPor_9->setGeometry(QRect(173, 139, 19, 16));
        lbGAS_CHROMOPor_9->setFont(font3);
        lbGAS_CHROMOPor_7 = new QLabel(frame_4);
        lbGAS_CHROMOPor_7->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_7"));
        lbGAS_CHROMOPor_7->setGeometry(QRect(173, 107, 19, 16));
        lbGAS_CHROMOPor_7->setFont(font3);
        lbGAS_CHROMOPor_1 = new QLabel(frame_4);
        lbGAS_CHROMOPor_1->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_1"));
        lbGAS_CHROMOPor_1->setGeometry(QRect(173, 17, 19, 16));
        lbGAS_CHROMOPor_1->setFont(font3);
        lbGAS_CHROMOPor_2 = new QLabel(frame_4);
        lbGAS_CHROMOPor_2->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_2"));
        lbGAS_CHROMOPor_2->setGeometry(QRect(173, 32, 19, 16));
        lbGAS_CHROMOPor_2->setFont(font3);
        lbGAS_CHROMOPor_6 = new QLabel(frame_4);
        lbGAS_CHROMOPor_6->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_6"));
        lbGAS_CHROMOPor_6->setGeometry(QRect(173, 93, 19, 16));
        lbGAS_CHROMOPor_6->setFont(font3);
        lbGAS_CHROMOPor_4 = new QLabel(frame_4);
        lbGAS_CHROMOPor_4->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_4"));
        lbGAS_CHROMOPor_4->setGeometry(QRect(173, 62, 19, 16));
        lbGAS_CHROMOPor_4->setFont(font3);
        lbGAS_CHROMOPor_8 = new QLabel(frame_4);
        lbGAS_CHROMOPor_8->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_8"));
        lbGAS_CHROMOPor_8->setGeometry(QRect(173, 123, 19, 16));
        lbGAS_CHROMOPor_8->setFont(font3);
        label_70 = new QLabel(frame_4);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(191, 170, 100, 16));
        label_70->setFont(font3);
        label_71 = new QLabel(frame_4);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(191, 48, 100, 16));
        label_71->setFont(font3);
        label_72 = new QLabel(frame_4);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(191, 154, 100, 16));
        label_72->setFont(font3);
        label_73 = new QLabel(frame_4);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(191, 78, 100, 16));
        label_73->setFont(font3);
        label_74 = new QLabel(frame_4);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(191, 139, 100, 16));
        label_74->setFont(font3);
        label_75 = new QLabel(frame_4);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(191, 107, 100, 16));
        label_75->setFont(font3);
        label_76 = new QLabel(frame_4);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(191, 17, 100, 16));
        label_76->setFont(font3);
        label_77 = new QLabel(frame_4);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(191, 32, 100, 16));
        label_77->setFont(font3);
        label_78 = new QLabel(frame_4);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(191, 93, 100, 16));
        label_78->setFont(font3);
        label_79 = new QLabel(frame_4);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(191, 62, 100, 16));
        label_79->setFont(font3);
        label_80 = new QLabel(frame_4);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(191, 123, 100, 16));
        label_80->setFont(font3);
        lbGAS_CHROMOVal_11 = new WLabel(frame_4);
        lbGAS_CHROMOVal_11->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_11"));
        lbGAS_CHROMOVal_11->setGeometry(QRect(352, 170, 50, 16));
        lbGAS_CHROMOVal_11->setFont(font3);
        lbGAS_CHROMOVal_3 = new WLabel(frame_4);
        lbGAS_CHROMOVal_3->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_3"));
        lbGAS_CHROMOVal_3->setGeometry(QRect(352, 48, 50, 16));
        lbGAS_CHROMOVal_3->setFont(font3);
        lbGAS_CHROMOVal_10 = new WLabel(frame_4);
        lbGAS_CHROMOVal_10->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_10"));
        lbGAS_CHROMOVal_10->setGeometry(QRect(352, 154, 50, 16));
        lbGAS_CHROMOVal_10->setFont(font3);
        lbGAS_CHROMOVal_5 = new WLabel(frame_4);
        lbGAS_CHROMOVal_5->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_5"));
        lbGAS_CHROMOVal_5->setGeometry(QRect(352, 78, 50, 16));
        lbGAS_CHROMOVal_5->setFont(font3);
        lbGAS_CHROMOVal_9 = new WLabel(frame_4);
        lbGAS_CHROMOVal_9->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_9"));
        lbGAS_CHROMOVal_9->setGeometry(QRect(352, 139, 50, 16));
        lbGAS_CHROMOVal_9->setFont(font3);
        lbGAS_CHROMOVal_7 = new WLabel(frame_4);
        lbGAS_CHROMOVal_7->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_7"));
        lbGAS_CHROMOVal_7->setGeometry(QRect(352, 107, 50, 16));
        lbGAS_CHROMOVal_7->setFont(font3);
        lbGAS_CHROMOVal_1 = new WLabel(frame_4);
        lbGAS_CHROMOVal_1->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_1"));
        lbGAS_CHROMOVal_1->setGeometry(QRect(352, 17, 50, 16));
        lbGAS_CHROMOVal_1->setFont(font3);
        lbGAS_CHROMOVal_2 = new WLabel(frame_4);
        lbGAS_CHROMOVal_2->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_2"));
        lbGAS_CHROMOVal_2->setGeometry(QRect(352, 32, 50, 16));
        lbGAS_CHROMOVal_2->setFont(font3);
        lbGAS_CHROMOVal_6 = new WLabel(frame_4);
        lbGAS_CHROMOVal_6->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_6"));
        lbGAS_CHROMOVal_6->setGeometry(QRect(352, 93, 50, 16));
        lbGAS_CHROMOVal_6->setFont(font3);
        lbGAS_CHROMOVal_4 = new WLabel(frame_4);
        lbGAS_CHROMOVal_4->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_4"));
        lbGAS_CHROMOVal_4->setGeometry(QRect(352, 62, 50, 16));
        lbGAS_CHROMOVal_4->setFont(font3);
        lbGAS_CHROMOVal_8 = new WLabel(frame_4);
        lbGAS_CHROMOVal_8->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_8"));
        lbGAS_CHROMOVal_8->setGeometry(QRect(352, 123, 50, 16));
        lbGAS_CHROMOVal_8->setFont(font3);
        label_92 = new QLabel(frame_4);
        label_92->setObjectName(QString::fromUtf8("label_92"));
        label_92->setGeometry(QRect(430, 170, 100, 16));
        label_92->setFont(font3);
        label_93 = new QLabel(frame_4);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(430, 32, 100, 16));
        label_93->setFont(font3);
        lbGAS_CHROMOPor_12 = new QLabel(frame_4);
        lbGAS_CHROMOPor_12->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_12"));
        lbGAS_CHROMOPor_12->setGeometry(QRect(412, 17, 19, 16));
        lbGAS_CHROMOPor_12->setFont(font3);
        label_95 = new QLabel(frame_4);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(430, 93, 100, 16));
        label_95->setFont(font3);
        lbGAS_CHROMOPor_17 = new QLabel(frame_4);
        lbGAS_CHROMOPor_17->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_17"));
        lbGAS_CHROMOPor_17->setGeometry(QRect(412, 93, 19, 16));
        lbGAS_CHROMOPor_17->setFont(font3);
        lbGAS_CHROMOPor_13 = new QLabel(frame_4);
        lbGAS_CHROMOPor_13->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_13"));
        lbGAS_CHROMOPor_13->setGeometry(QRect(412, 32, 19, 16));
        lbGAS_CHROMOPor_13->setFont(font3);
        lbGAS_CHROMOPor_15 = new QLabel(frame_4);
        lbGAS_CHROMOPor_15->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_15"));
        lbGAS_CHROMOPor_15->setGeometry(QRect(412, 62, 19, 16));
        lbGAS_CHROMOPor_15->setFont(font3);
        label_99 = new QLabel(frame_4);
        label_99->setObjectName(QString::fromUtf8("label_99"));
        label_99->setGeometry(QRect(430, 62, 100, 16));
        label_99->setFont(font3);
        lbGAS_CHROMOPor_21 = new QLabel(frame_4);
        lbGAS_CHROMOPor_21->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_21"));
        lbGAS_CHROMOPor_21->setGeometry(QRect(412, 154, 19, 16));
        lbGAS_CHROMOPor_21->setFont(font3);
        label_101 = new QLabel(frame_4);
        label_101->setObjectName(QString::fromUtf8("label_101"));
        label_101->setGeometry(QRect(430, 48, 100, 16));
        label_101->setFont(font3);
        lbGAS_CHROMOPor_19 = new QLabel(frame_4);
        lbGAS_CHROMOPor_19->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_19"));
        lbGAS_CHROMOPor_19->setGeometry(QRect(412, 123, 19, 16));
        lbGAS_CHROMOPor_19->setFont(font3);
        label_103 = new QLabel(frame_4);
        label_103->setObjectName(QString::fromUtf8("label_103"));
        label_103->setGeometry(QRect(430, 123, 100, 16));
        label_103->setFont(font3);
        lbGAS_CHROMOPor_22 = new QLabel(frame_4);
        lbGAS_CHROMOPor_22->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_22"));
        lbGAS_CHROMOPor_22->setGeometry(QRect(412, 170, 19, 16));
        lbGAS_CHROMOPor_22->setFont(font3);
        lbGAS_CHROMOPor_14 = new QLabel(frame_4);
        lbGAS_CHROMOPor_14->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_14"));
        lbGAS_CHROMOPor_14->setGeometry(QRect(412, 48, 19, 16));
        lbGAS_CHROMOPor_14->setFont(font3);
        label_106 = new QLabel(frame_4);
        label_106->setObjectName(QString::fromUtf8("label_106"));
        label_106->setGeometry(QRect(430, 154, 100, 16));
        label_106->setFont(font3);
        lbGAS_CHROMOPor_16 = new QLabel(frame_4);
        lbGAS_CHROMOPor_16->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_16"));
        lbGAS_CHROMOPor_16->setGeometry(QRect(412, 78, 19, 16));
        lbGAS_CHROMOPor_16->setFont(font3);
        label_108 = new QLabel(frame_4);
        label_108->setObjectName(QString::fromUtf8("label_108"));
        label_108->setGeometry(QRect(430, 78, 100, 16));
        label_108->setFont(font3);
        lbGAS_CHROMOPor_20 = new QLabel(frame_4);
        lbGAS_CHROMOPor_20->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_20"));
        lbGAS_CHROMOPor_20->setGeometry(QRect(412, 139, 19, 16));
        lbGAS_CHROMOPor_20->setFont(font3);
        label_110 = new QLabel(frame_4);
        label_110->setObjectName(QString::fromUtf8("label_110"));
        label_110->setGeometry(QRect(430, 17, 100, 16));
        label_110->setFont(font3);
        label_111 = new QLabel(frame_4);
        label_111->setObjectName(QString::fromUtf8("label_111"));
        label_111->setGeometry(QRect(430, 107, 100, 16));
        label_111->setFont(font3);
        label_112 = new QLabel(frame_4);
        label_112->setObjectName(QString::fromUtf8("label_112"));
        label_112->setGeometry(QRect(430, 139, 100, 16));
        label_112->setFont(font3);
        lbGAS_CHROMOPor_18 = new QLabel(frame_4);
        lbGAS_CHROMOPor_18->setObjectName(QString::fromUtf8("lbGAS_CHROMOPor_18"));
        lbGAS_CHROMOPor_18->setGeometry(QRect(412, 107, 19, 16));
        lbGAS_CHROMOPor_18->setFont(font3);
        lbGAS_CHROMOVal_14 = new WLabel(frame_4);
        lbGAS_CHROMOVal_14->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_14"));
        lbGAS_CHROMOVal_14->setGeometry(QRect(902, 48, 50, 16));
        lbGAS_CHROMOVal_14->setFont(font3);
        lbGAS_CHROMOVal_14->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_15 = new WLabel(frame_4);
        lbGAS_CHROMOVal_15->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_15"));
        lbGAS_CHROMOVal_15->setGeometry(QRect(902, 62, 50, 16));
        lbGAS_CHROMOVal_15->setFont(font3);
        lbGAS_CHROMOVal_15->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_20 = new WLabel(frame_4);
        lbGAS_CHROMOVal_20->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_20"));
        lbGAS_CHROMOVal_20->setGeometry(QRect(902, 139, 50, 16));
        lbGAS_CHROMOVal_20->setFont(font3);
        lbGAS_CHROMOVal_20->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_17 = new WLabel(frame_4);
        lbGAS_CHROMOVal_17->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_17"));
        lbGAS_CHROMOVal_17->setGeometry(QRect(902, 93, 50, 16));
        lbGAS_CHROMOVal_17->setFont(font3);
        lbGAS_CHROMOVal_17->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_16 = new WLabel(frame_4);
        lbGAS_CHROMOVal_16->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_16"));
        lbGAS_CHROMOVal_16->setGeometry(QRect(902, 78, 50, 16));
        lbGAS_CHROMOVal_16->setFont(font3);
        lbGAS_CHROMOVal_16->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_13 = new WLabel(frame_4);
        lbGAS_CHROMOVal_13->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_13"));
        lbGAS_CHROMOVal_13->setGeometry(QRect(902, 32, 50, 16));
        lbGAS_CHROMOVal_13->setFont(font3);
        lbGAS_CHROMOVal_13->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_19 = new WLabel(frame_4);
        lbGAS_CHROMOVal_19->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_19"));
        lbGAS_CHROMOVal_19->setGeometry(QRect(902, 123, 50, 16));
        lbGAS_CHROMOVal_19->setFont(font3);
        lbGAS_CHROMOVal_19->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_12 = new WLabel(frame_4);
        lbGAS_CHROMOVal_12->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_12"));
        lbGAS_CHROMOVal_12->setGeometry(QRect(902, 17, 50, 16));
        lbGAS_CHROMOVal_12->setFont(font3);
        lbGAS_CHROMOVal_12->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_21 = new WLabel(frame_4);
        lbGAS_CHROMOVal_21->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_21"));
        lbGAS_CHROMOVal_21->setGeometry(QRect(902, 154, 50, 16));
        lbGAS_CHROMOVal_21->setFont(font3);
        lbGAS_CHROMOVal_21->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOVal_18 = new WLabel(frame_4);
        lbGAS_CHROMOVal_18->setObjectName(QString::fromUtf8("lbGAS_CHROMOVal_18"));
        lbGAS_CHROMOVal_18->setGeometry(QRect(902, 107, 50, 16));
        lbGAS_CHROMOVal_18->setFont(font3);
        lbGAS_CHROMOVal_18->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbGAS_CHROMOU_21 = new QLabel(frame_4);
        lbGAS_CHROMOU_21->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_21"));
        lbGAS_CHROMOU_21->setGeometry(QRect(952, 154, 60, 16));
        lbGAS_CHROMOU_21->setFont(font3);
        lbGAS_CHROMOU_21->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_15 = new QLabel(frame_4);
        lbGAS_CHROMOU_15->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_15"));
        lbGAS_CHROMOU_15->setGeometry(QRect(952, 62, 60, 16));
        lbGAS_CHROMOU_15->setFont(font3);
        lbGAS_CHROMOU_15->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_13 = new QLabel(frame_4);
        lbGAS_CHROMOU_13->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_13"));
        lbGAS_CHROMOU_13->setGeometry(QRect(952, 32, 60, 16));
        lbGAS_CHROMOU_13->setFont(font3);
        lbGAS_CHROMOU_13->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_14 = new QLabel(frame_4);
        lbGAS_CHROMOU_14->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_14"));
        lbGAS_CHROMOU_14->setGeometry(QRect(952, 48, 60, 16));
        lbGAS_CHROMOU_14->setFont(font3);
        lbGAS_CHROMOU_14->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_16 = new QLabel(frame_4);
        lbGAS_CHROMOU_16->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_16"));
        lbGAS_CHROMOU_16->setGeometry(QRect(952, 78, 60, 16));
        lbGAS_CHROMOU_16->setFont(font3);
        lbGAS_CHROMOU_16->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_17 = new QLabel(frame_4);
        lbGAS_CHROMOU_17->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_17"));
        lbGAS_CHROMOU_17->setGeometry(QRect(952, 93, 60, 16));
        lbGAS_CHROMOU_17->setFont(font3);
        lbGAS_CHROMOU_17->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_12 = new QLabel(frame_4);
        lbGAS_CHROMOU_12->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_12"));
        lbGAS_CHROMOU_12->setGeometry(QRect(952, 17, 60, 16));
        lbGAS_CHROMOU_12->setFont(font3);
        lbGAS_CHROMOU_12->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_20 = new QLabel(frame_4);
        lbGAS_CHROMOU_20->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_20"));
        lbGAS_CHROMOU_20->setGeometry(QRect(952, 139, 60, 16));
        lbGAS_CHROMOU_20->setFont(font3);
        lbGAS_CHROMOU_20->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_19 = new QLabel(frame_4);
        lbGAS_CHROMOU_19->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_19"));
        lbGAS_CHROMOU_19->setGeometry(QRect(952, 123, 60, 16));
        lbGAS_CHROMOU_19->setFont(font3);
        lbGAS_CHROMOU_19->setAlignment(Qt::AlignCenter);
        lbGAS_CHROMOU_18 = new QLabel(frame_4);
        lbGAS_CHROMOU_18->setObjectName(QString::fromUtf8("lbGAS_CHROMOU_18"));
        lbGAS_CHROMOU_18->setGeometry(QRect(952, 107, 60, 16));
        lbGAS_CHROMOU_18->setFont(font3);
        lbGAS_CHROMOU_18->setAlignment(Qt::AlignCenter);
        label_135 = new QLabel(frame_4);
        label_135->setObjectName(QString::fromUtf8("label_135"));
        label_135->setGeometry(QRect(644, 48, 263, 16));
        label_135->setFont(font4);
        label_135->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_136 = new QLabel(frame_4);
        label_136->setObjectName(QString::fromUtf8("label_136"));
        label_136->setGeometry(QRect(644, 62, 263, 16));
        label_136->setFont(font4);
        label_136->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_137 = new QLabel(frame_4);
        label_137->setObjectName(QString::fromUtf8("label_137"));
        label_137->setGeometry(QRect(644, 139, 263, 16));
        label_137->setFont(font4);
        label_137->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_138 = new QLabel(frame_4);
        label_138->setObjectName(QString::fromUtf8("label_138"));
        label_138->setGeometry(QRect(644, 93, 263, 16));
        label_138->setFont(font4);
        label_138->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_139 = new QLabel(frame_4);
        label_139->setObjectName(QString::fromUtf8("label_139"));
        label_139->setGeometry(QRect(644, 78, 263, 16));
        label_139->setFont(font4);
        label_139->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_140 = new QLabel(frame_4);
        label_140->setObjectName(QString::fromUtf8("label_140"));
        label_140->setGeometry(QRect(644, 32, 263, 16));
        label_140->setFont(font4);
        label_140->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_141 = new QLabel(frame_4);
        label_141->setObjectName(QString::fromUtf8("label_141"));
        label_141->setGeometry(QRect(644, 123, 263, 16));
        label_141->setFont(font4);
        label_141->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_142 = new QLabel(frame_4);
        label_142->setObjectName(QString::fromUtf8("label_142"));
        label_142->setGeometry(QRect(644, 17, 263, 16));
        label_142->setFont(font4);
        label_142->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_143 = new QLabel(frame_4);
        label_143->setObjectName(QString::fromUtf8("label_143"));
        label_143->setGeometry(QRect(644, 154, 263, 16));
        label_143->setFont(font4);
        label_143->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_144 = new QLabel(frame_4);
        label_144->setObjectName(QString::fromUtf8("label_144"));
        label_144->setGeometry(QRect(644, 107, 263, 16));
        label_144->setFont(font4);
        label_144->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_3 = new QFrame(SisGasComb);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(564, 351, 132, 86));
        frame_3->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_3->setFrameShape(QFrame::Box);
        frame_3->setFrameShadow(QFrame::Sunken);
        lbFilGasT = new QLabel(frame_3);
        lbFilGasT->setObjectName(QString::fromUtf8("lbFilGasT"));
        lbFilGasT->setGeometry(QRect(10, 40, 111, 31));
        lbFilGasT->setFont(font4);
        lbFilGasT->setAlignment(Qt::AlignCenter);
        lbsk082T = new QLabel(frame_3);
        lbsk082T->setObjectName(QString::fromUtf8("lbsk082T"));
        lbsk082T->setGeometry(QRect(41, 6, 51, 16));
        lbsk082T->setFont(font5);
        lbsk082T->setAlignment(Qt::AlignCenter);
        lbVenT = new QLabel(SisGasComb);
        lbVenT->setObjectName(QString::fromUtf8("lbVenT"));
        lbVenT->setGeometry(QRect(207, 236, 46, 13));
        lbVenT_2 = new QLabel(SisGasComb);
        lbVenT_2->setObjectName(QString::fromUtf8("lbVenT_2"));
        lbVenT_2->setGeometry(QRect(801, 274, 46, 13));
        lbResidT = new QLabel(SisGasComb);
        lbResidT->setObjectName(QString::fromUtf8("lbResidT"));
        lbResidT->setGeometry(QRect(940, 223, 71, 31));
        QFont font6;
        font6.setPointSize(6);
        lbResidT->setFont(font6);
        lbResidT->setAlignment(Qt::AlignCenter);
        lbEntraT = new QLabel(SisGasComb);
        lbEntraT->setObjectName(QString::fromUtf8("lbEntraT"));
        lbEntraT->setGeometry(QRect(939, 376, 71, 31));
        lbEntraT->setFont(font6);
        lbEntraT->setAlignment(Qt::AlignCenter);
        lbEntraT_2 = new QLabel(SisGasComb);
        lbEntraT_2->setObjectName(QString::fromUtf8("lbEntraT_2"));
        lbEntraT_2->setGeometry(QRect(0, 379, 71, 31));
        lbEntraT_2->setFont(font6);
        lbEntraT_2->setAlignment(Qt::AlignCenter);
        lbxy106bT = new QLabel(SisGasComb);
        lbxy106bT->setObjectName(QString::fromUtf8("lbxy106bT"));
        lbxy106bT->setGeometry(QRect(198, 278, 46, 13));
        lbXy106aT = new QLabel(SisGasComb);
        lbXy106aT->setObjectName(QString::fromUtf8("lbXy106aT"));
        lbXy106aT->setGeometry(QRect(167, 404, 46, 13));
        lbXy107b = new QLabel(SisGasComb);
        lbXy107b->setObjectName(QString::fromUtf8("lbXy107b"));
        lbXy107b->setGeometry(QRect(793, 313, 46, 13));
        lbXy107aT = new QLabel(SisGasComb);
        lbXy107aT->setObjectName(QString::fromUtf8("lbXy107aT"));
        lbXy107aT->setGeometry(QRect(766, 405, 46, 13));
        led_4 = new AWMultiObject(SisGasComb);
        led_4->setObjectName(QString::fromUtf8("led_4"));
        led_4->setGeometry(QRect(845, 308, 27, 27));
        led_4->setElementType(AWMultiObject::CIRLED);
        led_3 = new AWMultiObject(SisGasComb);
        led_3->setObjectName(QString::fromUtf8("led_3"));
        led_3->setGeometry(QRect(773, 380, 27, 27));
        led_3->setElementType(AWMultiObject::CIRLED);
        led_1 = new AWMultiObject(SisGasComb);
        led_1->setObjectName(QString::fromUtf8("led_1"));
        led_1->setGeometry(QRect(172, 381, 27, 27));
        led_1->setElementType(AWMultiObject::CIRLED);
        led_2 = new AWMultiObject(SisGasComb);
        led_2->setObjectName(QString::fromUtf8("led_2"));
        led_2->setGeometry(QRect(251, 272, 27, 27));
        led_2->setElementType(AWMultiObject::CIRLED);
        btImpr = new QPushButton(SisGasComb);
        btImpr->setObjectName(QString::fromUtf8("btImpr"));
        btImpr->setGeometry(QRect(10, 632, 135, 25));
        btImpr->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnleAlarma_1 = new QCommandLinkButton(SisGasComb);
        btnleAlarma_1->setObjectName(QString::fromUtf8("btnleAlarma_1"));
        btnleAlarma_1->setGeometry(QRect(110, 190, 98, 17));
        btnleAlarma_1->setStyleSheet(QString::fromUtf8(""));
        btnleAlarma_1->setIcon(icon);
        btnleAlarma_03 = new QCommandLinkButton(SisGasComb);
        btnleAlarma_03->setObjectName(QString::fromUtf8("btnleAlarma_03"));
        btnleAlarma_03->setGeometry(QRect(254, 275, 21, 21));
        btnleAlarma_03->setStyleSheet(QString::fromUtf8(""));
        btnleAlarma_03->setIcon(icon);
        btnleAlarma_4 = new QCommandLinkButton(SisGasComb);
        btnleAlarma_4->setObjectName(QString::fromUtf8("btnleAlarma_4"));
        btnleAlarma_4->setGeometry(QRect(776, 382, 20, 21));
        btnleAlarma_4->setStyleSheet(QString::fromUtf8(""));
        btnleAlarma_4->setIcon(icon);
        btnleAlarma_04 = new QCommandLinkButton(SisGasComb);
        btnleAlarma_04->setObjectName(QString::fromUtf8("btnleAlarma_04"));
        btnleAlarma_04->setGeometry(QRect(175, 384, 21, 20));
        btnleAlarma_04->setStyleSheet(QString::fromUtf8(""));
        btnleAlarma_04->setIcon(icon);
        btnDisparo = new QCommandLinkButton(SisGasComb);
        btnDisparo->setObjectName(QString::fromUtf8("btnDisparo"));
        btnDisparo->setGeometry(QRect(800, 70, 111, 91));
        btnDisparo->setStyleSheet(QString::fromUtf8(""));
        btnDisparo->setIcon(icon);
        btnleAlarma_9 = new QCommandLinkButton(SisGasComb);
        btnleAlarma_9->setObjectName(QString::fromUtf8("btnleAlarma_9"));
        btnleAlarma_9->setGeometry(QRect(848, 311, 20, 21));
        btnleAlarma_9->setStyleSheet(QString::fromUtf8(""));
        btnleAlarma_9->setIcon(icon);

        retranslateUi(SisGasComb);

        QMetaObject::connectSlotsByName(SisGasComb);
    } // setupUi

    void retranslateUi(QWidget *SisGasComb)
    {
        SisGasComb->setWindowTitle(QApplication::translate("SisGasComb", "Form", 0, QApplication::UnicodeUTF8));
        lbFondo->setText(QString());
        lbPatinT->setText(QApplication::translate("SisGasComb", "PATIN DEL COMPRESOR DE AIRE", 0, QApplication::UnicodeUTF8));
        lbts208cT->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_YS_208C_F_CV", 0, QApplication::UnicodeUTF8));
        lbts208cT->setText(QApplication::translate("SisGasComb", "ALARMA SISTEMA DE DETECCI\303\222N DE INCENDIO", 0, QApplication::UnicodeUTF8));
        lbts208AT->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_YS_208A_F_CV", 0, QApplication::UnicodeUTF8));
        lbts208AT->setText(QApplication::translate("SisGasComb", "YS_208A", 0, QApplication::UnicodeUTF8));
        lbts208bT->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_YS_208B_F_CV", 0, QApplication::UnicodeUTF8));
        lbts208bT->setText(QApplication::translate("SisGasComb", "YS_208B", 0, QApplication::UnicodeUTF8));
        lbAlarIncT->setText(QApplication::translate("SisGasComb", "ALARMA SISTEMA DE DETECCI\303\222N DE INCENDIO", 0, QApplication::UnicodeUTF8));
        lbComMarcAT->setText(QApplication::translate("SisGasComb", "COMPRESOR DEAIRE A EN MARCHA", 0, QApplication::UnicodeUTF8));
        lbComMarcBT->setText(QApplication::translate("SisGasComb", "COMPRESOR DEAIRE B EN MARCHA", 0, QApplication::UnicodeUTF8));
        btnleAlarma_01->setText(QString());
        btnleAlarma_02->setText(QString());
        lbts208AT_2->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_PIT_208_PV_REAL_F_CV", 0, QApplication::UnicodeUTF8));
        lbts208AT_2->setText(QApplication::translate("SisGasComb", "????", 0, QApplication::UnicodeUTF8));
        lbSisGasT->setText(QApplication::translate("SisGasComb", "SISTEMA DE GAS COMBUSTIBLE", 0, QApplication::UnicodeUTF8));
        lbBotT->setText(QApplication::translate("SisGasComb", "BOTON DE DISPARO\n"
"DEL GAS COMBUSTIBLE", 0, QApplication::UnicodeUTF8));
        lbPatinCompT->setText(QApplication::translate("SisGasComb", "PATIN DEL COMPRESOR\n"
"DE GAS COMBUSTIBLE ", 0, QApplication::UnicodeUTF8));
        lbsk079->setText(QApplication::translate("SisGasComb", "SK - 079", 0, QApplication::UnicodeUTF8));
        lbEnfComb->setText(QApplication::translate("SisGasComb", "ENFRIADOR DE \n"
"GAS COMBUSTIBLE", 0, QApplication::UnicodeUTF8));
        lbSk080T->setText(QApplication::translate("SisGasComb", "SK - 080", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_1->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_1", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_2->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_2", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_3->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_3", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_4->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_4", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_8->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_8", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_7->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_7", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_6->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_6", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_5->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_5", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_11->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_11", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_9->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_9", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_10->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_10", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_21->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_21", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_14->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_14", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_19->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_19", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_13->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_13", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_16->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_16", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_12->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_12", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_15->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_15", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_17->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_17", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_18->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_18", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMO_20->setText(QApplication::translate("SisGasComb", "GAS_CHROMO_20", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("SisGasComb", "CROMATOGRAFOS DE GAS", 0, QApplication::UnicodeUTF8));
        lbMole_11->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_3->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_8->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_2->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_5->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_1->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_4->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_6->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_7->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_9->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbMole_10->setText(QApplication::translate("SisGasComb", "MOLE", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_11->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_10->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_3->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_5->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_9->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_7->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_1->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_2->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_6->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_4->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_8->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        label_70->setText(QApplication::translate("SisGasComb", "ETHANE", 0, QApplication::UnicodeUTF8));
        label_71->setText(QApplication::translate("SisGasComb", "I-BUTANE", 0, QApplication::UnicodeUTF8));
        label_72->setText(QApplication::translate("SisGasComb", "CO2", 0, QApplication::UnicodeUTF8));
        label_73->setText(QApplication::translate("SisGasComb", "NEOPENTANE", 0, QApplication::UnicodeUTF8));
        label_74->setText(QApplication::translate("SisGasComb", "METHANE", 0, QApplication::UnicodeUTF8));
        label_75->setText(QApplication::translate("SisGasComb", "n-PETANE", 0, QApplication::UnicodeUTF8));
        label_76->setText(QApplication::translate("SisGasComb", "C6(N-EXANE)", 0, QApplication::UnicodeUTF8));
        label_77->setText(QApplication::translate("SisGasComb", "PROPANE", 0, QApplication::UnicodeUTF8));
        label_78->setText(QApplication::translate("SisGasComb", "i-PETANE", 0, QApplication::UnicodeUTF8));
        label_79->setText(QApplication::translate("SisGasComb", "N-BUTANE", 0, QApplication::UnicodeUTF8));
        label_80->setText(QApplication::translate("SisGasComb", "NITROGEN", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_11->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_11_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_11->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_3->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_3_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_3->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_10->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_10_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_10->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_5->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_5_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_5->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_9->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_9_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_9->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_7->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_7_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_7->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_1->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_1_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_1->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_2->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_2_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_2->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_6->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_6_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_6->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_4->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_4_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_4->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_8->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_8_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_8->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        label_92->setText(QApplication::translate("SisGasComb", "ETHANE", 0, QApplication::UnicodeUTF8));
        label_93->setText(QApplication::translate("SisGasComb", "PROPANE", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_12->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        label_95->setText(QApplication::translate("SisGasComb", "i-PETANE", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_17->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_13->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_15->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        label_99->setText(QApplication::translate("SisGasComb", "N-BUTANE", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_21->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        label_101->setText(QApplication::translate("SisGasComb", "I-BUTANE", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_19->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        label_103->setText(QApplication::translate("SisGasComb", "NITROGEN", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_22->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_14->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        label_106->setText(QApplication::translate("SisGasComb", "CO2", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_16->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        label_108->setText(QApplication::translate("SisGasComb", "NEOPENTANE", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_20->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        label_110->setText(QApplication::translate("SisGasComb", "C6(N-EXANE)", 0, QApplication::UnicodeUTF8));
        label_111->setText(QApplication::translate("SisGasComb", "n-PETANE", 0, QApplication::UnicodeUTF8));
        label_112->setText(QApplication::translate("SisGasComb", "METHANE", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOPor_18->setText(QApplication::translate("SisGasComb", "%", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_14->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_14_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_14->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_15->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_15_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_15->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_20->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_17->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_17_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_17->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_16->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_16_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_16->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_13->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_13_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_13->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_19->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_12->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_12_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_12->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_21->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_18->setId(QApplication::translate("SisGasComb", "p_Fix32_NODE_GAS_CHROMO_18_F_CV", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOVal_18->setText(QApplication::translate("SisGasComb", "00.00", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_21->setText(QApplication::translate("SisGasComb", "KCAL/m3", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_15->setText(QApplication::translate("SisGasComb", "KCAL/m3", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_13->setText(QApplication::translate("SisGasComb", "KCAL/m3", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_14->setText(QApplication::translate("SisGasComb", "KCAL/m3", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_16->setText(QApplication::translate("SisGasComb", "KCAL/m3", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_17->setText(QApplication::translate("SisGasComb", "KCAL/m3", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_12->setText(QApplication::translate("SisGasComb", "KCAL/m3", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_20->setText(QString());
        lbGAS_CHROMOU_19->setText(QApplication::translate("SisGasComb", "\302\272C", 0, QApplication::UnicodeUTF8));
        lbGAS_CHROMOU_18->setText(QString());
        label_135->setText(QApplication::translate("SisGasComb", "PODER CALORIFICO SUPERIOR ACTUAL", 0, QApplication::UnicodeUTF8));
        label_136->setText(QApplication::translate("SisGasComb", "PODER CALORIFICO INFERIOR BASE SECO", 0, QApplication::UnicodeUTF8));
        label_137->setText(QApplication::translate("SisGasComb", "FACTOR DE COMPRESIBILIDAD", 0, QApplication::UnicodeUTF8));
        label_138->setText(QApplication::translate("SisGasComb", "PODER CALORIFICO INFERIOR BASE SATURADO", 0, QApplication::UnicodeUTF8));
        label_139->setText(QApplication::translate("SisGasComb", "PODER CALORIFICO INFERIOR BASE SATURADO", 0, QApplication::UnicodeUTF8));
        label_140->setText(QApplication::translate("SisGasComb", "PODER CALORIFICO SUPERIOR BASE SATURADO", 0, QApplication::UnicodeUTF8));
        label_141->setText(QApplication::translate("SisGasComb", "VALOR DE TEMPERATURA DE REFERENCIA", 0, QApplication::UnicodeUTF8));
        label_142->setText(QApplication::translate("SisGasComb", "PODER CALORIFICO SUPERIOR BASE SECO", 0, QApplication::UnicodeUTF8));
        label_143->setText(QApplication::translate("SisGasComb", "CONCENTRACI\303\222N TOTAL NO NORMALIZADA", 0, QApplication::UnicodeUTF8));
        label_144->setText(QApplication::translate("SisGasComb", "DENSIDAD RELATIVACORREGIDA DEL GAS", 0, QApplication::UnicodeUTF8));
        lbFilGasT->setText(QApplication::translate("SisGasComb", "FILTRO\n"
"DE GAS", 0, QApplication::UnicodeUTF8));
        lbsk082T->setText(QApplication::translate("SisGasComb", "SK - 082", 0, QApplication::UnicodeUTF8));
        lbVenT->setText(QApplication::translate("SisGasComb", "VENTEO", 0, QApplication::UnicodeUTF8));
        lbVenT_2->setText(QApplication::translate("SisGasComb", "VENTEO", 0, QApplication::UnicodeUTF8));
        lbResidT->setText(QApplication::translate("SisGasComb", "RESIDUOS\n"
"ACEITOSOS", 0, QApplication::UnicodeUTF8));
        lbEntraT->setText(QApplication::translate("SisGasComb", "ENTREGA DE\n"
"GAS", 0, QApplication::UnicodeUTF8));
        lbEntraT_2->setText(QApplication::translate("SisGasComb", "ENTREGA DE\n"
" GAS", 0, QApplication::UnicodeUTF8));
        lbxy106bT->setText(QApplication::translate("SisGasComb", "XY-106B", 0, QApplication::UnicodeUTF8));
        lbXy106aT->setText(QApplication::translate("SisGasComb", "XY-106A", 0, QApplication::UnicodeUTF8));
        lbXy107b->setText(QApplication::translate("SisGasComb", "XY-107B", 0, QApplication::UnicodeUTF8));
        lbXy107aT->setText(QApplication::translate("SisGasComb", "XY-107A", 0, QApplication::UnicodeUTF8));
        btImpr->setText(QApplication::translate("SisGasComb", "IMP PANT", 0, QApplication::UnicodeUTF8));
        btnleAlarma_1->setText(QString());
        btnleAlarma_03->setText(QString());
        btnleAlarma_4->setText(QString());
        btnleAlarma_04->setText(QString());
        btnDisparo->setText(QString());
        btnleAlarma_9->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class SisGasComb: public Ui_SisGasComb {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SISGASCOMB_H
