/********************************************************************************
** Form generated from reading UI file 'widget.ui'
**
** Created: Thu 19. Dec 14:36:09 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WIDGET_H
#define UI_WIDGET_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_Widget
{
public:
    QLabel *lbLinea;
    QFrame *frameLinea;
    QLabel *lbLineaT;
    QLabel *lbTG1T;
    QFrame *frameVariable;
    QLabel *lbEncabezadoT;
    QFrame *frameEtiq;
    QLabel *lbEtiqT;
    QFrame *frame;
    QLabel *lbLecT;
    QFrame *frame_2;
    QLabel *lbUnidT;
    QLabel *lbCemsT;
    QFrame *frame_3;
    QFrame *frame_4;
    QLabel *lbLectNoxT;
    QFrame *frame_5;
    QLabel *lbCemsNoxT;
    QFrame *frame_6;
    WLabel *lbNox;
    QFrame *frame_7;
    QLabel *lBNoxU;
    QFrame *frame_8;
    QFrame *frame_9;
    QFrame *frame_10;
    WLabel *lbNox_4;
    QFrame *frame_17;
    QFrame *frame_18;
    QFrame *frame_27;
    QFrame *frame_28;
    QFrame *frame_29;
    WLabel *lbNox_5;
    QFrame *frame_30;
    QFrame *frame_31;
    QFrame *frame_32;
    WLabel *lbNox_6;
    QFrame *frame_33;
    QFrame *frame_34;
    QLabel *lbCoU;
    QFrame *frame_35;
    WLabel *lbNox_2;
    QFrame *frame_36;
    QLabel *lbCemsCoT;
    QFrame *frame_37;
    QLabel *lbLectCoT;
    QFrame *frame_38;
    QFrame *frame_39;
    QFrame *frame_41;
    QFrame *frame_42;
    QFrame *frame_66;
    QFrame *frame_67;
    QFrame *frame_68;
    WLabel *lbNox_9;
    QFrame *frame_95;
    WLabel *lbNox_8;
    QFrame *frame_96;
    WLabel *lbNox_7;
    QFrame *frame_97;
    QFrame *frame_127;
    QFrame *frame_128;
    QFrame *frame_129;
    QLabel *lbO2U;
    QFrame *frame_131;
    WLabel *lbNox_3;
    QFrame *frame_132;
    QLabel *lbCemsO2T;
    QFrame *frame_133;
    QFrame *frame_134;
    QFrame *frame_135;
    QFrame *frame_138;
    QFrame *frame_178;
    QFrame *frame_179;
    QFrame *frame_180;
    WLabel *lbNox_12;
    QFrame *frame_181;
    WLabel *lbNox_11;
    QFrame *frame_182;
    WLabel *lbNox_10;
    QFrame *frame_183;
    WLabel *lbNox_15;
    QFrame *frame_184;
    WLabel *lbNox_14;
    QFrame *frame_185;
    WLabel *lbNox_13;
    QFrame *frame_186;
    WLabel *lbNox_16;
    QFrame *frame_187;
    QFrame *frame_188;
    QFrame *frame_189;
    QFrame *frame_190;
    QFrame *frame_191;
    QFrame *frame_192;
    QFrame *frame_193;
    QFrame *frame_194;
    QLabel *lbCemsEroMantT;
    QFrame *frame_195;
    QLabel *lbCemsMantT;
    QFrame *frame_196;
    QLabel *lbCemsEroTroubleT;
    QFrame *frame_197;
    QLabel *lbAlarmCemsT;
    QFrame *frame_198;
    QLabel *lbFallasCalibT;
    QFrame *frame_199;
    QLabel *lbCemsCalibT;
    QFrame *frame_200;
    QLabel *lbCemsEroCalT;
    QFrame *frame_201;
    QLabel *lbCemsEroIncalT;
    QFrame *frame_130;
    QLabel *lbLectO2T;
    QPushButton *btTurbinaMant;
    QPushButton *btResetCems;
    QPushButton *btImpPant;

    void setupUi(QWidget *Widget)
    {
        if (Widget->objectName().isEmpty())
            Widget->setObjectName(QString::fromUtf8("Widget"));
        Widget->resize(1024, 662);
        Widget->setMinimumSize(QSize(1024, 662));
        Widget->setMaximumSize(QSize(1024, 662));
        lbLinea = new QLabel(Widget);
        lbLinea->setObjectName(QString::fromUtf8("lbLinea"));
        lbLinea->setGeometry(QRect(0, 0, 1024, 662));
        lbLinea->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/BackGround.png")));
        lbLinea->setScaledContents(true);
        frameLinea = new QFrame(Widget);
        frameLinea->setObjectName(QString::fromUtf8("frameLinea"));
        frameLinea->setGeometry(QRect(30, 150, 68, 115));
        frameLinea->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        frameLinea->setFrameShape(QFrame::Box);
        frameLinea->setFrameShadow(QFrame::Raised);
        lbLineaT = new QLabel(frameLinea);
        lbLineaT->setObjectName(QString::fromUtf8("lbLineaT"));
        lbLineaT->setGeometry(QRect(10, 20, 52, 22));
        lbLineaT->setAlignment(Qt::AlignCenter);
        lbTG1T = new QLabel(frameLinea);
        lbTG1T->setObjectName(QString::fromUtf8("lbTG1T"));
        lbTG1T->setGeometry(QRect(18, 45, 31, 16));
        lbTG1T->setAlignment(Qt::AlignCenter);
        frameVariable = new QFrame(Widget);
        frameVariable->setObjectName(QString::fromUtf8("frameVariable"));
        frameVariable->setGeometry(QRect(109, 93, 263, 36));
        frameVariable->setFrameShape(QFrame::Box);
        frameVariable->setFrameShadow(QFrame::Raised);
        lbEncabezadoT = new QLabel(frameVariable);
        lbEncabezadoT->setObjectName(QString::fromUtf8("lbEncabezadoT"));
        lbEncabezadoT->setGeometry(QRect(12, 7, 231, 20));
        QFont font;
        font.setPointSize(9);
        lbEncabezadoT->setFont(font);
        lbEncabezadoT->setAlignment(Qt::AlignCenter);
        frameEtiq = new QFrame(Widget);
        frameEtiq->setObjectName(QString::fromUtf8("frameEtiq"));
        frameEtiq->setGeometry(QRect(371, 93, 180, 36));
        frameEtiq->setFont(font);
        frameEtiq->setFrameShape(QFrame::Box);
        frameEtiq->setFrameShadow(QFrame::Raised);
        lbEtiqT = new QLabel(frameEtiq);
        lbEtiqT->setObjectName(QString::fromUtf8("lbEtiqT"));
        lbEtiqT->setGeometry(QRect(13, 7, 151, 20));
        lbEtiqT->setAlignment(Qt::AlignCenter);
        frame = new QFrame(Widget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(550, 93, 139, 36));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Raised);
        lbLecT = new QLabel(frame);
        lbLecT->setObjectName(QString::fromUtf8("lbLecT"));
        lbLecT->setGeometry(QRect(10, 0, 111, 36));
        lbLecT->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(Widget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(688, 93, 142, 36));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Raised);
        lbUnidT = new QLabel(frame_2);
        lbUnidT->setObjectName(QString::fromUtf8("lbUnidT"));
        lbUnidT->setGeometry(QRect(20, 7, 101, 21));
        lbUnidT->setFont(font);
        lbUnidT->setAlignment(Qt::AlignCenter);
        lbCemsT = new QLabel(Widget);
        lbCemsT->setObjectName(QString::fromUtf8("lbCemsT"));
        lbCemsT->setGeometry(QRect(442, 6, 69, 17));
        QFont font1;
        font1.setPointSize(11);
        lbCemsT->setFont(font1);
        lbCemsT->setAlignment(Qt::AlignCenter);
        frame_3 = new QFrame(Widget);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(109, 154, 719, 296));
        frame_3->setStyleSheet(QString::fromUtf8("borde: rgb(0, 0, 0);"));
        frame_3->setFrameShape(QFrame::Box);
        frame_3->setFrameShadow(QFrame::Raised);
        frame_4 = new QFrame(frame_3);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(0, 0, 263, 18));
        frame_4->setFrameShape(QFrame::Box);
        frame_4->setFrameShadow(QFrame::Raised);
        lbLectNoxT = new QLabel(frame_4);
        lbLectNoxT->setObjectName(QString::fromUtf8("lbLectNoxT"));
        lbLectNoxT->setGeometry(QRect(8, 0, 241, 16));
        lbLectNoxT->setFont(font);
        lbLectNoxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_5 = new QFrame(frame_3);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(262, 0, 183, 18));
        frame_5->setFrameShape(QFrame::Box);
        frame_5->setFrameShadow(QFrame::Raised);
        lbCemsNoxT = new QLabel(frame_5);
        lbCemsNoxT->setObjectName(QString::fromUtf8("lbCemsNoxT"));
        lbCemsNoxT->setGeometry(QRect(8, 0, 151, 20));
        lbCemsNoxT->setFont(font);
        frame_6 = new QFrame(frame_3);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(443, 0, 139, 18));
        frame_6->setFrameShape(QFrame::Box);
        frame_6->setFrameShadow(QFrame::Raised);
        lbNox = new WLabel(frame_6);
        lbNox->setObjectName(QString::fromUtf8("lbNox"));
        lbNox->setGeometry(QRect(14, 0, 111, 20));
        lbNox->setFont(font);
        lbNox->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_7 = new QFrame(frame_3);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(580, 0, 140, 18));
        frame_7->setFrameShape(QFrame::Box);
        frame_7->setFrameShadow(QFrame::Raised);
        lBNoxU = new QLabel(frame_7);
        lBNoxU->setObjectName(QString::fromUtf8("lBNoxU"));
        lBNoxU->setGeometry(QRect(10, 0, 111, 20));
        lBNoxU->setFont(font);
        frame_8 = new QFrame(frame_3);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(0, 17, 263, 21));
        frame_8->setFrameShape(QFrame::Box);
        frame_8->setFrameShadow(QFrame::Raised);
        frame_9 = new QFrame(frame_3);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(262, 17, 183, 21));
        frame_9->setFrameShape(QFrame::Box);
        frame_9->setFrameShadow(QFrame::Raised);
        frame_10 = new QFrame(frame_3);
        frame_10->setObjectName(QString::fromUtf8("frame_10"));
        frame_10->setGeometry(QRect(443, 17, 139, 21));
        frame_10->setFrameShape(QFrame::Box);
        frame_10->setFrameShadow(QFrame::Raised);
        lbNox_4 = new WLabel(frame_10);
        lbNox_4->setObjectName(QString::fromUtf8("lbNox_4"));
        lbNox_4->setGeometry(QRect(10, 0, 111, 20));
        lbNox_4->setFont(font);
        lbNox_4->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_17 = new QFrame(frame_3);
        frame_17->setObjectName(QString::fromUtf8("frame_17"));
        frame_17->setGeometry(QRect(580, 17, 140, 21));
        frame_17->setFrameShape(QFrame::Box);
        frame_17->setFrameShadow(QFrame::Raised);
        frame_18 = new QFrame(frame_3);
        frame_18->setObjectName(QString::fromUtf8("frame_18"));
        frame_18->setGeometry(QRect(262, 37, 183, 19));
        frame_18->setFrameShape(QFrame::Box);
        frame_18->setFrameShadow(QFrame::Raised);
        frame_27 = new QFrame(frame_3);
        frame_27->setObjectName(QString::fromUtf8("frame_27"));
        frame_27->setGeometry(QRect(0, 37, 263, 20));
        frame_27->setFrameShape(QFrame::Box);
        frame_27->setFrameShadow(QFrame::Raised);
        frame_28 = new QFrame(frame_3);
        frame_28->setObjectName(QString::fromUtf8("frame_28"));
        frame_28->setGeometry(QRect(580, 37, 140, 21));
        frame_28->setFrameShape(QFrame::Box);
        frame_28->setFrameShadow(QFrame::Raised);
        frame_29 = new QFrame(frame_3);
        frame_29->setObjectName(QString::fromUtf8("frame_29"));
        frame_29->setGeometry(QRect(443, 37, 139, 21));
        frame_29->setFrameShape(QFrame::Box);
        frame_29->setFrameShadow(QFrame::Raised);
        lbNox_5 = new WLabel(frame_29);
        lbNox_5->setObjectName(QString::fromUtf8("lbNox_5"));
        lbNox_5->setGeometry(QRect(10, 0, 111, 20));
        lbNox_5->setFont(font);
        lbNox_5->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_30 = new QFrame(frame_3);
        frame_30->setObjectName(QString::fromUtf8("frame_30"));
        frame_30->setGeometry(QRect(0, 55, 263, 20));
        frame_30->setFrameShape(QFrame::Box);
        frame_30->setFrameShadow(QFrame::Raised);
        frame_31 = new QFrame(frame_3);
        frame_31->setObjectName(QString::fromUtf8("frame_31"));
        frame_31->setGeometry(QRect(262, 55, 183, 20));
        frame_31->setFrameShape(QFrame::Box);
        frame_31->setFrameShadow(QFrame::Raised);
        frame_32 = new QFrame(frame_3);
        frame_32->setObjectName(QString::fromUtf8("frame_32"));
        frame_32->setGeometry(QRect(443, 56, 139, 20));
        frame_32->setFrameShape(QFrame::Box);
        frame_32->setFrameShadow(QFrame::Raised);
        lbNox_6 = new WLabel(frame_32);
        lbNox_6->setObjectName(QString::fromUtf8("lbNox_6"));
        lbNox_6->setGeometry(QRect(10, 0, 111, 20));
        lbNox_6->setFont(font);
        lbNox_6->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_33 = new QFrame(frame_3);
        frame_33->setObjectName(QString::fromUtf8("frame_33"));
        frame_33->setGeometry(QRect(580, 56, 140, 20));
        frame_33->setFrameShape(QFrame::Box);
        frame_33->setFrameShadow(QFrame::Raised);
        frame_34 = new QFrame(frame_3);
        frame_34->setObjectName(QString::fromUtf8("frame_34"));
        frame_34->setGeometry(QRect(580, 74, 140, 20));
        frame_34->setFrameShape(QFrame::Box);
        frame_34->setFrameShadow(QFrame::Raised);
        lbCoU = new QLabel(frame_34);
        lbCoU->setObjectName(QString::fromUtf8("lbCoU"));
        lbCoU->setGeometry(QRect(10, 0, 111, 20));
        lbCoU->setFont(font);
        frame_35 = new QFrame(frame_3);
        frame_35->setObjectName(QString::fromUtf8("frame_35"));
        frame_35->setGeometry(QRect(442, 74, 140, 20));
        frame_35->setFrameShape(QFrame::Box);
        frame_35->setFrameShadow(QFrame::Raised);
        lbNox_2 = new WLabel(frame_35);
        lbNox_2->setObjectName(QString::fromUtf8("lbNox_2"));
        lbNox_2->setGeometry(QRect(10, 0, 111, 20));
        lbNox_2->setFont(font);
        lbNox_2->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_36 = new QFrame(frame_3);
        frame_36->setObjectName(QString::fromUtf8("frame_36"));
        frame_36->setGeometry(QRect(262, 74, 183, 20));
        frame_36->setFrameShape(QFrame::Box);
        frame_36->setFrameShadow(QFrame::Raised);
        lbCemsCoT = new QLabel(frame_36);
        lbCemsCoT->setObjectName(QString::fromUtf8("lbCemsCoT"));
        lbCemsCoT->setGeometry(QRect(8, 0, 151, 20));
        lbCemsCoT->setFont(font);
        frame_37 = new QFrame(frame_3);
        frame_37->setObjectName(QString::fromUtf8("frame_37"));
        frame_37->setGeometry(QRect(0, 74, 263, 20));
        frame_37->setFrameShape(QFrame::Box);
        frame_37->setFrameShadow(QFrame::Raised);
        lbLectCoT = new QLabel(frame_37);
        lbLectCoT->setObjectName(QString::fromUtf8("lbLectCoT"));
        lbLectCoT->setGeometry(QRect(8, 0, 231, 20));
        lbLectCoT->setFont(font);
        lbLectCoT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_38 = new QFrame(frame_3);
        frame_38->setObjectName(QString::fromUtf8("frame_38"));
        frame_38->setGeometry(QRect(0, 130, 263, 20));
        frame_38->setFrameShape(QFrame::Box);
        frame_38->setFrameShadow(QFrame::Raised);
        frame_39 = new QFrame(frame_3);
        frame_39->setObjectName(QString::fromUtf8("frame_39"));
        frame_39->setGeometry(QRect(0, 111, 263, 21));
        frame_39->setFrameShape(QFrame::Box);
        frame_39->setFrameShadow(QFrame::Raised);
        frame_41 = new QFrame(frame_3);
        frame_41->setObjectName(QString::fromUtf8("frame_41"));
        frame_41->setGeometry(QRect(0, 92, 263, 21));
        frame_41->setFrameShape(QFrame::Box);
        frame_41->setFrameShadow(QFrame::Raised);
        frame_42 = new QFrame(frame_3);
        frame_42->setObjectName(QString::fromUtf8("frame_42"));
        frame_42->setGeometry(QRect(262, 130, 183, 20));
        frame_42->setFrameShape(QFrame::Box);
        frame_42->setFrameShadow(QFrame::Raised);
        frame_66 = new QFrame(frame_3);
        frame_66->setObjectName(QString::fromUtf8("frame_66"));
        frame_66->setGeometry(QRect(262, 111, 183, 21));
        frame_66->setFrameShape(QFrame::Box);
        frame_66->setFrameShadow(QFrame::Raised);
        frame_67 = new QFrame(frame_3);
        frame_67->setObjectName(QString::fromUtf8("frame_67"));
        frame_67->setGeometry(QRect(262, 92, 183, 21));
        frame_67->setFrameShape(QFrame::Box);
        frame_67->setFrameShadow(QFrame::Raised);
        frame_68 = new QFrame(frame_3);
        frame_68->setObjectName(QString::fromUtf8("frame_68"));
        frame_68->setGeometry(QRect(443, 130, 139, 20));
        frame_68->setFrameShape(QFrame::Box);
        frame_68->setFrameShadow(QFrame::Raised);
        lbNox_9 = new WLabel(frame_68);
        lbNox_9->setObjectName(QString::fromUtf8("lbNox_9"));
        lbNox_9->setGeometry(QRect(10, 0, 111, 20));
        lbNox_9->setFont(font);
        lbNox_9->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_95 = new QFrame(frame_3);
        frame_95->setObjectName(QString::fromUtf8("frame_95"));
        frame_95->setGeometry(QRect(443, 111, 139, 21));
        frame_95->setFrameShape(QFrame::Box);
        frame_95->setFrameShadow(QFrame::Raised);
        lbNox_8 = new WLabel(frame_95);
        lbNox_8->setObjectName(QString::fromUtf8("lbNox_8"));
        lbNox_8->setGeometry(QRect(10, 0, 111, 20));
        lbNox_8->setFont(font);
        lbNox_8->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_96 = new QFrame(frame_3);
        frame_96->setObjectName(QString::fromUtf8("frame_96"));
        frame_96->setGeometry(QRect(443, 92, 139, 21));
        frame_96->setFrameShape(QFrame::Box);
        frame_96->setFrameShadow(QFrame::Raised);
        lbNox_7 = new WLabel(frame_96);
        lbNox_7->setObjectName(QString::fromUtf8("lbNox_7"));
        lbNox_7->setGeometry(QRect(10, 0, 111, 20));
        lbNox_7->setFont(font);
        lbNox_7->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_97 = new QFrame(frame_3);
        frame_97->setObjectName(QString::fromUtf8("frame_97"));
        frame_97->setGeometry(QRect(580, 130, 140, 20));
        frame_97->setFrameShape(QFrame::Box);
        frame_97->setFrameShadow(QFrame::Raised);
        frame_127 = new QFrame(frame_3);
        frame_127->setObjectName(QString::fromUtf8("frame_127"));
        frame_127->setGeometry(QRect(580, 111, 140, 21));
        frame_127->setFrameShape(QFrame::Box);
        frame_127->setFrameShadow(QFrame::Raised);
        frame_128 = new QFrame(frame_3);
        frame_128->setObjectName(QString::fromUtf8("frame_128"));
        frame_128->setGeometry(QRect(580, 92, 140, 21));
        frame_128->setFrameShape(QFrame::Box);
        frame_128->setFrameShadow(QFrame::Raised);
        frame_129 = new QFrame(frame_3);
        frame_129->setObjectName(QString::fromUtf8("frame_129"));
        frame_129->setGeometry(QRect(580, 149, 140, 20));
        frame_129->setFrameShape(QFrame::Box);
        frame_129->setFrameShadow(QFrame::Raised);
        lbO2U = new QLabel(frame_129);
        lbO2U->setObjectName(QString::fromUtf8("lbO2U"));
        lbO2U->setGeometry(QRect(10, 0, 111, 20));
        lbO2U->setFont(font);
        frame_131 = new QFrame(frame_3);
        frame_131->setObjectName(QString::fromUtf8("frame_131"));
        frame_131->setGeometry(QRect(442, 149, 140, 20));
        frame_131->setFrameShape(QFrame::Box);
        frame_131->setFrameShadow(QFrame::Raised);
        lbNox_3 = new WLabel(frame_131);
        lbNox_3->setObjectName(QString::fromUtf8("lbNox_3"));
        lbNox_3->setGeometry(QRect(10, 0, 111, 20));
        lbNox_3->setFont(font);
        lbNox_3->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_132 = new QFrame(frame_3);
        frame_132->setObjectName(QString::fromUtf8("frame_132"));
        frame_132->setGeometry(QRect(262, 149, 183, 20));
        frame_132->setFrameShape(QFrame::Box);
        frame_132->setFrameShadow(QFrame::Raised);
        lbCemsO2T = new QLabel(frame_132);
        lbCemsO2T->setObjectName(QString::fromUtf8("lbCemsO2T"));
        lbCemsO2T->setGeometry(QRect(8, 0, 151, 20));
        lbCemsO2T->setFont(font);
        frame_133 = new QFrame(frame_3);
        frame_133->setObjectName(QString::fromUtf8("frame_133"));
        frame_133->setGeometry(QRect(0, 206, 263, 18));
        frame_133->setFrameShape(QFrame::Box);
        frame_133->setFrameShadow(QFrame::Raised);
        frame_134 = new QFrame(frame_3);
        frame_134->setObjectName(QString::fromUtf8("frame_134"));
        frame_134->setGeometry(QRect(0, 168, 263, 21));
        frame_134->setFrameShape(QFrame::Box);
        frame_134->setFrameShadow(QFrame::Raised);
        frame_135 = new QFrame(frame_3);
        frame_135->setObjectName(QString::fromUtf8("frame_135"));
        frame_135->setGeometry(QRect(0, 188, 263, 20));
        frame_135->setFrameShape(QFrame::Box);
        frame_135->setFrameShadow(QFrame::Raised);
        frame_138 = new QFrame(frame_3);
        frame_138->setObjectName(QString::fromUtf8("frame_138"));
        frame_138->setGeometry(QRect(262, 205, 183, 18));
        frame_138->setFrameShape(QFrame::Box);
        frame_138->setFrameShadow(QFrame::Raised);
        frame_178 = new QFrame(frame_3);
        frame_178->setObjectName(QString::fromUtf8("frame_178"));
        frame_178->setGeometry(QRect(262, 187, 183, 20));
        frame_178->setFrameShape(QFrame::Box);
        frame_178->setFrameShadow(QFrame::Raised);
        frame_179 = new QFrame(frame_3);
        frame_179->setObjectName(QString::fromUtf8("frame_179"));
        frame_179->setGeometry(QRect(262, 168, 183, 21));
        frame_179->setFrameShape(QFrame::Box);
        frame_179->setFrameShadow(QFrame::Raised);
        frame_180 = new QFrame(frame_3);
        frame_180->setObjectName(QString::fromUtf8("frame_180"));
        frame_180->setGeometry(QRect(443, 205, 139, 18));
        frame_180->setFrameShape(QFrame::Box);
        frame_180->setFrameShadow(QFrame::Raised);
        lbNox_12 = new WLabel(frame_180);
        lbNox_12->setObjectName(QString::fromUtf8("lbNox_12"));
        lbNox_12->setGeometry(QRect(10, 0, 111, 20));
        lbNox_12->setFont(font);
        lbNox_12->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_181 = new QFrame(frame_3);
        frame_181->setObjectName(QString::fromUtf8("frame_181"));
        frame_181->setGeometry(QRect(443, 187, 139, 20));
        frame_181->setFrameShape(QFrame::Box);
        frame_181->setFrameShadow(QFrame::Raised);
        lbNox_11 = new WLabel(frame_181);
        lbNox_11->setObjectName(QString::fromUtf8("lbNox_11"));
        lbNox_11->setGeometry(QRect(10, 0, 111, 20));
        lbNox_11->setFont(font);
        lbNox_11->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_182 = new QFrame(frame_3);
        frame_182->setObjectName(QString::fromUtf8("frame_182"));
        frame_182->setGeometry(QRect(443, 168, 139, 21));
        frame_182->setFrameShape(QFrame::Box);
        frame_182->setFrameShadow(QFrame::Raised);
        lbNox_10 = new WLabel(frame_182);
        lbNox_10->setObjectName(QString::fromUtf8("lbNox_10"));
        lbNox_10->setGeometry(QRect(10, 0, 111, 20));
        lbNox_10->setFont(font);
        lbNox_10->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_183 = new QFrame(frame_3);
        frame_183->setObjectName(QString::fromUtf8("frame_183"));
        frame_183->setGeometry(QRect(442, 260, 139, 20));
        frame_183->setFrameShape(QFrame::Box);
        frame_183->setFrameShadow(QFrame::Raised);
        lbNox_15 = new WLabel(frame_183);
        lbNox_15->setObjectName(QString::fromUtf8("lbNox_15"));
        lbNox_15->setGeometry(QRect(10, 0, 111, 20));
        lbNox_15->setFont(font);
        lbNox_15->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_184 = new QFrame(frame_3);
        frame_184->setObjectName(QString::fromUtf8("frame_184"));
        frame_184->setGeometry(QRect(442, 240, 139, 22));
        frame_184->setFrameShape(QFrame::Box);
        frame_184->setFrameShadow(QFrame::Raised);
        lbNox_14 = new WLabel(frame_184);
        lbNox_14->setObjectName(QString::fromUtf8("lbNox_14"));
        lbNox_14->setGeometry(QRect(10, 0, 111, 20));
        lbNox_14->setFont(font);
        lbNox_14->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_185 = new QFrame(frame_3);
        frame_185->setObjectName(QString::fromUtf8("frame_185"));
        frame_185->setGeometry(QRect(442, 222, 139, 20));
        frame_185->setFrameShape(QFrame::Box);
        frame_185->setFrameShadow(QFrame::Raised);
        lbNox_13 = new WLabel(frame_185);
        lbNox_13->setObjectName(QString::fromUtf8("lbNox_13"));
        lbNox_13->setGeometry(QRect(10, 0, 111, 20));
        lbNox_13->setFont(font);
        lbNox_13->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_186 = new QFrame(frame_3);
        frame_186->setObjectName(QString::fromUtf8("frame_186"));
        frame_186->setGeometry(QRect(442, 278, 139, 20));
        frame_186->setFrameShape(QFrame::Box);
        frame_186->setFrameShadow(QFrame::Raised);
        lbNox_16 = new WLabel(frame_186);
        lbNox_16->setObjectName(QString::fromUtf8("lbNox_16"));
        lbNox_16->setGeometry(QRect(10, 0, 111, 20));
        lbNox_16->setFont(font);
        lbNox_16->setProperty("Alineacion", QVariant(WLabel::Centro));
        frame_187 = new QFrame(frame_3);
        frame_187->setObjectName(QString::fromUtf8("frame_187"));
        frame_187->setGeometry(QRect(580, 206, 140, 18));
        frame_187->setFrameShape(QFrame::Box);
        frame_187->setFrameShadow(QFrame::Raised);
        frame_188 = new QFrame(frame_3);
        frame_188->setObjectName(QString::fromUtf8("frame_188"));
        frame_188->setGeometry(QRect(580, 168, 140, 21));
        frame_188->setFrameShape(QFrame::Box);
        frame_188->setFrameShadow(QFrame::Raised);
        frame_189 = new QFrame(frame_3);
        frame_189->setObjectName(QString::fromUtf8("frame_189"));
        frame_189->setGeometry(QRect(580, 188, 140, 20));
        frame_189->setFrameShape(QFrame::Box);
        frame_189->setFrameShadow(QFrame::Raised);
        frame_190 = new QFrame(frame_3);
        frame_190->setObjectName(QString::fromUtf8("frame_190"));
        frame_190->setGeometry(QRect(580, 260, 140, 20));
        frame_190->setFrameShape(QFrame::Box);
        frame_190->setFrameShadow(QFrame::Raised);
        frame_191 = new QFrame(frame_3);
        frame_191->setObjectName(QString::fromUtf8("frame_191"));
        frame_191->setGeometry(QRect(580, 222, 140, 20));
        frame_191->setFrameShape(QFrame::Box);
        frame_191->setFrameShadow(QFrame::Raised);
        frame_192 = new QFrame(frame_3);
        frame_192->setObjectName(QString::fromUtf8("frame_192"));
        frame_192->setGeometry(QRect(580, 241, 140, 21));
        frame_192->setFrameShape(QFrame::Box);
        frame_192->setFrameShadow(QFrame::Raised);
        frame_193 = new QFrame(frame_3);
        frame_193->setObjectName(QString::fromUtf8("frame_193"));
        frame_193->setGeometry(QRect(580, 278, 140, 20));
        frame_193->setFrameShape(QFrame::Box);
        frame_193->setFrameShadow(QFrame::Raised);
        frame_194 = new QFrame(frame_3);
        frame_194->setObjectName(QString::fromUtf8("frame_194"));
        frame_194->setGeometry(QRect(262, 222, 183, 20));
        frame_194->setFrameShape(QFrame::Box);
        frame_194->setFrameShadow(QFrame::Raised);
        lbCemsEroMantT = new QLabel(frame_194);
        lbCemsEroMantT->setObjectName(QString::fromUtf8("lbCemsEroMantT"));
        lbCemsEroMantT->setGeometry(QRect(8, 0, 151, 20));
        lbCemsEroMantT->setFont(font);
        frame_195 = new QFrame(frame_3);
        frame_195->setObjectName(QString::fromUtf8("frame_195"));
        frame_195->setGeometry(QRect(0, 222, 263, 20));
        frame_195->setFrameShape(QFrame::Box);
        frame_195->setFrameShadow(QFrame::Raised);
        lbCemsMantT = new QLabel(frame_195);
        lbCemsMantT->setObjectName(QString::fromUtf8("lbCemsMantT"));
        lbCemsMantT->setGeometry(QRect(8, 0, 231, 20));
        lbCemsMantT->setFont(font);
        lbCemsMantT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_196 = new QFrame(frame_3);
        frame_196->setObjectName(QString::fromUtf8("frame_196"));
        frame_196->setGeometry(QRect(262, 241, 183, 20));
        frame_196->setFrameShape(QFrame::Box);
        frame_196->setFrameShadow(QFrame::Raised);
        lbCemsEroTroubleT = new QLabel(frame_196);
        lbCemsEroTroubleT->setObjectName(QString::fromUtf8("lbCemsEroTroubleT"));
        lbCemsEroTroubleT->setGeometry(QRect(8, 0, 151, 20));
        lbCemsEroTroubleT->setFont(font);
        frame_197 = new QFrame(frame_3);
        frame_197->setObjectName(QString::fromUtf8("frame_197"));
        frame_197->setGeometry(QRect(0, 241, 263, 20));
        frame_197->setFrameShape(QFrame::Box);
        frame_197->setFrameShadow(QFrame::Raised);
        lbAlarmCemsT = new QLabel(frame_197);
        lbAlarmCemsT->setObjectName(QString::fromUtf8("lbAlarmCemsT"));
        lbAlarmCemsT->setGeometry(QRect(8, 0, 231, 20));
        lbAlarmCemsT->setFont(font);
        lbAlarmCemsT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_198 = new QFrame(frame_3);
        frame_198->setObjectName(QString::fromUtf8("frame_198"));
        frame_198->setGeometry(QRect(0, 278, 263, 20));
        frame_198->setFrameShape(QFrame::Box);
        frame_198->setFrameShadow(QFrame::Raised);
        lbFallasCalibT = new QLabel(frame_198);
        lbFallasCalibT->setObjectName(QString::fromUtf8("lbFallasCalibT"));
        lbFallasCalibT->setGeometry(QRect(8, 0, 231, 20));
        lbFallasCalibT->setFont(font);
        lbFallasCalibT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_199 = new QFrame(frame_3);
        frame_199->setObjectName(QString::fromUtf8("frame_199"));
        frame_199->setGeometry(QRect(0, 260, 263, 20));
        frame_199->setFrameShape(QFrame::Box);
        frame_199->setFrameShadow(QFrame::Raised);
        lbCemsCalibT = new QLabel(frame_199);
        lbCemsCalibT->setObjectName(QString::fromUtf8("lbCemsCalibT"));
        lbCemsCalibT->setGeometry(QRect(8, 0, 231, 20));
        lbCemsCalibT->setFont(font);
        lbCemsCalibT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_200 = new QFrame(frame_3);
        frame_200->setObjectName(QString::fromUtf8("frame_200"));
        frame_200->setGeometry(QRect(262, 278, 183, 20));
        frame_200->setFrameShape(QFrame::Box);
        frame_200->setFrameShadow(QFrame::Raised);
        lbCemsEroCalT = new QLabel(frame_200);
        lbCemsEroCalT->setObjectName(QString::fromUtf8("lbCemsEroCalT"));
        lbCemsEroCalT->setGeometry(QRect(8, 0, 151, 20));
        lbCemsEroCalT->setFont(font);
        frame_201 = new QFrame(frame_3);
        frame_201->setObjectName(QString::fromUtf8("frame_201"));
        frame_201->setGeometry(QRect(262, 260, 183, 20));
        frame_201->setFrameShape(QFrame::Box);
        frame_201->setFrameShadow(QFrame::Raised);
        lbCemsEroIncalT = new QLabel(frame_201);
        lbCemsEroIncalT->setObjectName(QString::fromUtf8("lbCemsEroIncalT"));
        lbCemsEroIncalT->setGeometry(QRect(8, 0, 151, 20));
        lbCemsEroIncalT->setFont(font);
        frame_130 = new QFrame(frame_3);
        frame_130->setObjectName(QString::fromUtf8("frame_130"));
        frame_130->setGeometry(QRect(0, 149, 263, 21));
        frame_130->setFrameShape(QFrame::Box);
        frame_130->setFrameShadow(QFrame::Raised);
        lbLectO2T = new QLabel(frame_130);
        lbLectO2T->setObjectName(QString::fromUtf8("lbLectO2T"));
        lbLectO2T->setGeometry(QRect(8, 0, 231, 20));
        lbLectO2T->setFont(font);
        lbLectO2T->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        btTurbinaMant = new QPushButton(Widget);
        btTurbinaMant->setObjectName(QString::fromUtf8("btTurbinaMant"));
        btTurbinaMant->setGeometry(QRect(108, 500, 88, 36));
        QFont font2;
        font2.setPointSize(5);
        btTurbinaMant->setFont(font2);
        btTurbinaMant->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        btResetCems = new QPushButton(Widget);
        btResetCems->setObjectName(QString::fromUtf8("btResetCems"));
        btResetCems->setGeometry(QRect(197, 500, 88, 36));
        btResetCems->setFont(font2);
        btResetCems->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        btImpPant = new QPushButton(Widget);
        btImpPant->setObjectName(QString::fromUtf8("btImpPant"));
        btImpPant->setGeometry(QRect(20, 630, 133, 23));
        btImpPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));

        retranslateUi(Widget);

        QMetaObject::connectSlotsByName(Widget);
    } // setupUi

    void retranslateUi(QWidget *Widget)
    {
        Widget->setWindowTitle(QApplication::translate("Widget", "Widget", 0, QApplication::UnicodeUTF8));
        lbLinea->setText(QString());
        lbLineaT->setText(QApplication::translate("Widget", "LINEA 1", 0, QApplication::UnicodeUTF8));
        lbTG1T->setText(QApplication::translate("Widget", "TG1", 0, QApplication::UnicodeUTF8));
        lbEncabezadoT->setText(QApplication::translate("Widget", "VARIABLE", 0, QApplication::UnicodeUTF8));
        lbEtiqT->setText(QApplication::translate("Widget", "ETIQUETA", 0, QApplication::UnicodeUTF8));
        lbLecT->setText(QApplication::translate("Widget", "LECTURAS DE\n"
" ANALIZADORES", 0, QApplication::UnicodeUTF8));
        lbUnidT->setText(QApplication::translate("Widget", "UNIDADES", 0, QApplication::UnicodeUTF8));
        lbCemsT->setText(QApplication::translate("Widget", "CEMS", 0, QApplication::UnicodeUTF8));
        lbLectNoxT->setText(QApplication::translate("Widget", "LECTURA DEL ANALIZADOR DE NOX", 0, QApplication::UnicodeUTF8));
        lbCemsNoxT->setText(QApplication::translate("Widget", "CEMS_EO_NOX_PPM", 0, QApplication::UnicodeUTF8));
        lbNox->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_NOX_PPM_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lBNoxU->setText(QApplication::translate("Widget", "ppm", 0, QApplication::UnicodeUTF8));
        lbNox_4->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_NOX_CORR_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_4->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_5->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_NOX_LBS_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_5->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_6->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_NOX_LBMM_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_6->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbCoU->setText(QApplication::translate("Widget", "ppm", 0, QApplication::UnicodeUTF8));
        lbNox_2->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_CO_PPM_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_2->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbCemsCoT->setText(QApplication::translate("Widget", "CEMS_EO_CO_PPM", 0, QApplication::UnicodeUTF8));
        lbLectCoT->setText(QApplication::translate("Widget", "LECTURA DEL ANALIZADOR DE CO", 0, QApplication::UnicodeUTF8));
        lbNox_9->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_CO_LBMM_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_9->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_8->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_CO_LBS_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_8->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_7->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_CO_CORR_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_7->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbO2U->setText(QApplication::translate("Widget", "ppm", 0, QApplication::UnicodeUTF8));
        lbNox_3->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_O2_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_3->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbCemsO2T->setText(QApplication::translate("Widget", "CEMS_EO_O2", 0, QApplication::UnicodeUTF8));
        lbNox_12->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_HHV_GAS_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_12->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_11->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_FUEL_FD_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_11->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_10->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_EO_HEAT_INPUT_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_10->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_15->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_ERO_INCAL_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_15->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_14->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_ERO_CEM_TROUBLE_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_14->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_13->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_ERO_CEM_MAINT_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_13->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbNox_16->setId(QApplication::translate("Widget", "p_Fix32_NODE_CEMS_ERO_CAL_FAIL_F_CV", 0, QApplication::UnicodeUTF8));
        lbNox_16->setText(QApplication::translate("Widget", "????", 0, QApplication::UnicodeUTF8));
        lbCemsEroMantT->setText(QApplication::translate("Widget", "CEMS_ERO_CEM_MAINT", 0, QApplication::UnicodeUTF8));
        lbCemsMantT->setText(QApplication::translate("Widget", "CEMS EN MODO DE MANTENIMIENTO", 0, QApplication::UnicodeUTF8));
        lbCemsEroTroubleT->setText(QApplication::translate("Widget", "CEMS_ERO_CEM_TROUBLE", 0, QApplication::UnicodeUTF8));
        lbAlarmCemsT->setText(QApplication::translate("Widget", "ALARMA GENERAL DEL CEMS", 0, QApplication::UnicodeUTF8));
        lbFallasCalibT->setText(QApplication::translate("Widget", "FALLA EN CALIBRACION", 0, QApplication::UnicodeUTF8));
        lbCemsCalibT->setText(QApplication::translate("Widget", "CEMS EN MODO DE CALIBRACION", 0, QApplication::UnicodeUTF8));
        lbCemsEroCalT->setText(QApplication::translate("Widget", "CEMS_ERO_CAL_FAIL", 0, QApplication::UnicodeUTF8));
        lbCemsEroIncalT->setText(QApplication::translate("Widget", "CEMS_ERO_INCAL", 0, QApplication::UnicodeUTF8));
        lbLectO2T->setText(QApplication::translate("Widget", "LECTURA DEL ANALIZADOR DE O2", 0, QApplication::UnicodeUTF8));
        btTurbinaMant->setText(QApplication::translate("Widget", "TURBINA EN\n"
" MANTENIMIENTO", 0, QApplication::UnicodeUTF8));
        btResetCems->setText(QApplication::translate("Widget", "RESET CEMS\n"
" COMMS ", 0, QApplication::UnicodeUTF8));
        btImpPant->setText(QApplication::translate("Widget", "IMP PANT", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Widget: public Ui_Widget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WIDGET_H
