/********************************************************************************
** Form generated from reading UI file 'd7.ui'
**
** Created: Thu 19. Dec 17:48:56 2013
**      by: Qt User Interface Compiler version 4.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_D7_H
#define UI_D7_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "wlabel.h"

QT_BEGIN_NAMESPACE

class Ui_D7
{
public:
    QFrame *Temperaturas_2;
    QFrame *frame_8;
    WLabel *label_12;
    WLabel *lb_Vib_Unit_DE_X;
    WLabel *lb_Vib_Lect_DE_X;
    WLabel *Descr_45;
    WLabel *lb_Vib_Unit_NDE_X;
    WLabel *Descr_47;
    WLabel *lb_Vib_Lect_NDE_X;
    WLabel *lb_Vib_Unit_DE_Y;
    WLabel *lb_Vib_Lect_DE_Y;
    WLabel *Descr_46;
    WLabel *lb_Vib_Unit_NDE_Y;
    WLabel *lb_Vib_Lect_NDE_Y;
    WLabel *Descr_48;
    QFrame *Temperaturas_3;
    QFrame *frame_9;
    WLabel *label_13;
    WLabel *lb_Pot_Unit_PAG;
    WLabel *lb_Pot_Lect_PAG;
    WLabel *Descr_49;
    WLabel *lb_Pot_Unit_EIG;
    WLabel *lb_Pot_Lect_EIG;
    WLabel *Descr_50;
    QFrame *Modo;
    QFrame *frame_10;
    WLabel *label_14;
    WLabel *lb_Modo_Unit_DI;
    WLabel *lb_Modo_Lect_DI;
    WLabel *Descr_33;
    QFrame *Temperaturas_4;
    QFrame *frame_7;
    WLabel *label_11;
    WLabel *lb_DMMF_Unit_FGen;
    WLabel *lb_DMMF_Lect_FGen;
    WLabel *Descr_26;
    WLabel *lb_DMMF_Unit_AVT;
    WLabel *lb_DMMF_Lect_AVT;
    WLabel *Descr_25;
    WLabel *lb_DMMF_Lect_CFB;
    WLabel *Descr_23;
    WLabel *lb_DMMF_Unit_CFB;
    WLabel *Descr_22;
    WLabel *lb_DMMF_Lect_CFA;
    WLabel *lb_DMMF_Unit_CFA;
    WLabel *Descr_24;
    WLabel *lb_DMMF_Unit_CFC;
    WLabel *lb_DMMF_Lect_CFC;
    WLabel *lb_DMMF_Unit_FPGen;
    WLabel *lb_DMMF_Lect_FPGen;
    WLabel *Descr_27;
    WLabel *Descr_16;
    WLabel *lb_DMMF_Lect_VBus;
    WLabel *lb_DMMF_Unit_VBus;
    WLabel *lb_DMMF_Unit_VFAB;
    WLabel *Descr_18;
    WLabel *lb_DMMF_Lect_VFAB;
    WLabel *lb_DMMF_Lect_TMVAR;
    WLabel *Descr_21;
    WLabel *lb_DMMF_Unit_TMVAR;
    WLabel *lb_DMMF_Unit_VFBC;
    WLabel *Descr_19;
    WLabel *lb_DMMF_Lect_VFBC;
    WLabel *Descr_20;
    WLabel *lb_DMMF_Unit_VFAC;
    WLabel *lb_DMMF_Lect_VFAC;
    WLabel *Descr_17;
    WLabel *lb_DMMF_Lect_FBus;
    WLabel *lb_DMMF_Unit_FBus;
    QFrame *Temperaturas_5;
    QFrame *frame_11;
    WLabel *label_15;
    WLabel *lb_LS_Unit_VBus;
    WLabel *lb_LS_Lect_VBus;
    WLabel *Descr_30;
    WLabel *lb_LS_Unit_VCE;
    WLabel *lb_LS_Lect_VCE;
    WLabel *Descr_28;
    WLabel *lb_LS_Unit_VG;
    WLabel *lb_LS_Lect_VG;
    WLabel *Descr_31;
    WLabel *lb_LS_Unit_ACE;
    WLabel *lb_LS_Lect_ACE;
    WLabel *Descr_29;
    WLabel *lb_LS_Unit_FBus;
    WLabel *lb_LS_Lect_FBus;
    WLabel *Descr_43;
    QFrame *Temperaturas_6;
    QFrame *frame_12;
    WLabel *label_16;
    WLabel *lb_EM_Unit_VCBG;
    WLabel *lb_EM_Lect_VCBG;
    WLabel *Descr_34;
    WLabel *lb_EM_Unit_BALACG;
    WLabel *lb_EM_Lect_BALACG;
    WLabel *Descr_35;
    WLabel *lb_EM_Unit_BAEG;
    WLabel *lb_EM_Lect_BAEG;
    WLabel *Descr_36;
    WLabel *lb_EM_Unit_VCAG;
    WLabel *lb_EM_Lect_VCAG;
    WLabel *Descr_32;
    WLabel *lb_EM_Unit_VCBG_2;
    WLabel *lb_EM_Lect_VCBG_2;
    QFrame *Temperaturas_7;
    QFrame *frame_13;
    WLabel *label_17;
    WLabel *lb_LG_Unit_NTALG;
    WLabel *lb_LG_Lect_NTALG;
    WLabel *Descr_42;
    WLabel *lb_LG_Unit_PSLDGA;
    WLabel *Descr_38;
    WLabel *lb_LG_Lect_PSLDGA;
    WLabel *lb_LG_Unit_PSLDGB;
    WLabel *lb_LG_Lect_PSLDGB;
    WLabel *Descr_39;
    WLabel *lb_LG_Unit_EBAAP;
    WLabel *lb_LG_Lect_EBAAP;
    WLabel *Descr_41;
    WLabel *Descr_37;
    WLabel *lb_LG_Unit_PSALG;
    WLabel *lb_LG_Lect_PSALG;
    WLabel *lb_LG_Unit_PSLDG;
    WLabel *lb_LG_Lect_PSLDG;
    WLabel *Descr_40;
    QFrame *Temperaturas;
    QFrame *frame_6;
    WLabel *label_10;
    WLabel *Descr_01;
    WLabel *lb_Temp_Lect_FaseU1;
    WLabel *lb_Temp_Unit_FaseU1;
    WLabel *lb_Temp_Unit_FaseU2;
    WLabel *Descr_2;
    WLabel *lb_Temp_Lect_FaseU2;
    WLabel *lb_Temp_Lect_TCIIB;
    WLabel *lb_Temp_Unit_TCIIB;
    WLabel *Descr_12;
    WLabel *Descr_9;
    WLabel *lb_Temp_Lect_TCGDE;
    WLabel *lb_Temp_Unit_TCGDE;
    WLabel *lb_Temp_Lect_FaseW1;
    WLabel *lb_Temp_Unit_FaseW1;
    WLabel *Descr_5;
    WLabel *lb_Temp_Unit_FaseV1;
    WLabel *Descr_3;
    WLabel *lb_Temp_Lect_FaseV1;
    WLabel *Descr_6;
    WLabel *lb_Temp_Unit_FaseW2;
    WLabel *lb_Temp_Lect_FaseW2;
    WLabel *Descr_7;
    WLabel *lb_Temp_Lect_TPEG;
    WLabel *lb_Temp_Unit_TPEG;
    WLabel *lb_Temp_Lect_FaseV2;
    WLabel *lb_Temp_Unit_FaseV2;
    WLabel *Descr_4;
    WLabel *lb_Temp_Unit_TCIOB;
    WLabel *lb_Temp_Lect_TCIOB;
    WLabel *Descr_11;
    WLabel *lb_Temp_Unit_TSALG;
    WLabel *lb_Temp_Lect_TSALG;
    WLabel *Descr_8;
    WLabel *Descr_10;
    WLabel *lb_Temp_Lect_TCGNDE;
    WLabel *lb_Temp_Unit_TCGNDE;
    WLabel *lb_Temp_Lect_TACG;
    WLabel *Descr_13;
    WLabel *lb_Temp_Unit_TACG;
    WLabel *lb_Temp_Lect_TEAEG;
    WLabel *Descr_15;
    WLabel *lb_Temp_Unit_TEAEG;
    WLabel *Descr_14;
    WLabel *lb_Temp_Unit_TSAG;
    WLabel *lb_Temp_Lect_TSAG;
    WLabel *lbUnit3;
    QPushButton *btnIMPPant;

    void setupUi(QWidget *D7)
    {
        if (D7->objectName().isEmpty())
            D7->setObjectName(QString::fromUtf8("D7"));
        D7->resize(1024, 662);
        D7->setMinimumSize(QSize(1024, 662));
        D7->setMaximumSize(QSize(1024, 662));
        D7->setStyleSheet(QString::fromUtf8("background-color: rgb(154, 154, 154);\n"
""));
        Temperaturas_2 = new QFrame(D7);
        Temperaturas_2->setObjectName(QString::fromUtf8("Temperaturas_2"));
        Temperaturas_2->setGeometry(QRect(5, 377, 340, 120));
        Temperaturas_2->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_2->setFrameShape(QFrame::Box);
        Temperaturas_2->setFrameShadow(QFrame::Sunken);
        frame_8 = new QFrame(Temperaturas_2);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(1, 1, 338, 20));
        frame_8->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_8->setFrameShape(QFrame::WinPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        frame_8->setLineWidth(2);
        label_12 = new WLabel(frame_8);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(1, 1, 334, 16));
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        label_12->setFont(font);
        label_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Vib_Unit_DE_X = new WLabel(Temperaturas_2);
        lb_Vib_Unit_DE_X->setObjectName(QString::fromUtf8("lb_Vib_Unit_DE_X"));
        lb_Vib_Unit_DE_X->setGeometry(QRect(291, 30, 40, 18));
        lb_Vib_Unit_DE_X->setLayoutDirection(Qt::LeftToRight);
        QFont font1;
        font1.setPointSize(9);
        lb_Vib_Unit_DE_X->setFont(font1);
        lb_Vib_Unit_DE_X->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Vib_Lect_DE_X = new WLabel(Temperaturas_2);
        lb_Vib_Lect_DE_X->setObjectName(QString::fromUtf8("lb_Vib_Lect_DE_X"));
        lb_Vib_Lect_DE_X->setGeometry(QRect(235, 30, 50, 18));
        lb_Vib_Lect_DE_X->setMinimumSize(QSize(50, 18));
        lb_Vib_Lect_DE_X->setMaximumSize(QSize(50, 18));
        lb_Vib_Lect_DE_X->setLayoutDirection(Qt::LeftToRight);
        QFont font2;
        font2.setPointSize(8);
        lb_Vib_Lect_DE_X->setFont(font2);
        lb_Vib_Lect_DE_X->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_45 = new WLabel(Temperaturas_2);
        Descr_45->setObjectName(QString::fromUtf8("Descr_45"));
        Descr_45->setGeometry(QRect(25, 30, 200, 18));
        Descr_45->setLayoutDirection(Qt::LeftToRight);
        Descr_45->setFont(font2);
        Descr_45->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Vib_Unit_NDE_X = new WLabel(Temperaturas_2);
        lb_Vib_Unit_NDE_X->setObjectName(QString::fromUtf8("lb_Vib_Unit_NDE_X"));
        lb_Vib_Unit_NDE_X->setGeometry(QRect(291, 60, 40, 18));
        lb_Vib_Unit_NDE_X->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Unit_NDE_X->setFont(font1);
        lb_Vib_Unit_NDE_X->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_47 = new WLabel(Temperaturas_2);
        Descr_47->setObjectName(QString::fromUtf8("Descr_47"));
        Descr_47->setGeometry(QRect(25, 60, 200, 18));
        Descr_47->setLayoutDirection(Qt::LeftToRight);
        Descr_47->setFont(font2);
        Descr_47->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Vib_Lect_NDE_X = new WLabel(Temperaturas_2);
        lb_Vib_Lect_NDE_X->setObjectName(QString::fromUtf8("lb_Vib_Lect_NDE_X"));
        lb_Vib_Lect_NDE_X->setGeometry(QRect(235, 60, 50, 18));
        lb_Vib_Lect_NDE_X->setMinimumSize(QSize(50, 18));
        lb_Vib_Lect_NDE_X->setMaximumSize(QSize(50, 18));
        lb_Vib_Lect_NDE_X->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Lect_NDE_X->setFont(font2);
        lb_Vib_Lect_NDE_X->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_Vib_Unit_DE_Y = new WLabel(Temperaturas_2);
        lb_Vib_Unit_DE_Y->setObjectName(QString::fromUtf8("lb_Vib_Unit_DE_Y"));
        lb_Vib_Unit_DE_Y->setGeometry(QRect(291, 45, 40, 18));
        lb_Vib_Unit_DE_Y->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Unit_DE_Y->setFont(font1);
        lb_Vib_Unit_DE_Y->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Vib_Lect_DE_Y = new WLabel(Temperaturas_2);
        lb_Vib_Lect_DE_Y->setObjectName(QString::fromUtf8("lb_Vib_Lect_DE_Y"));
        lb_Vib_Lect_DE_Y->setGeometry(QRect(235, 45, 50, 18));
        lb_Vib_Lect_DE_Y->setMinimumSize(QSize(50, 18));
        lb_Vib_Lect_DE_Y->setMaximumSize(QSize(50, 18));
        lb_Vib_Lect_DE_Y->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Lect_DE_Y->setFont(font2);
        lb_Vib_Lect_DE_Y->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_46 = new WLabel(Temperaturas_2);
        Descr_46->setObjectName(QString::fromUtf8("Descr_46"));
        Descr_46->setGeometry(QRect(25, 45, 200, 18));
        Descr_46->setLayoutDirection(Qt::LeftToRight);
        Descr_46->setFont(font2);
        Descr_46->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Vib_Unit_NDE_Y = new WLabel(Temperaturas_2);
        lb_Vib_Unit_NDE_Y->setObjectName(QString::fromUtf8("lb_Vib_Unit_NDE_Y"));
        lb_Vib_Unit_NDE_Y->setGeometry(QRect(291, 75, 40, 18));
        lb_Vib_Unit_NDE_Y->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Unit_NDE_Y->setFont(font1);
        lb_Vib_Unit_NDE_Y->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Vib_Lect_NDE_Y = new WLabel(Temperaturas_2);
        lb_Vib_Lect_NDE_Y->setObjectName(QString::fromUtf8("lb_Vib_Lect_NDE_Y"));
        lb_Vib_Lect_NDE_Y->setGeometry(QRect(235, 75, 50, 18));
        lb_Vib_Lect_NDE_Y->setMinimumSize(QSize(50, 18));
        lb_Vib_Lect_NDE_Y->setMaximumSize(QSize(50, 18));
        lb_Vib_Lect_NDE_Y->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Lect_NDE_Y->setFont(font2);
        lb_Vib_Lect_NDE_Y->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_48 = new WLabel(Temperaturas_2);
        Descr_48->setObjectName(QString::fromUtf8("Descr_48"));
        Descr_48->setGeometry(QRect(25, 75, 200, 18));
        Descr_48->setLayoutDirection(Qt::LeftToRight);
        Descr_48->setFont(font2);
        Descr_48->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Temperaturas_3 = new QFrame(D7);
        Temperaturas_3->setObjectName(QString::fromUtf8("Temperaturas_3"));
        Temperaturas_3->setGeometry(QRect(5, 496, 340, 66));
        Temperaturas_3->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_3->setFrameShape(QFrame::Box);
        Temperaturas_3->setFrameShadow(QFrame::Sunken);
        frame_9 = new QFrame(Temperaturas_3);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(1, 1, 340, 20));
        frame_9->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_9->setFrameShape(QFrame::WinPanel);
        frame_9->setFrameShadow(QFrame::Raised);
        frame_9->setLineWidth(2);
        label_13 = new WLabel(frame_9);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(2, 2, 336, 16));
        label_13->setFont(font);
        label_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Pot_Unit_PAG = new WLabel(Temperaturas_3);
        lb_Pot_Unit_PAG->setObjectName(QString::fromUtf8("lb_Pot_Unit_PAG"));
        lb_Pot_Unit_PAG->setGeometry(QRect(291, 30, 40, 18));
        lb_Pot_Unit_PAG->setLayoutDirection(Qt::LeftToRight);
        lb_Pot_Unit_PAG->setFont(font1);
        lb_Pot_Unit_PAG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Pot_Lect_PAG = new WLabel(Temperaturas_3);
        lb_Pot_Lect_PAG->setObjectName(QString::fromUtf8("lb_Pot_Lect_PAG"));
        lb_Pot_Lect_PAG->setGeometry(QRect(235, 30, 50, 18));
        lb_Pot_Lect_PAG->setMinimumSize(QSize(50, 18));
        lb_Pot_Lect_PAG->setMaximumSize(QSize(50, 18));
        lb_Pot_Lect_PAG->setLayoutDirection(Qt::LeftToRight);
        lb_Pot_Lect_PAG->setFont(font2);
        lb_Pot_Lect_PAG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_49 = new WLabel(Temperaturas_3);
        Descr_49->setObjectName(QString::fromUtf8("Descr_49"));
        Descr_49->setGeometry(QRect(25, 30, 200, 18));
        Descr_49->setLayoutDirection(Qt::LeftToRight);
        Descr_49->setFont(font2);
        Descr_49->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Pot_Unit_EIG = new WLabel(Temperaturas_3);
        lb_Pot_Unit_EIG->setObjectName(QString::fromUtf8("lb_Pot_Unit_EIG"));
        lb_Pot_Unit_EIG->setGeometry(QRect(291, 45, 40, 18));
        lb_Pot_Unit_EIG->setLayoutDirection(Qt::LeftToRight);
        lb_Pot_Unit_EIG->setFont(font1);
        lb_Pot_Unit_EIG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Pot_Lect_EIG = new WLabel(Temperaturas_3);
        lb_Pot_Lect_EIG->setObjectName(QString::fromUtf8("lb_Pot_Lect_EIG"));
        lb_Pot_Lect_EIG->setGeometry(QRect(235, 45, 50, 18));
        lb_Pot_Lect_EIG->setMinimumSize(QSize(50, 18));
        lb_Pot_Lect_EIG->setMaximumSize(QSize(50, 18));
        lb_Pot_Lect_EIG->setLayoutDirection(Qt::LeftToRight);
        lb_Pot_Lect_EIG->setFont(font2);
        lb_Pot_Lect_EIG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_50 = new WLabel(Temperaturas_3);
        Descr_50->setObjectName(QString::fromUtf8("Descr_50"));
        Descr_50->setGeometry(QRect(25, 45, 200, 18));
        Descr_50->setLayoutDirection(Qt::LeftToRight);
        Descr_50->setFont(font2);
        Descr_50->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Modo = new QFrame(D7);
        Modo->setObjectName(QString::fromUtf8("Modo"));
        Modo->setGeometry(QRect(5, 561, 342, 94));
        Modo->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Modo->setFrameShape(QFrame::Box);
        Modo->setFrameShadow(QFrame::Sunken);
        frame_10 = new QFrame(Modo);
        frame_10->setObjectName(QString::fromUtf8("frame_10"));
        frame_10->setGeometry(QRect(1, 1, 340, 20));
        frame_10->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_10->setFrameShape(QFrame::WinPanel);
        frame_10->setFrameShadow(QFrame::Raised);
        frame_10->setLineWidth(2);
        label_14 = new WLabel(frame_10);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(2, 2, 336, 16));
        label_14->setFont(font);
        label_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Modo_Unit_DI = new WLabel(Modo);
        lb_Modo_Unit_DI->setObjectName(QString::fromUtf8("lb_Modo_Unit_DI"));
        lb_Modo_Unit_DI->setGeometry(QRect(297, 41, 40, 18));
        lb_Modo_Unit_DI->setLayoutDirection(Qt::LeftToRight);
        lb_Modo_Unit_DI->setFont(font1);
        lb_Modo_Unit_DI->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Modo_Lect_DI = new WLabel(Modo);
        lb_Modo_Lect_DI->setObjectName(QString::fromUtf8("lb_Modo_Lect_DI"));
        lb_Modo_Lect_DI->setGeometry(QRect(241, 43, 50, 18));
        lb_Modo_Lect_DI->setMinimumSize(QSize(50, 18));
        lb_Modo_Lect_DI->setMaximumSize(QSize(50, 18));
        lb_Modo_Lect_DI->setLayoutDirection(Qt::LeftToRight);
        lb_Modo_Lect_DI->setFont(font2);
        lb_Modo_Lect_DI->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_33 = new WLabel(Modo);
        Descr_33->setObjectName(QString::fromUtf8("Descr_33"));
        Descr_33->setGeometry(QRect(10, 43, 225, 18));
        Descr_33->setMinimumSize(QSize(225, 18));
        Descr_33->setMaximumSize(QSize(225, 18));
        Descr_33->setLayoutDirection(Qt::LeftToRight);
        Descr_33->setFont(font2);
        Descr_33->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Temperaturas_4 = new QFrame(D7);
        Temperaturas_4->setObjectName(QString::fromUtf8("Temperaturas_4"));
        Temperaturas_4->setGeometry(QRect(345, 5, 341, 433));
        Temperaturas_4->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_4->setFrameShape(QFrame::Box);
        Temperaturas_4->setFrameShadow(QFrame::Sunken);
        frame_7 = new QFrame(Temperaturas_4);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(1, 1, 340, 20));
        frame_7->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_7->setFrameShape(QFrame::WinPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        frame_7->setLineWidth(2);
        label_11 = new WLabel(frame_7);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(1, 1, 336, 16));
        label_11->setFont(font);
        label_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Unit_FGen = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_FGen->setObjectName(QString::fromUtf8("lb_DMMF_Unit_FGen"));
        lb_DMMF_Unit_FGen->setGeometry(QRect(291, 310, 40, 18));
        lb_DMMF_Unit_FGen->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_FGen->setFont(font1);
        lb_DMMF_Unit_FGen->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_FGen = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_FGen->setObjectName(QString::fromUtf8("lb_DMMF_Lect_FGen"));
        lb_DMMF_Lect_FGen->setGeometry(QRect(235, 310, 50, 18));
        lb_DMMF_Lect_FGen->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_FGen->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_FGen->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_FGen->setFont(font2);
        lb_DMMF_Lect_FGen->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_26 = new WLabel(Temperaturas_4);
        Descr_26->setObjectName(QString::fromUtf8("Descr_26"));
        Descr_26->setGeometry(QRect(25, 310, 180, 18));
        Descr_26->setLayoutDirection(Qt::LeftToRight);
        Descr_26->setFont(font2);
        Descr_26->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Unit_AVT = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_AVT->setObjectName(QString::fromUtf8("lb_DMMF_Unit_AVT"));
        lb_DMMF_Unit_AVT->setGeometry(QRect(291, 240, 40, 18));
        lb_DMMF_Unit_AVT->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_AVT->setFont(font1);
        lb_DMMF_Unit_AVT->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_AVT = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_AVT->setObjectName(QString::fromUtf8("lb_DMMF_Lect_AVT"));
        lb_DMMF_Lect_AVT->setGeometry(QRect(235, 240, 50, 18));
        lb_DMMF_Lect_AVT->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_AVT->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_AVT->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_AVT->setFont(font2);
        lb_DMMF_Lect_AVT->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_25 = new WLabel(Temperaturas_4);
        Descr_25->setObjectName(QString::fromUtf8("Descr_25"));
        Descr_25->setGeometry(QRect(25, 240, 180, 18));
        Descr_25->setLayoutDirection(Qt::LeftToRight);
        Descr_25->setFont(font2);
        Descr_25->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_CFB = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_CFB->setObjectName(QString::fromUtf8("lb_DMMF_Lect_CFB"));
        lb_DMMF_Lect_CFB->setGeometry(QRect(235, 210, 50, 18));
        lb_DMMF_Lect_CFB->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_CFB->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_CFB->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_CFB->setFont(font2);
        lb_DMMF_Lect_CFB->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_23 = new WLabel(Temperaturas_4);
        Descr_23->setObjectName(QString::fromUtf8("Descr_23"));
        Descr_23->setGeometry(QRect(25, 210, 180, 18));
        Descr_23->setLayoutDirection(Qt::LeftToRight);
        Descr_23->setFont(font2);
        Descr_23->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Unit_CFB = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_CFB->setObjectName(QString::fromUtf8("lb_DMMF_Unit_CFB"));
        lb_DMMF_Unit_CFB->setGeometry(QRect(291, 210, 40, 18));
        lb_DMMF_Unit_CFB->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_CFB->setFont(font1);
        lb_DMMF_Unit_CFB->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_22 = new WLabel(Temperaturas_4);
        Descr_22->setObjectName(QString::fromUtf8("Descr_22"));
        Descr_22->setGeometry(QRect(25, 195, 180, 18));
        Descr_22->setLayoutDirection(Qt::LeftToRight);
        Descr_22->setFont(font2);
        Descr_22->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_CFA = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_CFA->setObjectName(QString::fromUtf8("lb_DMMF_Lect_CFA"));
        lb_DMMF_Lect_CFA->setGeometry(QRect(235, 195, 50, 18));
        lb_DMMF_Lect_CFA->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_CFA->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_CFA->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_CFA->setFont(font2);
        lb_DMMF_Lect_CFA->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_DMMF_Unit_CFA = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_CFA->setObjectName(QString::fromUtf8("lb_DMMF_Unit_CFA"));
        lb_DMMF_Unit_CFA->setGeometry(QRect(291, 195, 40, 18));
        lb_DMMF_Unit_CFA->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_CFA->setFont(font1);
        lb_DMMF_Unit_CFA->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_24 = new WLabel(Temperaturas_4);
        Descr_24->setObjectName(QString::fromUtf8("Descr_24"));
        Descr_24->setGeometry(QRect(25, 225, 180, 18));
        Descr_24->setLayoutDirection(Qt::LeftToRight);
        Descr_24->setFont(font2);
        Descr_24->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Unit_CFC = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_CFC->setObjectName(QString::fromUtf8("lb_DMMF_Unit_CFC"));
        lb_DMMF_Unit_CFC->setGeometry(QRect(291, 225, 40, 18));
        lb_DMMF_Unit_CFC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_CFC->setFont(font1);
        lb_DMMF_Unit_CFC->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_CFC = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_CFC->setObjectName(QString::fromUtf8("lb_DMMF_Lect_CFC"));
        lb_DMMF_Lect_CFC->setGeometry(QRect(235, 225, 50, 18));
        lb_DMMF_Lect_CFC->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_CFC->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_CFC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_CFC->setFont(font2);
        lb_DMMF_Lect_CFC->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_DMMF_Unit_FPGen = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_FPGen->setObjectName(QString::fromUtf8("lb_DMMF_Unit_FPGen"));
        lb_DMMF_Unit_FPGen->setGeometry(QRect(291, 325, 40, 18));
        lb_DMMF_Unit_FPGen->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_FPGen->setFont(font1);
        lb_DMMF_Unit_FPGen->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_FPGen = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_FPGen->setObjectName(QString::fromUtf8("lb_DMMF_Lect_FPGen"));
        lb_DMMF_Lect_FPGen->setGeometry(QRect(235, 325, 50, 18));
        lb_DMMF_Lect_FPGen->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_FPGen->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_FPGen->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_FPGen->setFont(font2);
        lb_DMMF_Lect_FPGen->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_27 = new WLabel(Temperaturas_4);
        Descr_27->setObjectName(QString::fromUtf8("Descr_27"));
        Descr_27->setGeometry(QRect(25, 325, 225, 18));
        Descr_27->setMinimumSize(QSize(225, 18));
        Descr_27->setMaximumSize(QSize(225, 18));
        Descr_27->setLayoutDirection(Qt::LeftToRight);
        Descr_27->setFont(font2);
        Descr_27->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_16 = new WLabel(Temperaturas_4);
        Descr_16->setObjectName(QString::fromUtf8("Descr_16"));
        Descr_16->setGeometry(QRect(25, 30, 180, 18));
        Descr_16->setLayoutDirection(Qt::LeftToRight);
        Descr_16->setFont(font2);
        Descr_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_VBus = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_VBus->setObjectName(QString::fromUtf8("lb_DMMF_Lect_VBus"));
        lb_DMMF_Lect_VBus->setGeometry(QRect(235, 30, 50, 18));
        lb_DMMF_Lect_VBus->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_VBus->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_VBus->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_VBus->setFont(font2);
        lb_DMMF_Lect_VBus->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_DMMF_Unit_VBus = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_VBus->setObjectName(QString::fromUtf8("lb_DMMF_Unit_VBus"));
        lb_DMMF_Unit_VBus->setGeometry(QRect(291, 30, 40, 18));
        lb_DMMF_Unit_VBus->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_VBus->setFont(font1);
        lb_DMMF_Unit_VBus->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Unit_VFAB = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_VFAB->setObjectName(QString::fromUtf8("lb_DMMF_Unit_VFAB"));
        lb_DMMF_Unit_VFAB->setGeometry(QRect(291, 60, 40, 18));
        lb_DMMF_Unit_VFAB->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_VFAB->setFont(font1);
        lb_DMMF_Unit_VFAB->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_18 = new WLabel(Temperaturas_4);
        Descr_18->setObjectName(QString::fromUtf8("Descr_18"));
        Descr_18->setGeometry(QRect(25, 60, 180, 18));
        Descr_18->setLayoutDirection(Qt::LeftToRight);
        Descr_18->setFont(font2);
        Descr_18->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_VFAB = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_VFAB->setObjectName(QString::fromUtf8("lb_DMMF_Lect_VFAB"));
        lb_DMMF_Lect_VFAB->setGeometry(QRect(235, 60, 50, 18));
        lb_DMMF_Lect_VFAB->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_VFAB->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_VFAB->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_VFAB->setFont(font2);
        lb_DMMF_Lect_VFAB->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_DMMF_Lect_TMVAR = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_TMVAR->setObjectName(QString::fromUtf8("lb_DMMF_Lect_TMVAR"));
        lb_DMMF_Lect_TMVAR->setGeometry(QRect(235, 135, 50, 18));
        lb_DMMF_Lect_TMVAR->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_TMVAR->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_TMVAR->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_TMVAR->setFont(font2);
        lb_DMMF_Lect_TMVAR->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_21 = new WLabel(Temperaturas_4);
        Descr_21->setObjectName(QString::fromUtf8("Descr_21"));
        Descr_21->setGeometry(QRect(25, 135, 180, 18));
        Descr_21->setLayoutDirection(Qt::LeftToRight);
        Descr_21->setFont(font2);
        Descr_21->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Unit_TMVAR = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_TMVAR->setObjectName(QString::fromUtf8("lb_DMMF_Unit_TMVAR"));
        lb_DMMF_Unit_TMVAR->setGeometry(QRect(291, 135, 40, 18));
        lb_DMMF_Unit_TMVAR->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_TMVAR->setFont(font1);
        lb_DMMF_Unit_TMVAR->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Unit_VFBC = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_VFBC->setObjectName(QString::fromUtf8("lb_DMMF_Unit_VFBC"));
        lb_DMMF_Unit_VFBC->setGeometry(QRect(291, 75, 40, 18));
        lb_DMMF_Unit_VFBC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_VFBC->setFont(font1);
        lb_DMMF_Unit_VFBC->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_19 = new WLabel(Temperaturas_4);
        Descr_19->setObjectName(QString::fromUtf8("Descr_19"));
        Descr_19->setGeometry(QRect(25, 75, 180, 18));
        Descr_19->setLayoutDirection(Qt::LeftToRight);
        Descr_19->setFont(font2);
        Descr_19->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_VFBC = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_VFBC->setObjectName(QString::fromUtf8("lb_DMMF_Lect_VFBC"));
        lb_DMMF_Lect_VFBC->setGeometry(QRect(235, 75, 50, 18));
        lb_DMMF_Lect_VFBC->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_VFBC->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_VFBC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_VFBC->setFont(font2);
        lb_DMMF_Lect_VFBC->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_20 = new WLabel(Temperaturas_4);
        Descr_20->setObjectName(QString::fromUtf8("Descr_20"));
        Descr_20->setGeometry(QRect(25, 90, 180, 18));
        Descr_20->setLayoutDirection(Qt::LeftToRight);
        Descr_20->setFont(font2);
        Descr_20->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Unit_VFAC = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_VFAC->setObjectName(QString::fromUtf8("lb_DMMF_Unit_VFAC"));
        lb_DMMF_Unit_VFAC->setGeometry(QRect(291, 90, 40, 18));
        lb_DMMF_Unit_VFAC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_VFAC->setFont(font1);
        lb_DMMF_Unit_VFAC->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_VFAC = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_VFAC->setObjectName(QString::fromUtf8("lb_DMMF_Lect_VFAC"));
        lb_DMMF_Lect_VFAC->setGeometry(QRect(235, 90, 50, 18));
        lb_DMMF_Lect_VFAC->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_VFAC->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_VFAC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_VFAC->setFont(font2);
        lb_DMMF_Lect_VFAC->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_17 = new WLabel(Temperaturas_4);
        Descr_17->setObjectName(QString::fromUtf8("Descr_17"));
        Descr_17->setGeometry(QRect(25, 45, 180, 18));
        Descr_17->setLayoutDirection(Qt::LeftToRight);
        Descr_17->setFont(font2);
        Descr_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_DMMF_Lect_FBus = new WLabel(Temperaturas_4);
        lb_DMMF_Lect_FBus->setObjectName(QString::fromUtf8("lb_DMMF_Lect_FBus"));
        lb_DMMF_Lect_FBus->setGeometry(QRect(235, 45, 50, 18));
        lb_DMMF_Lect_FBus->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_FBus->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_FBus->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_FBus->setFont(font2);
        lb_DMMF_Lect_FBus->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_DMMF_Unit_FBus = new WLabel(Temperaturas_4);
        lb_DMMF_Unit_FBus->setObjectName(QString::fromUtf8("lb_DMMF_Unit_FBus"));
        lb_DMMF_Unit_FBus->setGeometry(QRect(291, 45, 40, 18));
        lb_DMMF_Unit_FBus->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_FBus->setFont(font1);
        lb_DMMF_Unit_FBus->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Temperaturas_5 = new QFrame(D7);
        Temperaturas_5->setObjectName(QString::fromUtf8("Temperaturas_5"));
        Temperaturas_5->setGeometry(QRect(345, 438, 340, 217));
        Temperaturas_5->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_5->setFrameShape(QFrame::Box);
        Temperaturas_5->setFrameShadow(QFrame::Sunken);
        frame_11 = new QFrame(Temperaturas_5);
        frame_11->setObjectName(QString::fromUtf8("frame_11"));
        frame_11->setGeometry(QRect(1, 1, 340, 20));
        frame_11->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_11->setFrameShape(QFrame::WinPanel);
        frame_11->setFrameShadow(QFrame::Raised);
        frame_11->setLineWidth(2);
        label_15 = new WLabel(frame_11);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(1, 1, 336, 16));
        label_15->setFont(font);
        label_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Unit_VBus = new WLabel(Temperaturas_5);
        lb_LS_Unit_VBus->setObjectName(QString::fromUtf8("lb_LS_Unit_VBus"));
        lb_LS_Unit_VBus->setGeometry(QRect(291, 60, 40, 18));
        lb_LS_Unit_VBus->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_VBus->setFont(font1);
        lb_LS_Unit_VBus->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Lect_VBus = new WLabel(Temperaturas_5);
        lb_LS_Lect_VBus->setObjectName(QString::fromUtf8("lb_LS_Lect_VBus"));
        lb_LS_Lect_VBus->setGeometry(QRect(235, 60, 50, 18));
        lb_LS_Lect_VBus->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_VBus->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_VBus->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_VBus->setFont(font2);
        lb_LS_Lect_VBus->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_30 = new WLabel(Temperaturas_5);
        Descr_30->setObjectName(QString::fromUtf8("Descr_30"));
        Descr_30->setGeometry(QRect(25, 60, 180, 18));
        Descr_30->setLayoutDirection(Qt::LeftToRight);
        Descr_30->setFont(font2);
        Descr_30->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Unit_VCE = new WLabel(Temperaturas_5);
        lb_LS_Unit_VCE->setObjectName(QString::fromUtf8("lb_LS_Unit_VCE"));
        lb_LS_Unit_VCE->setGeometry(QRect(291, 30, 40, 18));
        lb_LS_Unit_VCE->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_VCE->setFont(font1);
        lb_LS_Unit_VCE->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Lect_VCE = new WLabel(Temperaturas_5);
        lb_LS_Lect_VCE->setObjectName(QString::fromUtf8("lb_LS_Lect_VCE"));
        lb_LS_Lect_VCE->setGeometry(QRect(235, 30, 50, 18));
        lb_LS_Lect_VCE->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_VCE->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_VCE->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_VCE->setFont(font2);
        lb_LS_Lect_VCE->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_28 = new WLabel(Temperaturas_5);
        Descr_28->setObjectName(QString::fromUtf8("Descr_28"));
        Descr_28->setGeometry(QRect(25, 30, 180, 18));
        Descr_28->setLayoutDirection(Qt::LeftToRight);
        Descr_28->setFont(font2);
        Descr_28->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Unit_VG = new WLabel(Temperaturas_5);
        lb_LS_Unit_VG->setObjectName(QString::fromUtf8("lb_LS_Unit_VG"));
        lb_LS_Unit_VG->setGeometry(QRect(291, 160, 40, 18));
        lb_LS_Unit_VG->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_VG->setFont(font1);
        lb_LS_Unit_VG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Lect_VG = new WLabel(Temperaturas_5);
        lb_LS_Lect_VG->setObjectName(QString::fromUtf8("lb_LS_Lect_VG"));
        lb_LS_Lect_VG->setGeometry(QRect(235, 162, 50, 18));
        lb_LS_Lect_VG->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_VG->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_VG->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_VG->setFont(font2);
        lb_LS_Lect_VG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_31 = new WLabel(Temperaturas_5);
        Descr_31->setObjectName(QString::fromUtf8("Descr_31"));
        Descr_31->setGeometry(QRect(25, 162, 180, 18));
        Descr_31->setLayoutDirection(Qt::LeftToRight);
        Descr_31->setFont(font2);
        Descr_31->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Unit_ACE = new WLabel(Temperaturas_5);
        lb_LS_Unit_ACE->setObjectName(QString::fromUtf8("lb_LS_Unit_ACE"));
        lb_LS_Unit_ACE->setGeometry(QRect(291, 45, 40, 18));
        lb_LS_Unit_ACE->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_ACE->setFont(font1);
        lb_LS_Unit_ACE->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Lect_ACE = new WLabel(Temperaturas_5);
        lb_LS_Lect_ACE->setObjectName(QString::fromUtf8("lb_LS_Lect_ACE"));
        lb_LS_Lect_ACE->setGeometry(QRect(235, 45, 50, 18));
        lb_LS_Lect_ACE->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_ACE->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_ACE->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_ACE->setFont(font2);
        lb_LS_Lect_ACE->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_29 = new WLabel(Temperaturas_5);
        Descr_29->setObjectName(QString::fromUtf8("Descr_29"));
        Descr_29->setGeometry(QRect(25, 45, 180, 18));
        Descr_29->setLayoutDirection(Qt::LeftToRight);
        Descr_29->setFont(font2);
        Descr_29->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Unit_FBus = new WLabel(Temperaturas_5);
        lb_LS_Unit_FBus->setObjectName(QString::fromUtf8("lb_LS_Unit_FBus"));
        lb_LS_Unit_FBus->setGeometry(QRect(290, 75, 40, 18));
        lb_LS_Unit_FBus->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_FBus->setFont(font1);
        lb_LS_Unit_FBus->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LS_Lect_FBus = new WLabel(Temperaturas_5);
        lb_LS_Lect_FBus->setObjectName(QString::fromUtf8("lb_LS_Lect_FBus"));
        lb_LS_Lect_FBus->setGeometry(QRect(234, 75, 50, 18));
        lb_LS_Lect_FBus->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_FBus->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_FBus->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_FBus->setFont(font2);
        lb_LS_Lect_FBus->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_43 = new WLabel(Temperaturas_5);
        Descr_43->setObjectName(QString::fromUtf8("Descr_43"));
        Descr_43->setGeometry(QRect(24, 75, 180, 18));
        Descr_43->setLayoutDirection(Qt::LeftToRight);
        Descr_43->setFont(font2);
        Descr_43->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Temperaturas_6 = new QFrame(D7);
        Temperaturas_6->setObjectName(QString::fromUtf8("Temperaturas_6"));
        Temperaturas_6->setGeometry(QRect(686, 5, 335, 151));
        Temperaturas_6->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_6->setFrameShape(QFrame::Box);
        Temperaturas_6->setFrameShadow(QFrame::Sunken);
        frame_12 = new QFrame(Temperaturas_6);
        frame_12->setObjectName(QString::fromUtf8("frame_12"));
        frame_12->setEnabled(true);
        frame_12->setGeometry(QRect(1, 1, 340, 20));
        frame_12->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_12->setFrameShape(QFrame::WinPanel);
        frame_12->setFrameShadow(QFrame::Raised);
        frame_12->setLineWidth(2);
        label_16 = new WLabel(frame_12);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setEnabled(true);
        label_16->setGeometry(QRect(2, 2, 334, 16));
        label_16->setFont(font);
        label_16->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Unit_VCBG = new WLabel(Temperaturas_6);
        lb_EM_Unit_VCBG->setObjectName(QString::fromUtf8("lb_EM_Unit_VCBG"));
        lb_EM_Unit_VCBG->setGeometry(QRect(290, 45, 40, 14));
        lb_EM_Unit_VCBG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_VCBG->setFont(font1);
        lb_EM_Unit_VCBG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Lect_VCBG = new WLabel(Temperaturas_6);
        lb_EM_Lect_VCBG->setObjectName(QString::fromUtf8("lb_EM_Lect_VCBG"));
        lb_EM_Lect_VCBG->setGeometry(QRect(236, 45, 50, 14));
        lb_EM_Lect_VCBG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_VCBG->setFont(font2);
        lb_EM_Lect_VCBG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_34 = new WLabel(Temperaturas_6);
        Descr_34->setObjectName(QString::fromUtf8("Descr_34"));
        Descr_34->setGeometry(QRect(25, 45, 200, 18));
        Descr_34->setLayoutDirection(Qt::LeftToRight);
        Descr_34->setFont(font2);
        Descr_34->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Unit_BALACG = new WLabel(Temperaturas_6);
        lb_EM_Unit_BALACG->setObjectName(QString::fromUtf8("lb_EM_Unit_BALACG"));
        lb_EM_Unit_BALACG->setGeometry(QRect(290, 90, 40, 14));
        lb_EM_Unit_BALACG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_BALACG->setFont(font1);
        lb_EM_Unit_BALACG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Lect_BALACG = new WLabel(Temperaturas_6);
        lb_EM_Lect_BALACG->setObjectName(QString::fromUtf8("lb_EM_Lect_BALACG"));
        lb_EM_Lect_BALACG->setGeometry(QRect(236, 92, 50, 14));
        lb_EM_Lect_BALACG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_BALACG->setFont(font2);
        lb_EM_Lect_BALACG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_35 = new WLabel(Temperaturas_6);
        Descr_35->setObjectName(QString::fromUtf8("Descr_35"));
        Descr_35->setGeometry(QRect(25, 80, 200, 18));
        Descr_35->setLayoutDirection(Qt::LeftToRight);
        Descr_35->setFont(font2);
        Descr_35->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Unit_BAEG = new WLabel(Temperaturas_6);
        lb_EM_Unit_BAEG->setObjectName(QString::fromUtf8("lb_EM_Unit_BAEG"));
        lb_EM_Unit_BAEG->setGeometry(QRect(290, 120, 40, 14));
        lb_EM_Unit_BAEG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_BAEG->setFont(font1);
        lb_EM_Unit_BAEG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Lect_BAEG = new WLabel(Temperaturas_6);
        lb_EM_Lect_BAEG->setObjectName(QString::fromUtf8("lb_EM_Lect_BAEG"));
        lb_EM_Lect_BAEG->setGeometry(QRect(236, 122, 50, 14));
        lb_EM_Lect_BAEG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_BAEG->setFont(font2);
        lb_EM_Lect_BAEG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_36 = new WLabel(Temperaturas_6);
        Descr_36->setObjectName(QString::fromUtf8("Descr_36"));
        Descr_36->setGeometry(QRect(25, 122, 200, 18));
        Descr_36->setLayoutDirection(Qt::LeftToRight);
        Descr_36->setFont(font2);
        Descr_36->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Unit_VCAG = new WLabel(Temperaturas_6);
        lb_EM_Unit_VCAG->setObjectName(QString::fromUtf8("lb_EM_Unit_VCAG"));
        lb_EM_Unit_VCAG->setGeometry(QRect(290, 30, 40, 14));
        lb_EM_Unit_VCAG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_VCAG->setFont(font1);
        lb_EM_Unit_VCAG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Lect_VCAG = new WLabel(Temperaturas_6);
        lb_EM_Lect_VCAG->setObjectName(QString::fromUtf8("lb_EM_Lect_VCAG"));
        lb_EM_Lect_VCAG->setGeometry(QRect(236, 30, 50, 14));
        lb_EM_Lect_VCAG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_VCAG->setFont(font2);
        lb_EM_Lect_VCAG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_32 = new WLabel(Temperaturas_6);
        Descr_32->setObjectName(QString::fromUtf8("Descr_32"));
        Descr_32->setGeometry(QRect(25, 30, 200, 18));
        Descr_32->setLayoutDirection(Qt::LeftToRight);
        Descr_32->setFont(font2);
        Descr_32->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Unit_VCBG_2 = new WLabel(Temperaturas_6);
        lb_EM_Unit_VCBG_2->setObjectName(QString::fromUtf8("lb_EM_Unit_VCBG_2"));
        lb_EM_Unit_VCBG_2->setGeometry(QRect(290, 80, 40, 14));
        lb_EM_Unit_VCBG_2->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_VCBG_2->setFont(font1);
        lb_EM_Unit_VCBG_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_EM_Lect_VCBG_2 = new WLabel(Temperaturas_6);
        lb_EM_Lect_VCBG_2->setObjectName(QString::fromUtf8("lb_EM_Lect_VCBG_2"));
        lb_EM_Lect_VCBG_2->setGeometry(QRect(236, 80, 50, 14));
        lb_EM_Lect_VCBG_2->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_VCBG_2->setFont(font2);
        lb_EM_Lect_VCBG_2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Temperaturas_7 = new QFrame(D7);
        Temperaturas_7->setObjectName(QString::fromUtf8("Temperaturas_7"));
        Temperaturas_7->setGeometry(QRect(685, 156, 335, 499));
        Temperaturas_7->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_7->setFrameShape(QFrame::Box);
        Temperaturas_7->setFrameShadow(QFrame::Sunken);
        frame_13 = new QFrame(Temperaturas_7);
        frame_13->setObjectName(QString::fromUtf8("frame_13"));
        frame_13->setGeometry(QRect(3, 3, 340, 20));
        frame_13->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_13->setFrameShape(QFrame::WinPanel);
        frame_13->setFrameShadow(QFrame::Raised);
        frame_13->setLineWidth(2);
        label_17 = new WLabel(frame_13);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(1, 1, 334, 16));
        label_17->setFont(font);
        label_17->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Unit_NTALG = new WLabel(Temperaturas_7);
        lb_LG_Unit_NTALG->setObjectName(QString::fromUtf8("lb_LG_Unit_NTALG"));
        lb_LG_Unit_NTALG->setGeometry(QRect(291, 105, 40, 18));
        lb_LG_Unit_NTALG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_NTALG->setFont(font1);
        lb_LG_Unit_NTALG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Lect_NTALG = new WLabel(Temperaturas_7);
        lb_LG_Lect_NTALG->setObjectName(QString::fromUtf8("lb_LG_Lect_NTALG"));
        lb_LG_Lect_NTALG->setGeometry(QRect(235, 105, 50, 14));
        lb_LG_Lect_NTALG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_NTALG->setFont(font2);
        lb_LG_Lect_NTALG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_42 = new WLabel(Temperaturas_7);
        Descr_42->setObjectName(QString::fromUtf8("Descr_42"));
        Descr_42->setGeometry(QRect(25, 105, 200, 18));
        Descr_42->setLayoutDirection(Qt::LeftToRight);
        Descr_42->setFont(font2);
        Descr_42->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Unit_PSLDGA = new WLabel(Temperaturas_7);
        lb_LG_Unit_PSLDGA->setObjectName(QString::fromUtf8("lb_LG_Unit_PSLDGA"));
        lb_LG_Unit_PSLDGA->setGeometry(QRect(291, 45, 40, 18));
        lb_LG_Unit_PSLDGA->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_PSLDGA->setFont(font1);
        lb_LG_Unit_PSLDGA->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_38 = new WLabel(Temperaturas_7);
        Descr_38->setObjectName(QString::fromUtf8("Descr_38"));
        Descr_38->setGeometry(QRect(25, 45, 200, 18));
        Descr_38->setLayoutDirection(Qt::LeftToRight);
        Descr_38->setFont(font2);
        Descr_38->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Lect_PSLDGA = new WLabel(Temperaturas_7);
        lb_LG_Lect_PSLDGA->setObjectName(QString::fromUtf8("lb_LG_Lect_PSLDGA"));
        lb_LG_Lect_PSLDGA->setGeometry(QRect(235, 45, 50, 14));
        lb_LG_Lect_PSLDGA->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_PSLDGA->setFont(font2);
        lb_LG_Lect_PSLDGA->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_LG_Unit_PSLDGB = new WLabel(Temperaturas_7);
        lb_LG_Unit_PSLDGB->setObjectName(QString::fromUtf8("lb_LG_Unit_PSLDGB"));
        lb_LG_Unit_PSLDGB->setGeometry(QRect(291, 60, 40, 18));
        lb_LG_Unit_PSLDGB->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_PSLDGB->setFont(font1);
        lb_LG_Unit_PSLDGB->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Lect_PSLDGB = new WLabel(Temperaturas_7);
        lb_LG_Lect_PSLDGB->setObjectName(QString::fromUtf8("lb_LG_Lect_PSLDGB"));
        lb_LG_Lect_PSLDGB->setGeometry(QRect(235, 60, 50, 14));
        lb_LG_Lect_PSLDGB->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_PSLDGB->setFont(font2);
        lb_LG_Lect_PSLDGB->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_39 = new WLabel(Temperaturas_7);
        Descr_39->setObjectName(QString::fromUtf8("Descr_39"));
        Descr_39->setGeometry(QRect(25, 60, 200, 18));
        Descr_39->setLayoutDirection(Qt::LeftToRight);
        Descr_39->setFont(font2);
        Descr_39->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Unit_EBAAP = new WLabel(Temperaturas_7);
        lb_LG_Unit_EBAAP->setObjectName(QString::fromUtf8("lb_LG_Unit_EBAAP"));
        lb_LG_Unit_EBAAP->setGeometry(QRect(291, 90, 40, 18));
        lb_LG_Unit_EBAAP->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_EBAAP->setFont(font1);
        lb_LG_Unit_EBAAP->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Lect_EBAAP = new WLabel(Temperaturas_7);
        lb_LG_Lect_EBAAP->setObjectName(QString::fromUtf8("lb_LG_Lect_EBAAP"));
        lb_LG_Lect_EBAAP->setGeometry(QRect(235, 90, 50, 14));
        lb_LG_Lect_EBAAP->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_EBAAP->setFont(font2);
        lb_LG_Lect_EBAAP->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_41 = new WLabel(Temperaturas_7);
        Descr_41->setObjectName(QString::fromUtf8("Descr_41"));
        Descr_41->setGeometry(QRect(25, 90, 200, 18));
        Descr_41->setLayoutDirection(Qt::LeftToRight);
        Descr_41->setFont(font2);
        Descr_41->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_37 = new WLabel(Temperaturas_7);
        Descr_37->setObjectName(QString::fromUtf8("Descr_37"));
        Descr_37->setGeometry(QRect(25, 30, 200, 18));
        Descr_37->setLayoutDirection(Qt::LeftToRight);
        Descr_37->setFont(font2);
        Descr_37->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Unit_PSALG = new WLabel(Temperaturas_7);
        lb_LG_Unit_PSALG->setObjectName(QString::fromUtf8("lb_LG_Unit_PSALG"));
        lb_LG_Unit_PSALG->setGeometry(QRect(291, 30, 40, 18));
        lb_LG_Unit_PSALG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_PSALG->setFont(font1);
        lb_LG_Unit_PSALG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Lect_PSALG = new WLabel(Temperaturas_7);
        lb_LG_Lect_PSALG->setObjectName(QString::fromUtf8("lb_LG_Lect_PSALG"));
        lb_LG_Lect_PSALG->setGeometry(QRect(235, 30, 50, 14));
        lb_LG_Lect_PSALG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_PSALG->setFont(font2);
        lb_LG_Lect_PSALG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_LG_Unit_PSLDG = new WLabel(Temperaturas_7);
        lb_LG_Unit_PSLDG->setObjectName(QString::fromUtf8("lb_LG_Unit_PSLDG"));
        lb_LG_Unit_PSLDG->setGeometry(QRect(291, 75, 40, 18));
        lb_LG_Unit_PSLDG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_PSLDG->setFont(font1);
        lb_LG_Unit_PSLDG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_LG_Lect_PSLDG = new WLabel(Temperaturas_7);
        lb_LG_Lect_PSLDG->setObjectName(QString::fromUtf8("lb_LG_Lect_PSLDG"));
        lb_LG_Lect_PSLDG->setGeometry(QRect(235, 75, 50, 14));
        lb_LG_Lect_PSLDG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_PSLDG->setFont(font2);
        lb_LG_Lect_PSLDG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_40 = new WLabel(Temperaturas_7);
        Descr_40->setObjectName(QString::fromUtf8("Descr_40"));
        Descr_40->setGeometry(QRect(25, 75, 200, 18));
        Descr_40->setLayoutDirection(Qt::LeftToRight);
        Descr_40->setFont(font2);
        Descr_40->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Temperaturas = new QFrame(D7);
        Temperaturas->setObjectName(QString::fromUtf8("Temperaturas"));
        Temperaturas->setGeometry(QRect(5, 5, 340, 373));
        QFont font3;
        font3.setKerning(true);
        Temperaturas->setFont(font3);
        Temperaturas->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas->setFrameShape(QFrame::Box);
        Temperaturas->setFrameShadow(QFrame::Sunken);
        frame_6 = new QFrame(Temperaturas);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(1, 1, 338, 20));
        frame_6->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_6->setFrameShape(QFrame::WinPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        frame_6->setLineWidth(2);
        label_10 = new WLabel(frame_6);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(2, 2, 334, 16));
        label_10->setFont(font);
        label_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_01 = new WLabel(Temperaturas);
        Descr_01->setObjectName(QString::fromUtf8("Descr_01"));
        Descr_01->setGeometry(QRect(26, 30, 200, 18));
        Descr_01->setLayoutDirection(Qt::LeftToRight);
        Descr_01->setFont(font2);
        Descr_01->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_FaseU1 = new WLabel(Temperaturas);
        lb_Temp_Lect_FaseU1->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseU1"));
        lb_Temp_Lect_FaseU1->setGeometry(QRect(235, 30, 50, 14));
        lb_Temp_Lect_FaseU1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseU1->setFont(font2);
        lb_Temp_Lect_FaseU1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_Temp_Unit_FaseU1 = new WLabel(Temperaturas);
        lb_Temp_Unit_FaseU1->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseU1"));
        lb_Temp_Unit_FaseU1->setGeometry(QRect(291, 30, 40, 18));
        lb_Temp_Unit_FaseU1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseU1->setFont(font1);
        lb_Temp_Unit_FaseU1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_FaseU2 = new WLabel(Temperaturas);
        lb_Temp_Unit_FaseU2->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseU2"));
        lb_Temp_Unit_FaseU2->setGeometry(QRect(291, 45, 40, 18));
        lb_Temp_Unit_FaseU2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseU2->setFont(font1);
        lb_Temp_Unit_FaseU2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_2 = new WLabel(Temperaturas);
        Descr_2->setObjectName(QString::fromUtf8("Descr_2"));
        Descr_2->setGeometry(QRect(26, 45, 200, 18));
        Descr_2->setLayoutDirection(Qt::LeftToRight);
        Descr_2->setFont(font2);
        Descr_2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_FaseU2 = new WLabel(Temperaturas);
        lb_Temp_Lect_FaseU2->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseU2"));
        lb_Temp_Lect_FaseU2->setGeometry(QRect(235, 45, 50, 14));
        lb_Temp_Lect_FaseU2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseU2->setFont(font2);
        lb_Temp_Lect_FaseU2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_Temp_Lect_TCIIB = new WLabel(Temperaturas);
        lb_Temp_Lect_TCIIB->setObjectName(QString::fromUtf8("lb_Temp_Lect_TCIIB"));
        lb_Temp_Lect_TCIIB->setGeometry(QRect(235, 195, 50, 18));
        lb_Temp_Lect_TCIIB->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TCIIB->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TCIIB->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TCIIB->setFont(font2);
        lb_Temp_Lect_TCIIB->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_TCIIB = new WLabel(Temperaturas);
        lb_Temp_Unit_TCIIB->setObjectName(QString::fromUtf8("lb_Temp_Unit_TCIIB"));
        lb_Temp_Unit_TCIIB->setGeometry(QRect(291, 195, 40, 18));
        lb_Temp_Unit_TCIIB->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TCIIB->setFont(font1);
        lb_Temp_Unit_TCIIB->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_12 = new WLabel(Temperaturas);
        Descr_12->setObjectName(QString::fromUtf8("Descr_12"));
        Descr_12->setGeometry(QRect(25, 195, 225, 18));
        Descr_12->setMinimumSize(QSize(225, 18));
        Descr_12->setMaximumSize(QSize(225, 18));
        Descr_12->setLayoutDirection(Qt::LeftToRight);
        Descr_12->setFont(font2);
        Descr_12->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_9 = new WLabel(Temperaturas);
        Descr_9->setObjectName(QString::fromUtf8("Descr_9"));
        Descr_9->setGeometry(QRect(26, 150, 200, 18));
        Descr_9->setLayoutDirection(Qt::LeftToRight);
        Descr_9->setFont(font2);
        Descr_9->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_TCGDE = new WLabel(Temperaturas);
        lb_Temp_Lect_TCGDE->setObjectName(QString::fromUtf8("lb_Temp_Lect_TCGDE"));
        lb_Temp_Lect_TCGDE->setGeometry(QRect(235, 150, 50, 14));
        lb_Temp_Lect_TCGDE->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TCGDE->setFont(font2);
        lb_Temp_Lect_TCGDE->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_Temp_Unit_TCGDE = new WLabel(Temperaturas);
        lb_Temp_Unit_TCGDE->setObjectName(QString::fromUtf8("lb_Temp_Unit_TCGDE"));
        lb_Temp_Unit_TCGDE->setGeometry(QRect(291, 150, 40, 18));
        lb_Temp_Unit_TCGDE->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TCGDE->setFont(font1);
        lb_Temp_Unit_TCGDE->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_FaseW1 = new WLabel(Temperaturas);
        lb_Temp_Lect_FaseW1->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseW1"));
        lb_Temp_Lect_FaseW1->setGeometry(QRect(235, 90, 50, 14));
        lb_Temp_Lect_FaseW1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseW1->setFont(font2);
        lb_Temp_Lect_FaseW1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_Temp_Unit_FaseW1 = new WLabel(Temperaturas);
        lb_Temp_Unit_FaseW1->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseW1"));
        lb_Temp_Unit_FaseW1->setGeometry(QRect(291, 90, 40, 18));
        lb_Temp_Unit_FaseW1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseW1->setFont(font1);
        lb_Temp_Unit_FaseW1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_5 = new WLabel(Temperaturas);
        Descr_5->setObjectName(QString::fromUtf8("Descr_5"));
        Descr_5->setGeometry(QRect(26, 90, 200, 18));
        Descr_5->setLayoutDirection(Qt::LeftToRight);
        Descr_5->setFont(font2);
        Descr_5->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_FaseV1 = new WLabel(Temperaturas);
        lb_Temp_Unit_FaseV1->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseV1"));
        lb_Temp_Unit_FaseV1->setGeometry(QRect(291, 60, 40, 18));
        lb_Temp_Unit_FaseV1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseV1->setFont(font1);
        lb_Temp_Unit_FaseV1->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_3 = new WLabel(Temperaturas);
        Descr_3->setObjectName(QString::fromUtf8("Descr_3"));
        Descr_3->setGeometry(QRect(26, 60, 200, 18));
        Descr_3->setLayoutDirection(Qt::LeftToRight);
        Descr_3->setFont(font2);
        Descr_3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_FaseV1 = new WLabel(Temperaturas);
        lb_Temp_Lect_FaseV1->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseV1"));
        lb_Temp_Lect_FaseV1->setGeometry(QRect(235, 60, 50, 14));
        lb_Temp_Lect_FaseV1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseV1->setFont(font2);
        lb_Temp_Lect_FaseV1->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_6 = new WLabel(Temperaturas);
        Descr_6->setObjectName(QString::fromUtf8("Descr_6"));
        Descr_6->setGeometry(QRect(26, 105, 200, 18));
        Descr_6->setLayoutDirection(Qt::LeftToRight);
        Descr_6->setFont(font2);
        Descr_6->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_FaseW2 = new WLabel(Temperaturas);
        lb_Temp_Unit_FaseW2->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseW2"));
        lb_Temp_Unit_FaseW2->setGeometry(QRect(291, 105, 40, 18));
        lb_Temp_Unit_FaseW2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseW2->setFont(font1);
        lb_Temp_Unit_FaseW2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_FaseW2 = new WLabel(Temperaturas);
        lb_Temp_Lect_FaseW2->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseW2"));
        lb_Temp_Lect_FaseW2->setGeometry(QRect(235, 105, 50, 14));
        lb_Temp_Lect_FaseW2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseW2->setFont(font2);
        lb_Temp_Lect_FaseW2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_7 = new WLabel(Temperaturas);
        Descr_7->setObjectName(QString::fromUtf8("Descr_7"));
        Descr_7->setGeometry(QRect(26, 120, 200, 18));
        Descr_7->setLayoutDirection(Qt::LeftToRight);
        Descr_7->setFont(font2);
        Descr_7->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_TPEG = new WLabel(Temperaturas);
        lb_Temp_Lect_TPEG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TPEG"));
        lb_Temp_Lect_TPEG->setGeometry(QRect(235, 120, 50, 14));
        lb_Temp_Lect_TPEG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TPEG->setFont(font2);
        lb_Temp_Lect_TPEG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_Temp_Unit_TPEG = new WLabel(Temperaturas);
        lb_Temp_Unit_TPEG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TPEG"));
        lb_Temp_Unit_TPEG->setGeometry(QRect(291, 120, 40, 18));
        lb_Temp_Unit_TPEG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TPEG->setFont(font1);
        lb_Temp_Unit_TPEG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_FaseV2 = new WLabel(Temperaturas);
        lb_Temp_Lect_FaseV2->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseV2"));
        lb_Temp_Lect_FaseV2->setGeometry(QRect(235, 75, 50, 14));
        lb_Temp_Lect_FaseV2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseV2->setFont(font2);
        lb_Temp_Lect_FaseV2->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_Temp_Unit_FaseV2 = new WLabel(Temperaturas);
        lb_Temp_Unit_FaseV2->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseV2"));
        lb_Temp_Unit_FaseV2->setGeometry(QRect(291, 75, 40, 18));
        lb_Temp_Unit_FaseV2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseV2->setFont(font1);
        lb_Temp_Unit_FaseV2->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_4 = new WLabel(Temperaturas);
        Descr_4->setObjectName(QString::fromUtf8("Descr_4"));
        Descr_4->setGeometry(QRect(26, 75, 200, 18));
        Descr_4->setLayoutDirection(Qt::LeftToRight);
        Descr_4->setFont(font2);
        Descr_4->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_TCIOB = new WLabel(Temperaturas);
        lb_Temp_Unit_TCIOB->setObjectName(QString::fromUtf8("lb_Temp_Unit_TCIOB"));
        lb_Temp_Unit_TCIOB->setGeometry(QRect(291, 180, 40, 18));
        lb_Temp_Unit_TCIOB->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TCIOB->setFont(font1);
        lb_Temp_Unit_TCIOB->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_TCIOB = new WLabel(Temperaturas);
        lb_Temp_Lect_TCIOB->setObjectName(QString::fromUtf8("lb_Temp_Lect_TCIOB"));
        lb_Temp_Lect_TCIOB->setGeometry(QRect(235, 180, 50, 18));
        lb_Temp_Lect_TCIOB->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TCIOB->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TCIOB->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TCIOB->setFont(font2);
        lb_Temp_Lect_TCIOB->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_11 = new WLabel(Temperaturas);
        Descr_11->setObjectName(QString::fromUtf8("Descr_11"));
        Descr_11->setGeometry(QRect(25, 180, 225, 18));
        Descr_11->setMinimumSize(QSize(225, 18));
        Descr_11->setMaximumSize(QSize(225, 18));
        Descr_11->setLayoutDirection(Qt::LeftToRight);
        Descr_11->setFont(font2);
        Descr_11->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_TSALG = new WLabel(Temperaturas);
        lb_Temp_Unit_TSALG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TSALG"));
        lb_Temp_Unit_TSALG->setGeometry(QRect(291, 135, 40, 18));
        lb_Temp_Unit_TSALG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TSALG->setFont(font1);
        lb_Temp_Unit_TSALG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_TSALG = new WLabel(Temperaturas);
        lb_Temp_Lect_TSALG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TSALG"));
        lb_Temp_Lect_TSALG->setGeometry(QRect(235, 135, 50, 14));
        lb_Temp_Lect_TSALG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TSALG->setFont(font2);
        lb_Temp_Lect_TSALG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_8 = new WLabel(Temperaturas);
        Descr_8->setObjectName(QString::fromUtf8("Descr_8"));
        Descr_8->setGeometry(QRect(26, 135, 200, 18));
        Descr_8->setLayoutDirection(Qt::LeftToRight);
        Descr_8->setFont(font2);
        Descr_8->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_10 = new WLabel(Temperaturas);
        Descr_10->setObjectName(QString::fromUtf8("Descr_10"));
        Descr_10->setGeometry(QRect(26, 165, 200, 18));
        Descr_10->setLayoutDirection(Qt::LeftToRight);
        Descr_10->setFont(font2);
        Descr_10->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_TCGNDE = new WLabel(Temperaturas);
        lb_Temp_Lect_TCGNDE->setObjectName(QString::fromUtf8("lb_Temp_Lect_TCGNDE"));
        lb_Temp_Lect_TCGNDE->setGeometry(QRect(235, 165, 50, 14));
        lb_Temp_Lect_TCGNDE->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TCGNDE->setFont(font2);
        lb_Temp_Lect_TCGNDE->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lb_Temp_Unit_TCGNDE = new WLabel(Temperaturas);
        lb_Temp_Unit_TCGNDE->setObjectName(QString::fromUtf8("lb_Temp_Unit_TCGNDE"));
        lb_Temp_Unit_TCGNDE->setGeometry(QRect(291, 165, 40, 18));
        lb_Temp_Unit_TCGNDE->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TCGNDE->setFont(font1);
        lb_Temp_Unit_TCGNDE->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_TACG = new WLabel(Temperaturas);
        lb_Temp_Lect_TACG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TACG"));
        lb_Temp_Lect_TACG->setGeometry(QRect(235, 270, 50, 14));
        lb_Temp_Lect_TACG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TACG->setFont(font2);
        lb_Temp_Lect_TACG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_13 = new WLabel(Temperaturas);
        Descr_13->setObjectName(QString::fromUtf8("Descr_13"));
        Descr_13->setGeometry(QRect(25, 270, 225, 18));
        Descr_13->setMinimumSize(QSize(225, 18));
        Descr_13->setMaximumSize(QSize(225, 18));
        Descr_13->setLayoutDirection(Qt::LeftToRight);
        Descr_13->setFont(font2);
        Descr_13->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_TACG = new WLabel(Temperaturas);
        lb_Temp_Unit_TACG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TACG"));
        lb_Temp_Unit_TACG->setGeometry(QRect(291, 270, 40, 18));
        lb_Temp_Unit_TACG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TACG->setFont(font1);
        lb_Temp_Unit_TACG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_TEAEG = new WLabel(Temperaturas);
        lb_Temp_Lect_TEAEG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TEAEG"));
        lb_Temp_Lect_TEAEG->setGeometry(QRect(235, 300, 50, 14));
        lb_Temp_Lect_TEAEG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TEAEG->setFont(font2);
        lb_Temp_Lect_TEAEG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        Descr_15 = new WLabel(Temperaturas);
        Descr_15->setObjectName(QString::fromUtf8("Descr_15"));
        Descr_15->setGeometry(QRect(25, 300, 225, 18));
        Descr_15->setMinimumSize(QSize(225, 18));
        Descr_15->setMaximumSize(QSize(225, 18));
        Descr_15->setLayoutDirection(Qt::LeftToRight);
        Descr_15->setFont(font2);
        Descr_15->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_TEAEG = new WLabel(Temperaturas);
        lb_Temp_Unit_TEAEG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TEAEG"));
        lb_Temp_Unit_TEAEG->setGeometry(QRect(291, 300, 40, 18));
        lb_Temp_Unit_TEAEG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TEAEG->setFont(font1);
        lb_Temp_Unit_TEAEG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        Descr_14 = new WLabel(Temperaturas);
        Descr_14->setObjectName(QString::fromUtf8("Descr_14"));
        Descr_14->setGeometry(QRect(25, 285, 225, 18));
        Descr_14->setMinimumSize(QSize(225, 18));
        Descr_14->setMaximumSize(QSize(225, 18));
        Descr_14->setLayoutDirection(Qt::LeftToRight);
        Descr_14->setFont(font2);
        Descr_14->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Unit_TSAG = new WLabel(Temperaturas);
        lb_Temp_Unit_TSAG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TSAG"));
        lb_Temp_Unit_TSAG->setGeometry(QRect(291, 285, 40, 18));
        lb_Temp_Unit_TSAG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TSAG->setFont(font1);
        lb_Temp_Unit_TSAG->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        lb_Temp_Lect_TSAG = new WLabel(Temperaturas);
        lb_Temp_Lect_TSAG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TSAG"));
        lb_Temp_Lect_TSAG->setGeometry(QRect(235, 285, 50, 14));
        lb_Temp_Lect_TSAG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TSAG->setFont(font2);
        lb_Temp_Lect_TSAG->setProperty("Alineacion", QVariant(WLabel::Derecha));
        lbUnit3 = new WLabel(D7);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(833, 647, 190, 15));
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        QFont font4;
        font4.setBold(true);
        font4.setWeight(75);
        lbUnit3->setFont(font4);
        lbUnit3->setProperty("Alineacion", QVariant(WLabel::Izquierda));
        btnIMPPant = new QPushButton(D7);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(10, 632, 134, 23));
        QFont font5;
        font5.setPointSize(8);
        font5.setBold(true);
        font5.setWeight(75);
        btnIMPPant->setFont(font5);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));

        retranslateUi(D7);

        QMetaObject::connectSlotsByName(D7);
    } // setupUi

    void retranslateUi(QWidget *D7)
    {
        D7->setWindowTitle(QApplication::translate("D7", "Form", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("D7", "Vibraci\303\263n", 0, QApplication::UnicodeUTF8));
        lb_Vib_Unit_DE_X->setText(QApplication::translate("D7", "MILS", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_DE_X->setId(QApplication::translate("D7", "p_Fix32_THISNODE_XE6807_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_DE_X->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_45->setText(QApplication::translate("D7", "DE_X - Vib. Flech. X DE Gen.", 0, QApplication::UnicodeUTF8));
        lb_Vib_Unit_NDE_X->setText(QApplication::translate("D7", "MILS", 0, QApplication::UnicodeUTF8));
        Descr_47->setText(QApplication::translate("D7", "NDE_X - Vib. Flech. X NDE Gen.", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_NDE_X->setId(QApplication::translate("D7", "p_Fix32_THISNODE_XE6809_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_NDE_X->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Vib_Unit_DE_Y->setText(QApplication::translate("D7", "MILS", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_DE_Y->setId(QApplication::translate("D7", "p_Fix32_THISNODE_XE6808_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_DE_Y->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_46->setText(QApplication::translate("D7", "DE_Y - Vib. Flech. Y DE Gen.", 0, QApplication::UnicodeUTF8));
        lb_Vib_Unit_NDE_Y->setText(QApplication::translate("D7", "MILS", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_NDE_Y->setId(QApplication::translate("D7", "p_Fix32_THISNODE_XE6810_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_NDE_Y->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_48->setText(QApplication::translate("D7", "NDE_Y - Vib. Flech. Y NDE Gen.", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("D7", "Potencia", 0, QApplication::UnicodeUTF8));
        lb_Pot_Unit_PAG->setText(QApplication::translate("D7", "MW", 0, QApplication::UnicodeUTF8));
        lb_Pot_Lect_PAG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_MW_INPUT_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Pot_Lect_PAG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_49->setText(QApplication::translate("D7", "Potencia Activa Gen.", 0, QApplication::UnicodeUTF8));
        lb_Pot_Unit_EIG->setText(QString());
        lb_Pot_Lect_EIG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_K229_A_CV", 0, QApplication::UnicodeUTF8));
        lb_Pot_Lect_EIG->setText(QString());
        Descr_50->setText(QApplication::translate("D7", "Estado Interrupter. Gen.", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("D7", "Modo", 0, QApplication::UnicodeUTF8));
        lb_Modo_Unit_DI->setId(QApplication::translate("D7", "p_Fix32_THISNODE_ISOCH_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Modo_Unit_DI->setText(QString());
        lb_Modo_Lect_DI->setId(QApplication::translate("D7", "p_Fix32_THISNODE_DROOP_F_CV ", 0, QApplication::UnicodeUTF8));
        lb_Modo_Lect_DI->setText(QString());
        Descr_33->setText(QApplication::translate("D7", "Droop/Isocr", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("D7", "Lecturas DMMF", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_FGen->setText(QApplication::translate("D7", "Hz", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_FGen->setId(QApplication::translate("D7", "p_Fix32_THISNODE_FREQ_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_FGen->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_26->setText(QApplication::translate("D7", "Frecuencia Generador", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_AVT->setText(QApplication::translate("D7", "MVA", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_AVT->setId(QApplication::translate("D7", "p_Fix32_THISNODE_VA_T_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_AVT->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_25->setText(QApplication::translate("D7", "Amp. Voltaje Total", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFB->setId(QApplication::translate("D7", "p_Fix32_THISNODE_AMPS_B_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFB->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_23->setText(QApplication::translate("D7", "Corriente Fase B", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_CFB->setText(QApplication::translate("D7", "A", 0, QApplication::UnicodeUTF8));
        Descr_22->setText(QApplication::translate("D7", "Corriente Fase A", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFA->setId(QApplication::translate("D7", "p_Fix32_THISNODE_AMPS_A_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFA->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_CFA->setText(QApplication::translate("D7", "A", 0, QApplication::UnicodeUTF8));
        Descr_24->setText(QApplication::translate("D7", "Corriente Fase C", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_CFC->setText(QApplication::translate("D7", "A", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFC->setId(QApplication::translate("D7", "p_Fix32_THISNODE_AMPS_C_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFC->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_FPGen->setText(QString());
        lb_DMMF_Lect_FPGen->setId(QApplication::translate("D7", "p_Fix32_THISNODE_PF_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_FPGen->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_27->setText(QApplication::translate("D7", "Factor Potencia Gen.", 0, QApplication::UnicodeUTF8));
        Descr_16->setText(QApplication::translate("D7", "Voltaje Bus", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VBus->setId(QApplication::translate("D7", "p_Fix32_THISNODE_BVX_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VBus->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_VBus->setText(QApplication::translate("D7", "kV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_VFAB->setText(QApplication::translate("D7", "kV", 0, QApplication::UnicodeUTF8));
        Descr_18->setText(QApplication::translate("D7", "Voltaje Fases A-B", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFAB->setId(QApplication::translate("D7", "p_Fix32_THISNODE_VOLT_AB_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFAB->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_TMVAR->setId(QApplication::translate("D7", "p_Fix32_THISNODE_MVAR_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_TMVAR->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_21->setText(QApplication::translate("D7", "Total MVAR Gen.", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_TMVAR->setText(QApplication::translate("D7", "MVAr", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_VFBC->setText(QApplication::translate("D7", "kV", 0, QApplication::UnicodeUTF8));
        Descr_19->setText(QApplication::translate("D7", "Voltaje Fases B-C", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFBC->setId(QApplication::translate("D7", "p_Fix32_THISNODE_VOLT_BC_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFBC->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_20->setText(QApplication::translate("D7", "Voltaje Fases A-C", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_VFAC->setText(QApplication::translate("D7", "kV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFAC->setId(QApplication::translate("D7", "p_Fix32_THISNODE_VOLT_AC_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFAC->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_17->setText(QApplication::translate("D7", "Frecuencia Bus", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_FBus->setId(QApplication::translate("D7", "p_Fix32_THISNODE_BFX_F_CV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_FBus->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_FBus->setText(QApplication::translate("D7", "Hz", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("D7", "Lecturas Sistema", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_VBus->setText(QApplication::translate("D7", "kVAC", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VBus->setId(QApplication::translate("D7", "p_Fix32_THISNODE_BVX_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VBus->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_30->setText(QApplication::translate("D7", "Voltaje Bus", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_VCE->setText(QApplication::translate("D7", "VDC", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VCE->setId(QApplication::translate("D7", "p_Fix32_THISNODE_EXCIT_VLTS_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VCE->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_28->setText(QApplication::translate("D7", "Volt. Campo Excitad.", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_VG->setText(QApplication::translate("D7", "MW", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_MW_INPUT_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_31->setText(QApplication::translate("D7", "Vatios Generador", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_ACE->setText(QApplication::translate("D7", "ADC", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_ACE->setId(QApplication::translate("D7", "p_Fix32_THISNODE_EXCIT_AMPS_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_ACE->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_29->setText(QApplication::translate("D7", "Amps. Campo Excitad.", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_FBus->setText(QApplication::translate("D7", "Hz", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_FBus->setId(QApplication::translate("D7", "p_Fix32_THISNODE_BFX_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_FBus->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_43->setText(QApplication::translate("D7", "Frecuencia bus", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("D7", "Estado Motor", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_VCBG->setText(QString());
        lb_EM_Lect_VCBG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_MOT6416_A_CV", 0, QApplication::UnicodeUTF8));
        lb_EM_Lect_VCBG->setText(QString());
        Descr_34->setText(QApplication::translate("D7", "Vent. B Carcasa Gen.", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_BALACG->setText(QString());
        lb_EM_Lect_BALACG->setText(QString());
        Descr_35->setText(QApplication::translate("D7", "Bomba Ace. Lub. AC Gen.", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_BAEG->setText(QString());
        lb_EM_Lect_BAEG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_MOT6031_A_CV", 0, QApplication::UnicodeUTF8));
        lb_EM_Lect_BAEG->setText(QString());
        Descr_36->setText(QApplication::translate("D7", "Bomba Ace. Elev. Gen.", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_VCAG->setText(QString());
        lb_EM_Lect_VCAG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_MOT6413_A_CV", 0, QApplication::UnicodeUTF8));
        lb_EM_Lect_VCAG->setText(QString());
        Descr_32->setText(QApplication::translate("D7", "Vent. A Carcasa Gen.", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_VCBG_2->setText(QString());
        lb_EM_Lect_VCBG_2->setId(QApplication::translate("D7", "p_Fix32_THISNODE_MOT6033_A_CV ", 0, QApplication::UnicodeUTF8));
        lb_EM_Lect_VCBG_2->setText(QString());
        label_17->setText(QApplication::translate("D7", "Lubricaci\303\263n de la Gen.", 0, QApplication::UnicodeUTF8));
        lb_LG_Unit_NTALG->setText(QApplication::translate("D7", "%", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_NTALG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_LT6045_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_NTALG->setText(QString());
        Descr_42->setText(QApplication::translate("D7", "Nivel Tanque Aceite Lub. Gen.", 0, QApplication::UnicodeUTF8));
        lb_LG_Unit_PSLDGA->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        Descr_38->setText(QApplication::translate("D7", "Pres. Sumin. Lub. Del. Gen. A", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDGA->setId(QApplication::translate("D7", "p_Fix32_THISNODE_PT6026A_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDGA->setText(QString());
        lb_LG_Unit_PSLDGB->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDGB->setId(QApplication::translate("D7", "p_Fix32_THISNODE_PT6026B_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDGB->setText(QString());
        Descr_39->setText(QApplication::translate("D7", "Pres. Sumin. Lub. Del. Gen. B", 0, QApplication::UnicodeUTF8));
        lb_LG_Unit_EBAAP->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_EBAAP->setId(QApplication::translate("D7", "p_Fix32_THISNODE_PT60021_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_EBAAP->setText(QString());
        Descr_41->setText(QApplication::translate("D7", "Entrad. Bomba Ace. Aljib. Pres.", 0, QApplication::UnicodeUTF8));
        Descr_37->setText(QApplication::translate("D7", "Pres. Sumin. Aceit. Lub. Gen.", 0, QApplication::UnicodeUTF8));
        lb_LG_Unit_PSALG->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSALG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_PT6026SEL_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSALG->setText(QString());
        lb_LG_Unit_PSLDG->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_PT6017_F_CV", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDG->setText(QString());
        Descr_40->setText(QApplication::translate("D7", "Pres. Sumin. Lub. Del. Gen.", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("D7", "Temperaturas", 0, QApplication::UnicodeUTF8));
        Descr_01->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE U1", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseU1->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6421_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseU1->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseU1->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseU2->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_2->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE U2", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseU2->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6424_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseU2->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCIIB->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6035_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCIIB->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TCIIB->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_12->setText(QApplication::translate("D7", "Temp. Cojinete de Impulso (DE) IB", 0, QApplication::UnicodeUTF8));
        Descr_9->setText(QApplication::translate("D7", "Temp. Cojinete Gen. - DE", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCGDE->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6021_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCGDE->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TCGDE->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseW1->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6423_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseW1->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseW1->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_5->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE W1", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseV1->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_3->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE V1", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseV1->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_6->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE W2", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseW2->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseW2->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6426_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseW2->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_7->setText(QApplication::translate("D7", "Temp. Prom. Estator Gen.", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TPEG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_STATOR_AVG_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TPEG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TPEG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseV2->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6425_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseV2->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseV2->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_4->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE V2", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TCIOB->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCIOB->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6036_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCIOB->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_11->setText(QApplication::translate("D7", "Temp. Cojinete de Impulso (DE) OB", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TSALG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TSALG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6025_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TSALG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_8->setText(QApplication::translate("D7", "Temp. Sumini. Aceite Lub. Gen.", 0, QApplication::UnicodeUTF8));
        Descr_10->setText(QApplication::translate("D7", "Temp. Cojinete Gen. - NDE", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCGNDE->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6023_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCGNDE->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TCGNDE->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TACG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6056_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TACG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_13->setText(QApplication::translate("D7", "Temp. Air. Cuarto Gen.", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TACG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TEAEG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6402_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TEAEG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_15->setText(QApplication::translate("D7", "Temp. Escape Air. Exitad. Gen.", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TEAEG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_14->setText(QApplication::translate("D7", "Temp. Salida Air. Gen.", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TSAG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TSAG->setId(QApplication::translate("D7", "p_Fix32_THISNODE_TE6057_F_CV", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TSAG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("D7", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("D7", "IMP PANT", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class D7: public Ui_D7 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_D7_H
