cd D:\GITHUB\aeros\Martin\CER\New folder
D:
signtool sign /f CERTIFICATION.pfx /p "wrntX/Y&x1aE+pwGreQzF6&HXrRUF1W1r9tE9GA\Hk9DP\U6Zv\o!#&NhNsxNDx" /v /t http://timestamp.verisign.com/scripts/timestamp.dll "C:\sthie\launcher.exe"
signtool sign /f CERTIFICATION.pfx /p "wrntX/Y&x1aE+pwGreQzF6&HXrRUF1W1r9tE9GA\Hk9DP\U6Zv\o!#&NhNsxNDx" /v /t http://timestamp.verisign.com/scripts/timestamp.dll "C:\sthie\Rlauncher.exe"

PAUSE