/********************************************************************************
** Form generated from reading UI file 'f5.ui'
**
** Created: Mon 2. Dec 16:27:59 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_F5_H
#define UI_F5_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "awmultiobject.h"

QT_BEGIN_NAMESPACE

class Ui_F5
{
public:
    QLabel *lbIMGFondo;
    QFrame *frTitulo_9;
    QLabel *lbAux_2;
    QLabel *lbApagado;
    QLabel *lbAux_1;
    QLabel *lbUnit3;
    QFrame *frAux_2;
    QLabel *lbValDES;
    QLabel *lbValNUM;
    QPushButton *btnIMPPant;
    QFrame *frAux;
    QFrame *fr_1;
    QFrame *frTitulo_1;
    QLabel *lbTitulo_1;
    QLabel *lbTexto_1;
    AWMultiObject *aLet_1;
    QLabel *lbTexto_2;
    AWMultiObject *aLet_2;
    QLabel *lbTexto_3;
    AWMultiObject *aLet_3;
    QLabel *lbTexto_4;
    AWMultiObject *aLet_4;
    AWMultiObject *aLet_5;
    QLabel *lbTexto_5;
    AWMultiObject *aLet_6;
    QLabel *lbTexto_6;
    QLabel *lbTexto_7;
    AWMultiObject *aLet_7;
    AWMultiObject *aLet_8;
    QLabel *lbTexto_8;
    AWMultiObject *aLet_9;
    QLabel *lbTexto_9;
    QLabel *lbTexto_10;
    AWMultiObject *aLet_10;
    QLabel *lbTexto_11;
    AWMultiObject *aLet_11;
    AWMultiObject *aLet_12;
    QLabel *lbTexto_12;
    QLabel *lbTexto_13;
    AWMultiObject *aLet_13;
    AWMultiObject *aLet_14;
    QLabel *lbTexto_14;
    QLabel *lbTexto_15;
    AWMultiObject *aLet_15;
    AWMultiObject *aLet_16;
    QLabel *lbTexto_16;
    AWMultiObject *aLet_17;
    QLabel *lbTexto_17;
    AWMultiObject *aLet_18;
    QLabel *lbTexto_18;
    AWMultiObject *aLet_19;
    QLabel *lbTexto_19;
    QLabel *lbTexto_58;
    AWMultiObject *aLet_58;
    QLabel *lbTexto_59;
    AWMultiObject *aLet_59;
    AWMultiObject *aLet_61;
    QLabel *lbTexto_61;
    QFrame *fr_2;
    QFrame *frTitulo_2;
    QLabel *lbTitulo_2;
    QLabel *lbTexto_20;
    AWMultiObject *aLet_20;
    QLabel *lbTexto_21;
    AWMultiObject *aLet_21;
    QLabel *lbTexto_22;
    AWMultiObject *aLet_22;
    QLabel *lbTexto_23;
    AWMultiObject *aLet_23;
    AWMultiObject *aLet_24;
    QLabel *lbTexto_24;
    AWMultiObject *aLet_25;
    QLabel *lbTexto_25;
    QLabel *lbTexto_26;
    AWMultiObject *aLet_26;
    AWMultiObject *aLet_27;
    QLabel *lbTexto_27;
    AWMultiObject *aLet_28;
    QLabel *lbTexto_28;
    QLabel *lbTexto_29;
    AWMultiObject *aLet_29;
    QLabel *lbTexto_30;
    AWMultiObject *aLet_30;
    AWMultiObject *aLet_31;
    QLabel *lbTexto_31;
    QLabel *lbTexto_32;
    AWMultiObject *aLet_32;
    AWMultiObject *aLet_33;
    QLabel *lbTexto_33;
    QLabel *lbTexto_34;
    AWMultiObject *aLet_34;
    AWMultiObject *aLet_35;
    QLabel *lbTexto_35;
    AWMultiObject *aLet_36;
    QLabel *lbTexto_36;
    AWMultiObject *aLet_37;
    QLabel *lbTexto_37;
    AWMultiObject *aLet_38;
    QLabel *lbTexto_38;
    QLabel *lbTexto_60;
    AWMultiObject *aLet_60;
    QFrame *fr_3;
    QFrame *frTitulo_3;
    QLabel *lbTitulo_3;
    QLabel *lbTexto_39;
    AWMultiObject *aLet_39;
    QLabel *lbTexto_40;
    AWMultiObject *aLet_40;
    QLabel *lbTexto_41;
    AWMultiObject *aLet_41;
    QLabel *lbTexto_42;
    AWMultiObject *aLet_42;
    AWMultiObject *aLet_43;
    QLabel *lbTexto_43;
    AWMultiObject *aLet_44;
    QLabel *lbTexto_44;
    QLabel *lbTexto_45;
    AWMultiObject *aLet_45;
    AWMultiObject *aLet_46;
    QLabel *lbTexto_46;
    AWMultiObject *aLet_47;
    QLabel *lbTexto_47;
    QLabel *lbTexto_48;
    AWMultiObject *aLet_48;
    QLabel *lbTexto_49;
    AWMultiObject *aLet_49;
    AWMultiObject *aLet_50;
    QLabel *lbTexto_50;
    QLabel *lbTexto_51;
    AWMultiObject *aLet_51;
    AWMultiObject *aLet_52;
    QLabel *lbTexto_52;
    QLabel *lbTexto_53;
    AWMultiObject *aLet_53;
    AWMultiObject *aLet_54;
    QLabel *lbTexto_54;
    AWMultiObject *aLet_55;
    QLabel *lbTexto_55;
    AWMultiObject *aLet_56;
    QLabel *lbTexto_56;
    AWMultiObject *aLet_57;
    QLabel *lbTexto_57;
    QLabel *lbTexto_62;
    AWMultiObject *aLet_62;
    AWMultiObject *aLet_63;
    QLabel *lbTexto_63;

    void setupUi(QWidget *F5)
    {
        if (F5->objectName().isEmpty())
            F5->setObjectName(QString::fromUtf8("F5"));
        F5->resize(1024, 662);
        F5->setMinimumSize(QSize(1024, 662));
        F5->setMaximumSize(QSize(1024, 662));
        F5->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbIMGFondo = new QLabel(F5);
        lbIMGFondo->setObjectName(QString::fromUtf8("lbIMGFondo"));
        lbIMGFondo->setGeometry(QRect(0, 0, 1024, 662));
        lbIMGFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/BackGround.png")));
        lbIMGFondo->setScaledContents(true);
        frTitulo_9 = new QFrame(F5);
        frTitulo_9->setObjectName(QString::fromUtf8("frTitulo_9"));
        frTitulo_9->setGeometry(QRect(310, 593, 561, 54));
        frTitulo_9->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_9->setFrameShape(QFrame::WinPanel);
        frTitulo_9->setFrameShadow(QFrame::Raised);
        frTitulo_9->setLineWidth(2);
        frTitulo_9->setMidLineWidth(0);
        lbAux_2 = new QLabel(F5);
        lbAux_2->setObjectName(QString::fromUtf8("lbAux_2"));
        lbAux_2->setGeometry(QRect(427, 600, 101, 16));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        lbAux_2->setFont(font);
        lbAux_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbApagado = new QLabel(F5);
        lbApagado->setObjectName(QString::fromUtf8("lbApagado"));
        lbApagado->setGeometry(QRect(140, 587, 111, 71));
        lbApagado->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbAux_1 = new QLabel(F5);
        lbAux_1->setObjectName(QString::fromUtf8("lbAux_1"));
        lbAux_1->setGeometry(QRect(340, 600, 46, 16));
        lbAux_1->setFont(font);
        lbAux_1->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbUnit3 = new QLabel(F5);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(835, 649, 190, 15));
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        lbUnit3->setFont(font1);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        frAux_2 = new QFrame(F5);
        frAux_2->setObjectName(QString::fromUtf8("frAux_2"));
        frAux_2->setGeometry(QRect(396, 618, 466, 24));
        frAux_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux_2->setFrameShape(QFrame::WinPanel);
        frAux_2->setFrameShadow(QFrame::Sunken);
        lbValDES = new QLabel(F5);
        lbValDES->setObjectName(QString::fromUtf8("lbValDES"));
        lbValDES->setGeometry(QRect(406, 623, 151, 16));
        QFont font2;
        font2.setPointSize(11);
        font2.setBold(true);
        font2.setWeight(75);
        lbValDES->setFont(font2);
        lbValDES->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        lbValNUM = new QLabel(F5);
        lbValNUM->setObjectName(QString::fromUtf8("lbValNUM"));
        lbValNUM->setGeometry(QRect(346, 623, 35, 16));
        lbValNUM->setFont(font2);
        lbValNUM->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        btnIMPPant = new QPushButton(F5);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(7, 640, 134, 21));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(true);
        font3.setWeight(75);
        btnIMPPant->setFont(font3);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        frAux = new QFrame(F5);
        frAux->setObjectName(QString::fromUtf8("frAux"));
        frAux->setGeometry(QRect(320, 618, 63, 24));
        frAux->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frAux->setFrameShape(QFrame::WinPanel);
        frAux->setFrameShadow(QFrame::Sunken);
        fr_1 = new QFrame(F5);
        fr_1->setObjectName(QString::fromUtf8("fr_1"));
        fr_1->setGeometry(QRect(2, 85, 341, 501));
        fr_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_1->setFrameShape(QFrame::StyledPanel);
        fr_1->setFrameShadow(QFrame::Plain);
        fr_1->setLineWidth(1);
        fr_1->setMidLineWidth(0);
        frTitulo_1 = new QFrame(fr_1);
        frTitulo_1->setObjectName(QString::fromUtf8("frTitulo_1"));
        frTitulo_1->setGeometry(QRect(3, 2, 333, 24));
        frTitulo_1->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_1->setFrameShape(QFrame::WinPanel);
        frTitulo_1->setFrameShadow(QFrame::Raised);
        frTitulo_1->setLineWidth(2);
        frTitulo_1->setMidLineWidth(0);
        lbTitulo_1 = new QLabel(fr_1);
        lbTitulo_1->setObjectName(QString::fromUtf8("lbTitulo_1"));
        lbTitulo_1->setGeometry(QRect(8, 2, 325, 20));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        lbTitulo_1->setFont(font4);
        lbTitulo_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_1 = new QLabel(fr_1);
        lbTexto_1->setObjectName(QString::fromUtf8("lbTexto_1"));
        lbTexto_1->setGeometry(QRect(42, 33, 281, 16));
        lbTexto_1->setFont(font3);
        lbTexto_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_1 = new AWMultiObject(fr_1);
        aLet_1->setObjectName(QString::fromUtf8("aLet_1"));
        aLet_1->setGeometry(QRect(13, 26, 25, 31));
        aLet_1->setElementType(AWMultiObject::CIRLED);
        aLet_1->setOnColor(AWMultiObject::Grey);
        aLet_1->setOffColor(AWMultiObject::Grey);
        lbTexto_2 = new QLabel(fr_1);
        lbTexto_2->setObjectName(QString::fromUtf8("lbTexto_2"));
        lbTexto_2->setGeometry(QRect(42, 50, 281, 16));
        lbTexto_2->setFont(font3);
        lbTexto_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_2 = new AWMultiObject(fr_1);
        aLet_2->setObjectName(QString::fromUtf8("aLet_2"));
        aLet_2->setGeometry(QRect(13, 44, 25, 31));
        aLet_2->setElementType(AWMultiObject::CIRLED);
        aLet_2->setOnColor(AWMultiObject::Grey);
        aLet_2->setOffColor(AWMultiObject::Grey);
        lbTexto_3 = new QLabel(fr_1);
        lbTexto_3->setObjectName(QString::fromUtf8("lbTexto_3"));
        lbTexto_3->setGeometry(QRect(42, 68, 281, 16));
        lbTexto_3->setFont(font3);
        lbTexto_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_3 = new AWMultiObject(fr_1);
        aLet_3->setObjectName(QString::fromUtf8("aLet_3"));
        aLet_3->setGeometry(QRect(13, 62, 25, 31));
        aLet_3->setElementType(AWMultiObject::CIRLED);
        aLet_3->setOnColor(AWMultiObject::Grey);
        aLet_3->setOffColor(AWMultiObject::Grey);
        lbTexto_4 = new QLabel(fr_1);
        lbTexto_4->setObjectName(QString::fromUtf8("lbTexto_4"));
        lbTexto_4->setGeometry(QRect(42, 87, 281, 16));
        lbTexto_4->setFont(font3);
        lbTexto_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_4 = new AWMultiObject(fr_1);
        aLet_4->setObjectName(QString::fromUtf8("aLet_4"));
        aLet_4->setGeometry(QRect(13, 80, 25, 31));
        aLet_4->setElementType(AWMultiObject::CIRLED);
        aLet_4->setOnColor(AWMultiObject::Grey);
        aLet_4->setOffColor(AWMultiObject::Grey);
        aLet_5 = new AWMultiObject(fr_1);
        aLet_5->setObjectName(QString::fromUtf8("aLet_5"));
        aLet_5->setGeometry(QRect(13, 99, 25, 31));
        aLet_5->setElementType(AWMultiObject::CIRLED);
        aLet_5->setOnColor(AWMultiObject::Grey);
        aLet_5->setOffColor(AWMultiObject::Grey);
        lbTexto_5 = new QLabel(fr_1);
        lbTexto_5->setObjectName(QString::fromUtf8("lbTexto_5"));
        lbTexto_5->setGeometry(QRect(42, 105, 281, 16));
        lbTexto_5->setFont(font3);
        lbTexto_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_6 = new AWMultiObject(fr_1);
        aLet_6->setObjectName(QString::fromUtf8("aLet_6"));
        aLet_6->setGeometry(QRect(13, 117, 25, 31));
        aLet_6->setElementType(AWMultiObject::CIRLED);
        aLet_6->setOnColor(AWMultiObject::Grey);
        aLet_6->setOffColor(AWMultiObject::Grey);
        lbTexto_6 = new QLabel(fr_1);
        lbTexto_6->setObjectName(QString::fromUtf8("lbTexto_6"));
        lbTexto_6->setGeometry(QRect(42, 123, 281, 16));
        lbTexto_6->setFont(font3);
        lbTexto_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_7 = new QLabel(fr_1);
        lbTexto_7->setObjectName(QString::fromUtf8("lbTexto_7"));
        lbTexto_7->setGeometry(QRect(42, 141, 281, 16));
        lbTexto_7->setFont(font3);
        lbTexto_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_7 = new AWMultiObject(fr_1);
        aLet_7->setObjectName(QString::fromUtf8("aLet_7"));
        aLet_7->setGeometry(QRect(13, 135, 25, 31));
        aLet_7->setElementType(AWMultiObject::CIRLED);
        aLet_7->setOnColor(AWMultiObject::Grey);
        aLet_7->setOffColor(AWMultiObject::Grey);
        aLet_8 = new AWMultiObject(fr_1);
        aLet_8->setObjectName(QString::fromUtf8("aLet_8"));
        aLet_8->setGeometry(QRect(13, 153, 25, 31));
        aLet_8->setElementType(AWMultiObject::CIRLED);
        aLet_8->setOnColor(AWMultiObject::Grey);
        aLet_8->setOffColor(AWMultiObject::Grey);
        lbTexto_8 = new QLabel(fr_1);
        lbTexto_8->setObjectName(QString::fromUtf8("lbTexto_8"));
        lbTexto_8->setGeometry(QRect(42, 160, 281, 16));
        lbTexto_8->setFont(font3);
        lbTexto_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_9 = new AWMultiObject(fr_1);
        aLet_9->setObjectName(QString::fromUtf8("aLet_9"));
        aLet_9->setGeometry(QRect(13, 173, 25, 31));
        aLet_9->setElementType(AWMultiObject::CIRLED);
        aLet_9->setOnColor(AWMultiObject::Grey);
        aLet_9->setOffColor(AWMultiObject::Grey);
        lbTexto_9 = new QLabel(fr_1);
        lbTexto_9->setObjectName(QString::fromUtf8("lbTexto_9"));
        lbTexto_9->setGeometry(QRect(42, 180, 281, 16));
        lbTexto_9->setFont(font3);
        lbTexto_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_10 = new QLabel(fr_1);
        lbTexto_10->setObjectName(QString::fromUtf8("lbTexto_10"));
        lbTexto_10->setGeometry(QRect(42, 198, 281, 16));
        lbTexto_10->setFont(font3);
        lbTexto_10->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_10 = new AWMultiObject(fr_1);
        aLet_10->setObjectName(QString::fromUtf8("aLet_10"));
        aLet_10->setGeometry(QRect(13, 190, 25, 31));
        aLet_10->setElementType(AWMultiObject::CIRLED);
        aLet_10->setOnColor(AWMultiObject::Grey);
        aLet_10->setOffColor(AWMultiObject::Grey);
        lbTexto_11 = new QLabel(fr_1);
        lbTexto_11->setObjectName(QString::fromUtf8("lbTexto_11"));
        lbTexto_11->setGeometry(QRect(42, 235, 281, 16));
        lbTexto_11->setFont(font3);
        lbTexto_11->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_11 = new AWMultiObject(fr_1);
        aLet_11->setObjectName(QString::fromUtf8("aLet_11"));
        aLet_11->setGeometry(QRect(13, 228, 25, 31));
        aLet_11->setElementType(AWMultiObject::CIRLED);
        aLet_11->setOnColor(AWMultiObject::Grey);
        aLet_11->setOffColor(AWMultiObject::Grey);
        aLet_12 = new AWMultiObject(fr_1);
        aLet_12->setObjectName(QString::fromUtf8("aLet_12"));
        aLet_12->setGeometry(QRect(13, 246, 25, 31));
        aLet_12->setElementType(AWMultiObject::CIRLED);
        aLet_12->setOnColor(AWMultiObject::Grey);
        aLet_12->setOffColor(AWMultiObject::Grey);
        lbTexto_12 = new QLabel(fr_1);
        lbTexto_12->setObjectName(QString::fromUtf8("lbTexto_12"));
        lbTexto_12->setGeometry(QRect(42, 253, 281, 16));
        lbTexto_12->setFont(font3);
        lbTexto_12->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_13 = new QLabel(fr_1);
        lbTexto_13->setObjectName(QString::fromUtf8("lbTexto_13"));
        lbTexto_13->setGeometry(QRect(42, 270, 281, 16));
        lbTexto_13->setFont(font3);
        lbTexto_13->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_13 = new AWMultiObject(fr_1);
        aLet_13->setObjectName(QString::fromUtf8("aLet_13"));
        aLet_13->setGeometry(QRect(13, 264, 25, 31));
        aLet_13->setElementType(AWMultiObject::CIRLED);
        aLet_13->setOnColor(AWMultiObject::Grey);
        aLet_13->setOffColor(AWMultiObject::Grey);
        aLet_14 = new AWMultiObject(fr_1);
        aLet_14->setObjectName(QString::fromUtf8("aLet_14"));
        aLet_14->setGeometry(QRect(13, 283, 25, 31));
        aLet_14->setElementType(AWMultiObject::CIRLED);
        aLet_14->setOnColor(AWMultiObject::Grey);
        aLet_14->setOffColor(AWMultiObject::Grey);
        lbTexto_14 = new QLabel(fr_1);
        lbTexto_14->setObjectName(QString::fromUtf8("lbTexto_14"));
        lbTexto_14->setGeometry(QRect(42, 290, 281, 16));
        lbTexto_14->setFont(font3);
        lbTexto_14->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_15 = new QLabel(fr_1);
        lbTexto_15->setObjectName(QString::fromUtf8("lbTexto_15"));
        lbTexto_15->setGeometry(QRect(42, 308, 281, 16));
        lbTexto_15->setFont(font3);
        lbTexto_15->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_15 = new AWMultiObject(fr_1);
        aLet_15->setObjectName(QString::fromUtf8("aLet_15"));
        aLet_15->setGeometry(QRect(13, 318, 25, 31));
        aLet_15->setElementType(AWMultiObject::CIRLED);
        aLet_15->setOnColor(AWMultiObject::Grey);
        aLet_15->setOffColor(AWMultiObject::Grey);
        aLet_16 = new AWMultiObject(fr_1);
        aLet_16->setObjectName(QString::fromUtf8("aLet_16"));
        aLet_16->setGeometry(QRect(13, 336, 25, 31));
        aLet_16->setElementType(AWMultiObject::CIRLED);
        aLet_16->setOnColor(AWMultiObject::Grey);
        aLet_16->setOffColor(AWMultiObject::Grey);
        lbTexto_16 = new QLabel(fr_1);
        lbTexto_16->setObjectName(QString::fromUtf8("lbTexto_16"));
        lbTexto_16->setGeometry(QRect(42, 325, 281, 16));
        lbTexto_16->setFont(font3);
        lbTexto_16->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_17 = new AWMultiObject(fr_1);
        aLet_17->setObjectName(QString::fromUtf8("aLet_17"));
        aLet_17->setGeometry(QRect(13, 300, 25, 31));
        aLet_17->setElementType(AWMultiObject::CIRLED);
        aLet_17->setOnColor(AWMultiObject::Grey);
        aLet_17->setOffColor(AWMultiObject::Grey);
        lbTexto_17 = new QLabel(fr_1);
        lbTexto_17->setObjectName(QString::fromUtf8("lbTexto_17"));
        lbTexto_17->setGeometry(QRect(42, 343, 281, 16));
        lbTexto_17->setFont(font3);
        lbTexto_17->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_18 = new AWMultiObject(fr_1);
        aLet_18->setObjectName(QString::fromUtf8("aLet_18"));
        aLet_18->setGeometry(QRect(13, 375, 25, 31));
        aLet_18->setElementType(AWMultiObject::CIRLED);
        aLet_18->setOnColor(AWMultiObject::Grey);
        aLet_18->setOffColor(AWMultiObject::Grey);
        lbTexto_18 = new QLabel(fr_1);
        lbTexto_18->setObjectName(QString::fromUtf8("lbTexto_18"));
        lbTexto_18->setGeometry(QRect(42, 383, 281, 16));
        lbTexto_18->setFont(font3);
        lbTexto_18->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_19 = new AWMultiObject(fr_1);
        aLet_19->setObjectName(QString::fromUtf8("aLet_19"));
        aLet_19->setGeometry(QRect(13, 428, 25, 31));
        aLet_19->setElementType(AWMultiObject::CIRLED);
        aLet_19->setOnColor(AWMultiObject::Grey);
        aLet_19->setOffColor(AWMultiObject::Grey);
        lbTexto_19 = new QLabel(fr_1);
        lbTexto_19->setObjectName(QString::fromUtf8("lbTexto_19"));
        lbTexto_19->setGeometry(QRect(42, 400, 281, 16));
        lbTexto_19->setFont(font3);
        lbTexto_19->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_58 = new QLabel(fr_1);
        lbTexto_58->setObjectName(QString::fromUtf8("lbTexto_58"));
        lbTexto_58->setGeometry(QRect(42, 435, 281, 16));
        lbTexto_58->setFont(font3);
        lbTexto_58->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_58 = new AWMultiObject(fr_1);
        aLet_58->setObjectName(QString::fromUtf8("aLet_58"));
        aLet_58->setGeometry(QRect(13, 393, 25, 31));
        aLet_58->setElementType(AWMultiObject::CIRLED);
        aLet_58->setOnColor(AWMultiObject::Grey);
        aLet_58->setOffColor(AWMultiObject::Grey);
        lbTexto_59 = new QLabel(fr_1);
        lbTexto_59->setObjectName(QString::fromUtf8("lbTexto_59"));
        lbTexto_59->setGeometry(QRect(42, 454, 281, 16));
        lbTexto_59->setFont(font3);
        lbTexto_59->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_59 = new AWMultiObject(fr_1);
        aLet_59->setObjectName(QString::fromUtf8("aLet_59"));
        aLet_59->setGeometry(QRect(13, 446, 25, 31));
        aLet_59->setElementType(AWMultiObject::CIRLED);
        aLet_59->setOnColor(AWMultiObject::Grey);
        aLet_59->setOffColor(AWMultiObject::Grey);
        aLet_61 = new AWMultiObject(fr_1);
        aLet_61->setObjectName(QString::fromUtf8("aLet_61"));
        aLet_61->setGeometry(QRect(13, 467, 25, 31));
        aLet_61->setElementType(AWMultiObject::CIRLED);
        aLet_61->setOnColor(AWMultiObject::Grey);
        aLet_61->setOffColor(AWMultiObject::Grey);
        lbTexto_61 = new QLabel(fr_1);
        lbTexto_61->setObjectName(QString::fromUtf8("lbTexto_61"));
        lbTexto_61->setGeometry(QRect(42, 473, 281, 16));
        lbTexto_61->setFont(font3);
        lbTexto_61->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_2 = new QFrame(F5);
        fr_2->setObjectName(QString::fromUtf8("fr_2"));
        fr_2->setGeometry(QRect(343, 85, 341, 501));
        fr_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_2->setFrameShape(QFrame::StyledPanel);
        fr_2->setFrameShadow(QFrame::Plain);
        fr_2->setLineWidth(1);
        fr_2->setMidLineWidth(0);
        frTitulo_2 = new QFrame(fr_2);
        frTitulo_2->setObjectName(QString::fromUtf8("frTitulo_2"));
        frTitulo_2->setGeometry(QRect(3, 2, 334, 24));
        frTitulo_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_2->setFrameShape(QFrame::WinPanel);
        frTitulo_2->setFrameShadow(QFrame::Raised);
        frTitulo_2->setLineWidth(2);
        frTitulo_2->setMidLineWidth(0);
        lbTitulo_2 = new QLabel(fr_2);
        lbTitulo_2->setObjectName(QString::fromUtf8("lbTitulo_2"));
        lbTitulo_2->setGeometry(QRect(8, 2, 325, 20));
        lbTitulo_2->setFont(font4);
        lbTitulo_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_20 = new QLabel(fr_2);
        lbTexto_20->setObjectName(QString::fromUtf8("lbTexto_20"));
        lbTexto_20->setGeometry(QRect(42, 50, 281, 16));
        lbTexto_20->setFont(font3);
        lbTexto_20->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_20 = new AWMultiObject(fr_2);
        aLet_20->setObjectName(QString::fromUtf8("aLet_20"));
        aLet_20->setGeometry(QRect(13, 43, 25, 31));
        aLet_20->setElementType(AWMultiObject::CIRLED);
        aLet_20->setOnColor(AWMultiObject::Grey);
        aLet_20->setOffColor(AWMultiObject::Grey);
        lbTexto_21 = new QLabel(fr_2);
        lbTexto_21->setObjectName(QString::fromUtf8("lbTexto_21"));
        lbTexto_21->setGeometry(QRect(42, 70, 281, 16));
        lbTexto_21->setFont(font3);
        lbTexto_21->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_21 = new AWMultiObject(fr_2);
        aLet_21->setObjectName(QString::fromUtf8("aLet_21"));
        aLet_21->setGeometry(QRect(13, 62, 25, 31));
        aLet_21->setElementType(AWMultiObject::CIRLED);
        aLet_21->setOnColor(AWMultiObject::Grey);
        aLet_21->setOffColor(AWMultiObject::Grey);
        lbTexto_22 = new QLabel(fr_2);
        lbTexto_22->setObjectName(QString::fromUtf8("lbTexto_22"));
        lbTexto_22->setGeometry(QRect(42, 88, 281, 16));
        lbTexto_22->setFont(font3);
        lbTexto_22->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_22 = new AWMultiObject(fr_2);
        aLet_22->setObjectName(QString::fromUtf8("aLet_22"));
        aLet_22->setGeometry(QRect(13, 80, 25, 31));
        aLet_22->setElementType(AWMultiObject::CIRLED);
        aLet_22->setOnColor(AWMultiObject::Grey);
        aLet_22->setOffColor(AWMultiObject::Grey);
        lbTexto_23 = new QLabel(fr_2);
        lbTexto_23->setObjectName(QString::fromUtf8("lbTexto_23"));
        lbTexto_23->setGeometry(QRect(42, 106, 281, 16));
        lbTexto_23->setFont(font3);
        lbTexto_23->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_23 = new AWMultiObject(fr_2);
        aLet_23->setObjectName(QString::fromUtf8("aLet_23"));
        aLet_23->setGeometry(QRect(13, 99, 25, 31));
        aLet_23->setElementType(AWMultiObject::CIRLED);
        aLet_23->setOnColor(AWMultiObject::Grey);
        aLet_23->setOffColor(AWMultiObject::Grey);
        aLet_24 = new AWMultiObject(fr_2);
        aLet_24->setObjectName(QString::fromUtf8("aLet_24"));
        aLet_24->setGeometry(QRect(13, 118, 25, 31));
        aLet_24->setElementType(AWMultiObject::CIRLED);
        aLet_24->setOnColor(AWMultiObject::Grey);
        aLet_24->setOffColor(AWMultiObject::Grey);
        lbTexto_24 = new QLabel(fr_2);
        lbTexto_24->setObjectName(QString::fromUtf8("lbTexto_24"));
        lbTexto_24->setGeometry(QRect(42, 125, 281, 16));
        lbTexto_24->setFont(font3);
        lbTexto_24->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_25 = new AWMultiObject(fr_2);
        aLet_25->setObjectName(QString::fromUtf8("aLet_25"));
        aLet_25->setGeometry(QRect(13, 136, 25, 31));
        aLet_25->setElementType(AWMultiObject::CIRLED);
        aLet_25->setOnColor(AWMultiObject::Grey);
        aLet_25->setOffColor(AWMultiObject::Grey);
        lbTexto_25 = new QLabel(fr_2);
        lbTexto_25->setObjectName(QString::fromUtf8("lbTexto_25"));
        lbTexto_25->setGeometry(QRect(42, 144, 281, 16));
        lbTexto_25->setFont(font3);
        lbTexto_25->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_26 = new QLabel(fr_2);
        lbTexto_26->setObjectName(QString::fromUtf8("lbTexto_26"));
        lbTexto_26->setGeometry(QRect(42, 160, 281, 16));
        lbTexto_26->setFont(font3);
        lbTexto_26->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_26 = new AWMultiObject(fr_2);
        aLet_26->setObjectName(QString::fromUtf8("aLet_26"));
        aLet_26->setGeometry(QRect(13, 155, 25, 31));
        aLet_26->setElementType(AWMultiObject::CIRLED);
        aLet_26->setOnColor(AWMultiObject::Grey);
        aLet_26->setOffColor(AWMultiObject::Grey);
        aLet_27 = new AWMultiObject(fr_2);
        aLet_27->setObjectName(QString::fromUtf8("aLet_27"));
        aLet_27->setGeometry(QRect(13, 174, 25, 31));
        aLet_27->setElementType(AWMultiObject::CIRLED);
        aLet_27->setOnColor(AWMultiObject::Grey);
        aLet_27->setOffColor(AWMultiObject::Grey);
        lbTexto_27 = new QLabel(fr_2);
        lbTexto_27->setObjectName(QString::fromUtf8("lbTexto_27"));
        lbTexto_27->setGeometry(QRect(42, 180, 281, 16));
        lbTexto_27->setFont(font3);
        lbTexto_27->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_28 = new AWMultiObject(fr_2);
        aLet_28->setObjectName(QString::fromUtf8("aLet_28"));
        aLet_28->setGeometry(QRect(13, 192, 25, 31));
        aLet_28->setElementType(AWMultiObject::CIRLED);
        aLet_28->setOnColor(AWMultiObject::Grey);
        aLet_28->setOffColor(AWMultiObject::Grey);
        lbTexto_28 = new QLabel(fr_2);
        lbTexto_28->setObjectName(QString::fromUtf8("lbTexto_28"));
        lbTexto_28->setGeometry(QRect(42, 198, 281, 16));
        lbTexto_28->setFont(font3);
        lbTexto_28->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_29 = new QLabel(fr_2);
        lbTexto_29->setObjectName(QString::fromUtf8("lbTexto_29"));
        lbTexto_29->setGeometry(QRect(42, 217, 281, 16));
        lbTexto_29->setFont(font3);
        lbTexto_29->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_29 = new AWMultiObject(fr_2);
        aLet_29->setObjectName(QString::fromUtf8("aLet_29"));
        aLet_29->setGeometry(QRect(13, 210, 25, 31));
        aLet_29->setElementType(AWMultiObject::CIRLED);
        aLet_29->setOnColor(AWMultiObject::Grey);
        aLet_29->setOffColor(AWMultiObject::Grey);
        lbTexto_30 = new QLabel(fr_2);
        lbTexto_30->setObjectName(QString::fromUtf8("lbTexto_30"));
        lbTexto_30->setGeometry(QRect(42, 234, 281, 16));
        lbTexto_30->setFont(font3);
        lbTexto_30->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_30 = new AWMultiObject(fr_2);
        aLet_30->setObjectName(QString::fromUtf8("aLet_30"));
        aLet_30->setGeometry(QRect(13, 228, 25, 31));
        aLet_30->setElementType(AWMultiObject::CIRLED);
        aLet_30->setOnColor(AWMultiObject::Grey);
        aLet_30->setOffColor(AWMultiObject::Grey);
        aLet_31 = new AWMultiObject(fr_2);
        aLet_31->setObjectName(QString::fromUtf8("aLet_31"));
        aLet_31->setGeometry(QRect(13, 246, 25, 31));
        aLet_31->setElementType(AWMultiObject::CIRLED);
        aLet_31->setOnColor(AWMultiObject::Grey);
        aLet_31->setOffColor(AWMultiObject::Grey);
        lbTexto_31 = new QLabel(fr_2);
        lbTexto_31->setObjectName(QString::fromUtf8("lbTexto_31"));
        lbTexto_31->setGeometry(QRect(42, 253, 281, 16));
        lbTexto_31->setFont(font3);
        lbTexto_31->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_32 = new QLabel(fr_2);
        lbTexto_32->setObjectName(QString::fromUtf8("lbTexto_32"));
        lbTexto_32->setGeometry(QRect(42, 272, 281, 16));
        lbTexto_32->setFont(font3);
        lbTexto_32->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_32 = new AWMultiObject(fr_2);
        aLet_32->setObjectName(QString::fromUtf8("aLet_32"));
        aLet_32->setGeometry(QRect(13, 265, 25, 31));
        aLet_32->setElementType(AWMultiObject::CIRLED);
        aLet_32->setOnColor(AWMultiObject::Grey);
        aLet_32->setOffColor(AWMultiObject::Grey);
        aLet_33 = new AWMultiObject(fr_2);
        aLet_33->setObjectName(QString::fromUtf8("aLet_33"));
        aLet_33->setGeometry(QRect(13, 283, 25, 31));
        aLet_33->setElementType(AWMultiObject::CIRLED);
        aLet_33->setOnColor(AWMultiObject::Grey);
        aLet_33->setOffColor(AWMultiObject::Grey);
        lbTexto_33 = new QLabel(fr_2);
        lbTexto_33->setObjectName(QString::fromUtf8("lbTexto_33"));
        lbTexto_33->setGeometry(QRect(42, 290, 281, 16));
        lbTexto_33->setFont(font3);
        lbTexto_33->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_34 = new QLabel(fr_2);
        lbTexto_34->setObjectName(QString::fromUtf8("lbTexto_34"));
        lbTexto_34->setGeometry(QRect(42, 308, 281, 16));
        lbTexto_34->setFont(font3);
        lbTexto_34->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_34 = new AWMultiObject(fr_2);
        aLet_34->setObjectName(QString::fromUtf8("aLet_34"));
        aLet_34->setGeometry(QRect(13, 300, 25, 31));
        aLet_34->setElementType(AWMultiObject::CIRLED);
        aLet_34->setOnColor(AWMultiObject::Grey);
        aLet_34->setOffColor(AWMultiObject::Grey);
        aLet_35 = new AWMultiObject(fr_2);
        aLet_35->setObjectName(QString::fromUtf8("aLet_35"));
        aLet_35->setGeometry(QRect(13, 338, 25, 31));
        aLet_35->setElementType(AWMultiObject::CIRLED);
        aLet_35->setOnColor(AWMultiObject::Grey);
        aLet_35->setOffColor(AWMultiObject::Grey);
        lbTexto_35 = new QLabel(fr_2);
        lbTexto_35->setObjectName(QString::fromUtf8("lbTexto_35"));
        lbTexto_35->setGeometry(QRect(42, 327, 281, 16));
        lbTexto_35->setFont(font3);
        lbTexto_35->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_36 = new AWMultiObject(fr_2);
        aLet_36->setObjectName(QString::fromUtf8("aLet_36"));
        aLet_36->setGeometry(QRect(13, 320, 25, 31));
        aLet_36->setElementType(AWMultiObject::CIRLED);
        aLet_36->setOnColor(AWMultiObject::Grey);
        aLet_36->setOffColor(AWMultiObject::Grey);
        lbTexto_36 = new QLabel(fr_2);
        lbTexto_36->setObjectName(QString::fromUtf8("lbTexto_36"));
        lbTexto_36->setGeometry(QRect(42, 345, 281, 16));
        lbTexto_36->setFont(font3);
        lbTexto_36->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_37 = new AWMultiObject(fr_2);
        aLet_37->setObjectName(QString::fromUtf8("aLet_37"));
        aLet_37->setGeometry(QRect(13, 358, 25, 31));
        aLet_37->setElementType(AWMultiObject::CIRLED);
        aLet_37->setOnColor(AWMultiObject::Grey);
        aLet_37->setOffColor(AWMultiObject::Grey);
        lbTexto_37 = new QLabel(fr_2);
        lbTexto_37->setObjectName(QString::fromUtf8("lbTexto_37"));
        lbTexto_37->setGeometry(QRect(42, 364, 281, 16));
        lbTexto_37->setFont(font3);
        lbTexto_37->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_38 = new AWMultiObject(fr_2);
        aLet_38->setObjectName(QString::fromUtf8("aLet_38"));
        aLet_38->setGeometry(QRect(13, 393, 25, 31));
        aLet_38->setElementType(AWMultiObject::CIRLED);
        aLet_38->setOnColor(AWMultiObject::Grey);
        aLet_38->setOffColor(AWMultiObject::Grey);
        lbTexto_38 = new QLabel(fr_2);
        lbTexto_38->setObjectName(QString::fromUtf8("lbTexto_38"));
        lbTexto_38->setGeometry(QRect(42, 382, 281, 16));
        lbTexto_38->setFont(font3);
        lbTexto_38->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_60 = new QLabel(fr_2);
        lbTexto_60->setObjectName(QString::fromUtf8("lbTexto_60"));
        lbTexto_60->setGeometry(QRect(42, 400, 281, 16));
        lbTexto_60->setFont(font3);
        lbTexto_60->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_60 = new AWMultiObject(fr_2);
        aLet_60->setObjectName(QString::fromUtf8("aLet_60"));
        aLet_60->setGeometry(QRect(13, 375, 25, 31));
        aLet_60->setElementType(AWMultiObject::CIRLED);
        aLet_60->setOnColor(AWMultiObject::Grey);
        aLet_60->setOffColor(AWMultiObject::Grey);
        fr_3 = new QFrame(F5);
        fr_3->setObjectName(QString::fromUtf8("fr_3"));
        fr_3->setGeometry(QRect(684, 85, 341, 501));
        fr_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        fr_3->setFrameShape(QFrame::StyledPanel);
        fr_3->setFrameShadow(QFrame::Plain);
        fr_3->setLineWidth(1);
        fr_3->setMidLineWidth(0);
        frTitulo_3 = new QFrame(fr_3);
        frTitulo_3->setObjectName(QString::fromUtf8("frTitulo_3"));
        frTitulo_3->setGeometry(QRect(3, 2, 335, 24));
        frTitulo_3->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frTitulo_3->setFrameShape(QFrame::WinPanel);
        frTitulo_3->setFrameShadow(QFrame::Raised);
        frTitulo_3->setLineWidth(2);
        frTitulo_3->setMidLineWidth(0);
        lbTitulo_3 = new QLabel(fr_3);
        lbTitulo_3->setObjectName(QString::fromUtf8("lbTitulo_3"));
        lbTitulo_3->setGeometry(QRect(8, 2, 325, 20));
        lbTitulo_3->setFont(font4);
        lbTitulo_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_39 = new QLabel(fr_3);
        lbTexto_39->setObjectName(QString::fromUtf8("lbTexto_39"));
        lbTexto_39->setGeometry(QRect(42, 33, 281, 16));
        lbTexto_39->setFont(font3);
        lbTexto_39->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_39 = new AWMultiObject(fr_3);
        aLet_39->setObjectName(QString::fromUtf8("aLet_39"));
        aLet_39->setGeometry(QRect(13, 26, 25, 31));
        aLet_39->setElementType(AWMultiObject::CIRLED);
        aLet_39->setOnColor(AWMultiObject::Grey);
        aLet_39->setOffColor(AWMultiObject::Grey);
        lbTexto_40 = new QLabel(fr_3);
        lbTexto_40->setObjectName(QString::fromUtf8("lbTexto_40"));
        lbTexto_40->setGeometry(QRect(42, 50, 281, 16));
        lbTexto_40->setFont(font3);
        lbTexto_40->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_40 = new AWMultiObject(fr_3);
        aLet_40->setObjectName(QString::fromUtf8("aLet_40"));
        aLet_40->setGeometry(QRect(13, 44, 25, 31));
        aLet_40->setElementType(AWMultiObject::CIRLED);
        aLet_40->setOnColor(AWMultiObject::Grey);
        aLet_40->setOffColor(AWMultiObject::Grey);
        lbTexto_41 = new QLabel(fr_3);
        lbTexto_41->setObjectName(QString::fromUtf8("lbTexto_41"));
        lbTexto_41->setGeometry(QRect(42, 68, 281, 16));
        lbTexto_41->setFont(font3);
        lbTexto_41->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_41 = new AWMultiObject(fr_3);
        aLet_41->setObjectName(QString::fromUtf8("aLet_41"));
        aLet_41->setGeometry(QRect(13, 63, 25, 31));
        aLet_41->setElementType(AWMultiObject::CIRLED);
        aLet_41->setOnColor(AWMultiObject::Grey);
        aLet_41->setOffColor(AWMultiObject::Grey);
        lbTexto_42 = new QLabel(fr_3);
        lbTexto_42->setObjectName(QString::fromUtf8("lbTexto_42"));
        lbTexto_42->setGeometry(QRect(42, 87, 281, 16));
        lbTexto_42->setFont(font3);
        lbTexto_42->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_42 = new AWMultiObject(fr_3);
        aLet_42->setObjectName(QString::fromUtf8("aLet_42"));
        aLet_42->setGeometry(QRect(13, 80, 25, 31));
        aLet_42->setElementType(AWMultiObject::CIRLED);
        aLet_42->setOnColor(AWMultiObject::Grey);
        aLet_42->setOffColor(AWMultiObject::Grey);
        aLet_43 = new AWMultiObject(fr_3);
        aLet_43->setObjectName(QString::fromUtf8("aLet_43"));
        aLet_43->setGeometry(QRect(13, 98, 25, 31));
        aLet_43->setElementType(AWMultiObject::CIRLED);
        aLet_43->setOnColor(AWMultiObject::Grey);
        aLet_43->setOffColor(AWMultiObject::Grey);
        lbTexto_43 = new QLabel(fr_3);
        lbTexto_43->setObjectName(QString::fromUtf8("lbTexto_43"));
        lbTexto_43->setGeometry(QRect(42, 105, 281, 16));
        lbTexto_43->setFont(font3);
        lbTexto_43->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_44 = new AWMultiObject(fr_3);
        aLet_44->setObjectName(QString::fromUtf8("aLet_44"));
        aLet_44->setGeometry(QRect(13, 118, 25, 31));
        aLet_44->setElementType(AWMultiObject::CIRLED);
        aLet_44->setOnColor(AWMultiObject::Grey);
        aLet_44->setOffColor(AWMultiObject::Grey);
        lbTexto_44 = new QLabel(fr_3);
        lbTexto_44->setObjectName(QString::fromUtf8("lbTexto_44"));
        lbTexto_44->setGeometry(QRect(42, 125, 281, 16));
        lbTexto_44->setFont(font3);
        lbTexto_44->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_45 = new QLabel(fr_3);
        lbTexto_45->setObjectName(QString::fromUtf8("lbTexto_45"));
        lbTexto_45->setGeometry(QRect(42, 143, 281, 16));
        lbTexto_45->setFont(font3);
        lbTexto_45->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_45 = new AWMultiObject(fr_3);
        aLet_45->setObjectName(QString::fromUtf8("aLet_45"));
        aLet_45->setGeometry(QRect(13, 135, 25, 31));
        aLet_45->setElementType(AWMultiObject::CIRLED);
        aLet_45->setOnColor(AWMultiObject::Grey);
        aLet_45->setOffColor(AWMultiObject::Grey);
        aLet_46 = new AWMultiObject(fr_3);
        aLet_46->setObjectName(QString::fromUtf8("aLet_46"));
        aLet_46->setGeometry(QRect(13, 154, 25, 31));
        aLet_46->setElementType(AWMultiObject::CIRLED);
        aLet_46->setOnColor(AWMultiObject::Grey);
        aLet_46->setOffColor(AWMultiObject::Grey);
        lbTexto_46 = new QLabel(fr_3);
        lbTexto_46->setObjectName(QString::fromUtf8("lbTexto_46"));
        lbTexto_46->setGeometry(QRect(42, 161, 281, 16));
        lbTexto_46->setFont(font3);
        lbTexto_46->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_47 = new AWMultiObject(fr_3);
        aLet_47->setObjectName(QString::fromUtf8("aLet_47"));
        aLet_47->setGeometry(QRect(13, 173, 25, 31));
        aLet_47->setElementType(AWMultiObject::CIRLED);
        aLet_47->setOnColor(AWMultiObject::Grey);
        aLet_47->setOffColor(AWMultiObject::Grey);
        lbTexto_47 = new QLabel(fr_3);
        lbTexto_47->setObjectName(QString::fromUtf8("lbTexto_47"));
        lbTexto_47->setGeometry(QRect(42, 180, 281, 16));
        lbTexto_47->setFont(font3);
        lbTexto_47->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_48 = new QLabel(fr_3);
        lbTexto_48->setObjectName(QString::fromUtf8("lbTexto_48"));
        lbTexto_48->setGeometry(QRect(42, 198, 281, 16));
        lbTexto_48->setFont(font3);
        lbTexto_48->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_48 = new AWMultiObject(fr_3);
        aLet_48->setObjectName(QString::fromUtf8("aLet_48"));
        aLet_48->setGeometry(QRect(13, 190, 25, 31));
        aLet_48->setElementType(AWMultiObject::CIRLED);
        aLet_48->setOnColor(AWMultiObject::Grey);
        aLet_48->setOffColor(AWMultiObject::Grey);
        lbTexto_49 = new QLabel(fr_3);
        lbTexto_49->setObjectName(QString::fromUtf8("lbTexto_49"));
        lbTexto_49->setGeometry(QRect(42, 217, 281, 16));
        lbTexto_49->setFont(font3);
        lbTexto_49->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_49 = new AWMultiObject(fr_3);
        aLet_49->setObjectName(QString::fromUtf8("aLet_49"));
        aLet_49->setGeometry(QRect(13, 209, 25, 31));
        aLet_49->setElementType(AWMultiObject::CIRLED);
        aLet_49->setOnColor(AWMultiObject::Grey);
        aLet_49->setOffColor(AWMultiObject::Grey);
        aLet_50 = new AWMultiObject(fr_3);
        aLet_50->setObjectName(QString::fromUtf8("aLet_50"));
        aLet_50->setGeometry(QRect(13, 227, 25, 31));
        aLet_50->setElementType(AWMultiObject::CIRLED);
        aLet_50->setOnColor(AWMultiObject::Grey);
        aLet_50->setOffColor(AWMultiObject::Grey);
        lbTexto_50 = new QLabel(fr_3);
        lbTexto_50->setObjectName(QString::fromUtf8("lbTexto_50"));
        lbTexto_50->setGeometry(QRect(42, 234, 281, 16));
        lbTexto_50->setFont(font3);
        lbTexto_50->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_51 = new QLabel(fr_3);
        lbTexto_51->setObjectName(QString::fromUtf8("lbTexto_51"));
        lbTexto_51->setGeometry(QRect(42, 252, 281, 16));
        lbTexto_51->setFont(font3);
        lbTexto_51->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_51 = new AWMultiObject(fr_3);
        aLet_51->setObjectName(QString::fromUtf8("aLet_51"));
        aLet_51->setGeometry(QRect(13, 245, 25, 31));
        aLet_51->setElementType(AWMultiObject::CIRLED);
        aLet_51->setOnColor(AWMultiObject::Grey);
        aLet_51->setOffColor(AWMultiObject::Grey);
        aLet_52 = new AWMultiObject(fr_3);
        aLet_52->setObjectName(QString::fromUtf8("aLet_52"));
        aLet_52->setGeometry(QRect(13, 263, 25, 31));
        aLet_52->setElementType(AWMultiObject::CIRLED);
        aLet_52->setOnColor(AWMultiObject::Grey);
        aLet_52->setOffColor(AWMultiObject::Grey);
        lbTexto_52 = new QLabel(fr_3);
        lbTexto_52->setObjectName(QString::fromUtf8("lbTexto_52"));
        lbTexto_52->setGeometry(QRect(42, 271, 281, 16));
        lbTexto_52->setFont(font3);
        lbTexto_52->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_53 = new QLabel(fr_3);
        lbTexto_53->setObjectName(QString::fromUtf8("lbTexto_53"));
        lbTexto_53->setGeometry(QRect(42, 289, 281, 16));
        lbTexto_53->setFont(font3);
        lbTexto_53->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_53 = new AWMultiObject(fr_3);
        aLet_53->setObjectName(QString::fromUtf8("aLet_53"));
        aLet_53->setGeometry(QRect(13, 282, 25, 31));
        aLet_53->setElementType(AWMultiObject::CIRLED);
        aLet_53->setOnColor(AWMultiObject::Grey);
        aLet_53->setOffColor(AWMultiObject::Grey);
        aLet_54 = new AWMultiObject(fr_3);
        aLet_54->setObjectName(QString::fromUtf8("aLet_54"));
        aLet_54->setGeometry(QRect(13, 319, 25, 31));
        aLet_54->setElementType(AWMultiObject::CIRLED);
        aLet_54->setOnColor(AWMultiObject::Grey);
        aLet_54->setOffColor(AWMultiObject::Grey);
        lbTexto_54 = new QLabel(fr_3);
        lbTexto_54->setObjectName(QString::fromUtf8("lbTexto_54"));
        lbTexto_54->setGeometry(QRect(42, 307, 281, 16));
        lbTexto_54->setFont(font3);
        lbTexto_54->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_55 = new AWMultiObject(fr_3);
        aLet_55->setObjectName(QString::fromUtf8("aLet_55"));
        aLet_55->setGeometry(QRect(13, 301, 25, 31));
        aLet_55->setElementType(AWMultiObject::CIRLED);
        aLet_55->setOnColor(AWMultiObject::Grey);
        aLet_55->setOffColor(AWMultiObject::Grey);
        lbTexto_55 = new QLabel(fr_3);
        lbTexto_55->setObjectName(QString::fromUtf8("lbTexto_55"));
        lbTexto_55->setGeometry(QRect(42, 326, 281, 16));
        lbTexto_55->setFont(font3);
        lbTexto_55->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_56 = new AWMultiObject(fr_3);
        aLet_56->setObjectName(QString::fromUtf8("aLet_56"));
        aLet_56->setGeometry(QRect(13, 337, 25, 31));
        aLet_56->setElementType(AWMultiObject::CIRLED);
        aLet_56->setOnColor(AWMultiObject::Grey);
        aLet_56->setOffColor(AWMultiObject::Grey);
        lbTexto_56 = new QLabel(fr_3);
        lbTexto_56->setObjectName(QString::fromUtf8("lbTexto_56"));
        lbTexto_56->setGeometry(QRect(42, 344, 281, 16));
        lbTexto_56->setFont(font3);
        lbTexto_56->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_57 = new AWMultiObject(fr_3);
        aLet_57->setObjectName(QString::fromUtf8("aLet_57"));
        aLet_57->setGeometry(QRect(13, 373, 25, 31));
        aLet_57->setElementType(AWMultiObject::CIRLED);
        aLet_57->setOnColor(AWMultiObject::Grey);
        aLet_57->setOffColor(AWMultiObject::Grey);
        lbTexto_57 = new QLabel(fr_3);
        lbTexto_57->setObjectName(QString::fromUtf8("lbTexto_57"));
        lbTexto_57->setGeometry(QRect(42, 363, 281, 16));
        lbTexto_57->setFont(font3);
        lbTexto_57->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTexto_62 = new QLabel(fr_3);
        lbTexto_62->setObjectName(QString::fromUtf8("lbTexto_62"));
        lbTexto_62->setGeometry(QRect(42, 382, 281, 16));
        lbTexto_62->setFont(font3);
        lbTexto_62->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        aLet_62 = new AWMultiObject(fr_3);
        aLet_62->setObjectName(QString::fromUtf8("aLet_62"));
        aLet_62->setGeometry(QRect(13, 355, 25, 31));
        aLet_62->setElementType(AWMultiObject::CIRLED);
        aLet_62->setOnColor(AWMultiObject::Grey);
        aLet_62->setOffColor(AWMultiObject::Grey);
        aLet_63 = new AWMultiObject(fr_3);
        aLet_63->setObjectName(QString::fromUtf8("aLet_63"));
        aLet_63->setGeometry(QRect(13, 393, 25, 31));
        aLet_63->setElementType(AWMultiObject::CIRLED);
        aLet_63->setOnColor(AWMultiObject::Grey);
        aLet_63->setOffColor(AWMultiObject::Grey);
        lbTexto_63 = new QLabel(fr_3);
        lbTexto_63->setObjectName(QString::fromUtf8("lbTexto_63"));
        lbTexto_63->setGeometry(QRect(49, 400, 281, 16));
        lbTexto_63->setFont(font3);
        lbTexto_63->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbIMGFondo->raise();
        frTitulo_9->raise();
        lbAux_2->raise();
        lbApagado->raise();
        lbAux_1->raise();
        lbUnit3->raise();
        frAux_2->raise();
        lbValDES->raise();
        btnIMPPant->raise();
        frAux->raise();
        lbValNUM->raise();
        fr_1->raise();
        fr_2->raise();
        fr_3->raise();

        retranslateUi(F5);

        QMetaObject::connectSlotsByName(F5);
    } // setupUi

    void retranslateUi(QWidget *F5)
    {
        F5->setWindowTitle(QApplication::translate("F5", "Form", 0, QApplication::UnicodeUTF8));
        lbIMGFondo->setText(QString());
        lbAux_2->setText(QApplication::translate("F5", "Descripci\303\263n", 0, QApplication::UnicodeUTF8));
        lbApagado->setText(QApplication::translate("F5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">PRIMER</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">APAGADO</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbAux_1->setText(QApplication::translate("F5", "N\302\272", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("F5", "    UNIT3", 0, QApplication::UnicodeUTF8));
        lbValDES->setText(QApplication::translate("F5", "SIN APAGADOS", 0, QApplication::UnicodeUTF8));
        lbValNUM->setText(QApplication::translate("F5", "0", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("F5", "IMP PANT", 0, QApplication::UnicodeUTF8));
        lbTitulo_1->setText(QApplication::translate("F5", "APAGADO DE EMERGENCIA SIN MOTOR (2\302\272 ANILLO)", 0, QApplication::UnicodeUTF8));
        lbTexto_1->setText(QApplication::translate("F5", "SEC:A1_A04-ACT - TARJETA FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_2->setText(QApplication::translate("F5", "SEC:A1_A06-ACT - TARJETA FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_3->setText(QApplication::translate("F5", "SEC:A1_A07-ACT - TARJETA FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_4->setText(QApplication::translate("F5", "TARJETA MICRONET 8 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_5->setText(QApplication::translate("F5", "TARJETA MICRONET 9 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_6->setText(QApplication::translate("F5", "TARJETA MICRONET 10 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_7->setText(QApplication::translate("F5", "TARJ MICRONET 12 GRP 1 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_8->setText(QApplication::translate("F5", "TARJ MICRONET 12 GRP FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_9->setText(QApplication::translate("F5", "TARJ MICRONET 12 GRP 3 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_10->setText(QApplication::translate("F5", "TARJETA MICRONET 12 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_11->setText(QApplication::translate("F5", "SEC:GEN TANQ CIERR GRAD NO SE LLEN\303\223 (DE)", 0, QApplication::UnicodeUTF8));
        lbTexto_12->setText(QApplication::translate("F5", "SEC:GEN TANQ CIERR GRAD NO SE LLEN\303\223 (NDE)", 0, QApplication::UnicodeUTF8));
        lbTexto_13->setText(QApplication::translate("F5", "SEC:N25 NO LLEG\303\223 A 1700", 0, QApplication::UnicodeUTF8));
        lbTexto_14->setText(QApplication::translate("F5", "SEC:ARRANC BOMBA PAT\303\215N HID PRES SUMI BAJ", 0, QApplication::UnicodeUTF8));
        lbTexto_15->setText(QApplication::translate("F5", "SEC:ARRANC BOMBA PAT\303\215N HID VAC P/D ALT A", 0, QApplication::UnicodeUTF8));
        lbTexto_16->setText(QApplication::translate("F5", "SEC:LSLL-1601 ARRANQUE PAT\303\215N RES ACEITE H", 0, QApplication::UnicodeUTF8));
        lbTexto_17->setText(QApplication::translate("F5", "SEC:SIST LUB GEN FALL\303\223 VERIFICACI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_18->setText(QApplication::translate("F5", "SEC:ALTO D/EMERGENCIA HMI", 0, QApplication::UnicodeUTF8));
        lbTexto_19->setText(QApplication::translate("F5", "SEC:REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_58->setText(QApplication::translate("F5", "SEC:PANT ENTR BOQ CAMP AL AL P/D", 0, QApplication::UnicodeUTF8));
        lbTexto_59->setText(QApplication::translate("F5", "SEC:REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_61->setText(QApplication::translate("F5", "SEC:PDSL6407 BAJA DURANTE ARRANQUE", 0, QApplication::UnicodeUTF8));
        lbTitulo_2->setText(QApplication::translate("F5", "APAGADO DE EMERGENCIA SIN MOTOR (2\302\272 ANILLO)", 0, QApplication::UnicodeUTF8));
        lbTexto_20->setText(QApplication::translate("F5", "SEC:ARRANCADOR FALLA DE ACC A 1700", 0, QApplication::UnicodeUTF8));
        lbTexto_21->setText(QApplication::translate("F5", "SEC:SDNIV EX INF CUARTO TURB", 0, QApplication::UnicodeUTF8));
        lbTexto_22->setText(QApplication::translate("F5", "SEC:DSPUES D/PURG CALDERA XN25 MENOS 170", 0, QApplication::UnicodeUTF8));
        lbTexto_23->setText(QApplication::translate("F5", "SEC:CIERRE COMBUS - CAMBIO CR\303\215TICO", 0, QApplication::UnicodeUTF8));
        lbTexto_24->setText(QApplication::translate("F5", "SEC:XN25R FL ACC MENOS 6407", 0, QApplication::UnicodeUTF8));
        lbTexto_25->setText(QApplication::translate("F5", "SEC:CIERRE CAMINO CR\303\215TICO", 0, QApplication::UnicodeUTF8));
        lbTexto_26->setText(QApplication::translate("F5", "SEC:SOBRE VEL EXTERNA TURBINA", 0, QApplication::UnicodeUTF8));
        lbTexto_27->setText(QApplication::translate("F5", "SEC:REFACCI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_28->setText(QApplication::translate("F5", "SEC:A2_A12_GR1 - LON GRP1 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_29->setText(QApplication::translate("F5", "SEC:A2_A12_GR2 - LON GRP1 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_30->setText(QApplication::translate("F5", "SEC:A2_A12_GR3 - LON GRP1 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_31->setText(QApplication::translate("F5", "SEC:N1N1 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_32->setText(QApplication::translate("F5", "SEC:TE-6036 ALTO ALTO", 0, QApplication::UnicodeUTF8));
        lbTexto_33->setText(QApplication::translate("F5", "SEC:TE-6035 ALTO ALTO", 0, QApplication::UnicodeUTF8));
        lbTexto_34->setText(QApplication::translate("F5", "SEC:N2N4 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_35->setText(QApplication::translate("F5", "SEC:P\303\211RDIDA DE MCC FUENTE PODER", 0, QApplication::UnicodeUTF8));
        lbTexto_36->setText(QApplication::translate("F5", "SEC:BOMBAS AC LUB GEN FALLO VERIFICACI\303\223N", 0, QApplication::UnicodeUTF8));
        lbTexto_37->setText(QApplication::translate("F5", "SEC:TEMP COJINETE GEN (NDE)", 0, QApplication::UnicodeUTF8));
        lbTexto_38->setText(QApplication::translate("F5", "SEC:ENTR BOMB ACEI ALJIB GEN PRES BAJ BA", 0, QApplication::UnicodeUTF8));
        lbTexto_60->setText(QApplication::translate("F5", "SEC: TEMP COJINETE GEN (DE)", 0, QApplication::UnicodeUTF8));
        lbTitulo_3->setText(QApplication::translate("F5", "APAGADO DE EMERGENCIA SIN MOTOR (2\302\272 ANILLO)", 0, QApplication::UnicodeUTF8));
        lbTexto_39->setText(QApplication::translate("F5", "SEC:SUMI ACEIT LUB GEN PRES CIERR BAJ BA", 0, QApplication::UnicodeUTF8));
        lbTexto_40->setText(QApplication::translate("F5", "SEC:CIERRE EX INF CUARTO GEN", 0, QApplication::UnicodeUTF8));
        lbTexto_41->setText(QApplication::translate("F5", "SEC: LT-6045 BAJO BAJO NIVEL", 0, QApplication::UnicodeUTF8));
        lbTexto_42->setText(QApplication::translate("F5", "SEC:N1N31 NODO DE Al FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_43->setText(QApplication::translate("F5", "SEC:N2N12 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_44->setText(QApplication::translate("F5", "SEC:N2N32 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_45->setText(QApplication::translate("F5", "SEC:N3N39 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_46->setText(QApplication::translate("F5", "SEC:N3N40 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_47->setText(QApplication::translate("F5", "SEC:N3N41 FALLA NODO", 0, QApplication::UnicodeUTF8));
        lbTexto_48->setText(QApplication::translate("F5", "SEC:MONITOR FUEGO/GAS CIERRE", 0, QApplication::UnicodeUTF8));
        lbTexto_49->setText(QApplication::translate("F5", "SEC:ALTO D/EMERGENCIA LOCAL", 0, QApplication::UnicodeUTF8));
        lbTexto_50->setText(QApplication::translate("F5", "SEC:ALTO D/EMERGENCIA REMOTO", 0, QApplication::UnicodeUTF8));
        lbTexto_51->setText(QApplication::translate("F5", "SEC:A1-A12-BO1 - BO GRP1 I0 FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_52->setText(QApplication::translate("F5", "SEC:A1-A12-BO2 - BO GRP1 IO FALLA", 0, QApplication::UnicodeUTF8));
        lbTexto_53->setText(QApplication::translate("F5", "SEC: LT-6045 BAJO BAJO NIVEL", 0, QApplication::UnicodeUTF8));
        lbTexto_54->setText(QApplication::translate("F5", "SEC:SUMI ACEIT LUB GEN PRES CIERR BAJ BA", 0, QApplication::UnicodeUTF8));
        lbTexto_55->setText(QApplication::translate("F5", "SEC:BAJO VOLTAJE EN 400VAC MCC", 0, QApplication::UnicodeUTF8));
        lbTexto_56->setText(QApplication::translate("F5", "SEC:INTERRUP TIERRA GENERADOR CERRADO", 0, QApplication::UnicodeUTF8));
        lbTexto_57->setText(QApplication::translate("F5", "SEC:INTERRUP TIERRA GS124 CERRADO", 0, QApplication::UnicodeUTF8));
        lbTexto_62->setText(QApplication::translate("F5", "SEC:FALLA INIC ARRAN MOTOR PAT\303\215N CONTAC", 0, QApplication::UnicodeUTF8));
        lbTexto_63->setText(QApplication::translate("F5", "SEC:AGENTE SURES D/FUEGO EMITIDO", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class F5: public Ui_F5 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_F5_H
