/********************************************************************************
** Form generated from reading UI file 'analog24_s2.ui'
**
** Created: Sun 13. Oct 17:33:25 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ANALOG24_S2_H
#define UI_ANALOG24_S2_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Analog24_S2
{
public:
    QFrame *frBarraT;
    QLabel *lbAna24_S2T;
    QFrame *frame;
    QLabel *lbSloAl;
    QLabel *lbAIU_5;
    QLabel *lbAIU_20;
    QLabel *lbAIT_23;
    QLabel *lbAI_21;
    QLabel *lbNumAI_12;
    QLabel *lbAIT_6;
    QLabel *lbAIT_21;
    QLabel *lbAIU_10;
    QLabel *lbNumAI_7;
    QLabel *lbAIU_16;
    QLabel *lbNumAI_5;
    QLabel *lbNumAI_10;
    QLabel *lbNumAI_18;
    QLabel *lbNumAI_8;
    QLabel *lbAIU_1;
    QLabel *lbAIU_7;
    QLabel *lbAI_5;
    QLabel *lbAIT_12;
    QLabel *lbNumAI_3;
    QLabel *lbAIT_8;
    QLabel *lbAI_15;
    QLabel *lbNumAI_13;
    QLabel *lbAI_3;
    QLabel *lbAIT_5;
    QLabel *lbAIU_13;
    QLabel *lbAI_8;
    QLabel *lbAI_2;
    QLabel *lbAIU_19;
    QLabel *lbAIU_2;
    QLabel *lbAIT_3;
    QLabel *lbAIU_6;
    QLabel *lbNumAI_1;
    QLabel *lbNumAI_23;
    QLabel *lbNumAI_11;
    QLabel *lbAIU_15;
    QLabel *lbAIU_23;
    QLabel *lbAIU_14;
    QLabel *lbNumAI_21;
    QLabel *lbNumAI_17;
    QLabel *lbAIT_10;
    QLabel *lbAI_18;
    QLabel *lbAIU_8;
    QLabel *lbAIU_21;
    QLabel *lbAI_9;
    QLabel *lbNumAI_14;
    QLabel *lbAIT_16;
    QLabel *lbAIT_4;
    QLabel *lbAI_17;
    QLabel *lbAI_10;
    QLabel *lbAIU_18;
    QLabel *lbAIT_9;
    QLabel *lbAI_16;
    QLabel *lbAI_4;
    QLabel *lbAIT_17;
    QLabel *lbAIU_24;
    QLabel *lbAI_19;
    QLabel *lbNumAI_22;
    QLabel *lbAIT_24;
    QLabel *lbNumAI_20;
    QLabel *lbNumAI_16;
    QLabel *lbAI_6;
    QLabel *lbAIT_1;
    QLabel *lbAIU_4;
    QLabel *lbAI_7;
    QLabel *lbAIU_3;
    QLabel *lbAIT_11;
    QLabel *lbNumAI_15;
    QLabel *lbAIU_11;
    QLabel *lbAI_24;
    QLabel *lbAIT_22;
    QLabel *lbAIT_2;
    QLabel *lbNumAI_6;
    QLabel *lbAI_1;
    QLabel *lbAIT_7;
    QLabel *lbAIT_14;
    QLabel *lbAIT_20;
    QLabel *lbAI_22;
    QLabel *lbAIT_18;
    QLabel *lbAIT_15;
    QLabel *lbAI_12;
    QLabel *lbAI_13;
    QLabel *lbAI_14;
    QLabel *lbAI_20;
    QLabel *lbNumAI_19;
    QLabel *lbNumAI_9;
    QLabel *lbNumAI_24;
    QLabel *lbNumAI_2;
    QLabel *lbAIU_12;
    QLabel *lbAIT_13;
    QLabel *lbAI_11;
    QLabel *lbNumAI_4;
    QLabel *lbAIT_19;
    QLabel *lbAIU_9;
    QLabel *lbAI_23;
    QLabel *lbAIU_22;
    QLabel *lbAIU_17;
    QPushButton *btnProx;
    QPushButton *btnCerrar;

    void setupUi(QWidget *Analog24_S2)
    {
        if (Analog24_S2->objectName().isEmpty())
            Analog24_S2->setObjectName(QString::fromUtf8("Analog24_S2"));
        Analog24_S2->resize(485, 590);
        Analog24_S2->setMinimumSize(QSize(485, 590));
        Analog24_S2->setMaximumSize(QSize(485, 590));
        Analog24_S2->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        frBarraT = new QFrame(Analog24_S2);
        frBarraT->setObjectName(QString::fromUtf8("frBarraT"));
        frBarraT->setGeometry(QRect(0, 0, 485, 15));
        frBarraT->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frBarraT->setFrameShape(QFrame::Panel);
        frBarraT->setFrameShadow(QFrame::Raised);
        frBarraT->setLineWidth(0);
        lbAna24_S2T = new QLabel(frBarraT);
        lbAna24_S2T->setObjectName(QString::fromUtf8("lbAna24_S2T"));
        lbAna24_S2T->setGeometry(QRect(3, 0, 111, 16));
        QFont font;
        font.setPointSize(5);
        font.setBold(true);
        font.setWeight(75);
        lbAna24_S2T->setFont(font);
        lbAna24_S2T->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        frame = new QFrame(Analog24_S2);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 20, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        lbSloAl = new QLabel(Analog24_S2);
        lbSloAl->setObjectName(QString::fromUtf8("lbSloAl"));
        lbSloAl->setGeometry(QRect(67, 23, 400, 22));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        lbSloAl->setFont(font1);
        lbSloAl->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        lbAIU_5 = new QLabel(Analog24_S2);
        lbAIU_5->setObjectName(QString::fromUtf8("lbAIU_5"));
        lbAIU_5->setGeometry(QRect(442, 135, 31, 20));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setBold(true);
        font2.setWeight(75);
        lbAIU_5->setFont(font2);
        lbAIU_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_20 = new QLabel(Analog24_S2);
        lbAIU_20->setObjectName(QString::fromUtf8("lbAIU_20"));
        lbAIU_20->setGeometry(QRect(435, 435, 41, 20));
        lbAIU_20->setFont(font2);
        lbAIU_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_23 = new QLabel(Analog24_S2);
        lbAIT_23->setObjectName(QString::fromUtf8("lbAIT_23"));
        lbAIT_23->setGeometry(QRect(35, 495, 311, 16));
        lbAIT_23->setFont(font2);
        lbAI_21 = new QLabel(Analog24_S2);
        lbAI_21->setObjectName(QString::fromUtf8("lbAI_21"));
        lbAI_21->setGeometry(QRect(370, 455, 71, 20));
        lbAI_21->setFont(font2);
        lbAI_21->setLayoutDirection(Qt::RightToLeft);
        lbNumAI_12 = new QLabel(Analog24_S2);
        lbNumAI_12->setObjectName(QString::fromUtf8("lbNumAI_12"));
        lbNumAI_12->setGeometry(QRect(10, 275, 21, 16));
        lbNumAI_12->setFont(font2);
        lbNumAI_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_12->setAlignment(Qt::AlignCenter);
        lbAIT_6 = new QLabel(Analog24_S2);
        lbAIT_6->setObjectName(QString::fromUtf8("lbAIT_6"));
        lbAIT_6->setGeometry(QRect(33, 155, 340, 16));
        lbAIT_6->setFont(font2);
        lbAIT_21 = new QLabel(Analog24_S2);
        lbAIT_21->setObjectName(QString::fromUtf8("lbAIT_21"));
        lbAIT_21->setGeometry(QRect(35, 455, 311, 16));
        lbAIT_21->setFont(font2);
        lbAIU_10 = new QLabel(Analog24_S2);
        lbAIU_10->setObjectName(QString::fromUtf8("lbAIU_10"));
        lbAIU_10->setGeometry(QRect(442, 235, 31, 20));
        lbAIU_10->setFont(font2);
        lbAIU_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_7 = new QLabel(Analog24_S2);
        lbNumAI_7->setObjectName(QString::fromUtf8("lbNumAI_7"));
        lbNumAI_7->setGeometry(QRect(10, 175, 21, 16));
        lbNumAI_7->setFont(font2);
        lbNumAI_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_7->setAlignment(Qt::AlignCenter);
        lbAIU_16 = new QLabel(Analog24_S2);
        lbAIU_16->setObjectName(QString::fromUtf8("lbAIU_16"));
        lbAIU_16->setGeometry(QRect(442, 355, 31, 20));
        lbAIU_16->setFont(font2);
        lbAIU_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_5 = new QLabel(Analog24_S2);
        lbNumAI_5->setObjectName(QString::fromUtf8("lbNumAI_5"));
        lbNumAI_5->setGeometry(QRect(10, 135, 21, 16));
        lbNumAI_5->setFont(font2);
        lbNumAI_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_5->setAlignment(Qt::AlignCenter);
        lbNumAI_10 = new QLabel(Analog24_S2);
        lbNumAI_10->setObjectName(QString::fromUtf8("lbNumAI_10"));
        lbNumAI_10->setGeometry(QRect(10, 235, 21, 16));
        lbNumAI_10->setFont(font2);
        lbNumAI_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_10->setAlignment(Qt::AlignCenter);
        lbNumAI_18 = new QLabel(Analog24_S2);
        lbNumAI_18->setObjectName(QString::fromUtf8("lbNumAI_18"));
        lbNumAI_18->setGeometry(QRect(10, 395, 21, 16));
        lbNumAI_18->setFont(font2);
        lbNumAI_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_18->setAlignment(Qt::AlignCenter);
        lbNumAI_8 = new QLabel(Analog24_S2);
        lbNumAI_8->setObjectName(QString::fromUtf8("lbNumAI_8"));
        lbNumAI_8->setGeometry(QRect(10, 195, 21, 16));
        lbNumAI_8->setFont(font2);
        lbNumAI_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_8->setAlignment(Qt::AlignCenter);
        lbAIU_1 = new QLabel(Analog24_S2);
        lbAIU_1->setObjectName(QString::fromUtf8("lbAIU_1"));
        lbAIU_1->setGeometry(QRect(440, 55, 31, 20));
        lbAIU_1->setFont(font2);
        lbAIU_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_7 = new QLabel(Analog24_S2);
        lbAIU_7->setObjectName(QString::fromUtf8("lbAIU_7"));
        lbAIU_7->setGeometry(QRect(442, 175, 31, 20));
        lbAIU_7->setFont(font2);
        lbAIU_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_5 = new QLabel(Analog24_S2);
        lbAI_5->setObjectName(QString::fromUtf8("lbAI_5"));
        lbAI_5->setGeometry(QRect(382, 135, 59, 20));
        lbAI_5->setFont(font2);
        lbAI_5->setLayoutDirection(Qt::RightToLeft);
        lbAIT_12 = new QLabel(Analog24_S2);
        lbAIT_12->setObjectName(QString::fromUtf8("lbAIT_12"));
        lbAIT_12->setGeometry(QRect(35, 275, 340, 16));
        lbAIT_12->setFont(font2);
        lbNumAI_3 = new QLabel(Analog24_S2);
        lbNumAI_3->setObjectName(QString::fromUtf8("lbNumAI_3"));
        lbNumAI_3->setGeometry(QRect(10, 95, 21, 16));
        lbNumAI_3->setFont(font2);
        lbNumAI_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_3->setAlignment(Qt::AlignCenter);
        lbAIT_8 = new QLabel(Analog24_S2);
        lbAIT_8->setObjectName(QString::fromUtf8("lbAIT_8"));
        lbAIT_8->setGeometry(QRect(35, 195, 340, 16));
        lbAIT_8->setFont(font2);
        lbAI_15 = new QLabel(Analog24_S2);
        lbAI_15->setObjectName(QString::fromUtf8("lbAI_15"));
        lbAI_15->setGeometry(QRect(380, 335, 61, 20));
        lbAI_15->setFont(font2);
        lbAI_15->setLayoutDirection(Qt::RightToLeft);
        lbNumAI_13 = new QLabel(Analog24_S2);
        lbNumAI_13->setObjectName(QString::fromUtf8("lbNumAI_13"));
        lbNumAI_13->setGeometry(QRect(10, 295, 21, 16));
        lbNumAI_13->setFont(font2);
        lbNumAI_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_13->setAlignment(Qt::AlignCenter);
        lbAI_3 = new QLabel(Analog24_S2);
        lbAI_3->setObjectName(QString::fromUtf8("lbAI_3"));
        lbAI_3->setGeometry(QRect(382, 95, 59, 20));
        lbAI_3->setFont(font2);
        lbAI_3->setLayoutDirection(Qt::RightToLeft);
        lbAIT_5 = new QLabel(Analog24_S2);
        lbAIT_5->setObjectName(QString::fromUtf8("lbAIT_5"));
        lbAIT_5->setGeometry(QRect(35, 135, 340, 16));
        lbAIT_5->setFont(font2);
        lbAIU_13 = new QLabel(Analog24_S2);
        lbAIU_13->setObjectName(QString::fromUtf8("lbAIU_13"));
        lbAIU_13->setGeometry(QRect(442, 295, 31, 20));
        lbAIU_13->setFont(font2);
        lbAIU_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_8 = new QLabel(Analog24_S2);
        lbAI_8->setObjectName(QString::fromUtf8("lbAI_8"));
        lbAI_8->setGeometry(QRect(380, 195, 61, 20));
        lbAI_8->setFont(font2);
        lbAI_8->setLayoutDirection(Qt::RightToLeft);
        lbAI_2 = new QLabel(Analog24_S2);
        lbAI_2->setObjectName(QString::fromUtf8("lbAI_2"));
        lbAI_2->setGeometry(QRect(380, 75, 59, 20));
        lbAI_2->setFont(font2);
        lbAI_2->setLayoutDirection(Qt::RightToLeft);
        lbAIU_19 = new QLabel(Analog24_S2);
        lbAIU_19->setObjectName(QString::fromUtf8("lbAIU_19"));
        lbAIU_19->setGeometry(QRect(442, 415, 31, 20));
        lbAIU_19->setFont(font2);
        lbAIU_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_2 = new QLabel(Analog24_S2);
        lbAIU_2->setObjectName(QString::fromUtf8("lbAIU_2"));
        lbAIU_2->setGeometry(QRect(440, 75, 31, 20));
        lbAIU_2->setFont(font2);
        lbAIU_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_3 = new QLabel(Analog24_S2);
        lbAIT_3->setObjectName(QString::fromUtf8("lbAIT_3"));
        lbAIT_3->setGeometry(QRect(35, 95, 340, 16));
        lbAIT_3->setFont(font2);
        lbAIU_6 = new QLabel(Analog24_S2);
        lbAIU_6->setObjectName(QString::fromUtf8("lbAIU_6"));
        lbAIU_6->setGeometry(QRect(440, 155, 31, 20));
        lbAIU_6->setFont(font2);
        lbAIU_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_1 = new QLabel(Analog24_S2);
        lbNumAI_1->setObjectName(QString::fromUtf8("lbNumAI_1"));
        lbNumAI_1->setGeometry(QRect(10, 55, 21, 16));
        lbNumAI_1->setFont(font2);
        lbNumAI_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_1->setAlignment(Qt::AlignCenter);
        lbNumAI_23 = new QLabel(Analog24_S2);
        lbNumAI_23->setObjectName(QString::fromUtf8("lbNumAI_23"));
        lbNumAI_23->setGeometry(QRect(10, 495, 21, 16));
        lbNumAI_23->setFont(font2);
        lbNumAI_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_23->setAlignment(Qt::AlignCenter);
        lbNumAI_11 = new QLabel(Analog24_S2);
        lbNumAI_11->setObjectName(QString::fromUtf8("lbNumAI_11"));
        lbNumAI_11->setGeometry(QRect(10, 255, 21, 16));
        lbNumAI_11->setFont(font2);
        lbNumAI_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_11->setAlignment(Qt::AlignCenter);
        lbAIU_15 = new QLabel(Analog24_S2);
        lbAIU_15->setObjectName(QString::fromUtf8("lbAIU_15"));
        lbAIU_15->setGeometry(QRect(442, 335, 31, 20));
        lbAIU_15->setFont(font2);
        lbAIU_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_23 = new QLabel(Analog24_S2);
        lbAIU_23->setObjectName(QString::fromUtf8("lbAIU_23"));
        lbAIU_23->setGeometry(QRect(445, 495, 31, 20));
        lbAIU_23->setFont(font2);
        lbAIU_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_14 = new QLabel(Analog24_S2);
        lbAIU_14->setObjectName(QString::fromUtf8("lbAIU_14"));
        lbAIU_14->setGeometry(QRect(442, 315, 31, 20));
        lbAIU_14->setFont(font2);
        lbAIU_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_21 = new QLabel(Analog24_S2);
        lbNumAI_21->setObjectName(QString::fromUtf8("lbNumAI_21"));
        lbNumAI_21->setGeometry(QRect(10, 455, 21, 16));
        lbNumAI_21->setFont(font2);
        lbNumAI_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_21->setAlignment(Qt::AlignCenter);
        lbNumAI_17 = new QLabel(Analog24_S2);
        lbNumAI_17->setObjectName(QString::fromUtf8("lbNumAI_17"));
        lbNumAI_17->setGeometry(QRect(10, 375, 21, 16));
        lbNumAI_17->setFont(font2);
        lbNumAI_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_17->setAlignment(Qt::AlignCenter);
        lbAIT_10 = new QLabel(Analog24_S2);
        lbAIT_10->setObjectName(QString::fromUtf8("lbAIT_10"));
        lbAIT_10->setGeometry(QRect(35, 235, 340, 16));
        lbAIT_10->setFont(font2);
        lbAI_18 = new QLabel(Analog24_S2);
        lbAI_18->setObjectName(QString::fromUtf8("lbAI_18"));
        lbAI_18->setGeometry(QRect(380, 395, 61, 20));
        lbAI_18->setFont(font2);
        lbAI_18->setLayoutDirection(Qt::RightToLeft);
        lbAIU_8 = new QLabel(Analog24_S2);
        lbAIU_8->setObjectName(QString::fromUtf8("lbAIU_8"));
        lbAIU_8->setGeometry(QRect(442, 195, 31, 20));
        lbAIU_8->setFont(font2);
        lbAIU_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_21 = new QLabel(Analog24_S2);
        lbAIU_21->setObjectName(QString::fromUtf8("lbAIU_21"));
        lbAIU_21->setGeometry(QRect(442, 455, 31, 20));
        lbAIU_21->setFont(font2);
        lbAIU_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_9 = new QLabel(Analog24_S2);
        lbAI_9->setObjectName(QString::fromUtf8("lbAI_9"));
        lbAI_9->setGeometry(QRect(380, 215, 61, 20));
        lbAI_9->setFont(font2);
        lbAI_9->setLayoutDirection(Qt::RightToLeft);
        lbNumAI_14 = new QLabel(Analog24_S2);
        lbNumAI_14->setObjectName(QString::fromUtf8("lbNumAI_14"));
        lbNumAI_14->setGeometry(QRect(10, 315, 21, 16));
        lbNumAI_14->setFont(font2);
        lbNumAI_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_14->setAlignment(Qt::AlignCenter);
        lbAIT_16 = new QLabel(Analog24_S2);
        lbAIT_16->setObjectName(QString::fromUtf8("lbAIT_16"));
        lbAIT_16->setGeometry(QRect(35, 355, 340, 16));
        lbAIT_16->setFont(font2);
        lbAIT_4 = new QLabel(Analog24_S2);
        lbAIT_4->setObjectName(QString::fromUtf8("lbAIT_4"));
        lbAIT_4->setGeometry(QRect(35, 115, 340, 16));
        lbAIT_4->setFont(font2);
        lbAI_17 = new QLabel(Analog24_S2);
        lbAI_17->setObjectName(QString::fromUtf8("lbAI_17"));
        lbAI_17->setGeometry(QRect(380, 375, 61, 20));
        lbAI_17->setFont(font2);
        lbAI_17->setLayoutDirection(Qt::RightToLeft);
        lbAI_10 = new QLabel(Analog24_S2);
        lbAI_10->setObjectName(QString::fromUtf8("lbAI_10"));
        lbAI_10->setGeometry(QRect(380, 235, 61, 20));
        lbAI_10->setFont(font2);
        lbAI_10->setLayoutDirection(Qt::RightToLeft);
        lbAIU_18 = new QLabel(Analog24_S2);
        lbAIU_18->setObjectName(QString::fromUtf8("lbAIU_18"));
        lbAIU_18->setGeometry(QRect(442, 395, 31, 20));
        lbAIU_18->setFont(font2);
        lbAIU_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_9 = new QLabel(Analog24_S2);
        lbAIT_9->setObjectName(QString::fromUtf8("lbAIT_9"));
        lbAIT_9->setGeometry(QRect(35, 215, 340, 16));
        lbAIT_9->setFont(font2);
        lbAI_16 = new QLabel(Analog24_S2);
        lbAI_16->setObjectName(QString::fromUtf8("lbAI_16"));
        lbAI_16->setGeometry(QRect(380, 355, 61, 20));
        lbAI_16->setFont(font2);
        lbAI_16->setLayoutDirection(Qt::RightToLeft);
        lbAI_4 = new QLabel(Analog24_S2);
        lbAI_4->setObjectName(QString::fromUtf8("lbAI_4"));
        lbAI_4->setGeometry(QRect(382, 115, 59, 20));
        lbAI_4->setFont(font2);
        lbAI_4->setLayoutDirection(Qt::RightToLeft);
        lbAIT_17 = new QLabel(Analog24_S2);
        lbAIT_17->setObjectName(QString::fromUtf8("lbAIT_17"));
        lbAIT_17->setGeometry(QRect(35, 375, 340, 16));
        lbAIT_17->setFont(font2);
        lbAIU_24 = new QLabel(Analog24_S2);
        lbAIU_24->setObjectName(QString::fromUtf8("lbAIU_24"));
        lbAIU_24->setGeometry(QRect(442, 515, 31, 20));
        lbAIU_24->setFont(font2);
        lbAIU_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_19 = new QLabel(Analog24_S2);
        lbAI_19->setObjectName(QString::fromUtf8("lbAI_19"));
        lbAI_19->setGeometry(QRect(380, 415, 61, 20));
        lbAI_19->setFont(font2);
        lbAI_19->setLayoutDirection(Qt::RightToLeft);
        lbNumAI_22 = new QLabel(Analog24_S2);
        lbNumAI_22->setObjectName(QString::fromUtf8("lbNumAI_22"));
        lbNumAI_22->setGeometry(QRect(10, 475, 21, 16));
        lbNumAI_22->setFont(font2);
        lbNumAI_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_22->setAlignment(Qt::AlignCenter);
        lbAIT_24 = new QLabel(Analog24_S2);
        lbAIT_24->setObjectName(QString::fromUtf8("lbAIT_24"));
        lbAIT_24->setGeometry(QRect(35, 515, 311, 16));
        lbAIT_24->setFont(font2);
        lbNumAI_20 = new QLabel(Analog24_S2);
        lbNumAI_20->setObjectName(QString::fromUtf8("lbNumAI_20"));
        lbNumAI_20->setGeometry(QRect(10, 435, 21, 16));
        lbNumAI_20->setFont(font2);
        lbNumAI_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_20->setAlignment(Qt::AlignCenter);
        lbNumAI_16 = new QLabel(Analog24_S2);
        lbNumAI_16->setObjectName(QString::fromUtf8("lbNumAI_16"));
        lbNumAI_16->setGeometry(QRect(10, 355, 21, 16));
        lbNumAI_16->setFont(font2);
        lbNumAI_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_16->setAlignment(Qt::AlignCenter);
        lbAI_6 = new QLabel(Analog24_S2);
        lbAI_6->setObjectName(QString::fromUtf8("lbAI_6"));
        lbAI_6->setGeometry(QRect(380, 155, 59, 20));
        lbAI_6->setFont(font2);
        lbAI_6->setLayoutDirection(Qt::RightToLeft);
        lbAIT_1 = new QLabel(Analog24_S2);
        lbAIT_1->setObjectName(QString::fromUtf8("lbAIT_1"));
        lbAIT_1->setGeometry(QRect(33, 55, 340, 16));
        lbAIT_1->setFont(font2);
        lbAIU_4 = new QLabel(Analog24_S2);
        lbAIU_4->setObjectName(QString::fromUtf8("lbAIU_4"));
        lbAIU_4->setGeometry(QRect(442, 115, 31, 20));
        lbAIU_4->setFont(font2);
        lbAIU_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_7 = new QLabel(Analog24_S2);
        lbAI_7->setObjectName(QString::fromUtf8("lbAI_7"));
        lbAI_7->setGeometry(QRect(380, 175, 61, 20));
        lbAI_7->setFont(font2);
        lbAI_7->setLayoutDirection(Qt::RightToLeft);
        lbAIU_3 = new QLabel(Analog24_S2);
        lbAIU_3->setObjectName(QString::fromUtf8("lbAIU_3"));
        lbAIU_3->setGeometry(QRect(442, 95, 31, 20));
        lbAIU_3->setFont(font2);
        lbAIU_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_11 = new QLabel(Analog24_S2);
        lbAIT_11->setObjectName(QString::fromUtf8("lbAIT_11"));
        lbAIT_11->setGeometry(QRect(35, 255, 340, 16));
        lbAIT_11->setFont(font2);
        lbNumAI_15 = new QLabel(Analog24_S2);
        lbNumAI_15->setObjectName(QString::fromUtf8("lbNumAI_15"));
        lbNumAI_15->setGeometry(QRect(10, 335, 21, 16));
        lbNumAI_15->setFont(font2);
        lbNumAI_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_15->setAlignment(Qt::AlignCenter);
        lbAIU_11 = new QLabel(Analog24_S2);
        lbAIU_11->setObjectName(QString::fromUtf8("lbAIU_11"));
        lbAIU_11->setGeometry(QRect(442, 255, 31, 20));
        lbAIU_11->setFont(font2);
        lbAIU_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_24 = new QLabel(Analog24_S2);
        lbAI_24->setObjectName(QString::fromUtf8("lbAI_24"));
        lbAI_24->setGeometry(QRect(375, 515, 67, 20));
        lbAI_24->setFont(font2);
        lbAI_24->setLayoutDirection(Qt::RightToLeft);
        lbAIT_22 = new QLabel(Analog24_S2);
        lbAIT_22->setObjectName(QString::fromUtf8("lbAIT_22"));
        lbAIT_22->setGeometry(QRect(35, 475, 311, 16));
        lbAIT_22->setFont(font2);
        lbAIT_2 = new QLabel(Analog24_S2);
        lbAIT_2->setObjectName(QString::fromUtf8("lbAIT_2"));
        lbAIT_2->setGeometry(QRect(33, 75, 340, 16));
        lbAIT_2->setFont(font2);
        lbNumAI_6 = new QLabel(Analog24_S2);
        lbNumAI_6->setObjectName(QString::fromUtf8("lbNumAI_6"));
        lbNumAI_6->setGeometry(QRect(10, 155, 21, 16));
        lbNumAI_6->setFont(font2);
        lbNumAI_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_6->setAlignment(Qt::AlignCenter);
        lbAI_1 = new QLabel(Analog24_S2);
        lbAI_1->setObjectName(QString::fromUtf8("lbAI_1"));
        lbAI_1->setGeometry(QRect(380, 55, 59, 20));
        lbAI_1->setFont(font2);
        lbAI_1->setLayoutDirection(Qt::RightToLeft);
        lbAIT_7 = new QLabel(Analog24_S2);
        lbAIT_7->setObjectName(QString::fromUtf8("lbAIT_7"));
        lbAIT_7->setGeometry(QRect(35, 175, 340, 16));
        lbAIT_7->setFont(font2);
        lbAIT_14 = new QLabel(Analog24_S2);
        lbAIT_14->setObjectName(QString::fromUtf8("lbAIT_14"));
        lbAIT_14->setGeometry(QRect(35, 315, 340, 16));
        lbAIT_14->setFont(font2);
        lbAIT_20 = new QLabel(Analog24_S2);
        lbAIT_20->setObjectName(QString::fromUtf8("lbAIT_20"));
        lbAIT_20->setGeometry(QRect(35, 435, 311, 16));
        lbAIT_20->setFont(font2);
        lbAI_22 = new QLabel(Analog24_S2);
        lbAI_22->setObjectName(QString::fromUtf8("lbAI_22"));
        lbAI_22->setGeometry(QRect(370, 475, 71, 20));
        lbAI_22->setFont(font2);
        lbAI_22->setLayoutDirection(Qt::RightToLeft);
        lbAIT_18 = new QLabel(Analog24_S2);
        lbAIT_18->setObjectName(QString::fromUtf8("lbAIT_18"));
        lbAIT_18->setGeometry(QRect(35, 395, 340, 16));
        lbAIT_18->setFont(font2);
        lbAIT_15 = new QLabel(Analog24_S2);
        lbAIT_15->setObjectName(QString::fromUtf8("lbAIT_15"));
        lbAIT_15->setGeometry(QRect(35, 335, 340, 16));
        lbAIT_15->setFont(font2);
        lbAI_12 = new QLabel(Analog24_S2);
        lbAI_12->setObjectName(QString::fromUtf8("lbAI_12"));
        lbAI_12->setGeometry(QRect(380, 275, 61, 20));
        lbAI_12->setFont(font2);
        lbAI_12->setLayoutDirection(Qt::RightToLeft);
        lbAI_13 = new QLabel(Analog24_S2);
        lbAI_13->setObjectName(QString::fromUtf8("lbAI_13"));
        lbAI_13->setGeometry(QRect(380, 295, 61, 20));
        lbAI_13->setFont(font2);
        lbAI_13->setLayoutDirection(Qt::RightToLeft);
        lbAI_14 = new QLabel(Analog24_S2);
        lbAI_14->setObjectName(QString::fromUtf8("lbAI_14"));
        lbAI_14->setGeometry(QRect(380, 315, 61, 20));
        lbAI_14->setFont(font2);
        lbAI_14->setLayoutDirection(Qt::RightToLeft);
        lbAI_20 = new QLabel(Analog24_S2);
        lbAI_20->setObjectName(QString::fromUtf8("lbAI_20"));
        lbAI_20->setGeometry(QRect(370, 435, 71, 20));
        lbAI_20->setFont(font2);
        lbAI_20->setLayoutDirection(Qt::RightToLeft);
        lbNumAI_19 = new QLabel(Analog24_S2);
        lbNumAI_19->setObjectName(QString::fromUtf8("lbNumAI_19"));
        lbNumAI_19->setGeometry(QRect(10, 415, 21, 16));
        lbNumAI_19->setFont(font2);
        lbNumAI_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_19->setAlignment(Qt::AlignCenter);
        lbNumAI_9 = new QLabel(Analog24_S2);
        lbNumAI_9->setObjectName(QString::fromUtf8("lbNumAI_9"));
        lbNumAI_9->setGeometry(QRect(10, 215, 21, 16));
        lbNumAI_9->setFont(font2);
        lbNumAI_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_9->setAlignment(Qt::AlignCenter);
        lbNumAI_24 = new QLabel(Analog24_S2);
        lbNumAI_24->setObjectName(QString::fromUtf8("lbNumAI_24"));
        lbNumAI_24->setGeometry(QRect(10, 515, 21, 16));
        lbNumAI_24->setFont(font2);
        lbNumAI_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_24->setAlignment(Qt::AlignCenter);
        lbNumAI_2 = new QLabel(Analog24_S2);
        lbNumAI_2->setObjectName(QString::fromUtf8("lbNumAI_2"));
        lbNumAI_2->setGeometry(QRect(10, 75, 21, 16));
        lbNumAI_2->setFont(font2);
        lbNumAI_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_2->setAlignment(Qt::AlignCenter);
        lbAIU_12 = new QLabel(Analog24_S2);
        lbAIU_12->setObjectName(QString::fromUtf8("lbAIU_12"));
        lbAIU_12->setGeometry(QRect(442, 275, 31, 20));
        lbAIU_12->setFont(font2);
        lbAIU_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_13 = new QLabel(Analog24_S2);
        lbAIT_13->setObjectName(QString::fromUtf8("lbAIT_13"));
        lbAIT_13->setGeometry(QRect(35, 295, 340, 16));
        lbAIT_13->setFont(font2);
        lbAI_11 = new QLabel(Analog24_S2);
        lbAI_11->setObjectName(QString::fromUtf8("lbAI_11"));
        lbAI_11->setGeometry(QRect(380, 255, 61, 20));
        lbAI_11->setFont(font2);
        lbAI_11->setLayoutDirection(Qt::RightToLeft);
        lbNumAI_4 = new QLabel(Analog24_S2);
        lbNumAI_4->setObjectName(QString::fromUtf8("lbNumAI_4"));
        lbNumAI_4->setGeometry(QRect(10, 115, 21, 16));
        lbNumAI_4->setFont(font2);
        lbNumAI_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_4->setAlignment(Qt::AlignCenter);
        lbAIT_19 = new QLabel(Analog24_S2);
        lbAIT_19->setObjectName(QString::fromUtf8("lbAIT_19"));
        lbAIT_19->setGeometry(QRect(35, 415, 340, 16));
        lbAIT_19->setFont(font2);
        lbAIU_9 = new QLabel(Analog24_S2);
        lbAIU_9->setObjectName(QString::fromUtf8("lbAIU_9"));
        lbAIU_9->setGeometry(QRect(442, 215, 31, 20));
        lbAIU_9->setFont(font2);
        lbAIU_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_23 = new QLabel(Analog24_S2);
        lbAI_23->setObjectName(QString::fromUtf8("lbAI_23"));
        lbAI_23->setGeometry(QRect(370, 495, 71, 20));
        lbAI_23->setFont(font2);
        lbAI_23->setLayoutDirection(Qt::RightToLeft);
        lbAIU_22 = new QLabel(Analog24_S2);
        lbAIU_22->setObjectName(QString::fromUtf8("lbAIU_22"));
        lbAIU_22->setGeometry(QRect(445, 475, 31, 20));
        lbAIU_22->setFont(font2);
        lbAIU_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIU_17 = new QLabel(Analog24_S2);
        lbAIU_17->setObjectName(QString::fromUtf8("lbAIU_17"));
        lbAIU_17->setGeometry(QRect(442, 375, 31, 20));
        lbAIU_17->setFont(font2);
        lbAIU_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        btnProx = new QPushButton(Analog24_S2);
        btnProx->setObjectName(QString::fromUtf8("btnProx"));
        btnProx->setGeometry(QRect(274, 540, 101, 41));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        btnProx->setFont(font3);
        btnProx->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnCerrar = new QPushButton(Analog24_S2);
        btnCerrar->setObjectName(QString::fromUtf8("btnCerrar"));
        btnCerrar->setGeometry(QRect(124, 540, 101, 41));
        btnCerrar->setFont(font3);
        btnCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));

        retranslateUi(Analog24_S2);

        QMetaObject::connectSlotsByName(Analog24_S2);
    } // setupUi

    void retranslateUi(QWidget *Analog24_S2)
    {
        Analog24_S2->setWindowTitle(QApplication::translate("Analog24_S2", "Analog24_S2", 0, QApplication::UnicodeUTF8));
        lbAna24_S2T->setText(QApplication::translate("Analog24_S2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">ANALOG24_S2.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbSloAl->setText(QApplication::translate("Analog24_S2", "SLOT-  A107  - Al", 0, QApplication::UnicodeUTF8));
        lbAIU_5->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_20->setText(QString());
        lbAIT_23->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAI_21->setText(QApplication::translate("Analog24_S2", "0.90", 0, QApplication::UnicodeUTF8));
        lbNumAI_12->setText(QApplication::translate("Analog24_S2", "12", 0, QApplication::UnicodeUTF8));
        lbAIT_6->setText(QApplication::translate("Analog24_S2", "T3B2 HPC TEMP DE DESCARGA", 0, QApplication::UnicodeUTF8));
        lbAIT_21->setText(QApplication::translate("Analog24_S2", "NIVEL TANQUE DE LUB DE CAJA DE ENGRAN DE", 0, QApplication::UnicodeUTF8));
        lbAIU_10->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_7->setText(QApplication::translate("Analog24_S2", "7", 0, QApplication::UnicodeUTF8));
        lbAIU_16->setText(QString());
        lbNumAI_5->setText(QApplication::translate("Analog24_S2", "5", 0, QApplication::UnicodeUTF8));
        lbNumAI_10->setText(QApplication::translate("Analog24_S2", "10", 0, QApplication::UnicodeUTF8));
        lbNumAI_18->setText(QApplication::translate("Analog24_S2", "18", 0, QApplication::UnicodeUTF8));
        lbNumAI_8->setText(QApplication::translate("Analog24_S2", "8", 0, QApplication::UnicodeUTF8));
        lbAIU_1->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_7->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_5->setText(QApplication::translate("Analog24_S2", "982.00", 0, QApplication::UnicodeUTF8));
        lbAIT_12->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_3->setText(QApplication::translate("Analog24_S2", "3", 0, QApplication::UnicodeUTF8));
        lbAIT_8->setText(QApplication::translate("Analog24_S2", "TEMP ADMIS AIRE COMPRESOR HP T25B", 0, QApplication::UnicodeUTF8));
        lbAI_15->setText(QApplication::translate("Analog24_S2", "2.16", 0, QApplication::UnicodeUTF8));
        lbNumAI_13->setText(QApplication::translate("Analog24_S2", "13", 0, QApplication::UnicodeUTF8));
        lbAI_3->setText(QApplication::translate("Analog24_S2", "1615.00", 0, QApplication::UnicodeUTF8));
        lbAIT_5->setText(QApplication::translate("Analog24_S2", "T3A2 HPC TEMP DE DESCARGA", 0, QApplication::UnicodeUTF8));
        lbAIU_13->setText(QString());
        lbAI_8->setText(QApplication::translate("Analog24_S2", "216.00", 0, QApplication::UnicodeUTF8));
        lbAI_2->setText(QApplication::translate("Analog24_S2", "1599.00", 0, QApplication::UnicodeUTF8));
        lbAIU_19->setText(QApplication::translate("Analog24_S2", "%", 0, QApplication::UnicodeUTF8));
        lbAIU_2->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_3->setText(QApplication::translate("Analog24_S2", "TEMP DE ENTRADA DE GAS LPT T48F (ABAJO)", 0, QApplication::UnicodeUTF8));
        lbAIU_6->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_1->setText(QApplication::translate("Analog24_S2", "1", 0, QApplication::UnicodeUTF8));
        lbNumAI_23->setText(QApplication::translate("Analog24_S2", "23", 0, QApplication::UnicodeUTF8));
        lbNumAI_11->setText(QApplication::translate("Analog24_S2", "11", 0, QApplication::UnicodeUTF8));
        lbAIU_15->setText(QApplication::translate("Analog24_S2", "PSID", 0, QApplication::UnicodeUTF8));
        lbAIU_23->setText(QString());
        lbAIU_14->setText(QApplication::translate("Analog24_S2", "PSIA", 0, QApplication::UnicodeUTF8));
        lbNumAI_21->setText(QApplication::translate("Analog24_S2", "21", 0, QApplication::UnicodeUTF8));
        lbNumAI_17->setText(QApplication::translate("Analog24_S2", "17", 0, QApplication::UnicodeUTF8));
        lbAIT_10->setText(QApplication::translate("Analog24_S2", "SENSOR B TEMPERATURA DE GAS COMB", 0, QApplication::UnicodeUTF8));
        lbAI_18->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIU_8->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIU_21->setText(QApplication::translate("Analog24_S2", "PPM", 0, QApplication::UnicodeUTF8));
        lbAI_9->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_14->setText(QApplication::translate("Analog24_S2", "14", 0, QApplication::UnicodeUTF8));
        lbAIT_16->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIT_4->setText(QApplication::translate("Analog24_S2", "TEMP DE ENTRADA DE GAS LPT T48H (ARRIBA)", 0, QApplication::UnicodeUTF8));
        lbAI_17->setText(QApplication::translate("Analog24_S2", "64.80", 0, QApplication::UnicodeUTF8));
        lbAI_10->setText(QApplication::translate("Analog24_S2", "78.00", 0, QApplication::UnicodeUTF8));
        lbAIU_18->setText(QApplication::translate("Analog24_S2", "MA", 0, QApplication::UnicodeUTF8));
        lbAIT_9->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAI_16->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAI_4->setText(QApplication::translate("Analog24_S2", "1601.00", 0, QApplication::UnicodeUTF8));
        lbAIT_17->setText(QApplication::translate("Analog24_S2", "PRES DE BALANCE DE IMPULSO PTBB", 0, QApplication::UnicodeUTF8));
        lbAIU_24->setText(QApplication::translate("Analog24_S2", "PSIA", 0, QApplication::UnicodeUTF8));
        lbAI_19->setText(QApplication::translate("Analog24_S2", "0.10", 0, QApplication::UnicodeUTF8));
        lbNumAI_22->setText(QApplication::translate("Analog24_S2", "22", 0, QApplication::UnicodeUTF8));
        lbAIT_24->setText(QApplication::translate("Analog24_S2", "PS3B PRES ST DE DESCARGA HPC", 0, QApplication::UnicodeUTF8));
        lbNumAI_20->setText(QApplication::translate("Analog24_S2", "20", 0, QApplication::UnicodeUTF8));
        lbNumAI_16->setText(QApplication::translate("Analog24_S2", "16", 0, QApplication::UnicodeUTF8));
        lbAI_6->setText(QApplication::translate("Analog24_S2", "981.00", 0, QApplication::UnicodeUTF8));
        lbAIT_1->setText(QApplication::translate("Analog24_S2", "TEMP DE ENTRADA DE GAS LPT T48B (ARRIBA)", 0, QApplication::UnicodeUTF8));
        lbAIU_4->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_7->setText(QApplication::translate("Analog24_S2", "49.00", 0, QApplication::UnicodeUTF8));
        lbAIU_3->setText(QApplication::translate("Analog24_S2", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_11->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_15->setText(QApplication::translate("Analog24_S2", "15", 0, QApplication::UnicodeUTF8));
        lbAIU_11->setText(QString());
        lbAI_24->setText(QApplication::translate("Analog24_S2", "325.40", 0, QApplication::UnicodeUTF8));
        lbAIT_22->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIT_2->setText(QApplication::translate("Analog24_S2", "TEMP DE ENTRADA DE GAS LPT T48D (ABAJO)", 0, QApplication::UnicodeUTF8));
        lbNumAI_6->setText(QApplication::translate("Analog24_S2", "6", 0, QApplication::UnicodeUTF8));
        lbAI_1->setText(QApplication::translate("Analog24_S2", "1561.00", 0, QApplication::UnicodeUTF8));
        lbAIT_7->setText(QApplication::translate("Analog24_S2", "T2B LPC TEMP ADMIS DE AIRE", 0, QApplication::UnicodeUTF8));
        lbAIT_14->setText(QApplication::translate("Analog24_S2", "P25B HPC PRES TOTAL ENTRADA \"B\"", 0, QApplication::UnicodeUTF8));
        lbAIT_20->setText(QApplication::translate("Analog24_S2", "GRAV ESPECIFICA DE GAS COMB", 0, QApplication::UnicodeUTF8));
        lbAI_22->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIT_18->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIT_15->setText(QApplication::translate("Analog24_S2", "PRESI\303\223N DIN\303\201MICA AC\303\232STICA (PX36B)", 0, QApplication::UnicodeUTF8));
        lbAI_12->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAI_13->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAI_14->setText(QApplication::translate("Analog24_S2", "27.50", 0, QApplication::UnicodeUTF8));
        lbAI_20->setText(QApplication::translate("Analog24_S2", "0.58", 0, QApplication::UnicodeUTF8));
        lbNumAI_19->setText(QApplication::translate("Analog24_S2", "19", 0, QApplication::UnicodeUTF8));
        lbNumAI_9->setText(QApplication::translate("Analog24_S2", "9", 0, QApplication::UnicodeUTF8));
        lbNumAI_24->setText(QApplication::translate("Analog24_S2", "24", 0, QApplication::UnicodeUTF8));
        lbNumAI_2->setText(QApplication::translate("Analog24_S2", "2", 0, QApplication::UnicodeUTF8));
        lbAIU_12->setText(QString());
        lbAIT_13->setText(QApplication::translate("Analog24_S2", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAI_11->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_4->setText(QApplication::translate("Analog24_S2", "4", 0, QApplication::UnicodeUTF8));
        lbAIT_19->setText(QApplication::translate("Analog24_S2", "HUMEDAD DE GAS COMBUSTIBLE", 0, QApplication::UnicodeUTF8));
        lbAIU_9->setText(QString());
        lbAI_23->setText(QApplication::translate("Analog24_S2", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIU_22->setText(QString());
        lbAIU_17->setText(QApplication::translate("Analog24_S2", "PSIA", 0, QApplication::UnicodeUTF8));
        btnProx->setText(QApplication::translate("Analog24_S2", "PR\303\223X >", 0, QApplication::UnicodeUTF8));
        btnCerrar->setText(QApplication::translate("Analog24_S2", "CERRAR", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Analog24_S2: public Ui_Analog24_S2 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ANALOG24_S2_H
