/********************************************************************************
** Form generated from reading UI file 'analog24.ui'
**
** Created: Sun 13. Oct 17:33:26 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ANALOG24_H
#define UI_ANALOG24_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Analog24
{
public:
    QFrame *frBarraT;
    QLabel *lbAna24T;
    QLabel *lbSloAl;
    QFrame *frame;
    QPushButton *btnCerrar;
    QPushButton *btnProx;
    QLabel *lbNumAI_1;
    QLabel *lbAIU_1;
    QLabel *lbAIT_1;
    QLabel *lbAI_1;
    QLabel *lbAIU_2;
    QLabel *lbAIT_2;
    QLabel *lbAI_2;
    QLabel *lbNumAI_2;
    QLabel *lbNumAI_3;
    QLabel *lbAIU_3;
    QLabel *lbAI_3;
    QLabel *lbAIT_3;
    QLabel *lbNumAI_4;
    QLabel *lbAIU_4;
    QLabel *lbAIT_4;
    QLabel *lbAI_4;
    QLabel *lbNumAI_5;
    QLabel *lbAI_5;
    QLabel *lbAIU_5;
    QLabel *lbAIT_5;
    QLabel *lbAIU_6;
    QLabel *lbAI_6;
    QLabel *lbNumAI_6;
    QLabel *lbAIT_6;
    QLabel *lbNumAI_7;
    QLabel *lbAIU_7;
    QLabel *lbAI_7;
    QLabel *lbAIT_7;
    QLabel *lbNumAI_8;
    QLabel *lbAIU_8;
    QLabel *lbAIT_8;
    QLabel *lbAI_8;
    QLabel *lbNumAI_9;
    QLabel *lbAIU_9;
    QLabel *lbAI_9;
    QLabel *lbAIT_9;
    QLabel *lbNumAI_10;
    QLabel *lbAIT_10;
    QLabel *lbAI_10;
    QLabel *lbAIU_10;
    QLabel *lbNumAI_11;
    QLabel *lbAI_11;
    QLabel *lbAIT_11;
    QLabel *lbAIU_11;
    QLabel *lbNumAI_12;
    QLabel *lbAI_12;
    QLabel *lbAIU_12;
    QLabel *lbAIT_12;
    QLabel *lbNumAI_13;
    QLabel *lbAIU_13;
    QLabel *lbAI_13;
    QLabel *lbAIT_13;
    QLabel *lbNumAI_14;
    QLabel *lbAIT_14;
    QLabel *lbAI_14;
    QLabel *lbAIU_14;
    QLabel *lbNumAI_15;
    QLabel *lbAI_15;
    QLabel *lbAIT_15;
    QLabel *lbAIU_15;
    QLabel *lbNumAI_16;
    QLabel *lbAIT_16;
    QLabel *lbAI_16;
    QLabel *lbAIU_16;
    QLabel *lbNumAI_17;
    QLabel *lbAIU_17;
    QLabel *lbAI_17;
    QLabel *lbAIT_17;
    QLabel *lbNumAI_18;
    QLabel *lbAI_18;
    QLabel *lbAIU_18;
    QLabel *lbAIT_18;
    QLabel *lbNumAI_19;
    QLabel *lbAIT_19;
    QLabel *lbAIU_19;
    QLabel *lbAI_19;
    QLabel *lbNumAI_20;
    QLabel *lbAIU_20;
    QLabel *lbAIT_20;
    QLabel *lbAI_20;
    QLabel *lbNumAI_21;
    QLabel *lbAIU_21;
    QLabel *lbAI_21;
    QLabel *lbAIT_21;
    QLabel *lbNumAI_22;
    QLabel *lbAIU_22;
    QLabel *lbAIT_22;
    QLabel *lbAI_22;
    QLabel *lbNumAI_23;
    QLabel *lbAIU_23;
    QLabel *lbAI_23;
    QLabel *lbAIT_23;
    QLabel *lbAIU_24;
    QLabel *lbNumAI_24;
    QLabel *lbAIT_24;
    QLabel *lbAI_24;

    void setupUi(QWidget *Analog24)
    {
        if (Analog24->objectName().isEmpty())
            Analog24->setObjectName(QString::fromUtf8("Analog24"));
        Analog24->resize(485, 590);
        Analog24->setMinimumSize(QSize(485, 590));
        Analog24->setMaximumSize(QSize(485, 590));
        Analog24->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        frBarraT = new QFrame(Analog24);
        frBarraT->setObjectName(QString::fromUtf8("frBarraT"));
        frBarraT->setGeometry(QRect(1, 0, 485, 15));
        frBarraT->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frBarraT->setFrameShape(QFrame::Panel);
        frBarraT->setFrameShadow(QFrame::Raised);
        frBarraT->setLineWidth(0);
        lbAna24T = new QLabel(frBarraT);
        lbAna24T->setObjectName(QString::fromUtf8("lbAna24T"));
        lbAna24T->setGeometry(QRect(3, 0, 81, 12));
        QFont font;
        font.setPointSize(5);
        font.setBold(true);
        font.setWeight(75);
        lbAna24T->setFont(font);
        lbAna24T->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        lbSloAl = new QLabel(Analog24);
        lbSloAl->setObjectName(QString::fromUtf8("lbSloAl"));
        lbSloAl->setGeometry(QRect(65, 24, 400, 22));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        lbSloAl->setFont(font1);
        lbSloAl->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        frame = new QFrame(Analog24);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(1, 20, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        btnCerrar = new QPushButton(Analog24);
        btnCerrar->setObjectName(QString::fromUtf8("btnCerrar"));
        btnCerrar->setGeometry(QRect(123, 540, 101, 41));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        btnCerrar->setFont(font2);
        btnCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnProx = new QPushButton(Analog24);
        btnProx->setObjectName(QString::fromUtf8("btnProx"));
        btnProx->setGeometry(QRect(273, 540, 101, 41));
        btnProx->setFont(font2);
        btnProx->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbNumAI_1 = new QLabel(Analog24);
        lbNumAI_1->setObjectName(QString::fromUtf8("lbNumAI_1"));
        lbNumAI_1->setGeometry(QRect(8, 55, 21, 16));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setBold(true);
        font3.setWeight(75);
        lbNumAI_1->setFont(font3);
        lbNumAI_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_1->setAlignment(Qt::AlignCenter);
        lbAIU_1 = new QLabel(Analog24);
        lbAIU_1->setObjectName(QString::fromUtf8("lbAIU_1"));
        lbAIU_1->setGeometry(QRect(436, 55, 31, 20));
        lbAIU_1->setFont(font3);
        lbAIU_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_1 = new QLabel(Analog24);
        lbAIT_1->setObjectName(QString::fromUtf8("lbAIT_1"));
        lbAIT_1->setGeometry(QRect(33, 55, 340, 16));
        lbAIT_1->setFont(font3);
        lbAI_1 = new QLabel(Analog24);
        lbAI_1->setObjectName(QString::fromUtf8("lbAI_1"));
        lbAI_1->setGeometry(QRect(365, 55, 59, 20));
        lbAI_1->setFont(font3);
        lbAI_1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIU_2 = new QLabel(Analog24);
        lbAIU_2->setObjectName(QString::fromUtf8("lbAIU_2"));
        lbAIU_2->setGeometry(QRect(436, 75, 31, 20));
        lbAIU_2->setFont(font3);
        lbAIU_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_2 = new QLabel(Analog24);
        lbAIT_2->setObjectName(QString::fromUtf8("lbAIT_2"));
        lbAIT_2->setGeometry(QRect(33, 75, 340, 16));
        lbAIT_2->setFont(font3);
        lbAI_2 = new QLabel(Analog24);
        lbAI_2->setObjectName(QString::fromUtf8("lbAI_2"));
        lbAI_2->setGeometry(QRect(365, 75, 59, 20));
        lbAI_2->setFont(font3);
        lbAI_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumAI_2 = new QLabel(Analog24);
        lbNumAI_2->setObjectName(QString::fromUtf8("lbNumAI_2"));
        lbNumAI_2->setGeometry(QRect(8, 75, 21, 16));
        lbNumAI_2->setFont(font3);
        lbNumAI_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_2->setAlignment(Qt::AlignCenter);
        lbNumAI_3 = new QLabel(Analog24);
        lbNumAI_3->setObjectName(QString::fromUtf8("lbNumAI_3"));
        lbNumAI_3->setGeometry(QRect(10, 95, 21, 16));
        lbNumAI_3->setFont(font3);
        lbNumAI_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_3->setAlignment(Qt::AlignCenter);
        lbAIU_3 = new QLabel(Analog24);
        lbAIU_3->setObjectName(QString::fromUtf8("lbAIU_3"));
        lbAIU_3->setGeometry(QRect(436, 95, 31, 20));
        lbAIU_3->setFont(font3);
        lbAIU_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_3 = new QLabel(Analog24);
        lbAI_3->setObjectName(QString::fromUtf8("lbAI_3"));
        lbAI_3->setGeometry(QRect(367, 95, 59, 20));
        lbAI_3->setFont(font3);
        lbAI_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_3 = new QLabel(Analog24);
        lbAIT_3->setObjectName(QString::fromUtf8("lbAIT_3"));
        lbAIT_3->setGeometry(QRect(35, 95, 340, 16));
        lbAIT_3->setFont(font3);
        lbNumAI_4 = new QLabel(Analog24);
        lbNumAI_4->setObjectName(QString::fromUtf8("lbNumAI_4"));
        lbNumAI_4->setGeometry(QRect(10, 115, 21, 16));
        lbNumAI_4->setFont(font3);
        lbNumAI_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_4->setAlignment(Qt::AlignCenter);
        lbAIU_4 = new QLabel(Analog24);
        lbAIU_4->setObjectName(QString::fromUtf8("lbAIU_4"));
        lbAIU_4->setGeometry(QRect(436, 115, 31, 20));
        lbAIU_4->setFont(font3);
        lbAIU_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_4 = new QLabel(Analog24);
        lbAIT_4->setObjectName(QString::fromUtf8("lbAIT_4"));
        lbAIT_4->setGeometry(QRect(35, 115, 340, 16));
        lbAIT_4->setFont(font3);
        lbAI_4 = new QLabel(Analog24);
        lbAI_4->setObjectName(QString::fromUtf8("lbAI_4"));
        lbAI_4->setGeometry(QRect(367, 115, 59, 20));
        lbAI_4->setFont(font3);
        lbAI_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumAI_5 = new QLabel(Analog24);
        lbNumAI_5->setObjectName(QString::fromUtf8("lbNumAI_5"));
        lbNumAI_5->setGeometry(QRect(10, 135, 21, 16));
        lbNumAI_5->setFont(font3);
        lbNumAI_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_5->setAlignment(Qt::AlignCenter);
        lbAI_5 = new QLabel(Analog24);
        lbAI_5->setObjectName(QString::fromUtf8("lbAI_5"));
        lbAI_5->setGeometry(QRect(367, 135, 59, 20));
        lbAI_5->setFont(font3);
        lbAI_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIU_5 = new QLabel(Analog24);
        lbAIU_5->setObjectName(QString::fromUtf8("lbAIU_5"));
        lbAIU_5->setGeometry(QRect(436, 135, 31, 20));
        lbAIU_5->setFont(font3);
        lbAIU_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_5 = new QLabel(Analog24);
        lbAIT_5->setObjectName(QString::fromUtf8("lbAIT_5"));
        lbAIT_5->setGeometry(QRect(35, 135, 340, 16));
        lbAIT_5->setFont(font3);
        lbAIU_6 = new QLabel(Analog24);
        lbAIU_6->setObjectName(QString::fromUtf8("lbAIU_6"));
        lbAIU_6->setGeometry(QRect(436, 155, 31, 20));
        lbAIU_6->setFont(font3);
        lbAIU_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_6 = new QLabel(Analog24);
        lbAI_6->setObjectName(QString::fromUtf8("lbAI_6"));
        lbAI_6->setGeometry(QRect(365, 155, 59, 20));
        lbAI_6->setFont(font3);
        lbAI_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumAI_6 = new QLabel(Analog24);
        lbNumAI_6->setObjectName(QString::fromUtf8("lbNumAI_6"));
        lbNumAI_6->setGeometry(QRect(10, 155, 21, 16));
        lbNumAI_6->setFont(font3);
        lbNumAI_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_6->setAlignment(Qt::AlignCenter);
        lbAIT_6 = new QLabel(Analog24);
        lbAIT_6->setObjectName(QString::fromUtf8("lbAIT_6"));
        lbAIT_6->setGeometry(QRect(33, 155, 340, 16));
        lbAIT_6->setFont(font3);
        lbNumAI_7 = new QLabel(Analog24);
        lbNumAI_7->setObjectName(QString::fromUtf8("lbNumAI_7"));
        lbNumAI_7->setGeometry(QRect(10, 175, 21, 16));
        lbNumAI_7->setFont(font3);
        lbNumAI_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_7->setAlignment(Qt::AlignCenter);
        lbAIU_7 = new QLabel(Analog24);
        lbAIU_7->setObjectName(QString::fromUtf8("lbAIU_7"));
        lbAIU_7->setGeometry(QRect(436, 175, 31, 20));
        lbAIU_7->setFont(font3);
        lbAIU_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_7 = new QLabel(Analog24);
        lbAI_7->setObjectName(QString::fromUtf8("lbAI_7"));
        lbAI_7->setGeometry(QRect(365, 175, 61, 20));
        lbAI_7->setFont(font3);
        lbAI_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_7 = new QLabel(Analog24);
        lbAIT_7->setObjectName(QString::fromUtf8("lbAIT_7"));
        lbAIT_7->setGeometry(QRect(35, 175, 340, 16));
        lbAIT_7->setFont(font3);
        lbNumAI_8 = new QLabel(Analog24);
        lbNumAI_8->setObjectName(QString::fromUtf8("lbNumAI_8"));
        lbNumAI_8->setGeometry(QRect(10, 195, 21, 16));
        lbNumAI_8->setFont(font3);
        lbNumAI_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_8->setAlignment(Qt::AlignCenter);
        lbAIU_8 = new QLabel(Analog24);
        lbAIU_8->setObjectName(QString::fromUtf8("lbAIU_8"));
        lbAIU_8->setGeometry(QRect(436, 195, 31, 20));
        lbAIU_8->setFont(font3);
        lbAIU_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_8 = new QLabel(Analog24);
        lbAIT_8->setObjectName(QString::fromUtf8("lbAIT_8"));
        lbAIT_8->setGeometry(QRect(35, 195, 340, 16));
        lbAIT_8->setFont(font3);
        lbAI_8 = new QLabel(Analog24);
        lbAI_8->setObjectName(QString::fromUtf8("lbAI_8"));
        lbAI_8->setGeometry(QRect(365, 195, 61, 20));
        lbAI_8->setFont(font3);
        lbAI_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumAI_9 = new QLabel(Analog24);
        lbNumAI_9->setObjectName(QString::fromUtf8("lbNumAI_9"));
        lbNumAI_9->setGeometry(QRect(10, 215, 21, 16));
        lbNumAI_9->setFont(font3);
        lbNumAI_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_9->setAlignment(Qt::AlignCenter);
        lbAIU_9 = new QLabel(Analog24);
        lbAIU_9->setObjectName(QString::fromUtf8("lbAIU_9"));
        lbAIU_9->setGeometry(QRect(436, 215, 31, 20));
        lbAIU_9->setFont(font3);
        lbAIU_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_9 = new QLabel(Analog24);
        lbAI_9->setObjectName(QString::fromUtf8("lbAI_9"));
        lbAI_9->setGeometry(QRect(365, 215, 61, 20));
        lbAI_9->setFont(font3);
        lbAI_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_9 = new QLabel(Analog24);
        lbAIT_9->setObjectName(QString::fromUtf8("lbAIT_9"));
        lbAIT_9->setGeometry(QRect(35, 215, 340, 16));
        lbAIT_9->setFont(font3);
        lbNumAI_10 = new QLabel(Analog24);
        lbNumAI_10->setObjectName(QString::fromUtf8("lbNumAI_10"));
        lbNumAI_10->setGeometry(QRect(10, 237, 21, 16));
        lbNumAI_10->setFont(font3);
        lbNumAI_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_10->setAlignment(Qt::AlignCenter);
        lbAIT_10 = new QLabel(Analog24);
        lbAIT_10->setObjectName(QString::fromUtf8("lbAIT_10"));
        lbAIT_10->setGeometry(QRect(35, 237, 340, 16));
        lbAIT_10->setFont(font3);
        lbAI_10 = new QLabel(Analog24);
        lbAI_10->setObjectName(QString::fromUtf8("lbAI_10"));
        lbAI_10->setGeometry(QRect(365, 237, 61, 20));
        lbAI_10->setFont(font3);
        lbAI_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIU_10 = new QLabel(Analog24);
        lbAIU_10->setObjectName(QString::fromUtf8("lbAIU_10"));
        lbAIU_10->setGeometry(QRect(436, 237, 31, 20));
        lbAIU_10->setFont(font3);
        lbAIU_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_11 = new QLabel(Analog24);
        lbNumAI_11->setObjectName(QString::fromUtf8("lbNumAI_11"));
        lbNumAI_11->setGeometry(QRect(10, 255, 21, 16));
        lbNumAI_11->setFont(font3);
        lbNumAI_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_11->setAlignment(Qt::AlignCenter);
        lbAI_11 = new QLabel(Analog24);
        lbAI_11->setObjectName(QString::fromUtf8("lbAI_11"));
        lbAI_11->setGeometry(QRect(365, 255, 61, 20));
        lbAI_11->setFont(font3);
        lbAI_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_11 = new QLabel(Analog24);
        lbAIT_11->setObjectName(QString::fromUtf8("lbAIT_11"));
        lbAIT_11->setGeometry(QRect(35, 255, 340, 16));
        lbAIT_11->setFont(font3);
        lbAIU_11 = new QLabel(Analog24);
        lbAIU_11->setObjectName(QString::fromUtf8("lbAIU_11"));
        lbAIU_11->setGeometry(QRect(436, 255, 31, 20));
        lbAIU_11->setFont(font3);
        lbAIU_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_12 = new QLabel(Analog24);
        lbNumAI_12->setObjectName(QString::fromUtf8("lbNumAI_12"));
        lbNumAI_12->setGeometry(QRect(10, 275, 21, 16));
        lbNumAI_12->setFont(font3);
        lbNumAI_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_12->setAlignment(Qt::AlignCenter);
        lbAI_12 = new QLabel(Analog24);
        lbAI_12->setObjectName(QString::fromUtf8("lbAI_12"));
        lbAI_12->setGeometry(QRect(365, 275, 61, 20));
        lbAI_12->setFont(font3);
        lbAI_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIU_12 = new QLabel(Analog24);
        lbAIU_12->setObjectName(QString::fromUtf8("lbAIU_12"));
        lbAIU_12->setGeometry(QRect(436, 275, 31, 20));
        lbAIU_12->setFont(font3);
        lbAIU_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_12 = new QLabel(Analog24);
        lbAIT_12->setObjectName(QString::fromUtf8("lbAIT_12"));
        lbAIT_12->setGeometry(QRect(35, 275, 340, 16));
        lbAIT_12->setFont(font3);
        lbNumAI_13 = new QLabel(Analog24);
        lbNumAI_13->setObjectName(QString::fromUtf8("lbNumAI_13"));
        lbNumAI_13->setGeometry(QRect(10, 295, 21, 16));
        lbNumAI_13->setFont(font3);
        lbNumAI_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_13->setAlignment(Qt::AlignCenter);
        lbAIU_13 = new QLabel(Analog24);
        lbAIU_13->setObjectName(QString::fromUtf8("lbAIU_13"));
        lbAIU_13->setGeometry(QRect(436, 295, 31, 20));
        lbAIU_13->setFont(font3);
        lbAIU_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_13 = new QLabel(Analog24);
        lbAI_13->setObjectName(QString::fromUtf8("lbAI_13"));
        lbAI_13->setGeometry(QRect(365, 295, 61, 20));
        lbAI_13->setFont(font3);
        lbAI_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_13 = new QLabel(Analog24);
        lbAIT_13->setObjectName(QString::fromUtf8("lbAIT_13"));
        lbAIT_13->setGeometry(QRect(35, 295, 340, 16));
        lbAIT_13->setFont(font3);
        lbNumAI_14 = new QLabel(Analog24);
        lbNumAI_14->setObjectName(QString::fromUtf8("lbNumAI_14"));
        lbNumAI_14->setGeometry(QRect(10, 315, 21, 16));
        lbNumAI_14->setFont(font3);
        lbNumAI_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_14->setAlignment(Qt::AlignCenter);
        lbAIT_14 = new QLabel(Analog24);
        lbAIT_14->setObjectName(QString::fromUtf8("lbAIT_14"));
        lbAIT_14->setGeometry(QRect(35, 315, 340, 16));
        lbAIT_14->setFont(font3);
        lbAI_14 = new QLabel(Analog24);
        lbAI_14->setObjectName(QString::fromUtf8("lbAI_14"));
        lbAI_14->setGeometry(QRect(365, 315, 61, 20));
        lbAI_14->setFont(font3);
        lbAI_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIU_14 = new QLabel(Analog24);
        lbAIU_14->setObjectName(QString::fromUtf8("lbAIU_14"));
        lbAIU_14->setGeometry(QRect(436, 315, 31, 20));
        lbAIU_14->setFont(font3);
        lbAIU_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_15 = new QLabel(Analog24);
        lbNumAI_15->setObjectName(QString::fromUtf8("lbNumAI_15"));
        lbNumAI_15->setGeometry(QRect(10, 335, 21, 16));
        lbNumAI_15->setFont(font3);
        lbNumAI_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_15->setAlignment(Qt::AlignCenter);
        lbAI_15 = new QLabel(Analog24);
        lbAI_15->setObjectName(QString::fromUtf8("lbAI_15"));
        lbAI_15->setGeometry(QRect(365, 335, 61, 20));
        lbAI_15->setFont(font3);
        lbAI_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_15 = new QLabel(Analog24);
        lbAIT_15->setObjectName(QString::fromUtf8("lbAIT_15"));
        lbAIT_15->setGeometry(QRect(35, 335, 340, 16));
        lbAIT_15->setFont(font3);
        lbAIU_15 = new QLabel(Analog24);
        lbAIU_15->setObjectName(QString::fromUtf8("lbAIU_15"));
        lbAIU_15->setGeometry(QRect(436, 335, 31, 20));
        lbAIU_15->setFont(font3);
        lbAIU_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_16 = new QLabel(Analog24);
        lbNumAI_16->setObjectName(QString::fromUtf8("lbNumAI_16"));
        lbNumAI_16->setGeometry(QRect(10, 355, 21, 16));
        lbNumAI_16->setFont(font3);
        lbNumAI_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_16->setAlignment(Qt::AlignCenter);
        lbAIT_16 = new QLabel(Analog24);
        lbAIT_16->setObjectName(QString::fromUtf8("lbAIT_16"));
        lbAIT_16->setGeometry(QRect(35, 355, 340, 16));
        lbAIT_16->setFont(font3);
        lbAI_16 = new QLabel(Analog24);
        lbAI_16->setObjectName(QString::fromUtf8("lbAI_16"));
        lbAI_16->setGeometry(QRect(365, 355, 61, 20));
        lbAI_16->setFont(font3);
        lbAI_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIU_16 = new QLabel(Analog24);
        lbAIU_16->setObjectName(QString::fromUtf8("lbAIU_16"));
        lbAIU_16->setGeometry(QRect(436, 355, 31, 20));
        lbAIU_16->setFont(font3);
        lbAIU_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_17 = new QLabel(Analog24);
        lbNumAI_17->setObjectName(QString::fromUtf8("lbNumAI_17"));
        lbNumAI_17->setGeometry(QRect(10, 375, 21, 16));
        lbNumAI_17->setFont(font3);
        lbNumAI_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_17->setAlignment(Qt::AlignCenter);
        lbAIU_17 = new QLabel(Analog24);
        lbAIU_17->setObjectName(QString::fromUtf8("lbAIU_17"));
        lbAIU_17->setGeometry(QRect(436, 375, 31, 20));
        lbAIU_17->setFont(font3);
        lbAIU_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_17 = new QLabel(Analog24);
        lbAI_17->setObjectName(QString::fromUtf8("lbAI_17"));
        lbAI_17->setGeometry(QRect(365, 375, 61, 20));
        lbAI_17->setFont(font3);
        lbAI_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_17 = new QLabel(Analog24);
        lbAIT_17->setObjectName(QString::fromUtf8("lbAIT_17"));
        lbAIT_17->setGeometry(QRect(35, 375, 340, 16));
        lbAIT_17->setFont(font3);
        lbNumAI_18 = new QLabel(Analog24);
        lbNumAI_18->setObjectName(QString::fromUtf8("lbNumAI_18"));
        lbNumAI_18->setGeometry(QRect(10, 395, 21, 16));
        lbNumAI_18->setFont(font3);
        lbNumAI_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_18->setAlignment(Qt::AlignCenter);
        lbAI_18 = new QLabel(Analog24);
        lbAI_18->setObjectName(QString::fromUtf8("lbAI_18"));
        lbAI_18->setGeometry(QRect(365, 395, 61, 20));
        lbAI_18->setFont(font3);
        lbAI_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIU_18 = new QLabel(Analog24);
        lbAIU_18->setObjectName(QString::fromUtf8("lbAIU_18"));
        lbAIU_18->setGeometry(QRect(436, 395, 31, 20));
        lbAIU_18->setFont(font3);
        lbAIU_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_18 = new QLabel(Analog24);
        lbAIT_18->setObjectName(QString::fromUtf8("lbAIT_18"));
        lbAIT_18->setGeometry(QRect(35, 395, 340, 16));
        lbAIT_18->setFont(font3);
        lbNumAI_19 = new QLabel(Analog24);
        lbNumAI_19->setObjectName(QString::fromUtf8("lbNumAI_19"));
        lbNumAI_19->setGeometry(QRect(10, 415, 21, 16));
        lbNumAI_19->setFont(font3);
        lbNumAI_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_19->setAlignment(Qt::AlignCenter);
        lbAIT_19 = new QLabel(Analog24);
        lbAIT_19->setObjectName(QString::fromUtf8("lbAIT_19"));
        lbAIT_19->setGeometry(QRect(35, 415, 340, 16));
        lbAIT_19->setFont(font3);
        lbAIU_19 = new QLabel(Analog24);
        lbAIU_19->setObjectName(QString::fromUtf8("lbAIU_19"));
        lbAIU_19->setGeometry(QRect(436, 415, 31, 20));
        lbAIU_19->setFont(font3);
        lbAIU_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_19 = new QLabel(Analog24);
        lbAI_19->setObjectName(QString::fromUtf8("lbAI_19"));
        lbAI_19->setGeometry(QRect(365, 415, 61, 20));
        lbAI_19->setFont(font3);
        lbAI_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumAI_20 = new QLabel(Analog24);
        lbNumAI_20->setObjectName(QString::fromUtf8("lbNumAI_20"));
        lbNumAI_20->setGeometry(QRect(10, 435, 21, 16));
        lbNumAI_20->setFont(font3);
        lbNumAI_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_20->setAlignment(Qt::AlignCenter);
        lbAIU_20 = new QLabel(Analog24);
        lbAIU_20->setObjectName(QString::fromUtf8("lbAIU_20"));
        lbAIU_20->setGeometry(QRect(435, 435, 51, 20));
        lbAIU_20->setFont(font3);
        lbAIU_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_20 = new QLabel(Analog24);
        lbAIT_20->setObjectName(QString::fromUtf8("lbAIT_20"));
        lbAIT_20->setGeometry(QRect(35, 435, 311, 16));
        lbAIT_20->setFont(font3);
        lbAI_20 = new QLabel(Analog24);
        lbAI_20->setObjectName(QString::fromUtf8("lbAI_20"));
        lbAI_20->setGeometry(QRect(365, 435, 61, 20));
        lbAI_20->setFont(font3);
        lbAI_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumAI_21 = new QLabel(Analog24);
        lbNumAI_21->setObjectName(QString::fromUtf8("lbNumAI_21"));
        lbNumAI_21->setGeometry(QRect(10, 455, 21, 16));
        lbNumAI_21->setFont(font3);
        lbNumAI_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_21->setAlignment(Qt::AlignCenter);
        lbAIU_21 = new QLabel(Analog24);
        lbAIU_21->setObjectName(QString::fromUtf8("lbAIU_21"));
        lbAIU_21->setGeometry(QRect(435, 455, 51, 20));
        lbAIU_21->setFont(font3);
        lbAIU_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_21 = new QLabel(Analog24);
        lbAI_21->setObjectName(QString::fromUtf8("lbAI_21"));
        lbAI_21->setGeometry(QRect(365, 455, 61, 20));
        lbAI_21->setFont(font3);
        lbAI_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_21 = new QLabel(Analog24);
        lbAIT_21->setObjectName(QString::fromUtf8("lbAIT_21"));
        lbAIT_21->setGeometry(QRect(35, 455, 311, 16));
        lbAIT_21->setFont(font3);
        lbNumAI_22 = new QLabel(Analog24);
        lbNumAI_22->setObjectName(QString::fromUtf8("lbNumAI_22"));
        lbNumAI_22->setGeometry(QRect(10, 475, 21, 16));
        lbNumAI_22->setFont(font3);
        lbNumAI_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_22->setAlignment(Qt::AlignCenter);
        lbAIU_22 = new QLabel(Analog24);
        lbAIU_22->setObjectName(QString::fromUtf8("lbAIU_22"));
        lbAIU_22->setGeometry(QRect(435, 475, 51, 20));
        lbAIU_22->setFont(font3);
        lbAIU_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAIT_22 = new QLabel(Analog24);
        lbAIT_22->setObjectName(QString::fromUtf8("lbAIT_22"));
        lbAIT_22->setGeometry(QRect(35, 475, 311, 16));
        lbAIT_22->setFont(font3);
        lbAI_22 = new QLabel(Analog24);
        lbAI_22->setObjectName(QString::fromUtf8("lbAI_22"));
        lbAI_22->setGeometry(QRect(365, 475, 61, 20));
        lbAI_22->setFont(font3);
        lbAI_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumAI_23 = new QLabel(Analog24);
        lbNumAI_23->setObjectName(QString::fromUtf8("lbNumAI_23"));
        lbNumAI_23->setGeometry(QRect(10, 495, 21, 16));
        lbNumAI_23->setFont(font3);
        lbNumAI_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_23->setAlignment(Qt::AlignCenter);
        lbAIU_23 = new QLabel(Analog24);
        lbAIU_23->setObjectName(QString::fromUtf8("lbAIU_23"));
        lbAIU_23->setGeometry(QRect(435, 495, 51, 20));
        lbAIU_23->setFont(font3);
        lbAIU_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbAI_23 = new QLabel(Analog24);
        lbAI_23->setObjectName(QString::fromUtf8("lbAI_23"));
        lbAI_23->setGeometry(QRect(365, 495, 61, 20));
        lbAI_23->setFont(font3);
        lbAI_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbAIT_23 = new QLabel(Analog24);
        lbAIT_23->setObjectName(QString::fromUtf8("lbAIT_23"));
        lbAIT_23->setGeometry(QRect(35, 495, 311, 16));
        lbAIT_23->setFont(font3);
        lbAIU_24 = new QLabel(Analog24);
        lbAIU_24->setObjectName(QString::fromUtf8("lbAIU_24"));
        lbAIU_24->setGeometry(QRect(435, 515, 51, 20));
        lbAIU_24->setFont(font3);
        lbAIU_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_24 = new QLabel(Analog24);
        lbNumAI_24->setObjectName(QString::fromUtf8("lbNumAI_24"));
        lbNumAI_24->setGeometry(QRect(10, 515, 21, 16));
        lbNumAI_24->setFont(font3);
        lbNumAI_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumAI_24->setAlignment(Qt::AlignCenter);
        lbAIT_24 = new QLabel(Analog24);
        lbAIT_24->setObjectName(QString::fromUtf8("lbAIT_24"));
        lbAIT_24->setGeometry(QRect(35, 515, 311, 16));
        lbAIT_24->setFont(font3);
        lbAI_24 = new QLabel(Analog24);
        lbAI_24->setObjectName(QString::fromUtf8("lbAI_24"));
        lbAI_24->setGeometry(QRect(365, 515, 61, 20));
        lbAI_24->setFont(font3);
        lbAI_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame->raise();
        frBarraT->raise();
        lbSloAl->raise();
        btnCerrar->raise();
        btnProx->raise();
        lbNumAI_1->raise();
        lbAIU_1->raise();
        lbAIT_1->raise();
        lbAI_1->raise();
        lbAIU_2->raise();
        lbAIT_2->raise();
        lbAI_2->raise();
        lbNumAI_2->raise();
        lbNumAI_3->raise();
        lbAIU_3->raise();
        lbAI_3->raise();
        lbAIT_3->raise();
        lbNumAI_4->raise();
        lbAIU_4->raise();
        lbAIT_4->raise();
        lbAI_4->raise();
        lbNumAI_5->raise();
        lbAI_5->raise();
        lbAIU_5->raise();
        lbAIT_5->raise();
        lbAIU_6->raise();
        lbAI_6->raise();
        lbNumAI_6->raise();
        lbAIT_6->raise();
        lbNumAI_7->raise();
        lbAIU_7->raise();
        lbAI_7->raise();
        lbAIT_7->raise();
        lbNumAI_8->raise();
        lbAIU_8->raise();
        lbAIT_8->raise();
        lbAI_8->raise();
        lbNumAI_9->raise();
        lbAIU_9->raise();
        lbAI_9->raise();
        lbAIT_9->raise();
        lbNumAI_10->raise();
        lbAIT_10->raise();
        lbAI_10->raise();
        lbAIU_10->raise();
        lbNumAI_11->raise();
        lbAI_11->raise();
        lbAIT_11->raise();
        lbAIU_11->raise();
        lbNumAI_12->raise();
        lbAI_12->raise();
        lbAIU_12->raise();
        lbAIT_12->raise();
        lbNumAI_13->raise();
        lbAIU_13->raise();
        lbAI_13->raise();
        lbAIT_13->raise();
        lbNumAI_14->raise();
        lbAIT_14->raise();
        lbAI_14->raise();
        lbAIU_14->raise();
        lbNumAI_15->raise();
        lbAI_15->raise();
        lbAIT_15->raise();
        lbAIU_15->raise();
        lbNumAI_16->raise();
        lbAIT_16->raise();
        lbAI_16->raise();
        lbAIU_16->raise();
        lbNumAI_17->raise();
        lbAIU_17->raise();
        lbAI_17->raise();
        lbAIT_17->raise();
        lbNumAI_18->raise();
        lbAI_18->raise();
        lbAIU_18->raise();
        lbAIT_18->raise();
        lbNumAI_19->raise();
        lbAIT_19->raise();
        lbAIU_19->raise();
        lbAI_19->raise();
        lbNumAI_20->raise();
        lbAIU_20->raise();
        lbAIT_20->raise();
        lbAI_20->raise();
        lbNumAI_21->raise();
        lbAIU_21->raise();
        lbAI_21->raise();
        lbAIT_21->raise();
        lbNumAI_22->raise();
        lbAIU_22->raise();
        lbAIT_22->raise();
        lbAI_22->raise();
        lbNumAI_23->raise();
        lbAIU_23->raise();
        lbAI_23->raise();
        lbAIT_23->raise();
        lbAIU_24->raise();
        lbNumAI_24->raise();
        lbAIT_24->raise();
        lbAI_24->raise();

        retranslateUi(Analog24);

        QMetaObject::connectSlotsByName(Analog24);
    } // setupUi

    void retranslateUi(QWidget *Analog24)
    {
        Analog24->setWindowTitle(QApplication::translate("Analog24", "Analog24", 0, QApplication::UnicodeUTF8));
        lbAna24T->setText(QApplication::translate("Analog24", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">ANALOG24.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbSloAl->setText(QApplication::translate("Analog24", "SLOT-  A106  - Al", 0, QApplication::UnicodeUTF8));
        btnCerrar->setText(QApplication::translate("Analog24", "CERRAR", 0, QApplication::UnicodeUTF8));
        btnProx->setText(QApplication::translate("Analog24", "PR\303\223X >", 0, QApplication::UnicodeUTF8));
        lbNumAI_1->setText(QApplication::translate("Analog24", "1", 0, QApplication::UnicodeUTF8));
        lbAIU_1->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_1->setText(QApplication::translate("Analog24", "TEMP DE ENTRADA DE GAS LPT T48A", 0, QApplication::UnicodeUTF8));
        lbAI_1->setText(QApplication::translate("Analog24", "1576.00", 0, QApplication::UnicodeUTF8));
        lbAIU_2->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_2->setText(QApplication::translate("Analog24", "TEMP DE ENTRADA DE GAS LPT T48C (ABAJO)", 0, QApplication::UnicodeUTF8));
        lbAI_2->setText(QApplication::translate("Analog24", "1531.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_2->setText(QApplication::translate("Analog24", "2", 0, QApplication::UnicodeUTF8));
        lbNumAI_3->setText(QApplication::translate("Analog24", "3", 0, QApplication::UnicodeUTF8));
        lbAIU_3->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_3->setText(QApplication::translate("Analog24", "1580.00", 0, QApplication::UnicodeUTF8));
        lbAIT_3->setText(QApplication::translate("Analog24", "TEMP DE ENTRADA DE GAS LPT T48E (ABAJO)", 0, QApplication::UnicodeUTF8));
        lbNumAI_4->setText(QApplication::translate("Analog24", "4", 0, QApplication::UnicodeUTF8));
        lbAIU_4->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_4->setText(QApplication::translate("Analog24", "TEMP DE ENTRADA DE GAS LPT T48G (ARRIBA)", 0, QApplication::UnicodeUTF8));
        lbAI_4->setText(QApplication::translate("Analog24", "1565.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_5->setText(QApplication::translate("Analog24", "5", 0, QApplication::UnicodeUTF8));
        lbAI_5->setText(QApplication::translate("Analog24", "981.00", 0, QApplication::UnicodeUTF8));
        lbAIU_5->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_5->setText(QApplication::translate("Analog24", "T3A1 HPC TEMP DE DESCARGA", 0, QApplication::UnicodeUTF8));
        lbAIU_6->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_6->setText(QApplication::translate("Analog24", "980.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_6->setText(QApplication::translate("Analog24", "6", 0, QApplication::UnicodeUTF8));
        lbAIT_6->setText(QApplication::translate("Analog24", "T3B1 HPC TEMP DE DESCARGA", 0, QApplication::UnicodeUTF8));
        lbNumAI_7->setText(QApplication::translate("Analog24", "7", 0, QApplication::UnicodeUTF8));
        lbAIU_7->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_7->setText(QApplication::translate("Analog24", "49.00", 0, QApplication::UnicodeUTF8));
        lbAIT_7->setText(QApplication::translate("Analog24", "T2A LPC TEMP ADMIS DE AIRE", 0, QApplication::UnicodeUTF8));
        lbNumAI_8->setText(QApplication::translate("Analog24", "8", 0, QApplication::UnicodeUTF8));
        lbAIU_8->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAIT_8->setText(QApplication::translate("Analog24", "TEMP ADMIS AIRE COMPRESOR HP T25A", 0, QApplication::UnicodeUTF8));
        lbAI_8->setText(QApplication::translate("Analog24", "216.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_9->setText(QApplication::translate("Analog24", "9", 0, QApplication::UnicodeUTF8));
        lbAIU_9->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbAI_9->setText(QApplication::translate("Analog24", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIT_9->setText(QApplication::translate("Analog24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_10->setText(QApplication::translate("Analog24", "10", 0, QApplication::UnicodeUTF8));
        lbAIT_10->setText(QApplication::translate("Analog24", "SENSOR A TEMPERATURA DE GAS COMB (TGSA)", 0, QApplication::UnicodeUTF8));
        lbAI_10->setText(QApplication::translate("Analog24", "78.00", 0, QApplication::UnicodeUTF8));
        lbAIU_10->setText(QApplication::translate("Analog24", "\302\272F", 0, QApplication::UnicodeUTF8));
        lbNumAI_11->setText(QApplication::translate("Analog24", "11", 0, QApplication::UnicodeUTF8));
        lbAI_11->setText(QApplication::translate("Analog24", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIT_11->setText(QApplication::translate("Analog24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbAIU_11->setText(QString());
        lbNumAI_12->setText(QApplication::translate("Analog24", "12", 0, QApplication::UnicodeUTF8));
        lbAI_12->setText(QApplication::translate("Analog24", "10.00", 0, QApplication::UnicodeUTF8));
        lbAIU_12->setText(QString());
        lbAIT_12->setText(QApplication::translate("Analog24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumAI_13->setText(QApplication::translate("Analog24", "13", 0, QApplication::UnicodeUTF8));
        lbAIU_13->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbAI_13->setText(QApplication::translate("Analog24", "11.00", 0, QApplication::UnicodeUTF8));
        lbAIT_13->setText(QApplication::translate("Analog24", "PRES EST\303\201TICA DE ENTRADA P0", 0, QApplication::UnicodeUTF8));
        lbNumAI_14->setText(QApplication::translate("Analog24", "14", 0, QApplication::UnicodeUTF8));
        lbAIT_14->setText(QApplication::translate("Analog24", "P25A HPC PRES TOTAL ENTRADA \"A\"", 0, QApplication::UnicodeUTF8));
        lbAI_14->setText(QApplication::translate("Analog24", "27.60", 0, QApplication::UnicodeUTF8));
        lbAIU_14->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbNumAI_15->setText(QApplication::translate("Analog24", "15", 0, QApplication::UnicodeUTF8));
        lbAI_15->setText(QApplication::translate("Analog24", "2.24", 0, QApplication::UnicodeUTF8));
        lbAIT_15->setText(QApplication::translate("Analog24", "PRESI\303\223N DIN\303\201MICA AC\303\232STICA (PX36A)", 0, QApplication::UnicodeUTF8));
        lbAIU_15->setText(QApplication::translate("Analog24", "PSID", 0, QApplication::UnicodeUTF8));
        lbNumAI_16->setText(QApplication::translate("Analog24", "16", 0, QApplication::UnicodeUTF8));
        lbAIT_16->setText(QApplication::translate("Analog24", "P48 PRES TOTAL ENTRADA TBP", 0, QApplication::UnicodeUTF8));
        lbAI_16->setText(QApplication::translate("Analog24", "78.60", 0, QApplication::UnicodeUTF8));
        lbAIU_16->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbNumAI_17->setText(QApplication::translate("Analog24", "17", 0, QApplication::UnicodeUTF8));
        lbAIU_17->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbAI_17->setText(QApplication::translate("Analog24", "64.60", 0, QApplication::UnicodeUTF8));
        lbAIT_17->setText(QApplication::translate("Analog24", "PRES DE BALANCE DE IMPULSO PTBA", 0, QApplication::UnicodeUTF8));
        lbNumAI_18->setText(QApplication::translate("Analog24", "18", 0, QApplication::UnicodeUTF8));
        lbAI_18->setText(QApplication::translate("Analog24", "0.00", 0, QApplication::UnicodeUTF8));
        lbAIU_18->setText(QApplication::translate("Analog24", "MA", 0, QApplication::UnicodeUTF8));
        lbAIT_18->setText(QApplication::translate("Analog24", "DETECTOR UV N\302\272 1 DE LLAMA DE TURBINA", 0, QApplication::UnicodeUTF8));
        lbNumAI_19->setText(QApplication::translate("Analog24", "19", 0, QApplication::UnicodeUTF8));
        lbAIT_19->setText(QApplication::translate("Analog24", "SE\303\221AL DE MW DE GEN MW", 0, QApplication::UnicodeUTF8));
        lbAIU_19->setText(QApplication::translate("Analog24", "MW", 0, QApplication::UnicodeUTF8));
        lbAI_19->setText(QApplication::translate("Analog24", "32.52", 0, QApplication::UnicodeUTF8));
        lbNumAI_20->setText(QApplication::translate("Analog24", "20", 0, QApplication::UnicodeUTF8));
        lbAIU_20->setText(QApplication::translate("Analog24", "BTU/LB", 0, QApplication::UnicodeUTF8));
        lbAIT_20->setText(QApplication::translate("Analog24", "VALOR CALOR\303\215FICO (VCB)", 0, QApplication::UnicodeUTF8));
        lbAI_20->setText(QApplication::translate("Analog24", "21370.00", 0, QApplication::UnicodeUTF8));
        lbNumAI_21->setText(QApplication::translate("Analog24", "21", 0, QApplication::UnicodeUTF8));
        lbAIU_21->setText(QApplication::translate("Analog24", "%", 0, QApplication::UnicodeUTF8));
        lbAI_21->setText(QApplication::translate("Analog24", "45.00", 0, QApplication::UnicodeUTF8));
        lbAIT_21->setText(QApplication::translate("Analog24", "VALV DE MDCION DE GAS COMB - RETRO DE Pl", 0, QApplication::UnicodeUTF8));
        lbNumAI_22->setText(QApplication::translate("Analog24", "22", 0, QApplication::UnicodeUTF8));
        lbAIU_22->setText(QApplication::translate("Analog24", "%", 0, QApplication::UnicodeUTF8));
        lbAIT_22->setText(QApplication::translate("Analog24", "VALV DE MDCION DE GAS COMB - RETRO INTER", 0, QApplication::UnicodeUTF8));
        lbAI_22->setText(QApplication::translate("Analog24", "29.10", 0, QApplication::UnicodeUTF8));
        lbNumAI_23->setText(QApplication::translate("Analog24", "23", 0, QApplication::UnicodeUTF8));
        lbAIU_23->setText(QApplication::translate("Analog24", "%", 0, QApplication::UnicodeUTF8));
        lbAI_23->setText(QApplication::translate("Analog24", "43.20", 0, QApplication::UnicodeUTF8));
        lbAIT_23->setText(QApplication::translate("Analog24", "VALV DE MDCION DE GAS COMB - RETRO EXTRN", 0, QApplication::UnicodeUTF8));
        lbAIU_24->setText(QApplication::translate("Analog24", "PSIA", 0, QApplication::UnicodeUTF8));
        lbNumAI_24->setText(QApplication::translate("Analog24", "24", 0, QApplication::UnicodeUTF8));
        lbAIT_24->setText(QApplication::translate("Analog24", "PS3A PRES ST DE DESCARGA HPC", 0, QApplication::UnicodeUTF8));
        lbAI_24->setText(QApplication::translate("Analog24", "326.20", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Analog24: public Ui_Analog24 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ANALOG24_H
