/********************************************************************************
** Form generated from reading UI file 'b7.ui'
**
** Created: Sun 13. Oct 17:32:54 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_B7_H
#define UI_B7_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "ainstrumentindicator.h"
#include "awmultiobject.h"

QT_BEGIN_NAMESPACE

class Ui_B7
{
public:
    QLabel *Descr_45;
    QLabel *Descr_46;
    QLabel *Descr_44;
    QLabel *Descr_49;
    QLabel *Descr_43;
    QLabel *label;
    QLabel *Descr_51;
    QLabel *Descr_53;
    QLabel *Descr_54;
    QLabel *Descr_50;
    QLabel *Descr_47;
    QLabel *Descr_48;
    QLabel *Descr_52;
    QLabel *lb_Lect_GP1OA;
    QLabel *lb_Unit_GP1OA;
    QLabel *lb_Unit_GP1PA;
    QLabel *lb_Lect_GP1PA;
    QLabel *lb_Lect_GP1IA;
    QLabel *lb_Unit_GP1IA;
    QLabel *lb_Unit_GP1OB;
    QLabel *lb_Lect_GP1OB;
    QLabel *lb_Unit_GP1PB;
    QLabel *lb_Lect_GP1PB;
    QLabel *lb_Unit_GP1IB;
    QLabel *lb_Lect_GP1IB;
    QLabel *lb_Unit_GP2OA;
    QLabel *lb_Lect_GP2OA;
    QLabel *lb_Unit_GP2PA;
    QLabel *lb_Lect_GP2PA;
    QLabel *lb_Lect_GP2IA;
    QLabel *lb_Unit_GP2IA;
    QLabel *lb_Lect_GP2OB;
    QLabel *lb_Unit_GP2OB;
    QLabel *lb_Lect_GP2PB;
    QLabel *lb_Unit_GP2PB;
    QLabel *lb_Lect_GP2IB;
    QLabel *lb_Unit_GP2IB;
    QLabel *lb_Unit_FC62109B;
    QLabel *lb_Unit_FC62109A;
    QLabel *lb_Lect_FC62109B;
    QLabel *lb_Lect_FC62109A;
    QLabel *lb_Unit_FC62109_RTRO;
    QLabel *lb_Lect_FC62109_DEM;
    QLabel *Descr_38;
    QLabel *lb_Unit_FC62109_DEM;
    QLabel *lb_Lect_FC62109_RTRO;
    QLabel *Descr_37;
    QLabel *label_35;
    QLabel *label_37;
    QLabel *lb_Unit_FC62108B;
    QLabel *lb_Unit_FC62108A;
    QLabel *lb_Lect_FC62108A;
    QLabel *lb_Lect_FC62108B;
    QLabel *Descr_40;
    QLabel *lb_Lect_FC62108_DEM;
    QLabel *lb_Unit_FC62108;
    QLabel *lb_Lect_FC62108_RTRO;
    QLabel *Descr_39;
    QLabel *lb_Unit_FC62108_2;
    QLabel *lb_Unit_FC62107B;
    QLabel *lb_Lect_FC62107B;
    QLabel *lb_Unit_FC62107A;
    QLabel *lb_Lect_FC62107A;
    QLabel *lb_Unit_FC62107_RTRO;
    QLabel *lb_Unit_FC62107_DEM;
    QLabel *Descr_42;
    QLabel *lb_Lect_FC62107_RTRO;
    QLabel *lb_Lect_FC62107_DEM;
    QLabel *Descr_41;
    QLabel *label_33;
    QLabel *label_39;
    QLabel *label_29;
    QLabel *label_31;
    AWMultiObject *aWMultiObject;
    AWMultiObject *aWMultiObject_2;
    AWMultiObject *aWMultiObject_3;
    AWMultiObject *aWMultiObject_4;
    AWMultiObject *aWMultiObject_5;
    AWMultiObject *aWMultiObject_6;
    AWMultiObject *aWMultiObject_7;
    AWMultiObject *aWMultiObject_8;
    AWMultiObject *aWMultiObject_9;
    AWMultiObject *aWMultiObject_10;
    AWMultiObject *aWMultiObject_11;
    AWMultiObject *aWMultiObject_12;
    AWMultiObject *aWMultiObject_13;
    AWMultiObject *aWMultiObject_14;
    AInstrumentIndicator *aInstrumentIndicator;
    AInstrumentIndicator *aInstrumentIndicator_2;
    AInstrumentIndicator *aInstrumentIndicator_3;
    AInstrumentIndicator *aInstrumentIndicator_4;
    AInstrumentIndicator *aInstrumentIndicator_5;
    AInstrumentIndicator *aInstrumentIndicator_6;
    AInstrumentIndicator *aInstrumentIndicator_7;
    AInstrumentIndicator *aInstrumentIndicator_8;
    AInstrumentIndicator *aInstrumentIndicator_9;
    AInstrumentIndicator *aInstrumentIndicator_10;
    AInstrumentIndicator *aInstrumentIndicator_11;
    AInstrumentIndicator *aInstrumentIndicator_12;
    AInstrumentIndicator *aInstrumentIndicator_13;
    AInstrumentIndicator *aInstrumentIndicator_14;
    AInstrumentIndicator *aInstrumentIndicator_15;
    AInstrumentIndicator *aInstrumentIndicator_16;
    AInstrumentIndicator *aInstrumentIndicator_17;
    AInstrumentIndicator *aInstrumentIndicator_18;
    AInstrumentIndicator *aInstrumentIndicator_19;
    AInstrumentIndicator *aInstrumentIndicator_20;
    AInstrumentIndicator *aInstrumentIndicator_21;
    AInstrumentIndicator *aInstrumentIndicator_22;
    AInstrumentIndicator *aInstrumentIndicator_23;
    AInstrumentIndicator *aInstrumentIndicator_24;
    AInstrumentIndicator *aInstrumentIndicator_27;
    AInstrumentIndicator *aInstrumentIndicator_28;
    AInstrumentIndicator *aInstrumentIndicator_29;
    AInstrumentIndicator *aInstrumentIndicator_25;
    AInstrumentIndicator *aInstrumentIndicator_30;
    AInstrumentIndicator *aInstrumentIndicator_26;
    AInstrumentIndicator *aInstrumentIndicator_31;
    AInstrumentIndicator *aInstrumentIndicator_32;
    QLabel *lbUnit3;
    QPushButton *btnIMPPant;

    void setupUi(QWidget *B7)
    {
        if (B7->objectName().isEmpty())
            B7->setObjectName(QString::fromUtf8("B7"));
        B7->resize(1024, 662);
        B7->setMinimumSize(QSize(1024, 662));
        B7->setMaximumSize(QSize(1024, 662));
        B7->setStyleSheet(QString::fromUtf8("background-color: rgb(154, 154, 154);"));
        Descr_45 = new QLabel(B7);
        Descr_45->setObjectName(QString::fromUtf8("Descr_45"));
        Descr_45->setGeometry(QRect(172, 129, 61, 22));
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        Descr_45->setFont(font);
        Descr_45->setLayoutDirection(Qt::LeftToRight);
        Descr_45->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_45->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_46 = new QLabel(B7);
        Descr_46->setObjectName(QString::fromUtf8("Descr_46"));
        Descr_46->setGeometry(QRect(172, 192, 61, 22));
        Descr_46->setFont(font);
        Descr_46->setLayoutDirection(Qt::LeftToRight);
        Descr_46->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_46->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_44 = new QLabel(B7);
        Descr_44->setObjectName(QString::fromUtf8("Descr_44"));
        Descr_44->setGeometry(QRect(172, 91, 61, 22));
        Descr_44->setFont(font);
        Descr_44->setLayoutDirection(Qt::LeftToRight);
        Descr_44->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_44->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_49 = new QLabel(B7);
        Descr_49->setObjectName(QString::fromUtf8("Descr_49"));
        Descr_49->setGeometry(QRect(172, 500, 61, 22));
        Descr_49->setFont(font);
        Descr_49->setLayoutDirection(Qt::LeftToRight);
        Descr_49->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_49->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_43 = new QLabel(B7);
        Descr_43->setObjectName(QString::fromUtf8("Descr_43"));
        Descr_43->setGeometry(QRect(172, 50, 61, 22));
        Descr_43->setFont(font);
        Descr_43->setLayoutDirection(Qt::LeftToRight);
        Descr_43->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_43->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label = new QLabel(B7);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(0, 0, 1024, 662));
        label->setMinimumSize(QSize(1024, 662));
        label->setMaximumSize(QSize(1024, 662));
        label->setStyleSheet(QString::fromUtf8("background-color: none;"));
        label->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/B7.png")));
        label->setScaledContents(true);
        Descr_51 = new QLabel(B7);
        Descr_51->setObjectName(QString::fromUtf8("Descr_51"));
        Descr_51->setGeometry(QRect(172, 577, 61, 22));
        Descr_51->setFont(font);
        Descr_51->setLayoutDirection(Qt::LeftToRight);
        Descr_51->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_51->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_53 = new QLabel(B7);
        Descr_53->setObjectName(QString::fromUtf8("Descr_53"));
        Descr_53->setGeometry(QRect(172, 399, 61, 22));
        Descr_53->setFont(font);
        Descr_53->setLayoutDirection(Qt::LeftToRight);
        Descr_53->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_53->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_54 = new QLabel(B7);
        Descr_54->setObjectName(QString::fromUtf8("Descr_54"));
        Descr_54->setGeometry(QRect(172, 438, 61, 22));
        Descr_54->setFont(font);
        Descr_54->setLayoutDirection(Qt::LeftToRight);
        Descr_54->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_54->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_50 = new QLabel(B7);
        Descr_50->setObjectName(QString::fromUtf8("Descr_50"));
        Descr_50->setGeometry(QRect(172, 538, 61, 22));
        Descr_50->setFont(font);
        Descr_50->setLayoutDirection(Qt::LeftToRight);
        Descr_50->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_50->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_47 = new QLabel(B7);
        Descr_47->setObjectName(QString::fromUtf8("Descr_47"));
        Descr_47->setGeometry(QRect(172, 230, 61, 22));
        Descr_47->setFont(font);
        Descr_47->setLayoutDirection(Qt::LeftToRight);
        Descr_47->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_47->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_48 = new QLabel(B7);
        Descr_48->setObjectName(QString::fromUtf8("Descr_48"));
        Descr_48->setGeometry(QRect(172, 268, 61, 22));
        Descr_48->setFont(font);
        Descr_48->setLayoutDirection(Qt::LeftToRight);
        Descr_48->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_48->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_52 = new QLabel(B7);
        Descr_52->setObjectName(QString::fromUtf8("Descr_52"));
        Descr_52->setGeometry(QRect(172, 360, 61, 22));
        Descr_52->setFont(font);
        Descr_52->setLayoutDirection(Qt::LeftToRight);
        Descr_52->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_52->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP1OA = new QLabel(B7);
        lb_Lect_GP1OA->setObjectName(QString::fromUtf8("lb_Lect_GP1OA"));
        lb_Lect_GP1OA->setGeometry(QRect(5, 62, 40, 18));
        lb_Lect_GP1OA->setFont(font);
        lb_Lect_GP1OA->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP1OA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP1OA->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP1OA = new QLabel(B7);
        lb_Unit_GP1OA->setObjectName(QString::fromUtf8("lb_Unit_GP1OA"));
        lb_Unit_GP1OA->setGeometry(QRect(48, 62, 35, 22));
        lb_Unit_GP1OA->setMinimumSize(QSize(35, 22));
        lb_Unit_GP1OA->setMaximumSize(QSize(35, 22));
        lb_Unit_GP1OA->setFont(font);
        lb_Unit_GP1OA->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP1OA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP1OA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_GP1PA = new QLabel(B7);
        lb_Unit_GP1PA->setObjectName(QString::fromUtf8("lb_Unit_GP1PA"));
        lb_Unit_GP1PA->setGeometry(QRect(50, 100, 35, 22));
        lb_Unit_GP1PA->setMinimumSize(QSize(35, 22));
        lb_Unit_GP1PA->setMaximumSize(QSize(35, 22));
        lb_Unit_GP1PA->setFont(font);
        lb_Unit_GP1PA->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP1PA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP1PA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP1PA = new QLabel(B7);
        lb_Lect_GP1PA->setObjectName(QString::fromUtf8("lb_Lect_GP1PA"));
        lb_Lect_GP1PA->setGeometry(QRect(5, 102, 40, 18));
        lb_Lect_GP1PA->setFont(font);
        lb_Lect_GP1PA->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP1PA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP1PA->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Lect_GP1IA = new QLabel(B7);
        lb_Lect_GP1IA->setObjectName(QString::fromUtf8("lb_Lect_GP1IA"));
        lb_Lect_GP1IA->setGeometry(QRect(5, 140, 40, 18));
        lb_Lect_GP1IA->setFont(font);
        lb_Lect_GP1IA->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP1IA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP1IA->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP1IA = new QLabel(B7);
        lb_Unit_GP1IA->setObjectName(QString::fromUtf8("lb_Unit_GP1IA"));
        lb_Unit_GP1IA->setGeometry(QRect(46, 138, 35, 22));
        lb_Unit_GP1IA->setMinimumSize(QSize(35, 22));
        lb_Unit_GP1IA->setMaximumSize(QSize(35, 22));
        lb_Unit_GP1IA->setFont(font);
        lb_Unit_GP1IA->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP1IA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP1IA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_GP1OB = new QLabel(B7);
        lb_Unit_GP1OB->setObjectName(QString::fromUtf8("lb_Unit_GP1OB"));
        lb_Unit_GP1OB->setGeometry(QRect(50, 200, 35, 22));
        lb_Unit_GP1OB->setMinimumSize(QSize(35, 22));
        lb_Unit_GP1OB->setMaximumSize(QSize(35, 22));
        lb_Unit_GP1OB->setFont(font);
        lb_Unit_GP1OB->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP1OB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP1OB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP1OB = new QLabel(B7);
        lb_Lect_GP1OB->setObjectName(QString::fromUtf8("lb_Lect_GP1OB"));
        lb_Lect_GP1OB->setGeometry(QRect(5, 202, 40, 18));
        lb_Lect_GP1OB->setFont(font);
        lb_Lect_GP1OB->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP1OB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP1OB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP1PB = new QLabel(B7);
        lb_Unit_GP1PB->setObjectName(QString::fromUtf8("lb_Unit_GP1PB"));
        lb_Unit_GP1PB->setGeometry(QRect(50, 240, 35, 22));
        lb_Unit_GP1PB->setMinimumSize(QSize(35, 22));
        lb_Unit_GP1PB->setMaximumSize(QSize(35, 22));
        lb_Unit_GP1PB->setFont(font);
        lb_Unit_GP1PB->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP1PB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP1PB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP1PB = new QLabel(B7);
        lb_Lect_GP1PB->setObjectName(QString::fromUtf8("lb_Lect_GP1PB"));
        lb_Lect_GP1PB->setGeometry(QRect(5, 242, 40, 18));
        lb_Lect_GP1PB->setFont(font);
        lb_Lect_GP1PB->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP1PB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP1PB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP1IB = new QLabel(B7);
        lb_Unit_GP1IB->setObjectName(QString::fromUtf8("lb_Unit_GP1IB"));
        lb_Unit_GP1IB->setGeometry(QRect(50, 280, 35, 22));
        lb_Unit_GP1IB->setMinimumSize(QSize(35, 22));
        lb_Unit_GP1IB->setMaximumSize(QSize(35, 22));
        lb_Unit_GP1IB->setFont(font);
        lb_Unit_GP1IB->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP1IB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP1IB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP1IB = new QLabel(B7);
        lb_Lect_GP1IB->setObjectName(QString::fromUtf8("lb_Lect_GP1IB"));
        lb_Lect_GP1IB->setGeometry(QRect(5, 282, 50, 18));
        lb_Lect_GP1IB->setMinimumSize(QSize(50, 18));
        lb_Lect_GP1IB->setMaximumSize(QSize(50, 18));
        lb_Lect_GP1IB->setFont(font);
        lb_Lect_GP1IB->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP1IB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP1IB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP2OA = new QLabel(B7);
        lb_Unit_GP2OA->setObjectName(QString::fromUtf8("lb_Unit_GP2OA"));
        lb_Unit_GP2OA->setGeometry(QRect(48, 370, 35, 22));
        lb_Unit_GP2OA->setMinimumSize(QSize(35, 22));
        lb_Unit_GP2OA->setMaximumSize(QSize(35, 22));
        lb_Unit_GP2OA->setFont(font);
        lb_Unit_GP2OA->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP2OA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP2OA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP2OA = new QLabel(B7);
        lb_Lect_GP2OA->setObjectName(QString::fromUtf8("lb_Lect_GP2OA"));
        lb_Lect_GP2OA->setGeometry(QRect(5, 372, 40, 18));
        lb_Lect_GP2OA->setFont(font);
        lb_Lect_GP2OA->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP2OA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP2OA->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP2PA = new QLabel(B7);
        lb_Unit_GP2PA->setObjectName(QString::fromUtf8("lb_Unit_GP2PA"));
        lb_Unit_GP2PA->setGeometry(QRect(50, 408, 35, 22));
        lb_Unit_GP2PA->setMinimumSize(QSize(35, 22));
        lb_Unit_GP2PA->setMaximumSize(QSize(35, 22));
        lb_Unit_GP2PA->setFont(font);
        lb_Unit_GP2PA->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP2PA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP2PA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP2PA = new QLabel(B7);
        lb_Lect_GP2PA->setObjectName(QString::fromUtf8("lb_Lect_GP2PA"));
        lb_Lect_GP2PA->setGeometry(QRect(5, 410, 40, 18));
        lb_Lect_GP2PA->setFont(font);
        lb_Lect_GP2PA->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP2PA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP2PA->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Lect_GP2IA = new QLabel(B7);
        lb_Lect_GP2IA->setObjectName(QString::fromUtf8("lb_Lect_GP2IA"));
        lb_Lect_GP2IA->setGeometry(QRect(5, 450, 40, 18));
        lb_Lect_GP2IA->setFont(font);
        lb_Lect_GP2IA->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP2IA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP2IA->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP2IA = new QLabel(B7);
        lb_Unit_GP2IA->setObjectName(QString::fromUtf8("lb_Unit_GP2IA"));
        lb_Unit_GP2IA->setGeometry(QRect(48, 447, 35, 22));
        lb_Unit_GP2IA->setMinimumSize(QSize(35, 22));
        lb_Unit_GP2IA->setMaximumSize(QSize(35, 22));
        lb_Unit_GP2IA->setFont(font);
        lb_Unit_GP2IA->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP2IA->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP2IA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP2OB = new QLabel(B7);
        lb_Lect_GP2OB->setObjectName(QString::fromUtf8("lb_Lect_GP2OB"));
        lb_Lect_GP2OB->setGeometry(QRect(5, 510, 40, 18));
        lb_Lect_GP2OB->setFont(font);
        lb_Lect_GP2OB->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP2OB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP2OB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP2OB = new QLabel(B7);
        lb_Unit_GP2OB->setObjectName(QString::fromUtf8("lb_Unit_GP2OB"));
        lb_Unit_GP2OB->setGeometry(QRect(47, 509, 35, 22));
        lb_Unit_GP2OB->setMinimumSize(QSize(35, 22));
        lb_Unit_GP2OB->setMaximumSize(QSize(35, 22));
        lb_Unit_GP2OB->setFont(font);
        lb_Unit_GP2OB->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP2OB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP2OB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP2PB = new QLabel(B7);
        lb_Lect_GP2PB->setObjectName(QString::fromUtf8("lb_Lect_GP2PB"));
        lb_Lect_GP2PB->setGeometry(QRect(5, 550, 40, 18));
        lb_Lect_GP2PB->setFont(font);
        lb_Lect_GP2PB->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP2PB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP2PB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP2PB = new QLabel(B7);
        lb_Unit_GP2PB->setObjectName(QString::fromUtf8("lb_Unit_GP2PB"));
        lb_Unit_GP2PB->setGeometry(QRect(46, 548, 35, 22));
        lb_Unit_GP2PB->setMinimumSize(QSize(35, 22));
        lb_Unit_GP2PB->setMaximumSize(QSize(35, 22));
        lb_Unit_GP2PB->setFont(font);
        lb_Unit_GP2PB->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP2PB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP2PB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_GP2IB = new QLabel(B7);
        lb_Lect_GP2IB->setObjectName(QString::fromUtf8("lb_Lect_GP2IB"));
        lb_Lect_GP2IB->setGeometry(QRect(5, 590, 50, 18));
        lb_Lect_GP2IB->setMinimumSize(QSize(50, 18));
        lb_Lect_GP2IB->setMaximumSize(QSize(50, 18));
        lb_Lect_GP2IB->setFont(font);
        lb_Lect_GP2IB->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_GP2IB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_GP2IB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_GP2IB = new QLabel(B7);
        lb_Unit_GP2IB->setObjectName(QString::fromUtf8("lb_Unit_GP2IB"));
        lb_Unit_GP2IB->setGeometry(QRect(46, 588, 35, 22));
        lb_Unit_GP2IB->setMinimumSize(QSize(35, 22));
        lb_Unit_GP2IB->setMaximumSize(QSize(35, 22));
        lb_Unit_GP2IB->setFont(font);
        lb_Unit_GP2IB->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_GP2IB->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_GP2IB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_FC62109B = new QLabel(B7);
        lb_Unit_FC62109B->setObjectName(QString::fromUtf8("lb_Unit_FC62109B"));
        lb_Unit_FC62109B->setGeometry(QRect(520, 130, 22, 22));
        lb_Unit_FC62109B->setMinimumSize(QSize(22, 22));
        lb_Unit_FC62109B->setMaximumSize(QSize(22, 22));
        lb_Unit_FC62109B->setFont(font);
        lb_Unit_FC62109B->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62109B->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62109B->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_FC62109A = new QLabel(B7);
        lb_Unit_FC62109A->setObjectName(QString::fromUtf8("lb_Unit_FC62109A"));
        lb_Unit_FC62109A->setGeometry(QRect(454, 130, 22, 22));
        lb_Unit_FC62109A->setMinimumSize(QSize(22, 22));
        lb_Unit_FC62109A->setMaximumSize(QSize(22, 22));
        lb_Unit_FC62109A->setFont(font);
        lb_Unit_FC62109A->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62109A->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62109A->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62109B = new QLabel(B7);
        lb_Lect_FC62109B->setObjectName(QString::fromUtf8("lb_Lect_FC62109B"));
        lb_Lect_FC62109B->setGeometry(QRect(484, 132, 30, 18));
        lb_Lect_FC62109B->setMinimumSize(QSize(30, 18));
        lb_Lect_FC62109B->setMaximumSize(QSize(30, 18));
        lb_Lect_FC62109B->setFont(font);
        lb_Lect_FC62109B->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62109B->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62109B->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Lect_FC62109A = new QLabel(B7);
        lb_Lect_FC62109A->setObjectName(QString::fromUtf8("lb_Lect_FC62109A"));
        lb_Lect_FC62109A->setGeometry(QRect(418, 132, 30, 18));
        lb_Lect_FC62109A->setMinimumSize(QSize(30, 18));
        lb_Lect_FC62109A->setMaximumSize(QSize(30, 18));
        lb_Lect_FC62109A->setFont(font);
        lb_Lect_FC62109A->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62109A->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62109A->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_FC62109_RTRO = new QLabel(B7);
        lb_Unit_FC62109_RTRO->setObjectName(QString::fromUtf8("lb_Unit_FC62109_RTRO"));
        lb_Unit_FC62109_RTRO->setGeometry(QRect(470, 178, 40, 22));
        lb_Unit_FC62109_RTRO->setMinimumSize(QSize(40, 22));
        lb_Unit_FC62109_RTRO->setMaximumSize(QSize(40, 22));
        lb_Unit_FC62109_RTRO->setFont(font);
        lb_Unit_FC62109_RTRO->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62109_RTRO->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62109_RTRO->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62109_DEM = new QLabel(B7);
        lb_Lect_FC62109_DEM->setObjectName(QString::fromUtf8("lb_Lect_FC62109_DEM"));
        lb_Lect_FC62109_DEM->setGeometry(QRect(422, 162, 40, 18));
        lb_Lect_FC62109_DEM->setFont(font);
        lb_Lect_FC62109_DEM->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62109_DEM->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62109_DEM->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_38 = new QLabel(B7);
        Descr_38->setObjectName(QString::fromUtf8("Descr_38"));
        Descr_38->setGeometry(QRect(317, 178, 100, 22));
        Descr_38->setFont(font);
        Descr_38->setLayoutDirection(Qt::LeftToRight);
        Descr_38->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_38->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_FC62109_DEM = new QLabel(B7);
        lb_Unit_FC62109_DEM->setObjectName(QString::fromUtf8("lb_Unit_FC62109_DEM"));
        lb_Unit_FC62109_DEM->setGeometry(QRect(470, 160, 40, 22));
        lb_Unit_FC62109_DEM->setMinimumSize(QSize(40, 22));
        lb_Unit_FC62109_DEM->setMaximumSize(QSize(40, 22));
        lb_Unit_FC62109_DEM->setFont(font);
        lb_Unit_FC62109_DEM->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62109_DEM->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62109_DEM->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62109_RTRO = new QLabel(B7);
        lb_Lect_FC62109_RTRO->setObjectName(QString::fromUtf8("lb_Lect_FC62109_RTRO"));
        lb_Lect_FC62109_RTRO->setGeometry(QRect(422, 178, 40, 18));
        lb_Lect_FC62109_RTRO->setFont(font);
        lb_Lect_FC62109_RTRO->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62109_RTRO->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62109_RTRO->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_37 = new QLabel(B7);
        Descr_37->setObjectName(QString::fromUtf8("Descr_37"));
        Descr_37->setGeometry(QRect(317, 160, 100, 22));
        Descr_37->setFont(font);
        Descr_37->setLayoutDirection(Qt::LeftToRight);
        Descr_37->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_37->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_35 = new QLabel(B7);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(580, 114, 129, 41));
        label_35->setFont(font);
        label_35->setStyleSheet(QString::fromUtf8("background-color: none;\n"
"color: rgb(255, 255, 255);"));
        label_35->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_37 = new QLabel(B7);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(544, 258, 129, 31));
        label_37->setFont(font);
        label_37->setStyleSheet(QString::fromUtf8("background-color: none;\n"
"color: rgb(255, 255, 255);"));
        label_37->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_FC62108B = new QLabel(B7);
        lb_Unit_FC62108B->setObjectName(QString::fromUtf8("lb_Unit_FC62108B"));
        lb_Unit_FC62108B->setGeometry(QRect(510, 294, 22, 22));
        lb_Unit_FC62108B->setMinimumSize(QSize(22, 22));
        lb_Unit_FC62108B->setMaximumSize(QSize(22, 22));
        lb_Unit_FC62108B->setFont(font);
        lb_Unit_FC62108B->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62108B->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62108B->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_FC62108A = new QLabel(B7);
        lb_Unit_FC62108A->setObjectName(QString::fromUtf8("lb_Unit_FC62108A"));
        lb_Unit_FC62108A->setGeometry(QRect(444, 294, 22, 22));
        lb_Unit_FC62108A->setMinimumSize(QSize(22, 22));
        lb_Unit_FC62108A->setMaximumSize(QSize(22, 22));
        lb_Unit_FC62108A->setFont(font);
        lb_Unit_FC62108A->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62108A->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62108A->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62108A = new QLabel(B7);
        lb_Lect_FC62108A->setObjectName(QString::fromUtf8("lb_Lect_FC62108A"));
        lb_Lect_FC62108A->setGeometry(QRect(408, 294, 30, 18));
        lb_Lect_FC62108A->setMinimumSize(QSize(30, 18));
        lb_Lect_FC62108A->setMaximumSize(QSize(30, 18));
        lb_Lect_FC62108A->setFont(font);
        lb_Lect_FC62108A->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62108A->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62108A->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Lect_FC62108B = new QLabel(B7);
        lb_Lect_FC62108B->setObjectName(QString::fromUtf8("lb_Lect_FC62108B"));
        lb_Lect_FC62108B->setGeometry(QRect(474, 294, 30, 18));
        lb_Lect_FC62108B->setMinimumSize(QSize(30, 18));
        lb_Lect_FC62108B->setMaximumSize(QSize(30, 18));
        lb_Lect_FC62108B->setFont(font);
        lb_Lect_FC62108B->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62108B->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62108B->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_40 = new QLabel(B7);
        Descr_40->setObjectName(QString::fromUtf8("Descr_40"));
        Descr_40->setGeometry(QRect(317, 345, 100, 22));
        Descr_40->setFont(font);
        Descr_40->setLayoutDirection(Qt::LeftToRight);
        Descr_40->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_40->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62108_DEM = new QLabel(B7);
        lb_Lect_FC62108_DEM->setObjectName(QString::fromUtf8("lb_Lect_FC62108_DEM"));
        lb_Lect_FC62108_DEM->setGeometry(QRect(422, 332, 40, 18));
        lb_Lect_FC62108_DEM->setFont(font);
        lb_Lect_FC62108_DEM->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62108_DEM->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62108_DEM->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_FC62108 = new QLabel(B7);
        lb_Unit_FC62108->setObjectName(QString::fromUtf8("lb_Unit_FC62108"));
        lb_Unit_FC62108->setGeometry(QRect(472, 330, 40, 22));
        lb_Unit_FC62108->setMinimumSize(QSize(40, 22));
        lb_Unit_FC62108->setMaximumSize(QSize(40, 22));
        lb_Unit_FC62108->setFont(font);
        lb_Unit_FC62108->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62108->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62108->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62108_RTRO = new QLabel(B7);
        lb_Lect_FC62108_RTRO->setObjectName(QString::fromUtf8("lb_Lect_FC62108_RTRO"));
        lb_Lect_FC62108_RTRO->setGeometry(QRect(422, 345, 40, 18));
        lb_Lect_FC62108_RTRO->setFont(font);
        lb_Lect_FC62108_RTRO->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62108_RTRO->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62108_RTRO->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_39 = new QLabel(B7);
        Descr_39->setObjectName(QString::fromUtf8("Descr_39"));
        Descr_39->setGeometry(QRect(317, 330, 100, 22));
        Descr_39->setFont(font);
        Descr_39->setLayoutDirection(Qt::LeftToRight);
        Descr_39->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_39->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_FC62108_2 = new QLabel(B7);
        lb_Unit_FC62108_2->setObjectName(QString::fromUtf8("lb_Unit_FC62108_2"));
        lb_Unit_FC62108_2->setGeometry(QRect(472, 345, 40, 22));
        lb_Unit_FC62108_2->setMinimumSize(QSize(40, 22));
        lb_Unit_FC62108_2->setMaximumSize(QSize(40, 22));
        lb_Unit_FC62108_2->setFont(font);
        lb_Unit_FC62108_2->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62108_2->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62108_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_FC62107B = new QLabel(B7);
        lb_Unit_FC62107B->setObjectName(QString::fromUtf8("lb_Unit_FC62107B"));
        lb_Unit_FC62107B->setGeometry(QRect(520, 462, 22, 22));
        lb_Unit_FC62107B->setMinimumSize(QSize(22, 22));
        lb_Unit_FC62107B->setMaximumSize(QSize(22, 22));
        lb_Unit_FC62107B->setFont(font);
        lb_Unit_FC62107B->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62107B->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62107B->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62107B = new QLabel(B7);
        lb_Lect_FC62107B->setObjectName(QString::fromUtf8("lb_Lect_FC62107B"));
        lb_Lect_FC62107B->setGeometry(QRect(484, 462, 30, 18));
        lb_Lect_FC62107B->setMinimumSize(QSize(30, 18));
        lb_Lect_FC62107B->setMaximumSize(QSize(30, 18));
        lb_Lect_FC62107B->setFont(font);
        lb_Lect_FC62107B->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62107B->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62107B->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_FC62107A = new QLabel(B7);
        lb_Unit_FC62107A->setObjectName(QString::fromUtf8("lb_Unit_FC62107A"));
        lb_Unit_FC62107A->setGeometry(QRect(454, 462, 22, 22));
        lb_Unit_FC62107A->setMinimumSize(QSize(22, 22));
        lb_Unit_FC62107A->setMaximumSize(QSize(22, 22));
        lb_Unit_FC62107A->setFont(font);
        lb_Unit_FC62107A->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62107A->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62107A->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62107A = new QLabel(B7);
        lb_Lect_FC62107A->setObjectName(QString::fromUtf8("lb_Lect_FC62107A"));
        lb_Lect_FC62107A->setGeometry(QRect(418, 462, 30, 18));
        lb_Lect_FC62107A->setMinimumSize(QSize(30, 18));
        lb_Lect_FC62107A->setMaximumSize(QSize(30, 18));
        lb_Lect_FC62107A->setFont(font);
        lb_Lect_FC62107A->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62107A->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62107A->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Unit_FC62107_RTRO = new QLabel(B7);
        lb_Unit_FC62107_RTRO->setObjectName(QString::fromUtf8("lb_Unit_FC62107_RTRO"));
        lb_Unit_FC62107_RTRO->setGeometry(QRect(470, 514, 40, 22));
        lb_Unit_FC62107_RTRO->setMinimumSize(QSize(40, 22));
        lb_Unit_FC62107_RTRO->setMaximumSize(QSize(40, 22));
        lb_Unit_FC62107_RTRO->setFont(font);
        lb_Unit_FC62107_RTRO->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62107_RTRO->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62107_RTRO->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Unit_FC62107_DEM = new QLabel(B7);
        lb_Unit_FC62107_DEM->setObjectName(QString::fromUtf8("lb_Unit_FC62107_DEM"));
        lb_Unit_FC62107_DEM->setGeometry(QRect(470, 500, 40, 22));
        lb_Unit_FC62107_DEM->setMinimumSize(QSize(40, 22));
        lb_Unit_FC62107_DEM->setMaximumSize(QSize(40, 22));
        lb_Unit_FC62107_DEM->setFont(font);
        lb_Unit_FC62107_DEM->setLayoutDirection(Qt::LeftToRight);
        lb_Unit_FC62107_DEM->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Unit_FC62107_DEM->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_42 = new QLabel(B7);
        Descr_42->setObjectName(QString::fromUtf8("Descr_42"));
        Descr_42->setGeometry(QRect(317, 514, 100, 22));
        Descr_42->setFont(font);
        Descr_42->setLayoutDirection(Qt::LeftToRight);
        Descr_42->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_42->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Lect_FC62107_RTRO = new QLabel(B7);
        lb_Lect_FC62107_RTRO->setObjectName(QString::fromUtf8("lb_Lect_FC62107_RTRO"));
        lb_Lect_FC62107_RTRO->setGeometry(QRect(422, 514, 40, 18));
        lb_Lect_FC62107_RTRO->setFont(font);
        lb_Lect_FC62107_RTRO->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62107_RTRO->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62107_RTRO->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Lect_FC62107_DEM = new QLabel(B7);
        lb_Lect_FC62107_DEM->setObjectName(QString::fromUtf8("lb_Lect_FC62107_DEM"));
        lb_Lect_FC62107_DEM->setGeometry(QRect(422, 502, 40, 18));
        lb_Lect_FC62107_DEM->setFont(font);
        lb_Lect_FC62107_DEM->setLayoutDirection(Qt::LeftToRight);
        lb_Lect_FC62107_DEM->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        lb_Lect_FC62107_DEM->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_41 = new QLabel(B7);
        Descr_41->setObjectName(QString::fromUtf8("Descr_41"));
        Descr_41->setGeometry(QRect(317, 500, 100, 22));
        Descr_41->setFont(font);
        Descr_41->setLayoutDirection(Qt::LeftToRight);
        Descr_41->setStyleSheet(QString::fromUtf8("background-color:none;\n"
"color: rgb(255, 255, 255);"));
        Descr_41->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_33 = new QLabel(B7);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(657, 315, 129, 31));
        label_33->setFont(font);
        label_33->setStyleSheet(QString::fromUtf8("background-color: none;\n"
"color: rgb(255, 255, 255);"));
        label_33->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_39 = new QLabel(B7);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(579, 460, 129, 31));
        label_39->setFont(font);
        label_39->setStyleSheet(QString::fromUtf8("background-color: none;\n"
"color: rgb(255, 255, 255);"));
        label_39->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_29 = new QLabel(B7);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(853, 54, 129, 31));
        label_29->setFont(font);
        label_29->setStyleSheet(QString::fromUtf8("background-color: none;\n"
"color: rgb(255, 255, 255);"));
        label_29->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_31 = new QLabel(B7);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(852, 398, 129, 31));
        label_31->setFont(font);
        label_31->setStyleSheet(QString::fromUtf8("background-color: none;\n"
"color: rgb(255, 255, 255);"));
        label_31->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        aWMultiObject = new AWMultiObject(B7);
        aWMultiObject->setObjectName(QString::fromUtf8("aWMultiObject"));
        aWMultiObject->setGeometry(QRect(375, 464, 46, 46));
        aWMultiObject->setElementType(AWMultiObject::VH2);
        aWMultiObject_2 = new AWMultiObject(B7);
        aWMultiObject_2->setObjectName(QString::fromUtf8("aWMultiObject_2"));
        aWMultiObject_2->setGeometry(QRect(375, 294, 46, 46));
        aWMultiObject_2->setElementType(AWMultiObject::VH2);
        aWMultiObject_3 = new AWMultiObject(B7);
        aWMultiObject_3->setObjectName(QString::fromUtf8("aWMultiObject_3"));
        aWMultiObject_3->setGeometry(QRect(375, 126, 46, 46));
        aWMultiObject_3->setElementType(AWMultiObject::VH2);
        aWMultiObject_4 = new AWMultiObject(B7);
        aWMultiObject_4->setObjectName(QString::fromUtf8("aWMultiObject_4"));
        aWMultiObject_4->setGeometry(QRect(590, 363, 39, 39));
        aWMultiObject_4->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_4->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_5 = new AWMultiObject(B7);
        aWMultiObject_5->setObjectName(QString::fromUtf8("aWMultiObject_5"));
        aWMultiObject_5->setGeometry(QRect(709, 58, 39, 39));
        aWMultiObject_5->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_5->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_6 = new AWMultiObject(B7);
        aWMultiObject_6->setObjectName(QString::fromUtf8("aWMultiObject_6"));
        aWMultiObject_6->setGeometry(QRect(750, 107, 39, 39));
        aWMultiObject_6->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_6->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_7 = new AWMultiObject(B7);
        aWMultiObject_7->setObjectName(QString::fromUtf8("aWMultiObject_7"));
        aWMultiObject_7->setGeometry(QRect(790, 155, 39, 39));
        aWMultiObject_7->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_7->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_8 = new AWMultiObject(B7);
        aWMultiObject_8->setObjectName(QString::fromUtf8("aWMultiObject_8"));
        aWMultiObject_8->setGeometry(QRect(750, 208, 39, 39));
        aWMultiObject_8->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_8->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_9 = new AWMultiObject(B7);
        aWMultiObject_9->setObjectName(QString::fromUtf8("aWMultiObject_9"));
        aWMultiObject_9->setGeometry(QRect(714, 257, 39, 39));
        aWMultiObject_9->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_9->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_10 = new AWMultiObject(B7);
        aWMultiObject_10->setObjectName(QString::fromUtf8("aWMultiObject_10"));
        aWMultiObject_10->setGeometry(QRect(709, 400, 39, 39));
        aWMultiObject_10->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_10->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_11 = new AWMultiObject(B7);
        aWMultiObject_11->setObjectName(QString::fromUtf8("aWMultiObject_11"));
        aWMultiObject_11->setGeometry(QRect(714, 599, 39, 39));
        aWMultiObject_11->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_11->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_12 = new AWMultiObject(B7);
        aWMultiObject_12->setObjectName(QString::fromUtf8("aWMultiObject_12"));
        aWMultiObject_12->setGeometry(QRect(790, 497, 39, 39));
        aWMultiObject_12->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_12->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_13 = new AWMultiObject(B7);
        aWMultiObject_13->setObjectName(QString::fromUtf8("aWMultiObject_13"));
        aWMultiObject_13->setGeometry(QRect(750, 550, 39, 39));
        aWMultiObject_13->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_13->setElementType(AWMultiObject::VALCUAD2);
        aWMultiObject_14 = new AWMultiObject(B7);
        aWMultiObject_14->setObjectName(QString::fromUtf8("aWMultiObject_14"));
        aWMultiObject_14->setGeometry(QRect(750, 449, 39, 39));
        aWMultiObject_14->setOrientation(AWMultEstateWidget::Degree180);
        aWMultiObject_14->setElementType(AWMultiObject::VALCUAD2);
        aInstrumentIndicator = new AInstrumentIndicator(B7);
        aInstrumentIndicator->setObjectName(QString::fromUtf8("aInstrumentIndicator"));
        aInstrumentIndicator->setGeometry(QRect(98, 568, 61, 61));
        aInstrumentIndicator->setValue(2);
        aInstrumentIndicator_2 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_2->setObjectName(QString::fromUtf8("aInstrumentIndicator_2"));
        aInstrumentIndicator_2->setGeometry(QRect(98, 530, 61, 61));
        aInstrumentIndicator_2->setValue(2);
        aInstrumentIndicator_3 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_3->setObjectName(QString::fromUtf8("aInstrumentIndicator_3"));
        aInstrumentIndicator_3->setGeometry(QRect(98, 430, 61, 61));
        aInstrumentIndicator_3->setValue(2);
        aInstrumentIndicator_4 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_4->setObjectName(QString::fromUtf8("aInstrumentIndicator_4"));
        aInstrumentIndicator_4->setGeometry(QRect(98, 392, 61, 61));
        aInstrumentIndicator_4->setValue(2);
        aInstrumentIndicator_5 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_5->setObjectName(QString::fromUtf8("aInstrumentIndicator_5"));
        aInstrumentIndicator_5->setGeometry(QRect(98, 492, 61, 61));
        aInstrumentIndicator_5->setValue(2);
        aInstrumentIndicator_6 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_6->setObjectName(QString::fromUtf8("aInstrumentIndicator_6"));
        aInstrumentIndicator_6->setGeometry(QRect(98, 352, 61, 61));
        aInstrumentIndicator_6->setValue(2);
        aInstrumentIndicator_7 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_7->setObjectName(QString::fromUtf8("aInstrumentIndicator_7"));
        aInstrumentIndicator_7->setGeometry(QRect(98, 43, 61, 61));
        aInstrumentIndicator_7->setValue(2);
        aInstrumentIndicator_8 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_8->setObjectName(QString::fromUtf8("aInstrumentIndicator_8"));
        aInstrumentIndicator_8->setGeometry(QRect(98, 262, 61, 61));
        aInstrumentIndicator_8->setValue(2);
        aInstrumentIndicator_9 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_9->setObjectName(QString::fromUtf8("aInstrumentIndicator_9"));
        aInstrumentIndicator_9->setGeometry(QRect(98, 183, 61, 61));
        aInstrumentIndicator_9->setValue(2);
        aInstrumentIndicator_10 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_10->setObjectName(QString::fromUtf8("aInstrumentIndicator_10"));
        aInstrumentIndicator_10->setGeometry(QRect(98, 223, 61, 61));
        aInstrumentIndicator_10->setValue(2);
        aInstrumentIndicator_11 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_11->setObjectName(QString::fromUtf8("aInstrumentIndicator_11"));
        aInstrumentIndicator_11->setGeometry(QRect(98, 122, 61, 61));
        aInstrumentIndicator_11->setValue(2);
        aInstrumentIndicator_12 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_12->setObjectName(QString::fromUtf8("aInstrumentIndicator_12"));
        aInstrumentIndicator_12->setGeometry(QRect(98, 82, 61, 61));
        aInstrumentIndicator_12->setValue(2);
        aInstrumentIndicator_13 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_13->setObjectName(QString::fromUtf8("aInstrumentIndicator_13"));
        aInstrumentIndicator_13->setGeometry(QRect(366, 240, 61, 61));
        aInstrumentIndicator_13->setValue(2);
        aInstrumentIndicator_13->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_14 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_14->setObjectName(QString::fromUtf8("aInstrumentIndicator_14"));
        aInstrumentIndicator_14->setGeometry(QRect(419, 240, 61, 61));
        aInstrumentIndicator_14->setValue(2);
        aInstrumentIndicator_14->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_15 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_15->setObjectName(QString::fromUtf8("aInstrumentIndicator_15"));
        aInstrumentIndicator_15->setGeometry(QRect(473, 240, 61, 61));
        aInstrumentIndicator_15->setValue(2);
        aInstrumentIndicator_15->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_16 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_16->setObjectName(QString::fromUtf8("aInstrumentIndicator_16"));
        aInstrumentIndicator_16->setGeometry(QRect(419, 410, 61, 61));
        aInstrumentIndicator_16->setValue(2);
        aInstrumentIndicator_16->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_17 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_17->setObjectName(QString::fromUtf8("aInstrumentIndicator_17"));
        aInstrumentIndicator_17->setGeometry(QRect(473, 410, 61, 61));
        aInstrumentIndicator_17->setValue(2);
        aInstrumentIndicator_17->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_18 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_18->setObjectName(QString::fromUtf8("aInstrumentIndicator_18"));
        aInstrumentIndicator_18->setGeometry(QRect(366, 410, 61, 61));
        aInstrumentIndicator_18->setValue(2);
        aInstrumentIndicator_18->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_19 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_19->setObjectName(QString::fromUtf8("aInstrumentIndicator_19"));
        aInstrumentIndicator_19->setGeometry(QRect(473, 70, 61, 61));
        aInstrumentIndicator_19->setValue(2);
        aInstrumentIndicator_19->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_20 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_20->setObjectName(QString::fromUtf8("aInstrumentIndicator_20"));
        aInstrumentIndicator_20->setGeometry(QRect(366, 70, 61, 61));
        aInstrumentIndicator_20->setValue(2);
        aInstrumentIndicator_20->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_21 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_21->setObjectName(QString::fromUtf8("aInstrumentIndicator_21"));
        aInstrumentIndicator_21->setGeometry(QRect(419, 70, 61, 61));
        aInstrumentIndicator_21->setValue(2);
        aInstrumentIndicator_21->setOrientation(AWMultEstateWidget::Degree90);
        aInstrumentIndicator_22 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_22->setObjectName(QString::fromUtf8("aInstrumentIndicator_22"));
        aInstrumentIndicator_22->setGeometry(QRect(612, 370, 61, 61));
        aInstrumentIndicator_22->setValue(2);
        aInstrumentIndicator_22->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_23 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_23->setObjectName(QString::fromUtf8("aInstrumentIndicator_23"));
        aInstrumentIndicator_23->setGeometry(QRect(733, 64, 61, 61));
        aInstrumentIndicator_23->setValue(2);
        aInstrumentIndicator_23->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_24 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_24->setObjectName(QString::fromUtf8("aInstrumentIndicator_24"));
        aInstrumentIndicator_24->setGeometry(QRect(773, 112, 61, 61));
        aInstrumentIndicator_24->setValue(2);
        aInstrumentIndicator_24->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_27 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_27->setObjectName(QString::fromUtf8("aInstrumentIndicator_27"));
        aInstrumentIndicator_27->setGeometry(QRect(811, 160, 61, 61));
        aInstrumentIndicator_27->setValue(2);
        aInstrumentIndicator_27->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_28 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_28->setObjectName(QString::fromUtf8("aInstrumentIndicator_28"));
        aInstrumentIndicator_28->setGeometry(QRect(770, 214, 61, 61));
        aInstrumentIndicator_28->setValue(2);
        aInstrumentIndicator_28->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_29 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_29->setObjectName(QString::fromUtf8("aInstrumentIndicator_29"));
        aInstrumentIndicator_29->setGeometry(QRect(736, 264, 61, 61));
        aInstrumentIndicator_29->setValue(2);
        aInstrumentIndicator_29->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_25 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_25->setObjectName(QString::fromUtf8("aInstrumentIndicator_25"));
        aInstrumentIndicator_25->setGeometry(QRect(733, 407, 61, 61));
        aInstrumentIndicator_25->setValue(2);
        aInstrumentIndicator_25->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_30 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_30->setObjectName(QString::fromUtf8("aInstrumentIndicator_30"));
        aInstrumentIndicator_30->setGeometry(QRect(812, 502, 61, 61));
        aInstrumentIndicator_30->setValue(2);
        aInstrumentIndicator_30->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_26 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_26->setObjectName(QString::fromUtf8("aInstrumentIndicator_26"));
        aInstrumentIndicator_26->setGeometry(QRect(772, 455, 61, 61));
        aInstrumentIndicator_26->setValue(2);
        aInstrumentIndicator_26->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_31 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_31->setObjectName(QString::fromUtf8("aInstrumentIndicator_31"));
        aInstrumentIndicator_31->setGeometry(QRect(738, 604, 61, 61));
        aInstrumentIndicator_31->setValue(2);
        aInstrumentIndicator_31->setOrientation(AWMultEstateWidget::Degree180);
        aInstrumentIndicator_32 = new AInstrumentIndicator(B7);
        aInstrumentIndicator_32->setObjectName(QString::fromUtf8("aInstrumentIndicator_32"));
        aInstrumentIndicator_32->setGeometry(QRect(773, 556, 61, 61));
        aInstrumentIndicator_32->setValue(2);
        aInstrumentIndicator_32->setOrientation(AWMultEstateWidget::Degree180);
        lbUnit3 = new QLabel(B7);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(833, 647, 190, 15));
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        lbUnit3->setFont(font1);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        btnIMPPant = new QPushButton(B7);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(10, 632, 134, 23));
        QFont font2;
        font2.setPointSize(8);
        font2.setBold(true);
        font2.setWeight(75);
        btnIMPPant->setFont(font2);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        label->raise();
        Descr_45->raise();
        Descr_46->raise();
        Descr_44->raise();
        Descr_49->raise();
        Descr_43->raise();
        Descr_51->raise();
        Descr_53->raise();
        Descr_54->raise();
        Descr_50->raise();
        Descr_47->raise();
        Descr_48->raise();
        Descr_52->raise();
        lb_Lect_GP1OA->raise();
        lb_Unit_GP1OA->raise();
        lb_Unit_GP1PA->raise();
        lb_Lect_GP1PA->raise();
        lb_Lect_GP1IA->raise();
        lb_Unit_GP1IA->raise();
        lb_Unit_GP1OB->raise();
        lb_Lect_GP1OB->raise();
        lb_Unit_GP1PB->raise();
        lb_Lect_GP1PB->raise();
        lb_Unit_GP1IB->raise();
        lb_Lect_GP1IB->raise();
        lb_Unit_GP2OA->raise();
        lb_Lect_GP2OA->raise();
        lb_Unit_GP2PA->raise();
        lb_Lect_GP2PA->raise();
        lb_Lect_GP2IA->raise();
        lb_Unit_GP2IA->raise();
        lb_Lect_GP2OB->raise();
        lb_Unit_GP2OB->raise();
        lb_Lect_GP2PB->raise();
        lb_Unit_GP2PB->raise();
        lb_Lect_GP2IB->raise();
        lb_Unit_GP2IB->raise();
        lb_Unit_FC62109B->raise();
        lb_Unit_FC62109A->raise();
        lb_Lect_FC62109B->raise();
        lb_Lect_FC62109A->raise();
        lb_Unit_FC62109_RTRO->raise();
        lb_Lect_FC62109_DEM->raise();
        Descr_38->raise();
        lb_Unit_FC62109_DEM->raise();
        lb_Lect_FC62109_RTRO->raise();
        Descr_37->raise();
        label_35->raise();
        label_37->raise();
        lb_Unit_FC62108B->raise();
        lb_Unit_FC62108A->raise();
        lb_Lect_FC62108A->raise();
        lb_Lect_FC62108B->raise();
        Descr_40->raise();
        lb_Lect_FC62108_DEM->raise();
        lb_Unit_FC62108->raise();
        lb_Lect_FC62108_RTRO->raise();
        Descr_39->raise();
        lb_Unit_FC62108_2->raise();
        lb_Unit_FC62107B->raise();
        lb_Lect_FC62107B->raise();
        lb_Unit_FC62107A->raise();
        lb_Lect_FC62107A->raise();
        lb_Unit_FC62107_RTRO->raise();
        lb_Unit_FC62107_DEM->raise();
        Descr_42->raise();
        lb_Lect_FC62107_RTRO->raise();
        lb_Lect_FC62107_DEM->raise();
        Descr_41->raise();
        label_33->raise();
        label_39->raise();
        label_29->raise();
        label_31->raise();
        aWMultiObject->raise();
        aWMultiObject_2->raise();
        aWMultiObject_3->raise();
        aWMultiObject_4->raise();
        aWMultiObject_5->raise();
        aWMultiObject_6->raise();
        aWMultiObject_7->raise();
        aWMultiObject_8->raise();
        aWMultiObject_9->raise();
        aWMultiObject_10->raise();
        aWMultiObject_11->raise();
        aWMultiObject_12->raise();
        aWMultiObject_13->raise();
        aWMultiObject_14->raise();
        aInstrumentIndicator->raise();
        aInstrumentIndicator_2->raise();
        aInstrumentIndicator_3->raise();
        aInstrumentIndicator_4->raise();
        aInstrumentIndicator_5->raise();
        aInstrumentIndicator_6->raise();
        aInstrumentIndicator_7->raise();
        aInstrumentIndicator_8->raise();
        aInstrumentIndicator_9->raise();
        aInstrumentIndicator_10->raise();
        aInstrumentIndicator_11->raise();
        aInstrumentIndicator_12->raise();
        aInstrumentIndicator_13->raise();
        aInstrumentIndicator_14->raise();
        aInstrumentIndicator_15->raise();
        aInstrumentIndicator_16->raise();
        aInstrumentIndicator_17->raise();
        aInstrumentIndicator_18->raise();
        aInstrumentIndicator_19->raise();
        aInstrumentIndicator_20->raise();
        aInstrumentIndicator_21->raise();
        aInstrumentIndicator_22->raise();
        aInstrumentIndicator_23->raise();
        aInstrumentIndicator_24->raise();
        aInstrumentIndicator_27->raise();
        aInstrumentIndicator_28->raise();
        aInstrumentIndicator_29->raise();
        aInstrumentIndicator_25->raise();
        aInstrumentIndicator_30->raise();
        aInstrumentIndicator_26->raise();
        aInstrumentIndicator_31->raise();
        aInstrumentIndicator_32->raise();
        lbUnit3->raise();
        btnIMPPant->raise();

        retranslateUi(B7);

        QMetaObject::connectSlotsByName(B7);
    } // setupUi

    void retranslateUi(QWidget *B7)
    {
        B7->setWindowTitle(QApplication::translate("B7", "Form", 0, QApplication::UnicodeUTF8));
        Descr_45->setText(QApplication::translate("B7", "GP1IA", 0, QApplication::UnicodeUTF8));
        Descr_46->setText(QApplication::translate("B7", "GP1OB", 0, QApplication::UnicodeUTF8));
        Descr_44->setText(QApplication::translate("B7", "GP1PA", 0, QApplication::UnicodeUTF8));
        Descr_49->setText(QApplication::translate("B7", "GP2OB", 0, QApplication::UnicodeUTF8));
        Descr_43->setText(QApplication::translate("B7", "GP1OA", 0, QApplication::UnicodeUTF8));
        label->setText(QString());
        Descr_51->setText(QApplication::translate("B7", "GP2IB", 0, QApplication::UnicodeUTF8));
        Descr_53->setText(QApplication::translate("B7", "GP2PA", 0, QApplication::UnicodeUTF8));
        Descr_54->setText(QApplication::translate("B7", "GP2IA", 0, QApplication::UnicodeUTF8));
        Descr_50->setText(QApplication::translate("B7", "GP2PB", 0, QApplication::UnicodeUTF8));
        Descr_47->setText(QApplication::translate("B7", "GP1PB", 0, QApplication::UnicodeUTF8));
        Descr_48->setText(QApplication::translate("B7", "GP1IB", 0, QApplication::UnicodeUTF8));
        Descr_52->setText(QApplication::translate("B7", "GP2OA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP1OA->setText(QString());
        lb_Unit_GP1OA->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Unit_GP1PA->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP1PA->setText(QString());
        lb_Lect_GP1IA->setText(QString());
        lb_Unit_GP1IA->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Unit_GP1OB->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP1OB->setText(QString());
        lb_Unit_GP1PB->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP1PB->setText(QString());
        lb_Unit_GP1IB->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP1IB->setText(QString());
        lb_Unit_GP2OA->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP2OA->setText(QString());
        lb_Unit_GP2PA->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP2PA->setText(QString());
        lb_Lect_GP2IA->setText(QString());
        lb_Unit_GP2IA->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP2OB->setText(QString());
        lb_Unit_GP2OB->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP2PB->setText(QString());
        lb_Unit_GP2PB->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Lect_GP2IB->setText(QString());
        lb_Unit_GP2IB->setText(QApplication::translate("B7", "PSIA", 0, QApplication::UnicodeUTF8));
        lb_Unit_FC62109B->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Unit_FC62109A->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62109B->setText(QString());
        lb_Lect_FC62109A->setText(QString());
        lb_Unit_FC62109_RTRO->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62109_DEM->setText(QString());
        Descr_38->setText(QApplication::translate("B7", "FC62109   RTRO", 0, QApplication::UnicodeUTF8));
        lb_Unit_FC62109_DEM->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62109_RTRO->setText(QString());
        Descr_37->setText(QApplication::translate("B7", "FC62109   DEM", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("B7", "MULTIPLE A\n"
"ANILLO EXTERNO", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("B7", "MULTIPLE B\n"
"ANILLO PILOTO", 0, QApplication::UnicodeUTF8));
        lb_Unit_FC62108B->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Unit_FC62108A->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62108A->setText(QString());
        lb_Lect_FC62108B->setText(QString());
        Descr_40->setText(QApplication::translate("B7", "FC62108   RTRO", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62108_DEM->setText(QString());
        lb_Unit_FC62108->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62108_RTRO->setText(QString());
        Descr_39->setText(QApplication::translate("B7", "FC62108   DEM", 0, QApplication::UnicodeUTF8));
        lb_Unit_FC62108_2->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Unit_FC62107B->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62107B->setText(QString());
        lb_Unit_FC62107A->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62107A->setText(QString());
        lb_Unit_FC62107_RTRO->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        lb_Unit_FC62107_DEM->setText(QApplication::translate("B7", "%", 0, QApplication::UnicodeUTF8));
        Descr_42->setText(QApplication::translate("B7", "FC62107   RTRO", 0, QApplication::UnicodeUTF8));
        lb_Lect_FC62107_RTRO->setText(QString());
        lb_Lect_FC62107_DEM->setText(QString());
        Descr_41->setText(QApplication::translate("B7", "FC62107   DEM", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("B7", "FLUJO DEL\n"
"ANILLO PILOTO", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("B7", "MULTIPLE C\n"
"ANILLO INTERNO", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("B7", "FLUJO DEL ANILLO\n"
"EXTERNO", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("B7", "FLUJO DEL ANILLO\n"
"EXTERNO", 0, QApplication::UnicodeUTF8));
        aInstrumentIndicator->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62137B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_2->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_2->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62138B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_3->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_3->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62137A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_4->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_4->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62138A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_5->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_5->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62136B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_6->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_6->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62136A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_7->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_7->setProperty("DownLabel", QVariant(QApplication::translate("B7", "621329A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_8->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_8->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62141B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_9->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_9->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62139B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_10->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_10->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62140B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_11->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_11->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62141A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_12->setProperty("UpLabel", QVariant(QApplication::translate("B7", "PT", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_12->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62140A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_13->setProperty("UpLabel", QVariant(QApplication::translate("B7", "FCV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_13->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62108", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_14->setProperty("UpLabel", QVariant(QApplication::translate("B7", "ZE", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_14->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62108A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_15->setProperty("UpLabel", QVariant(QApplication::translate("B7", "ZE", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_15->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62108B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_16->setProperty("UpLabel", QVariant(QApplication::translate("B7", "ZE", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_16->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62107A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_17->setProperty("UpLabel", QVariant(QApplication::translate("B7", "ZE", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_17->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62107B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_18->setProperty("UpLabel", QVariant(QApplication::translate("B7", "FCV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_18->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62107", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_19->setProperty("UpLabel", QVariant(QApplication::translate("B7", "ZE", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_19->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62109B", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_20->setProperty("UpLabel", QVariant(QApplication::translate("B7", "FCV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_20->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62109", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_21->setProperty("UpLabel", QVariant(QApplication::translate("B7", "ZE", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_21->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62109A", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_22->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_22->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62115", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_23->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_23->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62111", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_24->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_24->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62113", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_27->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_27->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62116", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_28->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_28->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62118", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_29->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_29->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62120", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_25->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_25->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62110", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_30->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_30->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62114", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_26->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_26->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62112", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_31->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_31->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62119", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_32->setProperty("UpLabel", QVariant(QApplication::translate("B7", "SOV", 0, QApplication::UnicodeUTF8)));
        aInstrumentIndicator_32->setProperty("DownLabel", QVariant(QApplication::translate("B7", "62117", 0, QApplication::UnicodeUTF8)));
        lbUnit3->setText(QApplication::translate("B7", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("B7", "IMP PANT", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class B7: public Ui_B7 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_B7_H
