/********************************************************************************
** Form generated from reading UI file 'c5.ui'
**
** Created: Sat 12. Oct 11:06:22 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_C5_H
#define UI_C5_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_C5
{
public:
    QLabel *lbFondo;
    QFrame *frame;
    QFrame *frame_2;
    QLabel *lbTitle_1;
    QLabel *lbN25AT;
    QLabel *lbN25A;
    QLabel *lbN25AU;
    QLabel *lbN25BU;
    QLabel *lbN25B;
    QLabel *lbN25BT;
    QLabel *lbN25SELU;
    QLabel *lbN25SELT;
    QLabel *lbN25SEL;
    QLabel *lbN25REFU;
    QLabel *lbN25REFT;
    QLabel *lbN25REF;
    QLabel *lbNSDAU;
    QLabel *lbNSDAT;
    QLabel *lbNSDA;
    QLabel *lbNSDBU;
    QLabel *lbNSDBT;
    QLabel *lbNSDB;
    QLabel *lbNSDSELU;
    QLabel *lbNSDSELT;
    QLabel *lbNSDSEL;
    QFrame *frame_3;
    QFrame *frame_4;
    QLabel *lbTitle_3;
    QLabel *lbT2AT;
    QLabel *lbT2A;
    QLabel *lbT2AU;
    QLabel *lbT2BU;
    QLabel *lbT2B;
    QLabel *lbT2BT;
    QLabel *lbT2SELU;
    QLabel *lbT2SELT;
    QLabel *lbT2SEL;
    QLabel *lbT25BU;
    QLabel *lbT25BT;
    QLabel *lbT25B;
    QLabel *lbT25SELU;
    QLabel *lbT25SELT;
    QLabel *lbT25SEL;
    QLabel *lbT3A1U;
    QLabel *lbT3A1T;
    QLabel *lbT3A1;
    QLabel *lbT25AU;
    QLabel *lbT25A;
    QLabel *lbT25AT;
    QLabel *lbT3A2U;
    QLabel *lbT3A2;
    QLabel *lbT3A2T;
    QLabel *lbT3B1U;
    QLabel *lbT3B1T;
    QLabel *lbT3B1;
    QLabel *lbT3B2U;
    QLabel *lbT3B2;
    QLabel *lbT3SEL;
    QLabel *lbT3SELU;
    QLabel *lbT3SELT;
    QLabel *lbT3B2T;
    QFrame *frame_5;
    QFrame *frame_6;
    QLabel *lbTitle_2;
    QLabel *lbT48AT;
    QLabel *lbT48A;
    QLabel *lbT48AU;
    QLabel *lbT48BU;
    QLabel *lbT48B;
    QLabel *lbT48BT;
    QLabel *lbT48CU;
    QLabel *lbT48CT;
    QLabel *lbT48C;
    QLabel *lbT48DU;
    QLabel *lbT48DT;
    QLabel *lbT48D;
    QLabel *lbT48FU;
    QLabel *lbT48FT;
    QLabel *lbT48F;
    QLabel *lbT48GU;
    QLabel *lbT48GT;
    QLabel *lbT48G;
    QLabel *lbT48HU;
    QLabel *lbT48HT;
    QLabel *lbT48H;
    QLabel *lbT48EU;
    QLabel *lbT48E;
    QLabel *lbT48ET;
    QLabel *lbT48SELU;
    QLabel *lbT48SEL;
    QLabel *lbT48SELT;
    QLabel *lbT48REFU;
    QLabel *lbT48REFT;
    QLabel *lbT48REF;
    QFrame *frame_7;
    QFrame *frame_8;
    QLabel *lbTitle_4;
    QLabel *lbPOSELT;
    QLabel *lbPOSEL;
    QLabel *lbPOSELU;
    QLabel *lbP25AU;
    QLabel *lbP25AT;
    QLabel *lbP25A;
    QLabel *lbP25BU;
    QLabel *lbP25BT;
    QLabel *lbP25B;
    QLabel *lbPS3AU;
    QLabel *lbPS3AT;
    QLabel *lbPS3A;
    QLabel *lbPS3BU;
    QLabel *lbPS3BT;
    QLabel *lbPS3B;
    QLabel *lbPS3SELU;
    QLabel *lbPS3SELT;
    QLabel *lbPS3SEL;
    QLabel *lbP25SELU;
    QLabel *lbP25SEL;
    QLabel *lbP25SELT;
    QLabel *lbP48SELU;
    QLabel *lbP48SELT;
    QLabel *lbP48SEL;
    QFrame *frame_9;
    QFrame *frame_10;
    QLabel *lbTitle_8;
    QLabel *lbWF36DMDT;
    QLabel *lbWF36DMD;
    QLabel *lbWF36DMDU;
    QLabel *lbWF36ACU;
    QLabel *lbWF36AC;
    QLabel *lbWF36ACT;
    QLabel *lbGMVISELU;
    QLabel *lbGMVISELT;
    QLabel *lbGMVISEL;
    QLabel *lbGMVIDMDU;
    QLabel *lbGMVIDMDT;
    QLabel *lbGMVIDMD;
    QLabel *lbGMVPDMDU;
    QLabel *lbGMVPDMDT;
    QLabel *lbGMVPDMD;
    QLabel *lbGMVPSELU_2;
    QLabel *lbGMVPSELT_2;
    QLabel *lbGMVPSEL_2;
    QLabel *lbGMVPDMDU_2;
    QLabel *lbGMVPDMDT_2;
    QLabel *lbGMVPDMD_2;
    QLabel *lbGMVPSELU;
    QLabel *lbGMVPSEL;
    QLabel *lbGMVPSELT;
    QLabel *lbTGSSELU;
    QLabel *lbTGSSEL;
    QLabel *lbTGSSELT;
    QLabel *lbTGSSELU_2;
    QLabel *lbTGSSELT_2;
    QLabel *lbTGSSEL_2;
    QFrame *frame_11;
    QFrame *frame_12;
    QLabel *lbTitle_7;
    QLabel *lbCDPAT;
    QLabel *lbCDPA;
    QLabel *lbCDPAU;
    QLabel *lbCDPBU;
    QLabel *lbCDPB;
    QLabel *lbCDPBT;
    QLabel *lbCDPSELU;
    QLabel *lbCDPSELT;
    QLabel *lbCDPSEL;
    QLabel *lbCDPDMDU;
    QLabel *lbCDPDMDT;
    QLabel *lbCDPDMD;
    QLabel *lbST8AU;
    QLabel *lbST8AT;
    QLabel *lbST8A;
    QLabel *lbST8BU;
    QLabel *lbST8BT;
    QLabel *lbST8B;
    QLabel *lbST8SELU;
    QLabel *lbST8SELT;
    QLabel *lbST8SEL;
    QLabel *lbST8DMDU;
    QLabel *lbST8DMD;
    QLabel *lbST8DMDT;
    QFrame *frame_13;
    QFrame *frame_14;
    QLabel *lbTitle_5;
    QLabel *lbVSVAT;
    QLabel *lbVSVA;
    QLabel *lbVSVAU;
    QLabel *lbVSVBU;
    QLabel *lbVSVB;
    QLabel *lbVSVBT;
    QLabel *lbVSVSELU;
    QLabel *lbVSVSELT;
    QLabel *lbVSVSEL;
    QLabel *lbVSVDMDU;
    QLabel *lbVSVDMDT;
    QLabel *lbVSVDMD;
    QLabel *lbIGVA;
    QLabel *lbIGVBU;
    QLabel *lbIGVSEL;
    QLabel *lbIGVDMDU;
    QLabel *lbIGVDMDT;
    QLabel *lbIGVDMD;
    QLabel *lbIGVAT;
    QLabel *lbIGVAU;
    QLabel *lbIGVBT;
    QLabel *lbIGVSELU;
    QLabel *lbIGVSELT;
    QLabel *lbIGVB;
    QLabel *lbVBVA;
    QLabel *lbVBVBU;
    QLabel *lbVBVSEL;
    QLabel *lbVBVDMDU;
    QLabel *lbVBVDMDT;
    QLabel *lbVBVDMD;
    QLabel *lbVBVAT;
    QLabel *lbVBVAU;
    QLabel *lbVBVBT;
    QLabel *lbVBVSELU;
    QLabel *lbVBVSELT;
    QLabel *lbVBVB;
    QFrame *frame_15;
    QFrame *frame_16;
    QLabel *lbTitle_6;
    QLabel *lbPTBAT;
    QLabel *lbPTBA;
    QLabel *lbPTBAU;
    QLabel *lbPTBBU;
    QLabel *lbPTBB;
    QLabel *lbPTBBT;
    QLabel *lbPTBSELU;
    QLabel *lbPTBSELT;
    QLabel *lbPTBSEL;
    QLabel *lbTBVAU;
    QLabel *lbTBVAT;
    QLabel *lbTBVA;
    QLabel *lbTBVBU;
    QLabel *lbTBVBT;
    QLabel *lbTBVB;
    QLabel *lbTBVSELU;
    QLabel *lbTBVSELT;
    QLabel *lbTBVSEL;
    QLabel *lbTBVDMDU;
    QLabel *lbTBVDMD;
    QLabel *lbTBVDMDT;
    QLabel *label_232;

    void setupUi(QWidget *C5)
    {
        if (C5->objectName().isEmpty())
            C5->setObjectName(QString::fromUtf8("C5"));
        C5->resize(1024, 662);
        C5->setMinimumSize(QSize(1024, 662));
        C5->setMaximumSize(QSize(1024, 662));
        lbFondo = new QLabel(C5);
        lbFondo->setObjectName(QString::fromUtf8("lbFondo"));
        lbFondo->setGeometry(QRect(0, 0, 1024, 662));
        lbFondo->setMinimumSize(QSize(1024, 662));
        lbFondo->setMaximumSize(QSize(1024, 662));
        lbFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/C5.png")));
        lbFondo->setScaledContents(true);
        frame = new QFrame(C5);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(60, 70, 201, 233));
        frame->setStyleSheet(QString::fromUtf8(""));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Raised);
        frame_2 = new QFrame(frame);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(2, 0, 196, 28));
        frame_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Sunken);
        lbTitle_1 = new QLabel(frame_2);
        lbTitle_1->setObjectName(QString::fromUtf8("lbTitle_1"));
        lbTitle_1->setGeometry(QRect(5, 8, 188, 13));
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        lbTitle_1->setFont(font);
        lbTitle_1->setAlignment(Qt::AlignCenter);
        lbN25AT = new QLabel(frame);
        lbN25AT->setObjectName(QString::fromUtf8("lbN25AT"));
        lbN25AT->setGeometry(QRect(73, 36, 46, 13));
        lbN25AT->setFont(font);
        lbN25AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbN25A = new QLabel(frame);
        lbN25A->setObjectName(QString::fromUtf8("lbN25A"));
        lbN25A->setGeometry(QRect(120, 36, 40, 13));
        lbN25A->setFont(font);
        lbN25A->setAlignment(Qt::AlignCenter);
        lbN25AU = new QLabel(frame);
        lbN25AU->setObjectName(QString::fromUtf8("lbN25AU"));
        lbN25AU->setGeometry(QRect(165, 35, 37, 13));
        lbN25AU->setFont(font);
        lbN25AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25BU = new QLabel(frame);
        lbN25BU->setObjectName(QString::fromUtf8("lbN25BU"));
        lbN25BU->setGeometry(QRect(165, 56, 37, 13));
        lbN25BU->setFont(font);
        lbN25BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25B = new QLabel(frame);
        lbN25B->setObjectName(QString::fromUtf8("lbN25B"));
        lbN25B->setGeometry(QRect(119, 56, 40, 13));
        lbN25B->setFont(font);
        lbN25B->setAlignment(Qt::AlignCenter);
        lbN25BT = new QLabel(frame);
        lbN25BT->setObjectName(QString::fromUtf8("lbN25BT"));
        lbN25BT->setGeometry(QRect(73, 56, 46, 13));
        lbN25BT->setFont(font);
        lbN25BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbN25SELU = new QLabel(frame);
        lbN25SELU->setObjectName(QString::fromUtf8("lbN25SELU"));
        lbN25SELU->setGeometry(QRect(165, 75, 37, 13));
        lbN25SELU->setFont(font);
        lbN25SELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25SELT = new QLabel(frame);
        lbN25SELT->setObjectName(QString::fromUtf8("lbN25SELT"));
        lbN25SELT->setGeometry(QRect(73, 75, 46, 13));
        lbN25SELT->setFont(font);
        lbN25SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbN25SEL = new QLabel(frame);
        lbN25SEL->setObjectName(QString::fromUtf8("lbN25SEL"));
        lbN25SEL->setGeometry(QRect(120, 75, 40, 13));
        lbN25SEL->setFont(font);
        lbN25SEL->setAlignment(Qt::AlignCenter);
        lbN25REFU = new QLabel(frame);
        lbN25REFU->setObjectName(QString::fromUtf8("lbN25REFU"));
        lbN25REFU->setGeometry(QRect(165, 95, 37, 13));
        lbN25REFU->setFont(font);
        lbN25REFU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25REFT = new QLabel(frame);
        lbN25REFT->setObjectName(QString::fromUtf8("lbN25REFT"));
        lbN25REFT->setGeometry(QRect(73, 95, 46, 13));
        lbN25REFT->setFont(font);
        lbN25REFT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbN25REF = new QLabel(frame);
        lbN25REF->setObjectName(QString::fromUtf8("lbN25REF"));
        lbN25REF->setGeometry(QRect(120, 95, 40, 13));
        lbN25REF->setFont(font);
        lbN25REF->setAlignment(Qt::AlignCenter);
        lbNSDAU = new QLabel(frame);
        lbNSDAU->setObjectName(QString::fromUtf8("lbNSDAU"));
        lbNSDAU->setGeometry(QRect(165, 133, 37, 13));
        lbNSDAU->setFont(font);
        lbNSDAU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNSDAT = new QLabel(frame);
        lbNSDAT->setObjectName(QString::fromUtf8("lbNSDAT"));
        lbNSDAT->setGeometry(QRect(73, 133, 46, 13));
        lbNSDAT->setFont(font);
        lbNSDAT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNSDA = new QLabel(frame);
        lbNSDA->setObjectName(QString::fromUtf8("lbNSDA"));
        lbNSDA->setGeometry(QRect(120, 133, 40, 13));
        lbNSDA->setFont(font);
        lbNSDA->setAlignment(Qt::AlignCenter);
        lbNSDBU = new QLabel(frame);
        lbNSDBU->setObjectName(QString::fromUtf8("lbNSDBU"));
        lbNSDBU->setGeometry(QRect(165, 153, 37, 13));
        lbNSDBU->setFont(font);
        lbNSDBU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNSDBT = new QLabel(frame);
        lbNSDBT->setObjectName(QString::fromUtf8("lbNSDBT"));
        lbNSDBT->setGeometry(QRect(73, 153, 46, 13));
        lbNSDBT->setFont(font);
        lbNSDBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNSDB = new QLabel(frame);
        lbNSDB->setObjectName(QString::fromUtf8("lbNSDB"));
        lbNSDB->setGeometry(QRect(120, 153, 40, 13));
        lbNSDB->setFont(font);
        lbNSDB->setAlignment(Qt::AlignCenter);
        lbNSDSELU = new QLabel(frame);
        lbNSDSELU->setObjectName(QString::fromUtf8("lbNSDSELU"));
        lbNSDSELU->setGeometry(QRect(165, 172, 37, 13));
        lbNSDSELU->setFont(font);
        lbNSDSELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNSDSELT = new QLabel(frame);
        lbNSDSELT->setObjectName(QString::fromUtf8("lbNSDSELT"));
        lbNSDSELT->setGeometry(QRect(73, 172, 46, 13));
        lbNSDSELT->setFont(font);
        lbNSDSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNSDSEL = new QLabel(frame);
        lbNSDSEL->setObjectName(QString::fromUtf8("lbNSDSEL"));
        lbNSDSEL->setGeometry(QRect(120, 172, 40, 13));
        lbNSDSEL->setFont(font);
        lbNSDSEL->setAlignment(Qt::AlignCenter);
        frame_3 = new QFrame(C5);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(535, 70, 201, 233));
        frame_3->setFrameShape(QFrame::Box);
        frame_3->setFrameShadow(QFrame::Raised);
        frame_4 = new QFrame(frame_3);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(2, 0, 196, 28));
        frame_4->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_4->setFrameShape(QFrame::Box);
        frame_4->setFrameShadow(QFrame::Sunken);
        lbTitle_3 = new QLabel(frame_4);
        lbTitle_3->setObjectName(QString::fromUtf8("lbTitle_3"));
        lbTitle_3->setGeometry(QRect(5, 8, 188, 13));
        lbTitle_3->setFont(font);
        lbTitle_3->setAlignment(Qt::AlignCenter);
        lbT2AT = new QLabel(frame_3);
        lbT2AT->setObjectName(QString::fromUtf8("lbT2AT"));
        lbT2AT->setGeometry(QRect(66, 36, 50, 13));
        lbT2AT->setFont(font);
        lbT2AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT2A = new QLabel(frame_3);
        lbT2A->setObjectName(QString::fromUtf8("lbT2A"));
        lbT2A->setGeometry(QRect(120, 36, 40, 13));
        lbT2A->setFont(font);
        lbT2A->setAlignment(Qt::AlignCenter);
        lbT2AU = new QLabel(frame_3);
        lbT2AU->setObjectName(QString::fromUtf8("lbT2AU"));
        lbT2AU->setGeometry(QRect(159, 35, 37, 13));
        lbT2AU->setFont(font);
        lbT2AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT2BU = new QLabel(frame_3);
        lbT2BU->setObjectName(QString::fromUtf8("lbT2BU"));
        lbT2BU->setGeometry(QRect(159, 50, 37, 13));
        lbT2BU->setFont(font);
        lbT2BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT2B = new QLabel(frame_3);
        lbT2B->setObjectName(QString::fromUtf8("lbT2B"));
        lbT2B->setGeometry(QRect(120, 50, 40, 13));
        lbT2B->setFont(font);
        lbT2B->setAlignment(Qt::AlignCenter);
        lbT2BT = new QLabel(frame_3);
        lbT2BT->setObjectName(QString::fromUtf8("lbT2BT"));
        lbT2BT->setGeometry(QRect(66, 50, 50, 13));
        lbT2BT->setFont(font);
        lbT2BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT2SELU = new QLabel(frame_3);
        lbT2SELU->setObjectName(QString::fromUtf8("lbT2SELU"));
        lbT2SELU->setGeometry(QRect(159, 65, 37, 13));
        lbT2SELU->setFont(font);
        lbT2SELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT2SELT = new QLabel(frame_3);
        lbT2SELT->setObjectName(QString::fromUtf8("lbT2SELT"));
        lbT2SELT->setGeometry(QRect(66, 65, 50, 13));
        lbT2SELT->setFont(font);
        lbT2SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT2SEL = new QLabel(frame_3);
        lbT2SEL->setObjectName(QString::fromUtf8("lbT2SEL"));
        lbT2SEL->setGeometry(QRect(120, 65, 40, 13));
        lbT2SEL->setFont(font);
        lbT2SEL->setAlignment(Qt::AlignCenter);
        lbT25BU = new QLabel(frame_3);
        lbT25BU->setObjectName(QString::fromUtf8("lbT25BU"));
        lbT25BU->setGeometry(QRect(159, 105, 37, 13));
        lbT25BU->setFont(font);
        lbT25BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT25BT = new QLabel(frame_3);
        lbT25BT->setObjectName(QString::fromUtf8("lbT25BT"));
        lbT25BT->setGeometry(QRect(66, 105, 50, 13));
        lbT25BT->setFont(font);
        lbT25BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT25B = new QLabel(frame_3);
        lbT25B->setObjectName(QString::fromUtf8("lbT25B"));
        lbT25B->setGeometry(QRect(120, 105, 40, 13));
        lbT25B->setFont(font);
        lbT25B->setAlignment(Qt::AlignCenter);
        lbT25SELU = new QLabel(frame_3);
        lbT25SELU->setObjectName(QString::fromUtf8("lbT25SELU"));
        lbT25SELU->setGeometry(QRect(159, 119, 37, 13));
        lbT25SELU->setFont(font);
        lbT25SELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT25SELT = new QLabel(frame_3);
        lbT25SELT->setObjectName(QString::fromUtf8("lbT25SELT"));
        lbT25SELT->setGeometry(QRect(66, 119, 50, 13));
        lbT25SELT->setFont(font);
        lbT25SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT25SEL = new QLabel(frame_3);
        lbT25SEL->setObjectName(QString::fromUtf8("lbT25SEL"));
        lbT25SEL->setGeometry(QRect(120, 119, 40, 13));
        lbT25SEL->setFont(font);
        lbT25SEL->setAlignment(Qt::AlignCenter);
        lbT3A1U = new QLabel(frame_3);
        lbT3A1U->setObjectName(QString::fromUtf8("lbT3A1U"));
        lbT3A1U->setGeometry(QRect(159, 142, 37, 13));
        lbT3A1U->setFont(font);
        lbT3A1U->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT3A1T = new QLabel(frame_3);
        lbT3A1T->setObjectName(QString::fromUtf8("lbT3A1T"));
        lbT3A1T->setGeometry(QRect(66, 142, 50, 13));
        lbT3A1T->setFont(font);
        lbT3A1T->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT3A1 = new QLabel(frame_3);
        lbT3A1->setObjectName(QString::fromUtf8("lbT3A1"));
        lbT3A1->setGeometry(QRect(120, 142, 40, 13));
        lbT3A1->setFont(font);
        lbT3A1->setAlignment(Qt::AlignCenter);
        lbT25AU = new QLabel(frame_3);
        lbT25AU->setObjectName(QString::fromUtf8("lbT25AU"));
        lbT25AU->setGeometry(QRect(159, 91, 37, 13));
        lbT25AU->setFont(font);
        lbT25AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT25A = new QLabel(frame_3);
        lbT25A->setObjectName(QString::fromUtf8("lbT25A"));
        lbT25A->setGeometry(QRect(120, 91, 40, 13));
        lbT25A->setFont(font);
        lbT25A->setAlignment(Qt::AlignCenter);
        lbT25AT = new QLabel(frame_3);
        lbT25AT->setObjectName(QString::fromUtf8("lbT25AT"));
        lbT25AT->setGeometry(QRect(66, 91, 50, 13));
        lbT25AT->setFont(font);
        lbT25AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT3A2U = new QLabel(frame_3);
        lbT3A2U->setObjectName(QString::fromUtf8("lbT3A2U"));
        lbT3A2U->setGeometry(QRect(160, 156, 37, 13));
        lbT3A2U->setFont(font);
        lbT3A2U->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT3A2 = new QLabel(frame_3);
        lbT3A2->setObjectName(QString::fromUtf8("lbT3A2"));
        lbT3A2->setGeometry(QRect(120, 156, 40, 13));
        lbT3A2->setFont(font);
        lbT3A2->setAlignment(Qt::AlignCenter);
        lbT3A2T = new QLabel(frame_3);
        lbT3A2T->setObjectName(QString::fromUtf8("lbT3A2T"));
        lbT3A2T->setGeometry(QRect(66, 156, 50, 13));
        lbT3A2T->setFont(font);
        lbT3A2T->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT3B1U = new QLabel(frame_3);
        lbT3B1U->setObjectName(QString::fromUtf8("lbT3B1U"));
        lbT3B1U->setGeometry(QRect(160, 172, 37, 13));
        lbT3B1U->setFont(font);
        lbT3B1U->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT3B1T = new QLabel(frame_3);
        lbT3B1T->setObjectName(QString::fromUtf8("lbT3B1T"));
        lbT3B1T->setGeometry(QRect(66, 172, 50, 13));
        lbT3B1T->setFont(font);
        lbT3B1T->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT3B1 = new QLabel(frame_3);
        lbT3B1->setObjectName(QString::fromUtf8("lbT3B1"));
        lbT3B1->setGeometry(QRect(120, 172, 40, 13));
        lbT3B1->setFont(font);
        lbT3B1->setAlignment(Qt::AlignCenter);
        lbT3B2U = new QLabel(frame_3);
        lbT3B2U->setObjectName(QString::fromUtf8("lbT3B2U"));
        lbT3B2U->setGeometry(QRect(160, 190, 37, 13));
        lbT3B2U->setFont(font);
        lbT3B2U->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT3B2 = new QLabel(frame_3);
        lbT3B2->setObjectName(QString::fromUtf8("lbT3B2"));
        lbT3B2->setGeometry(QRect(120, 190, 40, 13));
        lbT3B2->setFont(font);
        lbT3B2->setAlignment(Qt::AlignCenter);
        lbT3SEL = new QLabel(frame_3);
        lbT3SEL->setObjectName(QString::fromUtf8("lbT3SEL"));
        lbT3SEL->setGeometry(QRect(120, 206, 40, 13));
        lbT3SEL->setFont(font);
        lbT3SEL->setAlignment(Qt::AlignCenter);
        lbT3SELU = new QLabel(frame_3);
        lbT3SELU->setObjectName(QString::fromUtf8("lbT3SELU"));
        lbT3SELU->setGeometry(QRect(160, 206, 37, 13));
        lbT3SELU->setFont(font);
        lbT3SELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT3SELT = new QLabel(frame_3);
        lbT3SELT->setObjectName(QString::fromUtf8("lbT3SELT"));
        lbT3SELT->setGeometry(QRect(66, 206, 50, 13));
        lbT3SELT->setFont(font);
        lbT3SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT3B2T = new QLabel(frame_3);
        lbT3B2T->setObjectName(QString::fromUtf8("lbT3B2T"));
        lbT3B2T->setGeometry(QRect(66, 190, 50, 13));
        lbT3B2T->setFont(font);
        lbT3B2T->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_5 = new QFrame(C5);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(297, 70, 201, 233));
        frame_5->setFrameShape(QFrame::Box);
        frame_5->setFrameShadow(QFrame::Raised);
        frame_6 = new QFrame(frame_5);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(2, 0, 196, 28));
        frame_6->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_6->setFrameShape(QFrame::Box);
        frame_6->setFrameShadow(QFrame::Sunken);
        lbTitle_2 = new QLabel(frame_6);
        lbTitle_2->setObjectName(QString::fromUtf8("lbTitle_2"));
        lbTitle_2->setGeometry(QRect(5, 8, 188, 13));
        lbTitle_2->setFont(font);
        lbTitle_2->setAlignment(Qt::AlignCenter);
        lbT48AT = new QLabel(frame_5);
        lbT48AT->setObjectName(QString::fromUtf8("lbT48AT"));
        lbT48AT->setGeometry(QRect(64, 36, 50, 13));
        lbT48AT->setFont(font);
        lbT48AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48A = new QLabel(frame_5);
        lbT48A->setObjectName(QString::fromUtf8("lbT48A"));
        lbT48A->setGeometry(QRect(120, 36, 40, 13));
        lbT48A->setFont(font);
        lbT48A->setAlignment(Qt::AlignCenter);
        lbT48AU = new QLabel(frame_5);
        lbT48AU->setObjectName(QString::fromUtf8("lbT48AU"));
        lbT48AU->setGeometry(QRect(159, 35, 37, 13));
        lbT48AU->setFont(font);
        lbT48AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48BU = new QLabel(frame_5);
        lbT48BU->setObjectName(QString::fromUtf8("lbT48BU"));
        lbT48BU->setGeometry(QRect(159, 56, 37, 13));
        lbT48BU->setFont(font);
        lbT48BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48B = new QLabel(frame_5);
        lbT48B->setObjectName(QString::fromUtf8("lbT48B"));
        lbT48B->setGeometry(QRect(120, 56, 40, 13));
        lbT48B->setFont(font);
        lbT48B->setAlignment(Qt::AlignCenter);
        lbT48BT = new QLabel(frame_5);
        lbT48BT->setObjectName(QString::fromUtf8("lbT48BT"));
        lbT48BT->setGeometry(QRect(64, 56, 50, 13));
        lbT48BT->setFont(font);
        lbT48BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48CU = new QLabel(frame_5);
        lbT48CU->setObjectName(QString::fromUtf8("lbT48CU"));
        lbT48CU->setGeometry(QRect(159, 75, 37, 13));
        lbT48CU->setFont(font);
        lbT48CU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48CT = new QLabel(frame_5);
        lbT48CT->setObjectName(QString::fromUtf8("lbT48CT"));
        lbT48CT->setGeometry(QRect(64, 75, 50, 13));
        lbT48CT->setFont(font);
        lbT48CT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48C = new QLabel(frame_5);
        lbT48C->setObjectName(QString::fromUtf8("lbT48C"));
        lbT48C->setGeometry(QRect(120, 75, 40, 13));
        lbT48C->setFont(font);
        lbT48C->setAlignment(Qt::AlignCenter);
        lbT48DU = new QLabel(frame_5);
        lbT48DU->setObjectName(QString::fromUtf8("lbT48DU"));
        lbT48DU->setGeometry(QRect(159, 95, 37, 13));
        lbT48DU->setFont(font);
        lbT48DU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48DT = new QLabel(frame_5);
        lbT48DT->setObjectName(QString::fromUtf8("lbT48DT"));
        lbT48DT->setGeometry(QRect(64, 95, 50, 13));
        lbT48DT->setFont(font);
        lbT48DT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48D = new QLabel(frame_5);
        lbT48D->setObjectName(QString::fromUtf8("lbT48D"));
        lbT48D->setGeometry(QRect(120, 95, 40, 13));
        lbT48D->setFont(font);
        lbT48D->setAlignment(Qt::AlignCenter);
        lbT48FU = new QLabel(frame_5);
        lbT48FU->setObjectName(QString::fromUtf8("lbT48FU"));
        lbT48FU->setGeometry(QRect(159, 133, 37, 13));
        lbT48FU->setFont(font);
        lbT48FU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48FT = new QLabel(frame_5);
        lbT48FT->setObjectName(QString::fromUtf8("lbT48FT"));
        lbT48FT->setGeometry(QRect(64, 133, 50, 13));
        lbT48FT->setFont(font);
        lbT48FT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48F = new QLabel(frame_5);
        lbT48F->setObjectName(QString::fromUtf8("lbT48F"));
        lbT48F->setGeometry(QRect(120, 133, 40, 13));
        lbT48F->setFont(font);
        lbT48F->setAlignment(Qt::AlignCenter);
        lbT48GU = new QLabel(frame_5);
        lbT48GU->setObjectName(QString::fromUtf8("lbT48GU"));
        lbT48GU->setGeometry(QRect(159, 153, 37, 13));
        lbT48GU->setFont(font);
        lbT48GU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48GT = new QLabel(frame_5);
        lbT48GT->setObjectName(QString::fromUtf8("lbT48GT"));
        lbT48GT->setGeometry(QRect(64, 153, 50, 13));
        lbT48GT->setFont(font);
        lbT48GT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48G = new QLabel(frame_5);
        lbT48G->setObjectName(QString::fromUtf8("lbT48G"));
        lbT48G->setGeometry(QRect(120, 153, 40, 13));
        lbT48G->setFont(font);
        lbT48G->setAlignment(Qt::AlignCenter);
        lbT48HU = new QLabel(frame_5);
        lbT48HU->setObjectName(QString::fromUtf8("lbT48HU"));
        lbT48HU->setGeometry(QRect(159, 172, 37, 13));
        lbT48HU->setFont(font);
        lbT48HU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48HT = new QLabel(frame_5);
        lbT48HT->setObjectName(QString::fromUtf8("lbT48HT"));
        lbT48HT->setGeometry(QRect(64, 172, 50, 13));
        lbT48HT->setFont(font);
        lbT48HT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48H = new QLabel(frame_5);
        lbT48H->setObjectName(QString::fromUtf8("lbT48H"));
        lbT48H->setGeometry(QRect(120, 172, 40, 13));
        lbT48H->setFont(font);
        lbT48H->setAlignment(Qt::AlignCenter);
        lbT48EU = new QLabel(frame_5);
        lbT48EU->setObjectName(QString::fromUtf8("lbT48EU"));
        lbT48EU->setGeometry(QRect(159, 114, 37, 13));
        lbT48EU->setFont(font);
        lbT48EU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48E = new QLabel(frame_5);
        lbT48E->setObjectName(QString::fromUtf8("lbT48E"));
        lbT48E->setGeometry(QRect(120, 114, 40, 13));
        lbT48E->setFont(font);
        lbT48E->setAlignment(Qt::AlignCenter);
        lbT48ET = new QLabel(frame_5);
        lbT48ET->setObjectName(QString::fromUtf8("lbT48ET"));
        lbT48ET->setGeometry(QRect(64, 114, 50, 13));
        lbT48ET->setFont(font);
        lbT48ET->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48SELU = new QLabel(frame_5);
        lbT48SELU->setObjectName(QString::fromUtf8("lbT48SELU"));
        lbT48SELU->setGeometry(QRect(160, 191, 37, 13));
        lbT48SELU->setFont(font);
        lbT48SELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48SEL = new QLabel(frame_5);
        lbT48SEL->setObjectName(QString::fromUtf8("lbT48SEL"));
        lbT48SEL->setGeometry(QRect(120, 191, 40, 13));
        lbT48SEL->setFont(font);
        lbT48SEL->setAlignment(Qt::AlignCenter);
        lbT48SELT = new QLabel(frame_5);
        lbT48SELT->setObjectName(QString::fromUtf8("lbT48SELT"));
        lbT48SELT->setGeometry(QRect(64, 191, 50, 13));
        lbT48SELT->setFont(font);
        lbT48SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48REFU = new QLabel(frame_5);
        lbT48REFU->setObjectName(QString::fromUtf8("lbT48REFU"));
        lbT48REFU->setGeometry(QRect(160, 210, 37, 13));
        lbT48REFU->setFont(font);
        lbT48REFU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48REFT = new QLabel(frame_5);
        lbT48REFT->setObjectName(QString::fromUtf8("lbT48REFT"));
        lbT48REFT->setGeometry(QRect(64, 210, 50, 13));
        lbT48REFT->setFont(font);
        lbT48REFT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48REF = new QLabel(frame_5);
        lbT48REF->setObjectName(QString::fromUtf8("lbT48REF"));
        lbT48REF->setGeometry(QRect(120, 210, 40, 13));
        lbT48REF->setFont(font);
        lbT48REF->setAlignment(Qt::AlignCenter);
        frame_7 = new QFrame(C5);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(770, 70, 201, 233));
        frame_7->setFrameShape(QFrame::Box);
        frame_7->setFrameShadow(QFrame::Raised);
        frame_8 = new QFrame(frame_7);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(2, 0, 196, 28));
        frame_8->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_8->setFrameShape(QFrame::Box);
        frame_8->setFrameShadow(QFrame::Sunken);
        lbTitle_4 = new QLabel(frame_8);
        lbTitle_4->setObjectName(QString::fromUtf8("lbTitle_4"));
        lbTitle_4->setGeometry(QRect(5, 8, 188, 13));
        lbTitle_4->setFont(font);
        lbTitle_4->setAlignment(Qt::AlignCenter);
        lbPOSELT = new QLabel(frame_7);
        lbPOSELT->setObjectName(QString::fromUtf8("lbPOSELT"));
        lbPOSELT->setGeometry(QRect(66, 36, 50, 13));
        lbPOSELT->setFont(font);
        lbPOSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbPOSEL = new QLabel(frame_7);
        lbPOSEL->setObjectName(QString::fromUtf8("lbPOSEL"));
        lbPOSEL->setGeometry(QRect(120, 36, 40, 13));
        lbPOSEL->setFont(font);
        lbPOSEL->setAlignment(Qt::AlignCenter);
        lbPOSELU = new QLabel(frame_7);
        lbPOSELU->setObjectName(QString::fromUtf8("lbPOSELU"));
        lbPOSELU->setGeometry(QRect(159, 35, 37, 13));
        lbPOSELU->setFont(font);
        lbPOSELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbP25AU = new QLabel(frame_7);
        lbP25AU->setObjectName(QString::fromUtf8("lbP25AU"));
        lbP25AU->setGeometry(QRect(159, 60, 37, 13));
        lbP25AU->setFont(font);
        lbP25AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbP25AT = new QLabel(frame_7);
        lbP25AT->setObjectName(QString::fromUtf8("lbP25AT"));
        lbP25AT->setGeometry(QRect(66, 60, 50, 13));
        lbP25AT->setFont(font);
        lbP25AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbP25A = new QLabel(frame_7);
        lbP25A->setObjectName(QString::fromUtf8("lbP25A"));
        lbP25A->setGeometry(QRect(120, 60, 40, 13));
        lbP25A->setFont(font);
        lbP25A->setAlignment(Qt::AlignCenter);
        lbP25BU = new QLabel(frame_7);
        lbP25BU->setObjectName(QString::fromUtf8("lbP25BU"));
        lbP25BU->setGeometry(QRect(159, 80, 37, 13));
        lbP25BU->setFont(font);
        lbP25BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbP25BT = new QLabel(frame_7);
        lbP25BT->setObjectName(QString::fromUtf8("lbP25BT"));
        lbP25BT->setGeometry(QRect(66, 80, 50, 13));
        lbP25BT->setFont(font);
        lbP25BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbP25B = new QLabel(frame_7);
        lbP25B->setObjectName(QString::fromUtf8("lbP25B"));
        lbP25B->setGeometry(QRect(120, 80, 40, 13));
        lbP25B->setFont(font);
        lbP25B->setAlignment(Qt::AlignCenter);
        lbPS3AU = new QLabel(frame_7);
        lbPS3AU->setObjectName(QString::fromUtf8("lbPS3AU"));
        lbPS3AU->setGeometry(QRect(159, 133, 37, 13));
        lbPS3AU->setFont(font);
        lbPS3AU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPS3AT = new QLabel(frame_7);
        lbPS3AT->setObjectName(QString::fromUtf8("lbPS3AT"));
        lbPS3AT->setGeometry(QRect(66, 133, 50, 13));
        lbPS3AT->setFont(font);
        lbPS3AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbPS3A = new QLabel(frame_7);
        lbPS3A->setObjectName(QString::fromUtf8("lbPS3A"));
        lbPS3A->setGeometry(QRect(120, 133, 40, 13));
        lbPS3A->setFont(font);
        lbPS3A->setAlignment(Qt::AlignCenter);
        lbPS3BU = new QLabel(frame_7);
        lbPS3BU->setObjectName(QString::fromUtf8("lbPS3BU"));
        lbPS3BU->setGeometry(QRect(159, 153, 37, 13));
        lbPS3BU->setFont(font);
        lbPS3BU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPS3BT = new QLabel(frame_7);
        lbPS3BT->setObjectName(QString::fromUtf8("lbPS3BT"));
        lbPS3BT->setGeometry(QRect(66, 153, 50, 13));
        lbPS3BT->setFont(font);
        lbPS3BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbPS3B = new QLabel(frame_7);
        lbPS3B->setObjectName(QString::fromUtf8("lbPS3B"));
        lbPS3B->setGeometry(QRect(120, 153, 40, 13));
        lbPS3B->setFont(font);
        lbPS3B->setAlignment(Qt::AlignCenter);
        lbPS3SELU = new QLabel(frame_7);
        lbPS3SELU->setObjectName(QString::fromUtf8("lbPS3SELU"));
        lbPS3SELU->setGeometry(QRect(159, 172, 37, 13));
        lbPS3SELU->setFont(font);
        lbPS3SELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPS3SELT = new QLabel(frame_7);
        lbPS3SELT->setObjectName(QString::fromUtf8("lbPS3SELT"));
        lbPS3SELT->setGeometry(QRect(66, 172, 50, 13));
        lbPS3SELT->setFont(font);
        lbPS3SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbPS3SEL = new QLabel(frame_7);
        lbPS3SEL->setObjectName(QString::fromUtf8("lbPS3SEL"));
        lbPS3SEL->setGeometry(QRect(120, 172, 40, 13));
        lbPS3SEL->setFont(font);
        lbPS3SEL->setAlignment(Qt::AlignCenter);
        lbP25SELU = new QLabel(frame_7);
        lbP25SELU->setObjectName(QString::fromUtf8("lbP25SELU"));
        lbP25SELU->setGeometry(QRect(159, 99, 37, 13));
        lbP25SELU->setFont(font);
        lbP25SELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbP25SEL = new QLabel(frame_7);
        lbP25SEL->setObjectName(QString::fromUtf8("lbP25SEL"));
        lbP25SEL->setGeometry(QRect(120, 99, 40, 13));
        lbP25SEL->setFont(font);
        lbP25SEL->setAlignment(Qt::AlignCenter);
        lbP25SELT = new QLabel(frame_7);
        lbP25SELT->setObjectName(QString::fromUtf8("lbP25SELT"));
        lbP25SELT->setGeometry(QRect(66, 99, 50, 13));
        lbP25SELT->setFont(font);
        lbP25SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbP48SELU = new QLabel(frame_7);
        lbP48SELU->setObjectName(QString::fromUtf8("lbP48SELU"));
        lbP48SELU->setGeometry(QRect(160, 210, 37, 13));
        lbP48SELU->setFont(font);
        lbP48SELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbP48SELT = new QLabel(frame_7);
        lbP48SELT->setObjectName(QString::fromUtf8("lbP48SELT"));
        lbP48SELT->setGeometry(QRect(66, 210, 50, 13));
        lbP48SELT->setFont(font);
        lbP48SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbP48SEL = new QLabel(frame_7);
        lbP48SEL->setObjectName(QString::fromUtf8("lbP48SEL"));
        lbP48SEL->setGeometry(QRect(120, 210, 40, 13));
        lbP48SEL->setFont(font);
        lbP48SEL->setAlignment(Qt::AlignCenter);
        frame_9 = new QFrame(C5);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(770, 340, 201, 233));
        frame_9->setFrameShape(QFrame::Box);
        frame_9->setFrameShadow(QFrame::Raised);
        frame_10 = new QFrame(frame_9);
        frame_10->setObjectName(QString::fromUtf8("frame_10"));
        frame_10->setGeometry(QRect(2, 0, 196, 28));
        frame_10->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_10->setFrameShape(QFrame::Box);
        frame_10->setFrameShadow(QFrame::Sunken);
        lbTitle_8 = new QLabel(frame_10);
        lbTitle_8->setObjectName(QString::fromUtf8("lbTitle_8"));
        lbTitle_8->setGeometry(QRect(5, 8, 188, 13));
        lbTitle_8->setFont(font);
        lbTitle_8->setAlignment(Qt::AlignCenter);
        lbWF36DMDT = new QLabel(frame_9);
        lbWF36DMDT->setObjectName(QString::fromUtf8("lbWF36DMDT"));
        lbWF36DMDT->setGeometry(QRect(47, 36, 74, 13));
        lbWF36DMDT->setFont(font);
        lbWF36DMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbWF36DMD = new QLabel(frame_9);
        lbWF36DMD->setObjectName(QString::fromUtf8("lbWF36DMD"));
        lbWF36DMD->setGeometry(QRect(120, 36, 40, 13));
        lbWF36DMD->setFont(font);
        lbWF36DMD->setAlignment(Qt::AlignCenter);
        lbWF36DMDU = new QLabel(frame_9);
        lbWF36DMDU->setObjectName(QString::fromUtf8("lbWF36DMDU"));
        lbWF36DMDU->setGeometry(QRect(159, 35, 37, 13));
        lbWF36DMDU->setFont(font);
        lbWF36DMDU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbWF36ACU = new QLabel(frame_9);
        lbWF36ACU->setObjectName(QString::fromUtf8("lbWF36ACU"));
        lbWF36ACU->setGeometry(QRect(159, 56, 37, 13));
        lbWF36ACU->setFont(font);
        lbWF36ACU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbWF36AC = new QLabel(frame_9);
        lbWF36AC->setObjectName(QString::fromUtf8("lbWF36AC"));
        lbWF36AC->setGeometry(QRect(120, 56, 40, 13));
        lbWF36AC->setFont(font);
        lbWF36AC->setAlignment(Qt::AlignCenter);
        lbWF36ACT = new QLabel(frame_9);
        lbWF36ACT->setObjectName(QString::fromUtf8("lbWF36ACT"));
        lbWF36ACT->setGeometry(QRect(47, 56, 74, 13));
        lbWF36ACT->setFont(font);
        lbWF36ACT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbGMVISELU = new QLabel(frame_9);
        lbGMVISELU->setObjectName(QString::fromUtf8("lbGMVISELU"));
        lbGMVISELU->setGeometry(QRect(159, 75, 37, 13));
        lbGMVISELU->setFont(font);
        lbGMVISELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbGMVISELT = new QLabel(frame_9);
        lbGMVISELT->setObjectName(QString::fromUtf8("lbGMVISELT"));
        lbGMVISELT->setGeometry(QRect(47, 75, 74, 16));
        lbGMVISELT->setFont(font);
        lbGMVISELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbGMVISEL = new QLabel(frame_9);
        lbGMVISEL->setObjectName(QString::fromUtf8("lbGMVISEL"));
        lbGMVISEL->setGeometry(QRect(120, 75, 40, 13));
        lbGMVISEL->setFont(font);
        lbGMVISEL->setAlignment(Qt::AlignCenter);
        lbGMVIDMDU = new QLabel(frame_9);
        lbGMVIDMDU->setObjectName(QString::fromUtf8("lbGMVIDMDU"));
        lbGMVIDMDU->setGeometry(QRect(159, 95, 37, 13));
        lbGMVIDMDU->setFont(font);
        lbGMVIDMDU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbGMVIDMDT = new QLabel(frame_9);
        lbGMVIDMDT->setObjectName(QString::fromUtf8("lbGMVIDMDT"));
        lbGMVIDMDT->setGeometry(QRect(47, 95, 74, 16));
        lbGMVIDMDT->setFont(font);
        lbGMVIDMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbGMVIDMD = new QLabel(frame_9);
        lbGMVIDMD->setObjectName(QString::fromUtf8("lbGMVIDMD"));
        lbGMVIDMD->setGeometry(QRect(120, 95, 40, 13));
        lbGMVIDMD->setFont(font);
        lbGMVIDMD->setAlignment(Qt::AlignCenter);
        lbGMVPDMDU = new QLabel(frame_9);
        lbGMVPDMDU->setObjectName(QString::fromUtf8("lbGMVPDMDU"));
        lbGMVPDMDU->setGeometry(QRect(159, 133, 37, 13));
        lbGMVPDMDU->setFont(font);
        lbGMVPDMDU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbGMVPDMDT = new QLabel(frame_9);
        lbGMVPDMDT->setObjectName(QString::fromUtf8("lbGMVPDMDT"));
        lbGMVPDMDT->setGeometry(QRect(47, 133, 74, 13));
        lbGMVPDMDT->setFont(font);
        lbGMVPDMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbGMVPDMD = new QLabel(frame_9);
        lbGMVPDMD->setObjectName(QString::fromUtf8("lbGMVPDMD"));
        lbGMVPDMD->setGeometry(QRect(120, 133, 40, 13));
        lbGMVPDMD->setFont(font);
        lbGMVPDMD->setAlignment(Qt::AlignCenter);
        lbGMVPSELU_2 = new QLabel(frame_9);
        lbGMVPSELU_2->setObjectName(QString::fromUtf8("lbGMVPSELU_2"));
        lbGMVPSELU_2->setGeometry(QRect(159, 153, 37, 13));
        lbGMVPSELU_2->setFont(font);
        lbGMVPSELU_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbGMVPSELT_2 = new QLabel(frame_9);
        lbGMVPSELT_2->setObjectName(QString::fromUtf8("lbGMVPSELT_2"));
        lbGMVPSELT_2->setGeometry(QRect(47, 153, 74, 13));
        lbGMVPSELT_2->setFont(font);
        lbGMVPSELT_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbGMVPSEL_2 = new QLabel(frame_9);
        lbGMVPSEL_2->setObjectName(QString::fromUtf8("lbGMVPSEL_2"));
        lbGMVPSEL_2->setGeometry(QRect(120, 153, 40, 13));
        lbGMVPSEL_2->setFont(font);
        lbGMVPSEL_2->setAlignment(Qt::AlignCenter);
        lbGMVPDMDU_2 = new QLabel(frame_9);
        lbGMVPDMDU_2->setObjectName(QString::fromUtf8("lbGMVPDMDU_2"));
        lbGMVPDMDU_2->setGeometry(QRect(159, 172, 37, 13));
        lbGMVPDMDU_2->setFont(font);
        lbGMVPDMDU_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbGMVPDMDT_2 = new QLabel(frame_9);
        lbGMVPDMDT_2->setObjectName(QString::fromUtf8("lbGMVPDMDT_2"));
        lbGMVPDMDT_2->setGeometry(QRect(47, 172, 74, 13));
        lbGMVPDMDT_2->setFont(font);
        lbGMVPDMDT_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbGMVPDMD_2 = new QLabel(frame_9);
        lbGMVPDMD_2->setObjectName(QString::fromUtf8("lbGMVPDMD_2"));
        lbGMVPDMD_2->setGeometry(QRect(120, 172, 40, 13));
        lbGMVPDMD_2->setFont(font);
        lbGMVPDMD_2->setAlignment(Qt::AlignCenter);
        lbGMVPSELU = new QLabel(frame_9);
        lbGMVPSELU->setObjectName(QString::fromUtf8("lbGMVPSELU"));
        lbGMVPSELU->setGeometry(QRect(159, 114, 37, 13));
        lbGMVPSELU->setFont(font);
        lbGMVPSELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbGMVPSEL = new QLabel(frame_9);
        lbGMVPSEL->setObjectName(QString::fromUtf8("lbGMVPSEL"));
        lbGMVPSEL->setGeometry(QRect(120, 114, 40, 13));
        lbGMVPSEL->setFont(font);
        lbGMVPSEL->setAlignment(Qt::AlignCenter);
        lbGMVPSELT = new QLabel(frame_9);
        lbGMVPSELT->setObjectName(QString::fromUtf8("lbGMVPSELT"));
        lbGMVPSELT->setGeometry(QRect(47, 114, 74, 13));
        lbGMVPSELT->setFont(font);
        lbGMVPSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTGSSELU = new QLabel(frame_9);
        lbTGSSELU->setObjectName(QString::fromUtf8("lbTGSSELU"));
        lbTGSSELU->setGeometry(QRect(160, 191, 37, 13));
        lbTGSSELU->setFont(font);
        lbTGSSELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbTGSSEL = new QLabel(frame_9);
        lbTGSSEL->setObjectName(QString::fromUtf8("lbTGSSEL"));
        lbTGSSEL->setGeometry(QRect(120, 191, 40, 13));
        lbTGSSEL->setFont(font);
        lbTGSSEL->setAlignment(Qt::AlignCenter);
        lbTGSSELT = new QLabel(frame_9);
        lbTGSSELT->setObjectName(QString::fromUtf8("lbTGSSELT"));
        lbTGSSELT->setGeometry(QRect(47, 191, 74, 13));
        lbTGSSELT->setFont(font);
        lbTGSSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTGSSELU_2 = new QLabel(frame_9);
        lbTGSSELU_2->setObjectName(QString::fromUtf8("lbTGSSELU_2"));
        lbTGSSELU_2->setGeometry(QRect(160, 210, 37, 13));
        lbTGSSELU_2->setFont(font);
        lbTGSSELU_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbTGSSELT_2 = new QLabel(frame_9);
        lbTGSSELT_2->setObjectName(QString::fromUtf8("lbTGSSELT_2"));
        lbTGSSELT_2->setGeometry(QRect(47, 210, 74, 13));
        lbTGSSELT_2->setFont(font);
        lbTGSSELT_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTGSSEL_2 = new QLabel(frame_9);
        lbTGSSEL_2->setObjectName(QString::fromUtf8("lbTGSSEL_2"));
        lbTGSSEL_2->setGeometry(QRect(120, 210, 40, 13));
        lbTGSSEL_2->setFont(font);
        lbTGSSEL_2->setAlignment(Qt::AlignCenter);
        frame_11 = new QFrame(C5);
        frame_11->setObjectName(QString::fromUtf8("frame_11"));
        frame_11->setGeometry(QRect(535, 340, 201, 233));
        frame_11->setFrameShape(QFrame::Box);
        frame_11->setFrameShadow(QFrame::Raised);
        frame_12 = new QFrame(frame_11);
        frame_12->setObjectName(QString::fromUtf8("frame_12"));
        frame_12->setGeometry(QRect(2, 0, 196, 28));
        frame_12->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_12->setFrameShape(QFrame::Box);
        frame_12->setFrameShadow(QFrame::Sunken);
        lbTitle_7 = new QLabel(frame_12);
        lbTitle_7->setObjectName(QString::fromUtf8("lbTitle_7"));
        lbTitle_7->setGeometry(QRect(5, 8, 188, 13));
        lbTitle_7->setFont(font);
        lbTitle_7->setAlignment(Qt::AlignCenter);
        lbCDPAT = new QLabel(frame_11);
        lbCDPAT->setObjectName(QString::fromUtf8("lbCDPAT"));
        lbCDPAT->setGeometry(QRect(39, 36, 82, 13));
        lbCDPAT->setFont(font);
        lbCDPAT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbCDPA = new QLabel(frame_11);
        lbCDPA->setObjectName(QString::fromUtf8("lbCDPA"));
        lbCDPA->setGeometry(QRect(120, 36, 40, 13));
        lbCDPA->setFont(font);
        lbCDPA->setAlignment(Qt::AlignCenter);
        lbCDPAU = new QLabel(frame_11);
        lbCDPAU->setObjectName(QString::fromUtf8("lbCDPAU"));
        lbCDPAU->setGeometry(QRect(159, 35, 37, 13));
        lbCDPAU->setFont(font);
        lbCDPAU->setAlignment(Qt::AlignCenter);
        lbCDPBU = new QLabel(frame_11);
        lbCDPBU->setObjectName(QString::fromUtf8("lbCDPBU"));
        lbCDPBU->setGeometry(QRect(159, 56, 37, 13));
        lbCDPBU->setFont(font);
        lbCDPBU->setAlignment(Qt::AlignCenter);
        lbCDPB = new QLabel(frame_11);
        lbCDPB->setObjectName(QString::fromUtf8("lbCDPB"));
        lbCDPB->setGeometry(QRect(119, 56, 40, 13));
        lbCDPB->setFont(font);
        lbCDPB->setAlignment(Qt::AlignCenter);
        lbCDPBT = new QLabel(frame_11);
        lbCDPBT->setObjectName(QString::fromUtf8("lbCDPBT"));
        lbCDPBT->setGeometry(QRect(39, 56, 82, 13));
        lbCDPBT->setFont(font);
        lbCDPBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbCDPSELU = new QLabel(frame_11);
        lbCDPSELU->setObjectName(QString::fromUtf8("lbCDPSELU"));
        lbCDPSELU->setGeometry(QRect(159, 75, 37, 13));
        lbCDPSELU->setFont(font);
        lbCDPSELU->setAlignment(Qt::AlignCenter);
        lbCDPSELT = new QLabel(frame_11);
        lbCDPSELT->setObjectName(QString::fromUtf8("lbCDPSELT"));
        lbCDPSELT->setGeometry(QRect(39, 75, 82, 13));
        lbCDPSELT->setFont(font);
        lbCDPSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbCDPSEL = new QLabel(frame_11);
        lbCDPSEL->setObjectName(QString::fromUtf8("lbCDPSEL"));
        lbCDPSEL->setGeometry(QRect(120, 75, 40, 13));
        lbCDPSEL->setFont(font);
        lbCDPSEL->setAlignment(Qt::AlignCenter);
        lbCDPDMDU = new QLabel(frame_11);
        lbCDPDMDU->setObjectName(QString::fromUtf8("lbCDPDMDU"));
        lbCDPDMDU->setGeometry(QRect(159, 95, 37, 13));
        lbCDPDMDU->setFont(font);
        lbCDPDMDU->setAlignment(Qt::AlignCenter);
        lbCDPDMDT = new QLabel(frame_11);
        lbCDPDMDT->setObjectName(QString::fromUtf8("lbCDPDMDT"));
        lbCDPDMDT->setGeometry(QRect(39, 95, 82, 13));
        lbCDPDMDT->setFont(font);
        lbCDPDMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbCDPDMD = new QLabel(frame_11);
        lbCDPDMD->setObjectName(QString::fromUtf8("lbCDPDMD"));
        lbCDPDMD->setGeometry(QRect(120, 95, 40, 13));
        lbCDPDMD->setFont(font);
        lbCDPDMD->setAlignment(Qt::AlignCenter);
        lbST8AU = new QLabel(frame_11);
        lbST8AU->setObjectName(QString::fromUtf8("lbST8AU"));
        lbST8AU->setGeometry(QRect(159, 133, 37, 13));
        lbST8AU->setFont(font);
        lbST8AU->setAlignment(Qt::AlignCenter);
        lbST8AT = new QLabel(frame_11);
        lbST8AT->setObjectName(QString::fromUtf8("lbST8AT"));
        lbST8AT->setGeometry(QRect(39, 133, 82, 13));
        lbST8AT->setFont(font);
        lbST8AT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbST8A = new QLabel(frame_11);
        lbST8A->setObjectName(QString::fromUtf8("lbST8A"));
        lbST8A->setGeometry(QRect(120, 133, 40, 13));
        lbST8A->setFont(font);
        lbST8A->setAlignment(Qt::AlignCenter);
        lbST8BU = new QLabel(frame_11);
        lbST8BU->setObjectName(QString::fromUtf8("lbST8BU"));
        lbST8BU->setGeometry(QRect(159, 153, 37, 13));
        lbST8BU->setFont(font);
        lbST8BU->setAlignment(Qt::AlignCenter);
        lbST8BT = new QLabel(frame_11);
        lbST8BT->setObjectName(QString::fromUtf8("lbST8BT"));
        lbST8BT->setGeometry(QRect(39, 153, 82, 13));
        lbST8BT->setFont(font);
        lbST8BT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbST8B = new QLabel(frame_11);
        lbST8B->setObjectName(QString::fromUtf8("lbST8B"));
        lbST8B->setGeometry(QRect(120, 153, 40, 13));
        lbST8B->setFont(font);
        lbST8B->setAlignment(Qt::AlignCenter);
        lbST8SELU = new QLabel(frame_11);
        lbST8SELU->setObjectName(QString::fromUtf8("lbST8SELU"));
        lbST8SELU->setGeometry(QRect(159, 172, 37, 13));
        lbST8SELU->setFont(font);
        lbST8SELU->setAlignment(Qt::AlignCenter);
        lbST8SELT = new QLabel(frame_11);
        lbST8SELT->setObjectName(QString::fromUtf8("lbST8SELT"));
        lbST8SELT->setGeometry(QRect(39, 172, 82, 13));
        lbST8SELT->setFont(font);
        lbST8SELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbST8SEL = new QLabel(frame_11);
        lbST8SEL->setObjectName(QString::fromUtf8("lbST8SEL"));
        lbST8SEL->setGeometry(QRect(120, 172, 40, 13));
        lbST8SEL->setFont(font);
        lbST8SEL->setAlignment(Qt::AlignCenter);
        lbST8DMDU = new QLabel(frame_11);
        lbST8DMDU->setObjectName(QString::fromUtf8("lbST8DMDU"));
        lbST8DMDU->setGeometry(QRect(160, 191, 37, 13));
        lbST8DMDU->setFont(font);
        lbST8DMDU->setAlignment(Qt::AlignCenter);
        lbST8DMD = new QLabel(frame_11);
        lbST8DMD->setObjectName(QString::fromUtf8("lbST8DMD"));
        lbST8DMD->setGeometry(QRect(121, 191, 40, 13));
        lbST8DMD->setFont(font);
        lbST8DMD->setAlignment(Qt::AlignCenter);
        lbST8DMDT = new QLabel(frame_11);
        lbST8DMDT->setObjectName(QString::fromUtf8("lbST8DMDT"));
        lbST8DMDT->setGeometry(QRect(39, 191, 82, 16));
        lbST8DMDT->setFont(font);
        lbST8DMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_13 = new QFrame(C5);
        frame_13->setObjectName(QString::fromUtf8("frame_13"));
        frame_13->setGeometry(QRect(60, 340, 201, 283));
        frame_13->setFrameShape(QFrame::Box);
        frame_13->setFrameShadow(QFrame::Raised);
        frame_14 = new QFrame(frame_13);
        frame_14->setObjectName(QString::fromUtf8("frame_14"));
        frame_14->setGeometry(QRect(2, 0, 196, 28));
        frame_14->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_14->setFrameShape(QFrame::Box);
        frame_14->setFrameShadow(QFrame::Sunken);
        lbTitle_5 = new QLabel(frame_14);
        lbTitle_5->setObjectName(QString::fromUtf8("lbTitle_5"));
        lbTitle_5->setGeometry(QRect(5, 8, 188, 13));
        lbTitle_5->setFont(font);
        lbTitle_5->setAlignment(Qt::AlignCenter);
        lbVSVAT = new QLabel(frame_13);
        lbVSVAT->setObjectName(QString::fromUtf8("lbVSVAT"));
        lbVSVAT->setGeometry(QRect(57, 36, 50, 13));
        lbVSVAT->setFont(font);
        lbVSVAT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbVSVA = new QLabel(frame_13);
        lbVSVA->setObjectName(QString::fromUtf8("lbVSVA"));
        lbVSVA->setGeometry(QRect(120, 36, 40, 13));
        lbVSVA->setFont(font);
        lbVSVA->setAlignment(Qt::AlignCenter);
        lbVSVAU = new QLabel(frame_13);
        lbVSVAU->setObjectName(QString::fromUtf8("lbVSVAU"));
        lbVSVAU->setGeometry(QRect(154, 35, 37, 13));
        lbVSVAU->setFont(font);
        lbVSVAU->setAlignment(Qt::AlignCenter);
        lbVSVBU = new QLabel(frame_13);
        lbVSVBU->setObjectName(QString::fromUtf8("lbVSVBU"));
        lbVSVBU->setGeometry(QRect(154, 56, 37, 13));
        lbVSVBU->setFont(font);
        lbVSVBU->setAlignment(Qt::AlignCenter);
        lbVSVB = new QLabel(frame_13);
        lbVSVB->setObjectName(QString::fromUtf8("lbVSVB"));
        lbVSVB->setGeometry(QRect(120, 56, 40, 13));
        lbVSVB->setFont(font);
        lbVSVB->setAlignment(Qt::AlignCenter);
        lbVSVBT = new QLabel(frame_13);
        lbVSVBT->setObjectName(QString::fromUtf8("lbVSVBT"));
        lbVSVBT->setGeometry(QRect(57, 56, 50, 13));
        lbVSVBT->setFont(font);
        lbVSVBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbVSVSELU = new QLabel(frame_13);
        lbVSVSELU->setObjectName(QString::fromUtf8("lbVSVSELU"));
        lbVSVSELU->setGeometry(QRect(154, 75, 37, 13));
        lbVSVSELU->setFont(font);
        lbVSVSELU->setAlignment(Qt::AlignCenter);
        lbVSVSELT = new QLabel(frame_13);
        lbVSVSELT->setObjectName(QString::fromUtf8("lbVSVSELT"));
        lbVSVSELT->setGeometry(QRect(57, 75, 50, 13));
        lbVSVSELT->setFont(font);
        lbVSVSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbVSVSEL = new QLabel(frame_13);
        lbVSVSEL->setObjectName(QString::fromUtf8("lbVSVSEL"));
        lbVSVSEL->setGeometry(QRect(120, 75, 40, 13));
        lbVSVSEL->setFont(font);
        lbVSVSEL->setAlignment(Qt::AlignCenter);
        lbVSVDMDU = new QLabel(frame_13);
        lbVSVDMDU->setObjectName(QString::fromUtf8("lbVSVDMDU"));
        lbVSVDMDU->setGeometry(QRect(154, 95, 37, 13));
        lbVSVDMDU->setFont(font);
        lbVSVDMDU->setAlignment(Qt::AlignCenter);
        lbVSVDMDT = new QLabel(frame_13);
        lbVSVDMDT->setObjectName(QString::fromUtf8("lbVSVDMDT"));
        lbVSVDMDT->setGeometry(QRect(57, 95, 50, 13));
        lbVSVDMDT->setFont(font);
        lbVSVDMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbVSVDMD = new QLabel(frame_13);
        lbVSVDMD->setObjectName(QString::fromUtf8("lbVSVDMD"));
        lbVSVDMD->setGeometry(QRect(120, 95, 40, 13));
        lbVSVDMD->setFont(font);
        lbVSVDMD->setAlignment(Qt::AlignCenter);
        lbIGVA = new QLabel(frame_13);
        lbIGVA->setObjectName(QString::fromUtf8("lbIGVA"));
        lbIGVA->setGeometry(QRect(120, 201, 40, 13));
        lbIGVA->setFont(font);
        lbIGVA->setAlignment(Qt::AlignCenter);
        lbIGVBU = new QLabel(frame_13);
        lbIGVBU->setObjectName(QString::fromUtf8("lbIGVBU"));
        lbIGVBU->setGeometry(QRect(154, 221, 37, 13));
        lbIGVBU->setFont(font);
        lbIGVBU->setAlignment(Qt::AlignCenter);
        lbIGVSEL = new QLabel(frame_13);
        lbIGVSEL->setObjectName(QString::fromUtf8("lbIGVSEL"));
        lbIGVSEL->setGeometry(QRect(120, 240, 40, 13));
        lbIGVSEL->setFont(font);
        lbIGVSEL->setAlignment(Qt::AlignCenter);
        lbIGVDMDU = new QLabel(frame_13);
        lbIGVDMDU->setObjectName(QString::fromUtf8("lbIGVDMDU"));
        lbIGVDMDU->setGeometry(QRect(154, 260, 37, 13));
        lbIGVDMDU->setFont(font);
        lbIGVDMDU->setAlignment(Qt::AlignCenter);
        lbIGVDMDT = new QLabel(frame_13);
        lbIGVDMDT->setObjectName(QString::fromUtf8("lbIGVDMDT"));
        lbIGVDMDT->setGeometry(QRect(57, 260, 50, 13));
        lbIGVDMDT->setFont(font);
        lbIGVDMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbIGVDMD = new QLabel(frame_13);
        lbIGVDMD->setObjectName(QString::fromUtf8("lbIGVDMD"));
        lbIGVDMD->setGeometry(QRect(120, 260, 40, 13));
        lbIGVDMD->setFont(font);
        lbIGVDMD->setAlignment(Qt::AlignCenter);
        lbIGVAT = new QLabel(frame_13);
        lbIGVAT->setObjectName(QString::fromUtf8("lbIGVAT"));
        lbIGVAT->setGeometry(QRect(57, 201, 50, 13));
        lbIGVAT->setFont(font);
        lbIGVAT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbIGVAU = new QLabel(frame_13);
        lbIGVAU->setObjectName(QString::fromUtf8("lbIGVAU"));
        lbIGVAU->setGeometry(QRect(154, 200, 37, 13));
        lbIGVAU->setFont(font);
        lbIGVAU->setAlignment(Qt::AlignCenter);
        lbIGVBT = new QLabel(frame_13);
        lbIGVBT->setObjectName(QString::fromUtf8("lbIGVBT"));
        lbIGVBT->setGeometry(QRect(57, 221, 50, 13));
        lbIGVBT->setFont(font);
        lbIGVBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbIGVSELU = new QLabel(frame_13);
        lbIGVSELU->setObjectName(QString::fromUtf8("lbIGVSELU"));
        lbIGVSELU->setGeometry(QRect(154, 240, 37, 13));
        lbIGVSELU->setFont(font);
        lbIGVSELU->setAlignment(Qt::AlignCenter);
        lbIGVSELT = new QLabel(frame_13);
        lbIGVSELT->setObjectName(QString::fromUtf8("lbIGVSELT"));
        lbIGVSELT->setGeometry(QRect(57, 240, 50, 13));
        lbIGVSELT->setFont(font);
        lbIGVSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbIGVB = new QLabel(frame_13);
        lbIGVB->setObjectName(QString::fromUtf8("lbIGVB"));
        lbIGVB->setGeometry(QRect(120, 221, 40, 13));
        lbIGVB->setFont(font);
        lbIGVB->setAlignment(Qt::AlignCenter);
        lbVBVA = new QLabel(frame_13);
        lbVBVA->setObjectName(QString::fromUtf8("lbVBVA"));
        lbVBVA->setGeometry(QRect(120, 120, 40, 13));
        lbVBVA->setFont(font);
        lbVBVA->setAlignment(Qt::AlignCenter);
        lbVBVBU = new QLabel(frame_13);
        lbVBVBU->setObjectName(QString::fromUtf8("lbVBVBU"));
        lbVBVBU->setGeometry(QRect(154, 140, 37, 13));
        lbVBVBU->setFont(font);
        lbVBVBU->setAlignment(Qt::AlignCenter);
        lbVBVSEL = new QLabel(frame_13);
        lbVBVSEL->setObjectName(QString::fromUtf8("lbVBVSEL"));
        lbVBVSEL->setGeometry(QRect(120, 159, 40, 13));
        lbVBVSEL->setFont(font);
        lbVBVSEL->setAlignment(Qt::AlignCenter);
        lbVBVDMDU = new QLabel(frame_13);
        lbVBVDMDU->setObjectName(QString::fromUtf8("lbVBVDMDU"));
        lbVBVDMDU->setGeometry(QRect(154, 179, 37, 13));
        lbVBVDMDU->setFont(font);
        lbVBVDMDU->setAlignment(Qt::AlignCenter);
        lbVBVDMDT = new QLabel(frame_13);
        lbVBVDMDT->setObjectName(QString::fromUtf8("lbVBVDMDT"));
        lbVBVDMDT->setGeometry(QRect(57, 179, 50, 13));
        lbVBVDMDT->setFont(font);
        lbVBVDMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbVBVDMD = new QLabel(frame_13);
        lbVBVDMD->setObjectName(QString::fromUtf8("lbVBVDMD"));
        lbVBVDMD->setGeometry(QRect(120, 179, 40, 13));
        lbVBVDMD->setFont(font);
        lbVBVDMD->setAlignment(Qt::AlignCenter);
        lbVBVAT = new QLabel(frame_13);
        lbVBVAT->setObjectName(QString::fromUtf8("lbVBVAT"));
        lbVBVAT->setGeometry(QRect(57, 120, 50, 13));
        lbVBVAT->setFont(font);
        lbVBVAT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbVBVAU = new QLabel(frame_13);
        lbVBVAU->setObjectName(QString::fromUtf8("lbVBVAU"));
        lbVBVAU->setGeometry(QRect(154, 119, 37, 13));
        lbVBVAU->setFont(font);
        lbVBVAU->setAlignment(Qt::AlignCenter);
        lbVBVBT = new QLabel(frame_13);
        lbVBVBT->setObjectName(QString::fromUtf8("lbVBVBT"));
        lbVBVBT->setGeometry(QRect(57, 140, 50, 13));
        lbVBVBT->setFont(font);
        lbVBVBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbVBVSELU = new QLabel(frame_13);
        lbVBVSELU->setObjectName(QString::fromUtf8("lbVBVSELU"));
        lbVBVSELU->setGeometry(QRect(154, 159, 37, 13));
        lbVBVSELU->setFont(font);
        lbVBVSELU->setAlignment(Qt::AlignCenter);
        lbVBVSELT = new QLabel(frame_13);
        lbVBVSELT->setObjectName(QString::fromUtf8("lbVBVSELT"));
        lbVBVSELT->setGeometry(QRect(57, 159, 50, 13));
        lbVBVSELT->setFont(font);
        lbVBVSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbVBVB = new QLabel(frame_13);
        lbVBVB->setObjectName(QString::fromUtf8("lbVBVB"));
        lbVBVB->setGeometry(QRect(120, 140, 40, 13));
        lbVBVB->setFont(font);
        lbVBVB->setAlignment(Qt::AlignCenter);
        frame_15 = new QFrame(C5);
        frame_15->setObjectName(QString::fromUtf8("frame_15"));
        frame_15->setGeometry(QRect(297, 340, 201, 233));
        frame_15->setFrameShape(QFrame::Box);
        frame_15->setFrameShadow(QFrame::Raised);
        frame_16 = new QFrame(frame_15);
        frame_16->setObjectName(QString::fromUtf8("frame_16"));
        frame_16->setGeometry(QRect(2, 0, 196, 28));
        frame_16->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_16->setFrameShape(QFrame::Box);
        frame_16->setFrameShadow(QFrame::Sunken);
        lbTitle_6 = new QLabel(frame_16);
        lbTitle_6->setObjectName(QString::fromUtf8("lbTitle_6"));
        lbTitle_6->setGeometry(QRect(5, 8, 188, 13));
        lbTitle_6->setFont(font);
        lbTitle_6->setAlignment(Qt::AlignCenter);
        lbPTBAT = new QLabel(frame_15);
        lbPTBAT->setObjectName(QString::fromUtf8("lbPTBAT"));
        lbPTBAT->setGeometry(QRect(73, 36, 46, 13));
        lbPTBAT->setFont(font);
        lbPTBAT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbPTBA = new QLabel(frame_15);
        lbPTBA->setObjectName(QString::fromUtf8("lbPTBA"));
        lbPTBA->setGeometry(QRect(120, 36, 40, 13));
        lbPTBA->setFont(font);
        lbPTBA->setAlignment(Qt::AlignCenter);
        lbPTBAU = new QLabel(frame_15);
        lbPTBAU->setObjectName(QString::fromUtf8("lbPTBAU"));
        lbPTBAU->setGeometry(QRect(159, 35, 37, 13));
        lbPTBAU->setFont(font);
        lbPTBAU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPTBBU = new QLabel(frame_15);
        lbPTBBU->setObjectName(QString::fromUtf8("lbPTBBU"));
        lbPTBBU->setGeometry(QRect(159, 56, 37, 13));
        lbPTBBU->setFont(font);
        lbPTBBU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPTBB = new QLabel(frame_15);
        lbPTBB->setObjectName(QString::fromUtf8("lbPTBB"));
        lbPTBB->setGeometry(QRect(119, 56, 40, 13));
        lbPTBB->setFont(font);
        lbPTBB->setAlignment(Qt::AlignCenter);
        lbPTBBT = new QLabel(frame_15);
        lbPTBBT->setObjectName(QString::fromUtf8("lbPTBBT"));
        lbPTBBT->setGeometry(QRect(73, 56, 46, 13));
        lbPTBBT->setFont(font);
        lbPTBBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbPTBSELU = new QLabel(frame_15);
        lbPTBSELU->setObjectName(QString::fromUtf8("lbPTBSELU"));
        lbPTBSELU->setGeometry(QRect(159, 75, 37, 13));
        lbPTBSELU->setFont(font);
        lbPTBSELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPTBSELT = new QLabel(frame_15);
        lbPTBSELT->setObjectName(QString::fromUtf8("lbPTBSELT"));
        lbPTBSELT->setGeometry(QRect(73, 75, 46, 13));
        lbPTBSELT->setFont(font);
        lbPTBSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbPTBSEL = new QLabel(frame_15);
        lbPTBSEL->setObjectName(QString::fromUtf8("lbPTBSEL"));
        lbPTBSEL->setGeometry(QRect(120, 75, 40, 13));
        lbPTBSEL->setFont(font);
        lbPTBSEL->setAlignment(Qt::AlignCenter);
        lbTBVAU = new QLabel(frame_15);
        lbTBVAU->setObjectName(QString::fromUtf8("lbTBVAU"));
        lbTBVAU->setGeometry(QRect(159, 133, 37, 13));
        lbTBVAU->setFont(font);
        lbTBVAU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbTBVAT = new QLabel(frame_15);
        lbTBVAT->setObjectName(QString::fromUtf8("lbTBVAT"));
        lbTBVAT->setGeometry(QRect(73, 133, 46, 13));
        lbTBVAT->setFont(font);
        lbTBVAT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTBVA = new QLabel(frame_15);
        lbTBVA->setObjectName(QString::fromUtf8("lbTBVA"));
        lbTBVA->setGeometry(QRect(120, 133, 40, 13));
        lbTBVA->setFont(font);
        lbTBVA->setAlignment(Qt::AlignCenter);
        lbTBVBU = new QLabel(frame_15);
        lbTBVBU->setObjectName(QString::fromUtf8("lbTBVBU"));
        lbTBVBU->setGeometry(QRect(159, 153, 37, 13));
        lbTBVBU->setFont(font);
        lbTBVBU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbTBVBT = new QLabel(frame_15);
        lbTBVBT->setObjectName(QString::fromUtf8("lbTBVBT"));
        lbTBVBT->setGeometry(QRect(73, 153, 46, 13));
        lbTBVBT->setFont(font);
        lbTBVBT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTBVB = new QLabel(frame_15);
        lbTBVB->setObjectName(QString::fromUtf8("lbTBVB"));
        lbTBVB->setGeometry(QRect(120, 153, 40, 13));
        lbTBVB->setFont(font);
        lbTBVB->setAlignment(Qt::AlignCenter);
        lbTBVSELU = new QLabel(frame_15);
        lbTBVSELU->setObjectName(QString::fromUtf8("lbTBVSELU"));
        lbTBVSELU->setGeometry(QRect(159, 172, 37, 13));
        lbTBVSELU->setFont(font);
        lbTBVSELU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbTBVSELT = new QLabel(frame_15);
        lbTBVSELT->setObjectName(QString::fromUtf8("lbTBVSELT"));
        lbTBVSELT->setGeometry(QRect(73, 172, 46, 13));
        lbTBVSELT->setFont(font);
        lbTBVSELT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTBVSEL = new QLabel(frame_15);
        lbTBVSEL->setObjectName(QString::fromUtf8("lbTBVSEL"));
        lbTBVSEL->setGeometry(QRect(120, 172, 40, 13));
        lbTBVSEL->setFont(font);
        lbTBVSEL->setAlignment(Qt::AlignCenter);
        lbTBVDMDU = new QLabel(frame_15);
        lbTBVDMDU->setObjectName(QString::fromUtf8("lbTBVDMDU"));
        lbTBVDMDU->setGeometry(QRect(160, 191, 37, 13));
        lbTBVDMDU->setFont(font);
        lbTBVDMDU->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbTBVDMD = new QLabel(frame_15);
        lbTBVDMD->setObjectName(QString::fromUtf8("lbTBVDMD"));
        lbTBVDMD->setGeometry(QRect(121, 191, 40, 13));
        lbTBVDMD->setFont(font);
        lbTBVDMD->setAlignment(Qt::AlignCenter);
        lbTBVDMDT = new QLabel(frame_15);
        lbTBVDMDT->setObjectName(QString::fromUtf8("lbTBVDMDT"));
        lbTBVDMDT->setGeometry(QRect(74, 191, 46, 13));
        lbTBVDMDT->setFont(font);
        lbTBVDMDT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_232 = new QLabel(C5);
        label_232->setObjectName(QString::fromUtf8("label_232"));
        label_232->setGeometry(QRect(0, 0, 1024, 662));
        label_232->setMinimumSize(QSize(1024, 662));
        label_232->setMaximumSize(QSize(1024, 662));
        label_232->raise();
        lbFondo->raise();
        frame->raise();
        frame_3->raise();
        frame_5->raise();
        frame_7->raise();
        frame_9->raise();
        frame_11->raise();
        frame_13->raise();
        frame_15->raise();

        retranslateUi(C5);

        QMetaObject::connectSlotsByName(C5);
    } // setupUi

    void retranslateUi(QWidget *C5)
    {
        C5->setWindowTitle(QApplication::translate("C5", "Form", 0, QApplication::UnicodeUTF8));
        lbFondo->setText(QString());
        lbTitle_1->setText(QApplication::translate("C5", "VELOCIDAD DE LA TURBINA", 0, QApplication::UnicodeUTF8));
        lbN25AT->setText(QApplication::translate("C5", "N25A", 0, QApplication::UnicodeUTF8));
        lbN25A->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbN25AU->setText(QApplication::translate("C5", "RPM", 0, QApplication::UnicodeUTF8));
        lbN25BU->setText(QApplication::translate("C5", "RPM", 0, QApplication::UnicodeUTF8));
        lbN25B->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbN25BT->setText(QApplication::translate("C5", "N25B", 0, QApplication::UnicodeUTF8));
        lbN25SELU->setText(QApplication::translate("C5", "RPM", 0, QApplication::UnicodeUTF8));
        lbN25SELT->setText(QApplication::translate("C5", "N25SEL", 0, QApplication::UnicodeUTF8));
        lbN25SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbN25REFU->setText(QApplication::translate("C5", "RPM", 0, QApplication::UnicodeUTF8));
        lbN25REFT->setText(QApplication::translate("C5", "N25REF", 0, QApplication::UnicodeUTF8));
        lbN25REF->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbNSDAU->setText(QApplication::translate("C5", "RPM", 0, QApplication::UnicodeUTF8));
        lbNSDAT->setText(QApplication::translate("C5", "NSDA", 0, QApplication::UnicodeUTF8));
        lbNSDA->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbNSDBU->setText(QApplication::translate("C5", "RPM", 0, QApplication::UnicodeUTF8));
        lbNSDBT->setText(QApplication::translate("C5", "NSDB", 0, QApplication::UnicodeUTF8));
        lbNSDB->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbNSDSELU->setText(QApplication::translate("C5", "RPM", 0, QApplication::UnicodeUTF8));
        lbNSDSELT->setText(QApplication::translate("C5", "NSDSEL", 0, QApplication::UnicodeUTF8));
        lbNSDSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTitle_3->setText(QApplication::translate("C5", "TEMPERATURAS DE TERBINA", 0, QApplication::UnicodeUTF8));
        lbT2AT->setText(QApplication::translate("C5", "T2A", 0, QApplication::UnicodeUTF8));
        lbT2A->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT2AU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT2BU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT2B->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT2BT->setText(QApplication::translate("C5", "T2B", 0, QApplication::UnicodeUTF8));
        lbT2SELU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT2SELT->setText(QApplication::translate("C5", "T2SEL", 0, QApplication::UnicodeUTF8));
        lbT2SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT25BU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT25BT->setText(QApplication::translate("C5", "T25B", 0, QApplication::UnicodeUTF8));
        lbT25B->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT25SELU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT25SELT->setText(QApplication::translate("C5", "T25SEL", 0, QApplication::UnicodeUTF8));
        lbT25SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT3A1U->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT3A1T->setText(QApplication::translate("C5", "T3A1", 0, QApplication::UnicodeUTF8));
        lbT3A1->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT25AU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT25A->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT25AT->setText(QApplication::translate("C5", "T25A", 0, QApplication::UnicodeUTF8));
        lbT3A2U->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT3A2->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT3A2T->setText(QApplication::translate("C5", "T3A2", 0, QApplication::UnicodeUTF8));
        lbT3B1U->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT3B1T->setText(QApplication::translate("C5", "T3B1", 0, QApplication::UnicodeUTF8));
        lbT3B1->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT3B2U->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT3B2->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT3SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT3SELU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT3SELT->setText(QApplication::translate("C5", "T3SEL", 0, QApplication::UnicodeUTF8));
        lbT3B2T->setText(QApplication::translate("C5", "T3B2", 0, QApplication::UnicodeUTF8));
        lbTitle_2->setText(QApplication::translate("C5", "TEMPERATURAS DE TERBINA", 0, QApplication::UnicodeUTF8));
        lbT48AT->setText(QApplication::translate("C5", "T48A", 0, QApplication::UnicodeUTF8));
        lbT48A->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48AU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48BU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48B->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48BT->setText(QApplication::translate("C5", "T48B", 0, QApplication::UnicodeUTF8));
        lbT48CU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48CT->setText(QApplication::translate("C5", "T48C", 0, QApplication::UnicodeUTF8));
        lbT48C->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48DU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48DT->setText(QApplication::translate("C5", "T48D", 0, QApplication::UnicodeUTF8));
        lbT48D->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48FU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48FT->setText(QApplication::translate("C5", "T48F", 0, QApplication::UnicodeUTF8));
        lbT48F->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48GU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48GT->setText(QApplication::translate("C5", "T48G", 0, QApplication::UnicodeUTF8));
        lbT48G->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48HU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48HT->setText(QApplication::translate("C5", "T48H", 0, QApplication::UnicodeUTF8));
        lbT48H->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48EU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48E->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48ET->setText(QApplication::translate("C5", "T48E", 0, QApplication::UnicodeUTF8));
        lbT48SELU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbT48SELT->setText(QApplication::translate("C5", "T48SEL", 0, QApplication::UnicodeUTF8));
        lbT48REFU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48REFT->setText(QApplication::translate("C5", "T48REF", 0, QApplication::UnicodeUTF8));
        lbT48REF->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTitle_4->setText(QApplication::translate("C5", "PRESIONES DE TURBINA", 0, QApplication::UnicodeUTF8));
        lbPOSELT->setText(QApplication::translate("C5", "POSEL", 0, QApplication::UnicodeUTF8));
        lbPOSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbPOSELU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbP25AU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbP25AT->setText(QApplication::translate("C5", "P25A", 0, QApplication::UnicodeUTF8));
        lbP25A->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbP25BU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbP25BT->setText(QApplication::translate("C5", "P25B", 0, QApplication::UnicodeUTF8));
        lbP25B->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbPS3AU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbPS3AT->setText(QApplication::translate("C5", "PS3A", 0, QApplication::UnicodeUTF8));
        lbPS3A->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbPS3BU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbPS3BT->setText(QApplication::translate("C5", "PS3B", 0, QApplication::UnicodeUTF8));
        lbPS3B->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbPS3SELU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbPS3SELT->setText(QApplication::translate("C5", "PS3SEL", 0, QApplication::UnicodeUTF8));
        lbPS3SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbP25SELU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbP25SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbP25SELT->setText(QApplication::translate("C5", "P25SEL", 0, QApplication::UnicodeUTF8));
        lbP48SELU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbP48SELT->setText(QApplication::translate("C5", "P48SEL", 0, QApplication::UnicodeUTF8));
        lbP48SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTitle_8->setText(QApplication::translate("C5", "PROPIEDADES DEL COMB ", 0, QApplication::UnicodeUTF8));
        lbWF36DMDT->setText(QApplication::translate("C5", "WF36DMD", 0, QApplication::UnicodeUTF8));
        lbWF36DMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbWF36DMDU->setText(QApplication::translate("C5", "Lbs/Hr", 0, QApplication::UnicodeUTF8));
        lbWF36ACU->setText(QApplication::translate("C5", "Lbs/Hr", 0, QApplication::UnicodeUTF8));
        lbWF36AC->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbWF36ACT->setText(QApplication::translate("C5", "WF36ACT", 0, QApplication::UnicodeUTF8));
        lbGMVISELU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbGMVISELT->setText(QApplication::translate("C5", "GMVISEL", 0, QApplication::UnicodeUTF8));
        lbGMVISEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbGMVIDMDU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbGMVIDMDT->setText(QApplication::translate("C5", "GMVIDMD", 0, QApplication::UnicodeUTF8));
        lbGMVIDMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbGMVPDMDU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbGMVPDMDT->setText(QApplication::translate("C5", "GMVPDMD", 0, QApplication::UnicodeUTF8));
        lbGMVPDMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbGMVPSELU_2->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbGMVPSELT_2->setText(QApplication::translate("C5", "GMVPSEL", 0, QApplication::UnicodeUTF8));
        lbGMVPSEL_2->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbGMVPDMDU_2->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbGMVPDMDT_2->setText(QApplication::translate("C5", "GMVPDMD", 0, QApplication::UnicodeUTF8));
        lbGMVPDMD_2->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbGMVPSELU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbGMVPSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbGMVPSELT->setText(QApplication::translate("C5", "GMVPSEL", 0, QApplication::UnicodeUTF8));
        lbTGSSELU->setText(QApplication::translate("C5", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbTGSSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTGSSELT->setText(QApplication::translate("C5", "TGSSEL", 0, QApplication::UnicodeUTF8));
        lbTGSSELU_2->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbTGSSELT_2->setText(QApplication::translate("C5", "TGSSEL", 0, QApplication::UnicodeUTF8));
        lbTGSSEL_2->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTitle_7->setText(QApplication::translate("C5", "V\303\201LVULAS DE PURGA", 0, QApplication::UnicodeUTF8));
        lbCDPAT->setText(QApplication::translate("C5", "CDPA", 0, QApplication::UnicodeUTF8));
        lbCDPA->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbCDPAU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbCDPBU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbCDPB->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbCDPBT->setText(QApplication::translate("C5", "CDPB", 0, QApplication::UnicodeUTF8));
        lbCDPSELU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbCDPSELT->setText(QApplication::translate("C5", "CDPSEL", 0, QApplication::UnicodeUTF8));
        lbCDPSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbCDPDMDU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbCDPDMDT->setText(QApplication::translate("C5", "CDPDMD", 0, QApplication::UnicodeUTF8));
        lbCDPDMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbST8AU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbST8AT->setText(QApplication::translate("C5", "ST8A", 0, QApplication::UnicodeUTF8));
        lbST8A->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbST8BU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbST8BT->setText(QApplication::translate("C5", "ST8B", 0, QApplication::UnicodeUTF8));
        lbST8B->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbST8SELU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbST8SELT->setText(QApplication::translate("C5", "ST8SEL", 0, QApplication::UnicodeUTF8));
        lbST8SEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbST8DMDU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbST8DMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbST8DMDT->setText(QApplication::translate("C5", "ST8DMD", 0, QApplication::UnicodeUTF8));
        lbTitle_5->setText(QApplication::translate("C5", "GEOMETR\303\215A VARIABLE", 0, QApplication::UnicodeUTF8));
        lbVSVAT->setText(QApplication::translate("C5", "VSVA", 0, QApplication::UnicodeUTF8));
        lbVSVA->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbVSVAU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbVSVBU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbVSVB->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbVSVBT->setText(QApplication::translate("C5", "VSVB", 0, QApplication::UnicodeUTF8));
        lbVSVSELU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbVSVSELT->setText(QApplication::translate("C5", "VSVSEL", 0, QApplication::UnicodeUTF8));
        lbVSVSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbVSVDMDU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbVSVDMDT->setText(QApplication::translate("C5", "VSVDMD", 0, QApplication::UnicodeUTF8));
        lbVSVDMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbIGVA->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbIGVBU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbIGVSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbIGVDMDU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbIGVDMDT->setText(QApplication::translate("C5", "IGVDMD", 0, QApplication::UnicodeUTF8));
        lbIGVDMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbIGVAT->setText(QApplication::translate("C5", "IGVA", 0, QApplication::UnicodeUTF8));
        lbIGVAU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbIGVBT->setText(QApplication::translate("C5", "IGVB", 0, QApplication::UnicodeUTF8));
        lbIGVSELU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbIGVSELT->setText(QApplication::translate("C5", "IGVSEL", 0, QApplication::UnicodeUTF8));
        lbIGVB->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbVBVA->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbVBVBU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbVBVSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbVBVDMDU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbVBVDMDT->setText(QApplication::translate("C5", "VBVDMD", 0, QApplication::UnicodeUTF8));
        lbVBVDMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbVBVAT->setText(QApplication::translate("C5", "VBVA", 0, QApplication::UnicodeUTF8));
        lbVBVAU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbVBVBT->setText(QApplication::translate("C5", "VBVB", 0, QApplication::UnicodeUTF8));
        lbVBVSELU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbVBVSELT->setText(QApplication::translate("C5", "VBVSEL", 0, QApplication::UnicodeUTF8));
        lbVBVB->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTitle_6->setText(QApplication::translate("C5", "EQUILIBRIO DE IMPULSI\303\223N", 0, QApplication::UnicodeUTF8));
        lbPTBAT->setText(QApplication::translate("C5", "PTBA", 0, QApplication::UnicodeUTF8));
        lbPTBA->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbPTBAU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbPTBBU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbPTBB->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbPTBBT->setText(QApplication::translate("C5", "PTBB", 0, QApplication::UnicodeUTF8));
        lbPTBSELU->setText(QApplication::translate("C5", "PSIA", 0, QApplication::UnicodeUTF8));
        lbPTBSELT->setText(QApplication::translate("C5", "PTBSEL", 0, QApplication::UnicodeUTF8));
        lbPTBSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTBVAU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbTBVAT->setText(QApplication::translate("C5", "TBVA", 0, QApplication::UnicodeUTF8));
        lbTBVA->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTBVBU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbTBVBT->setText(QApplication::translate("C5", "TBVB", 0, QApplication::UnicodeUTF8));
        lbTBVB->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTBVSELU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbTBVSELT->setText(QApplication::translate("C5", "TBVSEL", 0, QApplication::UnicodeUTF8));
        lbTBVSEL->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTBVDMDU->setText(QApplication::translate("C5", "%", 0, QApplication::UnicodeUTF8));
        lbTBVDMD->setText(QApplication::translate("C5", "0", 0, QApplication::UnicodeUTF8));
        lbTBVDMDT->setText(QApplication::translate("C5", "TBVDMD", 0, QApplication::UnicodeUTF8));
        label_232->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class C5: public Ui_C5 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_C5_H
