/********************************************************************************
** Form generated from reading UI file 'c1.ui'
**
** Created: Mon 23. Sep 20:33:30 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_C1_H
#define UI_C1_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_C1
{
public:
    QLabel *label;
    QFrame *frame;
    QLabel *lbRenSS1T;
    QLabel *lbNsdprxT;
    QLabel *lbN25prxT;
    QLabel *lbNcaprxT;
    QLabel *lbT48prxT;
    QLabel *lbPs3prxT;
    QLabel *lbT3hprxT;
    QLabel *lbN25hprxT;
    QLabel *lbNsdprx;
    QLabel *lbN25prx;
    QLabel *lbT48prx;
    QLabel *lbNcaprx;
    QLabel *lbPs3prx;
    QLabel *lbT3hprx;
    QLabel *lbN25hprx;
    QLabel *lbNsdprxU;
    QLabel *lbN25prxU;
    QLabel *lbNcaprxU;
    QLabel *lbT48prxU;
    QLabel *lbPs3prxU;
    QLabel *lbN25hprxU;
    QLabel *lbT3hprxU;
    QLabel *lbSelecDesBajT;
    QLabel *lbSelecDesBaj2T;
    QLabel *label_15;
    QFrame *frame_2;
    QLabel *lbWflprxT;
    QLabel *lbNcdprxU;
    QLabel *lbWflprxU;
    QLabel *lbNcdprxT;
    QLabel *lbREnSS1T;
    QLabel *lbNcdprx;
    QLabel *lbWflprx;
    QFrame *frame_3;
    QLabel *lbConCerT;
    QLabel *lbWehprxU;
    QLabel *lbConCerU;
    QLabel *lbWehprxT;
    QLabel *label_41;
    QLabel *lbWehprx;
    QLabel *lbConCer;
    QLabel *lbRenT;
    QLabel *lbRenU;
    QLabel *lbRen;
    QFrame *frame_4;
    QFrame *frame_5;
    QLabel *label_47;
    QFrame *frame_6;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *lbNSDREFT;
    QLabel *lbNSDSELU;
    QLabel *lbNSDSELT;
    QLabel *lbNSDPRX;
    QLabel *lbNSDPRXT;
    QLabel *lbNSDSEL;
    QLabel *lbNSDREFU;
    QLabel *lbNSDREF;
    QLabel *lbNSDPRXU;
    QLabel *lbN25PRXU;
    QLabel *lbN25PRX;
    QLabel *lbN25REFU;
    QLabel *label_63;
    QLabel *lbN25SEL;
    QLabel *lbN25PRXT;
    QLabel *lbN25SELU;
    QLabel *lbN25REF;
    QLabel *lbN25SELT;
    QLabel *lbMCDPRXU;
    QLabel *lbMCDPRXT_2;
    QLabel *lbN25DOC;
    QLabel *lbN25DOCT;
    QLabel *lbN25DEC;
    QLabel *lbN25DECU;
    QLabel *lbN25DECT;
    QLabel *lbMCDPRXT;
    QLabel *lbN25DOCU;
    QFrame *frame_7;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *lbN25ACCT;
    QLabel *lbN25DOTU;
    QLabel *lbN25DOTT;
    QLabel *lbNCAPRX;
    QLabel *lbNCAPRXT;
    QLabel *lbN25DOT;
    QLabel *lbN25ACCU;
    QLabel *lbN25ACC;
    QLabel *lbNCAPRXU;
    QLabel *lbWFLPRX;
    QLabel *lbWFLPRXU;
    QLabel *lbWFLPRXT;
    QLabel *lbT48PRXU;
    QLabel *lbT48PRX;
    QLabel *lbT48SEL;
    QLabel *lbT48SELT;
    QLabel *lbT48REF;
    QLabel *lbT48REFU;
    QLabel *lbT48REFT;
    QLabel *lbT48PRXT;
    QLabel *lbT48SELU;
    QFrame *frame_8;
    QLabel *label_156;
    QLabel *label_157;
    QLabel *label_158;
    QLabel *lbPS3REFT;
    QLabel *lbPS3SELU;
    QLabel *lbPS3SELT;
    QLabel *lbPS3PRX;
    QLabel *lbPS3PRXT;
    QLabel *lbPS3SEL;
    QLabel *lbPS3REFU;
    QLabel *lbPS3REF;
    QLabel *lbPS3PRXU;
    QLabel *lbT3HPRXU;
    QLabel *lbT3HPRX;
    QLabel *lbT3HREFU;
    QLabel *lbT3HREFT;
    QLabel *lbT3SEL;
    QLabel *lbT3HPRXT;
    QLabel *lbT3SELU;
    QLabel *lbT3HREF;
    QLabel *lbT3SELT;
    QLabel *lbN25HPRXU;
    QLabel *lbN25HPRX;
    QLabel *lbN25SEL_2;
    QLabel *lbN25SELT_2;
    QLabel *lbN25HREF;
    QLabel *lbN25HREFU;
    QLabel *lbN25HREFT;
    QLabel *lbN25HPRXT;
    QLabel *lbN25SELU_2;
    QFrame *frame_9;
    QLabel *label_186;
    QLabel *lbWFHPRXT;
    QLabel *lbWFMAXU;
    QLabel *lbWFMAXT;
    QLabel *lbWFMAX;
    QLabel *lbWFHPRXU;
    QLabel *lbWFHPRX;
    QLabel *lbUnit3;
    QPushButton *btnIMPPant;

    void setupUi(QWidget *C1)
    {
        if (C1->objectName().isEmpty())
            C1->setObjectName(QString::fromUtf8("C1"));
        C1->resize(1024, 662);
        C1->setMinimumSize(QSize(1024, 662));
        C1->setMaximumSize(QSize(1024, 662));
        label = new QLabel(C1);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(0, 0, 1024, 662));
        label->setMinimumSize(QSize(1024, 662));
        label->setMaximumSize(QSize(1024, 662));
        label->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/C1.png")));
        label->setScaledContents(true);
        frame = new QFrame(C1);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(61, 80, 190, 154));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Raised);
        lbRenSS1T = new QLabel(frame);
        lbRenSS1T->setObjectName(QString::fromUtf8("lbRenSS1T"));
        lbRenSS1T->setGeometry(QRect(10, 7, 171, 16));
        QFont font;
        font.setPointSize(10);
        lbRenSS1T->setFont(font);
        lbRenSS1T->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbRenSS1T->setAlignment(Qt::AlignCenter);
        lbNsdprxT = new QLabel(frame);
        lbNsdprxT->setObjectName(QString::fromUtf8("lbNsdprxT"));
        lbNsdprxT->setGeometry(QRect(30, 22, 71, 16));
        lbNsdprxT->setFont(font);
        lbNsdprxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNsdprxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25prxT = new QLabel(frame);
        lbN25prxT->setObjectName(QString::fromUtf8("lbN25prxT"));
        lbN25prxT->setGeometry(QRect(30, 40, 71, 16));
        lbN25prxT->setFont(font);
        lbN25prxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25prxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNcaprxT = new QLabel(frame);
        lbNcaprxT->setObjectName(QString::fromUtf8("lbNcaprxT"));
        lbNcaprxT->setGeometry(QRect(30, 57, 71, 16));
        lbNcaprxT->setFont(font);
        lbNcaprxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNcaprxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48prxT = new QLabel(frame);
        lbT48prxT->setObjectName(QString::fromUtf8("lbT48prxT"));
        lbT48prxT->setGeometry(QRect(30, 72, 71, 16));
        lbT48prxT->setFont(font);
        lbT48prxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48prxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPs3prxT = new QLabel(frame);
        lbPs3prxT->setObjectName(QString::fromUtf8("lbPs3prxT"));
        lbPs3prxT->setGeometry(QRect(30, 88, 71, 16));
        lbPs3prxT->setFont(font);
        lbPs3prxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPs3prxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT3hprxT = new QLabel(frame);
        lbT3hprxT->setObjectName(QString::fromUtf8("lbT3hprxT"));
        lbT3hprxT->setGeometry(QRect(30, 105, 71, 16));
        lbT3hprxT->setFont(font);
        lbT3hprxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3hprxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25hprxT = new QLabel(frame);
        lbN25hprxT->setObjectName(QString::fromUtf8("lbN25hprxT"));
        lbN25hprxT->setGeometry(QRect(28, 122, 71, 16));
        lbN25hprxT->setFont(font);
        lbN25hprxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25hprxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNsdprx = new QLabel(frame);
        lbNsdprx->setObjectName(QString::fromUtf8("lbNsdprx"));
        lbNsdprx->setGeometry(QRect(112, 22, 40, 16));
        lbNsdprx->setFont(font);
        lbNsdprx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNsdprx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbN25prx = new QLabel(frame);
        lbN25prx->setObjectName(QString::fromUtf8("lbN25prx"));
        lbN25prx->setGeometry(QRect(112, 40, 40, 16));
        lbN25prx->setFont(font);
        lbN25prx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25prx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT48prx = new QLabel(frame);
        lbT48prx->setObjectName(QString::fromUtf8("lbT48prx"));
        lbT48prx->setGeometry(QRect(112, 72, 40, 16));
        lbT48prx->setFont(font);
        lbT48prx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48prx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNcaprx = new QLabel(frame);
        lbNcaprx->setObjectName(QString::fromUtf8("lbNcaprx"));
        lbNcaprx->setGeometry(QRect(112, 56, 40, 16));
        lbNcaprx->setFont(font);
        lbNcaprx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNcaprx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbPs3prx = new QLabel(frame);
        lbPs3prx->setObjectName(QString::fromUtf8("lbPs3prx"));
        lbPs3prx->setGeometry(QRect(112, 88, 40, 16));
        lbPs3prx->setFont(font);
        lbPs3prx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPs3prx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbT3hprx = new QLabel(frame);
        lbT3hprx->setObjectName(QString::fromUtf8("lbT3hprx"));
        lbT3hprx->setGeometry(QRect(112, 106, 40, 16));
        lbT3hprx->setFont(font);
        lbT3hprx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3hprx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbN25hprx = new QLabel(frame);
        lbN25hprx->setObjectName(QString::fromUtf8("lbN25hprx"));
        lbN25hprx->setGeometry(QRect(112, 122, 40, 16));
        lbN25hprx->setFont(font);
        lbN25hprx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25hprx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNsdprxU = new QLabel(frame);
        lbNsdprxU->setObjectName(QString::fromUtf8("lbNsdprxU"));
        lbNsdprxU->setGeometry(QRect(153, 22, 32, 16));
        lbNsdprxU->setFont(font);
        lbNsdprxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNsdprxU->setAlignment(Qt::AlignCenter);
        lbN25prxU = new QLabel(frame);
        lbN25prxU->setObjectName(QString::fromUtf8("lbN25prxU"));
        lbN25prxU->setGeometry(QRect(153, 40, 32, 16));
        lbN25prxU->setFont(font);
        lbN25prxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25prxU->setAlignment(Qt::AlignCenter);
        lbNcaprxU = new QLabel(frame);
        lbNcaprxU->setObjectName(QString::fromUtf8("lbNcaprxU"));
        lbNcaprxU->setGeometry(QRect(153, 57, 32, 16));
        lbNcaprxU->setFont(font);
        lbNcaprxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNcaprxU->setAlignment(Qt::AlignCenter);
        lbT48prxU = new QLabel(frame);
        lbT48prxU->setObjectName(QString::fromUtf8("lbT48prxU"));
        lbT48prxU->setGeometry(QRect(153, 72, 32, 16));
        lbT48prxU->setFont(font);
        lbT48prxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48prxU->setAlignment(Qt::AlignCenter);
        lbPs3prxU = new QLabel(frame);
        lbPs3prxU->setObjectName(QString::fromUtf8("lbPs3prxU"));
        lbPs3prxU->setGeometry(QRect(153, 89, 32, 16));
        lbPs3prxU->setFont(font);
        lbPs3prxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPs3prxU->setAlignment(Qt::AlignCenter);
        lbN25hprxU = new QLabel(frame);
        lbN25hprxU->setObjectName(QString::fromUtf8("lbN25hprxU"));
        lbN25hprxU->setGeometry(QRect(153, 123, 32, 16));
        lbN25hprxU->setFont(font);
        lbN25hprxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25hprxU->setAlignment(Qt::AlignCenter);
        lbT3hprxU = new QLabel(frame);
        lbT3hprxU->setObjectName(QString::fromUtf8("lbT3hprxU"));
        lbT3hprxU->setGeometry(QRect(153, 106, 32, 16));
        lbT3hprxU->setFont(font);
        lbT3hprxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3hprxU->setAlignment(Qt::AlignCenter);
        lbSelecDesBajT = new QLabel(C1);
        lbSelecDesBajT->setObjectName(QString::fromUtf8("lbSelecDesBajT"));
        lbSelecDesBajT->setGeometry(QRect(65, 60, 191, 21));
        QFont font1;
        font1.setPointSize(9);
        font1.setBold(true);
        font1.setWeight(75);
        lbSelecDesBajT->setFont(font1);
        lbSelecDesBajT->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        lbSelecDesBaj2T = new QLabel(C1);
        lbSelecDesBaj2T->setObjectName(QString::fromUtf8("lbSelecDesBaj2T"));
        lbSelecDesBaj2T->setGeometry(QRect(370, 60, 191, 21));
        lbSelecDesBaj2T->setFont(font1);
        lbSelecDesBaj2T->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        label_15 = new QLabel(C1);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(660, 60, 191, 21));
        label_15->setFont(font1);
        label_15->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        frame_2 = new QFrame(C1);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(360, 80, 191, 74));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Raised);
        lbWflprxT = new QLabel(frame_2);
        lbWflprxT->setObjectName(QString::fromUtf8("lbWflprxT"));
        lbWflprxT->setGeometry(QRect(20, 40, 71, 16));
        lbWflprxT->setFont(font);
        lbWflprxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWflprxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNcdprxU = new QLabel(frame_2);
        lbNcdprxU->setObjectName(QString::fromUtf8("lbNcdprxU"));
        lbNcdprxU->setGeometry(QRect(143, 22, 32, 16));
        lbNcdprxU->setFont(font);
        lbNcdprxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNcdprxU->setAlignment(Qt::AlignCenter);
        lbWflprxU = new QLabel(frame_2);
        lbWflprxU->setObjectName(QString::fromUtf8("lbWflprxU"));
        lbWflprxU->setGeometry(QRect(143, 40, 32, 16));
        lbWflprxU->setFont(font);
        lbWflprxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWflprxU->setAlignment(Qt::AlignCenter);
        lbNcdprxT = new QLabel(frame_2);
        lbNcdprxT->setObjectName(QString::fromUtf8("lbNcdprxT"));
        lbNcdprxT->setGeometry(QRect(20, 22, 71, 16));
        lbNcdprxT->setFont(font);
        lbNcdprxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNcdprxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbREnSS1T = new QLabel(frame_2);
        lbREnSS1T->setObjectName(QString::fromUtf8("lbREnSS1T"));
        lbREnSS1T->setGeometry(QRect(4, 7, 181, 16));
        lbREnSS1T->setFont(font);
        lbREnSS1T->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbREnSS1T->setAlignment(Qt::AlignCenter);
        lbNcdprx = new QLabel(frame_2);
        lbNcdprx->setObjectName(QString::fromUtf8("lbNcdprx"));
        lbNcdprx->setGeometry(QRect(102, 22, 40, 16));
        lbNcdprx->setFont(font);
        lbNcdprx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNcdprx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbWflprx = new QLabel(frame_2);
        lbWflprx->setObjectName(QString::fromUtf8("lbWflprx"));
        lbWflprx->setGeometry(QRect(102, 40, 40, 16));
        lbWflprx->setFont(font);
        lbWflprx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWflprx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_3 = new QFrame(C1);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(650, 80, 199, 68));
        frame_3->setFrameShape(QFrame::Box);
        frame_3->setFrameShadow(QFrame::Raised);
        lbConCerT = new QLabel(frame_3);
        lbConCerT->setObjectName(QString::fromUtf8("lbConCerT"));
        lbConCerT->setGeometry(QRect(9, 42, 148, 16));
        lbConCerT->setFont(font);
        lbConCerT->setStyleSheet(QString::fromUtf8("\n"
"\n"
"color: rgb(255, 255, 0);"));
        lbConCerT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbWehprxU = new QLabel(frame_3);
        lbWehprxU->setObjectName(QString::fromUtf8("lbWehprxU"));
        lbWehprxU->setGeometry(QRect(174, 22, 21, 16));
        lbWehprxU->setFont(font);
        lbWehprxU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWehprxU->setAlignment(Qt::AlignCenter);
        lbConCerU = new QLabel(frame_3);
        lbConCerU->setObjectName(QString::fromUtf8("lbConCerU"));
        lbConCerU->setGeometry(QRect(174, 40, 21, 16));
        lbConCerU->setFont(font);
        lbConCerU->setStyleSheet(QString::fromUtf8("\n"
"color: rgb(255, 255, 0);"));
        lbConCerU->setAlignment(Qt::AlignCenter);
        lbWehprxT = new QLabel(frame_3);
        lbWehprxT->setObjectName(QString::fromUtf8("lbWehprxT"));
        lbWehprxT->setGeometry(QRect(20, 22, 71, 16));
        lbWehprxT->setFont(font);
        lbWehprxT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWehprxT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_41 = new QLabel(frame_3);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(4, 7, 181, 16));
        label_41->setFont(font);
        label_41->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_41->setAlignment(Qt::AlignCenter);
        lbWehprx = new QLabel(frame_3);
        lbWehprx->setObjectName(QString::fromUtf8("lbWehprx"));
        lbWehprx->setGeometry(QRect(130, 22, 40, 16));
        lbWehprx->setFont(font);
        lbWehprx->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWehprx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbConCer = new QLabel(frame_3);
        lbConCer->setObjectName(QString::fromUtf8("lbConCer"));
        lbConCer->setGeometry(QRect(154, 40, 15, 17));
        lbConCer->setFont(font);
        lbConCer->setStyleSheet(QString::fromUtf8("\n"
"color: rgb(255, 255, 0);"));
        lbConCer->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbRenT = new QLabel(C1);
        lbRenT->setObjectName(QString::fromUtf8("lbRenT"));
        lbRenT->setGeometry(QRect(860, 75, 141, 41));
        lbRenT->setFont(font);
        lbRenT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbRenT->setAlignment(Qt::AlignCenter);
        lbRenU = new QLabel(C1);
        lbRenU->setObjectName(QString::fromUtf8("lbRenU"));
        lbRenU->setGeometry(QRect(940, 114, 21, 16));
        lbRenU->setFont(font);
        lbRenU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbRenU->setAlignment(Qt::AlignCenter);
        lbRen = new QLabel(C1);
        lbRen->setObjectName(QString::fromUtf8("lbRen"));
        lbRen->setGeometry(QRect(881, 115, 41, 16));
        lbRen->setFont(font);
        lbRen->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbRen->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_4 = new QFrame(C1);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(0, 380, 1021, 261));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        frame_5 = new QFrame(frame_4);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(2, 3, 1018, 28));
        frame_5->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_5->setFrameShape(QFrame::Box);
        frame_5->setFrameShadow(QFrame::Sunken);
        label_47 = new QLabel(frame_5);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(5, 5, 1006, 15));
        QFont font2;
        font2.setPointSize(10);
        font2.setBold(true);
        font2.setWeight(75);
        label_47->setFont(font2);
        label_47->setAlignment(Qt::AlignCenter);
        frame_6 = new QFrame(frame_4);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(0, 30, 259, 231));
        frame_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(158, 158, 158);"));
        frame_6->setFrameShape(QFrame::Panel);
        frame_6->setFrameShadow(QFrame::Plain);
        label_48 = new QLabel(frame_6);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(7, 5, 241, 16));
        label_48->setFont(font2);
        label_48->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        label_49 = new QLabel(frame_6);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(7, 78, 241, 16));
        label_49->setFont(font2);
        label_49->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        label_50 = new QLabel(frame_6);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(7, 151, 241, 16));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(true);
        font3.setWeight(75);
        label_50->setFont(font3);
        label_50->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        lbNSDREFT = new QLabel(frame_6);
        lbNSDREFT->setObjectName(QString::fromUtf8("lbNSDREFT"));
        lbNSDREFT->setGeometry(QRect(10, 33, 68, 16));
        lbNSDREFT->setFont(font);
        lbNSDREFT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDREFT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNSDSELU = new QLabel(frame_6);
        lbNSDSELU->setObjectName(QString::fromUtf8("lbNSDSELU"));
        lbNSDSELU->setGeometry(QRect(133, 20, 41, 16));
        lbNSDSELU->setFont(font);
        lbNSDSELU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDSELU->setAlignment(Qt::AlignCenter);
        lbNSDSELT = new QLabel(frame_6);
        lbNSDSELT->setObjectName(QString::fromUtf8("lbNSDSELT"));
        lbNSDSELT->setGeometry(QRect(10, 20, 68, 16));
        lbNSDSELT->setFont(font);
        lbNSDSELT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDSELT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNSDPRX = new QLabel(frame_6);
        lbNSDPRX->setObjectName(QString::fromUtf8("lbNSDPRX"));
        lbNSDPRX->setGeometry(QRect(85, 48, 40, 16));
        lbNSDPRX->setFont(font);
        lbNSDPRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDPRX->setAlignment(Qt::AlignCenter);
        lbNSDPRXT = new QLabel(frame_6);
        lbNSDPRXT->setObjectName(QString::fromUtf8("lbNSDPRXT"));
        lbNSDPRXT->setGeometry(QRect(8, 48, 68, 16));
        lbNSDPRXT->setFont(font);
        lbNSDPRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDPRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNSDSEL = new QLabel(frame_6);
        lbNSDSEL->setObjectName(QString::fromUtf8("lbNSDSEL"));
        lbNSDSEL->setGeometry(QRect(85, 20, 40, 16));
        lbNSDSEL->setFont(font);
        lbNSDSEL->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDSEL->setAlignment(Qt::AlignCenter);
        lbNSDREFU = new QLabel(frame_6);
        lbNSDREFU->setObjectName(QString::fromUtf8("lbNSDREFU"));
        lbNSDREFU->setGeometry(QRect(133, 33, 41, 16));
        lbNSDREFU->setFont(font);
        lbNSDREFU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDREFU->setAlignment(Qt::AlignCenter);
        lbNSDREF = new QLabel(frame_6);
        lbNSDREF->setObjectName(QString::fromUtf8("lbNSDREF"));
        lbNSDREF->setGeometry(QRect(85, 33, 40, 16));
        lbNSDREF->setFont(font);
        lbNSDREF->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDREF->setAlignment(Qt::AlignCenter);
        lbNSDPRXU = new QLabel(frame_6);
        lbNSDPRXU->setObjectName(QString::fromUtf8("lbNSDPRXU"));
        lbNSDPRXU->setGeometry(QRect(133, 48, 41, 16));
        lbNSDPRXU->setFont(font);
        lbNSDPRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNSDPRXU->setAlignment(Qt::AlignCenter);
        lbN25PRXU = new QLabel(frame_6);
        lbN25PRXU->setObjectName(QString::fromUtf8("lbN25PRXU"));
        lbN25PRXU->setGeometry(QRect(133, 120, 41, 16));
        lbN25PRXU->setFont(font);
        lbN25PRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25PRXU->setAlignment(Qt::AlignCenter);
        lbN25PRX = new QLabel(frame_6);
        lbN25PRX->setObjectName(QString::fromUtf8("lbN25PRX"));
        lbN25PRX->setGeometry(QRect(85, 120, 40, 16));
        lbN25PRX->setFont(font);
        lbN25PRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25PRX->setAlignment(Qt::AlignCenter);
        lbN25REFU = new QLabel(frame_6);
        lbN25REFU->setObjectName(QString::fromUtf8("lbN25REFU"));
        lbN25REFU->setGeometry(QRect(133, 105, 41, 16));
        lbN25REFU->setFont(font);
        lbN25REFU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25REFU->setAlignment(Qt::AlignCenter);
        label_63 = new QLabel(frame_6);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(10, 105, 68, 16));
        label_63->setFont(font);
        label_63->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_63->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25SEL = new QLabel(frame_6);
        lbN25SEL->setObjectName(QString::fromUtf8("lbN25SEL"));
        lbN25SEL->setGeometry(QRect(85, 92, 40, 16));
        lbN25SEL->setFont(font);
        lbN25SEL->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25SEL->setAlignment(Qt::AlignCenter);
        lbN25PRXT = new QLabel(frame_6);
        lbN25PRXT->setObjectName(QString::fromUtf8("lbN25PRXT"));
        lbN25PRXT->setGeometry(QRect(8, 120, 68, 16));
        lbN25PRXT->setFont(font);
        lbN25PRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25PRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25SELU = new QLabel(frame_6);
        lbN25SELU->setObjectName(QString::fromUtf8("lbN25SELU"));
        lbN25SELU->setGeometry(QRect(133, 92, 41, 16));
        lbN25SELU->setFont(font);
        lbN25SELU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25SELU->setAlignment(Qt::AlignCenter);
        lbN25REF = new QLabel(frame_6);
        lbN25REF->setObjectName(QString::fromUtf8("lbN25REF"));
        lbN25REF->setGeometry(QRect(85, 105, 40, 16));
        lbN25REF->setFont(font);
        lbN25REF->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25REF->setAlignment(Qt::AlignCenter);
        lbN25SELT = new QLabel(frame_6);
        lbN25SELT->setObjectName(QString::fromUtf8("lbN25SELT"));
        lbN25SELT->setGeometry(QRect(10, 92, 68, 16));
        lbN25SELT->setFont(font);
        lbN25SELT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25SELT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbMCDPRXU = new QLabel(frame_6);
        lbMCDPRXU->setObjectName(QString::fromUtf8("lbMCDPRXU"));
        lbMCDPRXU->setGeometry(QRect(130, 190, 41, 16));
        lbMCDPRXU->setFont(font);
        lbMCDPRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbMCDPRXU->setAlignment(Qt::AlignCenter);
        lbMCDPRXT_2 = new QLabel(frame_6);
        lbMCDPRXT_2->setObjectName(QString::fromUtf8("lbMCDPRXT_2"));
        lbMCDPRXT_2->setGeometry(QRect(82, 190, 40, 16));
        lbMCDPRXT_2->setFont(font);
        lbMCDPRXT_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbMCDPRXT_2->setAlignment(Qt::AlignCenter);
        lbN25DOC = new QLabel(frame_6);
        lbN25DOC->setObjectName(QString::fromUtf8("lbN25DOC"));
        lbN25DOC->setGeometry(QRect(82, 162, 40, 16));
        lbN25DOC->setFont(font);
        lbN25DOC->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DOC->setAlignment(Qt::AlignCenter);
        lbN25DOCT = new QLabel(frame_6);
        lbN25DOCT->setObjectName(QString::fromUtf8("lbN25DOCT"));
        lbN25DOCT->setGeometry(QRect(7, 162, 68, 16));
        lbN25DOCT->setFont(font);
        lbN25DOCT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DOCT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25DEC = new QLabel(frame_6);
        lbN25DEC->setObjectName(QString::fromUtf8("lbN25DEC"));
        lbN25DEC->setGeometry(QRect(82, 175, 40, 16));
        lbN25DEC->setFont(font);
        lbN25DEC->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DEC->setAlignment(Qt::AlignCenter);
        lbN25DECU = new QLabel(frame_6);
        lbN25DECU->setObjectName(QString::fromUtf8("lbN25DECU"));
        lbN25DECU->setGeometry(QRect(130, 175, 41, 16));
        lbN25DECU->setFont(font);
        lbN25DECU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DECU->setAlignment(Qt::AlignCenter);
        lbN25DECT = new QLabel(frame_6);
        lbN25DECT->setObjectName(QString::fromUtf8("lbN25DECT"));
        lbN25DECT->setGeometry(QRect(7, 175, 68, 16));
        lbN25DECT->setFont(font);
        lbN25DECT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DECT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbMCDPRXT = new QLabel(frame_6);
        lbMCDPRXT->setObjectName(QString::fromUtf8("lbMCDPRXT"));
        lbMCDPRXT->setGeometry(QRect(5, 190, 68, 16));
        lbMCDPRXT->setFont(font);
        lbMCDPRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbMCDPRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25DOCU = new QLabel(frame_6);
        lbN25DOCU->setObjectName(QString::fromUtf8("lbN25DOCU"));
        lbN25DOCU->setGeometry(QRect(130, 162, 41, 16));
        lbN25DOCU->setFont(font);
        lbN25DOCU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DOCU->setAlignment(Qt::AlignCenter);
        frame_7 = new QFrame(frame_4);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(257, 30, 257, 231));
        frame_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(158, 158, 158);"));
        frame_7->setFrameShape(QFrame::Panel);
        frame_7->setFrameShadow(QFrame::Plain);
        label_78 = new QLabel(frame_7);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(7, 5, 241, 16));
        label_78->setFont(font2);
        label_78->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        label_79 = new QLabel(frame_7);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(7, 78, 241, 16));
        label_79->setFont(font2);
        label_79->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        label_80 = new QLabel(frame_7);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(7, 151, 241, 16));
        label_80->setFont(font3);
        label_80->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        lbN25ACCT = new QLabel(frame_7);
        lbN25ACCT->setObjectName(QString::fromUtf8("lbN25ACCT"));
        lbN25ACCT->setGeometry(QRect(10, 33, 68, 16));
        lbN25ACCT->setFont(font);
        lbN25ACCT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25ACCT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25DOTU = new QLabel(frame_7);
        lbN25DOTU->setObjectName(QString::fromUtf8("lbN25DOTU"));
        lbN25DOTU->setGeometry(QRect(133, 20, 41, 16));
        lbN25DOTU->setFont(font);
        lbN25DOTU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DOTU->setAlignment(Qt::AlignCenter);
        lbN25DOTT = new QLabel(frame_7);
        lbN25DOTT->setObjectName(QString::fromUtf8("lbN25DOTT"));
        lbN25DOTT->setGeometry(QRect(10, 20, 68, 16));
        lbN25DOTT->setFont(font);
        lbN25DOTT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DOTT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbNCAPRX = new QLabel(frame_7);
        lbNCAPRX->setObjectName(QString::fromUtf8("lbNCAPRX"));
        lbNCAPRX->setGeometry(QRect(85, 48, 40, 16));
        lbNCAPRX->setFont(font);
        lbNCAPRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNCAPRX->setAlignment(Qt::AlignCenter);
        lbNCAPRXT = new QLabel(frame_7);
        lbNCAPRXT->setObjectName(QString::fromUtf8("lbNCAPRXT"));
        lbNCAPRXT->setGeometry(QRect(8, 48, 68, 16));
        lbNCAPRXT->setFont(font);
        lbNCAPRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNCAPRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25DOT = new QLabel(frame_7);
        lbN25DOT->setObjectName(QString::fromUtf8("lbN25DOT"));
        lbN25DOT->setGeometry(QRect(85, 20, 40, 16));
        lbN25DOT->setFont(font);
        lbN25DOT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25DOT->setAlignment(Qt::AlignCenter);
        lbN25ACCU = new QLabel(frame_7);
        lbN25ACCU->setObjectName(QString::fromUtf8("lbN25ACCU"));
        lbN25ACCU->setGeometry(QRect(133, 33, 41, 16));
        lbN25ACCU->setFont(font);
        lbN25ACCU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25ACCU->setAlignment(Qt::AlignCenter);
        lbN25ACC = new QLabel(frame_7);
        lbN25ACC->setObjectName(QString::fromUtf8("lbN25ACC"));
        lbN25ACC->setGeometry(QRect(85, 33, 40, 16));
        lbN25ACC->setFont(font);
        lbN25ACC->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25ACC->setAlignment(Qt::AlignCenter);
        lbNCAPRXU = new QLabel(frame_7);
        lbNCAPRXU->setObjectName(QString::fromUtf8("lbNCAPRXU"));
        lbNCAPRXU->setGeometry(QRect(133, 48, 41, 16));
        lbNCAPRXU->setFont(font);
        lbNCAPRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbNCAPRXU->setAlignment(Qt::AlignCenter);
        lbWFLPRX = new QLabel(frame_7);
        lbWFLPRX->setObjectName(QString::fromUtf8("lbWFLPRX"));
        lbWFLPRX->setGeometry(QRect(85, 92, 40, 16));
        lbWFLPRX->setFont(font);
        lbWFLPRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFLPRX->setAlignment(Qt::AlignCenter);
        lbWFLPRXU = new QLabel(frame_7);
        lbWFLPRXU->setObjectName(QString::fromUtf8("lbWFLPRXU"));
        lbWFLPRXU->setGeometry(QRect(133, 92, 41, 16));
        lbWFLPRXU->setFont(font);
        lbWFLPRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFLPRXU->setAlignment(Qt::AlignCenter);
        lbWFLPRXT = new QLabel(frame_7);
        lbWFLPRXT->setObjectName(QString::fromUtf8("lbWFLPRXT"));
        lbWFLPRXT->setGeometry(QRect(10, 92, 68, 16));
        lbWFLPRXT->setFont(font);
        lbWFLPRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFLPRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48PRXU = new QLabel(frame_7);
        lbT48PRXU->setObjectName(QString::fromUtf8("lbT48PRXU"));
        lbT48PRXU->setGeometry(QRect(130, 190, 41, 16));
        lbT48PRXU->setFont(font);
        lbT48PRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48PRXU->setAlignment(Qt::AlignCenter);
        lbT48PRX = new QLabel(frame_7);
        lbT48PRX->setObjectName(QString::fromUtf8("lbT48PRX"));
        lbT48PRX->setGeometry(QRect(82, 190, 40, 16));
        lbT48PRX->setFont(font);
        lbT48PRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48PRX->setAlignment(Qt::AlignCenter);
        lbT48SEL = new QLabel(frame_7);
        lbT48SEL->setObjectName(QString::fromUtf8("lbT48SEL"));
        lbT48SEL->setGeometry(QRect(82, 162, 40, 16));
        lbT48SEL->setFont(font);
        lbT48SEL->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48SEL->setAlignment(Qt::AlignCenter);
        lbT48SELT = new QLabel(frame_7);
        lbT48SELT->setObjectName(QString::fromUtf8("lbT48SELT"));
        lbT48SELT->setGeometry(QRect(7, 162, 68, 16));
        lbT48SELT->setFont(font);
        lbT48SELT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48SELT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48REF = new QLabel(frame_7);
        lbT48REF->setObjectName(QString::fromUtf8("lbT48REF"));
        lbT48REF->setGeometry(QRect(82, 175, 40, 16));
        lbT48REF->setFont(font);
        lbT48REF->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48REF->setAlignment(Qt::AlignCenter);
        lbT48REFU = new QLabel(frame_7);
        lbT48REFU->setObjectName(QString::fromUtf8("lbT48REFU"));
        lbT48REFU->setGeometry(QRect(130, 175, 41, 16));
        lbT48REFU->setFont(font);
        lbT48REFU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48REFU->setAlignment(Qt::AlignCenter);
        lbT48REFT = new QLabel(frame_7);
        lbT48REFT->setObjectName(QString::fromUtf8("lbT48REFT"));
        lbT48REFT->setGeometry(QRect(7, 175, 68, 16));
        lbT48REFT->setFont(font);
        lbT48REFT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48REFT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48PRXT = new QLabel(frame_7);
        lbT48PRXT->setObjectName(QString::fromUtf8("lbT48PRXT"));
        lbT48PRXT->setGeometry(QRect(5, 190, 68, 16));
        lbT48PRXT->setFont(font);
        lbT48PRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48PRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT48SELU = new QLabel(frame_7);
        lbT48SELU->setObjectName(QString::fromUtf8("lbT48SELU"));
        lbT48SELU->setGeometry(QRect(130, 162, 41, 16));
        lbT48SELU->setFont(font);
        lbT48SELU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT48SELU->setAlignment(Qt::AlignCenter);
        frame_8 = new QFrame(frame_4);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(512, 30, 257, 231));
        frame_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(158, 158, 158);"));
        frame_8->setFrameShape(QFrame::Panel);
        frame_8->setFrameShadow(QFrame::Plain);
        label_156 = new QLabel(frame_8);
        label_156->setObjectName(QString::fromUtf8("label_156"));
        label_156->setGeometry(QRect(7, 5, 241, 16));
        label_156->setFont(font2);
        label_156->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        label_157 = new QLabel(frame_8);
        label_157->setObjectName(QString::fromUtf8("label_157"));
        label_157->setGeometry(QRect(7, 78, 241, 16));
        label_157->setFont(font2);
        label_157->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        label_158 = new QLabel(frame_8);
        label_158->setObjectName(QString::fromUtf8("label_158"));
        label_158->setGeometry(QRect(7, 151, 241, 16));
        label_158->setFont(font3);
        label_158->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        lbPS3REFT = new QLabel(frame_8);
        lbPS3REFT->setObjectName(QString::fromUtf8("lbPS3REFT"));
        lbPS3REFT->setGeometry(QRect(10, 33, 68, 16));
        lbPS3REFT->setFont(font);
        lbPS3REFT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3REFT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPS3SELU = new QLabel(frame_8);
        lbPS3SELU->setObjectName(QString::fromUtf8("lbPS3SELU"));
        lbPS3SELU->setGeometry(QRect(133, 20, 41, 16));
        lbPS3SELU->setFont(font);
        lbPS3SELU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3SELU->setAlignment(Qt::AlignCenter);
        lbPS3SELT = new QLabel(frame_8);
        lbPS3SELT->setObjectName(QString::fromUtf8("lbPS3SELT"));
        lbPS3SELT->setGeometry(QRect(10, 20, 68, 16));
        lbPS3SELT->setFont(font);
        lbPS3SELT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3SELT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPS3PRX = new QLabel(frame_8);
        lbPS3PRX->setObjectName(QString::fromUtf8("lbPS3PRX"));
        lbPS3PRX->setGeometry(QRect(85, 48, 40, 16));
        lbPS3PRX->setFont(font);
        lbPS3PRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3PRX->setAlignment(Qt::AlignCenter);
        lbPS3PRXT = new QLabel(frame_8);
        lbPS3PRXT->setObjectName(QString::fromUtf8("lbPS3PRXT"));
        lbPS3PRXT->setGeometry(QRect(8, 48, 68, 16));
        lbPS3PRXT->setFont(font);
        lbPS3PRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3PRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbPS3SEL = new QLabel(frame_8);
        lbPS3SEL->setObjectName(QString::fromUtf8("lbPS3SEL"));
        lbPS3SEL->setGeometry(QRect(85, 20, 40, 16));
        lbPS3SEL->setFont(font);
        lbPS3SEL->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3SEL->setAlignment(Qt::AlignCenter);
        lbPS3REFU = new QLabel(frame_8);
        lbPS3REFU->setObjectName(QString::fromUtf8("lbPS3REFU"));
        lbPS3REFU->setGeometry(QRect(133, 33, 41, 16));
        lbPS3REFU->setFont(font);
        lbPS3REFU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3REFU->setAlignment(Qt::AlignCenter);
        lbPS3REF = new QLabel(frame_8);
        lbPS3REF->setObjectName(QString::fromUtf8("lbPS3REF"));
        lbPS3REF->setGeometry(QRect(85, 33, 40, 16));
        lbPS3REF->setFont(font);
        lbPS3REF->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3REF->setAlignment(Qt::AlignCenter);
        lbPS3PRXU = new QLabel(frame_8);
        lbPS3PRXU->setObjectName(QString::fromUtf8("lbPS3PRXU"));
        lbPS3PRXU->setGeometry(QRect(133, 48, 41, 16));
        lbPS3PRXU->setFont(font);
        lbPS3PRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbPS3PRXU->setAlignment(Qt::AlignCenter);
        lbT3HPRXU = new QLabel(frame_8);
        lbT3HPRXU->setObjectName(QString::fromUtf8("lbT3HPRXU"));
        lbT3HPRXU->setGeometry(QRect(133, 120, 41, 16));
        lbT3HPRXU->setFont(font);
        lbT3HPRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3HPRXU->setAlignment(Qt::AlignCenter);
        lbT3HPRX = new QLabel(frame_8);
        lbT3HPRX->setObjectName(QString::fromUtf8("lbT3HPRX"));
        lbT3HPRX->setGeometry(QRect(85, 120, 40, 16));
        lbT3HPRX->setFont(font);
        lbT3HPRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3HPRX->setAlignment(Qt::AlignCenter);
        lbT3HREFU = new QLabel(frame_8);
        lbT3HREFU->setObjectName(QString::fromUtf8("lbT3HREFU"));
        lbT3HREFU->setGeometry(QRect(133, 105, 41, 16));
        lbT3HREFU->setFont(font);
        lbT3HREFU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3HREFU->setAlignment(Qt::AlignCenter);
        lbT3HREFT = new QLabel(frame_8);
        lbT3HREFT->setObjectName(QString::fromUtf8("lbT3HREFT"));
        lbT3HREFT->setGeometry(QRect(10, 105, 68, 16));
        lbT3HREFT->setFont(font);
        lbT3HREFT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3HREFT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT3SEL = new QLabel(frame_8);
        lbT3SEL->setObjectName(QString::fromUtf8("lbT3SEL"));
        lbT3SEL->setGeometry(QRect(85, 92, 40, 16));
        lbT3SEL->setFont(font);
        lbT3SEL->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3SEL->setAlignment(Qt::AlignCenter);
        lbT3HPRXT = new QLabel(frame_8);
        lbT3HPRXT->setObjectName(QString::fromUtf8("lbT3HPRXT"));
        lbT3HPRXT->setGeometry(QRect(8, 120, 68, 16));
        lbT3HPRXT->setFont(font);
        lbT3HPRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3HPRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbT3SELU = new QLabel(frame_8);
        lbT3SELU->setObjectName(QString::fromUtf8("lbT3SELU"));
        lbT3SELU->setGeometry(QRect(133, 92, 41, 16));
        lbT3SELU->setFont(font);
        lbT3SELU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3SELU->setAlignment(Qt::AlignCenter);
        lbT3HREF = new QLabel(frame_8);
        lbT3HREF->setObjectName(QString::fromUtf8("lbT3HREF"));
        lbT3HREF->setGeometry(QRect(85, 105, 40, 16));
        lbT3HREF->setFont(font);
        lbT3HREF->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3HREF->setAlignment(Qt::AlignCenter);
        lbT3SELT = new QLabel(frame_8);
        lbT3SELT->setObjectName(QString::fromUtf8("lbT3SELT"));
        lbT3SELT->setGeometry(QRect(10, 92, 68, 16));
        lbT3SELT->setFont(font);
        lbT3SELT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbT3SELT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25HPRXU = new QLabel(frame_8);
        lbN25HPRXU->setObjectName(QString::fromUtf8("lbN25HPRXU"));
        lbN25HPRXU->setGeometry(QRect(130, 190, 41, 16));
        lbN25HPRXU->setFont(font);
        lbN25HPRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25HPRXU->setAlignment(Qt::AlignCenter);
        lbN25HPRX = new QLabel(frame_8);
        lbN25HPRX->setObjectName(QString::fromUtf8("lbN25HPRX"));
        lbN25HPRX->setGeometry(QRect(82, 190, 40, 16));
        lbN25HPRX->setFont(font);
        lbN25HPRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25HPRX->setAlignment(Qt::AlignCenter);
        lbN25SEL_2 = new QLabel(frame_8);
        lbN25SEL_2->setObjectName(QString::fromUtf8("lbN25SEL_2"));
        lbN25SEL_2->setGeometry(QRect(82, 162, 40, 16));
        lbN25SEL_2->setFont(font);
        lbN25SEL_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25SEL_2->setAlignment(Qt::AlignCenter);
        lbN25SELT_2 = new QLabel(frame_8);
        lbN25SELT_2->setObjectName(QString::fromUtf8("lbN25SELT_2"));
        lbN25SELT_2->setGeometry(QRect(7, 162, 68, 16));
        lbN25SELT_2->setFont(font);
        lbN25SELT_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25SELT_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25HREF = new QLabel(frame_8);
        lbN25HREF->setObjectName(QString::fromUtf8("lbN25HREF"));
        lbN25HREF->setGeometry(QRect(82, 175, 40, 16));
        lbN25HREF->setFont(font);
        lbN25HREF->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25HREF->setAlignment(Qt::AlignCenter);
        lbN25HREFU = new QLabel(frame_8);
        lbN25HREFU->setObjectName(QString::fromUtf8("lbN25HREFU"));
        lbN25HREFU->setGeometry(QRect(130, 175, 41, 16));
        lbN25HREFU->setFont(font);
        lbN25HREFU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25HREFU->setAlignment(Qt::AlignCenter);
        lbN25HREFT = new QLabel(frame_8);
        lbN25HREFT->setObjectName(QString::fromUtf8("lbN25HREFT"));
        lbN25HREFT->setGeometry(QRect(7, 175, 68, 16));
        lbN25HREFT->setFont(font);
        lbN25HREFT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25HREFT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25HPRXT = new QLabel(frame_8);
        lbN25HPRXT->setObjectName(QString::fromUtf8("lbN25HPRXT"));
        lbN25HPRXT->setGeometry(QRect(5, 190, 68, 16));
        lbN25HPRXT->setFont(font);
        lbN25HPRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25HPRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbN25SELU_2 = new QLabel(frame_8);
        lbN25SELU_2->setObjectName(QString::fromUtf8("lbN25SELU_2"));
        lbN25SELU_2->setGeometry(QRect(130, 162, 41, 16));
        lbN25SELU_2->setFont(font);
        lbN25SELU_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbN25SELU_2->setAlignment(Qt::AlignCenter);
        frame_9 = new QFrame(frame_4);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(767, 30, 254, 231));
        frame_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(158, 158, 158);"));
        frame_9->setFrameShape(QFrame::Panel);
        frame_9->setFrameShadow(QFrame::Plain);
        label_186 = new QLabel(frame_9);
        label_186->setObjectName(QString::fromUtf8("label_186"));
        label_186->setGeometry(QRect(7, 5, 241, 16));
        label_186->setFont(font2);
        label_186->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 255);"));
        lbWFHPRXT = new QLabel(frame_9);
        lbWFHPRXT->setObjectName(QString::fromUtf8("lbWFHPRXT"));
        lbWFHPRXT->setGeometry(QRect(10, 33, 68, 16));
        lbWFHPRXT->setFont(font);
        lbWFHPRXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFHPRXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbWFMAXU = new QLabel(frame_9);
        lbWFMAXU->setObjectName(QString::fromUtf8("lbWFMAXU"));
        lbWFMAXU->setGeometry(QRect(133, 20, 41, 16));
        lbWFMAXU->setFont(font);
        lbWFMAXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFMAXU->setAlignment(Qt::AlignCenter);
        lbWFMAXT = new QLabel(frame_9);
        lbWFMAXT->setObjectName(QString::fromUtf8("lbWFMAXT"));
        lbWFMAXT->setGeometry(QRect(10, 20, 68, 16));
        lbWFMAXT->setFont(font);
        lbWFMAXT->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFMAXT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbWFMAX = new QLabel(frame_9);
        lbWFMAX->setObjectName(QString::fromUtf8("lbWFMAX"));
        lbWFMAX->setGeometry(QRect(85, 20, 40, 16));
        lbWFMAX->setFont(font);
        lbWFMAX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFMAX->setAlignment(Qt::AlignCenter);
        lbWFHPRXU = new QLabel(frame_9);
        lbWFHPRXU->setObjectName(QString::fromUtf8("lbWFHPRXU"));
        lbWFHPRXU->setGeometry(QRect(133, 33, 41, 16));
        lbWFHPRXU->setFont(font);
        lbWFHPRXU->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFHPRXU->setAlignment(Qt::AlignCenter);
        lbWFHPRX = new QLabel(frame_9);
        lbWFHPRX->setObjectName(QString::fromUtf8("lbWFHPRX"));
        lbWFHPRX->setGeometry(QRect(85, 33, 40, 16));
        lbWFHPRX->setFont(font);
        lbWFHPRX->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lbWFHPRX->setAlignment(Qt::AlignCenter);
        frame_6->raise();
        frame_7->raise();
        frame_8->raise();
        frame_9->raise();
        frame_5->raise();
        lbUnit3 = new QLabel(C1);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(833, 647, 190, 15));
        QFont font4;
        font4.setBold(true);
        font4.setWeight(75);
        lbUnit3->setFont(font4);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        btnIMPPant = new QPushButton(C1);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(10, 632, 134, 23));
        btnIMPPant->setFont(font3);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));

        retranslateUi(C1);

        QMetaObject::connectSlotsByName(C1);
    } // setupUi

    void retranslateUi(QWidget *C1)
    {
        C1->setWindowTitle(QApplication::translate("C1", "Form", 0, QApplication::UnicodeUTF8));
        label->setText(QString());
        lbRenSS1T->setText(QApplication::translate("C1", "RENDIMIENTO LSS1", 0, QApplication::UnicodeUTF8));
        lbNsdprxT->setText(QApplication::translate("C1", "1   NSDPRX", 0, QApplication::UnicodeUTF8));
        lbN25prxT->setText(QApplication::translate("C1", "2   NN25PRX", 0, QApplication::UnicodeUTF8));
        lbNcaprxT->setText(QApplication::translate("C1", "4   NCAPRX", 0, QApplication::UnicodeUTF8));
        lbT48prxT->setText(QApplication::translate("C1", "6   T48PRX", 0, QApplication::UnicodeUTF8));
        lbPs3prxT->setText(QApplication::translate("C1", "7  PS3PRX", 0, QApplication::UnicodeUTF8));
        lbT3hprxT->setText(QApplication::translate("C1", "8  T3HPRX", 0, QApplication::UnicodeUTF8));
        lbN25hprxT->setText(QApplication::translate("C1", "9  N25HPRX", 0, QApplication::UnicodeUTF8));
        lbNsdprx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25prx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbT48prx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbNcaprx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbPs3prx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbT3hprx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25hprx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbNsdprxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbN25prxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbNcaprxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbT48prxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbPs3prxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbN25hprxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbT3hprxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbSelecDesBajT->setText(QApplication::translate("C1", "SELECCI\303\223N DE SE\303\221AL BAJA 1", 0, QApplication::UnicodeUTF8));
        lbSelecDesBaj2T->setText(QApplication::translate("C1", "SELECCI\303\223N DE SE\303\221AL ALTA 1", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("C1", "SELECCI\303\223N DE SE\303\221AL BAJA 2", 0, QApplication::UnicodeUTF8));
        lbWflprxT->setText(QApplication::translate("C1", "5  WFLPRX", 0, QApplication::UnicodeUTF8));
        lbNcdprxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbWflprxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbNcdprxT->setText(QApplication::translate("C1", "3  NCDPRX", 0, QApplication::UnicodeUTF8));
        lbREnSS1T->setText(QApplication::translate("C1", "RENDIMIENTO LSS 1", 0, QApplication::UnicodeUTF8));
        lbNcdprx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbWflprx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbConCerT->setText(QApplication::translate("C1", "COMBUSTIBLE CERRADO", 0, QApplication::UnicodeUTF8));
        lbWehprxU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbConCerU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbWehprxT->setText(QApplication::translate("C1", "10  WEHPRX", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("C1", "RENDIMIENTO LSS 2", 0, QApplication::UnicodeUTF8));
        lbWehprx->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbConCer->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbRenT->setText(QApplication::translate("C1", "RENDIMIENTO \n"
" DEL REGULADOR", 0, QApplication::UnicodeUTF8));
        lbRenU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbRen->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("C1", "REGULADORES DE CONTROL", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("C1", "REGULADOR 1 - CONTROL NSD", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("C1", "REGULADOR 2 - CONTROL N25", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("C1", "REGULADOR 3 - CONTROL DE DESACEL  N25", 0, QApplication::UnicodeUTF8));
        lbNSDREFT->setText(QApplication::translate("C1", "NSDREF", 0, QApplication::UnicodeUTF8));
        lbNSDSELU->setText(QApplication::translate("C1", "RPM", 0, QApplication::UnicodeUTF8));
        lbNSDSELT->setText(QApplication::translate("C1", "NSDSEL", 0, QApplication::UnicodeUTF8));
        lbNSDPRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbNSDPRXT->setText(QApplication::translate("C1", "NSDPRX", 0, QApplication::UnicodeUTF8));
        lbNSDSEL->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbNSDREFU->setText(QApplication::translate("C1", "RPM", 0, QApplication::UnicodeUTF8));
        lbNSDREF->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbNSDPRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbN25PRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbN25PRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25REFU->setText(QApplication::translate("C1", "RPM", 0, QApplication::UnicodeUTF8));
        label_63->setText(QApplication::translate("C1", "N25REF", 0, QApplication::UnicodeUTF8));
        lbN25SEL->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25PRXT->setText(QApplication::translate("C1", "N25PRX", 0, QApplication::UnicodeUTF8));
        lbN25SELU->setText(QApplication::translate("C1", "RPM", 0, QApplication::UnicodeUTF8));
        lbN25REF->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25SELT->setText(QApplication::translate("C1", "N25SEL", 0, QApplication::UnicodeUTF8));
        lbMCDPRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbMCDPRXT_2->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25DOC->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25DOCT->setText(QApplication::translate("C1", "N25DOC", 0, QApplication::UnicodeUTF8));
        lbN25DEC->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25DECU->setText(QApplication::translate("C1", "RPM", 0, QApplication::UnicodeUTF8));
        lbN25DECT->setText(QApplication::translate("C1", "N25DEC", 0, QApplication::UnicodeUTF8));
        lbMCDPRXT->setText(QApplication::translate("C1", "MCDPRX", 0, QApplication::UnicodeUTF8));
        lbN25DOCU->setText(QApplication::translate("C1", "RPM", 0, QApplication::UnicodeUTF8));
        label_78->setText(QApplication::translate("C1", "REGULADOR 4 - CONTROL DE ACEL N25", 0, QApplication::UnicodeUTF8));
        label_79->setText(QApplication::translate("C1", "REGULADOR 5 - FLUJO MN DE COMB", 0, QApplication::UnicodeUTF8));
        label_80->setText(QApplication::translate("C1", "REGULADOR 6 - CONTROL T48", 0, QApplication::UnicodeUTF8));
        lbN25ACCT->setText(QApplication::translate("C1", "N25ACC", 0, QApplication::UnicodeUTF8));
        lbN25DOTU->setText(QApplication::translate("C1", "RPM/S", 0, QApplication::UnicodeUTF8));
        lbN25DOTT->setText(QApplication::translate("C1", "N25DOT", 0, QApplication::UnicodeUTF8));
        lbNCAPRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbNCAPRXT->setText(QApplication::translate("C1", "NCAPRX", 0, QApplication::UnicodeUTF8));
        lbN25DOT->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25ACCU->setText(QApplication::translate("C1", "RPM/S", 0, QApplication::UnicodeUTF8));
        lbN25ACC->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbNCAPRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbWFLPRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbWFLPRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbWFLPRXT->setText(QApplication::translate("C1", "WFLPRX", 0, QApplication::UnicodeUTF8));
        lbT48PRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbT48PRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbT48SEL->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbT48SELT->setText(QApplication::translate("C1", "T48SEL", 0, QApplication::UnicodeUTF8));
        lbT48REF->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbT48REFU->setText(QApplication::translate("C1", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT48REFT->setText(QApplication::translate("C1", "T48REF", 0, QApplication::UnicodeUTF8));
        lbT48PRXT->setText(QApplication::translate("C1", "T48PRX", 0, QApplication::UnicodeUTF8));
        lbT48SELU->setText(QApplication::translate("C1", "\302\260F", 0, QApplication::UnicodeUTF8));
        label_156->setText(QApplication::translate("C1", "REGULADOR 7 - CONTROL PS3", 0, QApplication::UnicodeUTF8));
        label_157->setText(QApplication::translate("C1", "REGULADOR 8 - CONTROL T3", 0, QApplication::UnicodeUTF8));
        label_158->setText(QApplication::translate("C1", "REGULADOR 9 - LIMITE MAX N25", 0, QApplication::UnicodeUTF8));
        lbPS3REFT->setText(QApplication::translate("C1", "PS3REF", 0, QApplication::UnicodeUTF8));
        lbPS3SELU->setText(QApplication::translate("C1", "PSI", 0, QApplication::UnicodeUTF8));
        lbPS3SELT->setText(QApplication::translate("C1", "PS3SEL", 0, QApplication::UnicodeUTF8));
        lbPS3PRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbPS3PRXT->setText(QApplication::translate("C1", "PS3PRX", 0, QApplication::UnicodeUTF8));
        lbPS3SEL->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbPS3REFU->setText(QApplication::translate("C1", "PSI", 0, QApplication::UnicodeUTF8));
        lbPS3REF->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbPS3PRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbT3HPRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbT3HPRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbT3HREFU->setText(QApplication::translate("C1", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT3HREFT->setText(QApplication::translate("C1", "T3HREF", 0, QApplication::UnicodeUTF8));
        lbT3SEL->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbT3HPRXT->setText(QApplication::translate("C1", "T3HPRX", 0, QApplication::UnicodeUTF8));
        lbT3SELU->setText(QApplication::translate("C1", "\302\260F", 0, QApplication::UnicodeUTF8));
        lbT3HREF->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbT3SELT->setText(QApplication::translate("C1", "T3SEL", 0, QApplication::UnicodeUTF8));
        lbN25HPRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbN25HPRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25SEL_2->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25SELT_2->setText(QApplication::translate("C1", "N25SEL", 0, QApplication::UnicodeUTF8));
        lbN25HREF->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbN25HREFU->setText(QApplication::translate("C1", "RPM", 0, QApplication::UnicodeUTF8));
        lbN25HREFT->setText(QApplication::translate("C1", "N25HREF", 0, QApplication::UnicodeUTF8));
        lbN25HPRXT->setText(QApplication::translate("C1", "N25HPRX", 0, QApplication::UnicodeUTF8));
        lbN25SELU_2->setText(QApplication::translate("C1", "RPM", 0, QApplication::UnicodeUTF8));
        label_186->setText(QApplication::translate("C1", "REGULADOR 7 - CONTROL PS3", 0, QApplication::UnicodeUTF8));
        lbWFHPRXT->setText(QApplication::translate("C1", "WFHPRX", 0, QApplication::UnicodeUTF8));
        lbWFMAXU->setText(QApplication::translate("C1", "LBS/HR", 0, QApplication::UnicodeUTF8));
        lbWFMAXT->setText(QApplication::translate("C1", "WFMAX", 0, QApplication::UnicodeUTF8));
        lbWFMAX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbWFHPRXU->setText(QApplication::translate("C1", "%", 0, QApplication::UnicodeUTF8));
        lbWFHPRX->setText(QApplication::translate("C1", "0", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("C1", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("C1", "IMP PANT", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class C1: public Ui_C1 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_C1_H
