/********************************************************************************
** Form generated from reading UI file 'd7.ui'
**
** Created: Sun 13. Oct 17:32:59 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_D7_H
#define UI_D7_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_D7
{
public:
    QFrame *Temperaturas_2;
    QFrame *frame_8;
    QLabel *label_12;
    QLabel *lb_Vib_Unit_DE_X;
    QLabel *lb_Vib_Lect_DE_X;
    QLabel *Descr_45;
    QLabel *lb_Vib_Unit_NDE_X;
    QLabel *Descr_47;
    QLabel *lb_Vib_Lect_NDE_X;
    QLabel *lb_Vib_Unit_DE_Y;
    QLabel *lb_Vib_Lect_DE_Y;
    QLabel *Descr_46;
    QLabel *lb_Vib_Unit_NDE_Y;
    QLabel *lb_Vib_Lect_NDE_Y;
    QLabel *Descr_48;
    QFrame *Temperaturas_3;
    QFrame *frame_9;
    QLabel *label_13;
    QLabel *lb_Pot_Unit_PAG;
    QLabel *lb_Pot_Lect_PAG;
    QLabel *Descr_49;
    QLabel *lb_Pot_Unit_EIG;
    QLabel *lb_Pot_Lect_EIG;
    QLabel *Descr_50;
    QFrame *Modo;
    QFrame *frame_10;
    QLabel *label_14;
    QLabel *lb_Modo_Unit_DI;
    QLabel *lb_Modo_Lect_DI;
    QLabel *Descr_33;
    QFrame *Temperaturas_4;
    QFrame *frame_7;
    QLabel *label_11;
    QLabel *lb_DMMF_Unit_FGen;
    QLabel *lb_DMMF_Lect_FGen;
    QLabel *Descr_26;
    QLabel *lb_DMMF_Unit_AVT;
    QLabel *lb_DMMF_Lect_AVT;
    QLabel *Descr_25;
    QLabel *lb_DMMF_Lect_CFB;
    QLabel *Descr_23;
    QLabel *lb_DMMF_Unit_CFB;
    QLabel *Descr_22;
    QLabel *lb_DMMF_Lect_CFA;
    QLabel *lb_DMMF_Unit_CFA;
    QLabel *Descr_24;
    QLabel *lb_DMMF_Unit_CFC;
    QLabel *lb_DMMF_Lect_CFC;
    QLabel *lb_DMMF_Unit_FPGen;
    QLabel *lb_DMMF_Lect_FPGen;
    QLabel *Descr_27;
    QLabel *Descr_16;
    QLabel *lb_DMMF_Lect_VBus;
    QLabel *lb_DMMF_Unit_VBus;
    QLabel *lb_DMMF_Unit_VFAB;
    QLabel *Descr_18;
    QLabel *lb_DMMF_Lect_VFAB;
    QLabel *lb_DMMF_Lect_TMVAR;
    QLabel *Descr_21;
    QLabel *lb_DMMF_Unit_TMVAR;
    QLabel *lb_DMMF_Unit_VFBC;
    QLabel *Descr_19;
    QLabel *lb_DMMF_Lect_VFBC;
    QLabel *Descr_20;
    QLabel *lb_DMMF_Unit_VFAC;
    QLabel *lb_DMMF_Lect_VFAC;
    QLabel *Descr_17;
    QLabel *lb_DMMF_Lect_FBus;
    QLabel *lb_DMMF_Unit_FBus;
    QFrame *Temperaturas_5;
    QFrame *frame_11;
    QLabel *label_15;
    QLabel *lb_LS_Unit_VBus;
    QLabel *lb_LS_Lect_VBus;
    QLabel *Descr_30;
    QLabel *lb_LS_Unit_VCE;
    QLabel *lb_LS_Lect_VCE;
    QLabel *Descr_28;
    QLabel *lb_LS_Unit_VG;
    QLabel *lb_LS_Lect_VG;
    QLabel *Descr_31;
    QLabel *lb_LS_Unit_ACE;
    QLabel *lb_LS_Lect_ACE;
    QLabel *Descr_29;
    QLabel *lb_LS_Unit_FBus;
    QLabel *lb_LS_Lect_FBus;
    QLabel *Descr_43;
    QFrame *Temperaturas_6;
    QFrame *frame_12;
    QLabel *label_16;
    QLabel *lb_EM_Unit_VCBG;
    QLabel *lb_EM_Lect_VCBG;
    QLabel *Descr_34;
    QLabel *lb_EM_Unit_BALACG;
    QLabel *lb_EM_Lect_BALACG;
    QLabel *Descr_35;
    QLabel *lb_EM_Unit_BAEG;
    QLabel *lb_EM_Lect_BAEG;
    QLabel *Descr_36;
    QLabel *lb_EM_Unit_VCAG;
    QLabel *lb_EM_Lect_VCAG;
    QLabel *Descr_32;
    QFrame *Temperaturas_7;
    QFrame *frame_13;
    QLabel *label_17;
    QLabel *lb_LG_Unit_NTALG;
    QLabel *lb_LG_Lect_NTALG;
    QLabel *Descr_42;
    QLabel *lb_LG_Unit_PSLDGA;
    QLabel *Descr_38;
    QLabel *lb_LG_Lect_PSLDGA;
    QLabel *lb_LG_Unit_PSLDGB;
    QLabel *lb_LG_Lect_PSLDGB;
    QLabel *Descr_39;
    QLabel *lb_LG_Unit_EBAAP;
    QLabel *lb_LG_Lect_EBAAP;
    QLabel *Descr_41;
    QLabel *Descr_37;
    QLabel *lb_LG_Unit_PSALG;
    QLabel *lb_LG_Lect_PSALG;
    QLabel *lb_LG_Unit_PSLDG;
    QLabel *lb_LG_Lect_PSLDG;
    QLabel *Descr_40;
    QFrame *Temperaturas;
    QFrame *frame_6;
    QLabel *label_10;
    QLabel *Descr_01;
    QLabel *lb_Temp_Lect_FaseU1;
    QLabel *lb_Temp_Unit_FaseU1;
    QLabel *lb_Temp_Unit_FaseU2;
    QLabel *Descr_2;
    QLabel *lb_Temp_Lect_FaseU2;
    QLabel *lb_Temp_Lect_TCIIB;
    QLabel *lb_Temp_Unit_TCIIB;
    QLabel *Descr_12;
    QLabel *Descr_9;
    QLabel *lb_Temp_Lect_TCGDE;
    QLabel *lb_Temp_Unit_TCGDE;
    QLabel *lb_Temp_Lect_FaseW1;
    QLabel *lb_Temp_Unit_FaseW1;
    QLabel *Descr_5;
    QLabel *lb_Temp_Unit_FaseV1;
    QLabel *Descr_3;
    QLabel *lb_Temp_Lect_FaseV1;
    QLabel *Descr_6;
    QLabel *lb_Temp_Unit_FaseW2;
    QLabel *lb_Temp_Lect_FaseW2;
    QLabel *Descr_7;
    QLabel *lb_Temp_Lect_TPEG;
    QLabel *lb_Temp_Unit_TPEG;
    QLabel *lb_Temp_Lect_FaseV2;
    QLabel *lb_Temp_Unit_FaseV2;
    QLabel *Descr_4;
    QLabel *lb_Temp_Unit_TCIOB;
    QLabel *lb_Temp_Lect_TCIOB;
    QLabel *Descr_11;
    QLabel *lb_Temp_Unit_TSALG;
    QLabel *lb_Temp_Lect_TSALG;
    QLabel *Descr_8;
    QLabel *Descr_10;
    QLabel *lb_Temp_Lect_TCGNDE;
    QLabel *lb_Temp_Unit_TCGNDE;
    QLabel *lb_Temp_Lect_TACG;
    QLabel *Descr_13;
    QLabel *lb_Temp_Unit_TACG;
    QLabel *lb_Temp_Lect_TEAEG;
    QLabel *Descr_15;
    QLabel *lb_Temp_Unit_TEAEG;
    QLabel *Descr_14;
    QLabel *lb_Temp_Unit_TSAG;
    QLabel *lb_Temp_Lect_TSAG;
    QLabel *lbUnit3;
    QPushButton *btnIMPPant;

    void setupUi(QWidget *D7)
    {
        if (D7->objectName().isEmpty())
            D7->setObjectName(QString::fromUtf8("D7"));
        D7->resize(1024, 662);
        D7->setMinimumSize(QSize(1024, 662));
        D7->setMaximumSize(QSize(1024, 662));
        D7->setStyleSheet(QString::fromUtf8("background-color: rgb(154, 154, 154);\n"
""));
        Temperaturas_2 = new QFrame(D7);
        Temperaturas_2->setObjectName(QString::fromUtf8("Temperaturas_2"));
        Temperaturas_2->setGeometry(QRect(5, 377, 340, 120));
        Temperaturas_2->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_2->setFrameShape(QFrame::Box);
        Temperaturas_2->setFrameShadow(QFrame::Sunken);
        frame_8 = new QFrame(Temperaturas_2);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(1, 1, 338, 20));
        frame_8->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_8->setFrameShape(QFrame::WinPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        frame_8->setLineWidth(2);
        label_12 = new QLabel(frame_8);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(1, 1, 334, 16));
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        label_12->setFont(font);
        label_12->setAlignment(Qt::AlignCenter);
        lb_Vib_Unit_DE_X = new QLabel(Temperaturas_2);
        lb_Vib_Unit_DE_X->setObjectName(QString::fromUtf8("lb_Vib_Unit_DE_X"));
        lb_Vib_Unit_DE_X->setGeometry(QRect(291, 30, 40, 18));
        QFont font1;
        font1.setPointSize(9);
        lb_Vib_Unit_DE_X->setFont(font1);
        lb_Vib_Unit_DE_X->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Unit_DE_X->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Vib_Lect_DE_X = new QLabel(Temperaturas_2);
        lb_Vib_Lect_DE_X->setObjectName(QString::fromUtf8("lb_Vib_Lect_DE_X"));
        lb_Vib_Lect_DE_X->setGeometry(QRect(235, 30, 50, 18));
        lb_Vib_Lect_DE_X->setMinimumSize(QSize(50, 18));
        lb_Vib_Lect_DE_X->setMaximumSize(QSize(50, 18));
        QFont font2;
        font2.setPointSize(8);
        lb_Vib_Lect_DE_X->setFont(font2);
        lb_Vib_Lect_DE_X->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Lect_DE_X->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_45 = new QLabel(Temperaturas_2);
        Descr_45->setObjectName(QString::fromUtf8("Descr_45"));
        Descr_45->setGeometry(QRect(25, 30, 200, 18));
        Descr_45->setFont(font2);
        Descr_45->setLayoutDirection(Qt::LeftToRight);
        Descr_45->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Vib_Unit_NDE_X = new QLabel(Temperaturas_2);
        lb_Vib_Unit_NDE_X->setObjectName(QString::fromUtf8("lb_Vib_Unit_NDE_X"));
        lb_Vib_Unit_NDE_X->setGeometry(QRect(291, 60, 40, 18));
        lb_Vib_Unit_NDE_X->setFont(font1);
        lb_Vib_Unit_NDE_X->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Unit_NDE_X->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_47 = new QLabel(Temperaturas_2);
        Descr_47->setObjectName(QString::fromUtf8("Descr_47"));
        Descr_47->setGeometry(QRect(25, 60, 200, 18));
        Descr_47->setFont(font2);
        Descr_47->setLayoutDirection(Qt::LeftToRight);
        Descr_47->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Vib_Lect_NDE_X = new QLabel(Temperaturas_2);
        lb_Vib_Lect_NDE_X->setObjectName(QString::fromUtf8("lb_Vib_Lect_NDE_X"));
        lb_Vib_Lect_NDE_X->setGeometry(QRect(235, 60, 50, 18));
        lb_Vib_Lect_NDE_X->setMinimumSize(QSize(50, 18));
        lb_Vib_Lect_NDE_X->setMaximumSize(QSize(50, 18));
        lb_Vib_Lect_NDE_X->setFont(font2);
        lb_Vib_Lect_NDE_X->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Lect_NDE_X->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Vib_Unit_DE_Y = new QLabel(Temperaturas_2);
        lb_Vib_Unit_DE_Y->setObjectName(QString::fromUtf8("lb_Vib_Unit_DE_Y"));
        lb_Vib_Unit_DE_Y->setGeometry(QRect(291, 45, 40, 18));
        lb_Vib_Unit_DE_Y->setFont(font1);
        lb_Vib_Unit_DE_Y->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Unit_DE_Y->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Vib_Lect_DE_Y = new QLabel(Temperaturas_2);
        lb_Vib_Lect_DE_Y->setObjectName(QString::fromUtf8("lb_Vib_Lect_DE_Y"));
        lb_Vib_Lect_DE_Y->setGeometry(QRect(235, 45, 50, 18));
        lb_Vib_Lect_DE_Y->setMinimumSize(QSize(50, 18));
        lb_Vib_Lect_DE_Y->setMaximumSize(QSize(50, 18));
        lb_Vib_Lect_DE_Y->setFont(font2);
        lb_Vib_Lect_DE_Y->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Lect_DE_Y->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_46 = new QLabel(Temperaturas_2);
        Descr_46->setObjectName(QString::fromUtf8("Descr_46"));
        Descr_46->setGeometry(QRect(25, 45, 200, 18));
        Descr_46->setFont(font2);
        Descr_46->setLayoutDirection(Qt::LeftToRight);
        Descr_46->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Vib_Unit_NDE_Y = new QLabel(Temperaturas_2);
        lb_Vib_Unit_NDE_Y->setObjectName(QString::fromUtf8("lb_Vib_Unit_NDE_Y"));
        lb_Vib_Unit_NDE_Y->setGeometry(QRect(291, 75, 40, 18));
        lb_Vib_Unit_NDE_Y->setFont(font1);
        lb_Vib_Unit_NDE_Y->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Unit_NDE_Y->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Vib_Lect_NDE_Y = new QLabel(Temperaturas_2);
        lb_Vib_Lect_NDE_Y->setObjectName(QString::fromUtf8("lb_Vib_Lect_NDE_Y"));
        lb_Vib_Lect_NDE_Y->setGeometry(QRect(235, 75, 50, 18));
        lb_Vib_Lect_NDE_Y->setMinimumSize(QSize(50, 18));
        lb_Vib_Lect_NDE_Y->setMaximumSize(QSize(50, 18));
        lb_Vib_Lect_NDE_Y->setFont(font2);
        lb_Vib_Lect_NDE_Y->setLayoutDirection(Qt::LeftToRight);
        lb_Vib_Lect_NDE_Y->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_48 = new QLabel(Temperaturas_2);
        Descr_48->setObjectName(QString::fromUtf8("Descr_48"));
        Descr_48->setGeometry(QRect(25, 75, 200, 18));
        Descr_48->setFont(font2);
        Descr_48->setLayoutDirection(Qt::LeftToRight);
        Descr_48->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Temperaturas_3 = new QFrame(D7);
        Temperaturas_3->setObjectName(QString::fromUtf8("Temperaturas_3"));
        Temperaturas_3->setGeometry(QRect(5, 496, 340, 66));
        Temperaturas_3->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_3->setFrameShape(QFrame::Box);
        Temperaturas_3->setFrameShadow(QFrame::Sunken);
        frame_9 = new QFrame(Temperaturas_3);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(1, 1, 340, 20));
        frame_9->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_9->setFrameShape(QFrame::WinPanel);
        frame_9->setFrameShadow(QFrame::Raised);
        frame_9->setLineWidth(2);
        label_13 = new QLabel(frame_9);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(2, 2, 336, 16));
        label_13->setFont(font);
        label_13->setAlignment(Qt::AlignCenter);
        lb_Pot_Unit_PAG = new QLabel(Temperaturas_3);
        lb_Pot_Unit_PAG->setObjectName(QString::fromUtf8("lb_Pot_Unit_PAG"));
        lb_Pot_Unit_PAG->setGeometry(QRect(291, 30, 40, 18));
        lb_Pot_Unit_PAG->setFont(font1);
        lb_Pot_Unit_PAG->setLayoutDirection(Qt::LeftToRight);
        lb_Pot_Unit_PAG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Pot_Lect_PAG = new QLabel(Temperaturas_3);
        lb_Pot_Lect_PAG->setObjectName(QString::fromUtf8("lb_Pot_Lect_PAG"));
        lb_Pot_Lect_PAG->setGeometry(QRect(235, 30, 50, 18));
        lb_Pot_Lect_PAG->setMinimumSize(QSize(50, 18));
        lb_Pot_Lect_PAG->setMaximumSize(QSize(50, 18));
        lb_Pot_Lect_PAG->setFont(font2);
        lb_Pot_Lect_PAG->setLayoutDirection(Qt::LeftToRight);
        lb_Pot_Lect_PAG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_49 = new QLabel(Temperaturas_3);
        Descr_49->setObjectName(QString::fromUtf8("Descr_49"));
        Descr_49->setGeometry(QRect(25, 30, 200, 18));
        Descr_49->setFont(font2);
        Descr_49->setLayoutDirection(Qt::LeftToRight);
        Descr_49->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Pot_Unit_EIG = new QLabel(Temperaturas_3);
        lb_Pot_Unit_EIG->setObjectName(QString::fromUtf8("lb_Pot_Unit_EIG"));
        lb_Pot_Unit_EIG->setGeometry(QRect(291, 45, 40, 18));
        lb_Pot_Unit_EIG->setFont(font1);
        lb_Pot_Unit_EIG->setLayoutDirection(Qt::LeftToRight);
        lb_Pot_Unit_EIG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Pot_Lect_EIG = new QLabel(Temperaturas_3);
        lb_Pot_Lect_EIG->setObjectName(QString::fromUtf8("lb_Pot_Lect_EIG"));
        lb_Pot_Lect_EIG->setGeometry(QRect(235, 45, 50, 18));
        lb_Pot_Lect_EIG->setMinimumSize(QSize(50, 18));
        lb_Pot_Lect_EIG->setMaximumSize(QSize(50, 18));
        lb_Pot_Lect_EIG->setFont(font2);
        lb_Pot_Lect_EIG->setLayoutDirection(Qt::LeftToRight);
        lb_Pot_Lect_EIG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_50 = new QLabel(Temperaturas_3);
        Descr_50->setObjectName(QString::fromUtf8("Descr_50"));
        Descr_50->setGeometry(QRect(25, 45, 200, 18));
        Descr_50->setFont(font2);
        Descr_50->setLayoutDirection(Qt::LeftToRight);
        Descr_50->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Modo = new QFrame(D7);
        Modo->setObjectName(QString::fromUtf8("Modo"));
        Modo->setGeometry(QRect(5, 561, 342, 94));
        Modo->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Modo->setFrameShape(QFrame::Box);
        Modo->setFrameShadow(QFrame::Sunken);
        frame_10 = new QFrame(Modo);
        frame_10->setObjectName(QString::fromUtf8("frame_10"));
        frame_10->setGeometry(QRect(1, 1, 340, 20));
        frame_10->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_10->setFrameShape(QFrame::WinPanel);
        frame_10->setFrameShadow(QFrame::Raised);
        frame_10->setLineWidth(2);
        label_14 = new QLabel(frame_10);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(2, 2, 336, 16));
        label_14->setFont(font);
        label_14->setAlignment(Qt::AlignCenter);
        lb_Modo_Unit_DI = new QLabel(Modo);
        lb_Modo_Unit_DI->setObjectName(QString::fromUtf8("lb_Modo_Unit_DI"));
        lb_Modo_Unit_DI->setGeometry(QRect(297, 41, 40, 18));
        lb_Modo_Unit_DI->setFont(font1);
        lb_Modo_Unit_DI->setLayoutDirection(Qt::LeftToRight);
        lb_Modo_Unit_DI->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Modo_Lect_DI = new QLabel(Modo);
        lb_Modo_Lect_DI->setObjectName(QString::fromUtf8("lb_Modo_Lect_DI"));
        lb_Modo_Lect_DI->setGeometry(QRect(241, 43, 50, 18));
        lb_Modo_Lect_DI->setMinimumSize(QSize(50, 18));
        lb_Modo_Lect_DI->setMaximumSize(QSize(50, 18));
        lb_Modo_Lect_DI->setFont(font2);
        lb_Modo_Lect_DI->setLayoutDirection(Qt::LeftToRight);
        lb_Modo_Lect_DI->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_33 = new QLabel(Modo);
        Descr_33->setObjectName(QString::fromUtf8("Descr_33"));
        Descr_33->setGeometry(QRect(10, 43, 225, 18));
        Descr_33->setMinimumSize(QSize(225, 18));
        Descr_33->setMaximumSize(QSize(225, 18));
        Descr_33->setFont(font2);
        Descr_33->setLayoutDirection(Qt::LeftToRight);
        Descr_33->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Temperaturas_4 = new QFrame(D7);
        Temperaturas_4->setObjectName(QString::fromUtf8("Temperaturas_4"));
        Temperaturas_4->setGeometry(QRect(345, 5, 341, 433));
        Temperaturas_4->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_4->setFrameShape(QFrame::Box);
        Temperaturas_4->setFrameShadow(QFrame::Sunken);
        frame_7 = new QFrame(Temperaturas_4);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(1, 1, 340, 20));
        frame_7->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_7->setFrameShape(QFrame::WinPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        frame_7->setLineWidth(2);
        label_11 = new QLabel(frame_7);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(1, 1, 336, 16));
        label_11->setFont(font);
        label_11->setAlignment(Qt::AlignCenter);
        lb_DMMF_Unit_FGen = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_FGen->setObjectName(QString::fromUtf8("lb_DMMF_Unit_FGen"));
        lb_DMMF_Unit_FGen->setGeometry(QRect(291, 310, 40, 18));
        lb_DMMF_Unit_FGen->setFont(font1);
        lb_DMMF_Unit_FGen->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_FGen->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_FGen = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_FGen->setObjectName(QString::fromUtf8("lb_DMMF_Lect_FGen"));
        lb_DMMF_Lect_FGen->setGeometry(QRect(235, 310, 50, 18));
        lb_DMMF_Lect_FGen->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_FGen->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_FGen->setFont(font2);
        lb_DMMF_Lect_FGen->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_FGen->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_26 = new QLabel(Temperaturas_4);
        Descr_26->setObjectName(QString::fromUtf8("Descr_26"));
        Descr_26->setGeometry(QRect(25, 310, 180, 18));
        Descr_26->setFont(font2);
        Descr_26->setLayoutDirection(Qt::LeftToRight);
        Descr_26->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Unit_AVT = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_AVT->setObjectName(QString::fromUtf8("lb_DMMF_Unit_AVT"));
        lb_DMMF_Unit_AVT->setGeometry(QRect(291, 240, 40, 18));
        lb_DMMF_Unit_AVT->setFont(font1);
        lb_DMMF_Unit_AVT->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_AVT->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_AVT = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_AVT->setObjectName(QString::fromUtf8("lb_DMMF_Lect_AVT"));
        lb_DMMF_Lect_AVT->setGeometry(QRect(235, 240, 50, 18));
        lb_DMMF_Lect_AVT->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_AVT->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_AVT->setFont(font2);
        lb_DMMF_Lect_AVT->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_AVT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_25 = new QLabel(Temperaturas_4);
        Descr_25->setObjectName(QString::fromUtf8("Descr_25"));
        Descr_25->setGeometry(QRect(25, 240, 180, 18));
        Descr_25->setFont(font2);
        Descr_25->setLayoutDirection(Qt::LeftToRight);
        Descr_25->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_CFB = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_CFB->setObjectName(QString::fromUtf8("lb_DMMF_Lect_CFB"));
        lb_DMMF_Lect_CFB->setGeometry(QRect(235, 210, 50, 18));
        lb_DMMF_Lect_CFB->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_CFB->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_CFB->setFont(font2);
        lb_DMMF_Lect_CFB->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_CFB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_23 = new QLabel(Temperaturas_4);
        Descr_23->setObjectName(QString::fromUtf8("Descr_23"));
        Descr_23->setGeometry(QRect(25, 210, 180, 18));
        Descr_23->setFont(font2);
        Descr_23->setLayoutDirection(Qt::LeftToRight);
        Descr_23->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Unit_CFB = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_CFB->setObjectName(QString::fromUtf8("lb_DMMF_Unit_CFB"));
        lb_DMMF_Unit_CFB->setGeometry(QRect(291, 210, 40, 18));
        lb_DMMF_Unit_CFB->setFont(font1);
        lb_DMMF_Unit_CFB->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_CFB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_22 = new QLabel(Temperaturas_4);
        Descr_22->setObjectName(QString::fromUtf8("Descr_22"));
        Descr_22->setGeometry(QRect(25, 195, 180, 18));
        Descr_22->setFont(font2);
        Descr_22->setLayoutDirection(Qt::LeftToRight);
        Descr_22->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_CFA = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_CFA->setObjectName(QString::fromUtf8("lb_DMMF_Lect_CFA"));
        lb_DMMF_Lect_CFA->setGeometry(QRect(235, 195, 50, 18));
        lb_DMMF_Lect_CFA->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_CFA->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_CFA->setFont(font2);
        lb_DMMF_Lect_CFA->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_CFA->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_DMMF_Unit_CFA = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_CFA->setObjectName(QString::fromUtf8("lb_DMMF_Unit_CFA"));
        lb_DMMF_Unit_CFA->setGeometry(QRect(291, 195, 40, 18));
        lb_DMMF_Unit_CFA->setFont(font1);
        lb_DMMF_Unit_CFA->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_CFA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_24 = new QLabel(Temperaturas_4);
        Descr_24->setObjectName(QString::fromUtf8("Descr_24"));
        Descr_24->setGeometry(QRect(25, 225, 180, 18));
        Descr_24->setFont(font2);
        Descr_24->setLayoutDirection(Qt::LeftToRight);
        Descr_24->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Unit_CFC = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_CFC->setObjectName(QString::fromUtf8("lb_DMMF_Unit_CFC"));
        lb_DMMF_Unit_CFC->setGeometry(QRect(291, 225, 40, 18));
        lb_DMMF_Unit_CFC->setFont(font1);
        lb_DMMF_Unit_CFC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_CFC->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_CFC = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_CFC->setObjectName(QString::fromUtf8("lb_DMMF_Lect_CFC"));
        lb_DMMF_Lect_CFC->setGeometry(QRect(235, 225, 50, 18));
        lb_DMMF_Lect_CFC->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_CFC->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_CFC->setFont(font2);
        lb_DMMF_Lect_CFC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_CFC->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_DMMF_Unit_FPGen = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_FPGen->setObjectName(QString::fromUtf8("lb_DMMF_Unit_FPGen"));
        lb_DMMF_Unit_FPGen->setGeometry(QRect(291, 325, 40, 18));
        lb_DMMF_Unit_FPGen->setFont(font1);
        lb_DMMF_Unit_FPGen->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_FPGen->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_FPGen = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_FPGen->setObjectName(QString::fromUtf8("lb_DMMF_Lect_FPGen"));
        lb_DMMF_Lect_FPGen->setGeometry(QRect(235, 325, 50, 18));
        lb_DMMF_Lect_FPGen->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_FPGen->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_FPGen->setFont(font2);
        lb_DMMF_Lect_FPGen->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_FPGen->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_27 = new QLabel(Temperaturas_4);
        Descr_27->setObjectName(QString::fromUtf8("Descr_27"));
        Descr_27->setGeometry(QRect(25, 325, 225, 18));
        Descr_27->setMinimumSize(QSize(225, 18));
        Descr_27->setMaximumSize(QSize(225, 18));
        Descr_27->setFont(font2);
        Descr_27->setLayoutDirection(Qt::LeftToRight);
        Descr_27->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_16 = new QLabel(Temperaturas_4);
        Descr_16->setObjectName(QString::fromUtf8("Descr_16"));
        Descr_16->setGeometry(QRect(25, 30, 180, 18));
        Descr_16->setFont(font2);
        Descr_16->setLayoutDirection(Qt::LeftToRight);
        Descr_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_VBus = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_VBus->setObjectName(QString::fromUtf8("lb_DMMF_Lect_VBus"));
        lb_DMMF_Lect_VBus->setGeometry(QRect(235, 30, 50, 18));
        lb_DMMF_Lect_VBus->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_VBus->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_VBus->setFont(font2);
        lb_DMMF_Lect_VBus->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_VBus->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_DMMF_Unit_VBus = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_VBus->setObjectName(QString::fromUtf8("lb_DMMF_Unit_VBus"));
        lb_DMMF_Unit_VBus->setGeometry(QRect(291, 30, 40, 18));
        lb_DMMF_Unit_VBus->setFont(font1);
        lb_DMMF_Unit_VBus->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_VBus->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Unit_VFAB = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_VFAB->setObjectName(QString::fromUtf8("lb_DMMF_Unit_VFAB"));
        lb_DMMF_Unit_VFAB->setGeometry(QRect(291, 60, 40, 18));
        lb_DMMF_Unit_VFAB->setFont(font1);
        lb_DMMF_Unit_VFAB->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_VFAB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_18 = new QLabel(Temperaturas_4);
        Descr_18->setObjectName(QString::fromUtf8("Descr_18"));
        Descr_18->setGeometry(QRect(25, 60, 180, 18));
        Descr_18->setFont(font2);
        Descr_18->setLayoutDirection(Qt::LeftToRight);
        Descr_18->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_VFAB = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_VFAB->setObjectName(QString::fromUtf8("lb_DMMF_Lect_VFAB"));
        lb_DMMF_Lect_VFAB->setGeometry(QRect(235, 60, 50, 18));
        lb_DMMF_Lect_VFAB->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_VFAB->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_VFAB->setFont(font2);
        lb_DMMF_Lect_VFAB->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_VFAB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_DMMF_Lect_TMVAR = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_TMVAR->setObjectName(QString::fromUtf8("lb_DMMF_Lect_TMVAR"));
        lb_DMMF_Lect_TMVAR->setGeometry(QRect(235, 135, 50, 18));
        lb_DMMF_Lect_TMVAR->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_TMVAR->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_TMVAR->setFont(font2);
        lb_DMMF_Lect_TMVAR->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_TMVAR->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_21 = new QLabel(Temperaturas_4);
        Descr_21->setObjectName(QString::fromUtf8("Descr_21"));
        Descr_21->setGeometry(QRect(25, 135, 180, 18));
        Descr_21->setFont(font2);
        Descr_21->setLayoutDirection(Qt::LeftToRight);
        Descr_21->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Unit_TMVAR = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_TMVAR->setObjectName(QString::fromUtf8("lb_DMMF_Unit_TMVAR"));
        lb_DMMF_Unit_TMVAR->setGeometry(QRect(291, 135, 40, 18));
        lb_DMMF_Unit_TMVAR->setFont(font1);
        lb_DMMF_Unit_TMVAR->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_TMVAR->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Unit_VFBC = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_VFBC->setObjectName(QString::fromUtf8("lb_DMMF_Unit_VFBC"));
        lb_DMMF_Unit_VFBC->setGeometry(QRect(291, 75, 40, 18));
        lb_DMMF_Unit_VFBC->setFont(font1);
        lb_DMMF_Unit_VFBC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_VFBC->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_19 = new QLabel(Temperaturas_4);
        Descr_19->setObjectName(QString::fromUtf8("Descr_19"));
        Descr_19->setGeometry(QRect(25, 75, 180, 18));
        Descr_19->setFont(font2);
        Descr_19->setLayoutDirection(Qt::LeftToRight);
        Descr_19->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_VFBC = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_VFBC->setObjectName(QString::fromUtf8("lb_DMMF_Lect_VFBC"));
        lb_DMMF_Lect_VFBC->setGeometry(QRect(235, 75, 50, 18));
        lb_DMMF_Lect_VFBC->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_VFBC->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_VFBC->setFont(font2);
        lb_DMMF_Lect_VFBC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_VFBC->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_20 = new QLabel(Temperaturas_4);
        Descr_20->setObjectName(QString::fromUtf8("Descr_20"));
        Descr_20->setGeometry(QRect(25, 90, 180, 18));
        Descr_20->setFont(font2);
        Descr_20->setLayoutDirection(Qt::LeftToRight);
        Descr_20->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Unit_VFAC = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_VFAC->setObjectName(QString::fromUtf8("lb_DMMF_Unit_VFAC"));
        lb_DMMF_Unit_VFAC->setGeometry(QRect(291, 90, 40, 18));
        lb_DMMF_Unit_VFAC->setFont(font1);
        lb_DMMF_Unit_VFAC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_VFAC->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_VFAC = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_VFAC->setObjectName(QString::fromUtf8("lb_DMMF_Lect_VFAC"));
        lb_DMMF_Lect_VFAC->setGeometry(QRect(235, 90, 50, 18));
        lb_DMMF_Lect_VFAC->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_VFAC->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_VFAC->setFont(font2);
        lb_DMMF_Lect_VFAC->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_VFAC->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_17 = new QLabel(Temperaturas_4);
        Descr_17->setObjectName(QString::fromUtf8("Descr_17"));
        Descr_17->setGeometry(QRect(25, 45, 180, 18));
        Descr_17->setFont(font2);
        Descr_17->setLayoutDirection(Qt::LeftToRight);
        Descr_17->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_DMMF_Lect_FBus = new QLabel(Temperaturas_4);
        lb_DMMF_Lect_FBus->setObjectName(QString::fromUtf8("lb_DMMF_Lect_FBus"));
        lb_DMMF_Lect_FBus->setGeometry(QRect(235, 45, 50, 18));
        lb_DMMF_Lect_FBus->setMinimumSize(QSize(50, 18));
        lb_DMMF_Lect_FBus->setMaximumSize(QSize(50, 18));
        lb_DMMF_Lect_FBus->setFont(font2);
        lb_DMMF_Lect_FBus->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Lect_FBus->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_DMMF_Unit_FBus = new QLabel(Temperaturas_4);
        lb_DMMF_Unit_FBus->setObjectName(QString::fromUtf8("lb_DMMF_Unit_FBus"));
        lb_DMMF_Unit_FBus->setGeometry(QRect(291, 45, 40, 18));
        lb_DMMF_Unit_FBus->setFont(font1);
        lb_DMMF_Unit_FBus->setLayoutDirection(Qt::LeftToRight);
        lb_DMMF_Unit_FBus->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Temperaturas_5 = new QFrame(D7);
        Temperaturas_5->setObjectName(QString::fromUtf8("Temperaturas_5"));
        Temperaturas_5->setGeometry(QRect(345, 438, 340, 217));
        Temperaturas_5->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_5->setFrameShape(QFrame::Box);
        Temperaturas_5->setFrameShadow(QFrame::Sunken);
        frame_11 = new QFrame(Temperaturas_5);
        frame_11->setObjectName(QString::fromUtf8("frame_11"));
        frame_11->setGeometry(QRect(1, 1, 340, 20));
        frame_11->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_11->setFrameShape(QFrame::WinPanel);
        frame_11->setFrameShadow(QFrame::Raised);
        frame_11->setLineWidth(2);
        label_15 = new QLabel(frame_11);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(1, 1, 336, 16));
        label_15->setFont(font);
        label_15->setAlignment(Qt::AlignCenter);
        lb_LS_Unit_VBus = new QLabel(Temperaturas_5);
        lb_LS_Unit_VBus->setObjectName(QString::fromUtf8("lb_LS_Unit_VBus"));
        lb_LS_Unit_VBus->setGeometry(QRect(291, 60, 40, 18));
        lb_LS_Unit_VBus->setFont(font1);
        lb_LS_Unit_VBus->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_VBus->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Lect_VBus = new QLabel(Temperaturas_5);
        lb_LS_Lect_VBus->setObjectName(QString::fromUtf8("lb_LS_Lect_VBus"));
        lb_LS_Lect_VBus->setGeometry(QRect(235, 60, 50, 18));
        lb_LS_Lect_VBus->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_VBus->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_VBus->setFont(font2);
        lb_LS_Lect_VBus->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_VBus->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_30 = new QLabel(Temperaturas_5);
        Descr_30->setObjectName(QString::fromUtf8("Descr_30"));
        Descr_30->setGeometry(QRect(25, 60, 180, 18));
        Descr_30->setFont(font2);
        Descr_30->setLayoutDirection(Qt::LeftToRight);
        Descr_30->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Unit_VCE = new QLabel(Temperaturas_5);
        lb_LS_Unit_VCE->setObjectName(QString::fromUtf8("lb_LS_Unit_VCE"));
        lb_LS_Unit_VCE->setGeometry(QRect(291, 30, 40, 18));
        lb_LS_Unit_VCE->setFont(font1);
        lb_LS_Unit_VCE->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_VCE->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Lect_VCE = new QLabel(Temperaturas_5);
        lb_LS_Lect_VCE->setObjectName(QString::fromUtf8("lb_LS_Lect_VCE"));
        lb_LS_Lect_VCE->setGeometry(QRect(235, 30, 50, 18));
        lb_LS_Lect_VCE->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_VCE->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_VCE->setFont(font2);
        lb_LS_Lect_VCE->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_VCE->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_28 = new QLabel(Temperaturas_5);
        Descr_28->setObjectName(QString::fromUtf8("Descr_28"));
        Descr_28->setGeometry(QRect(25, 30, 180, 18));
        Descr_28->setFont(font2);
        Descr_28->setLayoutDirection(Qt::LeftToRight);
        Descr_28->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Unit_VG = new QLabel(Temperaturas_5);
        lb_LS_Unit_VG->setObjectName(QString::fromUtf8("lb_LS_Unit_VG"));
        lb_LS_Unit_VG->setGeometry(QRect(291, 160, 40, 18));
        lb_LS_Unit_VG->setFont(font1);
        lb_LS_Unit_VG->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_VG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Lect_VG = new QLabel(Temperaturas_5);
        lb_LS_Lect_VG->setObjectName(QString::fromUtf8("lb_LS_Lect_VG"));
        lb_LS_Lect_VG->setGeometry(QRect(235, 162, 50, 18));
        lb_LS_Lect_VG->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_VG->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_VG->setFont(font2);
        lb_LS_Lect_VG->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_VG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_31 = new QLabel(Temperaturas_5);
        Descr_31->setObjectName(QString::fromUtf8("Descr_31"));
        Descr_31->setGeometry(QRect(25, 162, 180, 18));
        Descr_31->setFont(font2);
        Descr_31->setLayoutDirection(Qt::LeftToRight);
        Descr_31->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Unit_ACE = new QLabel(Temperaturas_5);
        lb_LS_Unit_ACE->setObjectName(QString::fromUtf8("lb_LS_Unit_ACE"));
        lb_LS_Unit_ACE->setGeometry(QRect(291, 45, 40, 18));
        lb_LS_Unit_ACE->setFont(font1);
        lb_LS_Unit_ACE->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_ACE->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Lect_ACE = new QLabel(Temperaturas_5);
        lb_LS_Lect_ACE->setObjectName(QString::fromUtf8("lb_LS_Lect_ACE"));
        lb_LS_Lect_ACE->setGeometry(QRect(235, 45, 50, 18));
        lb_LS_Lect_ACE->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_ACE->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_ACE->setFont(font2);
        lb_LS_Lect_ACE->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_ACE->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_29 = new QLabel(Temperaturas_5);
        Descr_29->setObjectName(QString::fromUtf8("Descr_29"));
        Descr_29->setGeometry(QRect(25, 45, 180, 18));
        Descr_29->setFont(font2);
        Descr_29->setLayoutDirection(Qt::LeftToRight);
        Descr_29->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Unit_FBus = new QLabel(Temperaturas_5);
        lb_LS_Unit_FBus->setObjectName(QString::fromUtf8("lb_LS_Unit_FBus"));
        lb_LS_Unit_FBus->setGeometry(QRect(290, 75, 40, 18));
        lb_LS_Unit_FBus->setFont(font1);
        lb_LS_Unit_FBus->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Unit_FBus->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LS_Lect_FBus = new QLabel(Temperaturas_5);
        lb_LS_Lect_FBus->setObjectName(QString::fromUtf8("lb_LS_Lect_FBus"));
        lb_LS_Lect_FBus->setGeometry(QRect(234, 75, 50, 18));
        lb_LS_Lect_FBus->setMinimumSize(QSize(50, 18));
        lb_LS_Lect_FBus->setMaximumSize(QSize(50, 18));
        lb_LS_Lect_FBus->setFont(font2);
        lb_LS_Lect_FBus->setLayoutDirection(Qt::LeftToRight);
        lb_LS_Lect_FBus->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_43 = new QLabel(Temperaturas_5);
        Descr_43->setObjectName(QString::fromUtf8("Descr_43"));
        Descr_43->setGeometry(QRect(24, 75, 180, 18));
        Descr_43->setFont(font2);
        Descr_43->setLayoutDirection(Qt::LeftToRight);
        Descr_43->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Temperaturas_6 = new QFrame(D7);
        Temperaturas_6->setObjectName(QString::fromUtf8("Temperaturas_6"));
        Temperaturas_6->setGeometry(QRect(686, 5, 335, 151));
        Temperaturas_6->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_6->setFrameShape(QFrame::Box);
        Temperaturas_6->setFrameShadow(QFrame::Sunken);
        frame_12 = new QFrame(Temperaturas_6);
        frame_12->setObjectName(QString::fromUtf8("frame_12"));
        frame_12->setEnabled(true);
        frame_12->setGeometry(QRect(1, 1, 340, 20));
        frame_12->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_12->setFrameShape(QFrame::WinPanel);
        frame_12->setFrameShadow(QFrame::Raised);
        frame_12->setLineWidth(2);
        label_16 = new QLabel(frame_12);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setEnabled(true);
        label_16->setGeometry(QRect(2, 2, 334, 16));
        label_16->setFont(font);
        label_16->setAlignment(Qt::AlignCenter);
        lb_EM_Unit_VCBG = new QLabel(Temperaturas_6);
        lb_EM_Unit_VCBG->setObjectName(QString::fromUtf8("lb_EM_Unit_VCBG"));
        lb_EM_Unit_VCBG->setGeometry(QRect(291, 45, 40, 18));
        lb_EM_Unit_VCBG->setFont(font1);
        lb_EM_Unit_VCBG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_VCBG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_EM_Lect_VCBG = new QLabel(Temperaturas_6);
        lb_EM_Lect_VCBG->setObjectName(QString::fromUtf8("lb_EM_Lect_VCBG"));
        lb_EM_Lect_VCBG->setGeometry(QRect(235, 45, 50, 18));
        lb_EM_Lect_VCBG->setMinimumSize(QSize(50, 18));
        lb_EM_Lect_VCBG->setMaximumSize(QSize(50, 18));
        lb_EM_Lect_VCBG->setFont(font2);
        lb_EM_Lect_VCBG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_VCBG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_34 = new QLabel(Temperaturas_6);
        Descr_34->setObjectName(QString::fromUtf8("Descr_34"));
        Descr_34->setGeometry(QRect(25, 45, 200, 18));
        Descr_34->setFont(font2);
        Descr_34->setLayoutDirection(Qt::LeftToRight);
        Descr_34->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_EM_Unit_BALACG = new QLabel(Temperaturas_6);
        lb_EM_Unit_BALACG->setObjectName(QString::fromUtf8("lb_EM_Unit_BALACG"));
        lb_EM_Unit_BALACG->setGeometry(QRect(280, 90, 40, 18));
        lb_EM_Unit_BALACG->setFont(font1);
        lb_EM_Unit_BALACG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_BALACG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_EM_Lect_BALACG = new QLabel(Temperaturas_6);
        lb_EM_Lect_BALACG->setObjectName(QString::fromUtf8("lb_EM_Lect_BALACG"));
        lb_EM_Lect_BALACG->setGeometry(QRect(224, 92, 50, 18));
        lb_EM_Lect_BALACG->setMinimumSize(QSize(50, 18));
        lb_EM_Lect_BALACG->setMaximumSize(QSize(50, 18));
        lb_EM_Lect_BALACG->setFont(font2);
        lb_EM_Lect_BALACG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_BALACG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_35 = new QLabel(Temperaturas_6);
        Descr_35->setObjectName(QString::fromUtf8("Descr_35"));
        Descr_35->setGeometry(QRect(25, 80, 200, 18));
        Descr_35->setFont(font2);
        Descr_35->setLayoutDirection(Qt::LeftToRight);
        Descr_35->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_EM_Unit_BAEG = new QLabel(Temperaturas_6);
        lb_EM_Unit_BAEG->setObjectName(QString::fromUtf8("lb_EM_Unit_BAEG"));
        lb_EM_Unit_BAEG->setGeometry(QRect(291, 120, 40, 18));
        lb_EM_Unit_BAEG->setFont(font1);
        lb_EM_Unit_BAEG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_BAEG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_EM_Lect_BAEG = new QLabel(Temperaturas_6);
        lb_EM_Lect_BAEG->setObjectName(QString::fromUtf8("lb_EM_Lect_BAEG"));
        lb_EM_Lect_BAEG->setGeometry(QRect(235, 122, 50, 18));
        lb_EM_Lect_BAEG->setMinimumSize(QSize(50, 18));
        lb_EM_Lect_BAEG->setMaximumSize(QSize(50, 18));
        lb_EM_Lect_BAEG->setFont(font2);
        lb_EM_Lect_BAEG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_BAEG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_36 = new QLabel(Temperaturas_6);
        Descr_36->setObjectName(QString::fromUtf8("Descr_36"));
        Descr_36->setGeometry(QRect(25, 122, 200, 18));
        Descr_36->setFont(font2);
        Descr_36->setLayoutDirection(Qt::LeftToRight);
        Descr_36->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_EM_Unit_VCAG = new QLabel(Temperaturas_6);
        lb_EM_Unit_VCAG->setObjectName(QString::fromUtf8("lb_EM_Unit_VCAG"));
        lb_EM_Unit_VCAG->setGeometry(QRect(291, 30, 40, 18));
        lb_EM_Unit_VCAG->setFont(font1);
        lb_EM_Unit_VCAG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Unit_VCAG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_EM_Lect_VCAG = new QLabel(Temperaturas_6);
        lb_EM_Lect_VCAG->setObjectName(QString::fromUtf8("lb_EM_Lect_VCAG"));
        lb_EM_Lect_VCAG->setGeometry(QRect(235, 30, 50, 18));
        lb_EM_Lect_VCAG->setMinimumSize(QSize(50, 18));
        lb_EM_Lect_VCAG->setMaximumSize(QSize(50, 18));
        lb_EM_Lect_VCAG->setFont(font2);
        lb_EM_Lect_VCAG->setLayoutDirection(Qt::LeftToRight);
        lb_EM_Lect_VCAG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_32 = new QLabel(Temperaturas_6);
        Descr_32->setObjectName(QString::fromUtf8("Descr_32"));
        Descr_32->setGeometry(QRect(25, 30, 200, 18));
        Descr_32->setFont(font2);
        Descr_32->setLayoutDirection(Qt::LeftToRight);
        Descr_32->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Temperaturas_7 = new QFrame(D7);
        Temperaturas_7->setObjectName(QString::fromUtf8("Temperaturas_7"));
        Temperaturas_7->setGeometry(QRect(685, 156, 335, 499));
        Temperaturas_7->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas_7->setFrameShape(QFrame::Box);
        Temperaturas_7->setFrameShadow(QFrame::Sunken);
        frame_13 = new QFrame(Temperaturas_7);
        frame_13->setObjectName(QString::fromUtf8("frame_13"));
        frame_13->setGeometry(QRect(3, 3, 340, 20));
        frame_13->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_13->setFrameShape(QFrame::WinPanel);
        frame_13->setFrameShadow(QFrame::Raised);
        frame_13->setLineWidth(2);
        label_17 = new QLabel(frame_13);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(1, 1, 334, 16));
        label_17->setFont(font);
        label_17->setAlignment(Qt::AlignCenter);
        lb_LG_Unit_NTALG = new QLabel(Temperaturas_7);
        lb_LG_Unit_NTALG->setObjectName(QString::fromUtf8("lb_LG_Unit_NTALG"));
        lb_LG_Unit_NTALG->setGeometry(QRect(291, 105, 40, 18));
        lb_LG_Unit_NTALG->setFont(font1);
        lb_LG_Unit_NTALG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_NTALG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Lect_NTALG = new QLabel(Temperaturas_7);
        lb_LG_Lect_NTALG->setObjectName(QString::fromUtf8("lb_LG_Lect_NTALG"));
        lb_LG_Lect_NTALG->setGeometry(QRect(235, 105, 50, 18));
        lb_LG_Lect_NTALG->setMinimumSize(QSize(50, 18));
        lb_LG_Lect_NTALG->setMaximumSize(QSize(50, 18));
        lb_LG_Lect_NTALG->setFont(font2);
        lb_LG_Lect_NTALG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_NTALG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_42 = new QLabel(Temperaturas_7);
        Descr_42->setObjectName(QString::fromUtf8("Descr_42"));
        Descr_42->setGeometry(QRect(25, 105, 200, 18));
        Descr_42->setFont(font2);
        Descr_42->setLayoutDirection(Qt::LeftToRight);
        Descr_42->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Unit_PSLDGA = new QLabel(Temperaturas_7);
        lb_LG_Unit_PSLDGA->setObjectName(QString::fromUtf8("lb_LG_Unit_PSLDGA"));
        lb_LG_Unit_PSLDGA->setGeometry(QRect(291, 45, 40, 18));
        lb_LG_Unit_PSLDGA->setFont(font1);
        lb_LG_Unit_PSLDGA->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_PSLDGA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_38 = new QLabel(Temperaturas_7);
        Descr_38->setObjectName(QString::fromUtf8("Descr_38"));
        Descr_38->setGeometry(QRect(25, 45, 200, 18));
        Descr_38->setFont(font2);
        Descr_38->setLayoutDirection(Qt::LeftToRight);
        Descr_38->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Lect_PSLDGA = new QLabel(Temperaturas_7);
        lb_LG_Lect_PSLDGA->setObjectName(QString::fromUtf8("lb_LG_Lect_PSLDGA"));
        lb_LG_Lect_PSLDGA->setGeometry(QRect(235, 45, 50, 18));
        lb_LG_Lect_PSLDGA->setMinimumSize(QSize(50, 18));
        lb_LG_Lect_PSLDGA->setMaximumSize(QSize(50, 18));
        lb_LG_Lect_PSLDGA->setFont(font2);
        lb_LG_Lect_PSLDGA->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_PSLDGA->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_LG_Unit_PSLDGB = new QLabel(Temperaturas_7);
        lb_LG_Unit_PSLDGB->setObjectName(QString::fromUtf8("lb_LG_Unit_PSLDGB"));
        lb_LG_Unit_PSLDGB->setGeometry(QRect(291, 60, 40, 18));
        lb_LG_Unit_PSLDGB->setFont(font1);
        lb_LG_Unit_PSLDGB->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_PSLDGB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Lect_PSLDGB = new QLabel(Temperaturas_7);
        lb_LG_Lect_PSLDGB->setObjectName(QString::fromUtf8("lb_LG_Lect_PSLDGB"));
        lb_LG_Lect_PSLDGB->setGeometry(QRect(235, 60, 50, 18));
        lb_LG_Lect_PSLDGB->setMinimumSize(QSize(50, 18));
        lb_LG_Lect_PSLDGB->setMaximumSize(QSize(50, 18));
        lb_LG_Lect_PSLDGB->setFont(font2);
        lb_LG_Lect_PSLDGB->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_PSLDGB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_39 = new QLabel(Temperaturas_7);
        Descr_39->setObjectName(QString::fromUtf8("Descr_39"));
        Descr_39->setGeometry(QRect(25, 60, 200, 18));
        Descr_39->setFont(font2);
        Descr_39->setLayoutDirection(Qt::LeftToRight);
        Descr_39->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Unit_EBAAP = new QLabel(Temperaturas_7);
        lb_LG_Unit_EBAAP->setObjectName(QString::fromUtf8("lb_LG_Unit_EBAAP"));
        lb_LG_Unit_EBAAP->setGeometry(QRect(291, 90, 40, 18));
        lb_LG_Unit_EBAAP->setFont(font1);
        lb_LG_Unit_EBAAP->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_EBAAP->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Lect_EBAAP = new QLabel(Temperaturas_7);
        lb_LG_Lect_EBAAP->setObjectName(QString::fromUtf8("lb_LG_Lect_EBAAP"));
        lb_LG_Lect_EBAAP->setGeometry(QRect(235, 90, 50, 18));
        lb_LG_Lect_EBAAP->setMinimumSize(QSize(50, 18));
        lb_LG_Lect_EBAAP->setMaximumSize(QSize(50, 18));
        lb_LG_Lect_EBAAP->setFont(font2);
        lb_LG_Lect_EBAAP->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_EBAAP->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_41 = new QLabel(Temperaturas_7);
        Descr_41->setObjectName(QString::fromUtf8("Descr_41"));
        Descr_41->setGeometry(QRect(25, 90, 200, 18));
        Descr_41->setFont(font2);
        Descr_41->setLayoutDirection(Qt::LeftToRight);
        Descr_41->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_37 = new QLabel(Temperaturas_7);
        Descr_37->setObjectName(QString::fromUtf8("Descr_37"));
        Descr_37->setGeometry(QRect(25, 30, 200, 18));
        Descr_37->setFont(font2);
        Descr_37->setLayoutDirection(Qt::LeftToRight);
        Descr_37->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Unit_PSALG = new QLabel(Temperaturas_7);
        lb_LG_Unit_PSALG->setObjectName(QString::fromUtf8("lb_LG_Unit_PSALG"));
        lb_LG_Unit_PSALG->setGeometry(QRect(291, 30, 40, 18));
        lb_LG_Unit_PSALG->setFont(font1);
        lb_LG_Unit_PSALG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_PSALG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Lect_PSALG = new QLabel(Temperaturas_7);
        lb_LG_Lect_PSALG->setObjectName(QString::fromUtf8("lb_LG_Lect_PSALG"));
        lb_LG_Lect_PSALG->setGeometry(QRect(235, 30, 50, 18));
        lb_LG_Lect_PSALG->setMinimumSize(QSize(50, 18));
        lb_LG_Lect_PSALG->setMaximumSize(QSize(50, 18));
        lb_LG_Lect_PSALG->setFont(font2);
        lb_LG_Lect_PSALG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_PSALG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_LG_Unit_PSLDG = new QLabel(Temperaturas_7);
        lb_LG_Unit_PSLDG->setObjectName(QString::fromUtf8("lb_LG_Unit_PSLDG"));
        lb_LG_Unit_PSLDG->setGeometry(QRect(291, 75, 40, 18));
        lb_LG_Unit_PSLDG->setFont(font1);
        lb_LG_Unit_PSLDG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Unit_PSLDG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_LG_Lect_PSLDG = new QLabel(Temperaturas_7);
        lb_LG_Lect_PSLDG->setObjectName(QString::fromUtf8("lb_LG_Lect_PSLDG"));
        lb_LG_Lect_PSLDG->setGeometry(QRect(235, 75, 50, 18));
        lb_LG_Lect_PSLDG->setMinimumSize(QSize(50, 18));
        lb_LG_Lect_PSLDG->setMaximumSize(QSize(50, 18));
        lb_LG_Lect_PSLDG->setFont(font2);
        lb_LG_Lect_PSLDG->setLayoutDirection(Qt::LeftToRight);
        lb_LG_Lect_PSLDG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_40 = new QLabel(Temperaturas_7);
        Descr_40->setObjectName(QString::fromUtf8("Descr_40"));
        Descr_40->setGeometry(QRect(25, 75, 200, 18));
        Descr_40->setFont(font2);
        Descr_40->setLayoutDirection(Qt::LeftToRight);
        Descr_40->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Temperaturas = new QFrame(D7);
        Temperaturas->setObjectName(QString::fromUtf8("Temperaturas"));
        Temperaturas->setGeometry(QRect(5, 5, 340, 373));
        QFont font3;
        font3.setKerning(true);
        Temperaturas->setFont(font3);
        Temperaturas->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);"));
        Temperaturas->setFrameShape(QFrame::Box);
        Temperaturas->setFrameShadow(QFrame::Sunken);
        frame_6 = new QFrame(Temperaturas);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(1, 1, 338, 20));
        frame_6->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_6->setFrameShape(QFrame::WinPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        frame_6->setLineWidth(2);
        label_10 = new QLabel(frame_6);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(2, 2, 334, 16));
        label_10->setFont(font);
        label_10->setAlignment(Qt::AlignCenter);
        Descr_01 = new QLabel(Temperaturas);
        Descr_01->setObjectName(QString::fromUtf8("Descr_01"));
        Descr_01->setGeometry(QRect(26, 30, 200, 18));
        Descr_01->setFont(font2);
        Descr_01->setLayoutDirection(Qt::LeftToRight);
        Descr_01->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_FaseU1 = new QLabel(Temperaturas);
        lb_Temp_Lect_FaseU1->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseU1"));
        lb_Temp_Lect_FaseU1->setGeometry(QRect(235, 30, 50, 18));
        lb_Temp_Lect_FaseU1->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_FaseU1->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_FaseU1->setFont(font2);
        lb_Temp_Lect_FaseU1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseU1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Temp_Unit_FaseU1 = new QLabel(Temperaturas);
        lb_Temp_Unit_FaseU1->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseU1"));
        lb_Temp_Unit_FaseU1->setGeometry(QRect(291, 30, 40, 18));
        lb_Temp_Unit_FaseU1->setFont(font1);
        lb_Temp_Unit_FaseU1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseU1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Unit_FaseU2 = new QLabel(Temperaturas);
        lb_Temp_Unit_FaseU2->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseU2"));
        lb_Temp_Unit_FaseU2->setGeometry(QRect(291, 45, 40, 18));
        lb_Temp_Unit_FaseU2->setFont(font1);
        lb_Temp_Unit_FaseU2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseU2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_2 = new QLabel(Temperaturas);
        Descr_2->setObjectName(QString::fromUtf8("Descr_2"));
        Descr_2->setGeometry(QRect(26, 45, 200, 18));
        Descr_2->setFont(font2);
        Descr_2->setLayoutDirection(Qt::LeftToRight);
        Descr_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_FaseU2 = new QLabel(Temperaturas);
        lb_Temp_Lect_FaseU2->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseU2"));
        lb_Temp_Lect_FaseU2->setGeometry(QRect(235, 45, 50, 18));
        lb_Temp_Lect_FaseU2->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_FaseU2->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_FaseU2->setFont(font2);
        lb_Temp_Lect_FaseU2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseU2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Temp_Lect_TCIIB = new QLabel(Temperaturas);
        lb_Temp_Lect_TCIIB->setObjectName(QString::fromUtf8("lb_Temp_Lect_TCIIB"));
        lb_Temp_Lect_TCIIB->setGeometry(QRect(235, 195, 50, 18));
        lb_Temp_Lect_TCIIB->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TCIIB->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TCIIB->setFont(font2);
        lb_Temp_Lect_TCIIB->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TCIIB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Temp_Unit_TCIIB = new QLabel(Temperaturas);
        lb_Temp_Unit_TCIIB->setObjectName(QString::fromUtf8("lb_Temp_Unit_TCIIB"));
        lb_Temp_Unit_TCIIB->setGeometry(QRect(291, 195, 40, 18));
        lb_Temp_Unit_TCIIB->setFont(font1);
        lb_Temp_Unit_TCIIB->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TCIIB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_12 = new QLabel(Temperaturas);
        Descr_12->setObjectName(QString::fromUtf8("Descr_12"));
        Descr_12->setGeometry(QRect(25, 195, 225, 18));
        Descr_12->setMinimumSize(QSize(225, 18));
        Descr_12->setMaximumSize(QSize(225, 18));
        Descr_12->setFont(font2);
        Descr_12->setLayoutDirection(Qt::LeftToRight);
        Descr_12->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_9 = new QLabel(Temperaturas);
        Descr_9->setObjectName(QString::fromUtf8("Descr_9"));
        Descr_9->setGeometry(QRect(26, 150, 200, 18));
        Descr_9->setFont(font2);
        Descr_9->setLayoutDirection(Qt::LeftToRight);
        Descr_9->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_TCGDE = new QLabel(Temperaturas);
        lb_Temp_Lect_TCGDE->setObjectName(QString::fromUtf8("lb_Temp_Lect_TCGDE"));
        lb_Temp_Lect_TCGDE->setGeometry(QRect(235, 150, 50, 18));
        lb_Temp_Lect_TCGDE->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TCGDE->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TCGDE->setFont(font2);
        lb_Temp_Lect_TCGDE->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TCGDE->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Temp_Unit_TCGDE = new QLabel(Temperaturas);
        lb_Temp_Unit_TCGDE->setObjectName(QString::fromUtf8("lb_Temp_Unit_TCGDE"));
        lb_Temp_Unit_TCGDE->setGeometry(QRect(291, 150, 40, 18));
        lb_Temp_Unit_TCGDE->setFont(font1);
        lb_Temp_Unit_TCGDE->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TCGDE->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_FaseW1 = new QLabel(Temperaturas);
        lb_Temp_Lect_FaseW1->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseW1"));
        lb_Temp_Lect_FaseW1->setGeometry(QRect(235, 90, 50, 18));
        lb_Temp_Lect_FaseW1->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_FaseW1->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_FaseW1->setFont(font2);
        lb_Temp_Lect_FaseW1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseW1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Temp_Unit_FaseW1 = new QLabel(Temperaturas);
        lb_Temp_Unit_FaseW1->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseW1"));
        lb_Temp_Unit_FaseW1->setGeometry(QRect(291, 90, 40, 18));
        lb_Temp_Unit_FaseW1->setFont(font1);
        lb_Temp_Unit_FaseW1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseW1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_5 = new QLabel(Temperaturas);
        Descr_5->setObjectName(QString::fromUtf8("Descr_5"));
        Descr_5->setGeometry(QRect(26, 90, 200, 18));
        Descr_5->setFont(font2);
        Descr_5->setLayoutDirection(Qt::LeftToRight);
        Descr_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Unit_FaseV1 = new QLabel(Temperaturas);
        lb_Temp_Unit_FaseV1->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseV1"));
        lb_Temp_Unit_FaseV1->setGeometry(QRect(291, 60, 40, 18));
        lb_Temp_Unit_FaseV1->setFont(font1);
        lb_Temp_Unit_FaseV1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseV1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_3 = new QLabel(Temperaturas);
        Descr_3->setObjectName(QString::fromUtf8("Descr_3"));
        Descr_3->setGeometry(QRect(26, 60, 200, 18));
        Descr_3->setFont(font2);
        Descr_3->setLayoutDirection(Qt::LeftToRight);
        Descr_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_FaseV1 = new QLabel(Temperaturas);
        lb_Temp_Lect_FaseV1->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseV1"));
        lb_Temp_Lect_FaseV1->setGeometry(QRect(235, 60, 50, 18));
        lb_Temp_Lect_FaseV1->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_FaseV1->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_FaseV1->setFont(font2);
        lb_Temp_Lect_FaseV1->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseV1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_6 = new QLabel(Temperaturas);
        Descr_6->setObjectName(QString::fromUtf8("Descr_6"));
        Descr_6->setGeometry(QRect(26, 105, 200, 18));
        Descr_6->setFont(font2);
        Descr_6->setLayoutDirection(Qt::LeftToRight);
        Descr_6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Unit_FaseW2 = new QLabel(Temperaturas);
        lb_Temp_Unit_FaseW2->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseW2"));
        lb_Temp_Unit_FaseW2->setGeometry(QRect(291, 105, 40, 18));
        lb_Temp_Unit_FaseW2->setFont(font1);
        lb_Temp_Unit_FaseW2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseW2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_FaseW2 = new QLabel(Temperaturas);
        lb_Temp_Lect_FaseW2->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseW2"));
        lb_Temp_Lect_FaseW2->setGeometry(QRect(235, 105, 50, 18));
        lb_Temp_Lect_FaseW2->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_FaseW2->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_FaseW2->setFont(font2);
        lb_Temp_Lect_FaseW2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseW2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_7 = new QLabel(Temperaturas);
        Descr_7->setObjectName(QString::fromUtf8("Descr_7"));
        Descr_7->setGeometry(QRect(26, 120, 200, 18));
        Descr_7->setFont(font2);
        Descr_7->setLayoutDirection(Qt::LeftToRight);
        Descr_7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_TPEG = new QLabel(Temperaturas);
        lb_Temp_Lect_TPEG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TPEG"));
        lb_Temp_Lect_TPEG->setGeometry(QRect(235, 120, 50, 18));
        lb_Temp_Lect_TPEG->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TPEG->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TPEG->setFont(font2);
        lb_Temp_Lect_TPEG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TPEG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Temp_Unit_TPEG = new QLabel(Temperaturas);
        lb_Temp_Unit_TPEG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TPEG"));
        lb_Temp_Unit_TPEG->setGeometry(QRect(291, 120, 40, 18));
        lb_Temp_Unit_TPEG->setFont(font1);
        lb_Temp_Unit_TPEG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TPEG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_FaseV2 = new QLabel(Temperaturas);
        lb_Temp_Lect_FaseV2->setObjectName(QString::fromUtf8("lb_Temp_Lect_FaseV2"));
        lb_Temp_Lect_FaseV2->setGeometry(QRect(235, 75, 50, 18));
        lb_Temp_Lect_FaseV2->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_FaseV2->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_FaseV2->setFont(font2);
        lb_Temp_Lect_FaseV2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_FaseV2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Temp_Unit_FaseV2 = new QLabel(Temperaturas);
        lb_Temp_Unit_FaseV2->setObjectName(QString::fromUtf8("lb_Temp_Unit_FaseV2"));
        lb_Temp_Unit_FaseV2->setGeometry(QRect(291, 75, 40, 18));
        lb_Temp_Unit_FaseV2->setFont(font1);
        lb_Temp_Unit_FaseV2->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_FaseV2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_4 = new QLabel(Temperaturas);
        Descr_4->setObjectName(QString::fromUtf8("Descr_4"));
        Descr_4->setGeometry(QRect(26, 75, 200, 18));
        Descr_4->setFont(font2);
        Descr_4->setLayoutDirection(Qt::LeftToRight);
        Descr_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Unit_TCIOB = new QLabel(Temperaturas);
        lb_Temp_Unit_TCIOB->setObjectName(QString::fromUtf8("lb_Temp_Unit_TCIOB"));
        lb_Temp_Unit_TCIOB->setGeometry(QRect(291, 180, 40, 18));
        lb_Temp_Unit_TCIOB->setFont(font1);
        lb_Temp_Unit_TCIOB->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TCIOB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_TCIOB = new QLabel(Temperaturas);
        lb_Temp_Lect_TCIOB->setObjectName(QString::fromUtf8("lb_Temp_Lect_TCIOB"));
        lb_Temp_Lect_TCIOB->setGeometry(QRect(235, 180, 50, 18));
        lb_Temp_Lect_TCIOB->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TCIOB->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TCIOB->setFont(font2);
        lb_Temp_Lect_TCIOB->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TCIOB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_11 = new QLabel(Temperaturas);
        Descr_11->setObjectName(QString::fromUtf8("Descr_11"));
        Descr_11->setGeometry(QRect(25, 180, 225, 18));
        Descr_11->setMinimumSize(QSize(225, 18));
        Descr_11->setMaximumSize(QSize(225, 18));
        Descr_11->setFont(font2);
        Descr_11->setLayoutDirection(Qt::LeftToRight);
        Descr_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Unit_TSALG = new QLabel(Temperaturas);
        lb_Temp_Unit_TSALG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TSALG"));
        lb_Temp_Unit_TSALG->setGeometry(QRect(291, 135, 40, 18));
        lb_Temp_Unit_TSALG->setFont(font1);
        lb_Temp_Unit_TSALG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TSALG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_TSALG = new QLabel(Temperaturas);
        lb_Temp_Lect_TSALG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TSALG"));
        lb_Temp_Lect_TSALG->setGeometry(QRect(235, 135, 50, 18));
        lb_Temp_Lect_TSALG->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TSALG->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TSALG->setFont(font2);
        lb_Temp_Lect_TSALG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TSALG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_8 = new QLabel(Temperaturas);
        Descr_8->setObjectName(QString::fromUtf8("Descr_8"));
        Descr_8->setGeometry(QRect(26, 135, 200, 18));
        Descr_8->setFont(font2);
        Descr_8->setLayoutDirection(Qt::LeftToRight);
        Descr_8->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_10 = new QLabel(Temperaturas);
        Descr_10->setObjectName(QString::fromUtf8("Descr_10"));
        Descr_10->setGeometry(QRect(26, 165, 200, 18));
        Descr_10->setFont(font2);
        Descr_10->setLayoutDirection(Qt::LeftToRight);
        Descr_10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_TCGNDE = new QLabel(Temperaturas);
        lb_Temp_Lect_TCGNDE->setObjectName(QString::fromUtf8("lb_Temp_Lect_TCGNDE"));
        lb_Temp_Lect_TCGNDE->setGeometry(QRect(235, 165, 50, 18));
        lb_Temp_Lect_TCGNDE->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TCGNDE->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TCGNDE->setFont(font2);
        lb_Temp_Lect_TCGNDE->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TCGNDE->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lb_Temp_Unit_TCGNDE = new QLabel(Temperaturas);
        lb_Temp_Unit_TCGNDE->setObjectName(QString::fromUtf8("lb_Temp_Unit_TCGNDE"));
        lb_Temp_Unit_TCGNDE->setGeometry(QRect(291, 165, 40, 18));
        lb_Temp_Unit_TCGNDE->setFont(font1);
        lb_Temp_Unit_TCGNDE->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TCGNDE->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_TACG = new QLabel(Temperaturas);
        lb_Temp_Lect_TACG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TACG"));
        lb_Temp_Lect_TACG->setGeometry(QRect(235, 270, 50, 18));
        lb_Temp_Lect_TACG->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TACG->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TACG->setFont(font2);
        lb_Temp_Lect_TACG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TACG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_13 = new QLabel(Temperaturas);
        Descr_13->setObjectName(QString::fromUtf8("Descr_13"));
        Descr_13->setGeometry(QRect(25, 270, 225, 18));
        Descr_13->setMinimumSize(QSize(225, 18));
        Descr_13->setMaximumSize(QSize(225, 18));
        Descr_13->setFont(font2);
        Descr_13->setLayoutDirection(Qt::LeftToRight);
        Descr_13->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Unit_TACG = new QLabel(Temperaturas);
        lb_Temp_Unit_TACG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TACG"));
        lb_Temp_Unit_TACG->setGeometry(QRect(291, 270, 40, 18));
        lb_Temp_Unit_TACG->setFont(font1);
        lb_Temp_Unit_TACG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TACG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_TEAEG = new QLabel(Temperaturas);
        lb_Temp_Lect_TEAEG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TEAEG"));
        lb_Temp_Lect_TEAEG->setGeometry(QRect(235, 300, 50, 18));
        lb_Temp_Lect_TEAEG->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TEAEG->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TEAEG->setFont(font2);
        lb_Temp_Lect_TEAEG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TEAEG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Descr_15 = new QLabel(Temperaturas);
        Descr_15->setObjectName(QString::fromUtf8("Descr_15"));
        Descr_15->setGeometry(QRect(25, 300, 225, 18));
        Descr_15->setMinimumSize(QSize(225, 18));
        Descr_15->setMaximumSize(QSize(225, 18));
        Descr_15->setFont(font2);
        Descr_15->setLayoutDirection(Qt::LeftToRight);
        Descr_15->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Unit_TEAEG = new QLabel(Temperaturas);
        lb_Temp_Unit_TEAEG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TEAEG"));
        lb_Temp_Unit_TEAEG->setGeometry(QRect(291, 300, 40, 18));
        lb_Temp_Unit_TEAEG->setFont(font1);
        lb_Temp_Unit_TEAEG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TEAEG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Descr_14 = new QLabel(Temperaturas);
        Descr_14->setObjectName(QString::fromUtf8("Descr_14"));
        Descr_14->setGeometry(QRect(25, 285, 225, 18));
        Descr_14->setMinimumSize(QSize(225, 18));
        Descr_14->setMaximumSize(QSize(225, 18));
        Descr_14->setFont(font2);
        Descr_14->setLayoutDirection(Qt::LeftToRight);
        Descr_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Unit_TSAG = new QLabel(Temperaturas);
        lb_Temp_Unit_TSAG->setObjectName(QString::fromUtf8("lb_Temp_Unit_TSAG"));
        lb_Temp_Unit_TSAG->setGeometry(QRect(291, 285, 40, 18));
        lb_Temp_Unit_TSAG->setFont(font1);
        lb_Temp_Unit_TSAG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Unit_TSAG->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lb_Temp_Lect_TSAG = new QLabel(Temperaturas);
        lb_Temp_Lect_TSAG->setObjectName(QString::fromUtf8("lb_Temp_Lect_TSAG"));
        lb_Temp_Lect_TSAG->setGeometry(QRect(235, 285, 50, 18));
        lb_Temp_Lect_TSAG->setMinimumSize(QSize(50, 18));
        lb_Temp_Lect_TSAG->setMaximumSize(QSize(50, 18));
        lb_Temp_Lect_TSAG->setFont(font2);
        lb_Temp_Lect_TSAG->setLayoutDirection(Qt::LeftToRight);
        lb_Temp_Lect_TSAG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUnit3 = new QLabel(D7);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(833, 647, 190, 15));
        QFont font4;
        font4.setBold(true);
        font4.setWeight(75);
        lbUnit3->setFont(font4);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        btnIMPPant = new QPushButton(D7);
        btnIMPPant->setObjectName(QString::fromUtf8("btnIMPPant"));
        btnIMPPant->setGeometry(QRect(10, 632, 134, 23));
        QFont font5;
        font5.setPointSize(8);
        font5.setBold(true);
        font5.setWeight(75);
        btnIMPPant->setFont(font5);
        btnIMPPant->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));

        retranslateUi(D7);

        QMetaObject::connectSlotsByName(D7);
    } // setupUi

    void retranslateUi(QWidget *D7)
    {
        D7->setWindowTitle(QApplication::translate("D7", "Form", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("D7", "Vibraci\303\263n", 0, QApplication::UnicodeUTF8));
        lb_Vib_Unit_DE_X->setText(QApplication::translate("D7", "MILS", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_DE_X->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_45->setText(QApplication::translate("D7", "DE_X - Vib. Flech. X DE Gen.", 0, QApplication::UnicodeUTF8));
        lb_Vib_Unit_NDE_X->setText(QApplication::translate("D7", "MILS", 0, QApplication::UnicodeUTF8));
        Descr_47->setText(QApplication::translate("D7", "NDE_X - Vib. Flech. X NDE Gen.", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_NDE_X->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Vib_Unit_DE_Y->setText(QApplication::translate("D7", "MILS", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_DE_Y->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_46->setText(QApplication::translate("D7", "DE_Y - Vib. Flech. Y DE Gen.", 0, QApplication::UnicodeUTF8));
        lb_Vib_Unit_NDE_Y->setText(QApplication::translate("D7", "MILS", 0, QApplication::UnicodeUTF8));
        lb_Vib_Lect_NDE_Y->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_48->setText(QApplication::translate("D7", "NDE_Y - Vib. Flech. Y NDE Gen.", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("D7", "Potencia", 0, QApplication::UnicodeUTF8));
        lb_Pot_Unit_PAG->setText(QApplication::translate("D7", "MW", 0, QApplication::UnicodeUTF8));
        lb_Pot_Lect_PAG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_49->setText(QApplication::translate("D7", "Potencia Activa Gen.", 0, QApplication::UnicodeUTF8));
        lb_Pot_Unit_EIG->setText(QString());
        lb_Pot_Lect_EIG->setText(QString());
        Descr_50->setText(QApplication::translate("D7", "Estado Interrupter. Gen.", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("D7", "Modo", 0, QApplication::UnicodeUTF8));
        lb_Modo_Unit_DI->setText(QString());
        lb_Modo_Lect_DI->setText(QString());
        Descr_33->setText(QApplication::translate("D7", "Droop/Isocr", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("D7", "Lecturas DMMF", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_FGen->setText(QApplication::translate("D7", "Hz", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_FGen->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_26->setText(QApplication::translate("D7", "Frecuencia Generador", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_AVT->setText(QApplication::translate("D7", "MVA", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_AVT->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_25->setText(QApplication::translate("D7", "Amp. Voltaje Total", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFB->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_23->setText(QApplication::translate("D7", "Corriente Fase B", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_CFB->setText(QApplication::translate("D7", "A", 0, QApplication::UnicodeUTF8));
        Descr_22->setText(QApplication::translate("D7", "Corriente Fase A", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFA->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_CFA->setText(QApplication::translate("D7", "A", 0, QApplication::UnicodeUTF8));
        Descr_24->setText(QApplication::translate("D7", "Corriente Fase C", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_CFC->setText(QApplication::translate("D7", "A", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_CFC->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_FPGen->setText(QString());
        lb_DMMF_Lect_FPGen->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_27->setText(QApplication::translate("D7", "Factor Potencia Gen.", 0, QApplication::UnicodeUTF8));
        Descr_16->setText(QApplication::translate("D7", "Voltaje Bus", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VBus->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_VBus->setText(QApplication::translate("D7", "kV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_VFAB->setText(QApplication::translate("D7", "kV", 0, QApplication::UnicodeUTF8));
        Descr_18->setText(QApplication::translate("D7", "Voltaje Fases A-B", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFAB->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_TMVAR->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_21->setText(QApplication::translate("D7", "Total MVAR Gen.", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_TMVAR->setText(QApplication::translate("D7", "MVAr", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_VFBC->setText(QApplication::translate("D7", "kV", 0, QApplication::UnicodeUTF8));
        Descr_19->setText(QApplication::translate("D7", "Voltaje Fases B-C", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFBC->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_20->setText(QApplication::translate("D7", "Voltaje Fases A-C", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_VFAC->setText(QApplication::translate("D7", "kV", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_VFAC->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_17->setText(QApplication::translate("D7", "Frecuencia Bus", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Lect_FBus->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_DMMF_Unit_FBus->setText(QApplication::translate("D7", "Hz", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("D7", "Lecturas Sistema", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_VBus->setText(QApplication::translate("D7", "kVAC", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VBus->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_30->setText(QApplication::translate("D7", "Voltaje Bus", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_VCE->setText(QApplication::translate("D7", "VDC", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VCE->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_28->setText(QApplication::translate("D7", "Volt. Campo Excitad.", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_VG->setText(QApplication::translate("D7", "MW", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_VG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_31->setText(QApplication::translate("D7", "Vatios Generador", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_ACE->setText(QApplication::translate("D7", "ADC", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_ACE->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_29->setText(QApplication::translate("D7", "Amps. Campo Excitad.", 0, QApplication::UnicodeUTF8));
        lb_LS_Unit_FBus->setText(QApplication::translate("D7", "Hz", 0, QApplication::UnicodeUTF8));
        lb_LS_Lect_FBus->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_43->setText(QApplication::translate("D7", "Frecuencia bus", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("D7", "Estado Motor", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_VCBG->setText(QString());
        lb_EM_Lect_VCBG->setText(QString());
        Descr_34->setText(QApplication::translate("D7", "Vent. B Carcasa Gen.", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_BALACG->setText(QString());
        lb_EM_Lect_BALACG->setText(QString());
        Descr_35->setText(QApplication::translate("D7", "Bomba Ace. Lub. AC Gen.", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_BAEG->setText(QString());
        lb_EM_Lect_BAEG->setText(QString());
        Descr_36->setText(QApplication::translate("D7", "Bomba Ace. Elev. Gen.", 0, QApplication::UnicodeUTF8));
        lb_EM_Unit_VCAG->setText(QString());
        lb_EM_Lect_VCAG->setText(QString());
        Descr_32->setText(QApplication::translate("D7", "Vent. A Carcasa Gen.", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("D7", "Lubricaci\303\263n de la Gen.", 0, QApplication::UnicodeUTF8));
        lb_LG_Unit_NTALG->setText(QApplication::translate("D7", "%", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_NTALG->setText(QString());
        Descr_42->setText(QApplication::translate("D7", "Nivel Tanque Aceite Lub. Gen.", 0, QApplication::UnicodeUTF8));
        lb_LG_Unit_PSLDGA->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        Descr_38->setText(QApplication::translate("D7", "Pres. Sumin. Lub. Del. Gen. A", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDGA->setText(QString());
        lb_LG_Unit_PSLDGB->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDGB->setText(QString());
        Descr_39->setText(QApplication::translate("D7", "Pres. Sumin. Lub. Del. Gen. B", 0, QApplication::UnicodeUTF8));
        lb_LG_Unit_EBAAP->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_EBAAP->setText(QString());
        Descr_41->setText(QApplication::translate("D7", "Entrad. Bomba Ace. Aljib. Pres.", 0, QApplication::UnicodeUTF8));
        Descr_37->setText(QApplication::translate("D7", "Pres. Sumin. Aceit. Lub. Gen.", 0, QApplication::UnicodeUTF8));
        lb_LG_Unit_PSALG->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSALG->setText(QString());
        lb_LG_Unit_PSLDG->setText(QApplication::translate("D7", "PSIG", 0, QApplication::UnicodeUTF8));
        lb_LG_Lect_PSLDG->setText(QString());
        Descr_40->setText(QApplication::translate("D7", "Pres. Sumin. Lub. Del. Gen.", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("D7", "Temperaturas", 0, QApplication::UnicodeUTF8));
        Descr_01->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE U1", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseU1->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseU1->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseU2->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_2->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE U2", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseU2->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCIIB->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TCIIB->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_12->setText(QApplication::translate("D7", "Temp. Cojinete de Impulso (DE) IB", 0, QApplication::UnicodeUTF8));
        Descr_9->setText(QApplication::translate("D7", "Temp. Cojinete Gen. - DE", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCGDE->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TCGDE->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseW1->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseW1->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_5->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE W1", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseV1->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_3->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE V1", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseV1->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_6->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE W2", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseW2->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseW2->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_7->setText(QApplication::translate("D7", "Temp. Prom. Estator Gen.", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TPEG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TPEG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_FaseV2->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_FaseV2->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_4->setText(QApplication::translate("D7", "Temp. Estator Gen. - FASE V2", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TCIOB->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCIOB->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_11->setText(QApplication::translate("D7", "Temp. Cojinete de Impulso (DE) OB", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TSALG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TSALG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_8->setText(QApplication::translate("D7", "Temp. Sumini. Aceite Lub. Gen.", 0, QApplication::UnicodeUTF8));
        Descr_10->setText(QApplication::translate("D7", "Temp. Cojinete Gen. - NDE", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TCGNDE->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TCGNDE->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TACG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_13->setText(QApplication::translate("D7", "Temp. Air. Cuarto Gen.", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TACG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TEAEG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        Descr_15->setText(QApplication::translate("D7", "Temp. Escape Air. Exitad. Gen.", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TEAEG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        Descr_14->setText(QApplication::translate("D7", "Temp. Salida Air. Gen.", 0, QApplication::UnicodeUTF8));
        lb_Temp_Unit_TSAG->setText(QApplication::translate("D7", "\302\272F", 0, QApplication::UnicodeUTF8));
        lb_Temp_Lect_TSAG->setText(QApplication::translate("D7", "0", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("D7", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btnIMPPant->setText(QApplication::translate("D7", "IMP PANT", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class D7: public Ui_D7 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_D7_H
