/********************************************************************************
** Form generated from reading UI file 'd1.ui'
**
** Created: Sun 13. Oct 17:33:24 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_D1_H
#define UI_D1_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "awmultiobject.h"

QT_BEGIN_NAMESPACE

class Ui_D1
{
public:
    QLabel *lbIMGFondo;
    QLabel *lbInd_1;
    QLabel *lbInd_2;
    QLabel *lbInd_3;
    QLabel *lbInd_4;
    QLabel *lbInd_5;
    QLabel *lbInd_6;
    QLabel *lbInd_7;
    QLabel *lbInd_8;
    QLabel *lbInd_9;
    QLabel *lbInd_10;
    QLabel *lbInd_11;
    QLabel *lbInd_12;
    QLabel *lbInd_13;
    QLabel *lbInd_14;
    QLabel *lbInd_15;
    QLabel *lbInd_16;
    QLabel *lbInd_17;
    QLabel *lbInd_18;
    QLabel *lbInd_19;
    QLabel *lbInd_20;
    QLabel *lbInd_21;
    QLabel *lbInd_22;
    QLabel *lbInd_23;
    QLabel *lbInd_24;
    QLabel *lbInd_25;
    QLabel *lbInd_26;
    QLabel *lbInd_27;
    QLabel *lbInd_28;
    QLabel *lbInd_29;
    QLabel *lbInd_30;
    QLabel *lbInd_31;
    QLabel *lbInd_32;
    AWMultiObject *WCuadrado_1;
    AWMultiObject *WCuadrado_2;
    AWMultiObject *WCuadrado_3;
    AWMultiObject *WCuadrado_4;
    AWMultiObject *WCuadrado_5;
    AWMultiObject *WCuadrado_7;
    AWMultiObject *WCuadrado_8;
    AWMultiObject *WCuadrado_9;
    AWMultiObject *WCuadrado_10;
    AWMultiObject *WCuadrado_11;
    AWMultiObject *WCuadrado_12;
    AWMultiObject *WCuadrado_13;
    AWMultiObject *WCuadrado_14;
    AWMultiObject *WCuadrado_15;
    AWMultiObject *WCuadrado_16;
    AWMultiObject *WCuadrado_17;
    AWMultiObject *WCuadrado_18;
    QPushButton *btnRed_1;
    QPushButton *btnRed_2;
    QPushButton *btnRed_3;
    QPushButton *btnRed_4;
    QLabel *lbUnit3;
    QPushButton *btind1;
    QPushButton *btind1_2;
    QPushButton *btind1_3;
    QPushButton *btind1_4;
    QPushButton *btind1_5;
    QPushButton *btind1_6;
    QPushButton *btind1_7;
    QPushButton *btind1_8;
    QPushButton *btind1_9;
    QPushButton *btind1_10;
    QPushButton *btind1_11;
    QPushButton *btind1_12;
    QPushButton *btind1_13;
    QPushButton *btind1_14;
    QPushButton *btind1_15;
    QPushButton *btind1_16;
    QPushButton *btind1_17;
    QPushButton *btind1_18;
    QPushButton *btind1_19;
    QPushButton *btind1_20;
    QPushButton *btind1_21;
    QPushButton *btind1_22;
    QPushButton *btind1_23;
    QPushButton *btind1_24;

    void setupUi(QWidget *D1)
    {
        if (D1->objectName().isEmpty())
            D1->setObjectName(QString::fromUtf8("D1"));
        D1->resize(1024, 662);
        D1->setStyleSheet(QString::fromUtf8("background-color: rgb(136, 136, 136);"));
        lbIMGFondo = new QLabel(D1);
        lbIMGFondo->setObjectName(QString::fromUtf8("lbIMGFondo"));
        lbIMGFondo->setGeometry(QRect(0, 0, 1024, 664));
        lbIMGFondo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/PNG/D1.png")));
        lbIMGFondo->setScaledContents(true);
        lbInd_1 = new QLabel(D1);
        lbInd_1->setObjectName(QString::fromUtf8("lbInd_1"));
        lbInd_1->setGeometry(QRect(79, 63, 21, 21));
        QFont font;
        font.setFamily(QString::fromUtf8("Verdana"));
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        lbInd_1->setFont(font);
        lbInd_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_2 = new QLabel(D1);
        lbInd_2->setObjectName(QString::fromUtf8("lbInd_2"));
        lbInd_2->setGeometry(QRect(190, 62, 21, 21));
        lbInd_2->setFont(font);
        lbInd_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_3 = new QLabel(D1);
        lbInd_3->setObjectName(QString::fromUtf8("lbInd_3"));
        lbInd_3->setGeometry(QRect(220, 62, 16, 21));
        lbInd_3->setFont(font);
        lbInd_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_4 = new QLabel(D1);
        lbInd_4->setObjectName(QString::fromUtf8("lbInd_4"));
        lbInd_4->setGeometry(QRect(255, 62, 21, 21));
        lbInd_4->setFont(font);
        lbInd_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_5 = new QLabel(D1);
        lbInd_5->setObjectName(QString::fromUtf8("lbInd_5"));
        lbInd_5->setGeometry(QRect(290, 62, 21, 21));
        lbInd_5->setFont(font);
        lbInd_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_6 = new QLabel(D1);
        lbInd_6->setObjectName(QString::fromUtf8("lbInd_6"));
        lbInd_6->setGeometry(QRect(330, 62, 21, 21));
        lbInd_6->setFont(font);
        lbInd_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_7 = new QLabel(D1);
        lbInd_7->setObjectName(QString::fromUtf8("lbInd_7"));
        lbInd_7->setGeometry(QRect(360, 62, 21, 21));
        lbInd_7->setFont(font);
        lbInd_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_8 = new QLabel(D1);
        lbInd_8->setObjectName(QString::fromUtf8("lbInd_8"));
        lbInd_8->setGeometry(QRect(390, 62, 21, 21));
        lbInd_8->setFont(font);
        lbInd_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_9 = new QLabel(D1);
        lbInd_9->setObjectName(QString::fromUtf8("lbInd_9"));
        lbInd_9->setGeometry(QRect(430, 62, 21, 21));
        lbInd_9->setFont(font);
        lbInd_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_10 = new QLabel(D1);
        lbInd_10->setObjectName(QString::fromUtf8("lbInd_10"));
        lbInd_10->setGeometry(QRect(460, 62, 21, 21));
        lbInd_10->setFont(font);
        lbInd_10->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_11 = new QLabel(D1);
        lbInd_11->setObjectName(QString::fromUtf8("lbInd_11"));
        lbInd_11->setGeometry(QRect(70, 315, 31, 21));
        lbInd_11->setFont(font);
        lbInd_11->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_12 = new QLabel(D1);
        lbInd_12->setObjectName(QString::fromUtf8("lbInd_12"));
        lbInd_12->setGeometry(QRect(180, 315, 31, 21));
        lbInd_12->setFont(font);
        lbInd_12->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_13 = new QLabel(D1);
        lbInd_13->setObjectName(QString::fromUtf8("lbInd_13"));
        lbInd_13->setGeometry(QRect(220, 315, 31, 21));
        lbInd_13->setFont(font);
        lbInd_13->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_14 = new QLabel(D1);
        lbInd_14->setObjectName(QString::fromUtf8("lbInd_14"));
        lbInd_14->setGeometry(QRect(260, 315, 31, 21));
        lbInd_14->setFont(font);
        lbInd_14->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_15 = new QLabel(D1);
        lbInd_15->setObjectName(QString::fromUtf8("lbInd_15"));
        lbInd_15->setGeometry(QRect(290, 315, 31, 21));
        lbInd_15->setFont(font);
        lbInd_15->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_16 = new QLabel(D1);
        lbInd_16->setObjectName(QString::fromUtf8("lbInd_16"));
        lbInd_16->setGeometry(QRect(325, 315, 31, 21));
        lbInd_16->setFont(font);
        lbInd_16->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_17 = new QLabel(D1);
        lbInd_17->setObjectName(QString::fromUtf8("lbInd_17"));
        lbInd_17->setGeometry(QRect(355, 315, 31, 21));
        lbInd_17->setFont(font);
        lbInd_17->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_18 = new QLabel(D1);
        lbInd_18->setObjectName(QString::fromUtf8("lbInd_18"));
        lbInd_18->setGeometry(QRect(390, 315, 31, 21));
        lbInd_18->setFont(font);
        lbInd_18->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_19 = new QLabel(D1);
        lbInd_19->setObjectName(QString::fromUtf8("lbInd_19"));
        lbInd_19->setGeometry(QRect(425, 315, 31, 21));
        lbInd_19->setFont(font);
        lbInd_19->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_20 = new QLabel(D1);
        lbInd_20->setObjectName(QString::fromUtf8("lbInd_20"));
        lbInd_20->setGeometry(QRect(470, 315, 31, 21));
        lbInd_20->setFont(font);
        lbInd_20->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_21 = new QLabel(D1);
        lbInd_21->setObjectName(QString::fromUtf8("lbInd_21"));
        lbInd_21->setGeometry(QRect(80, 365, 31, 21));
        lbInd_21->setFont(font);
        lbInd_21->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_22 = new QLabel(D1);
        lbInd_22->setObjectName(QString::fromUtf8("lbInd_22"));
        lbInd_22->setGeometry(QRect(110, 365, 31, 21));
        lbInd_22->setFont(font);
        lbInd_22->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_23 = new QLabel(D1);
        lbInd_23->setObjectName(QString::fromUtf8("lbInd_23"));
        lbInd_23->setGeometry(QRect(180, 365, 31, 21));
        lbInd_23->setFont(font);
        lbInd_23->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_24 = new QLabel(D1);
        lbInd_24->setObjectName(QString::fromUtf8("lbInd_24"));
        lbInd_24->setGeometry(QRect(220, 365, 31, 20));
        lbInd_24->setFont(font);
        lbInd_24->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_25 = new QLabel(D1);
        lbInd_25->setObjectName(QString::fromUtf8("lbInd_25"));
        lbInd_25->setGeometry(QRect(255, 365, 31, 20));
        lbInd_25->setFont(font);
        lbInd_25->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_26 = new QLabel(D1);
        lbInd_26->setObjectName(QString::fromUtf8("lbInd_26"));
        lbInd_26->setGeometry(QRect(470, 365, 31, 20));
        lbInd_26->setFont(font);
        lbInd_26->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_27 = new QLabel(D1);
        lbInd_27->setObjectName(QString::fromUtf8("lbInd_27"));
        lbInd_27->setGeometry(QRect(75, 617, 31, 20));
        lbInd_27->setFont(font);
        lbInd_27->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_28 = new QLabel(D1);
        lbInd_28->setObjectName(QString::fromUtf8("lbInd_28"));
        lbInd_28->setGeometry(QRect(118, 617, 31, 20));
        lbInd_28->setFont(font);
        lbInd_28->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_29 = new QLabel(D1);
        lbInd_29->setObjectName(QString::fromUtf8("lbInd_29"));
        lbInd_29->setGeometry(QRect(185, 617, 31, 20));
        lbInd_29->setFont(font);
        lbInd_29->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_30 = new QLabel(D1);
        lbInd_30->setObjectName(QString::fromUtf8("lbInd_30"));
        lbInd_30->setGeometry(QRect(220, 617, 31, 20));
        lbInd_30->setFont(font);
        lbInd_30->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_31 = new QLabel(D1);
        lbInd_31->setObjectName(QString::fromUtf8("lbInd_31"));
        lbInd_31->setGeometry(QRect(252, 617, 31, 20));
        lbInd_31->setFont(font);
        lbInd_31->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbInd_32 = new QLabel(D1);
        lbInd_32->setObjectName(QString::fromUtf8("lbInd_32"));
        lbInd_32->setGeometry(QRect(465, 617, 31, 20));
        lbInd_32->setFont(font);
        lbInd_32->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        WCuadrado_1 = new AWMultiObject(D1);
        WCuadrado_1->setObjectName(QString::fromUtf8("WCuadrado_1"));
        WCuadrado_1->setGeometry(QRect(108, 490, 25, 25));
        WCuadrado_1->setElementType(AWMultiObject::SQUARE);
        WCuadrado_1->setOnColor(AWMultiObject::Grey);
        WCuadrado_1->setOffColor(AWMultiObject::Green);
        WCuadrado_2 = new AWMultiObject(D1);
        WCuadrado_2->setObjectName(QString::fromUtf8("WCuadrado_2"));
        WCuadrado_2->setGeometry(QRect(180, 490, 25, 25));
        WCuadrado_2->setElementType(AWMultiObject::SQUARE);
        WCuadrado_2->setOnColor(AWMultiObject::Grey);
        WCuadrado_2->setOffColor(AWMultiObject::Green);
        WCuadrado_3 = new AWMultiObject(D1);
        WCuadrado_3->setObjectName(QString::fromUtf8("WCuadrado_3"));
        WCuadrado_3->setGeometry(QRect(215, 490, 25, 25));
        WCuadrado_3->setElementType(AWMultiObject::SQUARE);
        WCuadrado_3->setOnColor(AWMultiObject::Grey);
        WCuadrado_3->setOffColor(AWMultiObject::Green);
        WCuadrado_4 = new AWMultiObject(D1);
        WCuadrado_4->setObjectName(QString::fromUtf8("WCuadrado_4"));
        WCuadrado_4->setGeometry(QRect(250, 490, 25, 25));
        WCuadrado_4->setElementType(AWMultiObject::SQUARE);
        WCuadrado_4->setOnColor(AWMultiObject::Grey);
        WCuadrado_4->setOffColor(AWMultiObject::Green);
        WCuadrado_5 = new AWMultiObject(D1);
        WCuadrado_5->setObjectName(QString::fromUtf8("WCuadrado_5"));
        WCuadrado_5->setGeometry(QRect(179, 193, 25, 25));
        WCuadrado_5->setElementType(AWMultiObject::SQUARE);
        WCuadrado_5->setOnColor(AWMultiObject::Grey);
        WCuadrado_5->setOffColor(AWMultiObject::Green);
        WCuadrado_7 = new AWMultiObject(D1);
        WCuadrado_7->setObjectName(QString::fromUtf8("WCuadrado_7"));
        WCuadrado_7->setGeometry(QRect(210, 193, 25, 25));
        WCuadrado_7->setElementType(AWMultiObject::SQUARE);
        WCuadrado_7->setOnColor(AWMultiObject::Grey);
        WCuadrado_7->setOffColor(AWMultiObject::Green);
        WCuadrado_8 = new AWMultiObject(D1);
        WCuadrado_8->setObjectName(QString::fromUtf8("WCuadrado_8"));
        WCuadrado_8->setGeometry(QRect(248, 193, 25, 25));
        WCuadrado_8->setElementType(AWMultiObject::SQUARE);
        WCuadrado_8->setOnColor(AWMultiObject::Grey);
        WCuadrado_8->setOffColor(AWMultiObject::Green);
        WCuadrado_9 = new AWMultiObject(D1);
        WCuadrado_9->setObjectName(QString::fromUtf8("WCuadrado_9"));
        WCuadrado_9->setGeometry(QRect(283, 193, 25, 25));
        WCuadrado_9->setElementType(AWMultiObject::SQUARE);
        WCuadrado_9->setOnColor(AWMultiObject::Grey);
        WCuadrado_9->setOffColor(AWMultiObject::Green);
        WCuadrado_10 = new AWMultiObject(D1);
        WCuadrado_10->setObjectName(QString::fromUtf8("WCuadrado_10"));
        WCuadrado_10->setGeometry(QRect(320, 193, 25, 25));
        WCuadrado_10->setElementType(AWMultiObject::SQUARE);
        WCuadrado_10->setOnColor(AWMultiObject::Grey);
        WCuadrado_10->setOffColor(AWMultiObject::Green);
        WCuadrado_11 = new AWMultiObject(D1);
        WCuadrado_11->setObjectName(QString::fromUtf8("WCuadrado_11"));
        WCuadrado_11->setGeometry(QRect(354, 193, 25, 25));
        WCuadrado_11->setElementType(AWMultiObject::SQUARE);
        WCuadrado_11->setOnColor(AWMultiObject::Grey);
        WCuadrado_11->setOffColor(AWMultiObject::Green);
        WCuadrado_12 = new AWMultiObject(D1);
        WCuadrado_12->setObjectName(QString::fromUtf8("WCuadrado_12"));
        WCuadrado_12->setGeometry(QRect(390, 193, 25, 25));
        WCuadrado_12->setElementType(AWMultiObject::SQUARE);
        WCuadrado_12->setOnColor(AWMultiObject::Grey);
        WCuadrado_12->setOffColor(AWMultiObject::Green);
        WCuadrado_13 = new AWMultiObject(D1);
        WCuadrado_13->setObjectName(QString::fromUtf8("WCuadrado_13"));
        WCuadrado_13->setGeometry(QRect(460, 193, 25, 25));
        WCuadrado_13->setElementType(AWMultiObject::SQUARE);
        WCuadrado_13->setOnColor(AWMultiObject::Grey);
        WCuadrado_13->setOffColor(AWMultiObject::Green);
        WCuadrado_14 = new AWMultiObject(D1);
        WCuadrado_14->setObjectName(QString::fromUtf8("WCuadrado_14"));
        WCuadrado_14->setGeometry(QRect(460, 396, 25, 25));
        WCuadrado_14->setElementType(AWMultiObject::SQUARE);
        WCuadrado_14->setOnColor(AWMultiObject::Grey);
        WCuadrado_14->setOffColor(AWMultiObject::Blue);
        WCuadrado_15 = new AWMultiObject(D1);
        WCuadrado_15->setObjectName(QString::fromUtf8("WCuadrado_15"));
        WCuadrado_15->setGeometry(QRect(460, 421, 25, 25));
        WCuadrado_15->setElementType(AWMultiObject::SQUARE);
        WCuadrado_15->setOnColor(AWMultiObject::Grey);
        WCuadrado_15->setOffColor(AWMultiObject::Blue);
        WCuadrado_16 = new AWMultiObject(D1);
        WCuadrado_16->setObjectName(QString::fromUtf8("WCuadrado_16"));
        WCuadrado_16->setGeometry(QRect(460, 444, 25, 25));
        WCuadrado_16->setElementType(AWMultiObject::SQUARE);
        WCuadrado_16->setOnColor(AWMultiObject::Grey);
        WCuadrado_16->setOffColor(AWMultiObject::Blue);
        WCuadrado_17 = new AWMultiObject(D1);
        WCuadrado_17->setObjectName(QString::fromUtf8("WCuadrado_17"));
        WCuadrado_17->setGeometry(QRect(460, 470, 25, 25));
        WCuadrado_17->setElementType(AWMultiObject::SQUARE);
        WCuadrado_17->setOnColor(AWMultiObject::Grey);
        WCuadrado_17->setOffColor(AWMultiObject::Blue);
        WCuadrado_18 = new AWMultiObject(D1);
        WCuadrado_18->setObjectName(QString::fromUtf8("WCuadrado_18"));
        WCuadrado_18->setGeometry(QRect(460, 496, 25, 25));
        WCuadrado_18->setElementType(AWMultiObject::SQUARE);
        WCuadrado_18->setOnColor(AWMultiObject::Grey);
        WCuadrado_18->setOffColor(AWMultiObject::Green);
        btnRed_1 = new QPushButton(D1);
        btnRed_1->setObjectName(QString::fromUtf8("btnRed_1"));
        btnRed_1->setGeometry(QRect(625, 480, 190, 31));
        QFont font1;
        font1.setPointSize(12);
        font1.setBold(true);
        font1.setWeight(75);
        btnRed_1->setFont(font1);
        btnRed_1->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnRed_2 = new QPushButton(D1);
        btnRed_2->setObjectName(QString::fromUtf8("btnRed_2"));
        btnRed_2->setGeometry(QRect(625, 513, 190, 31));
        btnRed_2->setFont(font1);
        btnRed_2->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnRed_3 = new QPushButton(D1);
        btnRed_3->setObjectName(QString::fromUtf8("btnRed_3"));
        btnRed_3->setGeometry(QRect(625, 548, 190, 31));
        btnRed_3->setFont(font1);
        btnRed_3->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnRed_4 = new QPushButton(D1);
        btnRed_4->setObjectName(QString::fromUtf8("btnRed_4"));
        btnRed_4->setGeometry(QRect(780, 620, 143, 21));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        btnRed_4->setFont(font2);
        btnRed_4->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbUnit3 = new QLabel(D1);
        lbUnit3->setObjectName(QString::fromUtf8("lbUnit3"));
        lbUnit3->setGeometry(QRect(837, 647, 190, 15));
        lbUnit3->setFont(font2);
        lbUnit3->setStyleSheet(QString::fromUtf8("background-color: rgb(175, 175, 175);"));
        btind1 = new QPushButton(D1);
        btind1->setObjectName(QString::fromUtf8("btind1"));
        btind1->setGeometry(QRect(69, 50, 36, 301));
        btind1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_2 = new QPushButton(D1);
        btind1_2->setObjectName(QString::fromUtf8("btind1_2"));
        btind1_2->setGeometry(QRect(104, 50, 36, 301));
        btind1_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_3 = new QPushButton(D1);
        btind1_3->setObjectName(QString::fromUtf8("btind1_3"));
        btind1_3->setGeometry(QRect(175, 50, 36, 301));
        btind1_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_4 = new QPushButton(D1);
        btind1_4->setObjectName(QString::fromUtf8("btind1_4"));
        btind1_4->setGeometry(QRect(140, 50, 36, 301));
        btind1_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_5 = new QPushButton(D1);
        btind1_5->setObjectName(QString::fromUtf8("btind1_5"));
        btind1_5->setGeometry(QRect(318, 50, 36, 301));
        btind1_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_6 = new QPushButton(D1);
        btind1_6->setObjectName(QString::fromUtf8("btind1_6"));
        btind1_6->setGeometry(QRect(211, 50, 36, 301));
        btind1_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_7 = new QPushButton(D1);
        btind1_7->setObjectName(QString::fromUtf8("btind1_7"));
        btind1_7->setGeometry(QRect(283, 50, 36, 301));
        btind1_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_8 = new QPushButton(D1);
        btind1_8->setObjectName(QString::fromUtf8("btind1_8"));
        btind1_8->setGeometry(QRect(247, 50, 36, 301));
        btind1_8->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_9 = new QPushButton(D1);
        btind1_9->setObjectName(QString::fromUtf8("btind1_9"));
        btind1_9->setGeometry(QRect(460, 50, 36, 301));
        btind1_9->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_10 = new QPushButton(D1);
        btind1_10->setObjectName(QString::fromUtf8("btind1_10"));
        btind1_10->setGeometry(QRect(354, 50, 36, 301));
        btind1_10->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_11 = new QPushButton(D1);
        btind1_11->setObjectName(QString::fromUtf8("btind1_11"));
        btind1_11->setGeometry(QRect(425, 50, 36, 301));
        btind1_11->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_12 = new QPushButton(D1);
        btind1_12->setObjectName(QString::fromUtf8("btind1_12"));
        btind1_12->setGeometry(QRect(389, 50, 36, 301));
        btind1_12->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_13 = new QPushButton(D1);
        btind1_13->setObjectName(QString::fromUtf8("btind1_13"));
        btind1_13->setGeometry(QRect(460, 350, 36, 301));
        btind1_13->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_14 = new QPushButton(D1);
        btind1_14->setObjectName(QString::fromUtf8("btind1_14"));
        btind1_14->setGeometry(QRect(104, 350, 36, 301));
        btind1_14->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_15 = new QPushButton(D1);
        btind1_15->setObjectName(QString::fromUtf8("btind1_15"));
        btind1_15->setGeometry(QRect(69, 350, 36, 301));
        btind1_15->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_16 = new QPushButton(D1);
        btind1_16->setObjectName(QString::fromUtf8("btind1_16"));
        btind1_16->setGeometry(QRect(211, 350, 36, 301));
        btind1_16->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_17 = new QPushButton(D1);
        btind1_17->setObjectName(QString::fromUtf8("btind1_17"));
        btind1_17->setGeometry(QRect(425, 350, 36, 301));
        btind1_17->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_18 = new QPushButton(D1);
        btind1_18->setObjectName(QString::fromUtf8("btind1_18"));
        btind1_18->setGeometry(QRect(283, 350, 36, 301));
        btind1_18->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_19 = new QPushButton(D1);
        btind1_19->setObjectName(QString::fromUtf8("btind1_19"));
        btind1_19->setGeometry(QRect(318, 350, 36, 301));
        btind1_19->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_20 = new QPushButton(D1);
        btind1_20->setObjectName(QString::fromUtf8("btind1_20"));
        btind1_20->setGeometry(QRect(354, 350, 36, 301));
        btind1_20->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_21 = new QPushButton(D1);
        btind1_21->setObjectName(QString::fromUtf8("btind1_21"));
        btind1_21->setGeometry(QRect(140, 350, 36, 301));
        btind1_21->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_22 = new QPushButton(D1);
        btind1_22->setObjectName(QString::fromUtf8("btind1_22"));
        btind1_22->setGeometry(QRect(175, 350, 36, 301));
        btind1_22->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_23 = new QPushButton(D1);
        btind1_23->setObjectName(QString::fromUtf8("btind1_23"));
        btind1_23->setGeometry(QRect(247, 350, 36, 301));
        btind1_23->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        btind1_24 = new QPushButton(D1);
        btind1_24->setObjectName(QString::fromUtf8("btind1_24"));
        btind1_24->setGeometry(QRect(389, 350, 36, 301));
        btind1_24->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbIMGFondo->raise();
        btind1_20->raise();
        btind1_17->raise();
        btind1_23->raise();
        btind1_16->raise();
        btind1_21->raise();
        btind1_22->raise();
        btind1_15->raise();
        btind1_24->raise();
        btind1_18->raise();
        btind1_19->raise();
        btind1_13->raise();
        btind1_14->raise();
        btind1_12->raise();
        btind1_9->raise();
        btind1_10->raise();
        btind1_11->raise();
        btind1_6->raise();
        btind1_8->raise();
        btind1_7->raise();
        btind1_5->raise();
        btind1_3->raise();
        btind1_4->raise();
        btind1_2->raise();
        btind1->raise();
        lbInd_1->raise();
        lbInd_2->raise();
        lbInd_3->raise();
        lbInd_4->raise();
        lbInd_5->raise();
        lbInd_6->raise();
        lbInd_7->raise();
        lbInd_8->raise();
        lbInd_9->raise();
        lbInd_10->raise();
        lbInd_11->raise();
        lbInd_12->raise();
        lbInd_13->raise();
        lbInd_14->raise();
        lbInd_15->raise();
        lbInd_16->raise();
        lbInd_17->raise();
        lbInd_18->raise();
        lbInd_19->raise();
        lbInd_20->raise();
        lbInd_21->raise();
        lbInd_22->raise();
        lbInd_23->raise();
        lbInd_24->raise();
        lbInd_25->raise();
        lbInd_26->raise();
        lbInd_27->raise();
        lbInd_28->raise();
        lbInd_29->raise();
        lbInd_30->raise();
        lbInd_31->raise();
        lbInd_32->raise();
        WCuadrado_1->raise();
        WCuadrado_2->raise();
        WCuadrado_3->raise();
        WCuadrado_4->raise();
        WCuadrado_5->raise();
        WCuadrado_7->raise();
        WCuadrado_8->raise();
        WCuadrado_9->raise();
        WCuadrado_10->raise();
        WCuadrado_11->raise();
        WCuadrado_12->raise();
        WCuadrado_13->raise();
        WCuadrado_14->raise();
        WCuadrado_15->raise();
        WCuadrado_16->raise();
        WCuadrado_17->raise();
        WCuadrado_18->raise();
        btnRed_1->raise();
        btnRed_2->raise();
        btnRed_3->raise();
        btnRed_4->raise();
        lbUnit3->raise();

        retranslateUi(D1);

        QMetaObject::connectSlotsByName(D1);
    } // setupUi

    void retranslateUi(QWidget *D1)
    {
        D1->setWindowTitle(QApplication::translate("D1", "D1", 0, QApplication::UnicodeUTF8));
        lbIMGFondo->setText(QString());
        lbInd_1->setText(QApplication::translate("D1", "01", 0, QApplication::UnicodeUTF8));
        lbInd_2->setText(QApplication::translate("D1", "04", 0, QApplication::UnicodeUTF8));
        lbInd_3->setText(QApplication::translate("D1", "05", 0, QApplication::UnicodeUTF8));
        lbInd_4->setText(QApplication::translate("D1", "06", 0, QApplication::UnicodeUTF8));
        lbInd_5->setText(QApplication::translate("D1", "07", 0, QApplication::UnicodeUTF8));
        lbInd_6->setText(QApplication::translate("D1", "08", 0, QApplication::UnicodeUTF8));
        lbInd_7->setText(QApplication::translate("D1", "09", 0, QApplication::UnicodeUTF8));
        lbInd_8->setText(QApplication::translate("D1", "10", 0, QApplication::UnicodeUTF8));
        lbInd_9->setText(QApplication::translate("D1", "11", 0, QApplication::UnicodeUTF8));
        lbInd_10->setText(QApplication::translate("D1", "12", 0, QApplication::UnicodeUTF8));
        lbInd_11->setText(QApplication::translate("D1", "CPU", 0, QApplication::UnicodeUTF8));
        lbInd_12->setText(QApplication::translate("D1", "MPU", 0, QApplication::UnicodeUTF8));
        lbInd_13->setText(QApplication::translate("D1", "SIO", 0, QApplication::UnicodeUTF8));
        lbInd_14->setText(QApplication::translate("D1", "Al", 0, QApplication::UnicodeUTF8));
        lbInd_15->setText(QApplication::translate("D1", "Al", 0, QApplication::UnicodeUTF8));
        lbInd_16->setText(QApplication::translate("D1", "DO", 0, QApplication::UnicodeUTF8));
        lbInd_17->setText(QApplication::translate("D1", "ACT", 0, QApplication::UnicodeUTF8));
        lbInd_18->setText(QApplication::translate("D1", "ACT", 0, QApplication::UnicodeUTF8));
        lbInd_19->setText(QApplication::translate("D1", "EXP", 0, QApplication::UnicodeUTF8));
        lbInd_20->setText(QApplication::translate("D1", "Dl", 0, QApplication::UnicodeUTF8));
        lbInd_21->setText(QApplication::translate("D1", "01", 0, QApplication::UnicodeUTF8));
        lbInd_22->setText(QApplication::translate("D1", "02", 0, QApplication::UnicodeUTF8));
        lbInd_23->setText(QApplication::translate("D1", "04", 0, QApplication::UnicodeUTF8));
        lbInd_24->setText(QApplication::translate("D1", "05", 0, QApplication::UnicodeUTF8));
        lbInd_25->setText(QApplication::translate("D1", "06", 0, QApplication::UnicodeUTF8));
        lbInd_26->setText(QApplication::translate("D1", "12", 0, QApplication::UnicodeUTF8));
        lbInd_27->setText(QApplication::translate("D1", "EXP", 0, QApplication::UnicodeUTF8));
        lbInd_28->setText(QApplication::translate("D1", "Dl", 0, QApplication::UnicodeUTF8));
        lbInd_29->setText(QApplication::translate("D1", "Al", 0, QApplication::UnicodeUTF8));
        lbInd_30->setText(QApplication::translate("D1", "Al", 0, QApplication::UnicodeUTF8));
        lbInd_31->setText(QApplication::translate("D1", "DVR", 0, QApplication::UnicodeUTF8));
        lbInd_32->setText(QApplication::translate("D1", "LN", 0, QApplication::UnicodeUTF8));
        btnRed_1->setText(QApplication::translate("D1", "RED DE C\303\223MPUTO 1", 0, QApplication::UnicodeUTF8));
        btnRed_2->setText(QApplication::translate("D1", "RED DE C\303\223MPUTO 2", 0, QApplication::UnicodeUTF8));
        btnRed_3->setText(QApplication::translate("D1", "RED DE C\303\223MPUTO 3", 0, QApplication::UnicodeUTF8));
        btnRed_4->setText(QApplication::translate("D1", "IMP PANT", 0, QApplication::UnicodeUTF8));
        lbUnit3->setText(QApplication::translate("D1", "    UNIT3", 0, QApplication::UnicodeUTF8));
        btind1->setText(QString());
        btind1_2->setText(QString());
        btind1_3->setText(QString());
        btind1_4->setText(QString());
        btind1_5->setText(QString());
        btind1_6->setText(QString());
        btind1_7->setText(QString());
        btind1_8->setText(QString());
        btind1_9->setText(QString());
        btind1_10->setText(QString());
        btind1_11->setText(QString());
        btind1_12->setText(QString());
        btind1_13->setText(QString());
        btind1_14->setText(QString());
        btind1_15->setText(QString());
        btind1_16->setText(QString());
        btind1_17->setText(QString());
        btind1_18->setText(QString());
        btind1_19->setText(QString());
        btind1_20->setText(QString());
        btind1_21->setText(QString());
        btind1_22->setText(QString());
        btind1_23->setText(QString());
        btind1_24->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class D1: public Ui_D1 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_D1_H
