/********************************************************************************
** Form generated from reading UI file 'digital16.ui'
**
** Created: Mon 23. Sep 20:33:27 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIGITAL16_H
#define UI_DIGITAL16_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Digital16
{
public:
    QFrame *frBarraT;
    QLabel *lbDig16T;
    QFrame *frame;
    QLabel *lbSloDO;
    QLabel *lbNumDO_1;
    QLabel *lbDOU_1;
    QLabel *lbDO_1;
    QLabel *lbDOT_1;
    QPushButton *btnProx;
    QPushButton *btnCerrar;
    QLabel *lbNumDO_2;
    QLabel *lbDO_2;
    QLabel *lbDOU_2;
    QLabel *lbDOT_2;
    QLabel *lbDOU_3;
    QLabel *lbDOT_3;
    QLabel *lbNumDO_3;
    QLabel *lbDO_3;
    QLabel *lbDOU_4;
    QLabel *lbDOT_4;
    QLabel *lbNumDO_4;
    QLabel *lbDO_4;
    QLabel *lbNumDO_5;
    QLabel *lbDOT_5;
    QLabel *lbDO_5;
    QLabel *lbDOU_5;
    QLabel *lbDOU_6;
    QLabel *lbNumDO_6;
    QLabel *lbDO_6;
    QLabel *lbDOT_6;
    QLabel *lbNumDO_7;
    QLabel *lbDO_7;
    QLabel *lbDOU_7;
    QLabel *lbDOT_7;
    QLabel *lbNumDO_8;
    QLabel *lbDOU_8;
    QLabel *lbDO_8;
    QLabel *lbDOT_8;
    QLabel *lbNumDO_9;
    QLabel *lbDOT_9;
    QLabel *lbDO_9;
    QLabel *lbDOU_9;
    QLabel *lbNumDO_10;
    QLabel *lbDO_10;
    QLabel *lbDOT_10;
    QLabel *lbDOU_10;
    QLabel *lbNumDO_11;
    QLabel *lbDOU_11;
    QLabel *lbDOT_11;
    QLabel *lbDO_11;
    QLabel *lbNumDO_12;
    QLabel *lbDOT_12;
    QLabel *lbDOU_12;
    QLabel *lbDO_12;
    QLabel *lbNumDO_13;
    QLabel *lbDO_13;
    QLabel *lbDOU_13;
    QLabel *lbDOT_13;
    QLabel *lbNumDO_14;
    QLabel *lbDO_14;
    QLabel *lbDOT_14;
    QLabel *lbDOU_14;
    QLabel *lbNumDO_15;
    QLabel *lbDOU_15;
    QLabel *lbDOT_15;
    QLabel *lbDO_15;
    QLabel *lbNumDO_16;
    QLabel *lbDOU_16;
    QLabel *lbDO_16;
    QLabel *lbDOT_16;

    void setupUi(QWidget *Digital16)
    {
        if (Digital16->objectName().isEmpty())
            Digital16->setObjectName(QString::fromUtf8("Digital16"));
        Digital16->resize(485, 425);
        Digital16->setMinimumSize(QSize(485, 425));
        Digital16->setMaximumSize(QSize(485, 425));
        Digital16->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        frBarraT = new QFrame(Digital16);
        frBarraT->setObjectName(QString::fromUtf8("frBarraT"));
        frBarraT->setGeometry(QRect(0, 0, 485, 14));
        frBarraT->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frBarraT->setFrameShape(QFrame::Panel);
        frBarraT->setFrameShadow(QFrame::Raised);
        frBarraT->setLineWidth(0);
        lbDig16T = new QLabel(frBarraT);
        lbDig16T->setObjectName(QString::fromUtf8("lbDig16T"));
        lbDig16T->setGeometry(QRect(3, 0, 111, 16));
        QFont font;
        font.setPointSize(5);
        font.setBold(true);
        font.setWeight(75);
        lbDig16T->setFont(font);
        lbDig16T->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        frame = new QFrame(Digital16);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 17, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        lbSloDO = new QLabel(Digital16);
        lbSloDO->setObjectName(QString::fromUtf8("lbSloDO"));
        lbSloDO->setGeometry(QRect(70, 22, 385, 20));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        lbSloDO->setFont(font1);
        lbSloDO->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        lbNumDO_1 = new QLabel(Digital16);
        lbNumDO_1->setObjectName(QString::fromUtf8("lbNumDO_1"));
        lbNumDO_1->setGeometry(QRect(6, 50, 20, 16));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setBold(true);
        font2.setWeight(75);
        lbNumDO_1->setFont(font2);
        lbNumDO_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_1->setAlignment(Qt::AlignCenter);
        lbDOU_1 = new QLabel(Digital16);
        lbDOU_1->setObjectName(QString::fromUtf8("lbDOU_1"));
        lbDOU_1->setGeometry(QRect(437, 50, 41, 20));
        lbDOU_1->setFont(font2);
        lbDOU_1->setLayoutDirection(Qt::RightToLeft);
        lbDOU_1->setStyleSheet(QString::fromUtf8(""));
        lbDO_1 = new QLabel(Digital16);
        lbDO_1->setObjectName(QString::fromUtf8("lbDO_1"));
        lbDO_1->setGeometry(QRect(357, 50, 41, 20));
        lbDO_1->setFont(font2);
        lbDO_1->setLayoutDirection(Qt::RightToLeft);
        lbDOT_1 = new QLabel(Digital16);
        lbDOT_1->setObjectName(QString::fromUtf8("lbDOT_1"));
        lbDOT_1->setGeometry(QRect(30, 50, 311, 16));
        lbDOT_1->setFont(font2);
        btnProx = new QPushButton(Digital16);
        btnProx->setObjectName(QString::fromUtf8("btnProx"));
        btnProx->setGeometry(QRect(283, 365, 101, 41));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        btnProx->setFont(font3);
        btnProx->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        btnCerrar = new QPushButton(Digital16);
        btnCerrar->setObjectName(QString::fromUtf8("btnCerrar"));
        btnCerrar->setGeometry(QRect(133, 365, 101, 41));
        btnCerrar->setFont(font3);
        btnCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbNumDO_2 = new QLabel(Digital16);
        lbNumDO_2->setObjectName(QString::fromUtf8("lbNumDO_2"));
        lbNumDO_2->setGeometry(QRect(6, 70, 20, 16));
        lbNumDO_2->setFont(font2);
        lbNumDO_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_2->setAlignment(Qt::AlignCenter);
        lbDO_2 = new QLabel(Digital16);
        lbDO_2->setObjectName(QString::fromUtf8("lbDO_2"));
        lbDO_2->setGeometry(QRect(356, 70, 41, 20));
        lbDO_2->setFont(font2);
        lbDO_2->setLayoutDirection(Qt::RightToLeft);
        lbDOU_2 = new QLabel(Digital16);
        lbDOU_2->setObjectName(QString::fromUtf8("lbDOU_2"));
        lbDOU_2->setGeometry(QRect(436, 70, 41, 20));
        lbDOU_2->setFont(font2);
        lbDOU_2->setLayoutDirection(Qt::RightToLeft);
        lbDOU_2->setStyleSheet(QString::fromUtf8(""));
        lbDOT_2 = new QLabel(Digital16);
        lbDOT_2->setObjectName(QString::fromUtf8("lbDOT_2"));
        lbDOT_2->setGeometry(QRect(30, 70, 311, 16));
        lbDOT_2->setFont(font2);
        lbDOU_3 = new QLabel(Digital16);
        lbDOU_3->setObjectName(QString::fromUtf8("lbDOU_3"));
        lbDOU_3->setGeometry(QRect(435, 90, 41, 20));
        lbDOU_3->setFont(font2);
        lbDOU_3->setLayoutDirection(Qt::RightToLeft);
        lbDOU_3->setStyleSheet(QString::fromUtf8(""));
        lbDOT_3 = new QLabel(Digital16);
        lbDOT_3->setObjectName(QString::fromUtf8("lbDOT_3"));
        lbDOT_3->setGeometry(QRect(30, 90, 311, 16));
        lbDOT_3->setFont(font2);
        lbNumDO_3 = new QLabel(Digital16);
        lbNumDO_3->setObjectName(QString::fromUtf8("lbNumDO_3"));
        lbNumDO_3->setGeometry(QRect(6, 90, 20, 16));
        lbNumDO_3->setFont(font2);
        lbNumDO_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_3->setAlignment(Qt::AlignCenter);
        lbDO_3 = new QLabel(Digital16);
        lbDO_3->setObjectName(QString::fromUtf8("lbDO_3"));
        lbDO_3->setGeometry(QRect(360, 90, 41, 20));
        lbDO_3->setFont(font2);
        lbDO_3->setLayoutDirection(Qt::RightToLeft);
        lbDOU_4 = new QLabel(Digital16);
        lbDOU_4->setObjectName(QString::fromUtf8("lbDOU_4"));
        lbDOU_4->setGeometry(QRect(435, 110, 41, 20));
        lbDOU_4->setFont(font2);
        lbDOU_4->setLayoutDirection(Qt::RightToLeft);
        lbDOU_4->setStyleSheet(QString::fromUtf8(""));
        lbDOT_4 = new QLabel(Digital16);
        lbDOT_4->setObjectName(QString::fromUtf8("lbDOT_4"));
        lbDOT_4->setGeometry(QRect(30, 110, 311, 16));
        lbDOT_4->setFont(font2);
        lbNumDO_4 = new QLabel(Digital16);
        lbNumDO_4->setObjectName(QString::fromUtf8("lbNumDO_4"));
        lbNumDO_4->setGeometry(QRect(6, 110, 20, 16));
        lbNumDO_4->setFont(font2);
        lbNumDO_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_4->setAlignment(Qt::AlignCenter);
        lbDO_4 = new QLabel(Digital16);
        lbDO_4->setObjectName(QString::fromUtf8("lbDO_4"));
        lbDO_4->setGeometry(QRect(355, 110, 41, 20));
        lbDO_4->setFont(font2);
        lbDO_4->setLayoutDirection(Qt::RightToLeft);
        lbNumDO_5 = new QLabel(Digital16);
        lbNumDO_5->setObjectName(QString::fromUtf8("lbNumDO_5"));
        lbNumDO_5->setGeometry(QRect(6, 130, 20, 16));
        lbNumDO_5->setFont(font2);
        lbNumDO_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_5->setAlignment(Qt::AlignCenter);
        lbDOT_5 = new QLabel(Digital16);
        lbDOT_5->setObjectName(QString::fromUtf8("lbDOT_5"));
        lbDOT_5->setGeometry(QRect(30, 130, 311, 16));
        lbDOT_5->setFont(font2);
        lbDO_5 = new QLabel(Digital16);
        lbDO_5->setObjectName(QString::fromUtf8("lbDO_5"));
        lbDO_5->setGeometry(QRect(355, 130, 41, 20));
        lbDO_5->setFont(font2);
        lbDO_5->setLayoutDirection(Qt::RightToLeft);
        lbDOU_5 = new QLabel(Digital16);
        lbDOU_5->setObjectName(QString::fromUtf8("lbDOU_5"));
        lbDOU_5->setGeometry(QRect(425, 130, 51, 20));
        lbDOU_5->setFont(font2);
        lbDOU_5->setLayoutDirection(Qt::RightToLeft);
        lbDOU_5->setStyleSheet(QString::fromUtf8(""));
        lbDOU_6 = new QLabel(Digital16);
        lbDOU_6->setObjectName(QString::fromUtf8("lbDOU_6"));
        lbDOU_6->setGeometry(QRect(425, 150, 51, 20));
        lbDOU_6->setFont(font2);
        lbDOU_6->setLayoutDirection(Qt::RightToLeft);
        lbDOU_6->setStyleSheet(QString::fromUtf8(""));
        lbNumDO_6 = new QLabel(Digital16);
        lbNumDO_6->setObjectName(QString::fromUtf8("lbNumDO_6"));
        lbNumDO_6->setGeometry(QRect(6, 150, 20, 16));
        lbNumDO_6->setFont(font2);
        lbNumDO_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_6->setAlignment(Qt::AlignCenter);
        lbDO_6 = new QLabel(Digital16);
        lbDO_6->setObjectName(QString::fromUtf8("lbDO_6"));
        lbDO_6->setGeometry(QRect(355, 150, 41, 20));
        lbDO_6->setFont(font2);
        lbDO_6->setLayoutDirection(Qt::RightToLeft);
        lbDOT_6 = new QLabel(Digital16);
        lbDOT_6->setObjectName(QString::fromUtf8("lbDOT_6"));
        lbDOT_6->setGeometry(QRect(30, 150, 311, 16));
        lbDOT_6->setFont(font2);
        lbNumDO_7 = new QLabel(Digital16);
        lbNumDO_7->setObjectName(QString::fromUtf8("lbNumDO_7"));
        lbNumDO_7->setGeometry(QRect(6, 170, 20, 16));
        lbNumDO_7->setFont(font2);
        lbNumDO_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_7->setAlignment(Qt::AlignCenter);
        lbDO_7 = new QLabel(Digital16);
        lbDO_7->setObjectName(QString::fromUtf8("lbDO_7"));
        lbDO_7->setGeometry(QRect(355, 170, 41, 20));
        lbDO_7->setFont(font2);
        lbDO_7->setLayoutDirection(Qt::RightToLeft);
        lbDOU_7 = new QLabel(Digital16);
        lbDOU_7->setObjectName(QString::fromUtf8("lbDOU_7"));
        lbDOU_7->setGeometry(QRect(425, 170, 51, 20));
        lbDOU_7->setFont(font2);
        lbDOU_7->setLayoutDirection(Qt::RightToLeft);
        lbDOU_7->setStyleSheet(QString::fromUtf8(""));
        lbDOT_7 = new QLabel(Digital16);
        lbDOT_7->setObjectName(QString::fromUtf8("lbDOT_7"));
        lbDOT_7->setGeometry(QRect(30, 170, 311, 16));
        lbDOT_7->setFont(font2);
        lbNumDO_8 = new QLabel(Digital16);
        lbNumDO_8->setObjectName(QString::fromUtf8("lbNumDO_8"));
        lbNumDO_8->setGeometry(QRect(6, 190, 20, 16));
        lbNumDO_8->setFont(font2);
        lbNumDO_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_8->setAlignment(Qt::AlignCenter);
        lbDOU_8 = new QLabel(Digital16);
        lbDOU_8->setObjectName(QString::fromUtf8("lbDOU_8"));
        lbDOU_8->setGeometry(QRect(425, 190, 51, 20));
        lbDOU_8->setFont(font2);
        lbDOU_8->setLayoutDirection(Qt::RightToLeft);
        lbDOU_8->setStyleSheet(QString::fromUtf8(""));
        lbDO_8 = new QLabel(Digital16);
        lbDO_8->setObjectName(QString::fromUtf8("lbDO_8"));
        lbDO_8->setGeometry(QRect(355, 190, 41, 20));
        lbDO_8->setFont(font2);
        lbDO_8->setLayoutDirection(Qt::RightToLeft);
        lbDOT_8 = new QLabel(Digital16);
        lbDOT_8->setObjectName(QString::fromUtf8("lbDOT_8"));
        lbDOT_8->setGeometry(QRect(30, 190, 311, 16));
        lbDOT_8->setFont(font2);
        lbNumDO_9 = new QLabel(Digital16);
        lbNumDO_9->setObjectName(QString::fromUtf8("lbNumDO_9"));
        lbNumDO_9->setGeometry(QRect(6, 210, 20, 16));
        lbNumDO_9->setFont(font2);
        lbNumDO_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_9->setAlignment(Qt::AlignCenter);
        lbDOT_9 = new QLabel(Digital16);
        lbDOT_9->setObjectName(QString::fromUtf8("lbDOT_9"));
        lbDOT_9->setGeometry(QRect(30, 210, 311, 16));
        lbDOT_9->setFont(font2);
        lbDO_9 = new QLabel(Digital16);
        lbDO_9->setObjectName(QString::fromUtf8("lbDO_9"));
        lbDO_9->setGeometry(QRect(355, 210, 41, 20));
        lbDO_9->setFont(font2);
        lbDO_9->setLayoutDirection(Qt::RightToLeft);
        lbDOU_9 = new QLabel(Digital16);
        lbDOU_9->setObjectName(QString::fromUtf8("lbDOU_9"));
        lbDOU_9->setGeometry(QRect(425, 210, 51, 20));
        lbDOU_9->setFont(font2);
        lbDOU_9->setLayoutDirection(Qt::RightToLeft);
        lbDOU_9->setStyleSheet(QString::fromUtf8(""));
        lbNumDO_10 = new QLabel(Digital16);
        lbNumDO_10->setObjectName(QString::fromUtf8("lbNumDO_10"));
        lbNumDO_10->setGeometry(QRect(6, 230, 20, 16));
        lbNumDO_10->setFont(font2);
        lbNumDO_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_10->setAlignment(Qt::AlignCenter);
        lbDO_10 = new QLabel(Digital16);
        lbDO_10->setObjectName(QString::fromUtf8("lbDO_10"));
        lbDO_10->setGeometry(QRect(359, 230, 37, 20));
        lbDO_10->setFont(font2);
        lbDO_10->setLayoutDirection(Qt::RightToLeft);
        lbDOT_10 = new QLabel(Digital16);
        lbDOT_10->setObjectName(QString::fromUtf8("lbDOT_10"));
        lbDOT_10->setGeometry(QRect(30, 230, 311, 16));
        lbDOT_10->setFont(font2);
        lbDOU_10 = new QLabel(Digital16);
        lbDOU_10->setObjectName(QString::fromUtf8("lbDOU_10"));
        lbDOU_10->setGeometry(QRect(429, 230, 51, 20));
        lbDOU_10->setFont(font2);
        lbDOU_10->setLayoutDirection(Qt::RightToLeft);
        lbDOU_10->setStyleSheet(QString::fromUtf8(""));
        lbNumDO_11 = new QLabel(Digital16);
        lbNumDO_11->setObjectName(QString::fromUtf8("lbNumDO_11"));
        lbNumDO_11->setGeometry(QRect(6, 247, 20, 16));
        lbNumDO_11->setFont(font2);
        lbNumDO_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_11->setAlignment(Qt::AlignCenter);
        lbDOU_11 = new QLabel(Digital16);
        lbDOU_11->setObjectName(QString::fromUtf8("lbDOU_11"));
        lbDOU_11->setGeometry(QRect(429, 247, 51, 20));
        lbDOU_11->setFont(font2);
        lbDOU_11->setLayoutDirection(Qt::RightToLeft);
        lbDOU_11->setStyleSheet(QString::fromUtf8(""));
        lbDOT_11 = new QLabel(Digital16);
        lbDOT_11->setObjectName(QString::fromUtf8("lbDOT_11"));
        lbDOT_11->setGeometry(QRect(30, 247, 311, 16));
        lbDOT_11->setFont(font2);
        lbDO_11 = new QLabel(Digital16);
        lbDO_11->setObjectName(QString::fromUtf8("lbDO_11"));
        lbDO_11->setGeometry(QRect(359, 247, 37, 20));
        lbDO_11->setFont(font2);
        lbDO_11->setLayoutDirection(Qt::RightToLeft);
        lbNumDO_12 = new QLabel(Digital16);
        lbNumDO_12->setObjectName(QString::fromUtf8("lbNumDO_12"));
        lbNumDO_12->setGeometry(QRect(6, 265, 20, 16));
        lbNumDO_12->setFont(font2);
        lbNumDO_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_12->setAlignment(Qt::AlignCenter);
        lbDOT_12 = new QLabel(Digital16);
        lbDOT_12->setObjectName(QString::fromUtf8("lbDOT_12"));
        lbDOT_12->setGeometry(QRect(30, 265, 311, 16));
        lbDOT_12->setFont(font2);
        lbDOU_12 = new QLabel(Digital16);
        lbDOU_12->setObjectName(QString::fromUtf8("lbDOU_12"));
        lbDOU_12->setGeometry(QRect(429, 265, 51, 20));
        lbDOU_12->setFont(font2);
        lbDOU_12->setLayoutDirection(Qt::RightToLeft);
        lbDOU_12->setStyleSheet(QString::fromUtf8(""));
        lbDO_12 = new QLabel(Digital16);
        lbDO_12->setObjectName(QString::fromUtf8("lbDO_12"));
        lbDO_12->setGeometry(QRect(359, 265, 37, 20));
        lbDO_12->setFont(font2);
        lbDO_12->setLayoutDirection(Qt::RightToLeft);
        lbNumDO_13 = new QLabel(Digital16);
        lbNumDO_13->setObjectName(QString::fromUtf8("lbNumDO_13"));
        lbNumDO_13->setGeometry(QRect(6, 282, 20, 16));
        lbNumDO_13->setFont(font2);
        lbNumDO_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_13->setAlignment(Qt::AlignCenter);
        lbDO_13 = new QLabel(Digital16);
        lbDO_13->setObjectName(QString::fromUtf8("lbDO_13"));
        lbDO_13->setGeometry(QRect(359, 283, 37, 20));
        lbDO_13->setFont(font2);
        lbDO_13->setLayoutDirection(Qt::RightToLeft);
        lbDOU_13 = new QLabel(Digital16);
        lbDOU_13->setObjectName(QString::fromUtf8("lbDOU_13"));
        lbDOU_13->setGeometry(QRect(429, 283, 51, 20));
        lbDOU_13->setFont(font2);
        lbDOU_13->setLayoutDirection(Qt::RightToLeft);
        lbDOU_13->setStyleSheet(QString::fromUtf8(""));
        lbDOT_13 = new QLabel(Digital16);
        lbDOT_13->setObjectName(QString::fromUtf8("lbDOT_13"));
        lbDOT_13->setGeometry(QRect(30, 283, 311, 16));
        lbDOT_13->setFont(font2);
        lbNumDO_14 = new QLabel(Digital16);
        lbNumDO_14->setObjectName(QString::fromUtf8("lbNumDO_14"));
        lbNumDO_14->setGeometry(QRect(6, 300, 20, 16));
        lbNumDO_14->setFont(font2);
        lbNumDO_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_14->setAlignment(Qt::AlignCenter);
        lbDO_14 = new QLabel(Digital16);
        lbDO_14->setObjectName(QString::fromUtf8("lbDO_14"));
        lbDO_14->setGeometry(QRect(359, 300, 37, 20));
        lbDO_14->setFont(font2);
        lbDO_14->setLayoutDirection(Qt::RightToLeft);
        lbDOT_14 = new QLabel(Digital16);
        lbDOT_14->setObjectName(QString::fromUtf8("lbDOT_14"));
        lbDOT_14->setGeometry(QRect(30, 300, 311, 16));
        lbDOT_14->setFont(font2);
        lbDOU_14 = new QLabel(Digital16);
        lbDOU_14->setObjectName(QString::fromUtf8("lbDOU_14"));
        lbDOU_14->setGeometry(QRect(429, 300, 51, 20));
        lbDOU_14->setFont(font2);
        lbDOU_14->setLayoutDirection(Qt::RightToLeft);
        lbDOU_14->setStyleSheet(QString::fromUtf8(""));
        lbNumDO_15 = new QLabel(Digital16);
        lbNumDO_15->setObjectName(QString::fromUtf8("lbNumDO_15"));
        lbNumDO_15->setGeometry(QRect(6, 320, 20, 16));
        lbNumDO_15->setFont(font2);
        lbNumDO_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_15->setAlignment(Qt::AlignCenter);
        lbDOU_15 = new QLabel(Digital16);
        lbDOU_15->setObjectName(QString::fromUtf8("lbDOU_15"));
        lbDOU_15->setGeometry(QRect(428, 320, 51, 20));
        lbDOU_15->setFont(font2);
        lbDOU_15->setLayoutDirection(Qt::RightToLeft);
        lbDOU_15->setStyleSheet(QString::fromUtf8(""));
        lbDOT_15 = new QLabel(Digital16);
        lbDOT_15->setObjectName(QString::fromUtf8("lbDOT_15"));
        lbDOT_15->setGeometry(QRect(34, 320, 311, 16));
        lbDOT_15->setFont(font2);
        lbDO_15 = new QLabel(Digital16);
        lbDO_15->setObjectName(QString::fromUtf8("lbDO_15"));
        lbDO_15->setGeometry(QRect(359, 320, 37, 20));
        lbDO_15->setFont(font2);
        lbDO_15->setLayoutDirection(Qt::RightToLeft);
        lbNumDO_16 = new QLabel(Digital16);
        lbNumDO_16->setObjectName(QString::fromUtf8("lbNumDO_16"));
        lbNumDO_16->setGeometry(QRect(6, 340, 20, 16));
        lbNumDO_16->setFont(font2);
        lbNumDO_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumDO_16->setAlignment(Qt::AlignCenter);
        lbDOU_16 = new QLabel(Digital16);
        lbDOU_16->setObjectName(QString::fromUtf8("lbDOU_16"));
        lbDOU_16->setGeometry(QRect(427, 340, 51, 20));
        lbDOU_16->setFont(font2);
        lbDOU_16->setLayoutDirection(Qt::RightToLeft);
        lbDOU_16->setStyleSheet(QString::fromUtf8(""));
        lbDO_16 = new QLabel(Digital16);
        lbDO_16->setObjectName(QString::fromUtf8("lbDO_16"));
        lbDO_16->setGeometry(QRect(359, 340, 37, 20));
        lbDO_16->setFont(font2);
        lbDO_16->setLayoutDirection(Qt::RightToLeft);
        lbDOT_16 = new QLabel(Digital16);
        lbDOT_16->setObjectName(QString::fromUtf8("lbDOT_16"));
        lbDOT_16->setGeometry(QRect(28, 340, 311, 16));
        lbDOT_16->setFont(font2);

        retranslateUi(Digital16);

        QMetaObject::connectSlotsByName(Digital16);
    } // setupUi

    void retranslateUi(QWidget *Digital16)
    {
        Digital16->setWindowTitle(QApplication::translate("Digital16", "Digital16", 0, QApplication::UnicodeUTF8));
        lbDig16T->setText(QApplication::translate("Digital16", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">DIGITAL16.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbSloDO->setText(QApplication::translate("Digital16", "SLOT-  A108  - DO", 0, QApplication::UnicodeUTF8));
        lbNumDO_1->setText(QApplication::translate("Digital16", "1", 0, QApplication::UnicodeUTF8));
        lbDOU_1->setText(QApplication::translate("Digital16", "NACT", 0, QApplication::UnicodeUTF8));
        lbDO_1->setText(QApplication::translate("Digital16", "1", 0, QApplication::UnicodeUTF8));
        lbDOT_1->setText(QApplication::translate("Digital16", "01 - RESUMEN CIERRES TURBINA-GENERADOR", 0, QApplication::UnicodeUTF8));
        btnProx->setText(QApplication::translate("Digital16", "PR\303\223X >", 0, QApplication::UnicodeUTF8));
        btnCerrar->setText(QApplication::translate("Digital16", "CERRAR", 0, QApplication::UnicodeUTF8));
        lbNumDO_2->setText(QApplication::translate("Digital16", "2", 0, QApplication::UnicodeUTF8));
        lbDO_2->setText(QApplication::translate("Digital16", "1", 0, QApplication::UnicodeUTF8));
        lbDOU_2->setText(QApplication::translate("Digital16", "ON", 0, QApplication::UnicodeUTF8));
        lbDOT_2->setText(QApplication::translate("Digital16", "02 - POWER SYSTEM STABILIZER ON", 0, QApplication::UnicodeUTF8));
        lbDOU_3->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDOT_3->setText(QApplication::translate("Digital16", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDO_3->setText(QApplication::translate("Digital16", "3", 0, QApplication::UnicodeUTF8));
        lbDO_3->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDOU_4->setText(QApplication::translate("Digital16", "OPN", 0, QApplication::UnicodeUTF8));
        lbDOT_4->setText(QApplication::translate("Digital16", "04 - VALV CIERRE GAS COMB (CORRIENTE ABA)", 0, QApplication::UnicodeUTF8));
        lbNumDO_4->setText(QApplication::translate("Digital16", "4", 0, QApplication::UnicodeUTF8));
        lbDO_4->setText(QApplication::translate("Digital16", "1", 0, QApplication::UnicodeUTF8));
        lbNumDO_5->setText(QApplication::translate("Digital16", "5", 0, QApplication::UnicodeUTF8));
        lbDOT_5->setText(QApplication::translate("Digital16", "05 - VALV AIRE ENFRIA POST CIERRE", 0, QApplication::UnicodeUTF8));
        lbDO_5->setText(QApplication::translate("Digital16", "0", 0, QApplication::UnicodeUTF8));
        lbDOU_5->setText(QApplication::translate("Digital16", "T:OPEN", 0, QApplication::UnicodeUTF8));
        lbDOU_6->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbNumDO_6->setText(QApplication::translate("Digital16", "6", 0, QApplication::UnicodeUTF8));
        lbDO_6->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDOT_6->setText(QApplication::translate("Digital16", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDO_7->setText(QApplication::translate("Digital16", "7", 0, QApplication::UnicodeUTF8));
        lbDO_7->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDOU_7->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDOT_7->setText(QApplication::translate("Digital16", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDO_8->setText(QApplication::translate("Digital16", "8", 0, QApplication::UnicodeUTF8));
        lbDOU_8->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDO_8->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDOT_8->setText(QApplication::translate("Digital16", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDO_9->setText(QApplication::translate("Digital16", "9", 0, QApplication::UnicodeUTF8));
        lbDOT_9->setText(QApplication::translate("Digital16", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbDO_9->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDOU_9->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbNumDO_10->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDO_10->setText(QApplication::translate("Digital16", "0", 0, QApplication::UnicodeUTF8));
        lbDOT_10->setText(QApplication::translate("Digital16", "10 - VALV DESAG\303\234E COMBUSTOR", 0, QApplication::UnicodeUTF8));
        lbDOU_10->setText(QApplication::translate("Digital16", "CLSD", 0, QApplication::UnicodeUTF8));
        lbNumDO_11->setText(QApplication::translate("Digital16", "11", 0, QApplication::UnicodeUTF8));
        lbDOU_11->setText(QApplication::translate("Digital16", "ENBL", 0, QApplication::UnicodeUTF8));
        lbDOT_11->setText(QApplication::translate("Digital16", "11 - CONT VALV MED GAS COMB CIERRE/REEST", 0, QApplication::UnicodeUTF8));
        lbDO_11->setText(QApplication::translate("Digital16", "1", 0, QApplication::UnicodeUTF8));
        lbNumDO_12->setText(QApplication::translate("Digital16", "12", 0, QApplication::UnicodeUTF8));
        lbDOT_12->setText(QApplication::translate("Digital16", "12 - CONT VALV MED COMB LIQ CIERRE/REEST", 0, QApplication::UnicodeUTF8));
        lbDOU_12->setText(QApplication::translate("Digital16", "ENBL", 0, QApplication::UnicodeUTF8));
        lbDO_12->setText(QApplication::translate("Digital16", "1", 0, QApplication::UnicodeUTF8));
        lbNumDO_13->setText(QApplication::translate("Digital16", "13", 0, QApplication::UnicodeUTF8));
        lbDO_13->setText(QApplication::translate("Digital16", "1", 0, QApplication::UnicodeUTF8));
        lbDOU_13->setText(QApplication::translate("Digital16", "ENBL", 0, QApplication::UnicodeUTF8));
        lbDOT_13->setText(QApplication::translate("Digital16", "13 - INY AGUA NOX CIERRE/REESTAB V\303\201LVULA", 0, QApplication::UnicodeUTF8));
        lbNumDO_14->setText(QApplication::translate("Digital16", "14", 0, QApplication::UnicodeUTF8));
        lbDO_14->setText(QApplication::translate("Digital16", "0", 0, QApplication::UnicodeUTF8));
        lbDOT_14->setText(QApplication::translate("Digital16", "14 - SIRENA", 0, QApplication::UnicodeUTF8));
        lbDOU_14->setText(QApplication::translate("Digital16", "NACT", 0, QApplication::UnicodeUTF8));
        lbNumDO_15->setText(QApplication::translate("Digital16", "15", 0, QApplication::UnicodeUTF8));
        lbDOU_15->setText(QApplication::translate("Digital16", "ENBL", 0, QApplication::UnicodeUTF8));
        lbDOT_15->setText(QApplication::translate("Digital16", "15 - CONTROL INTERRUPTOR DE CIRCUITO", 0, QApplication::UnicodeUTF8));
        lbDO_15->setText(QApplication::translate("Digital16", "1", 0, QApplication::UnicodeUTF8));
        lbNumDO_16->setText(QApplication::translate("Digital16", "16", 0, QApplication::UnicodeUTF8));
        lbDOU_16->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDO_16->setText(QApplication::translate("Digital16", "10", 0, QApplication::UnicodeUTF8));
        lbDOT_16->setText(QApplication::translate("Digital16", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Digital16: public Ui_Digital16 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIGITAL16_H
