/********************************************************************************
** Form generated from reading UI file 'digital24.ui'
**
** Created: Wed 9. Oct 20:10:14 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIGITAL24_H
#define UI_DIGITAL24_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Digital24
{
public:
    QLabel *lbTit_3;
    QLabel *lbTit_10;
    QLabel *lbNum_4;
    QLabel *lbNumDes_12;
    QLabel *lbTit_8;
    QLabel *lbUni_10;
    QLabel *lbTit_2;
    QLabel *lbNumDes_2;
    QLabel *lbUni_8;
    QLabel *lbNumDes_7;
    QLabel *lbUni_1;
    QLabel *lbNum_11;
    QLabel *lbUni_4;
    QLabel *lbUni_11;
    QLabel *lbNumDes_4;
    QLabel *lbTit_11;
    QLabel *lbTit_1;
    QLabel *lbNumDes_11;
    QLabel *lbNum_8;
    QLabel *lbUni_9;
    QLabel *lbTit_9;
    QLabel *lbNumDes_8;
    QLabel *lbNum_7;
    QFrame *frame;
    QLabel *label_2;
    QLabel *lbNum_10;
    QLabel *lbNum_9;
    QPushButton *btCerrar;
    QLabel *lbUni_5;
    QLabel *lbTit_6;
    QFrame *frame_2;
    QLabel *lbIP;
    QLabel *lbUni_6;
    QLabel *lbNum_3;
    QLabel *lbNum_6;
    QLabel *lbNum_12;
    QLabel *lbNum_5;
    QLabel *lbTit_12;
    QLabel *lbTit_5;
    QLabel *lbTit_7;
    QLabel *lbNumDes_3;
    QLabel *lbNumDes_9;
    QLabel *lbUni_3;
    QLabel *lbTit_4;
    QLabel *lbNum_2;
    QLabel *lbNumDes_5;
    QLabel *lbUni_12;
    QLabel *lbUni_2;
    QLabel *lbNumDes_1;
    QLabel *lbNum_1;
    QLabel *lbUni_7;
    QLabel *lbNumDes_10;
    QLabel *lbNumDes_6;
    QPushButton *btProx;
    QLabel *lbUni_13;
    QLabel *lbTit_13;
    QLabel *lbNum_13;
    QLabel *lbNum_14;
    QLabel *lbUni_14;
    QLabel *lbNumDes_13;
    QLabel *lbNum_15;
    QLabel *lbUni_15;
    QLabel *lbTit_14;
    QLabel *lbNumDes_14;
    QLabel *lbNum_16;
    QLabel *lbTit_15;
    QLabel *lbNumDes_15;
    QLabel *lbNumDes_16;
    QLabel *lbNumDes_17;
    QLabel *lbNumDes_18;
    QLabel *lbNum_17;
    QLabel *lbNumDes_19;
    QLabel *lbUni_16;
    QLabel *lbNumDes_20;
    QLabel *lbNum_18;
    QLabel *lbUni_17;
    QLabel *lbTit_16;
    QLabel *lbNum_19;
    QLabel *lbUni_18;
    QLabel *lbTit_17;
    QLabel *lbTit_18;
    QLabel *lbTit_19;
    QLabel *lbNum_20;
    QLabel *lbTit_20;
    QLabel *lbNum_21;
    QLabel *lbNum_22;
    QLabel *lbUni_19;
    QLabel *lbNumDes_21;
    QLabel *lbNumDes_22;
    QLabel *lbTit_21;
    QLabel *lbUni_20;
    QLabel *lbNum_23;
    QLabel *lbTit_22;
    QLabel *lbTit_23;
    QLabel *lbUni_21;
    QLabel *lbUni_22;
    QLabel *lbNumDes_23;
    QLabel *lbNumDes_24;
    QLabel *lbNum_24;
    QLabel *lbUni_23;
    QLabel *lbUni_24;
    QLabel *lbTit_24;

    void setupUi(QWidget *Digital24)
    {
        if (Digital24->objectName().isEmpty())
            Digital24->setObjectName(QString::fromUtf8("Digital24"));
        Digital24->resize(485, 590);
        Digital24->setMinimumSize(QSize(485, 590));
        Digital24->setMaximumSize(QSize(485, 590));
        Digital24->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        lbTit_3 = new QLabel(Digital24);
        lbTit_3->setObjectName(QString::fromUtf8("lbTit_3"));
        lbTit_3->setGeometry(QRect(30, 94, 340, 16));
        QFont font;
        font.setFamily(QString::fromUtf8("Verdana"));
        font.setPointSize(8);
        font.setBold(false);
        font.setWeight(50);
        lbTit_3->setFont(font);
        lbTit_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbTit_10 = new QLabel(Digital24);
        lbTit_10->setObjectName(QString::fromUtf8("lbTit_10"));
        lbTit_10->setGeometry(QRect(30, 230, 340, 16));
        lbTit_10->setFont(font);
        lbNum_4 = new QLabel(Digital24);
        lbNum_4->setObjectName(QString::fromUtf8("lbNum_4"));
        lbNum_4->setGeometry(QRect(5, 113, 21, 16));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Verdana"));
        font1.setBold(true);
        font1.setWeight(75);
        lbNum_4->setFont(font1);
        lbNum_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_4->setAlignment(Qt::AlignCenter);
        lbNumDes_12 = new QLabel(Digital24);
        lbNumDes_12->setObjectName(QString::fromUtf8("lbNumDes_12"));
        lbNumDes_12->setGeometry(QRect(381, 270, 35, 16));
        lbNumDes_12->setFont(font);
        lbNumDes_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_8 = new QLabel(Digital24);
        lbTit_8->setObjectName(QString::fromUtf8("lbTit_8"));
        lbTit_8->setGeometry(QRect(30, 190, 340, 16));
        lbTit_8->setFont(font);
        lbUni_10 = new QLabel(Digital24);
        lbUni_10->setObjectName(QString::fromUtf8("lbUni_10"));
        lbUni_10->setGeometry(QRect(420, 230, 51, 16));
        lbUni_10->setFont(font);
        lbUni_10->setStyleSheet(QString::fromUtf8(""));
        lbUni_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_2 = new QLabel(Digital24);
        lbTit_2->setObjectName(QString::fromUtf8("lbTit_2"));
        lbTit_2->setGeometry(QRect(30, 74, 340, 16));
        lbTit_2->setFont(font);
        lbTit_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbNumDes_2 = new QLabel(Digital24);
        lbNumDes_2->setObjectName(QString::fromUtf8("lbNumDes_2"));
        lbNumDes_2->setGeometry(QRect(381, 74, 35, 16));
        lbNumDes_2->setFont(font);
        lbNumDes_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_8 = new QLabel(Digital24);
        lbUni_8->setObjectName(QString::fromUtf8("lbUni_8"));
        lbUni_8->setGeometry(QRect(420, 190, 51, 16));
        lbUni_8->setFont(font);
        lbUni_8->setStyleSheet(QString::fromUtf8(""));
        lbUni_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_7 = new QLabel(Digital24);
        lbNumDes_7->setObjectName(QString::fromUtf8("lbNumDes_7"));
        lbNumDes_7->setGeometry(QRect(381, 173, 35, 16));
        lbNumDes_7->setFont(font);
        lbNumDes_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_1 = new QLabel(Digital24);
        lbUni_1->setObjectName(QString::fromUtf8("lbUni_1"));
        lbUni_1->setGeometry(QRect(420, 55, 50, 16));
        lbUni_1->setFont(font);
        lbUni_1->setStyleSheet(QString::fromUtf8(""));
        lbUni_1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_11 = new QLabel(Digital24);
        lbNum_11->setObjectName(QString::fromUtf8("lbNum_11"));
        lbNum_11->setGeometry(QRect(5, 250, 21, 16));
        lbNum_11->setFont(font1);
        lbNum_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_11->setAlignment(Qt::AlignCenter);
        lbUni_4 = new QLabel(Digital24);
        lbUni_4->setObjectName(QString::fromUtf8("lbUni_4"));
        lbUni_4->setGeometry(QRect(420, 113, 51, 16));
        lbUni_4->setFont(font);
        lbUni_4->setStyleSheet(QString::fromUtf8(""));
        lbUni_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_11 = new QLabel(Digital24);
        lbUni_11->setObjectName(QString::fromUtf8("lbUni_11"));
        lbUni_11->setGeometry(QRect(420, 250, 51, 16));
        lbUni_11->setFont(font);
        lbUni_11->setStyleSheet(QString::fromUtf8(""));
        lbUni_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_4 = new QLabel(Digital24);
        lbNumDes_4->setObjectName(QString::fromUtf8("lbNumDes_4"));
        lbNumDes_4->setGeometry(QRect(381, 113, 35, 16));
        lbNumDes_4->setFont(font);
        lbNumDes_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_11 = new QLabel(Digital24);
        lbTit_11->setObjectName(QString::fromUtf8("lbTit_11"));
        lbTit_11->setGeometry(QRect(30, 250, 340, 16));
        lbTit_11->setFont(font);
        lbTit_1 = new QLabel(Digital24);
        lbTit_1->setObjectName(QString::fromUtf8("lbTit_1"));
        lbTit_1->setGeometry(QRect(30, 55, 340, 16));
        lbTit_1->setFont(font);
        lbTit_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbNumDes_11 = new QLabel(Digital24);
        lbNumDes_11->setObjectName(QString::fromUtf8("lbNumDes_11"));
        lbNumDes_11->setGeometry(QRect(381, 250, 35, 16));
        lbNumDes_11->setFont(font);
        lbNumDes_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_8 = new QLabel(Digital24);
        lbNum_8->setObjectName(QString::fromUtf8("lbNum_8"));
        lbNum_8->setGeometry(QRect(5, 190, 21, 16));
        lbNum_8->setFont(font1);
        lbNum_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_8->setAlignment(Qt::AlignCenter);
        lbUni_9 = new QLabel(Digital24);
        lbUni_9->setObjectName(QString::fromUtf8("lbUni_9"));
        lbUni_9->setGeometry(QRect(420, 210, 51, 16));
        lbUni_9->setFont(font);
        lbUni_9->setStyleSheet(QString::fromUtf8(""));
        lbUni_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_9 = new QLabel(Digital24);
        lbTit_9->setObjectName(QString::fromUtf8("lbTit_9"));
        lbTit_9->setGeometry(QRect(30, 210, 340, 16));
        lbTit_9->setFont(font);
        lbNumDes_8 = new QLabel(Digital24);
        lbNumDes_8->setObjectName(QString::fromUtf8("lbNumDes_8"));
        lbNumDes_8->setGeometry(QRect(381, 190, 35, 16));
        lbNumDes_8->setFont(font);
        lbNumDes_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_7 = new QLabel(Digital24);
        lbNum_7->setObjectName(QString::fromUtf8("lbNum_7"));
        lbNum_7->setGeometry(QRect(5, 173, 21, 16));
        lbNum_7->setFont(font1);
        lbNum_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_7->setAlignment(Qt::AlignCenter);
        frame = new QFrame(Digital24);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(2, 17, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        label_2 = new QLabel(frame);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(62, 4, 400, 22));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        label_2->setFont(font2);
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        lbNum_10 = new QLabel(Digital24);
        lbNum_10->setObjectName(QString::fromUtf8("lbNum_10"));
        lbNum_10->setGeometry(QRect(5, 230, 21, 16));
        lbNum_10->setFont(font1);
        lbNum_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_10->setAlignment(Qt::AlignCenter);
        lbNum_9 = new QLabel(Digital24);
        lbNum_9->setObjectName(QString::fromUtf8("lbNum_9"));
        lbNum_9->setGeometry(QRect(5, 210, 21, 16));
        lbNum_9->setFont(font1);
        lbNum_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_9->setAlignment(Qt::AlignCenter);
        btCerrar = new QPushButton(Digital24);
        btCerrar->setObjectName(QString::fromUtf8("btCerrar"));
        btCerrar->setGeometry(QRect(136, 536, 101, 33));
        btCerrar->setFont(font2);
        btCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbUni_5 = new QLabel(Digital24);
        lbUni_5->setObjectName(QString::fromUtf8("lbUni_5"));
        lbUni_5->setGeometry(QRect(420, 135, 51, 16));
        lbUni_5->setFont(font);
        lbUni_5->setStyleSheet(QString::fromUtf8(""));
        lbUni_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_6 = new QLabel(Digital24);
        lbTit_6->setObjectName(QString::fromUtf8("lbTit_6"));
        lbTit_6->setGeometry(QRect(30, 154, 340, 16));
        lbTit_6->setFont(font);
        frame_2 = new QFrame(Digital24);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(0, 0, 485, 16));
        frame_2->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frame_2->setFrameShape(QFrame::Panel);
        frame_2->setFrameShadow(QFrame::Raised);
        frame_2->setLineWidth(0);
        lbIP = new QLabel(frame_2);
        lbIP->setObjectName(QString::fromUtf8("lbIP"));
        lbIP->setGeometry(QRect(3, 0, 101, 16));
        QFont font3;
        font3.setPointSize(9);
        lbIP->setFont(font3);
        lbIP->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 110, 195);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(74, 110, 195);"));
        lbUni_6 = new QLabel(Digital24);
        lbUni_6->setObjectName(QString::fromUtf8("lbUni_6"));
        lbUni_6->setGeometry(QRect(420, 154, 51, 16));
        lbUni_6->setFont(font);
        lbUni_6->setStyleSheet(QString::fromUtf8(""));
        lbUni_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_3 = new QLabel(Digital24);
        lbNum_3->setObjectName(QString::fromUtf8("lbNum_3"));
        lbNum_3->setGeometry(QRect(5, 94, 21, 16));
        lbNum_3->setFont(font1);
        lbNum_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_3->setAlignment(Qt::AlignCenter);
        lbNum_6 = new QLabel(Digital24);
        lbNum_6->setObjectName(QString::fromUtf8("lbNum_6"));
        lbNum_6->setGeometry(QRect(5, 154, 21, 16));
        lbNum_6->setFont(font1);
        lbNum_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_6->setAlignment(Qt::AlignCenter);
        lbNum_12 = new QLabel(Digital24);
        lbNum_12->setObjectName(QString::fromUtf8("lbNum_12"));
        lbNum_12->setGeometry(QRect(5, 270, 21, 16));
        lbNum_12->setFont(font1);
        lbNum_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_12->setAlignment(Qt::AlignCenter);
        lbNum_5 = new QLabel(Digital24);
        lbNum_5->setObjectName(QString::fromUtf8("lbNum_5"));
        lbNum_5->setGeometry(QRect(5, 135, 21, 16));
        lbNum_5->setFont(font1);
        lbNum_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_5->setAlignment(Qt::AlignCenter);
        lbTit_12 = new QLabel(Digital24);
        lbTit_12->setObjectName(QString::fromUtf8("lbTit_12"));
        lbTit_12->setGeometry(QRect(30, 270, 340, 16));
        lbTit_12->setFont(font);
        lbTit_5 = new QLabel(Digital24);
        lbTit_5->setObjectName(QString::fromUtf8("lbTit_5"));
        lbTit_5->setGeometry(QRect(30, 135, 340, 16));
        lbTit_5->setFont(font);
        lbTit_7 = new QLabel(Digital24);
        lbTit_7->setObjectName(QString::fromUtf8("lbTit_7"));
        lbTit_7->setGeometry(QRect(30, 173, 340, 16));
        lbTit_7->setFont(font);
        lbNumDes_3 = new QLabel(Digital24);
        lbNumDes_3->setObjectName(QString::fromUtf8("lbNumDes_3"));
        lbNumDes_3->setGeometry(QRect(381, 94, 35, 16));
        lbNumDes_3->setFont(font);
        lbNumDes_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_9 = new QLabel(Digital24);
        lbNumDes_9->setObjectName(QString::fromUtf8("lbNumDes_9"));
        lbNumDes_9->setGeometry(QRect(381, 210, 35, 16));
        lbNumDes_9->setFont(font);
        lbNumDes_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_3 = new QLabel(Digital24);
        lbUni_3->setObjectName(QString::fromUtf8("lbUni_3"));
        lbUni_3->setGeometry(QRect(420, 94, 51, 16));
        lbUni_3->setFont(font);
        lbUni_3->setStyleSheet(QString::fromUtf8(""));
        lbUni_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_4 = new QLabel(Digital24);
        lbTit_4->setObjectName(QString::fromUtf8("lbTit_4"));
        lbTit_4->setGeometry(QRect(30, 113, 340, 16));
        lbTit_4->setFont(font);
        lbNum_2 = new QLabel(Digital24);
        lbNum_2->setObjectName(QString::fromUtf8("lbNum_2"));
        lbNum_2->setGeometry(QRect(5, 74, 21, 16));
        lbNum_2->setFont(font1);
        lbNum_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_2->setAlignment(Qt::AlignCenter);
        lbNumDes_5 = new QLabel(Digital24);
        lbNumDes_5->setObjectName(QString::fromUtf8("lbNumDes_5"));
        lbNumDes_5->setGeometry(QRect(381, 135, 35, 16));
        lbNumDes_5->setFont(font);
        lbNumDes_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_12 = new QLabel(Digital24);
        lbUni_12->setObjectName(QString::fromUtf8("lbUni_12"));
        lbUni_12->setGeometry(QRect(420, 270, 51, 16));
        lbUni_12->setFont(font);
        lbUni_12->setStyleSheet(QString::fromUtf8(""));
        lbUni_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_2 = new QLabel(Digital24);
        lbUni_2->setObjectName(QString::fromUtf8("lbUni_2"));
        lbUni_2->setGeometry(QRect(420, 74, 51, 16));
        lbUni_2->setFont(font);
        lbUni_2->setStyleSheet(QString::fromUtf8(""));
        lbUni_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_1 = new QLabel(Digital24);
        lbNumDes_1->setObjectName(QString::fromUtf8("lbNumDes_1"));
        lbNumDes_1->setGeometry(QRect(381, 55, 35, 16));
        lbNumDes_1->setFont(font);
        lbNumDes_1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_1 = new QLabel(Digital24);
        lbNum_1->setObjectName(QString::fromUtf8("lbNum_1"));
        lbNum_1->setGeometry(QRect(5, 55, 21, 16));
        lbNum_1->setFont(font1);
        lbNum_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_1->setAlignment(Qt::AlignCenter);
        lbUni_7 = new QLabel(Digital24);
        lbUni_7->setObjectName(QString::fromUtf8("lbUni_7"));
        lbUni_7->setGeometry(QRect(420, 173, 51, 16));
        lbUni_7->setFont(font);
        lbUni_7->setStyleSheet(QString::fromUtf8(""));
        lbUni_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_10 = new QLabel(Digital24);
        lbNumDes_10->setObjectName(QString::fromUtf8("lbNumDes_10"));
        lbNumDes_10->setGeometry(QRect(381, 230, 35, 16));
        lbNumDes_10->setFont(font);
        lbNumDes_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_6 = new QLabel(Digital24);
        lbNumDes_6->setObjectName(QString::fromUtf8("lbNumDes_6"));
        lbNumDes_6->setGeometry(QRect(381, 154, 35, 16));
        lbNumDes_6->setFont(font);
        lbNumDes_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        btProx = new QPushButton(Digital24);
        btProx->setObjectName(QString::fromUtf8("btProx"));
        btProx->setGeometry(QRect(283, 536, 101, 33));
        btProx->setFont(font2);
        btProx->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbUni_13 = new QLabel(Digital24);
        lbUni_13->setObjectName(QString::fromUtf8("lbUni_13"));
        lbUni_13->setGeometry(QRect(420, 450, 51, 16));
        lbUni_13->setFont(font);
        lbUni_13->setStyleSheet(QString::fromUtf8(""));
        lbUni_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_13 = new QLabel(Digital24);
        lbTit_13->setObjectName(QString::fromUtf8("lbTit_13"));
        lbTit_13->setGeometry(QRect(30, 310, 340, 16));
        lbTit_13->setFont(font);
        lbNum_13 = new QLabel(Digital24);
        lbNum_13->setObjectName(QString::fromUtf8("lbNum_13"));
        lbNum_13->setGeometry(QRect(5, 510, 21, 16));
        lbNum_13->setFont(font1);
        lbNum_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_13->setAlignment(Qt::AlignCenter);
        lbNum_14 = new QLabel(Digital24);
        lbNum_14->setObjectName(QString::fromUtf8("lbNum_14"));
        lbNum_14->setGeometry(QRect(5, 430, 21, 16));
        lbNum_14->setFont(font1);
        lbNum_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_14->setAlignment(Qt::AlignCenter);
        lbUni_14 = new QLabel(Digital24);
        lbUni_14->setObjectName(QString::fromUtf8("lbUni_14"));
        lbUni_14->setGeometry(QRect(420, 310, 51, 16));
        lbUni_14->setFont(font);
        lbUni_14->setStyleSheet(QString::fromUtf8(""));
        lbUni_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_13 = new QLabel(Digital24);
        lbNumDes_13->setObjectName(QString::fromUtf8("lbNumDes_13"));
        lbNumDes_13->setGeometry(QRect(381, 390, 35, 16));
        lbNumDes_13->setFont(font);
        lbNumDes_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_15 = new QLabel(Digital24);
        lbNum_15->setObjectName(QString::fromUtf8("lbNum_15"));
        lbNum_15->setGeometry(QRect(5, 450, 21, 16));
        lbNum_15->setFont(font1);
        lbNum_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_15->setAlignment(Qt::AlignCenter);
        lbUni_15 = new QLabel(Digital24);
        lbUni_15->setObjectName(QString::fromUtf8("lbUni_15"));
        lbUni_15->setGeometry(QRect(420, 290, 51, 16));
        lbUni_15->setFont(font);
        lbUni_15->setStyleSheet(QString::fromUtf8(""));
        lbUni_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_14 = new QLabel(Digital24);
        lbTit_14->setObjectName(QString::fromUtf8("lbTit_14"));
        lbTit_14->setGeometry(QRect(30, 490, 340, 16));
        lbTit_14->setFont(font);
        lbNumDes_14 = new QLabel(Digital24);
        lbNumDes_14->setObjectName(QString::fromUtf8("lbNumDes_14"));
        lbNumDes_14->setGeometry(QRect(381, 470, 35, 16));
        lbNumDes_14->setFont(font);
        lbNumDes_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_16 = new QLabel(Digital24);
        lbNum_16->setObjectName(QString::fromUtf8("lbNum_16"));
        lbNum_16->setGeometry(QRect(5, 370, 21, 16));
        lbNum_16->setFont(font1);
        lbNum_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_16->setAlignment(Qt::AlignCenter);
        lbTit_15 = new QLabel(Digital24);
        lbTit_15->setObjectName(QString::fromUtf8("lbTit_15"));
        lbTit_15->setGeometry(QRect(30, 390, 340, 16));
        lbTit_15->setFont(font);
        lbNumDes_15 = new QLabel(Digital24);
        lbNumDes_15->setObjectName(QString::fromUtf8("lbNumDes_15"));
        lbNumDes_15->setGeometry(QRect(381, 490, 35, 16));
        lbNumDes_15->setFont(font);
        lbNumDes_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_16 = new QLabel(Digital24);
        lbNumDes_16->setObjectName(QString::fromUtf8("lbNumDes_16"));
        lbNumDes_16->setGeometry(QRect(381, 430, 35, 16));
        lbNumDes_16->setFont(font);
        lbNumDes_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_17 = new QLabel(Digital24);
        lbNumDes_17->setObjectName(QString::fromUtf8("lbNumDes_17"));
        lbNumDes_17->setGeometry(QRect(381, 290, 35, 16));
        lbNumDes_17->setFont(font);
        lbNumDes_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_18 = new QLabel(Digital24);
        lbNumDes_18->setObjectName(QString::fromUtf8("lbNumDes_18"));
        lbNumDes_18->setGeometry(QRect(381, 330, 35, 16));
        lbNumDes_18->setFont(font);
        lbNumDes_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_17 = new QLabel(Digital24);
        lbNum_17->setObjectName(QString::fromUtf8("lbNum_17"));
        lbNum_17->setGeometry(QRect(5, 490, 21, 16));
        lbNum_17->setFont(font1);
        lbNum_17->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_17->setAlignment(Qt::AlignCenter);
        lbNumDes_19 = new QLabel(Digital24);
        lbNumDes_19->setObjectName(QString::fromUtf8("lbNumDes_19"));
        lbNumDes_19->setGeometry(QRect(381, 410, 35, 16));
        lbNumDes_19->setFont(font);
        lbNumDes_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_16 = new QLabel(Digital24);
        lbUni_16->setObjectName(QString::fromUtf8("lbUni_16"));
        lbUni_16->setGeometry(QRect(420, 470, 51, 16));
        lbUni_16->setFont(font);
        lbUni_16->setStyleSheet(QString::fromUtf8(""));
        lbUni_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_20 = new QLabel(Digital24);
        lbNumDes_20->setObjectName(QString::fromUtf8("lbNumDes_20"));
        lbNumDes_20->setGeometry(QRect(381, 350, 35, 16));
        lbNumDes_20->setFont(font);
        lbNumDes_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_18 = new QLabel(Digital24);
        lbNum_18->setObjectName(QString::fromUtf8("lbNum_18"));
        lbNum_18->setGeometry(QRect(5, 310, 21, 16));
        lbNum_18->setFont(font1);
        lbNum_18->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_18->setAlignment(Qt::AlignCenter);
        lbUni_17 = new QLabel(Digital24);
        lbUni_17->setObjectName(QString::fromUtf8("lbUni_17"));
        lbUni_17->setGeometry(QRect(420, 330, 51, 16));
        lbUni_17->setFont(font);
        lbUni_17->setStyleSheet(QString::fromUtf8(""));
        lbUni_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_16 = new QLabel(Digital24);
        lbTit_16->setObjectName(QString::fromUtf8("lbTit_16"));
        lbTit_16->setGeometry(QRect(30, 510, 340, 16));
        lbTit_16->setFont(font);
        lbNum_19 = new QLabel(Digital24);
        lbNum_19->setObjectName(QString::fromUtf8("lbNum_19"));
        lbNum_19->setGeometry(QRect(5, 470, 21, 16));
        lbNum_19->setFont(font1);
        lbNum_19->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_19->setAlignment(Qt::AlignCenter);
        lbUni_18 = new QLabel(Digital24);
        lbUni_18->setObjectName(QString::fromUtf8("lbUni_18"));
        lbUni_18->setGeometry(QRect(420, 370, 51, 16));
        lbUni_18->setFont(font);
        lbUni_18->setStyleSheet(QString::fromUtf8(""));
        lbUni_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_17 = new QLabel(Digital24);
        lbTit_17->setObjectName(QString::fromUtf8("lbTit_17"));
        lbTit_17->setGeometry(QRect(30, 410, 340, 16));
        lbTit_17->setFont(font);
        lbTit_18 = new QLabel(Digital24);
        lbTit_18->setObjectName(QString::fromUtf8("lbTit_18"));
        lbTit_18->setGeometry(QRect(30, 330, 340, 16));
        lbTit_18->setFont(font);
        lbTit_19 = new QLabel(Digital24);
        lbTit_19->setObjectName(QString::fromUtf8("lbTit_19"));
        lbTit_19->setGeometry(QRect(30, 450, 340, 16));
        lbTit_19->setFont(font);
        lbNum_20 = new QLabel(Digital24);
        lbNum_20->setObjectName(QString::fromUtf8("lbNum_20"));
        lbNum_20->setGeometry(QRect(5, 290, 21, 16));
        lbNum_20->setFont(font1);
        lbNum_20->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_20->setAlignment(Qt::AlignCenter);
        lbTit_20 = new QLabel(Digital24);
        lbTit_20->setObjectName(QString::fromUtf8("lbTit_20"));
        lbTit_20->setGeometry(QRect(30, 430, 340, 16));
        lbTit_20->setFont(font);
        lbNum_21 = new QLabel(Digital24);
        lbNum_21->setObjectName(QString::fromUtf8("lbNum_21"));
        lbNum_21->setGeometry(QRect(5, 350, 21, 16));
        lbNum_21->setFont(font1);
        lbNum_21->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_21->setAlignment(Qt::AlignCenter);
        lbNum_22 = new QLabel(Digital24);
        lbNum_22->setObjectName(QString::fromUtf8("lbNum_22"));
        lbNum_22->setGeometry(QRect(5, 410, 21, 16));
        lbNum_22->setFont(font1);
        lbNum_22->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_22->setAlignment(Qt::AlignCenter);
        lbUni_19 = new QLabel(Digital24);
        lbUni_19->setObjectName(QString::fromUtf8("lbUni_19"));
        lbUni_19->setGeometry(QRect(420, 350, 51, 16));
        lbUni_19->setFont(font);
        lbUni_19->setStyleSheet(QString::fromUtf8(""));
        lbUni_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_21 = new QLabel(Digital24);
        lbNumDes_21->setObjectName(QString::fromUtf8("lbNumDes_21"));
        lbNumDes_21->setGeometry(QRect(381, 450, 35, 16));
        lbNumDes_21->setFont(font);
        lbNumDes_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_22 = new QLabel(Digital24);
        lbNumDes_22->setObjectName(QString::fromUtf8("lbNumDes_22"));
        lbNumDes_22->setGeometry(QRect(381, 370, 35, 16));
        lbNumDes_22->setFont(font);
        lbNumDes_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_21 = new QLabel(Digital24);
        lbTit_21->setObjectName(QString::fromUtf8("lbTit_21"));
        lbTit_21->setGeometry(QRect(30, 350, 340, 16));
        lbTit_21->setFont(font);
        lbUni_20 = new QLabel(Digital24);
        lbUni_20->setObjectName(QString::fromUtf8("lbUni_20"));
        lbUni_20->setGeometry(QRect(420, 430, 51, 16));
        lbUni_20->setFont(font);
        lbUni_20->setStyleSheet(QString::fromUtf8(""));
        lbUni_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_23 = new QLabel(Digital24);
        lbNum_23->setObjectName(QString::fromUtf8("lbNum_23"));
        lbNum_23->setGeometry(QRect(5, 330, 21, 16));
        lbNum_23->setFont(font1);
        lbNum_23->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_23->setAlignment(Qt::AlignCenter);
        lbTit_22 = new QLabel(Digital24);
        lbTit_22->setObjectName(QString::fromUtf8("lbTit_22"));
        lbTit_22->setGeometry(QRect(30, 370, 340, 16));
        lbTit_22->setFont(font);
        lbTit_23 = new QLabel(Digital24);
        lbTit_23->setObjectName(QString::fromUtf8("lbTit_23"));
        lbTit_23->setGeometry(QRect(30, 470, 340, 16));
        lbTit_23->setFont(font);
        lbUni_21 = new QLabel(Digital24);
        lbUni_21->setObjectName(QString::fromUtf8("lbUni_21"));
        lbUni_21->setGeometry(QRect(420, 490, 51, 16));
        lbUni_21->setFont(font);
        lbUni_21->setStyleSheet(QString::fromUtf8(""));
        lbUni_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_22 = new QLabel(Digital24);
        lbUni_22->setObjectName(QString::fromUtf8("lbUni_22"));
        lbUni_22->setGeometry(QRect(420, 410, 51, 16));
        lbUni_22->setFont(font);
        lbUni_22->setStyleSheet(QString::fromUtf8(""));
        lbUni_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_23 = new QLabel(Digital24);
        lbNumDes_23->setObjectName(QString::fromUtf8("lbNumDes_23"));
        lbNumDes_23->setGeometry(QRect(381, 510, 35, 16));
        lbNumDes_23->setFont(font);
        lbNumDes_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNumDes_24 = new QLabel(Digital24);
        lbNumDes_24->setObjectName(QString::fromUtf8("lbNumDes_24"));
        lbNumDes_24->setGeometry(QRect(381, 310, 35, 16));
        lbNumDes_24->setFont(font);
        lbNumDes_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbNum_24 = new QLabel(Digital24);
        lbNum_24->setObjectName(QString::fromUtf8("lbNum_24"));
        lbNum_24->setGeometry(QRect(5, 390, 21, 16));
        lbNum_24->setFont(font1);
        lbNum_24->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNum_24->setAlignment(Qt::AlignCenter);
        lbUni_23 = new QLabel(Digital24);
        lbUni_23->setObjectName(QString::fromUtf8("lbUni_23"));
        lbUni_23->setGeometry(QRect(420, 510, 51, 16));
        lbUni_23->setFont(font);
        lbUni_23->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));
        lbUni_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbUni_24 = new QLabel(Digital24);
        lbUni_24->setObjectName(QString::fromUtf8("lbUni_24"));
        lbUni_24->setGeometry(QRect(420, 390, 51, 16));
        lbUni_24->setFont(font);
        lbUni_24->setStyleSheet(QString::fromUtf8(""));
        lbUni_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbTit_24 = new QLabel(Digital24);
        lbTit_24->setObjectName(QString::fromUtf8("lbTit_24"));
        lbTit_24->setGeometry(QRect(30, 290, 340, 16));
        lbTit_24->setFont(font);
        lbTit_24->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0);"));

        retranslateUi(Digital24);

        QMetaObject::connectSlotsByName(Digital24);
    } // setupUi

    void retranslateUi(QWidget *Digital24)
    {
        Digital24->setWindowTitle(QApplication::translate("Digital24", "Form", 0, QApplication::UnicodeUTF8));
        lbTit_3->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbTit_10->setText(QApplication::translate("Digital24", "14 -LUB VENT INTERCAM CAL 'A'  ALTA VIB", 0, QApplication::UnicodeUTF8));
        lbNum_4->setText(QApplication::translate("Digital24", "4", 0, QApplication::UnicodeUTF8));
        lbNumDes_12->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbTit_8->setText(QApplication::translate("Digital24", "68 TRIP (CLIENTE)", 0, QApplication::UnicodeUTF8));
        lbUni_10->setText(QString());
        lbTit_2->setText(QApplication::translate("Digital24", "****", 0, QApplication::UnicodeUTF8));
        lbNumDes_2->setText(QApplication::translate("Digital24", "****", 0, QApplication::UnicodeUTF8));
        lbUni_8->setText(QApplication::translate("Digital24", "NSDN", 0, QApplication::UnicodeUTF8));
        lbNumDes_7->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        lbUni_1->setText(QApplication::translate("Digital24", "CLOSED", 0, QApplication::UnicodeUTF8));
        lbNum_11->setText(QApplication::translate("Digital24", "11", 0, QApplication::UnicodeUTF8));
        lbUni_4->setText(QApplication::translate("Digital24", "NSDN", 0, QApplication::UnicodeUTF8));
        lbUni_11->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_4->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        lbTit_11->setText(QApplication::translate("Digital24", "14 -LUB VENT INTERCAM CAL 'B' ALTA VIB", 0, QApplication::UnicodeUTF8));
        lbTit_1->setText(QApplication::translate("Digital24", "CIERRE SUPRESI\303\223N COMB Y NOX", 0, QApplication::UnicodeUTF8));
        lbNumDes_11->setText(QApplication::translate("Digital24", "0", 0, QApplication::UnicodeUTF8));
        lbNum_8->setText(QApplication::translate("Digital24", "8", 0, QApplication::UnicodeUTF8));
        lbUni_9->setText(QString());
        lbTit_9->setText(QApplication::translate("Digital24", "FALLA INTERUPTOR GENERADOR", 0, QApplication::UnicodeUTF8));
        lbNumDes_8->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        lbNum_7->setText(QApplication::translate("Digital24", "7", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Digital24", "SLOT-  A112  -DI", 0, QApplication::UnicodeUTF8));
        lbNum_10->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNum_9->setText(QApplication::translate("Digital24", "9", 0, QApplication::UnicodeUTF8));
        btCerrar->setText(QApplication::translate("Digital24", "CERRAR", 0, QApplication::UnicodeUTF8));
        lbUni_5->setText(QApplication::translate("Digital24", "NSDN", 0, QApplication::UnicodeUTF8));
        lbTit_6->setText(QApplication::translate("Digital24", "CIERRE L.I.E -SALA TURBINA", 0, QApplication::UnicodeUTF8));
        lbIP->setText(QApplication::translate("Digital24", "DIGITAL24.grf", 0, QApplication::UnicodeUTF8));
        lbUni_6->setText(QApplication::translate("Digital24", "NSDN", 0, QApplication::UnicodeUTF8));
        lbNum_3->setText(QApplication::translate("Digital24", "3", 0, QApplication::UnicodeUTF8));
        lbNum_6->setText(QApplication::translate("Digital24", "6", 0, QApplication::UnicodeUTF8));
        lbNum_12->setText(QApplication::translate("Digital24", "12", 0, QApplication::UnicodeUTF8));
        lbNum_5->setText(QApplication::translate("Digital24", "5", 0, QApplication::UnicodeUTF8));
        lbTit_12->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbTit_5->setText(QApplication::translate("Digital24", "CIERRE MONITOR FUEGO/GAS", 0, QApplication::UnicodeUTF8));
        lbTit_7->setText(QApplication::translate("Digital24", "CIERRE L.I.E -SALA GEN", 0, QApplication::UnicodeUTF8));
        lbNumDes_3->setText(QApplication::translate("Digital24", "0", 0, QApplication::UnicodeUTF8));
        lbNumDes_9->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        lbUni_3->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbTit_4->setText(QApplication::translate("Digital24", "CONTROL ISOC/DROOP", 0, QApplication::UnicodeUTF8));
        lbNum_2->setText(QApplication::translate("Digital24", "2", 0, QApplication::UnicodeUTF8));
        lbNumDes_5->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        lbUni_12->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbUni_2->setText(QApplication::translate("Digital24", "****", 0, QApplication::UnicodeUTF8));
        lbNumDes_1->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        lbNum_1->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        lbUni_7->setText(QApplication::translate("Digital24", "NSDN", 0, QApplication::UnicodeUTF8));
        lbNumDes_10->setText(QApplication::translate("Digital24", "0", 0, QApplication::UnicodeUTF8));
        lbNumDes_6->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        btProx->setText(QApplication::translate("Digital24", "PR\303\223X>", 0, QApplication::UnicodeUTF8));
        lbUni_13->setText(QApplication::translate("Digital24", "OPN", 0, QApplication::UnicodeUTF8));
        lbTit_13->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNum_13->setText(QApplication::translate("Digital24", "24", 0, QApplication::UnicodeUTF8));
        lbNum_14->setText(QApplication::translate("Digital24", "20", 0, QApplication::UnicodeUTF8));
        lbUni_14->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_13->setText(QApplication::translate("Digital24", "1", 0, QApplication::UnicodeUTF8));
        lbNum_15->setText(QApplication::translate("Digital24", "21", 0, QApplication::UnicodeUTF8));
        lbUni_15->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbTit_14->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumDes_14->setText(QApplication::translate("Digital24", "0", 0, QApplication::UnicodeUTF8));
        lbNum_16->setText(QApplication::translate("Digital24", "17", 0, QApplication::UnicodeUTF8));
        lbTit_15->setText(QApplication::translate("Digital24", "INTERR GEN CERRADO", 0, QApplication::UnicodeUTF8));
        lbNumDes_15->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_16->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_17->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_18->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNum_17->setText(QApplication::translate("Digital24", "23", 0, QApplication::UnicodeUTF8));
        lbNumDes_19->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbUni_16->setText(QApplication::translate("Digital24", "OPN", 0, QApplication::UnicodeUTF8));
        lbNumDes_20->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNum_18->setText(QApplication::translate("Digital24", "14", 0, QApplication::UnicodeUTF8));
        lbUni_17->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbTit_16->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNum_19->setText(QApplication::translate("Digital24", "22", 0, QApplication::UnicodeUTF8));
        lbUni_18->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbTit_17->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbTit_18->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbTit_19->setText(QApplication::translate("Digital24", "CORTE COMB GAS POS INTER VLV (FLUJ ANT)", 0, QApplication::UnicodeUTF8));
        lbNum_20->setText(QApplication::translate("Digital24", "13", 0, QApplication::UnicodeUTF8));
        lbTit_20->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNum_21->setText(QApplication::translate("Digital24", "16", 0, QApplication::UnicodeUTF8));
        lbNum_22->setText(QApplication::translate("Digital24", "19", 0, QApplication::UnicodeUTF8));
        lbUni_19->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_21->setText(QApplication::translate("Digital24", "0", 0, QApplication::UnicodeUTF8));
        lbNumDes_22->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbTit_21->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbUni_20->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNum_23->setText(QApplication::translate("Digital24", "15", 0, QApplication::UnicodeUTF8));
        lbTit_22->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbTit_23->setText(QApplication::translate("Digital24", "CORTE COMB GAS POS INTER VLV (FLUJ POST)", 0, QApplication::UnicodeUTF8));
        lbUni_21->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbUni_22->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_23->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNumDes_24->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbNum_24->setText(QApplication::translate("Digital24", "18", 0, QApplication::UnicodeUTF8));
        lbUni_23->setText(QApplication::translate("Digital24", "10", 0, QApplication::UnicodeUTF8));
        lbUni_24->setText(QApplication::translate("Digital24", "CLOSED", 0, QApplication::UnicodeUTF8));
        lbTit_24->setText(QApplication::translate("Digital24", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Digital24: public Ui_Digital24 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIGITAL24_H
