/********************************************************************************
** Form generated from reading UI file 'e1.ui'
**
** Created: Sun 13. Oct 17:34:58 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_E1_H
#define UI_E1_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "qwt_plot.h"

QT_BEGIN_NAMESPACE

class Ui_E1
{
public:
    QFrame *frame;
    QFrame *frame_2;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_5;
    QwtPlot *qwtPlot;
    QLabel *label_2;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QFrame *frame_3;
    QwtPlot *qwtPlot_2;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLabel *label_84;
    QLabel *label_85;
    QLabel *label_86;
    QLabel *label_87;
    QLabel *label_88;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QLabel *label_3;
    QPushButton *pushButton_12;
    QPushButton *pushButton_9;
    QPushButton *pushButton_13;
    QPushButton *pushButton_8;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;

    void setupUi(QWidget *E1)
    {
        if (E1->objectName().isEmpty())
            E1->setObjectName(QString::fromUtf8("E1"));
        E1->resize(1024, 662);
        E1->setMinimumSize(QSize(1024, 662));
        E1->setMaximumSize(QSize(1024, 662));
        frame = new QFrame(E1);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 0, 1024, 662));
        frame->setMinimumSize(QSize(1024, 662));
        frame->setMaximumSize(QSize(1024, 662));
        frame->setStyleSheet(QString::fromUtf8("background-color: rgb(227, 227, 228);"));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame_2 = new QFrame(frame);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(4, 4, 1016, 316));
        frame_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        pushButton = new QPushButton(frame_2);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(356, 3, 99, 29));
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        pushButton->setFont(font);
        pushButton_2 = new QPushButton(frame_2);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(456, 3, 99, 29));
        pushButton_2->setFont(font);
        pushButton_5 = new QPushButton(frame_2);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(557, 3, 99, 29));
        pushButton_5->setFont(font);
        qwtPlot = new QwtPlot(frame_2);
        qwtPlot->setObjectName(QString::fromUtf8("qwtPlot"));
        qwtPlot->setGeometry(QRect(7, 34, 971, 151));
        label_2 = new QLabel(frame_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(54, 12, 151, 21));
        QFont font1;
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        label_2->setFont(font1);
        label_4 = new QLabel(frame_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(5, 194, 41, 16));
        label_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_5 = new QLabel(frame_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(70, 194, 41, 16));
        label_5->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_6 = new QLabel(frame_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(144, 194, 51, 16));
        label_6->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_7 = new QLabel(frame_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(210, 194, 66, 16));
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_8 = new QLabel(frame_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(280, 194, 151, 16));
        label_8->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_9 = new QLabel(frame_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(280, 207, 151, 16));
        label_9->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_10 = new QLabel(frame_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(5, 207, 41, 16));
        label_10->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_11 = new QLabel(frame_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(210, 207, 66, 16));
        label_11->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_12 = new QLabel(frame_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(70, 207, 41, 16));
        label_12->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_13 = new QLabel(frame_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(144, 207, 51, 16));
        label_13->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_14 = new QLabel(frame_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(280, 220, 151, 16));
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_15 = new QLabel(frame_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(144, 220, 51, 16));
        label_15->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_16 = new QLabel(frame_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(5, 220, 41, 16));
        label_16->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_17 = new QLabel(frame_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(210, 220, 66, 16));
        label_17->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_18 = new QLabel(frame_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(70, 220, 41, 16));
        label_18->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_19 = new QLabel(frame_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(280, 234, 151, 16));
        label_19->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_20 = new QLabel(frame_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(210, 234, 66, 16));
        label_20->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_21 = new QLabel(frame_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(144, 234, 51, 16));
        label_21->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_22 = new QLabel(frame_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(70, 234, 41, 16));
        label_22->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_23 = new QLabel(frame_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(5, 234, 41, 16));
        label_23->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_24 = new QLabel(frame_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(280, 247, 151, 16));
        label_24->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_25 = new QLabel(frame_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(70, 247, 41, 16));
        label_25->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_26 = new QLabel(frame_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(5, 247, 41, 16));
        label_26->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_27 = new QLabel(frame_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(144, 247, 51, 16));
        label_27->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_28 = new QLabel(frame_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(210, 247, 66, 16));
        label_28->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_29 = new QLabel(frame_2);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(280, 262, 151, 16));
        label_29->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_30 = new QLabel(frame_2);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(144, 262, 51, 16));
        label_30->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_31 = new QLabel(frame_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(210, 262, 66, 16));
        label_31->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_32 = new QLabel(frame_2);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(5, 262, 41, 16));
        label_32->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_33 = new QLabel(frame_2);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(70, 262, 41, 16));
        label_33->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_34 = new QLabel(frame_2);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(280, 275, 151, 16));
        label_34->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_35 = new QLabel(frame_2);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(5, 275, 41, 16));
        label_35->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_36 = new QLabel(frame_2);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(210, 275, 66, 16));
        label_36->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_37 = new QLabel(frame_2);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(70, 275, 41, 16));
        label_37->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_38 = new QLabel(frame_2);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(144, 275, 51, 16));
        label_38->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_39 = new QLabel(frame_2);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(280, 288, 151, 16));
        label_39->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_40 = new QLabel(frame_2);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(210, 288, 66, 16));
        label_40->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_41 = new QLabel(frame_2);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(5, 288, 41, 16));
        label_41->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_42 = new QLabel(frame_2);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(70, 288, 41, 16));
        label_42->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_43 = new QLabel(frame_2);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(144, 288, 51, 16));
        label_43->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_44 = new QLabel(frame_2);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(328, 300, 91, 16));
        label_44->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_45 = new QLabel(frame_2);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(8, 300, 41, 16));
        label_45->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_46 = new QLabel(frame_2);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(117, 300, 41, 16));
        label_46->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_47 = new QLabel(frame_2);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(243, 300, 51, 16));
        label_47->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        frame_3 = new QFrame(frame);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(4, 327, 1016, 329));
        frame_3->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        qwtPlot_2 = new QwtPlot(frame_3);
        qwtPlot_2->setObjectName(QString::fromUtf8("qwtPlot_2"));
        qwtPlot_2->setGeometry(QRect(13, 33, 971, 151));
        label_48 = new QLabel(frame_3);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(5, 194, 51, 16));
        label_48->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_49 = new QLabel(frame_3);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(70, 194, 41, 16));
        label_49->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_50 = new QLabel(frame_3);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(144, 194, 51, 16));
        label_50->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_51 = new QLabel(frame_3);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(210, 194, 66, 16));
        label_51->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_52 = new QLabel(frame_3);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(280, 194, 151, 16));
        label_52->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_53 = new QLabel(frame_3);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(280, 207, 151, 16));
        label_53->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_54 = new QLabel(frame_3);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(5, 207, 51, 16));
        label_54->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_55 = new QLabel(frame_3);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(210, 207, 66, 16));
        label_55->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_56 = new QLabel(frame_3);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(70, 207, 41, 16));
        label_56->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_57 = new QLabel(frame_3);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(144, 207, 51, 16));
        label_57->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_58 = new QLabel(frame_3);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(280, 220, 151, 16));
        label_58->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_59 = new QLabel(frame_3);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(144, 220, 51, 16));
        label_59->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_60 = new QLabel(frame_3);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(5, 220, 51, 16));
        label_60->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_61 = new QLabel(frame_3);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(210, 220, 66, 16));
        label_61->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_62 = new QLabel(frame_3);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(70, 220, 41, 16));
        label_62->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_63 = new QLabel(frame_3);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(280, 234, 151, 16));
        label_63->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_64 = new QLabel(frame_3);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(210, 234, 66, 16));
        label_64->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_65 = new QLabel(frame_3);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(144, 234, 51, 16));
        label_65->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_66 = new QLabel(frame_3);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(70, 234, 41, 16));
        label_66->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_67 = new QLabel(frame_3);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(5, 234, 51, 16));
        label_67->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_68 = new QLabel(frame_3);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(280, 247, 151, 16));
        label_68->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_69 = new QLabel(frame_3);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(70, 247, 41, 16));
        label_69->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_70 = new QLabel(frame_3);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(5, 247, 51, 16));
        label_70->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_71 = new QLabel(frame_3);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(144, 247, 51, 16));
        label_71->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_72 = new QLabel(frame_3);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(210, 247, 66, 16));
        label_72->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_73 = new QLabel(frame_3);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(280, 262, 151, 16));
        label_73->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_74 = new QLabel(frame_3);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(144, 262, 51, 16));
        label_74->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_75 = new QLabel(frame_3);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(210, 262, 66, 16));
        label_75->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_76 = new QLabel(frame_3);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(5, 262, 51, 16));
        label_76->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_77 = new QLabel(frame_3);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(70, 262, 41, 16));
        label_77->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_78 = new QLabel(frame_3);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(280, 275, 151, 16));
        label_78->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_79 = new QLabel(frame_3);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(5, 275, 51, 16));
        label_79->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_80 = new QLabel(frame_3);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(210, 275, 66, 16));
        label_80->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_81 = new QLabel(frame_3);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(70, 275, 41, 16));
        label_81->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_82 = new QLabel(frame_3);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(144, 275, 51, 16));
        label_82->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_83 = new QLabel(frame_3);
        label_83->setObjectName(QString::fromUtf8("label_83"));
        label_83->setGeometry(QRect(280, 288, 151, 16));
        label_83->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_84 = new QLabel(frame_3);
        label_84->setObjectName(QString::fromUtf8("label_84"));
        label_84->setGeometry(QRect(210, 288, 66, 16));
        label_84->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_85 = new QLabel(frame_3);
        label_85->setObjectName(QString::fromUtf8("label_85"));
        label_85->setGeometry(QRect(5, 288, 51, 16));
        label_85->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_86 = new QLabel(frame_3);
        label_86->setObjectName(QString::fromUtf8("label_86"));
        label_86->setGeometry(QRect(70, 288, 41, 16));
        label_86->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_87 = new QLabel(frame_3);
        label_87->setObjectName(QString::fromUtf8("label_87"));
        label_87->setGeometry(QRect(144, 288, 51, 16));
        label_87->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 0);"));
        label_88 = new QLabel(frame_3);
        label_88->setObjectName(QString::fromUtf8("label_88"));
        label_88->setGeometry(QRect(328, 300, 81, 16));
        label_88->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_89 = new QLabel(frame_3);
        label_89->setObjectName(QString::fromUtf8("label_89"));
        label_89->setGeometry(QRect(8, 300, 41, 16));
        label_89->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_90 = new QLabel(frame_3);
        label_90->setObjectName(QString::fromUtf8("label_90"));
        label_90->setGeometry(QRect(117, 300, 41, 16));
        label_90->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_91 = new QLabel(frame_3);
        label_91->setObjectName(QString::fromUtf8("label_91"));
        label_91->setGeometry(QRect(243, 300, 51, 16));
        label_91->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        pushButton_6 = new QPushButton(frame_3);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(463, 1, 99, 29));
        pushButton_6->setFont(font);
        pushButton_7 = new QPushButton(frame_3);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(364, 1, 96, 29));
        pushButton_7->setFont(font);
        label_3 = new QLabel(frame_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(58, 5, 91, 21));
        label_3->setFont(font1);
        pushButton_12 = new QPushButton(frame_3);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(155, 1, 96, 29));
        QFont font2;
        font2.setPointSize(19);
        font2.setBold(true);
        font2.setWeight(75);
        pushButton_12->setFont(font2);
        pushButton_12->setStyleSheet(QString::fromUtf8("color: rgb(28, 12, 255);"));
        pushButton_9 = new QPushButton(frame_3);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(664, 1, 99, 29));
        pushButton_9->setFont(font);
        pushButton_13 = new QPushButton(frame_3);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(259, 1, 99, 29));
        pushButton_13->setFont(font2);
        pushButton_13->setStyleSheet(QString::fromUtf8("color: rgb(28, 12, 255);"));
        pushButton_8 = new QPushButton(frame_3);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(564, 1, 99, 29));
        pushButton_8->setFont(font);
        pushButton_14 = new QPushButton(frame_3);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(878, 1, 99, 29));
        pushButton_14->setFont(font2);
        pushButton_14->setStyleSheet(QString::fromUtf8("color: rgb(28, 12, 255);"));
        pushButton_15 = new QPushButton(frame_3);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(771, 1, 96, 29));
        pushButton_15->setFont(font2);
        pushButton_15->setStyleSheet(QString::fromUtf8("color: rgb(28, 12, 255);"));

        retranslateUi(E1);

        QMetaObject::connectSlotsByName(E1);
    } // setupUi

    void retranslateUi(QWidget *E1)
    {
        E1->setWindowTitle(QApplication::translate("E1", "Form", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("E1", "RESTABLECER", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("E1", "MINUTO", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("E1", "10 MINUTO", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("E1", "TIEMPO REAL", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("E1", "RPM", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("E1", "VALOR SELECCIONADO N25", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("E1", "VALOR SELECCIONADO N2D", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("E1", "RPM", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("E1", "T48SEL", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("E1", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("E1", "T3SEL", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("E1", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("E1", "T25SEL", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("E1", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("E1", "CONVERCION DE PRES", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("E1", "PSIA/BARA", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("E1", "SELECCION DE PRES", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("E1", "PSIA/BARA", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("E1", "CONVERCI\303\223N DE PRES", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("E1", "PSIA/BARA", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("E1", "DESCRIPCION", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("E1", "VALOR", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("E1", "RANGO", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("E1", "UNIDADES", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("E1", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("E1", "RPM", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("E1", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("E1", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("E1", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("E1", "RPM", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_57->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("E1", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_60->setText(QApplication::translate("E1", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("E1", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_62->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_63->setText(QApplication::translate("E1", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_64->setText(QApplication::translate("E1", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_65->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_66->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_67->setText(QApplication::translate("E1", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_68->setText(QApplication::translate("E1", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_69->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_70->setText(QApplication::translate("E1", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_71->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_72->setText(QApplication::translate("E1", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_73->setText(QApplication::translate("E1", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_74->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_75->setText(QApplication::translate("E1", "PSIA/BARA", 0, QApplication::UnicodeUTF8));
        label_76->setText(QApplication::translate("E1", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_77->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_78->setText(QApplication::translate("E1", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_79->setText(QApplication::translate("E1", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_80->setText(QApplication::translate("E1", "PSIA/BARA", 0, QApplication::UnicodeUTF8));
        label_81->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_82->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_83->setText(QApplication::translate("E1", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_84->setText(QApplication::translate("E1", "PSIA/BARA", 0, QApplication::UnicodeUTF8));
        label_85->setText(QApplication::translate("E1", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_86->setText(QApplication::translate("E1", "100.00", 0, QApplication::UnicodeUTF8));
        label_87->setText(QApplication::translate("E1", "1000.00", 0, QApplication::UnicodeUTF8));
        label_88->setText(QApplication::translate("E1", "DESCRIPCION", 0, QApplication::UnicodeUTF8));
        label_89->setText(QApplication::translate("E1", "VALOR", 0, QApplication::UnicodeUTF8));
        label_90->setText(QApplication::translate("E1", "RANGO", 0, QApplication::UnicodeUTF8));
        label_91->setText(QApplication::translate("E1", "UNIDADES", 0, QApplication::UnicodeUTF8));
        pushButton_6->setText(QApplication::translate("E1", "HORA", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("E1", "RESTABLECER", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("E1", "HIST\303\223RICO", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("E1", "<<", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("E1", "FECHA FINAL", 0, QApplication::UnicodeUTF8));
        pushButton_13->setText(QApplication::translate("E1", "<", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("E1", "DIA", 0, QApplication::UnicodeUTF8));
        pushButton_14->setText(QApplication::translate("E1", ">", 0, QApplication::UnicodeUTF8));
        pushButton_15->setText(QApplication::translate("E1", ">>", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class E1: public Ui_E1 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_E1_H
