/********************************************************************************
** Form generated from reading UI file 'lnet_di3.ui'
**
** Created: Wed 9. Oct 20:10:10 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LNET_DI3_H
#define UI_LNET_DI3_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_LNET_DI3
{
public:
    QFrame *frame;
    QLabel *lbNodRTD;
    QFrame *frame_3;
    QLabel *lbLnetT_2;
    QFrame *frame_4;
    QLabel *lbLnetT_3;
    QLabel *lbLnetT;
    QPushButton *btnCerrar;
    QLabel *lbNodeT_1;
    QLabel *lbNumNode_1;
    QLabel *lbNodeU_1;
    QLabel *lbNode_1;
    QLabel *lbNodeU_2;
    QLabel *lbNode_2;
    QLabel *lbNumNode_2;
    QLabel *lbNodeT_2;
    QLabel *lbNumNode_3;
    QLabel *lbNode_3;
    QLabel *lbNodeU_3;
    QLabel *lbNodeT_3;
    QLabel *lbNumNode_4;
    QLabel *lbNodeU_4;
    QLabel *lbNode_4;
    QLabel *lbNodeT_4;
    QLabel *lbNumNode_5;
    QLabel *lbNodeT_5;
    QLabel *lbNode_5;
    QLabel *lbNodeU_5;
    QLabel *lbNodeU_6;
    QLabel *lbNode_6;
    QLabel *lbNodeT_6;
    QLabel *lbNumNode_6;
    QLabel *lbNodeU_7;
    QLabel *lbNodeT_7;
    QLabel *lbNode_7;
    QLabel *lbNumNode_7;
    QLabel *lbNodeU_8;
    QLabel *lbNumNode_8;
    QLabel *lbNode_8;
    QLabel *lbNodeT_8;
    QLabel *lbNumNode_9;
    QLabel *lbNode_9;
    QLabel *lbNodeU_9;
    QLabel *lbNodeT_9;
    QLabel *lbNumNode_10;
    QLabel *lbNodeT_10;
    QLabel *lbNodeU_10;
    QLabel *lbNode_10;
    QLabel *lbNumNode_11;
    QLabel *lbNodeU_11;
    QLabel *lbNodeT_11;
    QLabel *lbNode_11;
    QLabel *lbNumNode_12;
    QLabel *lbNodeT_12;
    QLabel *lbNodeU_12;
    QLabel *lbNode_12;
    QLabel *lbNumNode_13;
    QLabel *lbNodeU_13;
    QLabel *lbNodeT_13;
    QLabel *lbNode_13;
    QLabel *lbNumNode_14;
    QLabel *lbNode_14;
    QLabel *lbNodeT_14;
    QLabel *lbNodeU_14;
    QLabel *lbNumNode_15;
    QLabel *lbNodeU_15;
    QLabel *lbNodeT_15;
    QLabel *lbNode_15;
    QLabel *lbNumNode_16;
    QLabel *lbNodeU_16;
    QLabel *lbNode_16;
    QLabel *lbNodeT_16;

    void setupUi(QWidget *LNET_DI3)
    {
        if (LNET_DI3->objectName().isEmpty())
            LNET_DI3->setObjectName(QString::fromUtf8("LNET_DI3"));
        LNET_DI3->resize(485, 425);
        LNET_DI3->setMinimumSize(QSize(485, 425));
        LNET_DI3->setMaximumSize(QSize(485, 425));
        LNET_DI3->setStyleSheet(QString::fromUtf8("background-color: rgb(128, 128, 128);"));
        frame = new QFrame(LNET_DI3);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 15, 485, 30));
        frame->setStyleSheet(QString::fromUtf8("border-color: rgb(255, 255, 255);"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        lbNodRTD = new QLabel(LNET_DI3);
        lbNodRTD->setObjectName(QString::fromUtf8("lbNodRTD"));
        lbNodRTD->setGeometry(QRect(63, 21, 400, 20));
        QFont font;
        font.setFamily(QString::fromUtf8("Verdana"));
        font.setPointSize(11);
        font.setBold(true);
        font.setWeight(75);
        lbNodRTD->setFont(font);
        lbNodRTD->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        frame_3 = new QFrame(LNET_DI3);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(0, 0, 485, 12));
        frame_3->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frame_3->setFrameShape(QFrame::Panel);
        frame_3->setFrameShadow(QFrame::Raised);
        frame_3->setLineWidth(0);
        lbLnetT_2 = new QLabel(frame_3);
        lbLnetT_2->setObjectName(QString::fromUtf8("lbLnetT_2"));
        lbLnetT_2->setGeometry(QRect(0, 0, 81, 20));
        QFont font1;
        font1.setPointSize(5);
        font1.setBold(true);
        font1.setWeight(75);
        lbLnetT_2->setFont(font1);
        lbLnetT_2->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        frame_4 = new QFrame(frame_3);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(10, 10, 485, 11));
        frame_4->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 71, 134, 255), stop:1 rgba(255, 255, 255, 255));"));
        frame_4->setFrameShape(QFrame::Panel);
        frame_4->setFrameShadow(QFrame::Raised);
        frame_4->setLineWidth(0);
        lbLnetT_3 = new QLabel(frame_4);
        lbLnetT_3->setObjectName(QString::fromUtf8("lbLnetT_3"));
        lbLnetT_3->setGeometry(QRect(0, 0, 81, 20));
        lbLnetT_3->setFont(font1);
        lbLnetT_3->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        lbLnetT = new QLabel(frame_3);
        lbLnetT->setObjectName(QString::fromUtf8("lbLnetT"));
        lbLnetT->setGeometry(QRect(3, 0, 81, 12));
        lbLnetT->setFont(font1);
        lbLnetT->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 105, 160);"));
        btnCerrar = new QPushButton(LNET_DI3);
        btnCerrar->setObjectName(QString::fromUtf8("btnCerrar"));
        btnCerrar->setGeometry(QRect(132, 375, 101, 31));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Verdana"));
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        btnCerrar->setFont(font2);
        btnCerrar->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 208, 200);"));
        lbNodeT_1 = new QLabel(LNET_DI3);
        lbNodeT_1->setObjectName(QString::fromUtf8("lbNodeT_1"));
        lbNodeT_1->setGeometry(QRect(30, 50, 291, 16));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Verdana"));
        font3.setBold(true);
        font3.setWeight(75);
        lbNodeT_1->setFont(font3);
        lbNumNode_1 = new QLabel(LNET_DI3);
        lbNumNode_1->setObjectName(QString::fromUtf8("lbNumNode_1"));
        lbNumNode_1->setGeometry(QRect(8, 50, 21, 16));
        lbNumNode_1->setFont(font3);
        lbNumNode_1->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_1->setAlignment(Qt::AlignCenter);
        lbNodeU_1 = new QLabel(LNET_DI3);
        lbNodeU_1->setObjectName(QString::fromUtf8("lbNodeU_1"));
        lbNodeU_1->setGeometry(QRect(415, 50, 61, 20));
        lbNodeU_1->setFont(font3);
        lbNodeU_1->setLayoutDirection(Qt::RightToLeft);
        lbNode_1 = new QLabel(LNET_DI3);
        lbNode_1->setObjectName(QString::fromUtf8("lbNode_1"));
        lbNode_1->setGeometry(QRect(335, 50, 61, 20));
        lbNode_1->setFont(font3);
        lbNode_1->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_2 = new QLabel(LNET_DI3);
        lbNodeU_2->setObjectName(QString::fromUtf8("lbNodeU_2"));
        lbNodeU_2->setGeometry(QRect(415, 70, 61, 20));
        lbNodeU_2->setFont(font3);
        lbNodeU_2->setLayoutDirection(Qt::RightToLeft);
        lbNode_2 = new QLabel(LNET_DI3);
        lbNode_2->setObjectName(QString::fromUtf8("lbNode_2"));
        lbNode_2->setGeometry(QRect(335, 70, 61, 20));
        lbNode_2->setFont(font3);
        lbNode_2->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_2 = new QLabel(LNET_DI3);
        lbNumNode_2->setObjectName(QString::fromUtf8("lbNumNode_2"));
        lbNumNode_2->setGeometry(QRect(8, 70, 21, 16));
        lbNumNode_2->setFont(font3);
        lbNumNode_2->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_2->setAlignment(Qt::AlignCenter);
        lbNodeT_2 = new QLabel(LNET_DI3);
        lbNodeT_2->setObjectName(QString::fromUtf8("lbNodeT_2"));
        lbNodeT_2->setGeometry(QRect(30, 70, 291, 16));
        lbNodeT_2->setFont(font3);
        lbNumNode_3 = new QLabel(LNET_DI3);
        lbNumNode_3->setObjectName(QString::fromUtf8("lbNumNode_3"));
        lbNumNode_3->setGeometry(QRect(8, 90, 21, 16));
        lbNumNode_3->setFont(font3);
        lbNumNode_3->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_3->setAlignment(Qt::AlignCenter);
        lbNode_3 = new QLabel(LNET_DI3);
        lbNode_3->setObjectName(QString::fromUtf8("lbNode_3"));
        lbNode_3->setGeometry(QRect(335, 90, 61, 20));
        lbNode_3->setFont(font3);
        lbNode_3->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_3 = new QLabel(LNET_DI3);
        lbNodeU_3->setObjectName(QString::fromUtf8("lbNodeU_3"));
        lbNodeU_3->setGeometry(QRect(415, 90, 61, 20));
        lbNodeU_3->setFont(font3);
        lbNodeU_3->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_3 = new QLabel(LNET_DI3);
        lbNodeT_3->setObjectName(QString::fromUtf8("lbNodeT_3"));
        lbNodeT_3->setGeometry(QRect(30, 90, 291, 16));
        lbNodeT_3->setFont(font3);
        lbNumNode_4 = new QLabel(LNET_DI3);
        lbNumNode_4->setObjectName(QString::fromUtf8("lbNumNode_4"));
        lbNumNode_4->setGeometry(QRect(8, 110, 21, 16));
        lbNumNode_4->setFont(font3);
        lbNumNode_4->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_4->setAlignment(Qt::AlignCenter);
        lbNodeU_4 = new QLabel(LNET_DI3);
        lbNodeU_4->setObjectName(QString::fromUtf8("lbNodeU_4"));
        lbNodeU_4->setGeometry(QRect(415, 110, 61, 20));
        lbNodeU_4->setFont(font3);
        lbNodeU_4->setLayoutDirection(Qt::RightToLeft);
        lbNode_4 = new QLabel(LNET_DI3);
        lbNode_4->setObjectName(QString::fromUtf8("lbNode_4"));
        lbNode_4->setGeometry(QRect(335, 110, 61, 20));
        lbNode_4->setFont(font3);
        lbNode_4->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_4 = new QLabel(LNET_DI3);
        lbNodeT_4->setObjectName(QString::fromUtf8("lbNodeT_4"));
        lbNodeT_4->setGeometry(QRect(30, 110, 291, 16));
        lbNodeT_4->setFont(font3);
        lbNumNode_5 = new QLabel(LNET_DI3);
        lbNumNode_5->setObjectName(QString::fromUtf8("lbNumNode_5"));
        lbNumNode_5->setGeometry(QRect(8, 130, 21, 16));
        lbNumNode_5->setFont(font3);
        lbNumNode_5->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_5->setAlignment(Qt::AlignCenter);
        lbNodeT_5 = new QLabel(LNET_DI3);
        lbNodeT_5->setObjectName(QString::fromUtf8("lbNodeT_5"));
        lbNodeT_5->setGeometry(QRect(30, 130, 291, 16));
        lbNodeT_5->setFont(font3);
        lbNode_5 = new QLabel(LNET_DI3);
        lbNode_5->setObjectName(QString::fromUtf8("lbNode_5"));
        lbNode_5->setGeometry(QRect(335, 130, 61, 20));
        lbNode_5->setFont(font3);
        lbNode_5->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_5 = new QLabel(LNET_DI3);
        lbNodeU_5->setObjectName(QString::fromUtf8("lbNodeU_5"));
        lbNodeU_5->setGeometry(QRect(415, 130, 61, 20));
        lbNodeU_5->setFont(font3);
        lbNodeU_5->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_6 = new QLabel(LNET_DI3);
        lbNodeU_6->setObjectName(QString::fromUtf8("lbNodeU_6"));
        lbNodeU_6->setGeometry(QRect(415, 150, 61, 20));
        lbNodeU_6->setFont(font3);
        lbNodeU_6->setLayoutDirection(Qt::RightToLeft);
        lbNode_6 = new QLabel(LNET_DI3);
        lbNode_6->setObjectName(QString::fromUtf8("lbNode_6"));
        lbNode_6->setGeometry(QRect(335, 150, 61, 20));
        lbNode_6->setFont(font3);
        lbNode_6->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_6 = new QLabel(LNET_DI3);
        lbNodeT_6->setObjectName(QString::fromUtf8("lbNodeT_6"));
        lbNodeT_6->setGeometry(QRect(30, 150, 291, 16));
        lbNodeT_6->setFont(font3);
        lbNumNode_6 = new QLabel(LNET_DI3);
        lbNumNode_6->setObjectName(QString::fromUtf8("lbNumNode_6"));
        lbNumNode_6->setGeometry(QRect(8, 150, 21, 16));
        lbNumNode_6->setFont(font3);
        lbNumNode_6->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_6->setAlignment(Qt::AlignCenter);
        lbNodeU_7 = new QLabel(LNET_DI3);
        lbNodeU_7->setObjectName(QString::fromUtf8("lbNodeU_7"));
        lbNodeU_7->setGeometry(QRect(415, 170, 61, 20));
        lbNodeU_7->setFont(font3);
        lbNodeU_7->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_7 = new QLabel(LNET_DI3);
        lbNodeT_7->setObjectName(QString::fromUtf8("lbNodeT_7"));
        lbNodeT_7->setGeometry(QRect(25, 170, 291, 16));
        lbNodeT_7->setFont(font3);
        lbNode_7 = new QLabel(LNET_DI3);
        lbNode_7->setObjectName(QString::fromUtf8("lbNode_7"));
        lbNode_7->setGeometry(QRect(335, 170, 61, 20));
        lbNode_7->setFont(font3);
        lbNode_7->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_7 = new QLabel(LNET_DI3);
        lbNumNode_7->setObjectName(QString::fromUtf8("lbNumNode_7"));
        lbNumNode_7->setGeometry(QRect(8, 170, 21, 16));
        lbNumNode_7->setFont(font3);
        lbNumNode_7->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_7->setAlignment(Qt::AlignCenter);
        lbNodeU_8 = new QLabel(LNET_DI3);
        lbNodeU_8->setObjectName(QString::fromUtf8("lbNodeU_8"));
        lbNodeU_8->setGeometry(QRect(415, 188, 61, 20));
        lbNodeU_8->setFont(font3);
        lbNodeU_8->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_8 = new QLabel(LNET_DI3);
        lbNumNode_8->setObjectName(QString::fromUtf8("lbNumNode_8"));
        lbNumNode_8->setGeometry(QRect(8, 188, 21, 16));
        lbNumNode_8->setFont(font3);
        lbNumNode_8->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_8->setAlignment(Qt::AlignCenter);
        lbNode_8 = new QLabel(LNET_DI3);
        lbNode_8->setObjectName(QString::fromUtf8("lbNode_8"));
        lbNode_8->setGeometry(QRect(335, 188, 61, 20));
        lbNode_8->setFont(font3);
        lbNode_8->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_8 = new QLabel(LNET_DI3);
        lbNodeT_8->setObjectName(QString::fromUtf8("lbNodeT_8"));
        lbNodeT_8->setGeometry(QRect(30, 188, 291, 16));
        lbNodeT_8->setFont(font3);
        lbNumNode_9 = new QLabel(LNET_DI3);
        lbNumNode_9->setObjectName(QString::fromUtf8("lbNumNode_9"));
        lbNumNode_9->setGeometry(QRect(8, 205, 21, 16));
        lbNumNode_9->setFont(font3);
        lbNumNode_9->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_9->setAlignment(Qt::AlignCenter);
        lbNode_9 = new QLabel(LNET_DI3);
        lbNode_9->setObjectName(QString::fromUtf8("lbNode_9"));
        lbNode_9->setGeometry(QRect(335, 205, 61, 20));
        lbNode_9->setFont(font3);
        lbNode_9->setLayoutDirection(Qt::RightToLeft);
        lbNodeU_9 = new QLabel(LNET_DI3);
        lbNodeU_9->setObjectName(QString::fromUtf8("lbNodeU_9"));
        lbNodeU_9->setGeometry(QRect(415, 205, 61, 20));
        lbNodeU_9->setFont(font3);
        lbNodeU_9->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_9 = new QLabel(LNET_DI3);
        lbNodeT_9->setObjectName(QString::fromUtf8("lbNodeT_9"));
        lbNodeT_9->setGeometry(QRect(30, 205, 291, 16));
        lbNodeT_9->setFont(font3);
        lbNumNode_10 = new QLabel(LNET_DI3);
        lbNumNode_10->setObjectName(QString::fromUtf8("lbNumNode_10"));
        lbNumNode_10->setGeometry(QRect(8, 225, 21, 16));
        lbNumNode_10->setFont(font3);
        lbNumNode_10->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_10->setAlignment(Qt::AlignCenter);
        lbNodeT_10 = new QLabel(LNET_DI3);
        lbNodeT_10->setObjectName(QString::fromUtf8("lbNodeT_10"));
        lbNodeT_10->setGeometry(QRect(30, 225, 291, 16));
        lbNodeT_10->setFont(font3);
        lbNodeU_10 = new QLabel(LNET_DI3);
        lbNodeU_10->setObjectName(QString::fromUtf8("lbNodeU_10"));
        lbNodeU_10->setGeometry(QRect(415, 225, 61, 20));
        lbNodeU_10->setFont(font3);
        lbNodeU_10->setLayoutDirection(Qt::RightToLeft);
        lbNode_10 = new QLabel(LNET_DI3);
        lbNode_10->setObjectName(QString::fromUtf8("lbNode_10"));
        lbNode_10->setGeometry(QRect(335, 225, 61, 20));
        lbNode_10->setFont(font3);
        lbNode_10->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_11 = new QLabel(LNET_DI3);
        lbNumNode_11->setObjectName(QString::fromUtf8("lbNumNode_11"));
        lbNumNode_11->setGeometry(QRect(8, 245, 21, 16));
        lbNumNode_11->setFont(font3);
        lbNumNode_11->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_11->setAlignment(Qt::AlignCenter);
        lbNodeU_11 = new QLabel(LNET_DI3);
        lbNodeU_11->setObjectName(QString::fromUtf8("lbNodeU_11"));
        lbNodeU_11->setGeometry(QRect(415, 245, 61, 20));
        lbNodeU_11->setFont(font3);
        lbNodeU_11->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_11 = new QLabel(LNET_DI3);
        lbNodeT_11->setObjectName(QString::fromUtf8("lbNodeT_11"));
        lbNodeT_11->setGeometry(QRect(30, 245, 291, 16));
        lbNodeT_11->setFont(font3);
        lbNode_11 = new QLabel(LNET_DI3);
        lbNode_11->setObjectName(QString::fromUtf8("lbNode_11"));
        lbNode_11->setGeometry(QRect(335, 245, 61, 20));
        lbNode_11->setFont(font3);
        lbNode_11->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_12 = new QLabel(LNET_DI3);
        lbNumNode_12->setObjectName(QString::fromUtf8("lbNumNode_12"));
        lbNumNode_12->setGeometry(QRect(8, 265, 21, 16));
        lbNumNode_12->setFont(font3);
        lbNumNode_12->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_12->setAlignment(Qt::AlignCenter);
        lbNodeT_12 = new QLabel(LNET_DI3);
        lbNodeT_12->setObjectName(QString::fromUtf8("lbNodeT_12"));
        lbNodeT_12->setGeometry(QRect(30, 265, 291, 16));
        lbNodeT_12->setFont(font3);
        lbNodeU_12 = new QLabel(LNET_DI3);
        lbNodeU_12->setObjectName(QString::fromUtf8("lbNodeU_12"));
        lbNodeU_12->setGeometry(QRect(415, 265, 61, 20));
        lbNodeU_12->setFont(font3);
        lbNodeU_12->setLayoutDirection(Qt::RightToLeft);
        lbNode_12 = new QLabel(LNET_DI3);
        lbNode_12->setObjectName(QString::fromUtf8("lbNode_12"));
        lbNode_12->setGeometry(QRect(335, 265, 61, 20));
        lbNode_12->setFont(font3);
        lbNode_12->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_13 = new QLabel(LNET_DI3);
        lbNumNode_13->setObjectName(QString::fromUtf8("lbNumNode_13"));
        lbNumNode_13->setGeometry(QRect(8, 285, 21, 16));
        lbNumNode_13->setFont(font3);
        lbNumNode_13->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_13->setAlignment(Qt::AlignCenter);
        lbNodeU_13 = new QLabel(LNET_DI3);
        lbNodeU_13->setObjectName(QString::fromUtf8("lbNodeU_13"));
        lbNodeU_13->setGeometry(QRect(415, 285, 61, 20));
        lbNodeU_13->setFont(font3);
        lbNodeU_13->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_13 = new QLabel(LNET_DI3);
        lbNodeT_13->setObjectName(QString::fromUtf8("lbNodeT_13"));
        lbNodeT_13->setGeometry(QRect(30, 285, 291, 16));
        lbNodeT_13->setFont(font3);
        lbNode_13 = new QLabel(LNET_DI3);
        lbNode_13->setObjectName(QString::fromUtf8("lbNode_13"));
        lbNode_13->setGeometry(QRect(335, 285, 61, 20));
        lbNode_13->setFont(font3);
        lbNode_13->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_14 = new QLabel(LNET_DI3);
        lbNumNode_14->setObjectName(QString::fromUtf8("lbNumNode_14"));
        lbNumNode_14->setGeometry(QRect(8, 302, 21, 16));
        lbNumNode_14->setFont(font3);
        lbNumNode_14->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_14->setAlignment(Qt::AlignCenter);
        lbNode_14 = new QLabel(LNET_DI3);
        lbNode_14->setObjectName(QString::fromUtf8("lbNode_14"));
        lbNode_14->setGeometry(QRect(335, 302, 61, 20));
        lbNode_14->setFont(font3);
        lbNode_14->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_14 = new QLabel(LNET_DI3);
        lbNodeT_14->setObjectName(QString::fromUtf8("lbNodeT_14"));
        lbNodeT_14->setGeometry(QRect(30, 302, 291, 16));
        lbNodeT_14->setFont(font3);
        lbNodeU_14 = new QLabel(LNET_DI3);
        lbNodeU_14->setObjectName(QString::fromUtf8("lbNodeU_14"));
        lbNodeU_14->setGeometry(QRect(415, 302, 61, 20));
        lbNodeU_14->setFont(font3);
        lbNodeU_14->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_15 = new QLabel(LNET_DI3);
        lbNumNode_15->setObjectName(QString::fromUtf8("lbNumNode_15"));
        lbNumNode_15->setGeometry(QRect(8, 322, 21, 16));
        lbNumNode_15->setFont(font3);
        lbNumNode_15->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_15->setAlignment(Qt::AlignCenter);
        lbNodeU_15 = new QLabel(LNET_DI3);
        lbNodeU_15->setObjectName(QString::fromUtf8("lbNodeU_15"));
        lbNodeU_15->setGeometry(QRect(415, 322, 61, 20));
        lbNodeU_15->setFont(font3);
        lbNodeU_15->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_15 = new QLabel(LNET_DI3);
        lbNodeT_15->setObjectName(QString::fromUtf8("lbNodeT_15"));
        lbNodeT_15->setGeometry(QRect(30, 322, 291, 16));
        lbNodeT_15->setFont(font3);
        lbNode_15 = new QLabel(LNET_DI3);
        lbNode_15->setObjectName(QString::fromUtf8("lbNode_15"));
        lbNode_15->setGeometry(QRect(335, 322, 61, 20));
        lbNode_15->setFont(font3);
        lbNode_15->setLayoutDirection(Qt::RightToLeft);
        lbNumNode_16 = new QLabel(LNET_DI3);
        lbNumNode_16->setObjectName(QString::fromUtf8("lbNumNode_16"));
        lbNumNode_16->setGeometry(QRect(8, 340, 21, 16));
        lbNumNode_16->setFont(font3);
        lbNumNode_16->setStyleSheet(QString::fromUtf8("color: rgb(22, 232, 232);"));
        lbNumNode_16->setAlignment(Qt::AlignCenter);
        lbNodeU_16 = new QLabel(LNET_DI3);
        lbNodeU_16->setObjectName(QString::fromUtf8("lbNodeU_16"));
        lbNodeU_16->setGeometry(QRect(415, 340, 61, 20));
        lbNodeU_16->setFont(font3);
        lbNodeU_16->setLayoutDirection(Qt::RightToLeft);
        lbNode_16 = new QLabel(LNET_DI3);
        lbNode_16->setObjectName(QString::fromUtf8("lbNode_16"));
        lbNode_16->setGeometry(QRect(335, 340, 61, 20));
        lbNode_16->setFont(font3);
        lbNode_16->setLayoutDirection(Qt::RightToLeft);
        lbNodeT_16 = new QLabel(LNET_DI3);
        lbNodeT_16->setObjectName(QString::fromUtf8("lbNodeT_16"));
        lbNodeT_16->setGeometry(QRect(30, 340, 291, 16));
        lbNodeT_16->setFont(font3);

        retranslateUi(LNET_DI3);

        QMetaObject::connectSlotsByName(LNET_DI3);
    } // setupUi

    void retranslateUi(QWidget *LNET_DI3)
    {
        LNET_DI3->setWindowTitle(QApplication::translate("LNET_DI3", "LNET_DI3", 0, QApplication::UnicodeUTF8));
        lbNodRTD->setText(QApplication::translate("LNET_DI3", "NODE - N1N33 - Dl", 0, QApplication::UnicodeUTF8));
        lbLnetT_2->setText(QApplication::translate("LNET_DI3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbLnetT_3->setText(QApplication::translate("LNET_DI3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", 0, QApplication::UnicodeUTF8));
        lbLnetT->setText(QApplication::translate("LNET_DI3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:5pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">LNET_DI.grf</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        btnCerrar->setText(QApplication::translate("LNET_DI3", "CERRAR", 0, QApplication::UnicodeUTF8));
        lbNodeT_1->setText(QApplication::translate("LNET_DI3", "VENT FLUJO AIRE TURB BAJO (VENT A)", 0, QApplication::UnicodeUTF8));
        lbNumNode_1->setText(QApplication::translate("LNET_DI3", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_1->setText(QApplication::translate("LNET_DI3", "NALM", 0, QApplication::UnicodeUTF8));
        lbNode_1->setText(QApplication::translate("LNET_DI3", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_2->setText(QApplication::translate("LNET_DI3", "NALM", 0, QApplication::UnicodeUTF8));
        lbNode_2->setText(QApplication::translate("LNET_DI3", "1", 0, QApplication::UnicodeUTF8));
        lbNumNode_2->setText(QApplication::translate("LNET_DI3", "2", 0, QApplication::UnicodeUTF8));
        lbNodeT_2->setText(QApplication::translate("LNET_DI3", "VENT FLUJO AIRE TURB BAJO (VENT B)", 0, QApplication::UnicodeUTF8));
        lbNumNode_3->setText(QApplication::translate("LNET_DI3", "3", 0, QApplication::UnicodeUTF8));
        lbNode_3->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeU_3->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_3->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumNode_4->setText(QApplication::translate("LNET_DI3", "4", 0, QApplication::UnicodeUTF8));
        lbNodeU_4->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNode_4->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_4->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumNode_5->setText(QApplication::translate("LNET_DI3", "5", 0, QApplication::UnicodeUTF8));
        lbNodeT_5->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_5->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeU_5->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeU_6->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNode_6->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_6->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNumNode_6->setText(QApplication::translate("LNET_DI3", "6", 0, QApplication::UnicodeUTF8));
        lbNodeU_7->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_7->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_7->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_7->setText(QApplication::translate("LNET_DI3", "7", 0, QApplication::UnicodeUTF8));
        lbNodeU_8->setText(QApplication::translate("LNET_DI3", "NALM", 0, QApplication::UnicodeUTF8));
        lbNumNode_8->setText(QApplication::translate("LNET_DI3", "8", 0, QApplication::UnicodeUTF8));
        lbNode_8->setText(QApplication::translate("LNET_DI3", "1", 0, QApplication::UnicodeUTF8));
        lbNodeT_8->setText(QApplication::translate("LNET_DI3", "SUMINISTRO GAS COMB ALTA ALTA PRES", 0, QApplication::UnicodeUTF8));
        lbNumNode_9->setText(QApplication::translate("LNET_DI3", "9", 0, QApplication::UnicodeUTF8));
        lbNode_9->setText(QApplication::translate("LNET_DI3", "1", 0, QApplication::UnicodeUTF8));
        lbNodeU_9->setText(QApplication::translate("LNET_DI3", "NALM", 0, QApplication::UnicodeUTF8));
        lbNodeT_9->setText(QApplication::translate("LNET_DI3", "SUMINISTRO GAS COMB BAJA PRESI\303\223N", 0, QApplication::UnicodeUTF8));
        lbNumNode_10->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_10->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNodeU_10->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNode_10->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_11->setText(QApplication::translate("LNET_DI3", "11", 0, QApplication::UnicodeUTF8));
        lbNodeU_11->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_11->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_11->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_12->setText(QApplication::translate("LNET_DI3", "12", 0, QApplication::UnicodeUTF8));
        lbNodeT_12->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNodeU_12->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNode_12->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_13->setText(QApplication::translate("LNET_DI3", "13", 0, QApplication::UnicodeUTF8));
        lbNodeU_13->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_13->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_13->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_14->setText(QApplication::translate("LNET_DI3", "14", 0, QApplication::UnicodeUTF8));
        lbNode_14->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_14->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNodeU_14->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_15->setText(QApplication::translate("LNET_DI3", "15", 0, QApplication::UnicodeUTF8));
        lbNodeU_15->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_15->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
        lbNode_15->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNumNode_16->setText(QApplication::translate("LNET_DI3", "16", 0, QApplication::UnicodeUTF8));
        lbNodeU_16->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNode_16->setText(QApplication::translate("LNET_DI3", "10", 0, QApplication::UnicodeUTF8));
        lbNodeT_16->setText(QApplication::translate("LNET_DI3", "(REFACCI\303\223N)", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class LNET_DI3: public Ui_LNET_DI3 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LNET_DI3_H
