/********************************************************************************
** Form generated from reading UI file 'e3.ui'
**
** Created: Fri 3. Jan 20:43:14 2014
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_E3_H
#define UI_E3_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include <wlabel.h>
#include "qwt_plot.h"

QT_BEGIN_NAMESPACE

class Ui_E3
{
public:
    QFrame *frame;
    QFrame *frame_2;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_5;
    QwtPlot *qwtPlot;
    WLabel *label_2;
    WLabel *label_4;
    WLabel *label_5;
    WLabel *label_6;
    WLabel *label_7;
    WLabel *label_8;
    WLabel *label_9;
    WLabel *label_10;
    WLabel *label_11;
    WLabel *label_12;
    WLabel *label_13;
    WLabel *label_14;
    WLabel *label_15;
    WLabel *label_16;
    WLabel *label_17;
    WLabel *label_18;
    WLabel *label_19;
    WLabel *label_20;
    WLabel *label_21;
    WLabel *label_22;
    WLabel *label_23;
    WLabel *label_24;
    WLabel *label_25;
    WLabel *label_26;
    WLabel *label_27;
    WLabel *label_28;
    WLabel *label_29;
    WLabel *label_30;
    WLabel *label_31;
    WLabel *label_32;
    WLabel *label_33;
    WLabel *label_44;
    WLabel *label_45;
    WLabel *label_46;
    WLabel *label_47;
    QFrame *frame_3;
    QwtPlot *qwtPlot_2;
    WLabel *label_48;
    WLabel *label_49;
    WLabel *label_50;
    WLabel *label_51;
    WLabel *label_52;
    WLabel *label_53;
    WLabel *label_54;
    WLabel *label_55;
    WLabel *label_56;
    WLabel *label_57;
    WLabel *label_58;
    WLabel *label_59;
    WLabel *label_60;
    WLabel *label_61;
    WLabel *label_62;
    WLabel *label_63;
    WLabel *label_64;
    WLabel *label_65;
    WLabel *label_66;
    WLabel *label_67;
    WLabel *label_68;
    WLabel *label_69;
    WLabel *label_70;
    WLabel *label_71;
    WLabel *label_72;
    WLabel *label_73;
    WLabel *label_74;
    WLabel *label_75;
    WLabel *label_76;
    WLabel *label_77;
    WLabel *label_88;
    WLabel *label_89;
    WLabel *label_90;
    WLabel *label_91;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    WLabel *label_3;
    QPushButton *pushButton_12;
    QPushButton *pushButton_9;
    QPushButton *pushButton_13;
    QPushButton *pushButton_8;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;

    void setupUi(QWidget *E3)
    {
        if (E3->objectName().isEmpty())
            E3->setObjectName(QString::fromUtf8("E3"));
        E3->resize(1024, 662);
        E3->setMinimumSize(QSize(1024, 662));
        E3->setMaximumSize(QSize(1024, 662));
        frame = new QFrame(E3);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 0, 1024, 662));
        frame->setMinimumSize(QSize(1024, 662));
        frame->setMaximumSize(QSize(1024, 662));
        frame->setStyleSheet(QString::fromUtf8("background-color: rgb(227, 227, 228);"));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame_2 = new QFrame(frame);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(4, 4, 1016, 316));
        frame_2->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        pushButton = new QPushButton(frame_2);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(356, 3, 99, 29));
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        pushButton->setFont(font);
        pushButton_2 = new QPushButton(frame_2);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(456, 3, 99, 29));
        pushButton_2->setFont(font);
        pushButton_5 = new QPushButton(frame_2);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(557, 3, 99, 29));
        pushButton_5->setFont(font);
        qwtPlot = new QwtPlot(frame_2);
        qwtPlot->setObjectName(QString::fromUtf8("qwtPlot"));
        qwtPlot->setGeometry(QRect(7, 34, 971, 180));
        label_2 = new WLabel(frame_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(54, 12, 151, 21));
        QFont font1;
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        label_2->setFont(font1);
        label_4 = new WLabel(frame_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(5, 212, 41, 16));
        label_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_5 = new WLabel(frame_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(70, 212, 41, 16));
        label_5->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_6 = new WLabel(frame_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(144, 212, 51, 16));
        label_6->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_7 = new WLabel(frame_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(210, 212, 66, 16));
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_8 = new WLabel(frame_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(280, 212, 151, 16));
        label_8->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_9 = new WLabel(frame_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(280, 225, 151, 16));
        label_9->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_10 = new WLabel(frame_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(5, 225, 41, 16));
        label_10->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_11 = new WLabel(frame_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(210, 225, 66, 16));
        label_11->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_12 = new WLabel(frame_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(70, 225, 41, 16));
        label_12->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_13 = new WLabel(frame_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(144, 225, 51, 16));
        label_13->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_14 = new WLabel(frame_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(280, 238, 151, 16));
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_15 = new WLabel(frame_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(144, 238, 51, 16));
        label_15->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_16 = new WLabel(frame_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(5, 238, 41, 16));
        label_16->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_17 = new WLabel(frame_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(210, 238, 66, 16));
        label_17->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_18 = new WLabel(frame_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(70, 238, 41, 16));
        label_18->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_19 = new WLabel(frame_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(280, 252, 151, 16));
        label_19->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_20 = new WLabel(frame_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(210, 252, 66, 16));
        label_20->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_21 = new WLabel(frame_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(144, 252, 51, 16));
        label_21->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_22 = new WLabel(frame_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(70, 252, 41, 16));
        label_22->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_23 = new WLabel(frame_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(5, 252, 41, 16));
        label_23->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_24 = new WLabel(frame_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(280, 265, 151, 16));
        label_24->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_25 = new WLabel(frame_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(70, 265, 41, 16));
        label_25->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_26 = new WLabel(frame_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(5, 265, 41, 16));
        label_26->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_27 = new WLabel(frame_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(144, 265, 51, 16));
        label_27->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_28 = new WLabel(frame_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(210, 265, 66, 16));
        label_28->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_29 = new WLabel(frame_2);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(280, 280, 151, 16));
        label_29->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_30 = new WLabel(frame_2);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(144, 280, 51, 16));
        label_30->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_31 = new WLabel(frame_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(210, 280, 66, 16));
        label_31->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_32 = new WLabel(frame_2);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(5, 280, 41, 16));
        label_32->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_33 = new WLabel(frame_2);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(70, 280, 41, 16));
        label_33->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_44 = new WLabel(frame_2);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(328, 300, 91, 16));
        label_44->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_45 = new WLabel(frame_2);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(8, 300, 41, 16));
        label_45->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_46 = new WLabel(frame_2);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(117, 300, 41, 16));
        label_46->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_47 = new WLabel(frame_2);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(243, 300, 51, 16));
        label_47->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        frame_3 = new QFrame(frame);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(4, 327, 1016, 329));
        frame_3->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 192, 192);"));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        qwtPlot_2 = new QwtPlot(frame_3);
        qwtPlot_2->setObjectName(QString::fromUtf8("qwtPlot_2"));
        qwtPlot_2->setGeometry(QRect(13, 33, 971, 180));
        label_48 = new WLabel(frame_3);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(5, 212, 51, 16));
        label_48->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_49 = new WLabel(frame_3);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(70, 212, 41, 16));
        label_49->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_50 = new WLabel(frame_3);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(144, 212, 51, 16));
        label_50->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_51 = new WLabel(frame_3);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(210, 212, 66, 16));
        label_51->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_52 = new WLabel(frame_3);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(280, 212, 151, 16));
        label_52->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_53 = new WLabel(frame_3);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(280, 225, 151, 16));
        label_53->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_54 = new WLabel(frame_3);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(5, 225, 51, 16));
        label_54->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_55 = new WLabel(frame_3);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(210, 225, 66, 16));
        label_55->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_56 = new WLabel(frame_3);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(70, 225, 41, 16));
        label_56->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_57 = new WLabel(frame_3);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(144, 225, 51, 16));
        label_57->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 255);"));
        label_58 = new WLabel(frame_3);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(280, 238, 151, 16));
        label_58->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_59 = new WLabel(frame_3);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(144, 238, 51, 16));
        label_59->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_60 = new WLabel(frame_3);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(5, 238, 51, 16));
        label_60->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_61 = new WLabel(frame_3);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(210, 238, 66, 16));
        label_61->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_62 = new WLabel(frame_3);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(70, 238, 41, 16));
        label_62->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);"));
        label_63 = new WLabel(frame_3);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(280, 252, 151, 16));
        label_63->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_64 = new WLabel(frame_3);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(210, 252, 66, 16));
        label_64->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_65 = new WLabel(frame_3);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(144, 252, 51, 16));
        label_65->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_66 = new WLabel(frame_3);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(70, 252, 41, 16));
        label_66->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_67 = new WLabel(frame_3);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(5, 252, 51, 16));
        label_67->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 255);"));
        label_68 = new WLabel(frame_3);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(280, 265, 151, 16));
        label_68->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_69 = new WLabel(frame_3);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(70, 265, 41, 16));
        label_69->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_70 = new WLabel(frame_3);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(5, 265, 51, 16));
        label_70->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_71 = new WLabel(frame_3);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(144, 265, 51, 16));
        label_71->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_72 = new WLabel(frame_3);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(210, 265, 66, 16));
        label_72->setStyleSheet(QString::fromUtf8("color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 127);"));
        label_73 = new WLabel(frame_3);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(280, 280, 151, 16));
        label_73->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_74 = new WLabel(frame_3);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(144, 280, 51, 16));
        label_74->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_75 = new WLabel(frame_3);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(210, 280, 66, 16));
        label_75->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_76 = new WLabel(frame_3);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(5, 280, 51, 16));
        label_76->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_77 = new WLabel(frame_3);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(70, 280, 41, 16));
        label_77->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 0);"));
        label_88 = new WLabel(frame_3);
        label_88->setObjectName(QString::fromUtf8("label_88"));
        label_88->setGeometry(QRect(328, 300, 81, 16));
        label_88->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_89 = new WLabel(frame_3);
        label_89->setObjectName(QString::fromUtf8("label_89"));
        label_89->setGeometry(QRect(8, 300, 41, 16));
        label_89->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_90 = new WLabel(frame_3);
        label_90->setObjectName(QString::fromUtf8("label_90"));
        label_90->setGeometry(QRect(117, 300, 41, 16));
        label_90->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        label_91 = new WLabel(frame_3);
        label_91->setObjectName(QString::fromUtf8("label_91"));
        label_91->setGeometry(QRect(243, 300, 51, 16));
        label_91->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        pushButton_6 = new QPushButton(frame_3);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(463, 1, 99, 29));
        pushButton_6->setFont(font);
        pushButton_7 = new QPushButton(frame_3);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(364, 1, 96, 29));
        pushButton_7->setFont(font);
        label_3 = new WLabel(frame_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(58, 5, 91, 21));
        label_3->setFont(font1);
        pushButton_12 = new QPushButton(frame_3);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(155, 1, 96, 29));
        QFont font2;
        font2.setPointSize(19);
        font2.setBold(true);
        font2.setWeight(75);
        pushButton_12->setFont(font2);
        pushButton_12->setStyleSheet(QString::fromUtf8("color: rgb(28, 12, 255);"));
        pushButton_9 = new QPushButton(frame_3);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(664, 1, 99, 29));
        pushButton_9->setFont(font);
        pushButton_13 = new QPushButton(frame_3);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(259, 1, 99, 29));
        pushButton_13->setFont(font2);
        pushButton_13->setStyleSheet(QString::fromUtf8("color: rgb(28, 12, 255);"));
        pushButton_8 = new QPushButton(frame_3);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(564, 1, 99, 29));
        pushButton_8->setFont(font);
        pushButton_14 = new QPushButton(frame_3);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(878, 1, 99, 29));
        pushButton_14->setFont(font2);
        pushButton_14->setStyleSheet(QString::fromUtf8("color: rgb(28, 12, 255);"));
        pushButton_15 = new QPushButton(frame_3);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(771, 1, 96, 29));
        pushButton_15->setFont(font2);
        pushButton_15->setStyleSheet(QString::fromUtf8("color: rgb(28, 12, 255);"));

        retranslateUi(E3);

        QMetaObject::connectSlotsByName(E3);
    } // setupUi

    void retranslateUi(QWidget *E3)
    {
        E3->setWindowTitle(QApplication::translate("E3", "Form", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("E3", "RESTABLECER", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("E3", "MINUTO", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("E3", "10 MINUTO", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("E3", "TIEMPO REAL", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("E3", "TLUBSEL", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("E3", "TAGBSEL", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("E3", "TGBBSEL", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("E3", "TGBCSEL", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("E3", "TGBDSEL", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("E3", "TGBESEL", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("E3", "DESCRIPCION", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("E3", "VALOR", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("E3", "RANGO", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("E3", "UNIDADES", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("E3", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("E3", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("E3", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("E3", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_57->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("E3", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_60->setText(QApplication::translate("E3", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_62->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_63->setText(QApplication::translate("E3", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_64->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_65->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_66->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_67->setText(QApplication::translate("E3", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_68->setText(QApplication::translate("E3", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_69->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_70->setText(QApplication::translate("E3", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_71->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_72->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_73->setText(QApplication::translate("E3", "DESCRIPTION", 0, QApplication::UnicodeUTF8));
        label_74->setText(QApplication::translate("E3", "1000.00", 0, QApplication::UnicodeUTF8));
        label_75->setText(QApplication::translate("E3", "DEG F/C", 0, QApplication::UnicodeUTF8));
        label_76->setText(QApplication::translate("E3", "<NO DATA>", 0, QApplication::UnicodeUTF8));
        label_77->setText(QApplication::translate("E3", "100.00", 0, QApplication::UnicodeUTF8));
        label_88->setText(QApplication::translate("E3", "DESCRIPCION", 0, QApplication::UnicodeUTF8));
        label_89->setText(QApplication::translate("E3", "VALOR", 0, QApplication::UnicodeUTF8));
        label_90->setText(QApplication::translate("E3", "RANGO", 0, QApplication::UnicodeUTF8));
        label_91->setText(QApplication::translate("E3", "UNIDADES", 0, QApplication::UnicodeUTF8));
        pushButton_6->setText(QApplication::translate("E3", "HORA", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("E3", "RESTABLECER", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("E3", "HIST\303\223RICO", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("E3", "<<", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("E3", "FECHA FINAL", 0, QApplication::UnicodeUTF8));
        pushButton_13->setText(QApplication::translate("E3", "<", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("E3", "DIA", 0, QApplication::UnicodeUTF8));
        pushButton_14->setText(QApplication::translate("E3", ">", 0, QApplication::UnicodeUTF8));
        pushButton_15->setText(QApplication::translate("E3", ">>", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class E3: public Ui_E3 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_E3_H
